### ISSUE TITLE
Unable to convert model

### ISSUE THREAD

**Issue by garyhighlinebeta** [bmaltais/kohya_ss#1020]
In the utility tab, I cannot use "convert model"

I tried different things for source model "path to source model folder of file to convert"

but keep getting similar error like this:

`06:48:15-131454 INFO     The provided model is a folder                                                                      
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/workspace/kohya_ss/library/convert_model_gui.py", line 47, in convert_model
    msgbox('The provided target folder does not exist')
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/derived_boxes.py", line 230, in msgbox
    return buttonbox(msg=msg,
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 95, in buttonbox
    bb = ButtonBox(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 147, in __init__
    self.ui = GUItk(msg, title, choices, images, default_choice, cancel_choice, self.callback_ui)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 263, in __init__
    self.boxRoot = tk.Tk()
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable`

or 

`06:48:43-691080 INFO     The provided source model is a file                                                                 
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/workspace/kohya_ss/library/convert_model_gui.py", line 47, in convert_model
    msgbox('The provided target folder does not exist')
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/derived_boxes.py", line 230, in msgbox
    return buttonbox(msg=msg,
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 95, in buttonbox
    bb = ButtonBox(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 147, in __init__
    self.ui = GUItk(msg, title, choices, images, default_choice, cancel_choice, self.callback_ui)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 263, in __init__
    self.boxRoot = tk.Tk()
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable`

**Comment by bmaltais** [comment]
I just tried ti with:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/c1234d50-cded-4090-b2ea-1550aed73425)

and it worked fine:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/8341ba2a-afef-47c7-bd1d-435870779cca)

**Comment by dcsan** [comment]
https://github.com/bmaltais/kohya_ss/issues/760
related no $DISPLAY environment variable

**Comment by bmaltais** [comment]
Oh... I have never tested on headless environments... If you find the solution let me know and I will see if I can integrate it.

**Comment by garyhighlinebeta** [comment]
@dcsan did you find a solution? This is how I start my kohya on a server

`cd /workspace/kohya_ss
source venv/bin/activate
fuser -k 3010/tcp
./gui.sh --listen 0.0.0.0 --server_port 3010 --share`

**Comment by kieranxsomer** [comment]
> Oh... I have never tested on headless environments... If you find the solution let me know and I will see if I can integrate it.

At the moment it's when we get stuck on the TRAIN model page, i can get to tagging all of my images and everything.
I can't train on a local machine, because AMD and only 8gb Vram (and amd lmao) 
So i've relied on Vast and Runpod XD -- Runpod to me is OK but buggy so i swaped to vast recently.

**Comment by kieranxsomer** [comment]
> @dcsan did you find a solution? This is how I start my kohya on a server
> 
> ```
> cd /workspace/kohya_ss
> 
> source venv/bin/activate
> 
> fuser -k 3010/tcp
> 
> ./gui.sh --listen 0.0.0.0 --server_port 3010 --share
> ```

Also a lot of the time when starting on vast with a STRAIGHT python template?
i've had to install a previous torch vision, get teh matching xformers..

I think tehre's a matlib error i get that's fixable i forgot the error to.
Usually it does localhost 127.whatever the heck the numbers are ...

and yea i've been doing share.

Maybe i just stick for now to doing gui-less training lol
