### ISSUE TITLE
Error training a textual inversion on runpod

### ISSUE THREAD

**Issue by anto18671** [bmaltais/kohya_ss#1026]
21:13:35-353463 INFO     Start training TI...                                                                                                                                                                                 
21:13:35-358366 ERROR    The following folders do not match the required pattern <number>_<text>: /workspace/output/img/.ipynb_checkpoints                                                                                    
21:13:35-361143 ERROR    Please follow the folder structure documentation found at docs\image_folder_structure.md ...                                                                                                         
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/workspace/kohya_ss/textual_inversion_gui.py", line 459, in train_model
    repeats = int(folder.split('_')[0])
ValueError: invalid literal for int() with base 10: '.ipynb'

I used /workspace/output/img has path for image and my files are at /workspace/output/img/10_MegaStructureV1

I used Furkan Gozukara Tutorial For How To Install Kohya LoRA- Web UI On RunPod

**Comment by anto18671** [comment]
@FurkanGozukara @bmaltais Can you help ?

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara @bmaltais Can you help ?

Why do you waste time with textual inversion on runpod

That is the worst trainer

**Comment by bmaltais** [comment]
Kohya_ss has not put much love into that one. He slapped it together but it never got any significant attention after... I was considering dropping it from the GUI.
