### ISSUE TITLE
Multiple traceback errors when running BLIP Captioning

### ISSUE THREAD

**Issue by xathian** [bmaltais/kohya_ss#1050]
```
Captioning files in H:/tmp/AngTrain...
./venv/Scripts/python.exe "finetune/make_captions.py" --batch_size="2" --num_beams="1" --top_p="0.9" --max_length="75" --min_length="5" --beam_search --caption_extension=".txt" "H:/tmp/AngTrain" --caption_weights="https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth"
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Current Working Directory is:  E:\Programs\Kohya\kohya_ss
load images from H:\tmp\AngTrain
found 35 images.
loading BLIP caption: https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth
Traceback (most recent call last):
  File "E:\Programs\Kohya\kohya_ss\finetune\make_captions.py", line 198, in <module>
    main(args)
  File "E:\Programs\Kohya\kohya_ss\finetune\make_captions.py", line 84, in main
    model = blip_decoder(pretrained=args.caption_weights, image_size=IMAGE_SIZE, vit="large", med_config="./blip/med_config.json")
  File "E:\Programs\Kohya\kohya_ss\finetune\blip\blip.py", line 175, in blip_decoder
    model = BLIP_Decoder(**kwargs)
  File "E:\Programs\Kohya\kohya_ss\finetune\blip\blip.py", line 98, in __init__
    self.tokenizer = init_tokenizer()
  File "E:\Programs\Kohya\kohya_ss\finetune\blip\blip.py", line 189, in init_tokenizer
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
  File "E:\Programs\Kohya\kohya_ss\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1763, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "E:\Programs\Kohya\kohya_ss\venv\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "E:\Programs\Kohya\kohya_ss\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\Programs\Kohya\kohya_ss\venv\lib\site-packages\huggingface_hub\file_download.py", line 1296, in hf_hub_download
    with FileLock(lock_path):
  File "E:\Programs\Kohya\kohya_ss\venv\lib\site-packages\filelock\_api.py", line 255, in __enter__
    self.acquire()
  File "E:\Programs\Kohya\kohya_ss\venv\lib\site-packages\filelock\_api.py", line 213, in acquire
    self._acquire()
  File "E:\Programs\Kohya\kohya_ss\venv\lib\site-packages\filelock\_windows.py", line 27, in _acquire
    fd = os.open(self.lock_file, flags, self._context.mode)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Xathian/.cache\\huggingface\\hub\\models--bert-base-uncased\\blobs\\W/"fb140275c155a9c7c5a3b3e0e77a9e839594a938.lock'
...captioning done
```

Nothing actually captions.

**Comment by bmaltais** [comment]
I really don't get what the issue is. I just re-installed my who environment using the latest setup.bat and used torch 2 and all is working...

Are you on Windows or Linux?
