### ISSUE TITLE
No module named tkinter

### ISSUE THREAD

**Issue by cshadd** [bmaltais/kohya_ss#1128]
I have installed everything correctly, but I am getting this error when running the gui.bat

```shell
21:17:58-617439 INFO     Version: v21.7.16
21:17:58-617439 INFO     nVidia toolkit detected
21:18:00-679888 INFO     Torch 2.0.1+cu118
21:18:00-711140 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
21:18:00-711140 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12287 Arch (8, 6) Cores 28
21:18:00-711140 INFO     Verifying modules instalation status from requirements_windows_torch2.txt...
21:18:00-711140 INFO     Verifying modules instalation status from requirements.txt...
Traceback (most recent call last):
  File "D:\kohya_ss\kohya_gui.py", line 4, in <module>
    from dreambooth_gui import dreambooth_tab
  File "D:\kohya_ss\dreambooth_gui.py", line 13, in <module>
    from library.common_gui import (
  File "D:\kohya_ss\library\common_gui.py", line 1, in <module>
    from tkinter import filedialog, Tk
ModuleNotFoundError: No module named 'tkinter'
```

Here is my NVIDIA configuration:
```shell
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.79                 Driver Version: 531.79       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060       WDDM | 00000000:09:00.0 Off |                  N/A |
|  0%   44C    P0               43W / 170W|    196MiB / 12288MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1192    C+G   ..._8wekyb3d8bbwe\Microsoft.Photos.exe    N/A      |
|    0   N/A  N/A      1848    C+G   ....Search_cw5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A      4876    C+G   ...5n1h2txyewy\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A      8080    C+G   ...ekyb3d8bbwe\PhoneExperienceHost.exe    N/A      |
|    0   N/A  N/A      8932    C+G   ....Search_cw5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A     15948    C+G   C:\Windows\explorer.exe                   N/A      |
|    0   N/A  N/A     16924    C+G   ...CBS_cw5n1h2txyewy\TextInputHost.exe    N/A      |
+---------------------------------------------------------------------------------------+
```

I have CUDA 12.1, and 11.8 installed with PATH variables although main CUDA path points to 12.1.

This was working on my system before I pulled. I tried to revert the commit and even delete the repository but it still is not working.

**Comment by FelipeCCSacramento** [comment]
I had this same issue trying to install it for the first time today on Windows
When you install Python 3.10.9, make sure to select `tcl/tk and IDLE option`
I think this information should be on README

![image](https://github.com/bmaltais/kohya_ss/assets/137085879/af294de4-ca2f-49a3-b56a-b2767b073480)

**Comment by rdcoder33** [comment]
run this command in your terminal:

`sudo apt update -y && sudo apt install -y python3.10-tk`

**Comment by bmaltais** [comment]
This must be new to the installer... Never had to do that before on windows... What gives... I can add that to the requirements file to fix it I guess...

**Comment by cshadd** [comment]
Sorry for the late response. Is it possible to do this using [pyenv](https://github.com/pyenv/pyenv)? I want to keep multiple versions of python because these different AIs have different environments.

**Comment by aycaecemgul** [comment]
just using this does not work if you have multiple python versions.

`sudo apt update -y && sudo apt install -y python3-tk
`

specify the python version you are using like this:

`sudo apt update -y && sudo apt install -y python3.10-tk
`

**Comment by goph-R** [comment]
The issue is, there is no python3.10-tk package on Debian 12.
```shell
gopher@gollum:~/kohya_ss$ sudo apt install -y python3.10-tk
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python3.10-tk
E: Couldn't find any package by glob 'python3.10-tk'
```
