### ISSUE TITLE
What is this problem!? about Configuring accelerate...PLZ Newbie

### ISSUE THREAD

**Issue by laavve** [bmaltais/kohya_ss#1134]
During installation I got this error:
`
Kohya_ss GUI setup menu:

1. Install kohya_ss gui
2. (Optional) Install cudann files
3. (Optional) Install bitsandbytes-windows
4. (Optional) Manually configure accelerate
5. (Optional) Start Kohya_ss GUI in browser
6. Quit

Enter your choice: 1

1. Torch 1
2. Torch 2
3. Cancel

Enter your choice: 1

16:20:00-989932 INFO     Version: v21.7.16
16:20:01-005546 INFO     Python 3.10.9 on Windows
16:20:01-005546 INFO     nVidia toolkit detected
16:20:01-021118 INFO     Installing modules from requirements_windows_torch1.txt...
16:20:01-021118 INFO     Installing package: torch==1.12.1+cu116 torchvision==0.13.1+cu116 --index-url
                         https://download.pytorch.org/whl/cu116
16:23:32-604814 INFO     Installing package:
                         https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/download/f/xformers-0.0.14.d
                         ev0-cp310-cp310-win_amd64.whl -U -I
16:23:48-653223 INFO     Installing package: bitsandbytes==0.35.0
16:23:52-465868 INFO     Installing package: accelerate==0.15.0 tensorboard==2.10.1 tensorflow==2.10.1
16:25:27-065712 INFO     Installing modules from requirements.txt...
16:25:27-096955 INFO     Installing package: albumentations==1.3.0
16:26:16-050452 INFO     Installing package: altair==4.2.2
16:26:47-472779 INFO     Installing package: dadaptation==3.1
16:26:50-019654 INFO     Installing package: diffusers[torch]==0.10.2
16:27:00-254252 INFO     Installing package: easygui==0.98.3
16:27:03-129275 INFO     Installing package: einops==0.6.0
16:27:05-957377 INFO     Installing package: fairscale==0.4.13
16:27:10-004316 INFO     Installing package: ftfy==6.1.1
16:27:12-957378 INFO     Installing package: gradio==3.33.1
16:27:45-894875 INFO     Installing package: huggingface-hub>=0.13.3
16:27:49-191750 INFO     Installing package: lion-pytorch==0.0.6
16:27:52-019876 INFO     Installing package: lycoris_lora==0.1.6
16:28:19-691807 INFO     Installing package: opencv-python==4.7.0.68
16:28:24-988710 INFO     Installing package: prodigyopt==1.0
16:28:28-691752 INFO     Installing package: pytorch-lightning==1.9.0
16:28:40-410497 INFO     Installing package: rich==13.4.1
16:28:45-848000 INFO     Installing package: safetensors==0.3.1
16:28:49-863630 INFO     Installing package: timm==0.6.12
16:28:56-801126 INFO     Installing package: tk==0.1.0
16:29:00-832375 INFO     Installing package: toml==0.10.2
16:29:04-910502 INFO     Installing package: transformers==4.26.0
16:29:33-957433 INFO     Installing package: voluptuous==0.13.1
16:29:38-176140 INFO     Installing package: wandb==0.15.0
16:29:55-223193 INFO     Installing package: -e .
16:30:07-848205 INFO     Copying bitsandbytes files...
16:30:07-957582 INFO     Configuring accelerate...
Traceback (most recent call last):
  File "C:\Users\Lave\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Lave\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 4, in <module>
  File "C:\kohya_ss\venv\lib\site-packages\accelerate\__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "C:\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 27, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\kohya_ss\venv\lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\kohya_ss\venv\lib\site-packages\accelerate\utils\__init__.py", line 103, in <module>
    from .megatron_lm import (
  File "C:\kohya_ss\venv\lib\site-packages\accelerate\utils\megatron_lm.py", line 32, in <module>
    from transformers.modeling_outputs import (
  File "C:\kohya_ss\venv\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "C:\kohya_ss\venv\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\kohya_ss\venv\lib\site-packages\transformers\utils\__init__.py", line 60, in <module>
    from .hub import (
  File "C:\kohya_ss\venv\lib\site-packages\transformers\utils\hub.py", line 1087, in <module>
    cache_version = int(f.read())
ValueError: invalid literal for int() with base 10: '\x00'

Kohya_ss GUI setup menu:

1. Install kohya_ss gui
2. (Optional) Install cudann files
3. (Optional) Install bitsandbytes-windows
4. (Optional) Manually configure accelerate
5. (Optional) Start Kohya_ss GUI in browser
6. Quit

Enter your choice: 4

Traceback (most recent call last):
  File "C:\Users\Lave\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Lave\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 4, in <module>
  File "C:\kohya_ss\venv\lib\site-packages\accelerate\__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "C:\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 27, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\kohya_ss\venv\lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\kohya_ss\venv\lib\site-packages\accelerate\utils\__init__.py", line 103, in <module>
    from .megatron_lm import (
  File "C:\kohya_ss\venv\lib\site-packages\accelerate\utils\megatron_lm.py", line 32, in <module>
    from transformers.modeling_outputs import (
  File "C:\kohya_ss\venv\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "C:\kohya_ss\venv\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\kohya_ss\venv\lib\site-packages\transformers\utils\__init__.py", line 60, in <module>
    from .hub import (
  File "C:\kohya_ss\venv\lib\site-packages\transformers\utils\hub.py", line 1087, in <module>
    cache_version = int(f.read())
ValueError: invalid literal for int() with base 10: '\x00'

Kohya_ss GUI setup menu:

1. Install kohya_ss gui
2. (Optional) Install cudann files
3. (Optional) Install bitsandbytes-windows
4. (Optional) Manually configure accelerate
5. (Optional) Start Kohya_ss GUI in browser
6. Quit

Enter your choice:`

**Comment by laavve** [comment]
ok with Torch 2
