### ISSUE TITLE
On first run, an error occurs

### ISSUE THREAD

**Issue by ADKYUSHU12321** [bmaltais/kohya_ss#1159]
On first run, I get the following error: Traceback (most recent call last):
   File ".\setup\setup_windows.py", line 201, in <module>
     setup_common. setup_logging()
   File "C:\Users\mat\Desktop\kohya_ss\setup\setup_common.py", line 54, in setup_logging
     logging. basicConfig(
   File "C:\ProgramData\Miniconda3\lib\logging\__init__.py", line 2009, in basicConfig
     raise ValueError('Unrecognized argument(s): %s' % keys)
ValueError: Unrecognized argument(s): encoding

python3.10.9

**Comment by bmaltais** [comment]
Install python directly from from the link in the readme. Miniconda may not work well as I never use that in windows.
