### ISSUE TITLE
The Lora cannot be used in the additional networks extension in v21.8.0.

### ISSUE THREAD

**Issue by hinablue** [bmaltais/kohya_ss#1163]
There is the error message from the Docker log,

```
services-sd-testing-1  | LoRA weight_unet: 1, weight_tenc: 1, model: hinaCalineHires_v230(fcf679496ab3)
services-sd-testing-1  | dimension: {192}, alpha: {32.0}, multiplier_unet: 1, multiplier_tenc: 1
services-sd-testing-1  | *** Error running process_batch: /stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
services-sd-testing-1  |     Traceback (most recent call last):
services-sd-testing-1  |       File "/stable-diffusion-webui/modules/scripts.py", line 490, in process_batch
services-sd-testing-1  |         script.process_batch(p, *script_args, **kwargs)
services-sd-testing-1  |       File "/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 244, in process_batch
services-sd-testing-1  |         network, info = lora_compvis.create_network_and_apply_compvis(
services-sd-testing-1  |       File "/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 153, in create_network_and_apply_compvis
services-sd-testing-1  |         network = LoRANetworkCompvis(text_encoder, unet, multiplier_tenc, multiplier_unet, modules_dim, modules_alpha)
services-sd-testing-1  |       File "/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 341, in __init__
services-sd-testing-1  |         comp_vis_lora_name = LoRANetworkCompvis.convert_diffusers_name_to_compvis(self.v2, du_lora_name)
services-sd-testing-1  |       File "/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 302, in convert_diffusers_name_to_compvis
services-sd-testing-1  |         assert cv_name is not None, f"conversion failed: {du_name}. the model may not be trained by `sd-scripts`."
services-sd-testing-1  |     AssertionError: conversion failed: lora_te1_text_model_encoder_layers_0_mlp_fc1. the model may not be trained by `sd-scripts`.
```

I'm not sure the issue is about `sd-webui-additional-networks` or `kohya_ss`. And I fallback to `v21.7.15` it work find.

**Comment by dougvan1701** [comment]
Dropping back to v21.7.16 corrected the broken LoRA issue for me that was introduced in a recent update. None of the LoRAs I created using the latest release worked with A111, EazyDiffusion or Comfy_UI. V21.7.16 appears to work just fine.
