### ISSUE TITLE
Dataset Balancing issues

### ISSUE THREAD

**Issue by Pychnight** [bmaltais/kohya_ss#12]
seems like there is a small bug with 1.8.5 data set balancing, it seems to do it partially correct.

though it comes up with this error

`Traceback (most recent call last):
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 847, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\library\dataset_balancing_gui.py", line 58, in dataset_balancing
    repeats = max(1, round(concept_repeats / images))
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 847, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\library\dataset_balancing_gui.py", line 58, in dataset_balancing
    repeats = max(1, round(concept_repeats / images))
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 847, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\person\OneDrive\Documents\GitHub\kohya_ss\library\dataset_balancing_gui.py", line 58, in dataset_balancing
    repeats = max(1, round(concept_repeats / images))
ZeroDivisionError: division by zero`

**Comment by bmaltais** [comment]
Hummm... possibly a corner case. Is it possible that some of the folders do not contain any images? Or possibly images with an extension that the GUI does not recognise? I will try to balance with an empty folder and see if I can reproduce the issue.

**Comment by bmaltais** [comment]
Found the issue... it does indeed appart when no images are found in a folder... causing a division by zero. Now... why is it not detecting any images is the other question...

**Comment by bmaltais** [comment]
Issue should be fixed by: https://github.com/bmaltais/kohya_ss/pull/14
