### ISSUE TITLE
Installation problem: Configuring accelerate... throws error

### ISSUE THREAD

**Issue by shoash** [bmaltais/kohya_ss#1203]
Does anybody know how to fix this issue?

Kohya_ss GUI setup menu:

1. Install kohya_ss gui
2. (Optional) Install cudann files
3. (Optional) Install bitsandbytes-windows
4. (Optional) Manually configure accelerate
5. (Optional) Start Kohya_ss GUI in browser
6. Quit

Enter your choice: 1

1. Torch 1 (legacy)
2. Torch 2 (recommended)
3. Cancel

Enter your choice: 2

12:00:09-385269 INFO     Version: v21.8.2
12:00:09-386269 INFO     Python 3.10.0 on Windows
12:00:09-390775 INFO     nVidia toolkit detected
12:00:09-395782 INFO     Installing modules from requirements_windows_torch2.txt...
12:00:09-396781 INFO     Installing package: torch==2.0.1+cu118 torchvision==0.15.2+cu118 --index-url
                         https://download.pytorch.org/whl/cu118
12:00:12-885575 INFO     Installing modules from requirements.txt...
12:00:12-895087 INFO     Installing package: -e .
12:00:19-879112 INFO     Copying bitsandbytes files...
12:00:19-881624 INFO     Configuring accelerate...
Traceback (most recent call last):
  File "C:\Users\m_Geo\AppData\Local\Programs\Python\Python311\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\m_Geo\AppData\Local\Programs\Python\Python311\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\m_Geo\stable diffusionTrainer\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 4, in <module>
  File "C:\Users\m_Geo\stable diffusionTrainer\kohya_ss\venv\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\m_Geo\stable diffusionTrainer\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 30, in <module>
    import torch
  File "C:\Users\m_Geo\stable diffusionTrainer\kohya_ss\venv\lib\site-packages\torch\__init__.py", line 133, in <module>
    raise err
OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden. Error loading "C:\Users\m_Geo\stable diffusionTrainer\kohya_ss\venv\lib\site-packages\torch\lib\torch_python.dll" or one of its dependencies.

**Comment by bmaltais** [comment]
This is very odd... not seen that one before... I will check if I can reproduce it.

**Comment by Glt1997** [comment]
Also having the same issue.
