### ISSUE TITLE
This is an issue another user had with the GPU no being detected. Supposedly this was fixed?

### ISSUE THREAD

**Issue by solu3141** [bmaltais/kohya_ss#123]
I tried to reinstall but I'm still having these issues. I'm not sure if it's a problem on my end or not, but I followed all of the steps for installation. 

> Traceback (most recent call last):
  File "D:\LoRA Creation\kohya_ss\train_db.py", line 340, in <module>
    train(args)
  File "D:\LoRA Creation\kohya_ss\train_db.py", line 57, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "D:\LoRA Creation\kohya_ss\library\train_util.py", line 1483, in prepare_accelerator
    accelerator = Accelerator(gradient_accumulation_steps=args.gradient_accumulation_steps, mixed_precision=args.mixed_precision,
  File "D:\LoRA Creation\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 355, in __init__
    raise ValueError(err.format(mode="fp16", requirement="a GPU"))
ValueError: fp16 mixed precision requires a GPU
Traceback (most recent call last):
  File "C:\Users\mlc31\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mlc31\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\LoRA Creation\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\LoRA Creation\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\LoRA Creation\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\LoRA Creation\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

For reference the GPU in question is the laptop version of the 3070.

**Comment by Chopin68** [comment]
I also have this problem! Any ideas

**Comment by Chopin68** [comment]
I solved it. Check the version of cuda and whether the gpu version of torch is installed

**Comment by Chopin68** [comment]
![image](https://user-images.githubusercontent.com/75252160/217414049-283f4f4f-cd03-446b-afbd-ec7062341a34.png)
This is my config

**Comment by solu3141** [comment]
Thanks! I found the part I was looking for on the non-GUI version too. Hopefully it all works out.

**Comment by solu3141** [comment]
So two kind of dumb questions:
Where is that config file so I can edit it without having to reinstall every time? 
Pretty sure I don't have CUDA given that the "nvcc --version" check doesn't work, but I did the "Optional: CUDNN 8.6" step figuring that would handle it. Seeing as it didn't my question is should I just put CUDA on my machine or does it go in the venv somehow?
Sorry for the probably obvious questions. I don't work with thing that require GPU setup usually.

**Comment by Chopin68** [comment]
> 


In my environment, C:\Users\admin\.cache\huggingface\accelerate\default_config.yaml
If your 'nvcc - V' doesn't work, you may not have cuda installed. You can download it from here https://developer.nvidia.com/cuda-11-6-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_local

**Comment by solu3141** [comment]
Well after all that I got it working but it looks like 8 GB of VRAM is not enough. Thanks for all the help though!

**Comment by Chopin68** [comment]
> 好吧，毕竟我让它工作了，但看起来 8 GB 的 VRAM 是不够的。感谢您的所有帮助！
Enough. I only used 6GB for training

**Comment by solu3141** [comment]
Ok that was just a mistake on my part. I had gone through the process of starting it so many times I forgot to switch to the LoRA tab instead of the dreambooth one. Thanks for everything it's working now so I'll close the issue!
