### ISSUE TITLE
Unable to install bitsandbytes 0.35.0

### ISSUE THREAD

**Issue by civet** [bmaltais/kohya_ss#1243]
I ran the installation script many times and it failed. Finally, it was found that there was a dependency that always failed to install.

`C:\kohya_ss> setup.bat`
1
2
```
17:35:22-464319 INFO     Version: v21.8.3
17:35:22-464319 INFO     Python 3.10.9 on Windows
17:35:22-479963 INFO     nVidia toolkit detected
17:35:25-336694 INFO     Torch 2.0.1+cu118
17:35:25-405726 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
17:35:25-405726 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12287 Arch (8, 6) Cores 28
17:35:25-405726 INFO     Installing modules from requirements_windows_torch2.txt...
17:35:25-405726 INFO     Installing package: torch==2.0.1+cu118 torchvision==0.15.2+cu118 --index-url
                         https://download.pytorch.org/whl/cu118
17:35:32-184917 INFO     Installing package: xformers==0.0.20 bitsandbytes==0.35.0
17:35:37-854160 ERROR    Error running pip: install --upgrade xformers==0.0.20 bitsandbytes==0.35.0
```

then, try to find out the details:
`(venv) C:\kohya_ss> pip install -v bitsandbytes==0.35.0 `
```
Using pip 23.2 from C:\kohya_ss\venv\lib\site-packages\pip (python 3.10)
Collecting bitsandbytes==0.35.0
Installing collected packages: bitsandbytes
ERROR: Could not install packages due to an OSError.
Traceback (most recent call last):
  File "C:\kohya_ss\venv\lib\site-packages\pip\_internal\commands\install.py", line 452, in run
    installed = install_given_reqs(
  File "C:\kohya_ss\venv\lib\site-packages\pip\_internal\req\__init__.py", line 72, in install_given_reqs
    requirement.install(
  File "C:\kohya_ss\venv\lib\site-packages\pip\_internal\req\req_install.py", line 807, in install
    install_wheel(
  File "C:\kohya_ss\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 731, in install_wheel
    _install_wheel(
  File "C:\kohya_ss\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 591, in _install_wheel
    file.save()
  File "C:\kohya_ss\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 389, in save
    with open(self.dest_path, "wb") as dest:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\kohya_ss\\venv\\Lib\\site-packages\\bitsandbytes\\__init__.py
...
```

**Comment by civet** [comment]
Stupid me, I tried a clean install and it worked
