### ISSUE TITLE
SDXL training RuntimeError: stack expects each tensor to be equal size, but got [4, 140, 116] at entry 0 and [4, 152, 104] at entry 1

### ISSUE THREAD

**Issue by hopto-dot** [bmaltais/kohya_ss#1269]
```
10:48:17-357880 INFO     Start training LoRA Standard ...
10:48:17-369892 INFO     Valid image folder names found in: C:/Users/George/Documents/Git/kohya_ss/LoRA Training/rosuuri/images
10:48:17-409880 INFO     Folder 1_rosuuri: 426 images found
10:48:17-412880 INFO     Folder 1_rosuuri: 426 steps
10:48:17-417880 INFO     Total steps: 426
10:48:17-419879 INFO     Train batch size: 8
10:48:17-422879 INFO     Gradient accumulation steps: 1.0
10:48:17-425881 INFO     Epoch: 10
10:48:17-427880 INFO     Regulatization factor: 1
10:48:17-430879 INFO     max_train_steps (426 / 8 / 1.0 * 10 * 1) = 533
10:48:17-433879 INFO     stop_text_encoder_training = 0
10:48:17-436879 INFO     lr_warmup_steps = 0
10:48:17-444880 INFO     Saving training config to C:/Users/George/Documents/Git/kohya_ss/LoRA Training/rosuuri/model\rosuuri_20230727-104817.json...
10:48:17-450880 INFO     accelerate launch --num_cpu_threads_per_process=3 "./sdxl_train_network.py" --enable_bucket --min_bucket_reso=64 --max_bucket_reso=2048
                         --pretrained_model_name_or_path="C:/Users/George/Documents/Git/ComfyUI_windows/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors"
                         --train_data_dir="C:/Users/George/Documents/Git/kohya_ss/LoRA Training/rosuuri/images" --resolution="1024,1024"
                         --output_dir="C:/Users/George/Documents/Git/kohya_ss/LoRA Training/rosuuri/model" --network_alpha="128" --training_comment="First LoRA attempt"
                         --save_model_as=safetensors --network_module=networks.lora --network_args rank_dropout="0.09" module_dropout="0.09" --text_encoder_lr=0.0001 --unet_lr=0.0001
                         --network_dim=128 --output_name="rosuuri" --lr_scheduler_num_cycles="10" --no_half_vae --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="8"
                         --max_train_steps="533" --save_every_n_epochs="1" --mixed_precision="bf16" --save_precision="bf16" --seed="12345" --caption_extension=".txt" --cache_latents
                         --cache_latents_to_disk --optimizer_type="AdamW" --max_data_loader_n_workers="1" --bucket_reso_steps=32 --save_state --flip_aug --shuffle_caption
                         --gradient_checkpointing --xformers --noise_offset=0.05 --sample_sampler=euler_a --sample_prompts="C:/Users/George/Documents/Git/kohya_ss/LoRA
                         Training/rosuuri/model\sample\prompt.txt" --sample_every_n_steps="100"
```                         

``` python
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
prepare tokenizers
Using DreamBooth method.
prepare images.
found directory C:\Users\George\Documents\Git\kohya_ss\LoRA Training\rosuuri\images\1_rosuuri contains 426 image files
426 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 8
  resolution: (1024, 1024)
  enable_bucket: True
  min_bucket_reso: 64
  max_bucket_reso: 2048
  bucket_reso_steps: 32
  bucket_no_upscale: False

  [Subset 0 of Dataset 0]
    image_dir: "C:\Users\George\Documents\Git\kohya_ss\LoRA Training\rosuuri\images\1_rosuuri"
    image_count: 426
    num_repeats: 1
    shuffle_caption: True
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: True
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: rosuuri
    caption_extension: .txt


[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 426/426 [00:00<00:00, 664.11it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (608, 1664), count: 1
bucket 1: resolution (608, 1696), count: 1
bucket 2: resolution (704, 1440), count: 1
bucket 3: resolution (736, 1376), count: 3
bucket 4: resolution (736, 1408), count: 6
bucket 5: resolution (768, 1312), count: 7
bucket 6: resolution (768, 1344), count: 4
bucket 7: resolution (800, 1280), count: 26
bucket 8: resolution (832, 1216), count: 89
bucket 9: resolution (832, 1248), count: 20
bucket 10: resolution (864, 1184), count: 84
bucket 11: resolution (896, 1152), count: 17
bucket 12: resolution (928, 1120), count: 18
bucket 13: resolution (960, 1088), count: 11
bucket 14: resolution (992, 1056), count: 5
bucket 15: resolution (1024, 1024), count: 12
bucket 16: resolution (1056, 992), count: 2
bucket 17: resolution (1088, 960), count: 6
bucket 18: resolution (1120, 928), count: 10
bucket 19: resolution (1152, 896), count: 2
bucket 20: resolution (1184, 864), count: 33
bucket 21: resolution (1216, 832), count: 15
bucket 22: resolution (1248, 832), count: 13
bucket 23: resolution (1280, 800), count: 2
bucket 24: resolution (1312, 768), count: 7
bucket 25: resolution (1344, 768), count: 26
bucket 26: resolution (1376, 736), count: 2
bucket 27: resolution (1408, 736), count: 2
bucket 28: resolution (1472, 704), count: 1
mean ar error (without repeats): 0.01777963214955272
Warning: SDXL has been trained with noise_offset=0.0357 / SDXLはnoise_offset=0.0357で学習されています
noise_offset is set to 0.05 / noise_offsetが0.05に設定されました
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: C:/Users/George/Documents/Git/ComfyUI_windows/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors
building U-Net
loading U-Net from checkpoint
U-Net:  <All keys matched successfully>
building text encoders
loading text encoders from checkpoint
text encoder 1: <All keys matched successfully>
text encoder 2: <All keys matched successfully>
building VAE
loading VAE from checkpoint
VAE: <All keys matched successfully>
Enable xformers for U-Net
import network module: networks.lora
[Dataset 0]
caching latents.
checking cache validity...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 426/426 [00:13<00:00, 31.78it/s]
caching latents...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:15<00:00,  3.76s/it]
create LoRA network. base dim (rank): 128, alpha: 128.0
neuron dropout: p=None, rank dropout: p=0.09, module dropout: p=0.09
create LoRA for Text Encoder 1:
create LoRA for Text Encoder 2:
create LoRA for Text Encoder: 264 modules.
create LoRA for U-Net: 722 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
use AdamW optimizer | {}
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 426
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 71
  num epochs / epoch数: 8
  batch size per device / バッチサイズ: 8
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 533
steps:   0%|                                                                                                                                                        | 0/533 [00:00<?, ?it/s]
epoch 1/8
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
C:\Users\George\Documents\Git\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\flash.py:339: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  and inp.query.storage().data_ptr() == inp.key.storage().data_ptr()
steps:   1%|▋                                                                                                                                 | 3/533 [00:42<2:05:19, 14.19s/it, loss=0.146]╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\George\Documents\Git\kohya_ss\sdxl_train_network.py:174 in <module>                     │
│                                                                                                  │
│   171 │   args = train_util.read_config_from_file(args, parser)                                  │
│   172 │                                                                                          │
│   173 │   trainer = SdxlNetworkTrainer()                                                         │
│ ❱ 174 │   trainer.train(args)                                                                    │
│   175                                                                                            │
│                                                                                                  │
│ C:\Users\George\Documents\Git\kohya_ss\train_network.py:716 in train                             │
│                                                                                                  │
│   713 │   │   │                                                                                  │
│   714 │   │   │   network.on_epoch_start(text_encoder, unet)                                     │
│   715 │   │   │                                                                                  │
│ ❱ 716 │   │   │   for step, batch in enumerate(train_dataloader):                                │
│   717 │   │   │   │   current_step.value = global_step                                           │
│   718 │   │   │   │   with accelerator.accumulate(network):                                      │
│   719 │   │   │   │   │   on_step_start(text_encoder, unet)                                      │
│                                                                                                  │
│ C:\Users\George\Documents\Git\kohya_ss\venv\lib\site-packages\accelerate\data_loader.py:388 in   │
│ __iter__                                                                                         │
│                                                                                                  │
│   385 │   │   │   │   # But we still move it to the device so it is done before `StopIteration   │
│   386 │   │   │   │   if self.device is not None:                                                │
│   387 │   │   │   │   │   current_batch = send_to_device(current_batch, self.device)             │
│ ❱ 388 │   │   │   │   next_batch = next(dataloader_iter)                                         │
│   389 │   │   │   │   if batch_index >= self.skip_batches:                                       │
│   390 │   │   │   │   │   yield current_batch                                                    │
│   391 │   │   │   │   batch_index += 1                                                           │
│                                                                                                  │
│ C:\Users\George\Documents\Git\kohya_ss\venv\lib\site-packages\torch\utils\data\dataloader.py:633 │
│ in __next__                                                                                      │
│                                                                                                  │
│    630 │   │   │   if self._sampler_iter is None:                                                │
│    631 │   │   │   │   # TODO(https://github.com/pytorch/pytorch/issues/76750)                   │
│    632 │   │   │   │   self._reset()  # type: ignore[call-arg]                                   │
│ ❱  633 │   │   │   data = self._next_data()                                                      │
│    634 │   │   │   self._num_yielded += 1                                                        │
│    635 │   │   │   if self._dataset_kind == _DatasetKind.Iterable and \                          │
│    636 │   │   │   │   │   self._IterableDataset_len_called is not None and \                    │
│                                                                                                  │
│ C:\Users\George\Documents\Git\kohya_ss\venv\lib\site-packages\torch\utils\data\dataloader.py:134 │
│ 5 in _next_data                                                                                  │
│                                                                                                  │
│   1342 │   │   │   │   self._task_info[idx] += (data,)                                           │
│   1343 │   │   │   else:                                                                         │
│   1344 │   │   │   │   del self._task_info[idx]                                                  │
│ ❱ 1345 │   │   │   │   return self._process_data(data)                                           │
│   1346 │                                                                                         │
│   1347 │   def _try_put_index(self):                                                             │
│   1348 │   │   assert self._tasks_outstanding < self._prefetch_factor * self._num_workers        │
│                                                                                                  │
│ C:\Users\George\Documents\Git\kohya_ss\venv\lib\site-packages\torch\utils\data\dataloader.py:137 │
│ 1 in _process_data                                                                               │
│                                                                                                  │
│   1368 │   │   self._rcvd_idx += 1                                                               │
│   1369 │   │   self._try_put_index()                                                             │
│   1370 │   │   if isinstance(data, ExceptionWrapper):                                            │
│ ❱ 1371 │   │   │   data.reraise()                                                                │
│   1372 │   │   return data                                                                       │
│   1373 │                                                                                         │
│   1374 │   def _mark_worker_as_unavailable(self, worker_id, shutdown=False):                     │
│                                                                                                  │
│ C:\Users\George\Documents\Git\kohya_ss\venv\lib\site-packages\torch\_utils.py:644 in reraise     │
│                                                                                                  │
│   641 │   │   │   # If the exception takes multiple arguments, don't try to                      │
│   642 │   │   │   # instantiate since we don't know how to                                       │
│   643 │   │   │   raise RuntimeError(msg) from None                                              │
│ ❱ 644 │   │   raise exception                                                                    │
│   645                                                                                            │
│   646                                                                                            │
│   647 def _get_available_device_type():                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\George\Documents\Git\kohya_ss\venv\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\George\Documents\Git\kohya_ss\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\George\Documents\Git\kohya_ss\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\George\Documents\Git\kohya_ss\venv\lib\site-packages\torch\utils\data\dataset.py", line 243, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "C:\Users\George\Documents\Git\kohya_ss\library\train_util.py", line 1167, in __getitem__
    example["latents"] = torch.stack(latents_list) if latents_list[0] is not None else None
RuntimeError: stack expects each tensor to be equal size, but got [4, 140, 116] at entry 0 and [4, 152, 104] at entry 1

steps:   1%|▋                                                                                                                                 | 3/533 [00:43<2:08:59, 14.60s/it, loss=0.146]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\George\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main  │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\George\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code             │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Users\George\Documents\Git\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli │
│ .py:45 in main                                                                                   │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Users\George\Documents\Git\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918  │
│ in launch_command                                                                                │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ C:\Users\George\Documents\Git\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580  │
│ in simple_launcher                                                                               │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['C:\\Users\\George\\Documents\\Git\\kohya_ss\\venv\\Scripts\\python.exe', './sdxl_train_network.py', '--enable_bucket', '--min_bucket_reso=64',
'--max_bucket_reso=2048', '--pretrained_model_name_or_path=C:/Users/George/Documents/Git/ComfyUI_windows/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors',
'--train_data_dir=C:/Users/George/Documents/Git/kohya_ss/LoRA Training/rosuuri/images', '--resolution=1024,1024', '--output_dir=C:/Users/George/Documents/Git/kohya_ss/LoRA
Training/rosuuri/model', '--network_alpha=128', '--training_comment=First LoRA attempt', '--save_model_as=safetensors', '--network_module=networks.lora', '--network_args',
'rank_dropout=0.09', 'module_dropout=0.09', '--text_encoder_lr=0.0001', '--unet_lr=0.0001', '--network_dim=128', '--output_name=rosuuri', '--lr_scheduler_num_cycles=10', '--no_half_vae',
'--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=8', '--max_train_steps=533', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16',
'--seed=12345', '--caption_extension=.txt', '--cache_latents', '--cache_latents_to_disk', '--optimizer_type=AdamW', '--max_data_loader_n_workers=1', '--bucket_reso_steps=32',
'--save_state', '--flip_aug', '--shuffle_caption', '--gradient_checkpointing', '--xformers', '--noise_offset=0.05', '--sample_sampler=euler_a',
'--sample_prompts=C:/Users/George/Documents/Git/kohya_ss/LoRA Training/rosuuri/model\\sample\\prompt.txt', '--sample_every_n_steps=100']' returned non-zero exit status 1.
```

# Additional information
* I have 16GB of RAM
* I'm running KohyaSS on a rtx 3090 24GB
* VRAM usage hovers around 23.4GB when training for the first few steps.

**Comment by Fade07w** [comment]
You ever get help with this?

**Comment by hopto-dot** [comment]
In the end I used different settings to train the model and it worked. It's probably worth closing this issue.

**Comment by superprat** [comment]
What were the settings that you changed?

**Comment by superprat** [comment]
For those facing the same issue, it seems to be a problem with images in the bucket being of different sizes., Reducing bucket resolution steps to 32 resolved it
