### ISSUE TITLE
Error merging LoRA

### ISSUE THREAD

**Issue by NoneIQalt** [bmaltais/kohya_ss#128]
`.\venv\Scripts\python.exe "networks\merge_lora.py" --save_precision fp16 --precision fp16 --save_to C:/Users/Myusername/Desktop/sd/Kohya/semirealistic.safetensors --models C:/Users/Myusername/Downloads/samdoesartsSamYang_normal.safetensors C:/Users/Myusername/Downloads/wlopStyleLora_30Epochs.safetensors --ratios 0.6 0.4
loading: C:/Users/Myusername/Downloads/samdoesartsSamYang_normal.safetensors
merging...
loading: C:/Users/Myusername/Downloads/wlopStyleLora_30Epochs.safetensors
merging...
Traceback (most recent call last):
  File "C:\Users\Myusername\Desktop\sd\Kohya\kohya_ss\networks\merge_lora.py", line 179, in <module>
    merge(args)
  File "C:\Users\Myusername\Desktop\sd\Kohya\kohya_ss\networks\merge_lora.py", line 155, in merge
    state_dict, _, _ = merge_lora_models(args.models, args.ratios, merge_dtype)
  File "C:\Users\Myusername\Desktop\sd\Kohya\kohya_ss\networks\merge_lora.py", line 112, in merge_lora_models
    assert merged_sd[key].size() == lora_sd[key].size(
AssertionError: weights shape mismatch merging v1 and v2, different dims? / 重みのサイズが合いません。v1とv2、または次元数の異なるモデルはマージできません`

**Comment by bmaltais** [comment]
You can't merge LoRA made for v1 and v2 models tegether. This is what the error is about.
