### ISSUE TITLE
Error while BLIP captioning

### ISSUE THREAD

**Issue by satoshi02198** [bmaltais/kohya_ss#1302]
This is error log.
how can I fix this issue?

Traceback (most recent call last):
  File "C:\Users\satoshi\ai-tools\kohya_ss\finetune\make_captions.py", line 16, in <module>
    from blip.blip import blip_decoder
  File "C:\Users\satoshi\ai-tools\kohya_ss\finetune\blip\blip.py", line 13, in <module>
    from blip.vit import VisionTransformer, interpolate_pos_embed
  File "C:\Users\satoshi\ai-tools\kohya_ss\finetune\blip\vit.py", line 16, in <module>
    from timm.models.vision_transformer import _cfg, PatchEmbed
  File "C:\Users\satoshi\ai-tools\kohya_ss\venv\Lib\site-packages\timm\__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "C:\Users\satoshi\ai-tools\kohya_ss\venv\Lib\site-packages\timm\models\__init__.py", line 28, in <module>
    from .maxxvit import *
  File "C:\Users\satoshi\ai-tools\kohya_ss\venv\Lib\site-packages\timm\models\maxxvit.py", line 225, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Users\satoshi\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Users\satoshi\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\satoshi\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\satoshi\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'timm.models.maxxvit.MaxxVitConvCfg'> for field conv_cfg is not allowed: use default_factory

**Comment by satoshi02198** [comment]
I missed I used python 3.11.After Install 3.10.9,It working.
