### ISSUE TITLE
Crash everytime i launch training

### ISSUE THREAD

**Issue by Wolf101010** [bmaltais/kohya_ss#133]
My connection crashed while executing my first training, the programs was downloading models and stuff.
The programs instantly crash, after launching the bat file again, and starting a new training, i realise it didn't start the download again as i expected but keep crashing everytime i tried to run a training.

I've try to install it again, or to use the ps1 script in PowerShell instead of the .bat, but it keep crashing.

What could i do to repair it?
Here the error that happen every time i launch a training:
```
Traceback (most recent call last):
  File "D:\WorkStation\AI\kohya_ss\train_db.py", line 340, in <module>
    train(args)
  File "D:\WorkStation\AI\kohya_ss\train_db.py", line 63, in train
    text_encoder, vae, unet, load_stable_diffusion_format = train_util.load_target_model(args, weight_dtype)
  File "D:\WorkStation\AI\kohya_ss\library\train_util.py", line 1527, in load_target_model
    pipe = StableDiffusionPipeline.from_pretrained(args.pretrained_model_name_or_path, tokenizer=None, safety_checker=None)
  File "D:\WorkStation\AI\kohya_ss\venv\lib\site-packages\diffusers\pipeline_utils.py", line 709, in from_pretrained
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "D:\WorkStation\AI\kohya_ss\venv\lib\site-packages\transformers\modeling_utils.py", line 2301, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "D:\WorkStation\AI\kohya_ss\venv\lib\site-packages\transformers\modeling_utils.py", line 413, in load_state_dict
    return safe_load_file(checkpoint_file)
  File "D:\WorkStation\AI\kohya_ss\venv\lib\site-packages\safetensors\torch.py", line 100, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: self.size(-1) must be divisible by 4 to view Byte as Float (different element sizes), but got 144511
Traceback (most recent call last):
  File "C:\Users\Wolf\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Wolf\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\WorkStation\AI\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\WorkStation\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\WorkStation\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\WorkStation\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\WorkStation\\AI\\kohya_ss\\venv\\Scripts\\python.exe', 'train_db.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=D:/WorkStation/Nextcloud/Documents/StableDiffusion/Training 2.0/Ryze/4_LORA/image', '--resolution=512,512', '--output_dir=D:/WorkStation/Nextcloud/Documents/StableDiffusion/Training 2.0/Ryze/4_LORA/model', '--logging_dir=D:/WorkStation/Nextcloud/Documents/StableDiffusion/Training 2.0/Ryze/4_LORA/log', '--save_model_as=safetensors', '--output_name=wcmRyze', '--max_data_loader_n_workers=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=1200', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--use_8bit_adam', '--bucket_no_upscale']' returned non-zero exit status 1.
```

**Comment by Wolf101010** [comment]
Deleting .cache for the actual user solved the problem

**Comment by Vigilence** [comment]
@Wolf101010  How do I delete the cache?  I have the same issue.

**Comment by Wolf101010** [comment]
depending of your drive it should be in C:\Users\<your actual username>\.cache\  and you should delete the huggingface folder

**Comment by Vigilence** [comment]
Sadly this didn't help, but thanks.
