### ISSUE TITLE
TypeError: unsupported operand type(s) when Resizing Lora

### ISSUE THREAD

**Issue by Bammargiela** [bmaltais/kohya_ss#1338]
I am trying to resize an SDXL Lora from the GUI in Google Colab. Not sure if it is relevant but I had to fix an error where library module was not found by using `!pip install --upgrade .`

Is resizing SDXL Loras supported?

Here is the command from the GUI code cell output and the error:

`22:09:26-589983 INFO     python3 "networks/resize_lora.py" --save_precision fp16
                         --save_to                                              
                         "/content/drive/MyDrive/ComfyUI/models/loras/lora-v1-rank4.
                         safetensors" --model                                   
                         "/content/drive/MyDrive/ComfyUI/models/loras/lora-v1.safete
                         nsors" --new_rank 4 --device cuda --dynamic_method     
                         sv_fro --dynamic_param 0.9 --verbose                   
2023-08-06 22:09:31.340536: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-06 22:09:32.235922: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
loading Model...
Resizing Lora...
Traceback (most recent call last):
  File "/content/kohya_ss/networks/resize_lora.py", line 359, in <module>
    resize(args)
  File "/content/kohya_ss/networks/resize_lora.py", line 308, in resize
    state_dict, old_dim, new_alpha = resize_lora_model(lora_sd, args.new_rank, save_dtype, args.device, args.dynamic_method, args.dynamic_param, args.verbose)
  File "/content/kohya_ss/networks/resize_lora.py", line 206, in resize_lora_model
    scale = network_alpha/network_dim
TypeError: unsupported operand type(s) for /: 'Tensor' and 'NoneType'
22:09:46-508721 INFO     Done resizing...     `

**Comment by oliverban** [comment]
I am getting this as well and I think that it is as Symbio is saying, can't merge lokr style Lora with classical Lora!
