### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '100 Testtraining'

### ISSUE THREAD

**Issue by metzo007** [bmaltais/kohya_ss#136]
Hi,

I an getting this error message, following Aitrepreneur tutorial when I start the training.

Thanks, metzo

**Comment by metzo007** [comment]
Traceback (most recent call last):
  File "D:\KohyaGUI\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\KohyaGUI\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\KohyaGUI\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\KohyaGUI\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\KohyaGUI\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread    return await future
  File "D:\KohyaGUI\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\KohyaGUI\kohya_ss\lora_gui.py", line 337, in train_model
    repeats = int(folder.split('_')[0])
ValueError: invalid literal for int() with base 10: '100 Testtraining'

**Comment by bmaltais** [comment]
Make sure to put an underscore between the "100" and the "Testtraining" part of the folder name. It should read like `100_Testtraining`

**Comment by ffdown** [comment]
```
Traceback (most recent call last):
  File "E:\AI\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AI\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "E:\AI\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\AI\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\AI\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\AI\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\AI\kohya_ss\lora_gui.py", line 340, in train_model
    repeats = int(folder.split('_')[0])
ValueError: invalid literal for int() with base 10: 'log'
```

**Comment by metzo007** [comment]
This worked. The underscore is ever in the video. now I feel stupid. Thanks :-)
