### ISSUE TITLE
AttributeError: module 'os' has no attribute 'statvfs'

### ISSUE THREAD

**Issue by MahmoudGFX** [bmaltais/kohya_ss#1360]
Hello, trying to install Kohya_ss on windows, 
I am getting this error. 
I think The os.statvfs() call is not supported in Windows, right? 

```
Traceback (most recent call last):
  File "D:\stable-diffusion\kohya_ss\kohya_gui.py", line 1, in <module>
    import gradio as gr
  File "D:\stable-diffusion\kohya_ss\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "D:\stable-diffusion\kohya_ss\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "D:\stable-diffusion\kohya_ss\venv\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "D:\stable-diffusion\kohya_ss\venv\lib\site-packages\gradio\components\base.py", line 29, in <module>
    from gradio.blocks import Block, BlockContext
  File "D:\stable-diffusion\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 26, in <module>
    from gradio import (
  File "D:\stable-diffusion\kohya_ss\venv\lib\site-packages\gradio\networking.py", line 18, in <module>
    from gradio.routes import App
  File "D:\stable-diffusion\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 44, in <module>
    import gradio.ranged_response as ranged_response
  File "D:\stable-diffusion\kohya_ss\venv\lib\site-packages\gradio\ranged_response.py", line 12, in <module>
    from aiofiles.os import stat as aio_stat
  File "D:\stable-diffusion\kohya_ss\venv\lib\site-packages\aiofiles\os.py", line 32, in <module>
    statvfs = wrap(os.statvfs)
AttributeError: module 'os' has no attribute 'statvfs'
```

**Comment by YouYouTheBoxx** [comment]
I'm having the same error. Hope it'll be fixed soon.

**Comment by MahmoudGFX** [comment]
I managed to make it work 
`pip install aiofiles==23.1.0`
this version of aiofiles
and it should work
