### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by CRCODE22** [bmaltais/kohya_ss#1386]
When under Lora/Tools/Deprecated and you click prepare training data it will create many folders

RecursionError: maximum recursion depth exceeded while calling a Python object

Traceback (most recent call last):
  File "E:\kohya_ss-21.8.7\venv\lib\site-packages\gradio\routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\kohya_ss-21.8.7\venv\lib\site-packages\gradio\blocks.py", line 1384, in process_api
    result = await self.call_function(
  File "E:\kohya_ss-21.8.7\venv\lib\site-packages\gradio\blocks.py", line 1089, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\kohya_ss-21.8.7\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\kohya_ss-21.8.7\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\kohya_ss-21.8.7\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\kohya_ss-21.8.7\venv\lib\site-packages\gradio\utils.py", line 700, in wrapper
    response = f(*args, **kwargs)
  File "E:\kohya_ss-21.8.7\library\dreambooth_folder_creation_gui.py", line 74, in dreambooth_folder_preparation
    shutil.copytree(util_training_images_dir_input, training_dir)
  File "E:\anaconda3\lib\shutil.py", line 559, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "E:\anaconda3\lib\shutil.py", line 495, in _copytree
    copytree(srcobj, dstname, symlinks, ignore, copy_function,
  File "E:\anaconda3\lib\shutil.py", line 559, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "E:\anaconda3\lib\shutil.py", line 495, in _copytree
    copytree(srcobj, dstname, symlinks, ignore, copy_function,
  File "E:\anaconda3\lib\shutil.py", line 559, in copytree
........................................
....................................... keeps repeating many times

RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by phalladar** [comment]
Same issue.

**Comment by azamet90** [comment]
@bmaltais closed but any solution for this? i also have the same problem and im sure there is other people facing same problem.
