### ISSUE TITLE
Cuda error in Ubuntu

### ISSUE THREAD

**Issue by JohnTesla** [bmaltais/kohya_ss#1387]
**UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). 
Error 802: system not yet initialized (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
WARNING  Torch reports CUDA not available**   

/media/jag/NEU1/3PAX/kohya_ss-linux$ ./gui.sh
11:21:08-641870 INFO     Version: v21.8.7                                       
                                                                                
11:21:08-747643 INFO     nVidia toolkit detected                                
11:21:18-704585 INFO     Torch 2.0.1+cu118                                      
/media/jag/NEU1/3PAX/kohya_ss-linux/venv/lib/python3.10/site-packages/torch/cuda/__init__.py:107: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 802: system not yet initialized (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
11:21:18-836091 WARNING  Torch reports CUDA not available                       
11:21:18-843771 INFO     Verifying modules instalation status from              
                         /media/jag/NEU1/3PAX/kohya_ss-linux/requirements_linux.
                         txt...                                                 
11:21:18-853834 INFO     Verifying modules instalation status from              
                         requirements.txt...                                    
Traceback (most recent call last):
  File "/media/jag/NEU1/3PAX/kohya_ss-linux/kohya_gui.py", line 1, in <module>
    import gradio as gr
  File "/media/jag/NEU1/3PAX/kohya_ss-linux/venv/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/media/jag/NEU1/3PAX/kohya_ss-linux/venv/lib/python3.10/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/media/jag/NEU1/3PAX/kohya_ss-linux/venv/lib/python3.10/site-packages/gradio/components/annotated_image.py", line 8, in <module>
    from gradio_client.documentation import document, set_documentation_group
  File "/media/jag/NEU1/3PAX/kohya_ss-linux/venv/lib/python3.10/site-packages/gradio_client/__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "/media/jag/NEU1/3PAX/kohya_ss-linux/venv/lib/python3.10/site-packages/gradio_client/client.py", line 32, in <module>
    from gradio_client import serializing, utils
  File "/media/jag/NEU1/3PAX/kohya_ss-linux/venv/lib/python3.10/site-packages/gradio_client/serializing.py", line 9, in <module>
    from gradio_client import media_data, utils
  File "/media/jag/NEU1/3PAX/kohya_ss-linux/venv/lib/python3.10/site-packages/gradio_client/utils.py", line 21, in <module>
    import fsspec.asyn
  File "/media/jag/NEU1/3PAX/kohya_ss-linux/venv/lib/python3.10/site-packages/fsspec/__init__.py", line 5, in <module>
    from .compression import available_compressions
  File "/media/jag/NEU1/3PAX/kohya_ss-linux/venv/lib/python3.10/site-packages/fsspec/compression.py", line 2, in <module>
    from bz2 import BZ2File
  File "/home/jag/.pyenv/versions/3.10.9/lib/python3.10/bz2.py", line 17, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

 **NVIDIA-SMI 535.86.10              Driver Version: 535.86.10    CUDA Version: 12.2**

**Comment by ashleykleynhans** [comment]
Probably some CUDA 12.2 issue, works fine on Ubuntu 22.04 LTS in RunPod using CUDA 11.8.
