### ISSUE TITLE
textual inversion safetensor files wont load in A1111

### ISSUE THREAD

**Issue by metter** [bmaltais/kohya_ss#1389]
I am training TI embeddings on the SDXL 1.0 base model, with these settings:
```
{
  "adaptive_noise_scale": 0,
  "additional_parameters": "",
  "bucket_no_upscale": true,
  "bucket_reso_steps": 64,
  "cache_latents": false,
  "cache_latents_to_disk": false,
  "caption_dropout_every_n_epochs": 0.0,
  "caption_dropout_rate": 0,
  "caption_extension": "",
  "clip_skip": "1",
  "color_aug": false,
  "enable_bucket": false,
  "epoch": 1,
  "flip_aug": false,
  "full_fp16": false,
  "gradient_accumulation_steps": "1",
  "gradient_checkpointing": false,
  "init_word": "woman",
  "keep_tokens": "0",
  "learning_rate": 0.005,
  "logging_dir": "---folderpath---/training_data/25_South American_25_female/training/log",
  "lr_scheduler": "constant",
  "lr_scheduler_num_cycles": "",
  "lr_scheduler_power": "",
  "lr_warmup": 0,
  "max_bucket_reso": 2048,
  "max_data_loader_n_workers": "0",
  "max_resolution": "768,768",
  "max_timestep": 1000,
  "max_token_length": "75",
  "max_train_epochs": "",
  "max_train_steps": "",
  "mem_eff_attn": false,
  "min_bucket_reso": 256,
  "min_snr_gamma": 0,
  "min_timestep": 0,
  "mixed_precision": "fp16",
  "model_list": "custom",
  "multires_noise_discount": 0,
  "multires_noise_iterations": 0,
  "no_token_padding": false,
  "noise_offset": 0,
  "noise_offset_type": "Original",
  "num_cpu_threads_per_process": 2,
  "num_vectors_per_token": 8,
  "optimizer": "AdamW8bit",
  "optimizer_args": "",
  "output_dir": "---folderpath---/training_data/25_South American_25_female/training/model",
  "output_name": "25_South American_25_female",
  "persistent_data_loader_workers": false,
  "pretrained_model_name_or_path": "---folderpath---/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0.safetensors",
  "prior_loss_weight": 1.0,
  "random_crop": false,
  "reg_data_dir": "",
  "resume": "",
  "sample_every_n_epochs": 0,
  "sample_every_n_steps": 0,
  "sample_prompts": "",
  "sample_sampler": "euler_a",
  "save_every_n_epochs": 1,
  "save_every_n_steps": 0,
  "save_last_n_steps": 0,
  "save_last_n_steps_state": 0,
  "save_model_as": "safetensors",
  "save_precision": "fp16",
  "save_state": true,
  "scale_v_pred_loss_like_noise_pred": false,
  "sdxl": true,
  "sdxl_no_half_vae": true,
  "seed": "",
  "shuffle_caption": false,
  "stop_text_encoder_training": 0,
  "template": "object template",
  "token_string": "25_south_american_25_female",
  "train_batch_size": 1,
  "train_data_dir": "---folderpath---/training_data/25_South American_25_female/training/img",
  "use_wandb": false,
  "v2": false,
  "v_parameterization": false,
  "vae": "",
  "vae_batch_size": 0,
  "wandb_api_key": "",
  "weights": "",
  "xformers": "xformers"
}
```

I put the resulting .safetensor files into the /embeddings folder of automatic1111 and get this during startup:
```
*** Error loading embedding 1_european_20_female-step00001250.safetensors
    Traceback (most recent call last):
      File "---folderpath---\stable-diffusion-webui\modules\textual_inversion\textual_inversion.py", line 227, in load_from_dir
        self.load_from_file(fullfn, fn)
      File "---folderpath---\stable-diffusion-webui\modules\textual_inversion\textual_inversion.py", line 192, in load_from_file
        assert len(data.keys()) == 1, 'embedding file has multiple terms in it'
    AssertionError: embedding file has multiple terms in it
```

any idea why that is?

**Comment by bluntstone** [comment]
I get the same error. They work in ComfyUI. I think its a1111 just haven't implemented it yet. Waiting for an update of A1111. Also don't work in invokeai.  syntax for comfyui is "embedding:embeddingname trigger"

**Comment by metter** [comment]
Just tried it in ComfyUI and they work fine. Thank you for the tip. I'll raise it on the A111 repo
