### ISSUE TITLE
error <Signals.SIGKILL: 9> when trying to train lora sdxl on colab free

### ISSUE THREAD

**Issue by loboere** [bmaltais/kohya_ss#1398]
error <Signals.SIGKILL: 9> when trying to train lora sdxl on colab free

12gb ram
GPU=T4 16gb

I am trying to train a lora for sdxl /content/sd_xl_base_1.0.safetensors
but it gives error
Does anyone know how to make it work in colab free?

```
23:18:09-788156 INFO     headless: True                                         
23:18:09-792555 INFO     Load CSS...                                            
Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://c196559e2ed0533f57.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
23:19:04-005686 INFO     Start training Dreambooth...                           
23:19:04-007710 ERROR    The following folders do not match the required pattern
                         <number>_<text>: /content/data/elsin                   
23:19:04-009048 ERROR    Please follow the folder structure documentation found 
                         at docs\image_folder_structure.md ...                  
23:19:04-010148 INFO     Output folder path is missing                          
23:20:05-712865 INFO     Start training Dreambooth...                           
23:20:05-714313 ERROR    The following folders do not match the required pattern
                         <number>_<text>: /content/data/.ipynb_checkpoints      
23:20:05-715692 ERROR    Please follow the folder structure documentation found 
                         at docs\image_folder_structure.md ...                  
23:20:05-716783 INFO     Output folder path is missing                          
23:21:01-053944 INFO     Start training Dreambooth...                           
23:21:01-055406 ERROR    The following folders do not match the required pattern
                         <number>_<text>: /content/data/.ipynb_checkpoints      
23:21:01-057091 ERROR    Please follow the folder structure documentation found 
                         at docs\image_folder_structure.md ...                  
23:21:01-058249 INFO     Headless mode, skipping verification if model already  
                         exist... if model already exist it will be             
                         overwritten...                                         
23:21:01-059596 INFO     Folder 30_elsin : steps 30                             
23:21:01-060594 INFO     max_train_steps = 30                                   
23:21:01-061609 INFO     stop_text_encoder_training = 0                         
23:21:01-062559 INFO     lr_warmup_steps = 3                                    
23:21:01-063650 INFO     Saving training config to                              
                         /content/out/last_20230816-232101.json...              
23:21:01-064982 INFO     accelerate launch --num_cpu_threads_per_process=2      
                         "./sdxl_train.py" --enable_bucket --min_bucket_reso=256
                         --max_bucket_reso=2048                                 
                         --pretrained_model_name_or_path="/content/sd_xl_base_1.
                         0.safetensors" --train_data_dir="/content/data"        
                         --resolution="512,512" --output_dir="/content/out"     
                         --save_model_as=safetensors --output_name="last"       
                         --lr_scheduler_num_cycles="1"                          
                         --max_data_loader_n_workers="0" --learning_rate="1e-05"
                         --lr_scheduler="cosine" --lr_warmup_steps="3"          
                         --train_batch_size="1" --max_train_steps="30"          
                         --save_every_n_epochs="1" --mixed_precision="fp16"     
                         --save_precision="fp16" --cache_latents                
                         --optimizer_type="AdamW8bit"                           
                         --max_data_loader_n_workers="0" --bucket_reso_steps=64 
                         --xformers --bucket_no_upscale --noise_offset=0.0      
2023-08-16 23:21:10.317576: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
2023-08-16 23:21:18.523009: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Warning: SDXL has been trained with noise_offset=0.0357 / SDXLはnoise_offset=0.0357で学習されています
noise_offset is set to 0.0 / noise_offsetが0.0に設定されました
prepare tokenizers
Downloading (…)olve/main/vocab.json: 100% 961k/961k [00:00<00:00, 14.8MB/s]
Downloading (…)olve/main/merges.txt: 100% 525k/525k [00:00<00:00, 19.0MB/s]
Downloading (…)cial_tokens_map.json: 100% 389/389 [00:00<00:00, 1.78MB/s]
Downloading (…)okenizer_config.json: 100% 905/905 [00:00<00:00, 3.33MB/s]
Downloading (…)olve/main/vocab.json: 100% 862k/862k [00:00<00:00, 9.25MB/s]
Downloading (…)olve/main/merges.txt: 100% 525k/525k [00:00<00:00, 24.2MB/s]
Downloading (…)cial_tokens_map.json: 100% 389/389 [00:00<00:00, 2.28MB/s]
Downloading (…)okenizer_config.json: 100% 904/904 [00:00<00:00, 5.85MB/s]
Using DreamBooth method.
ignore directory without repeats / 繰り返し回数のないディレクトリを無視します: .ipynb_checkpoints
prepare images.
found directory /content/data/30_elsin contains 1 image files
No caption file found for 1 images. Training will continue without captions for these images. If class token exists, it will be used. / 1枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を続行します。class tokenが存在する場合はそれを使います。
/content/data/30_elsin/caricaturin (1).png
30 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 2048
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "/content/data/30_elsin"
    image_count: 1
    num_repeats: 30
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: elsin
    caption_extension: .caption


[Dataset 0]
loading image sizes.
100% 1/1 [00:00<00:00, 211.78it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (448, 448), count: 30
mean ar error (without repeats): 0.0494233937397035
prepare accelerator
loading model for process 0/1
load StableDiffusion checkpoint: /content/sd_xl_base_1.0.safetensors
building U-Net
loading U-Net from checkpoint
U-Net:  <All keys matched successfully>
building text encoders
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', './sdxl_train.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=/content/sd_xl_base_1.0.safetensors', '--train_data_dir=/content/data', '--resolution=512,512', '--output_dir=/content/out', '--save_model_as=safetensors', '--output_name=last', '--lr_scheduler_num_cycles=1', '--max_data_loader_n_workers=0', '--learning_rate=1e-05', '--lr_scheduler=cosine', '--lr_warmup_steps=3', '--train_batch_size=1', '--max_train_steps=30', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' died with <Signals.SIGKILL: 9>.
```

**Comment by wcurti** [comment]
Did you ever figure this out? I have the same error. I also am using Colab with purchased credits, so it's not just the free tier.

**Comment by wcurti** [comment]
Actually, I've figured it out. It's just an out of RAM error. This script tops out at around 19 gb of RAM, which won't be possible on a pay-as-you-go or free tier of Colab. You need access to the high-RAM machines.

**Comment by drimeF0** [comment]
try use diffusers checkpoints and add `--lowram --network_train_unet_only --cache_text_encoder_outputs` to command line args
![firefox_tEXWANIFqT](https://github.com/bmaltais/kohya_ss/assets/67423319/8e68186b-5e97-4129-aa6f-6561b931009e)

**Comment by loboere** [comment]
> try use diffusers checkpoints and add `--lowram --network_train_unet_only --cache_text_encoder_outputs` to command line args ![firefox_tEXWANIFqT](https://private-user-images.githubusercontent.com/67423319/267303415-8e68186b-5e97-4129-aa6f-6561b931009e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNjg4OTUsIm5iZiI6MTcwNDI2ODU5NSwicGF0aCI6Ii82NzQyMzMxOS8yNjczMDM0MTUtOGU2ODE4NmItNWU5Ny00MTI5LWFhNmYtNjU2MWI5MzEwMDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA3NTYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MjYwNDkxMGQ5ZDNkYzY0NjFiM2RjZDI0YTVmMmZmZTA5NTBkYWZmY2RlYjEzNTkyYWJhMjM3NmFkZTQyOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ovf6NkoJZJFTRqU_1t0HH42hUzLeD79ggLV-1KiPVeA)

Does that work on the free level? If so, where do I put those parameters?
