### ISSUE TITLE
Problem in merging two lora files 

### ISSUE THREAD

**Issue by GabruAru** [bmaltais/kohya_ss#1449]
merging...
Traceback (most recent call last):
  File "/content/sd-scripts/networks/merge_lora.py", line 243, in <module>
    merge(args)
  File "/content/sd-scripts/networks/merge_lora.py", line 199, in merge
    state_dict = merge_lora_models(args.models, args.ratios, merge_dtype)
  File "/content/sd-scripts/networks/merge_lora.py", line 148, in merge_lora_models
    base_alpha = base_alphas[lora_module_name]
KeyError: 'cond_stage_model.transformer.text_model.embeddings.position_embedding.weigh'

**Comment by GabruAru** [comment]
I am trying to merge two files in safetensors format  and i am getting this error 

I used this:

python networks\merge_lora.py
     --save_to ..\lora_train1\model-char1-style1-merged.safetensors
     --models ..\lora_train1\last.safetensors ..\lora_train2\last.safetensors --ratios 0.6 0.4

with my models
