### ISSUE TITLE
LR Scheduler adafactor help needed, or is this an internal error?

### ISSUE THREAD

**Issue by DarkAlchy** [bmaltais/kohya_ss#1494]
Traceback (most recent call last):
  File "F:\kohya_ss-win\sdxl_train.py", line 746, in <module>
    train(args)
  File "F:\kohya_ss-win\sdxl_train.py", line 360, in train
    lr_scheduler = train_util.get_scheduler_fix(args, optimizer, accelerator.num_processes)
  File "F:\kohya_ss-win\library\train_util.py", line 3649, in get_scheduler_fix
    initial_lr = float(name.split(":")[1])
IndexError: list index out of range

What am I missing and need to add as args, or is this an error in the gui?

**Comment by anae-git** [comment]
I fixed this here: https://github.com/bmaltais/kohya_ss/issues/1419#issuecomment-1694876051

Not really sure why this simple fix hasn't been applied yet.

**Comment by DarkAlchy** [comment]
> I fixed this here: [#1419 (comment)](https://github.com/bmaltais/kohya_ss/issues/1419#issuecomment-1694876051)
> 
> Not really sure why this simple fix hasn't been applied yet.

No special args are needed for it to work?

Yeah, This kohya project is falling apart it seems as bmalt must have passed away and Kohya has stepped away it seems as that simple fix/update has not been made.
