### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'model'

### ISSUE THREAD

**Issue by NoteToSelfFindGoodNickname** [bmaltais/kohya_ss#150]
Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loading config...
Folder 54_iconex: 1566 steps
Traceback (most recent call last):
  File "C:\Users\tomwe\Kohya\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\tomwe\Kohya\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\Users\tomwe\Kohya\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\tomwe\Kohya\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\tomwe\Kohya\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\tomwe\Kohya\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\tomwe\Kohya\kohya_ss\dreambooth_gui.py", line 290, in train_model
    repeats = int(folder.split('_')[0])
ValueError: invalid literal for int() with base 10: 'model'

**Comment by NoteToSelfFindGoodNickname** [comment]
It's due to the source model.
But I wonder if it's not possible to catch this error and provide a proper error message.
But perhaps it's just not possible because the script calls other scripts without being able to press its output...

**Comment by Chosen-one-Vault13** [comment]
When you say it's due to the source model could you please elaborate? More people (like myself) can come across the same issue and would be great to understand exactly how to fix the problem
