### ISSUE TITLE
Runpod template gives display error 

### ISSUE THREAD

**Issue by Mocro020** [bmaltais/kohya_ss#1525]
Anyone else ran to this problem and got a fix?

17:47:13-934645 INFO     Version: v21.8.9                                       
                                                                                
17:47:13-939379 INFO     nVidia toolkit detected                                
17:47:15-543025 INFO     Torch 2.0.1+cu118                                      
17:47:15-585258 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700             
17:47:15-611667 INFO     Torch detected GPU: NVIDIA A100 80GB PCIe VRAM 81051   
                         Arch (8, 0) Cores 108                                  
17:47:15-613563 INFO     Verifying modules instalation status from              
                         /workspace/kohya_ss/requirements_runpod.txt...         
17:47:15-617962 INFO     Verifying modules instalation status from              
                         requirements.txt...                                    
no language
17:47:18-557879 INFO     headless: True                                         
17:47:18-562044 INFO     Load CSS...                                            
Running on local URL:  http://0.0.0.0:3011

To create a public link, set `share=True` in `launch()`.
17:57:02-185006 INFO     Loading config...                                      
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1384, in process_api
    result = await self.call_function(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1089, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/utils.py", line 700, in wrapper
    response = f(*args, **kwargs)
  File "/workspace/kohya_ss/library/dreambooth_folder_creation_gui.py", line 52, in dreambooth_folder_preparation
    msgbox('Class prompt missing...')
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/derived_boxes.py", line 230, in msgbox
    return buttonbox(msg=msg,
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 95, in buttonbox
    bb = ButtonBox(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 147, in __init__
    self.ui = GUItk(msg, title, choices, images, default_choice, cancel_choice, self.callback_ui)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 263, in __init__
    self.boxRoot = tk.Tk()
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by ashleykleynhans** [comment]
Don't click on the buttons to load things from disk.  You have to manually enter the path to the JSON files etc and then press the LOAD and SAVE buttons in `--headless` mode.   You can only use those browse buttons to browse your machine when you have a physical display attached, which is not the case with RunPod.

**Comment by Mocro020** [comment]
lol i just told someone today that i should stop pushing buttons.. thx!
