### ISSUE TITLE
DefaultCPUAllocator: not enough memory: you tried to allocate 58982400 bytes.

### ISSUE THREAD

**Issue by eugene2878** [bmaltais/kohya_ss#156]
Can not figure out what problem is. Here is the error
`Folder 150_NkkCS: 1500 steps
max_train_steps = 1500
stop_text_encoder_training = 0
lr_warmup_steps = 150
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --pretrained_model_name_or_path="D:/stable-diffusion-portable-main/models/Stable-diffusion/realisticVisionV13_v13.safetensors" --train_data_dir="D:\kohya_ss\NkkCS_LoRa\img" --resolution=512,512 --output_dir="D:\kohya_ss\NkkCS_LoRa\model" --logging_dir="D:\kohya_ss\NkkCS_LoRa\log" --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=8 --output_name="Nkkcs" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="cosine" --lr_warmup_steps="150" --train_batch_size="1" --max_train_steps="1500" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --seed="1234" --caption_extension=".txt" --cache_latents --bucket_reso_steps=64 --mem_eff_attn --gradient_checkpointing --xformers --bucket_no_upscale
prepare tokenizer
Use DreamBooth method.
prepare train images.
found directory 150_NkkCS contains 10 image files
1500 train images with repeating.
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 1115.30it/s]
prepare dataset
prepare accelerator
Using accelerator 0.15.0 or above.
load StableDiffusion checkpoint
Traceback (most recent call last):
  File "D:\kohya_ss\train_network.py", line 548, in <module>
    train(args)
  File "D:\kohya_ss\train_network.py", line 156, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype)
  File "D:\kohya_ss\library\train_util.py", line 1584, in load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, args.pretrained_model_name_or_path)
  File "D:\kohya_ss\library\model_util.py", line 879, in load_models_from_stable_diffusion_checkpoint
    unet = UNet2DConditionModel(**unet_config)
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\configuration_utils.py", line 567, in inner_init
    init(self, *args, **init_kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 151, in __init__
    down_block = get_down_block(
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 42, in get_down_block
    return DownBlock2D(
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 648, in __init__
    ResnetBlock2D(
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\models\resnet.py", line 414, in __init__
    self.conv2 = torch.nn.Conv2d(out_channels, out_channels, kernel_size=3, stride=1, padding=1)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 444, in __init__
    super(Conv2d, self).__init__(
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 131, in __init__
    self.weight = Parameter(torch.empty(
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 58982400 bytes.
Traceback (most recent call last):
  File "C:\Users\jlari\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jlari\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=D:/stable-diffusion-portable-main/models/Stable-diffusion/realisticVisionV13_v13.safetensors', '--train_data_dir=D:\\kohya_ss\\NkkCS_LoRa\\img', '--resolution=512,512', '--output_dir=D:\\kohya_ss\\NkkCS_LoRa\\model', '--logging_dir=D:\\kohya_ss\\NkkCS_LoRa\\log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=Nkkcs', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=150', '--train_batch_size=1', '--max_train_steps=1500', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.`

**Comment by eugene2878** [comment]
Issue was with low memory of RAM and page memory due to low disk space
