### ISSUE TITLE
exited after this huge error, also no bits and bytes issue

### ISSUE THREAD

**Issue by TanvirHafiz** [bmaltais/kohya_ss#1577]
Traceback (most recent call last):
  File "G:\kohya_ss\train_network.py", line 1006, in <module>
    trainer.train(args)
  File "G:\kohya_ss\train_network.py", line 335, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "G:\kohya_ss\library\train_util.py", line 3412, in get_optimizer
    raise ImportError("No bitsandbytes / bitsandbytesがインストールされていないようです")
ImportError: No bitsandbytes / bitsandbytesがインストールされていないようです
Traceback (most recent call last):
  File "C:\Users\Tanvir\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Tanvir\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Tanvir\AppData\Local\Programs\Python\Python310\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\Tanvir\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\Tanvir\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\Users\Tanvir\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Tanvir\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', './train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=D:\\Work Folder\\Lora Training\\Ankita_lora_training\\img', '--reg_data_dir=D:\\Work Folder\\Lora Training\\Ankita_lora_training\\reg', '--resolution=512,650', '--output_dir=D:\\Work Folder\\Lora Training\\Ankita_lora_training\\model', '--logging_dir=D:\\Work Folder\\Lora Training\\Ankita_lora_training\\log', '--network_alpha=64', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=64', '--output_name=ankita_PC', '--lr_scheduler_num_cycles=1', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=3', '--max_train_steps=480', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--xformers', '--bucket_no_upscale', '--noise_offset=0.05']' returned non-zero exit status 1.

whats the solution?

**Comment by wagesj45** [comment]
I don't think there is one. I think we have to wait until there are some pull requests to get all the requirements fixed. At least that appears to be the case for Linux installs.

**Comment by hughdidit** [comment]
Also waiting for a fix. This is two months old and no one has been assigned to it? True?
