### ISSUE TITLE
Bug: issues with saving state / epoch for any model

### ISSUE THREAD

**Issue by Pychnight** [bmaltais/kohya_ss#1580]
pops up with the following error

`Traceback (most recent call last):
  File "D:\kohya_ss\sdxl_train.py", line 753, in <module>
    train(args)
  File "D:\kohya_ss\sdxl_train.py", line 600, in train
    sdxl_train_util.save_sd_model_on_epoch_end_or_stepwise(
  File "D:\kohya_ss\library\sdxl_train_util.py", line 309, in save_sd_model_on_epoch_end_or_stepwise
    train_util.save_sd_model_on_epoch_end_or_stepwise_common(
  File "D:\kohya_ss\library\train_util.py", line 4173, in save_sd_model_on_epoch_end_or_stepwise_common
    sd_saver(ckpt_file, epoch_no, global_step)
  File "D:\kohya_ss\library\sdxl_train_util.py", line 283, in sd_saver
    sdxl_model_util.save_stable_diffusion_checkpoint(
  File "D:\kohya_ss\library\sdxl_model_util.py", line 516, in save_stable_diffusion_checkpoint
    save_file(state_dict, output_file, metadata)
  File "D:\kohya_ss\venv\lib\site-packages\safetensors\torch.py", line 232, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "D:\kohya_ss\venv\lib\site-packages\safetensors\torch.py", line 402, in _flatten
    return {
  File "D:\kohya_ss\venv\lib\site-packages\safetensors\torch.py", line 406, in <dictcomp>
    "data": _tobytes(v, k),
  File "D:\kohya_ss\venv\lib\site-packages\safetensors\torch.py", line 372, in _tobytes
    return data.tobytes()
MemoryError
steps:   0%|▏                                             | 50000/16257000 [14:00:08<4538:41:17,  1.01s/it, loss=0.103]
Traceback (most recent call last):
  File "C:\Users\war45\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\war45\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohya_ss\\venv\\Scripts\\python.exe', './sdxl_train.py', '--pretrained_model_name_or_path=D:/SDXL-512', '--train_data_dir=D:/anime/data/SD512', '--resolution=1024', '--output_dir=./output/Speed_test2', '--logging_dir=./output/animeXL/logs', '--save_model_as=safetensors', '--full_bf16', '--output_name=AnimeXtremeXL_Overtraining_test', '--lr_scheduler_num_cycles=50', '--max_data_loader_n_workers=32', '--learning_rate=4e-05', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=16257000', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--cache_latents', '--cache_latents_to_disk', '--optimizer_type=Adafactor', '--optimizer_args', 'scale_parameter=False', 'relative_step=False', 'warmup_init=False', 'weight_decay=0.01', '--max_data_loader_n_workers=32', '--bucket_reso_steps=64', '--save_every_n_steps=50000', '--save_state', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0', '--sample_sampler=euler_a', '--sample_prompts=./output/Speed_test2\\sample\\prompt.txt', '--sample_every_n_epochs=1', '--sample_every_n_steps=50000']' returned non-zero exit status 1.`

so, ended with 18 hours down the drain when it attempted to save the state, i mostly do this just to check on how training is progressing. it might be a issue that i have both steps and epochs set, but it should be supported.

and as for what it seems to have run into was a "memory" error, i'm running a geforce 4090 and my ram is 32 GB, I will be upgrading my system soon to 128 GB with a newer cpu to try to resolve this memory issue.

The model i'm using is a newer model of SDXL that was recently released with support for 512 standard images and produce good quality.

I have done the following tests

1- create a data set with a large set of images as a test
2- test the large data with batch 1.
3- create a small data set with roughly 20 images and no reg
4- test batch 1 with 1 data loader runs

seems like both small and large data sets run into the same issue, even with a 1 data loader defined.

it seems "batch" training is also kinda screwy as it seems to run out of vram even with 2 batch set with a very small data set, so likely been testing, the data loaders might of been set too high for this run, maybe we can improve the script to try to reduce the data loaders before aborting the training if the model can't fit into the ram?

**Comment by ude6** [comment]
Hi,
did you find a solution ?
I have the same error here.


Traceback (most recent call last):
  File "D:\diffusion\train\kohya\kohya_ss\sdxl_train.py", line 753, in <module>
    train(args)
  File "D:\diffusion\train\kohya\kohya_ss\sdxl_train.py", line 600, in train
    sdxl_train_util.save_sd_model_on_epoch_end_or_stepwise(
  File "D:\diffusion\train\kohya\kohya_ss\library\sdxl_train_util.py", line 309, in save_sd_model_on_epoch_end_or_stepwise
    train_util.save_sd_model_on_epoch_end_or_stepwise_common(
  File "D:\diffusion\train\kohya\kohya_ss\library\train_util.py", line 4182, in save_sd_model_on_epoch_end_or_stepwise_common
    sd_saver(ckpt_file, epoch_no, global_step)
  File "D:\diffusion\train\kohya\kohya_ss\library\sdxl_train_util.py", line 283, in sd_saver
    sdxl_model_util.save_stable_diffusion_checkpoint(
  File "D:\diffusion\train\kohya\kohya_ss\library\sdxl_model_util.py", line 516, in save_stable_diffusion_checkpoint
    save_file(state_dict, output_file, metadata)
  File "D:\diffusion\train\kohya\kohya_ss\venv\Lib\site-packages\safetensors\torch.py", line 232, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
safetensors_rust.SafetensorError: Error while serializing: IoError(Os { code: 1224, kind: Uncategorized, message: "Der Vorgang ist bei einer Datei mit einem geöffneten Bereich, der einem Benutzer zugeordnet ist, nicht anwendbar." })

**Comment by Pychnight** [comment]
no, i have not solved this... i have only managed to confirm don't use save steps on kohya_ss repo, it does not function properly.

I have been testing training for the last week, trying to find out why SDXL was not adapting to concepts correctly, I found it seems like every time it creates a save step it might be resetting training back to then retraining a specific number of concepts.

so, i tested and tested... I created 1 model that had saved every 5000 steps, 10000 steps, then lastly 1 epoch save

I found that saving every epoch seemed to produce the best results, Overall the save state training seems to be really broken and seems to not get any progress regardless the amount of steps it's been training on.

...

What, i would like the save steps script to do... is remember the amount of steps put into the model and text encoder information,
and ensuring if saving at steps ensure the model continues to train the rest of the data set instead of getting stuck at the first section then saving then repeating the same section over and over. (at least that's what it looks like it's doing... cause i got samples of images at each section of my data set to find out just how far it's trained.


overall, don't use both steps and epochs use one or the other, i personally recommend epochs, i know they take longer but it will adapt better.

**Comment by sebaxakerhtc** [comment]
This issue was closed as completed, but where's the solution?
Just happened this "MemoryError" and saving model doesn't work anymore.
ReCloned repo and still the same

**Comment by bmaltais** [comment]
I closed a whole bunch of old issues. I can’t fix those ones because it is related to the scripts written by Koby’s that I call from the gui. Nothing I can do about them.

**Comment by sebaxakerhtc** [comment]
@Pychnight, @ude6, @bmaltais 
I have to found the solution by setting pagefile min 51200 max 102400 (maybe it can be setted to smaller size - idk, but I have that space on my SSD)
