### ISSUE TITLE
loading manually kohya_ss on runpod with error on training start

### ISSUE THREAD

**Issue by eyalgi11** [bmaltais/kohya_ss#1615]
i followed the steps in runpod manual installation and when I start training my lora it give me an error

```python
09:57:50-144511 INFO     Headless mode, skipping verification if model already exist... if model already exist it will be overwritten...                                                    
09:57:50-146670 INFO     Folder 20_angourie rice woman : steps 300                                                                                                                          
09:57:50-147661 INFO     Regularisation images are used... Will double the number of steps required...                                                                                      
09:57:50-148414 INFO     max_train_steps (300 / 1 / 1 * 10 * 2) = 6000                                                                                                                      
09:57:50-149220 INFO     stop_text_encoder_training = 0                                                                                                                                     
09:57:50-149863 INFO     lr_warmup_steps = 0                                                                                                                                                
09:57:50-150591 INFO     Saving training config to /workspace/Output/model/anna_sinyakina-angourie_rice_20231016-095750.json...                                                             
09:57:50-151511 INFO     accelerate launch --num_cpu_threads_per_process=2 "./sdxl_train.py" --enable_bucket --min_bucket_reso=256 --max_bucket_reso=2048                                   
                         --pretrained_model_name_or_path="/workspace/SD_XLv1.0VAEfix" --train_data_dir="/workspace/Output/img" --reg_data_dir="/workspace/Output/reg"                       
                         --resolution="1024,1024" --output_dir="/workspace/Output/model" --logging_dir="/workspace/Output/log" --save_model_as=safetensors                                  
                         --output_name="anna_sinyakina-angourie_rice" --lr_scheduler_num_cycles="10" --max_data_loader_n_workers="0" --learning_rate="0.0003" --lr_scheduler="constant"     
                         --train_batch_size="1" --max_train_steps="6000" --save_every_n_epochs="1" --mixed_precision="bf16" --save_precision="bf16" --caption_extension=".txt"              
                         --cache_latents --cache_latents_to_disk --optimizer_type="Adafactor" --optimizer_args scale_parameter=False relative_step=False warmup_init=False                  
                         --max_data_loader_n_workers="0" --bucket_reso_steps=64 --gradient_checkpointing --xformers --bucket_no_upscale --noise_offset=0.0                                  
2023-10-16 09:57:53.354358: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-16 09:57:53.354389: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-16 09:57:53.354405: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-16 09:57:53.359106: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-16 09:57:54.122012: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
prepare tokenizers
Using DreamBooth method.
prepare images.
found directory /workspace/Output/img/20_angourie rice woman contains 15 image files
found directory /workspace/Output/reg/1_woman contains 1000 image files
No caption file found for 1000 images. Training will continue without captions for these images. If class token exists, it will be used. / 1000枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を続行します。class tokenが存在する場合はそれを使います。
/workspace/Output/reg/1_woman/woman_0001.jpg
/workspace/Output/reg/1_woman/woman_0002.jpg
/workspace/Output/reg/1_woman/woman_0003.jpg
/workspace/Output/reg/1_woman/woman_0004.jpg
/workspace/Output/reg/1_woman/woman_0005.jpg
/workspace/Output/reg/1_woman/woman_0006.jpg... and 995 more
300 train images with repeating.
1000 reg images.
some of reg images are not used / 正則化画像の数が多いので、一部使用されない正則化画像があります
[Dataset 0]
  batch_size: 1
  resolution: (1024, 1024)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 2048
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "/workspace/Output/img/20_angourie rice woman"
    image_count: 15
    num_repeats: 20
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: angourie rice woman
    caption_extension: .txt

  [Subset 1 of Dataset 0]
    image_dir: "/workspace/Output/reg/1_woman"
    image_count: 1000
    num_repeats: 1
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: True
    class_tokens: woman
    caption_extension: .txt


[Dataset 0]
loading image sizes.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 315/315 [00:00<00:00, 7310.83it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (832, 1024), count: 20
bucket 1: resolution (832, 1088), count: 40
bucket 2: resolution (832, 1216), count: 20
bucket 3: resolution (1024, 1024), count: 300
bucket 4: resolution (1088, 832), count: 20
bucket 5: resolution (1088, 896), count: 20
bucket 6: resolution (1088, 960), count: 20
bucket 7: resolution (1152, 832), count: 40
bucket 8: resolution (1152, 896), count: 20
bucket 9: resolution (1216, 768), count: 20
bucket 10: resolution (1216, 832), count: 20
bucket 11: resolution (1344, 768), count: 60
mean ar error (without repeats): 0.0007480784361696039
prepare accelerator
loading model for process 0/1
load StableDiffusion checkpoint: /workspace/SD_XLv1.0VAEfix
Traceback (most recent call last):
  File "/workspace/kohya_ss/./sdxl_train.py", line 753, in <module>
    train(args)
  File "/workspace/kohya_ss/./sdxl_train.py", line 216, in train
    ) = sdxl_train_util.load_target_model(args, accelerator, "sdxl", weight_dtype)
  File "/workspace/kohya_ss/library/sdxl_train_util.py", line 34, in load_target_model
    ) = _load_target_model(
  File "/workspace/kohya_ss/library/sdxl_train_util.py", line 75, in _load_target_model
    ) = sdxl_model_util.load_models_from_sdxl_checkpoint(model_version, name_or_path, device, model_dtype)
  File "/workspace/kohya_ss/library/sdxl_model_util.py", line 175, in load_models_from_sdxl_checkpoint
    checkpoint = torch.load(ckpt_path, map_location=map_location)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x04'.
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/workspace/kohya_ss/venv/bin/python', './sdxl_train.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=/workspace/SD_XLv1.0VAEfix', '--train_data_dir=/workspace/Output/img', '--reg_data_dir=/workspace/Output/reg', '--resolution=1024,1024', '--output_dir=/workspace/Output/model', '--logging_dir=/workspace/Output/log', '--save_model_as=safetensors', '--output_name=anna_sinyakina-angourie_rice', '--lr_scheduler_num_cycles=10', '--max_data_loader_n_workers=0', '--learning_rate=0.0003', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=6000', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--caption_extension=.txt', '--cache_latents', '--cache_latents_to_disk', '--optimizer_type=Adafactor', '--optimizer_args', 'scale_parameter=False', 'relative_step=False', 'warmup_init=False', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

```

**Comment by ashleykleynhans** [comment]
Looks like there is an issue with your base model based on the **UnpicklingError**.

Why do you manually install it rather than using the existing templates on RunPod out of interest?
