### ISSUE TITLE
 timm==0.6.12 results in error when trying to train a lora reverted back to  timm==0.6.7

### ISSUE THREAD

**Issue by plaidpants** [bmaltais/kohya_ss#1622]
I get this error on windows if I use 0.6.12, reverting to 0.6.7 allows it to work.

ValueError: mutable default <class 'timm.models.maxxvit.MaxxVitConvCfg'> for field conv_cfg is not allowed: use default_factory

See similar issue here.

https://github.com/Fannovel16/comfy_controlnet_preprocessors/issues/28

full trace
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "T:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 4, in <module>
  File "T:\kohya_ss\venv\Lib\site-packages\accelerate\commands\accelerate_cli.py", line 21, in <module>
    from accelerate.commands.estimate import estimate_command_parser
  File "T:\kohya_ss\venv\Lib\site-packages\accelerate\commands\estimate.py", line 35, in <module>
    import timm
  File "T:\kohya_ss\venv\Lib\site-packages\timm\__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "T:\kohya_ss\venv\Lib\site-packages\timm\models\__init__.py", line 28, in <module>
    from .maxxvit import *
  File "T:\kohya_ss\venv\Lib\site-packages\timm\models\maxxvit.py", line 225, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Python311\Lib\dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Python311\Lib\dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'timm.models.maxxvit.MaxxVitConvCfg'> for field conv_cfg is not allowed: use default_factory

**Comment by madrooky** [comment]
I get the very same Error on my first steps using Kohya.
I was trying to start regular dreambooth training.
Reverting to 0.6.7 fixed the issue.
