### ISSUE TITLE
Error messages in command window after rtaining starts

### ISSUE THREAD

**Issue by digitalascension1** [bmaltais/kohya_ss#1630]
I get this message in the command window after I click the training button in Kohya SS

prepare tokenizer
Traceback (most recent call last):
  File "C:\Kohya\kohya_ss\train_network.py", line 1009, in <module>
    trainer.train(args)
  File "C:\Kohya\kohya_ss\train_network.py", line 144, in train
    tokenizer = self.load_tokenizer(args)
  File "C:\Kohya\kohya_ss\train_network.py", line 105, in load_tokenizer
    tokenizer = train_util.load_tokenizer(args)
  File "C:\Kohya\kohya_ss\library\train_util.py", line 3744, in load_tokenizer
    tokenizer = CLIPTokenizer.from_pretrained(original_path)
  File "C:\Kohya\kohya_ss\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1784, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "C:\Kohya\kohya_ss\venv\lib\site-packages\transformers\utils\hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Kohya\kohya_ss\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Kohya\kohya_ss\venv\lib\site-packages\huggingface_hub\file_download.py", line 1308, in hf_hub_download
    _cache_commit_hash_for_specific_revision(storage_folder, revision, commit_hash)
  File "C:\Kohya\kohya_ss\venv\lib\site-packages\huggingface_hub\file_download.py", line 941, in _cache_commit_hash_for_specific_revision
    ref_path.write_text(commit_hash)
  File "C:\Users\erikc\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "C:\Users\erikc\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\erikc\\.cache\\huggingface\\hub\\models--openai--clip-vit-large-patch14\\refs\\main'
Traceback (most recent call last):
  File "C:\Users\erikc\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\erikc\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', './train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=C:/AutoSD/stable-diffusion-webui/models/Stable-diffusion/realcartoonRealistic_v8.safetensors', '--train_data_dir=C:/Users/erikc/Downloads/grace_training\\img', '--reg_data_dir=C:/Users/erikc/Downloads/grace_training\\reg', '--resolution=768,768', '--output_dir=C:/Users/erikc/Downloads/grace_training\\model', '--logging_dir=C:/Users/erikc/Downloads/grace_training\\log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=128', '--output_name=grace', '--lr_scheduler_num_cycles=10', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=2480', '--train_batch_size=1', '--max_train_steps=24800', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

I know others have had this same issue but I don't understand how to fix the problem. Sorry.

**Comment by coinselor** [comment]
Had the same issue. I followed the steps in https://github.com/bmaltais/kohya_ss/issues/548 and got it to work.

Basically, clear the hugginface/clip folders inside user/.cache
