### ISSUE TITLE
Docker method: xFormers can't load C++/CUDA extensions / xFormers wasn't build with CUDA support

### ISSUE THREAD

**Issue by dougbtv** [bmaltais/kohya_ss#1651]
I think the core of the error is:

```
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.1.0+cu121)
    Python  3.10.11 (you have 3.10.11)
```

I built the image against the `Dockerfile` @ HEAD.

I also tried to uncomment the line:

```
RUN python3 -m pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
```

But this is also failing.

Full log follows

```
=============
== PyTorch ==
=============

NVIDIA Release 23.04 (build 58180998)
PyTorch Version 2.1.0a0+fe05266

Container image Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

Copyright (c) 2014-2023 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.7) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
18:54:59-024241 INFO     headless: False                                                                                  
18:54:59-027373 INFO     Load CSS...                                                                                      
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
18:55:26-255073 INFO     Start training LoRA Standard ...                                                                 
18:55:26-256901 INFO     Checking for duplicate image filenames in training data directory...                             
18:55:26-263202 INFO     Valid image folder names found in: /dataset/mylora2/images/                            
18:55:26-266091 INFO     Folder 50_mylora: 378 images found                                                     
18:55:26-267730 INFO     Folder 50_mylora: 18900 steps                                                          
18:55:26-269389 INFO     Total steps: 18900                                                                               
18:55:26-270813 INFO     Train batch size: 1                                                                              
18:55:26-272227 INFO     Gradient accumulation steps: 1                                                                   
18:55:26-273637 INFO     Epoch: 10                                                                                        
18:55:26-274989 INFO     Regulatization factor: 1                                                                         
18:55:26-276417 INFO     max_train_steps (18900 / 1 / 1 * 10 * 1) = 189000                                                
18:55:26-278316 INFO     stop_text_encoder_training = 0                                                                   
18:55:26-279742 INFO     lr_warmup_steps = 0                                                                              
18:55:26-281291 INFO     Saving training config to                                                                        
                         /dataset/mylora2/model/myloraxl_v1_20231101-185526.json...                   
18:55:26-283461 INFO     accelerate launch --num_cpu_threads_per_process=2 "./sdxl_train_network.py" --enable_bucket      
                         --min_bucket_reso=256 --max_bucket_reso=2048                                                     
                         --pretrained_model_name_or_path="/models/sd_xl_base_1.0.safetensors"                             
                         --train_data_dir="/dataset/mylora2/images/" --resolution="1024,1024"                   
                         --output_dir="/dataset/mylora2/model" --logging_dir="/dataset/mylora2/log"   
                         --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora                   
                         --text_encoder_lr=0.0004 --unet_lr=0.0004 --network_dim=256 --output_name="myloraxl_v1"
                         --lr_scheduler_num_cycles="10" --no_half_vae --learning_rate="0.0004" --lr_scheduler="constant"  
                         --train_batch_size="1" --max_train_steps="189000" --save_every_n_epochs="1"                      
                         --mixed_precision="fp16" --save_precision="fp16" --cache_latents --cache_latents_to_disk         
                         --optimizer_type="Adafactor" --optimizer_args scale_parameter=False relative_step=False          
                         warmup_init=False --max_data_loader_n_workers="0" --bucket_reso_steps=64 --xformers              
                         --bucket_no_upscale --noise_offset=0.0                                                           
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.7) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.7) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.1.0+cu121)
    Python  3.10.11 (you have 3.10.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
prepare tokenizers
Downloading (…)olve/main/vocab.json: 100%|█████████████████████████████████████████████| 961k/961k [00:00<00:00, 16.8MB/s]
Downloading (…)olve/main/merges.txt: 100%|█████████████████████████████████████████████| 525k/525k [00:00<00:00, 15.8MB/s]
Downloading (…)cial_tokens_map.json: 100%|███████████████████████████████████████████████| 389/389 [00:00<00:00, 3.15MB/s]
Downloading (…)okenizer_config.json: 100%|███████████████████████████████████████████████| 905/905 [00:00<00:00, 5.63MB/s]
Downloading (…)olve/main/vocab.json: 100%|█████████████████████████████████████████████| 862k/862k [00:00<00:00, 17.6MB/s]
Downloading (…)olve/main/merges.txt: 100%|█████████████████████████████████████████████| 525k/525k [00:00<00:00, 39.8MB/s]
Downloading (…)cial_tokens_map.json: 100%|███████████████████████████████████████████████| 389/389 [00:00<00:00, 2.53MB/s]
Downloading (…)okenizer_config.json: 100%|███████████████████████████████████████████████| 904/904 [00:00<00:00, 5.44MB/s]
Using DreamBooth method.
prepare images.
found directory /dataset/mylora2/images/50_mylora contains 378 image files
No caption file found for 378 images. Training will continue without captions for these images. If class token exists, it will be used. / 378枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を続行します。class tokenが存在する場合はそれを使います。
/dataset/mylora2/images/50_mylora/2018-04-24_04-46-18_UTC.jpg
/dataset/mylora2/images/50_mylora/2018-04-25_04-07-28_UTC.jpg
/dataset/mylora2/images/50_mylora/2018-04-26_07-16-15_UTC.jpg
/dataset/mylora2/images/50_mylora/2018-04-28_06-47-19_UTC.jpg
/dataset/mylora2/images/50_mylora/2018-05-02_23-41-40_UTC.jpg
/dataset/mylora2/images/50_mylora/2018-05-26_08-50-43_UTC.jpg... and 373 more
18900 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (1024, 1024)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 2048
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "/dataset/mylora2/images/50_mylora"
    image_count: 378
    num_repeats: 50
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: mylora
    caption_extension: .caption


[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 378/378 [00:00<00:00, 14555.67it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (896, 1024), count: 50
bucket 1: resolution (896, 1088), count: 17150
bucket 2: resolution (960, 960), count: 550
bucket 3: resolution (1024, 1024), count: 1150
mean ar error (without repeats): 0.020873662245654546
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: /models/sd_xl_base_1.0.safetensors
building U-Net
loading U-Net from checkpoint
U-Net:  <All keys matched successfully>
building text encoders
loading text encoders from checkpoint
text encoder 1: <All keys matched successfully>
text encoder 2: <All keys matched successfully>
building VAE
loading VAE from checkpoint
VAE: <All keys matched successfully>
Enable xformers for U-Net
Traceback (most recent call last):
  File "/app/./sdxl_train_network.py", line 183, in <module>
    trainer.train(args)
  File "/app/train_network.py", line 232, in train
    vae.set_use_memory_efficient_attention_xformers(args.xformers)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 251, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 244, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 216, in set_use_memory_efficient_attention_xformers
    raise e
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 210, in set_use_memory_efficient_attention_xformers
    _ = xformers.ops.memory_efficient_attention(
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py", line 192, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py", line 290, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py", line 306, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp)
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/dispatch.py", line 94, in _dispatch_fw
    return _run_priority_list(
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/dispatch.py", line 69, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 2, 1, 40) (torch.float32)
     key         : shape=(1, 2, 1, 40) (torch.float32)
     value       : shape=(1, 2, 1, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    Operator wasn't built - see `python -m xformers.info` for more info
`tritonflashattF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    requires A100 GPU
    Only work on pre-MLIR triton for now
`cutlassF` is not supported because:
    xFormers wasn't build with CUDA support
    Operator wasn't built - see `python -m xformers.info` for more info
`smallkF` is not supported because:
    xFormers wasn't build with CUDA support
    max(query.shape[-1] != value.shape[-1]) > 32
    Operator wasn't built - see `python -m xformers.info` for more info
    unsupported embed per head: 40
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', './sdxl_train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=/models/sd_xl_base_1.0.safetensors', '--train_data_dir=/dataset/mylora2/images/', '--resolution=1024,1024', '--output_dir=/dataset/mylora2/model', '--logging_dir=/dataset/mylora2/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=0.0004', '--unet_lr=0.0004', '--network_dim=256', '--output_name=myloraxl_v1', '--lr_scheduler_num_cycles=10', '--no_half_vae', '--learning_rate=0.0004', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=189000', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--cache_latents_to_disk', '--optimizer_type=Adafactor', '--optimizer_args', 'scale_parameter=False', 'relative_step=False', 'warmup_init=False', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

```

**Comment by dougbtv** [comment]
I was able to at least get the xformers deps to be fixed with:

```diff
diff --git a/requirements.txt b/requirements.txt
index 216e961..d04c753 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,4 +1,4 @@
-accelerate==0.23.0
+# accelerate==0.23.0
 # albumentations==1.3.0
 aiofiles==23.2.1
 altair==4.2.2
diff --git a/requirements_linux_docker.txt b/requirements_linux_docker.txt
index bc936c4..84a2281 100644
--- a/requirements_linux_docker.txt
+++ b/requirements_linux_docker.txt
@@ -1,5 +1,5 @@
-xformers==0.0.20
+xformers==0.0.22.post7 --index-url https://download.pytorch.org/whl/cu118
 bitsandbytes==0.41.1
-accelerate==0.19.0
+accelerate==0.24.1
 tensorboard==2.14.1
 tensorflow==2.14.0
```

However, on a run that now results in:

```
epoch 1/10
Traceback (most recent call last):
  File "/app/./sdxl_train_network.py", line 183, in <module>
    trainer.train(args)
  File "/app/train_network.py", line 817, in train
    accelerator.backward(loss)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1987, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
steps:   0%|                                                                                   | 0/189000 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 994, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 636, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
```

**Comment by RealBeyondMaster** [comment]
Same fo rme, doesn't run anymore.

**Comment by dougbtv** [comment]
Found report and reference to the "unable to register cuDNN factory" in https://github.com/tensorflow/tensorflow/issues/62075

**Comment by dougbtv** [comment]
I was able to get a run started where I got 90 steps before I ran into an out of VRAM condition, a la `torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 40.00 MiB. GPU 0 has a total capacty of 23.69 GiB of which 33.31 MiB is free.`

I used the recommendation from the tensorflow issue above to install `tensorflow[and-cuda]` and while the `"unable to register cuDNN factory"` errors persist, previously it would bail out before the first training step was processed.

Here's the diff I have:

```diff
diff --git a/requirements.txt b/requirements.txt
index 216e961..d04c753 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,4 +1,4 @@
-accelerate==0.23.0
+# accelerate==0.23.0
 # albumentations==1.3.0
 aiofiles==23.2.1
 altair==4.2.2
diff --git a/requirements_linux_docker.txt b/requirements_linux_docker.txt
index bc936c4..38c44ae 100644
--- a/requirements_linux_docker.txt
+++ b/requirements_linux_docker.txt
@@ -1,5 +1,5 @@
-xformers==0.0.20
+xformers==0.0.22.post7 --index-url https://download.pytorch.org/whl/cu118
 bitsandbytes==0.41.1
-accelerate==0.19.0
+accelerate==0.24.1
 tensorboard==2.14.1
-tensorflow==2.14.0
+tensorflow[and-cuda]==2.14.0
```

**Comment by dougbtv** [comment]
Maybe not entirely relevant, but I was able to reduce memory consumption using tips from https://github.com/kohya-ss/sd-scripts/issues/627

```json
{
  "LoRA_type": "Standard",
  "adaptive_noise_scale": 0,
  "additional_parameters": "",
  "block_alphas": "",
  "block_dims": "",
  "block_lr_zero_threshold": "",
  "bucket_no_upscale": true,
  "bucket_reso_steps": 64,
  "cache_latents": true,
  "cache_latents_to_disk": true,
  "caption_dropout_every_n_epochs": 0.0,
  "caption_dropout_rate": 0,
  "caption_extension": "",
  "clip_skip": "1",
  "color_aug": false,
  "conv_alpha": 1,
  "conv_block_alphas": "",
  "conv_block_dims": "",
  "conv_dim": 1,
  "decompose_both": false,
  "dim_from_weights": false,
  "down_lr_weight": "",
  "enable_bucket": true,
  "epoch": 10,
  "factor": -1,
  "flip_aug": false,
  "full_bf16": false,
  "full_fp16": true,
  "gradient_accumulation_steps": "1",
  "gradient_checkpointing": true,
  "keep_tokens": "0",
  "learning_rate": 0.0004,
  "logging_dir": "/dataset/mylora2/log",
  "lora_network_weights": "",
  "lr_scheduler": "constant",
  "lr_scheduler_args": "",
  "lr_scheduler_num_cycles": "",
  "lr_scheduler_power": "",
  "lr_warmup": 0,
  "max_bucket_reso": 2048,
  "max_data_loader_n_workers": "0",
  "max_resolution": "1024,1024",
  "max_timestep": 1000,
  "max_token_length": "75",
  "max_train_epochs": "",
  "max_train_steps": "",
  "mem_eff_attn": false,
  "mid_lr_weight": "",
  "min_bucket_reso": 256,
  "min_snr_gamma": 0,
  "min_timestep": 0,
  "mixed_precision": "fp16",
  "model_list": "custom",
  "module_dropout": 0,
  "multires_noise_discount": 0,
  "multires_noise_iterations": 0,
  "network_alpha": 1,
  "network_dim": 256,
  "network_dropout": 0,
  "no_token_padding": false,
  "noise_offset": 0,
  "noise_offset_type": "Original",
  "num_cpu_threads_per_process": 2,
  "optimizer": "Adafactor",
  "optimizer_args": "scale_parameter=False relative_step=False warmup_init=False",
  "output_dir": "/dataset/mylora2/model",
  "output_name": "myloraxl_v1",
  "persistent_data_loader_workers": false,
  "pretrained_model_name_or_path": "/models/sd_xl_base_1.0.safetensors",
  "prior_loss_weight": 1.0,
  "random_crop": false,
  "rank_dropout": 0,
  "reg_data_dir": "",
  "resume": "",
  "sample_every_n_epochs": 0,
  "sample_every_n_steps": 0,
  "sample_prompts": "",
  "sample_sampler": "euler_a",
  "save_every_n_epochs": 1,
  "save_every_n_steps": 0,
  "save_last_n_steps": 0,
  "save_last_n_steps_state": 0,
  "save_model_as": "safetensors",
  "save_precision": "fp16",
  "save_state": false,
  "scale_v_pred_loss_like_noise_pred": false,
  "scale_weight_norms": 0,
  "sdxl": true,
  "sdxl_cache_text_encoder_outputs": false,
  "sdxl_no_half_vae": true,
  "seed": "",
  "shuffle_caption": false,
  "stop_text_encoder_training": 0,
  "text_encoder_lr": 0.0004,
  "train_batch_size": 1,
  "train_data_dir": "/dataset/mylora2/images/",
  "train_on_input": true,
  "training_comment": "",
  "unet_lr": 0.0004,
  "unit": 1,
  "up_lr_weight": "",
  "use_cp": false,
  "use_wandb": false,
  "v2": false,
  "v_parameterization": false,
  "v_pred_like_loss": 0,
  "vae_batch_size": 0,
  "wandb_api_key": "",
  "weighted_captions": false,
  "xformers": "xformers"
}
```

and this run command:

```
accelerate launch --num_cpu_threads_per_process=2 "./sdxl_train_network.py" --enable_bucket               
                         --min_bucket_reso=256 --max_bucket_reso=2048                                                              
                         --pretrained_model_name_or_path="/models/sd_xl_base_1.0.safetensors"                                      
                         --train_data_dir="/dataset/mylora2/images/" --resolution="1024,1024"                            
                         --output_dir="/dataset/mylora2/model" --logging_dir="/dataset/mylora2/log"            
                         --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=0.0004   
                         --unet_lr=0.0004 --network_dim=256 --output_name="myloraxl_v1" --lr_scheduler_num_cycles="4"    
                         --no_half_vae --learning_rate="0.0004" --lr_scheduler="constant" --train_batch_size="1"                   
                         --max_train_steps="75600" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16"      
                         --cache_latents --cache_latents_to_disk --optimizer_type="Adafactor" --optimizer_args                     
                         scale_parameter=False relative_step=False warmup_init=False --max_data_loader_n_workers="0"               
                         --bucket_reso_steps=64 --gradient_checkpointing --full_fp16 --xformers --bucket_no_upscale                
                         --noise_offset=0.0 
```

**Comment by TinJieWang** [comment]
I seem to have encountered the same issue as you, but it was resolved by using `pip install xformers` in docker. I'm not sure if this can solve your problem.
Here is the requirements from docker
```
absl-py==2.0.0
accelerate==0.23.0
aiofiles==23.2.1
aiohttp==3.8.6
aiosignal==1.3.1
altair==4.2.2
annotated-types==0.6.0
anyio==3.7.1
appdirs==1.4.4
astunparse==1.6.3
async-timeout==4.0.3
attrs==23.1.0
bitsandbytes==0.41.1
cachetools==5.3.2
certifi==2019.11.28
chardet==3.0.4
charset-normalizer==3.3.2
click==8.1.7
cmake==3.27.7
coloredlogs==15.0.1
contourpy==1.1.1
cycler==0.12.1
dadaptation==3.1
dbus-python==1.2.16
diffusers==0.21.4
distro-info==0.23+ubuntu1.1
docker-pycreds==0.4.0
easygui==0.98.3
einops==0.6.0
entrypoints==0.4
exceptiongroup==1.1.3
fairscale==0.4.13
fastapi==0.104.1
ffmpy==0.3.1
filelock==3.13.1
flatbuffers==23.5.26
fonttools==4.43.1
frozenlist==1.4.0
fsspec==2023.10.0
ftfy==6.1.1
gast==0.5.4
gitdb==4.0.11
GitPython==3.1.40
google-auth==2.23.4
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
gradio==3.36.1
gradio_client==0.7.0
grpcio==1.59.2
h11==0.14.0
h5py==3.10.0
html5lib==1.0.1
httpcore==0.18.0
httpx==0.25.0
huggingface-hub==0.15.1
humanfriendly==10.0
idna==2.8
importlib-metadata==6.8.0
invisible-watermark==0.2.0
Jinja2==3.1.2
jsonschema==4.19.2
jsonschema-specifications==2023.7.1
keras==2.14.0
kiwisolver==1.4.5
libclang==16.0.6
# Editable Git install with no remote (library==1.0.3)
-e /app
lightning-utilities==0.9.0
linkify-it-py==2.0.2
lion-pytorch==0.0.6
lit==17.0.4
lycoris-lora==1.9.0
Markdown==3.5.1
markdown-it-py==2.2.0
MarkupSafe==2.1.3
matplotlib==3.8.1
mdit-py-plugins==0.3.3
mdurl==0.1.2
ml-dtypes==0.2.0
mpmath==1.3.0
multidict==6.0.4
mypy-extensions==1.0.0
networkx==3.2.1
numpy==1.26.1
nvidia-cublas-cu11==[11.10.3.66](http://11.10.3.66/)
nvidia-cublas-cu12==[12.1.3.1](http://12.1.3.1/)
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu11==[8.5.0.96](http://8.5.0.96/)
nvidia-cudnn-cu12==[8.9.2.26](http://8.9.2.26/)
nvidia-cufft-cu11==[10.9.0.58](http://10.9.0.58/)
nvidia-cufft-cu12==[11.0.2.54](http://11.0.2.54/)
nvidia-curand-cu11==[10.2.10.91](http://10.2.10.91/)
nvidia-curand-cu12==[10.3.2.106](http://10.3.2.106/)
nvidia-cusolver-cu11==[11.4.0.1](http://11.4.0.1/)
nvidia-cusolver-cu12==[11.4.5.107](http://11.4.5.107/)
nvidia-cusparse-cu11==[11.7.4.91](http://11.7.4.91/)
nvidia-cusparse-cu12==[12.1.0.106](http://12.1.0.106/)
nvidia-nccl-cu11==2.14.3
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.52
nvidia-nvtx-cu11==11.7.91
nvidia-nvtx-cu12==12.1.105
oauthlib==3.2.2
onnx==1.14.1
onnxruntime-gpu==1.16.0
open-clip-torch==2.20.0
opencv-python==[4.7.0.68](http://4.7.0.68/)
opt-einsum==3.3.0
orjson==3.9.10
packaging==23.2
pandas==2.1.2
pathtools==0.1.2
Pillow-SIMD==9.0.0.post1
prodigyopt==1.0
protobuf==3.20.3
psutil==5.9.6
pyasn1==0.5.0
pyasn1-modules==0.3.0
pydantic==2.4.2
pydantic_core==2.10.1
pydub==0.25.1
Pygments==2.16.1
PyGObject==3.36.0
pyparsing==3.1.1
pyre-extensions==0.0.29
python-apt==2.0.1+ubuntu0.20.4.1
python-dateutil==2.8.2
python-multipart==0.0.6
pytorch-lightning==1.9.0
pytz==2023.3.post1
PyWavelets==1.4.1
PyYAML==6.0.1
referencing==0.30.2
regex==2023.10.3
requests==2.22.0
requests-oauthlib==1.3.1
requests-unixsocket==0.2.0
rich==13.4.1
rpds-py==0.10.6
rsa==4.9
safetensors==0.3.1
scipy==1.11.3
semantic-version==2.10.0
sentencepiece==0.1.99
sentry-sdk==1.33.1
setproctitle==1.3.3
six==1.14.0
smmap==5.0.1
sniffio==1.3.0
starlette==0.27.0
sympy==1.12
tensorboard==2.14.1
tensorboard-data-server==0.7.2
tensorflow==2.14.0
tensorflow-estimator==2.14.0
tensorflow-io-gcs-filesystem==0.34.0
termcolor==2.3.0
timm==0.6.12
tk==0.1.0
tokenizers==0.13.3
toml==0.10.2
toolz==0.12.0
torch==2.0.1
torchmetrics==1.2.0
torchvision==0.16.0
tqdm==4.66.1
transformers==4.30.2
triton==2.0.0
typing-inspect==0.9.0
typing_extensions==4.8.0
tzdata==2023.3
uc-micro-py==1.0.2
unattended-upgrades==0.1
urllib3==2.0.7
uvicorn==0.23.2
voluptuous==0.13.1
wandb==0.15.11
wcwidth==0.2.9
webencodings==0.5.1
websockets==11.0.3
Werkzeug==3.0.1
wrapt==1.14.1
xformers==0.0.20
yarl==1.9.2
zipp==3.17.0
```

**Comment by azograby** [comment]
Until a better solution, you may add this line to the Dockerfile:

RUN python3 -m pip install -v -U xformers==0.0.22.post7 --index-url https://download.pytorch.org/whl/cu118

Right after pip install -r ./requirements.txt

**Comment by philenius** [comment]
> Until a better solution, you may add this line to the Dockerfile:
> 
> RUN python3 -m pip install -v -U xformers==0.0.22.post7 --index-url https://download.pytorch.org/whl/cu118
> 
> Right after pip install -r ./requirements.txt

Doesn't seem to help. When I start a LoRA training, then I get the following error at runtime:
```
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 5, in <module>
    from accelerate.commands.accelerate_cli import main
  File "/usr/local/lib/python3.10/dist-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 33, in <module>
    import torch
  File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 1119, in <module>
    from ._tensor import Tensor
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 12, in <module>
    import torch.utils.hooks as hooks
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/__init__.py", line 6, in <module>
    from .backend_registration import rename_privateuse1_backend, generate_methods_for_privateuse1_backend
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/backend_registration.py", line 2, in <module>
    from torch._C import _rename_privateuse1_backend, _get_privateuse1_backend_name
ImportError: cannot import name '_get_privateuse1_backend_name' from 'torch._C' (/usr/local/lib/python3.10/dist-packages/torch/_C.cpython-310-x86_64-linux-gnu.so)
```

Without adding the extra line `RUN python -m ...` I get the same error as @dougbtv

**Comment by azograby** [comment]
After adding that single line, it worked for me on v22.1.1, running this as
a SageMaker training job on ml.g5.8xl

**Comment by azograby** [comment]
@philenius Looks like [torchvision](https://pypi.org/project/torchvision/#history) and [torch](https://pypi.org/project/torch/2.1.1/#history) versions were updated yesterday and that's why this method wasn't working. If you use torch==2.1.0 and torchvision==0.16.0 it should work. I just tested and I'm no longer getting that error message.
