### ISSUE TITLE
AdamW8bit error

### ISSUE THREAD

**Issue by SmoothBrainApe** [bmaltais/kohya_ss#1659]
"/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (1.26.11) or chardet (5.2.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

and

Traceback (most recent call last):
  File "/home/chupz22/kohya_ss/./train_network.py", line 1009, in <module>
    trainer.train(args)
  File "/home/chupz22/kohya_ss/./train_network.py", line 338, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "/home/chupz22/kohya_ss/library/train_util.py", line 3421, in get_optimizer
    raise ImportError("No bitsandbytes / bitsandbytesがインストールされていないようです")
ImportError: No bitsandbytes / bitsandbytesがインストールされていないようです
Traceback (most recent call last):
  File "/home/chupz22/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/chupz22/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/chupz22/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/home/chupz22/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

Everytime I try to use AdamW8bit. Any workaround? AdamW works but I read that AdamW8bit uses less VRAM so I can train faster.

**Comment by a-l-e-x-d-s-9** [comment]
You don't have bitsandbytes installed. AdamW8bit works fine when you have bitsandbytes.
With Window you need the version that is included in the code.
Maybe you haven't installed the requirements.

**Comment by SmoothBrainApe** [comment]
> You don't have bitsandbytes installed. AdamW8bit works fine when you have bitsandbytes. With Windows you need the version that is included in the code. Maybe you haven't installed the requirements.

What should be the version? I have bitsandbytes 0.41.1

**Comment by Zarukei** [comment]
I noticed installing the newest version of  kohya_ss gives me this error on windows, but going back to v22.0.0 it works fine with bits

**Comment by Sorkan72** [comment]
Anyone have a fix for this? Windows.

**Comment by alejobrainz** [comment]
Same here.  Going back to 22.0.0
