### ISSUE TITLE
tkinter.TclError: couldn't connect to display ":1.0" When pressing "Train"

### ISSUE THREAD

**Issue by derto42** [bmaltais/kohya_ss#166]
Running on ubuntu via RunPod

When starting training, nothing happens and this error occurs:

Traceback (most recent call last):
  File "/home/kasm-user/Desktop/Everything I need/kohya_ss/venv/lib/python3.8/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/kasm-user/Desktop/Everything I need/kohya_ss/venv/lib/python3.8/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/home/kasm-user/Desktop/Everything I need/kohya_ss/venv/lib/python3.8/site-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/kasm-user/Desktop/Everything I need/kohya_ss/venv/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/kasm-user/Desktop/Everything I need/kohya_ss/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/kasm-user/Desktop/Everything I need/kohya_ss/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/kasm-user/Desktop/Everything I need/kohya_ss/lora_gui.py", line 291, in train_model
    msgbox('Image folder does not exist')
  File "/home/kasm-user/Desktop/Everything I need/kohya_ss/venv/lib/python3.8/site-packages/easygui/boxes/derived_boxes.py", line 230, in msgbox
    return buttonbox(msg=msg,
  File "/home/kasm-user/Desktop/Everything I need/kohya_ss/venv/lib/python3.8/site-packages/easygui/boxes/button_box.py", line 95, in buttonbox
    bb = ButtonBox(
  File "/home/kasm-user/Desktop/Everything I need/kohya_ss/venv/lib/python3.8/site-packages/easygui/boxes/button_box.py", line 147, in __init__
    self.ui = GUItk(msg, title, choices, images, default_choice, cancel_choice, self.callback_ui)
  File "/home/kasm-user/Desktop/Everything I need/kohya_ss/venv/lib/python3.8/site-packages/easygui/boxes/button_box.py", line 263, in __init__
    self.boxRoot = tk.Tk()
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":1.0"

It also gives the same error when pressing select folder icons, gives a big fat error message on the GUI, and similar error in terminal.

**Comment by derto42** [comment]
Fixed

**Comment by clownvary** [comment]
> Fixed ended up running
> 
> xhost +

how did you resolve this issue?

**Comment by clownvary** [comment]
@derto42  how did you resolve this issue?
