### ISSUE TITLE
Merge Lycoris with Checkpoint only shows CPU as available device

### ISSUE THREAD

**Issue by JVGA8837** [bmaltais/kohya_ss#1671]
![image](https://github.com/bmaltais/kohya_ss/assets/67811123/b5a79dab-1f48-4910-85eb-31dc92e9c5ef)
I have tried using the cpu but results in errors
Float16
```
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
Converting Dtype and Device: 100%|██████████████████████████████████████████████| 1050/1050 [00:00<00:00, 38556.33it/s]
Merging lora_te: 100%|██████████████████████████████████████████████████████████████| 152/152 [00:00<00:00, 799.24it/s]
Merging lora_unet:   0%|                                                             | 1/633 [00:00<00:00, 1992.54it/s]
Traceback (most recent call last):
  File "D:\kohya_ss\tools\merge_lycoris.py", line 85, in <module>
    main()
  File "D:\kohya_ss\tools\merge_lycoris.py", line 69, in main
    merge(
  File "D:\kohya_ss\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\lycoris\utils\__init__.py", line 528, in merge
    merge_state_dict(
  File "D:\kohya_ss\venv\lib\site-packages\lycoris\utils\__init__.py", line 505, in merge_state_dict
    result, result_b = rebuild_weight(*get_module(
  File "D:\kohya_ss\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\lycoris\utils\__init__.py", line 447, in rebuild_weight
    raise NotImplementedError
NotImplementedError
```

BFloat16
```
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
Traceback (most recent call last):
  File "D:\kohya_ss\tools\merge_lycoris.py", line 85, in <module>
    main()
  File "D:\kohya_ss\tools\merge_lycoris.py", line 67, in main
    raise ValueError(f'Cannot Find the dtype "{dtype}"')
ValueError: Cannot Find the dtype "None"
```

**Comment by heda05** [comment]
I'm experiencing the same problem. Did you solve the problem?

**Comment by JVGA8837** [comment]
Nope, that's why I posted the issue.
