### ISSUE TITLE
Invalid Escape Sequence '\c'

### ISSUE THREAD

**Issue by Madlyaza** [bmaltais/kohya_ss#1673]
When i try and run setup.bat i get this error.

```
Warning: Python version 3.10.9 is recommended.
G:\AI Imaging\KohyaSS\kohya_ss\setup\setup_windows.py:19: SyntaxWarning: invalid escape sequence '\c'
  os.path.dirname(os.path.realpath(__file__)), '..\cudnn_windows'
G:\AI Imaging\KohyaSS\kohya_ss\setup\setup_windows.py:229: SyntaxWarning: invalid escape sequence '\g'
  subprocess.Popen('start cmd /k .\gui.bat --inbrowser', shell=True) # /k keep the terminal open on quit. /c would close the terminal instead
Traceback (most recent call last):
  File "G:\AI Imaging\KohyaSS\kohya_ss\setup\setup_windows.py", line 7, in <module>
    import setup_common
  File "G:\AI Imaging\KohyaSS\kohya_ss\setup\setup_common.py", line 11, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

(venv) G:\AI Imaging\KohyaSS\kohya_ss>

```
I dont understand why it tells me python 3.10.9 is recommended. Because i have that installed.

**Comment by PierreAdam** [comment]
Open the file `setup/setup_windows.py` and on the line 19, there is this code
```python
os.path.dirname(os.path.realpath(__file__)), "..\cudnn_windows"
```
it should be replaced by this one
``` python
os.path.dirname(os.path.realpath(__file__)), "..\\cudnn_windows"
```

Same thing on the line 229
```python
"start cmd /k .\gui.bat --inbrowser", shell=True
```
should be replaced by 
```
"start cmd /k .\\gui.bat --inbrowser", shell=True
```

However, make sure that the Venv is correctly running python 3.10. That might be an issue as well. To check it you can run `.\venv\Scripts\python.exe --version`
