### ISSUE TITLE
Applying presets fails with FileNotFoundError

### ISSUE THREAD

**Issue by asbjbo** [bmaltais/kohya_ss#1677]
Hi,

I'm trying to use Kohya SS GUI for the first time. Installation seems to have gone well. I am running under Windows 10 with a NVidia GTX 1080 Ti and Python 3.10.9. I have a set of image files and want to train a SD XL LoRA. The GUI launches and I can start filling in data. I started by "prepare dataset" and filled in names in the "folder" tab, which seemed to work.. However, when going to "parameters" and selecting any parameter preset from the menu, I get a FileNotFoundError (trace included below) in the terminal window, where it seems to try opening a file called "./presets/lora/.json" instead of an actual file like "./presets/lora/SDXL - edgLoRAXL AI_Now.json". Inspecting the code, it appears that `open_configuration` may got called with a blank `training_preset` value.

Traceback:
PS C:\Users\asbjo\StableDiffusion\kohya_ss> .\gui.bat
21:03:38-621758 INFO     Version: v22.1.1

21:03:38-632995 INFO     nVidia toolkit detected
21:03:40-729533 INFO     Torch 2.0.1+cu118
21:03:40-755496 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
21:03:40-758388 INFO     Torch detected GPU: NVIDIA GeForce GTX 1080 Ti VRAM 11264 Arch (6, 1) Cores 28
21:03:40-762384 INFO     Verifying modules installation status from requirements_windows_torch2.txt...
21:03:40-766380 INFO     Verifying modules installation status from requirements.txt...
21:03:44-195969 INFO     headless: False
21:03:44-200962 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
21:04:22-839031 INFO     SDXL model selected. Setting sdxl parameters
21:05:42-792167 INFO     Copy C:/Users/asbjo/StableDiffusion/AMB/100_AMB to
                         C:/Users/asbjo/StableDiffusion/AMB\img/100_AMB man...
21:05:43-793972 INFO     Removing existing directory C:/Users/asbjo/StableDiffusion/AMB\reg/1_man...
21:05:43-795970 INFO     Copy C:/Users/asbjo/StableDiffusion/AMB/reg to C:/Users/asbjo/StableDiffusion/AMB\reg/1_man...
21:05:43-799966 INFO     Done creating kohya_ss training folder structure at C:/Users/asbjo/StableDiffusion/AMB...
21:06:27-995875 INFO     Applying preset ...
Traceback (most recent call last):
  File "C:\Users\asbjo\StableDiffusion\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\asbjo\StableDiffusion\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1384, in process_api
    result = await self.call_function(
  File "C:\Users\asbjo\StableDiffusion\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1089, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\asbjo\StableDiffusion\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\asbjo\StableDiffusion\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\asbjo\StableDiffusion\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\asbjo\StableDiffusion\kohya_ss\venv\lib\site-packages\gradio\utils.py", line 700, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\asbjo\StableDiffusion\kohya_ss\lora_gui.py", line 356, in open_configuration
    with open(file_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './presets/lora/.json'

**Comment by mrmeseeks23** [comment]
Noting same problem on Linux/Ubuntu 22.04 RunPod setup.  tried altering 'lora_gui.py' to reflect entire path: '/workspace/kohya_ss/presets/lora/{}.json' without success.  As of latest commit

**Comment by Foolsets** [comment]
same here windows 10
14:14:30-280306 INFO     Applying preset ...
Traceback (most recent call last):
  File "C:\ai\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\gradio\routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\ai\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\gradio\blocks.py", line 1384, in process_api
    result = await self.call_function(
  File "C:\ai\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\gradio\blocks.py", line 1089, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ai\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ai\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\ai\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\ai\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\gradio\utils.py", line 700, in wrapper
    response = f(*args, **kwargs)
  File "C:\ai\Kohya_ss-GUI-LoRA-Portable-main\lora_gui.py", line 356, in open_configuration
    with open(file_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './presets/lora/.json'

**Comment by NagaYasu75** [comment]
Same here, but is in Permission denied error...
20:31:33-274073 INFO     Applying preset ...
Traceback (most recent call last):
  File "D:\AI\Kohya\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI\Kohya\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1384, in process_api
    result = await self.call_function(
  File "D:\AI\Kohya\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1089, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI\Kohya\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI\Kohya\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread    return await future
  File "D:\AI\Kohya\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\AI\Kohya\kohya_ss\venv\lib\site-packages\gradio\utils.py", line 700, in wrapper
    response = f(*args, **kwargs)
  File "D:\AI\Kohya\kohya_ss\lora_gui.py", line 356, in open_configuration
    with open(file_path, 'r') as f:
PermissionError: [Errno 13] Permission denied: './presets/lora/.json'

**Comment by franz101** [comment]
Somehow the filename is not parsed correctly:
`./presets/lora/.json`
