### ISSUE TITLE
Frustrating installation process

### ISSUE THREAD

**Issue by CodeHatchling** [bmaltais/kohya_ss#1679]
While trying to install Kohya I've been running into frequent snags. As of writing this I have been able to get it to run, though training always fails before it can begin with the error "ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths'" despite its presence in the directory (though this is a separate issue).

I tried at least a dozen times to get it running, and this is just an outline of the issues I ran into, excluding the failed attempts to fix it.

### Every time the installation fails, you have to delete the entire repo and start over

I've tried at least a dozen times to install. Each time an issue occurs, re-running the installation batch file will cause the console to simply write `\Microsoft was unexpected at this time.` 

**Solution:**
Delete the folder entirely and redo the clone. I had to write a batch file (containing the console commands listed in the readme) to make this faster. (Perhaps resetting the repo would have worked?)

### The installer doesn't look for the right version of Python

Before installing, I made sure to have the recommended version of Python installed. However, after running it complained that a different version was installed and then immediately failed with a syntax error in setup\check_local_modules.py, at line 25: A quotation mark confused it.

I looked at what python version I had installed in Add/Remove programs. I had two very old versions (< 3.5) and 3.10.9. It must have been trying to use the old version.

**Solution:**
Uninstall every version of Python, then reinstall 3.10.9.

### The installer seems to have threadlock issues

On my first attempt, it got stuck on `Installing package: torch==2.0.1+cu118 torchvision==0.15.2+cu118 --index-url`. After waiting for a half hour, I somehow forced it to break out by pressing Ctrl+V with the install window focussed unknowingly.

It created a stack trace, and the last place it reached was a call to wait for a locked thread. Judging by the low amount of CPU activity, it was likely stuck there waiting indefinitely.

**Solution:**
Delete everything and try again. It worked the second time.

### The option to start the GUI in the browser from the setup menu breaks.

After installing successfully I selected:
`5. (Optional) Start Kohya_ss GUI in browser`

It created a new console window, and all it said was `\Microsoft was unexpected at this time.` It does this after multiple tries.

**Solution:**
Manually run the `gui.git` batch file. (Admittedly minor in hindsight, but seeing that dreaded error about Microsoft rear its head again was panic inducing initially.)

If you need help reproducing any of these problems, I'll gladly try to retrace mysteps and give full error logs that pop up.

Thank you!

**Comment by CodeHatchling** [comment]
For what it's worth, I've found that using the portable version [Kohya_ss-GUI-LoRA-Portable](https://github.com/serpotapov/Kohya_ss-GUI-LoRA-Portable) has not had any issues so far in this respect. I'm assuming the two repos are using shared code, so this could be the solution for anyone else with this problem.

**Comment by jxhxgt** [comment]
No module named 'bitsandbytes.cuda_setup.paths

**Comment by jxhxgt** [comment]
ohhhh
=

**Comment by jxhxgt** [comment]
I also encountered this, but reinstalling didn't help

**Comment by kalle07** [comment]
nearly same issue on windows
the version 2 month ago works very fine

start.bat has an error 
i must start this manualy after create venv
python .\setup\setup_windows.py
all install but in the end gui doesnt start without any errormessage

logfile from install may it helps ?

...............
2023-11-13 20:50:43,709 | sd | INFO | setup_windows | Checking for CUDNN files in D:\kohya_ss\venv\Lib\site-packages\torch\lib...
2023-11-13 20:50:43,715 | sd | WARNING | setup_windows | Destination directory D:\kohya_ss\venv\Lib\site-packages\torch\lib does not exist
2023-11-13 20:50:56,733 | sd | INFO | setup_common | Version: v22.1.1

2023-11-13 20:50:56,733 | sd | INFO | setup_common | Python 3.10.9 on Windows
2023-11-13 20:50:56,743 | sd | DEBUG | setup_common | Package version found: pip 22.3.1
2023-11-13 20:50:56,743 | sd | INFO | setup_common | Installing modules from requirements_windows_torch2.txt...
2023-11-13 20:50:56,743 | sd | DEBUG | setup_common | Package version not found: torch
2023-11-13 20:50:56,743 | sd | INFO | setup_common | Installing package: torch==2.0.1+cu118 torchvision==0.15.2+cu118 --index-url https://download.pytorch.org/whl/cu118
2023-11-13 20:50:56,743 | sd | DEBUG | setup_common | Running pip: install --upgrade torch==2.0.1+cu118 torchvision==0.15.2+cu118 --index-url https://download.pytorch.org/whl/cu118
2023-11-13 20:52:15,973 | sd | DEBUG | setup_common | Package version not found: xformers
2023-11-13 20:52:15,973 | sd | INFO | setup_common | Installing package: xformers==0.0.21
2023-11-13 20:52:15,973 | sd | DEBUG | setup_common | Running pip: install --upgrade xformers==0.0.21
2023-11-13 20:52:18,547 | sd | DEBUG | setup_common | Package version not found: bitsandbytes
2023-11-13 20:52:18,547 | sd | INFO | setup_common | Installing package: bitsandbytes==0.41.1
2023-11-13 20:52:18,547 | sd | DEBUG | setup_common | Running pip: install --upgrade bitsandbytes==0.41.1
2023-11-13 20:52:20,869 | sd | DEBUG | setup_common | Package version not found: tensorboard
2023-11-13 20:52:20,869 | sd | INFO | setup_common | Installing package: tensorboard==2.14.1 tensorflow==2.14.0
2023-11-13 20:52:20,869 | sd | DEBUG | setup_common | Running pip: install --upgrade tensorboard==2.14.1 tensorflow==2.14.0
2023-11-13 20:52:49,657 | sd | INFO | setup_common | Installing modules from requirements.txt...
2023-11-13 20:52:49,657 | sd | DEBUG | setup_common | Package version not found: accelerate
2023-11-13 20:52:49,657 | sd | INFO | setup_common | Installing package: accelerate==0.23.0
2023-11-13 20:52:49,657 | sd | DEBUG | setup_common | Running pip: install --upgrade accelerate==0.23.0
2023-11-13 20:52:52,767 | sd | DEBUG | setup_common | Package version not found: aiofiles
2023-11-13 20:52:52,767 | sd | INFO | setup_common | Installing package: aiofiles==23.2.1
2023-11-13 20:52:52,767 | sd | DEBUG | setup_common | Running pip: install --upgrade aiofiles==23.2.1
2023-11-13 20:52:53,714 | sd | DEBUG | setup_common | Package version not found: altair
2023-11-13 20:52:53,714 | sd | INFO | setup_common | Installing package: altair==4.2.2
2023-11-13 20:52:53,714 | sd | DEBUG | setup_common | Running pip: install --upgrade altair==4.2.2
2023-11-13 20:53:04,959 | sd | DEBUG | setup_common | Package version not found: dadaptation
2023-11-13 20:53:04,959 | sd | INFO | setup_common | Installing package: dadaptation==3.1
2023-11-13 20:53:04,969 | sd | DEBUG | setup_common | Running pip: install --upgrade dadaptation==3.1
2023-11-13 20:53:06,072 | sd | DEBUG | setup_common | Package version not found: diffusers
2023-11-13 20:53:06,072 | sd | INFO | setup_common | Installing package: diffusers[torch]==0.21.4
2023-11-13 20:53:06,088 | sd | DEBUG | setup_common | Running pip: install --upgrade diffusers[torch]==0.21.4
2023-11-13 20:53:09,520 | sd | DEBUG | setup_common | Package version not found: easygui
2023-11-13 20:53:09,520 | sd | INFO | setup_common | Installing package: easygui==0.98.3
2023-11-13 20:53:09,535 | sd | DEBUG | setup_common | Running pip: install --upgrade easygui==0.98.3
2023-11-13 20:53:10,712 | sd | DEBUG | setup_common | Package version not found: einops
2023-11-13 20:53:10,712 | sd | INFO | setup_common | Installing package: einops==0.6.0
2023-11-13 20:53:10,712 | sd | DEBUG | setup_common | Running pip: install --upgrade einops==0.6.0
2023-11-13 20:53:11,884 | sd | DEBUG | setup_common | Package version not found: fairscale
2023-11-13 20:53:11,884 | sd | INFO | setup_common | Installing package: fairscale==0.4.13
2023-11-13 20:53:11,884 | sd | DEBUG | setup_common | Running pip: install --upgrade fairscale==0.4.13
2023-11-13 20:53:13,510 | sd | DEBUG | setup_common | Package version not found: ftfy
2023-11-13 20:53:13,525 | sd | INFO | setup_common | Installing package: ftfy==6.1.1
2023-11-13 20:53:13,525 | sd | DEBUG | setup_common | Running pip: install --upgrade ftfy==6.1.1
2023-11-13 20:53:14,874 | sd | DEBUG | setup_common | Package version not found: gradio
2023-11-13 20:53:14,874 | sd | INFO | setup_common | Installing package: gradio==3.36.1
2023-11-13 20:53:14,874 | sd | DEBUG | setup_common | Running pip: install --upgrade gradio==3.36.1
2023-11-13 20:53:29,036 | sd | DEBUG | setup_common | Package version not found: huggingface-hub
2023-11-13 20:53:29,036 | sd | INFO | setup_common | Installing package: huggingface-hub==0.15.1
2023-11-13 20:53:29,036 | sd | DEBUG | setup_common | Running pip: install --upgrade huggingface-hub==0.15.1
2023-11-13 20:53:30,858 | sd | DEBUG | setup_common | Package version not found: invisible-watermark
2023-11-13 20:53:30,858 | sd | INFO | setup_common | Installing package: invisible-watermark==0.2.0
2023-11-13 20:53:30,858 | sd | DEBUG | setup_common | Running pip: install --upgrade invisible-watermark==0.2.0
2023-11-13 20:53:33,208 | sd | DEBUG | setup_common | Package version not found: lion-pytorch
2023-11-13 20:53:33,208 | sd | INFO | setup_common | Installing package: lion-pytorch==0.0.6
2023-11-13 20:53:33,208 | sd | DEBUG | setup_common | Running pip: install --upgrade lion-pytorch==0.0.6
2023-11-13 20:53:34,482 | sd | DEBUG | setup_common | Package version not found: lycoris_lora
2023-11-13 20:53:34,482 | sd | INFO | setup_common | Installing package: lycoris_lora==1.9.0
2023-11-13 20:53:34,482 | sd | DEBUG | setup_common | Running pip: install --upgrade lycoris_lora==1.9.0
2023-11-13 20:53:45,792 | sd | DEBUG | setup_common | Package version not found: onnx
2023-11-13 20:53:45,792 | sd | INFO | setup_common | Installing package: onnx==1.14.1
2023-11-13 20:53:45,792 | sd | DEBUG | setup_common | Running pip: install --upgrade onnx==1.14.1
2023-11-13 20:53:52,340 | sd | DEBUG | setup_common | Package version not found: onnxruntime-gpu
2023-11-13 20:53:52,340 | sd | INFO | setup_common | Installing package: onnxruntime-gpu==1.16.0
2023-11-13 20:53:52,340 | sd | DEBUG | setup_common | Running pip: install --upgrade onnxruntime-gpu==1.16.0
2023-11-13 20:53:57,418 | sd | DEBUG | setup_common | Package version not found: protobuf
2023-11-13 20:53:57,418 | sd | INFO | setup_common | Installing package: protobuf==3.20.3
2023-11-13 20:53:57,418 | sd | DEBUG | setup_common | Running pip: install --upgrade protobuf==3.20.3
2023-11-13 20:53:59,489 | sd | DEBUG | setup_common | Package version not found: open-clip-torch
2023-11-13 20:53:59,489 | sd | INFO | setup_common | Installing package: open-clip-torch==2.20.0
2023-11-13 20:53:59,491 | sd | DEBUG | setup_common | Running pip: install --upgrade open-clip-torch==2.20.0
2023-11-13 20:54:03,121 | sd | DEBUG | setup_common | Package version not found: opencv-python
2023-11-13 20:54:03,121 | sd | INFO | setup_common | Installing package: opencv-python==4.7.0.68
2023-11-13 20:54:03,121 | sd | DEBUG | setup_common | Running pip: install --upgrade opencv-python==4.7.0.68
2023-11-13 20:54:05,516 | sd | DEBUG | setup_common | Package version not found: prodigyopt
2023-11-13 20:54:05,516 | sd | INFO | setup_common | Installing package: prodigyopt==1.0
2023-11-13 20:54:05,531 | sd | DEBUG | setup_common | Running pip: install --upgrade prodigyopt==1.0
2023-11-13 20:54:07,152 | sd | DEBUG | setup_common | Package version not found: pytorch-lightning
2023-11-13 20:54:07,152 | sd | INFO | setup_common | Installing package: pytorch-lightning==1.9.0
2023-11-13 20:54:07,152 | sd | DEBUG | setup_common | Running pip: install --upgrade pytorch-lightning==1.9.0
2023-11-13 20:54:11,546 | sd | DEBUG | setup_common | Package version not found: rich
2023-11-13 20:54:11,546 | sd | INFO | setup_common | Installing package: rich==13.4.1
2023-11-13 20:54:11,546 | sd | DEBUG | setup_common | Running pip: install --upgrade rich==13.4.1
2023-11-13 20:54:13,841 | sd | DEBUG | setup_common | Package version not found: safetensors
2023-11-13 20:54:13,841 | sd | INFO | setup_common | Installing package: safetensors==0.3.1
2023-11-13 20:54:13,841 | sd | DEBUG | setup_common | Running pip: install --upgrade safetensors==0.3.1
2023-11-13 20:54:15,726 | sd | DEBUG | setup_common | Package version not found: timm
2023-11-13 20:54:15,726 | sd | INFO | setup_common | Installing package: timm==0.6.12
2023-11-13 20:54:15,742 | sd | DEBUG | setup_common | Running pip: install --upgrade timm==0.6.12
2023-11-13 20:54:18,792 | sd | DEBUG | setup_common | Package version not found: tk
2023-11-13 20:54:18,792 | sd | INFO | setup_common | Installing package: tk==0.1.0
2023-11-13 20:54:18,808 | sd | DEBUG | setup_common | Running pip: install --upgrade tk==0.1.0
2023-11-13 20:54:20,579 | sd | DEBUG | setup_common | Package version not found: toml
2023-11-13 20:54:20,579 | sd | INFO | setup_common | Installing package: toml==0.10.2
2023-11-13 20:54:20,579 | sd | DEBUG | setup_common | Running pip: install --upgrade toml==0.10.2
2023-11-13 20:54:22,384 | sd | DEBUG | setup_common | Package version not found: transformers
2023-11-13 20:54:22,384 | sd | INFO | setup_common | Installing package: transformers==4.30.2
2023-11-13 20:54:22,384 | sd | DEBUG | setup_common | Running pip: install --upgrade transformers==4.30.2
2023-11-13 20:54:34,734 | sd | DEBUG | setup_common | Package version not found: voluptuous
2023-11-13 20:54:34,734 | sd | INFO | setup_common | Installing package: voluptuous==0.13.1
2023-11-13 20:54:34,734 | sd | DEBUG | setup_common | Running pip: install --upgrade voluptuous==0.13.1
2023-11-13 20:54:36,575 | sd | DEBUG | setup_common | Package version not found: wandb
2023-11-13 20:54:36,575 | sd | INFO | setup_common | Installing package: wandb==0.15.11
2023-11-13 20:54:36,575 | sd | DEBUG | setup_common | Running pip: install --upgrade wandb==0.15.11
2023-11-13 20:54:43,143 | sd | DEBUG | setup_common | Package version not found: -e
2023-11-13 20:54:43,143 | sd | INFO | setup_common | Installing package: -e .
2023-11-13 20:54:43,143 | sd | DEBUG | setup_common | Running pip: install --upgrade -e .
2023-11-13 20:54:48,264 | sd | INFO | setup_windows | Copying bitsandbytes files...
2023-11-13 20:54:48,264 | sd | DEBUG | setup_windows | Copy D:\kohya_ss\bitsandbytes_windows\cextension.py to D:\kohya_ss\venv\Lib\site-packages\bitsandbytes
2023-11-13 20:54:48,264 | sd | DEBUG | setup_windows | Copy D:\kohya_ss\bitsandbytes_windows\libbitsandbytes_cpu.dll to D:\kohya_ss\venv\Lib\site-packages\bitsandbytes
2023-11-13 20:54:48,264 | sd | DEBUG | setup_windows | Copy D:\kohya_ss\bitsandbytes_windows\libbitsandbytes_cuda116.dll to D:\kohya_ss\venv\Lib\site-packages\bitsandbytes
2023-11-13 20:54:48,274 | sd | DEBUG | setup_windows | Copy D:\kohya_ss\bitsandbytes_windows\libbitsandbytes_cuda118.dll to D:\kohya_ss\venv\Lib\site-packages\bitsandbytes
2023-11-13 20:54:48,274 | sd | DEBUG | setup_windows | Copy D:\kohya_ss\bitsandbytes_windows\main.py to D:\kohya_ss\venv\Lib\site-packages\bitsandbytes\cuda_setup
2023-11-13 20:54:48,274 | sd | INFO | setup_common | Configuring accelerate...
2023-11-13 20:54:48,290 | sd | DEBUG | setup_common | Source accelerate config location: D:\kohya_ss\setup\..\config_files\accelerate\default_config.yaml
2023-11-13 20:54:48,290 | sd | DEBUG | setup_common | Environment variables: HF_HOME: None, LOCALAPPDATA: C:\Users\kallemst\AppData\Local, USERPROFILE: C:\Users\kallemst
2023-11-13 20:54:48,290 | sd | DEBUG | setup_common | Target config location: C:\Users\kallemst\AppData\Local\huggingface\accelerate\default_config.yaml
2023-11-13 20:56:34,017 | sd | INFO | setup_windows | Checking for CUDNN files in D:\kohya_ss\venv\Lib\site-packages\torch\lib...
2023-11-13 20:56:35,304 | sd | INFO | setup_windows | Copied CUDNN 8.6 files to destination

**Comment by Petter-Pmagi** [comment]
> No module named 'bitsandbytes.cuda_setup.paths

Had this too, the version of bitsandbytes that is installed by default in windows seems to not work, it is missing a file paths.py, solution is to install bitsandbytes-windows from setup.bat instead

**Comment by davidfunk13** [comment]
> > No module named 'bitsandbytes.cuda_setup.paths
> 
> Had this too, the version of bitsandbytes that is installed by default in windows seems to not work, it is missing a file paths.py, solution is to install bitsandbytes-windows from setup.bat instead. Weirdly this does not seem to download bitsandbytes-windows but to path the source code to remove the ref to paths.py for example. But it works.

would you mind elaborating here a little? same issue over here.

**Comment by Petter-Pmagi** [comment]
> > > No module named 'bitsandbytes.cuda_setup.paths
> > 
> > 
> > Had this too, the version of bitsandbytes that is installed by default in windows seems to not work, it is missing a file paths.py, solution is to install bitsandbytes-windows from setup.bat instead. Weirdly this does not seem to download bitsandbytes-windows but to path the source code to remove the ref to paths.py for example. But it works.
> 
> would you mind elaborating here a little? same issue over here.

So, when you install kohya from its menu (setup.bat) you first select 1 to install, then you select 5 (I think) to install bitsandbytes windows (they say its not recommended but dont mind that). As far as I can see in teh source code this will not actually download a new bitsandbytes but just patch the installed one (0.41 probably). As far as I can see you need to do this in windows so why it is not in the install instructions for windows is very strange. 

Another thing that seems to be missing is that you need to install cuda drivers 11.8 from nvidia site as that specific version is refered to by other files, so that should also be in the install info. (the pytorch version installed by kohya seems to be compiled for this version).

It is now working for me but I get a number or errors/warnings:

WARNING  Package wrong version: huggingface-hub 0.17.3 required 0.15.1

-----probably ok



 ValueError
Traceback (most recent call last):
  File "C:\Users\pette\stable-diffusion-webui\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\Users\pette\stable-diffusion-webui\extensions-builtin\Lora\extra_networks_lora.py", line 30, in activate
    te_multiplier = float(params.positional[1]) if len(params.positional) > 1 else 1.0
ValueError: could not convert string to float: '\\Users\\pette\\Documents\\training_petter\\model\\last.safetensors'

-----seeems to be a problem with epoch numbers in filename, not sure it matters.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8317


Enable xformers for U-Net
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
import network module: networks.lora

------not sure if this should/could be installed: pip install triton
https://www.reddit.com/r/StableDiffusion/comments/13c8dao/kohya_what_is_a_triton_and_why_dont_i_have_one/



load Diffusers pretrained models: runwayml/stable-diffusion-v1-5
text_encoder\model.safetensors not found

------seems to work anyway:
The display issue 'safetensors not found' has been resolved by setting local_files_only=True in the diffusers' from_pretrained function. Therefore, this issue will be closed.
https://www.reddit.com/r/StableDiffusion/comments/114e0nj/kohya_ss_error_how_do_i_solve_this/
https://huggingface.co/stabilityai/stable-diffusion-2-1/blob/main/text_encoder/model.safetensors

-----> Could someone please have a look at the windows installation of kohya and all the above problems?

**Comment by kalle07** [comment]
i repeat [CodeHatchling](https://github.com/CodeHatchling)


For what it's worth, I've found that using the portable version [Kohya_ss-GUI-LoRA-Portable](https://github.com/serpotapov/Kohya_ss-GUI-LoRA-Portable) has not had any issues so far in this respect. I'm assuming the two repos are using shared code, so this could be the solution for anyone else with this problem.
