### ISSUE TITLE
training error DDPOptimizer backend

### ISSUE THREAD

**Issue by killermyth** [bmaltais/kohya_ss#1687]
**training command:**
accelerate launch --num_cpu_threads_per_process=10 "./sdxl_train.py" --enable_bucket --pretrained_model_name_or_path="/home/www/train/source/sd_xl_base_1.0.safetensors" --train_data_dir="/home/www/train/source/pure" --reg_data_dir="/home/www/train/source/sd-regularization-img/sdxl_artstyle_ddim" --resolution="1024,1024" --output_dir="/home/www/train/sdxl_head_101401" --logging_dir="/home/www/train/sdxl_head_101401/log" --save_model_as=safetensors --output_name="sdxl_110801" --lr_scheduler_num_cycles="10" --no_half_vae --learning_rate="4e-7" --lr_scheduler="constant_with_warmup" --lr_warmup_steps="200" --train_batch_size="30" --max_train_epochs="100" --save_every_n_epochs="25" --mixed_precision="bf16" --save_precision="bf16" --cache_latents --cache_latents_to_disk --cache_text_encoder_outputs --optimizer_type="Adafactor" --optimizer_args scale_parameter=False relative_step=False warmup_init=False --max_data_loader_n_workers="0" --bucket_reso_steps=64 --gradient_checkpointing --xformers --bucket_no_upscale

**error:**
[rank0]:[2023-11-16 17:56:59,595] [3/0] torch._dynamo.variables.higher_order_ops: [ERROR] speculate_subgraph: while introspecting the user-defined autograd.Function, we were unable to trace function `trampoline_autograd_fwd` into a single graph. This means that Dynamo was unable to prove safety for this API and will fall back to eager-mode PyTorch, which could lead to a slowdown. Scroll up for the stack trace of the initial exception. The reason was: call_method UserDefinedObjectVariable(set) __contains__ [TorchVariable(torch.bfloat16)] {}
Traceback (most recent call last):
  File "/home/www/kohya_ss/./sdxl_train.py", line 775, in <module>
    train(args)
  File "/home/www/kohya_ss/./sdxl_train.py", line 556, in train
    noise_pred = unet(noisy_latents, timesteps, text_embedding, vector_embedding)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/accelerate/utils/operations.py", line 636, in forward
    return model_forward(*args, **kwargs)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/accelerate/utils/operations.py", line 624, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/www/kohya_ss/library/sdxl_original_unet.py", line 1081, in forward
    h = call_module(module, h, emb, context)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 487, in catch_errors
    return hijacked_callback(frame, cache_entry, hooks, frame_state)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 641, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 569, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 491, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 458, in transform
    tracer.run()
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2074, in run
    super().run()
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2162, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 833, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 957, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1024, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1009, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/_dynamo/backends/distributed.py", line 228, in compile_fn
    raise NotImplementedError(
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fn' raised:
NotImplementedError: DDPOptimizer backend: Found a higher order op in the graph. This is not supported. Please turn off DDP optimizer using torch._dynamo.config.optimize_ddp=False. Note that this can cause performance degradation because there will be one bucket for the entire Dynamo graph. Please refer to this issue - https://github.com/pytorch/pytorch/issues/104674.

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

steps:   0%|          | 0/1800 [00:08<?, ?it/s]
[2023-11-16 17:57:08,025] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 336658) of binary: /home/www/anaconda3/envs/sdtrain/bin/python
Traceback (most recent call last):
  File "/home/www/anaconda3/envs/sdtrain/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/accelerate/commands/launch.py", line 977, in launch_command
    multi_gpu_launcher(args)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/www/anaconda3/envs/sdtrain/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
./sdxl_train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-16_17:57:08
  host      : aigp-loader-0.aigp-loader-service.default.svc.
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 336658)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by bmaltais** [comment]
Was it working in a previous release? When did this started?

**Comment by killermyth** [comment]
yes, this command is working in last week.
yesterday I git pull the latest code and setup the new environment, this error happened.
