### ISSUE TITLE
Error when loading presets

### ISSUE THREAD

**Issue by Davikar** [bmaltais/kohya_ss#1689]
The presets are not loaded when selected in the UI.
The following error appears in the console:

```
INFO     Applying preset ...
Traceback (most recent call last):
  File "C:\AI\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\AI\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1384, in process_api
    result = await self.call_function(
  File "C:\AI\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1089, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\AI\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AI\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\AI\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\AI\kohya_ss\venv\lib\site-packages\gradio\utils.py", line 700, in wrapper
    response = f(*args, **kwargs)
  File "C:\AI\kohya_ss\lora_gui.py", line 356, in open_configuration
    with open(file_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: './presets/lora/.json'
```

**Comment by bmaltais** [comment]
Hummm... can you try the dev2 branch version? I fixed an issue last night that I hope will fix that issue...

`git checkout dev2`
`git pull`

**Comment by Davikar** [comment]
> Hummm... can you try the dev2 branch version? I fixed an issue last night that I hope will fix that issue...
> 
> `git checkout dev2` `git pull`

A bit late reply, but yes, it's working now. (I see the fix was moved to main now.)
