### ISSUE TITLE
Keep running into this issue.. any ideas?

### ISSUE THREAD

**Issue by BrancasKitchen** [bmaltais/kohya_ss#1691]
trainer.train(args)
  File "C:\Users\florido\kohya_ss\train_network.py", line 228, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "C:\Users\florido\kohya_ss\sdxl_train_network.py", line 44, in load_target_model
    ) = sdxl_train_util.load_target_model(args, accelerator, sdxl_model_util.MODEL_VERSION_SDXL_BASE_V1_0, weight_dtype)
  File "C:\Users\florido\kohya_ss\library\sdxl_train_util.py", line 34, in load_target_model
    ) = _load_target_model(
  File "C:\Users\florido\kohya_ss\library\sdxl_train_util.py", line 84, in _load_target_model
    pipe = StableDiffusionXLPipeline.from_pretrained(
  File "C:\Users\florido\kohya_ss\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1191, in from_pretrained
    raise ValueError(
ValueError: Pipeline <class 'diffusers.pipelines.stable_diffusion_xl.pipeline_stable_diffusion_xl.StableDiffusionXLPipeline'> expected {'tokenizer_2', 'scheduler', 'tokenizer', 'vae', 'unet', 'text_encoder_2', 'text_encoder'}, but only {'tokenizer_2', 'scheduler', 'tokenizer', 'vae', 'unet', 'text_encoder_2'} were passed.
Traceback (most recent call last):
  File "C:\Users\florido\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\florido\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\florido\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\florido\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\florido\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\Users\florido\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\florido\\kohya_ss\\venv\\Scripts\\python.exe', './sdxl_train_network.py', '--enable_bucket', '--min_bucket_reso=64', '--max_bucket_reso=1024', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-refiner-1.0', '--train_data_dir=C:/Users/florido/Downloads/backslashlora\\img', '--resolution=1024,1024', '--output_dir=C:/Users/florido/Downloads/backslashlora\\model', '--logging_dir=C:/Users/florido/Downloads/backslashlora\\log', '--network_alpha=128', '--training_comment=trigger: the white queen', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=1.0', '--unet_lr=1.0', '--network_dim=128', '--output_name=last', '--lr_scheduler_num_cycles=1', '--scale_weight_norms=1', '--no_half_vae', '--learning_rate=1.0', '--lr_scheduler=adafactor', '--train_batch_size=5', '--max_train_steps=320', '--save_every_n_epochs=5', '--mixed_precision=no', '--save_precision=float', '--caption_extension=.txt', '--cache_latents', '--cache_latents_to_disk', '--optimizer_type=Adafactor', '--max_train_epochs=30', '--max_data_loader_n_workers=0', '--keep_tokens=1', '--bucket_reso_steps=32', '--gradient_checkpointing', '--xformers', '--noise_offset=0.0357', '--adaptive_noise_scale=0.00357', '--log_prefix=xl-loha']' returned non-zero exit status 1.

**Comment by Aralkar1** [comment]
Me too

**Comment by TheAnay** [comment]
me too please let know if u find a solution

**Comment by TheAnay** [comment]
@Aralkar1 @BrancasKitchen @lansing @rockerBOO HERES THE FIX 

Go to your Kohya_ss folder
Go to the venv folder
Open a cmd window 
Run activate.bat to activate the venv
Run commad pip uninstall bitsandbytes
Install bitsandbytes from the jllllll repo https://github.com/jllllll/bitsandbytes-windows-webui 
*RUN INSTALL SCRIPT FROM VENV. INSTALL SCRIPT ON THE GITHUB REPO 
Run kohyass using the gui-user.bat file

that fixed it for me nd probably will for u.
If u have made any changes to your kohya ss installation in attempts to fix the issue it is recomended to use a fresh kohya ss installation

**Comment by andrewshilliday** [comment]
That did not fix it for me (assuming I'm having the same problem).  I'm on a linux machine and when training, I get the following error:

```
Traceback (most recent call last):
  File "/home/andrewshilliday/kohya_ss/./sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "/home/andrewshilliday/kohya_ss/train_network.py", line 228, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "/home/andrewshilliday/kohya_ss/./sdxl_train_network.py", line 44, in load_target_model
    ) = sdxl_train_util.load_target_model(args, accelerator, sdxl_model_util.MODEL_VERSION_SDXL_BASE_V1_0, weight_dtype)
  File "/home/andrewshilliday/kohya_ss/library/sdxl_train_util.py", line 34, in load_target_model
    ) = _load_target_model(
  File "/home/andrewshilliday/kohya_ss/library/sdxl_train_util.py", line 84, in _load_target_model
    pipe = StableDiffusionXLPipeline.from_pretrained(
  File "/home/andrewshilliday/kohya_ss/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1191, in from_pretrained
    raise ValueError(
ValueError: Pipeline <class 'diffusers.pipelines.stable_diffusion_xl.pipeline_stable_diffusion_xl.StableDiffusionXLPipeline'> expected {'unet', 'tokenizer_2', 'text_encoder_2', 'text_encoder', 'vae', 'scheduler', 'tokenizer'}, but only {'unet', 'text_encoder', 'vae', 'scheduler', 'tokenizer'} were passed.
```

**Comment by BrancasKitchen** [comment]
> @Aralkar1 @BrancasKitchen @lansing @rockerBOO HERES THE FIX
> 
> Go to your Kohya_ss folder Go to the venv folder Open a cmd window Run activate.bat to activate the venv Run commad pip uninstall bitsandbytes Install bitsandbytes from the jllllll repo https://github.com/jllllll/bitsandbytes-windows-webui *RUN INSTALL SCRIPT FROM VENV. INSTALL SCRIPT ON THE GITHUB REPO Run kohyass using the gui-user.bat file
> 
> that fixed it for me nd probably will for u. If u have made any changes to your kohya ss installation in attempts to fix the issue it is recomended to use a fresh kohya ss installation

This worked, thanks!!!
