### ISSUE TITLE
fine_tune.py: error: unrecognized arguments: --no_half_vae

### ISSUE THREAD

**Issue by Davikar** [bmaltais/kohya_ss#1694]
Seems like UI is passing the --no_half_vae to fine_tune.py and it's not recognized:

```
fine_tune.py: error: unrecognized arguments: --no_half_vae
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\AI\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
```

Also, it seems that Debiased estimation loss isn't saved to the configuration files.

**Comment by treksis** [comment]
1) checkmark SDXL model
2) Then click parameters tab, you will see the option. 

If you don't checkmark SDXL Model you won't see it.

**Comment by kmillerdevx3** [comment]
These checkboxes seem to default to on, even when they're not visible. The workaround I've found is to select an SDXL preset, uncheck them, then choose an SD model and preset.
