### ISSUE TITLE
conversion failed, the model may not be trained by `sd-scripts`.

### ISSUE THREAD

**Issue by 123sleaf-123** [bmaltais/kohya_ss#1714]
*** Error running process_batch: E:\Code\Python\Diffusions\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
    Traceback (most recent call last):
      File "E:\Code\Python\Diffusions\stable-diffusion-webui\modules\scripts.py", line 643, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "E:\Code\Python\Diffusions\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 244, in process_batch
        network, info = lora_compvis.create_network_and_apply_compvis(
      File "E:\Code\Python\Diffusions\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 153, in create_network_and_apply_compvis
        network = LoRANetworkCompvis(text_encoder, unet, multiplier_tenc, multiplier_unet, modules_dim, modules_alpha)
      File "E:\Code\Python\Diffusions\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 341, in __init__
        comp_vis_lora_name = LoRANetworkCompvis.convert_diffusers_name_to_compvis(self.v2, du_lora_name)
      File "E:\Code\Python\Diffusions\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 302, in convert_diffusers_name_to_compvis
        assert cv_name is not None, f"conversion failed: {du_name}. the model may not be trained by `sd-scripts`."
    AssertionError: conversion failed: lora_te1_text_model_encoder_layers_0_mlp_fc1. the model may not be trained by `sd-scripts`.

I train a lora based on sdxl base 1.0, but It doesn't work properly in automatic11111. I'm not sure what's the problem.

**Comment by sgyh** [comment]
I have the same problem! does anybody has solutions?
