### ISSUE TITLE
training error: AttributeError: module 'tensorflow' has no attribute 'io'

### ISSUE THREAD

**Issue by DanielFrankee** [bmaltais/kohya_ss#1720]
I'm running into this error:

File "C:\Users\AIDEV\kohya_ss\sdxl_train.py", line 775, in <module>
    train(args)
  File "C:\Users\AIDEV\kohya_ss\sdxl_train.py", line 462, in train
    accelerator.init_trackers("finetuning" if args.log_tracker_name is None else args.log_tracker_name, init_kwargs=init_kwargs)
  File "C:\Users\AIDEV\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 615, in _inner
    return PartialState().on_main_process(function)(*args, **kwargs)
  File "C:\Users\AIDEV\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 2412, in init_trackers
    tracker_init(project_name, self.logging_dir, **init_kwargs.get(str(tracker), {}))
  File "C:\Users\AIDEV\kohya_ss\venv\lib\site-packages\accelerate\tracking.py", line 71, in execute_on_main_process
    return PartialState().on_main_process(function)(self, *args, **kwargs)
  File "C:\Users\AIDEV\kohya_ss\venv\lib\site-packages\accelerate\tracking.py", line 176, in __init__
    from torch.utils import tensorboard
  File "C:\Users\AIDEV\kohya_ss\venv\lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "C:\Users\AIDEV\kohya_ss\venv\lib\site-packages\torch\utils\tensorboard\writer.py", line 16, in <module>
    from ._embedding import (
  File "C:\Users\AIDEV\kohya_ss\venv\lib\site-packages\torch\utils\tensorboard\_embedding.py", line 9, in <module>
    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, "join")
  File "C:\Users\AIDEV\kohya_ss\venv\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
AttributeError: module 'tensorflow' has no attribute 'io'
steps:   0%|                                                                                                                                 | 0/41000 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\AIDEV\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\AIDEV\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\AIDEV\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\AIDEV\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\AIDEV\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\Users\AIDEV\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\AIDEV\\kohya_ss\\venv\\Scripts\\python.exe', './sdxl_train.py', '--pretrained_model_name_or_path=C:/Users/AIDEV/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0_0.9vae.safetensors', '--train_data_dir=C:\\Users\\AIDEV\\Desktop\\test_lora\\output\\img', '--reg_data_dir=C:\\Users\\AIDEV\\Desktop\\test_lora\\output\\reg', '--resolution=1024,1024', '--output_dir=C:\\Users\\AIDEV\\Desktop\\test_lora\\output\\model', '--logging_dir=C:\\Users\\AIDEV\\Desktop\\test_lora\\output\\log', '--save_model_as=safetensors', '--output_name=zoran_zoki', '--lr_scheduler_num_cycles=20', '--max_data_loader_n_workers=0', '--learning_rate_te1=1e-05', '--learning_rate_te2=1e-05', '--learning_rate=0.0004', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=41000', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--cache_latents', '--cache_latents_to_disk', '--optimizer_type=Adafactor', '--optimizer_args', 'scale_parameter=False', 'relative_step=False', 'warmup_init=False', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

**Comment by DanielFrankee** [comment]
ah - found the solution
[904](https://github.com/bmaltais/kohya_ss/issues/904)
