### ISSUE TITLE
New Error 😞 has anyone fixed it?

### ISSUE THREAD

**Issue by G4RLK** [bmaltais/kohya_ss#1743]
Traceback (most recent call last):
  File "D:\4-AI\kohya_ss\train_network.py", line 1012, in <module>
    trainer.train(args)
  File "D:\4-AI\kohya_ss\train_network.py", line 228, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "D:\4-AI\kohya_ss\train_network.py", line 102, in load_target_model
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "D:\4-AI\kohya_ss\library\train_util.py", line 3906, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "D:\4-AI\kohya_ss\library\train_util.py", line 3849, in _load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(
  File "D:\4-AI\kohya_ss\library\model_util.py", line 1015, in load_models_from_stable_diffusion_checkpoint
    info = vae.load_state_dict(converted_vae_checkpoint)
  File "D:\4-AI\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for AutoencoderKL:
        Unexpected key(s) in state_dict: "encoder.mid_block.attentions.0.to_to_k.bias", "encoder.mid_block.attentions.0.to_to_k.weight", "encoder.mid_block.attentions.0.to_to_q.bias", "encoder.mid_block.attentions.0.to_to_q.weight", "encoder.mid_block.attentions.0.to_to_v.bias", "encoder.mid_block.attentions.0.to_to_v.weight", "decoder.mid_block.attentions.0.to_to_k.bias", "decoder.mid_block.attentions.0.to_to_k.weight", "decoder.mid_block.attentions.0.to_to_q.bias", "decoder.mid_block.attentions.0.to_to_q.weight", "decoder.mid_block.attentions.0.to_to_v.bias", "decoder.mid_block.attentions.0.to_to_v.weight".
Traceback (most recent call last):
  File "C:\Users\DENGO\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\DENGO\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\4-AI\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\4-AI\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\4-AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "D:\4-AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\4-AI\\kohya_ss\\venv\\Scripts\\python.exe', './train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=D:/4-AI/stable-diffusion-webui/models/Stable-diffusion/serenity_v20.safetensors', '--train_data_dir=D:/4-AI/imgs for training/time at sandrock style/img', '--resolution=512,512', '--output_dir=D:/4-AI/imgs for training/time at sandrock style/output', '--logging_dir=D:/4-AI/imgs for training/time at sandrock style/log', '--network_alpha=19', '--save_model_as=ckpt', '--network_module=lycoris.kohya', '--network_args', 'preset=full', 'conv_dim=1', 'conv_alpha=1', 'algo=locon', '--network_dim=32', '--output_name=mtasandr0ck_style', '--lr_scheduler_num_cycles=2', '--no_half_vae', '--learning_rate=5e-05', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=3100', '--mixed_precision=fp16', '--save_precision=fp16', '--caption_extension=.txt', '--cache_latents', '--cache_latents_to_disk', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--bucket_reso_steps=64', '--save_every_n_steps=50', '--mem_eff_attn', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0', '--wandb_api_key=False', '--sample_sampler=ddim', '--sample_prompts=D:/4-AI/imgs for training/time at sandrock style/output\\sample\\prompt.txt', '--sample_every_n_steps=100']' returned non-zero exit status 1.

**Comment by DarksealStudios** [comment]
Same issue. 😢
