### ISSUE TITLE
 CLIPImageProcessor requires the PIL library but it was not found in your environment

### ISSUE THREAD

**Issue by yu840732962** [bmaltais/kohya_ss#1768]
`

2023-12-13 14:22:35 Traceback (most recent call last):
2023-12-13 14:22:35   File "/app/./train_network.py", line 1012, in <module>
2023-12-13 14:22:35     trainer.train(args)
2023-12-13 14:22:35   File "/app/./train_network.py", line 228, in train
2023-12-13 14:22:35     model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
2023-12-13 14:22:35   File "/app/./train_network.py", line 102, in load_target_model
2023-12-13 14:22:35     text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
2023-12-13 14:22:35   File "/app/library/train_util.py", line 3917, in load_target_model
2023-12-13 14:22:35     text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
2023-12-13 14:22:35   File "/app/library/train_util.py", line 3867, in _load_target_model
2023-12-13 14:22:35     pipe = StableDiffusionPipeline.from_pretrained(name_or_path, tokenizer=None, safety_checker=None)
2023-12-13 14:22:35   File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 1105, in from_pretrained
2023-12-13 14:22:35     loaded_sub_model = load_sub_model(
2023-12-13 14:22:35   File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 409, in load_sub_model
2023-12-13 14:22:35     class_obj()
2023-12-13 14:22:35   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/dummy_vision_objects.py", line 79, in __init__
2023-12-13 14:22:35     requires_backends(self, ["vision"])
2023-12-13 14:22:35   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1014, in requires_backends
2023-12-13 14:22:35     raise ImportError("".join(failed))
2023-12-13 14:22:35 ImportError: 
2023-12-13 14:22:35 CLIPImageProcessor requires the PIL library but it was not found in your environment. You can install it with pip:
2023-12-13 14:22:35 `pip install pillow`. Please note that you may need to restart your runtime after installation.
2023-12-13 14:22:35 
2023-12-13 14:22:36 Traceback (most recent call last):
2023-12-13 14:22:36   File "/usr/local/bin/accelerate", line 8, in <module>
2023-12-13 14:22:36     sys.exit(main())
2023-12-13 14:22:36   File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
2023-12-13 14:22:36     args.func(args)
2023-12-13 14:22:36   File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 986, in launch_command
2023-12-13 14:22:36     simple_launcher(args)
2023-12-13 14:22:36   File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 628, in simple_launcher
2023-12-13 14:22:36     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
2023-12-13 14:22:36 subprocess.CalledProcessError: Command '['/usr/bin/python3', './train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=/dataset/tran/image', '--resolution=512,512', '--output_dir=/dataset/tran/model', '--logging_dir=/dataset/tran/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=128', '--output_name=su_luoli', '--lr_scheduler_num_cycles=2', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=80', '--train_batch_size=1', '--max_train_steps=800', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

`

dockerfile 
`
# Replace pillow with pillow-simd
RUN --mount=type=cache,target=/root/.cache/pip python3 -m pip uninstall -y pillow && \
    CC="cc -mavx2" python3 -m pip install -U --force-reinstall pillow-simd
`

help， How to solve this problem

**Comment by Brensom** [comment]
I have the same problem. What to do?
