### ISSUE TITLE
KeyError: 'time_embedding.linear_1.weight' 

### ISSUE THREAD

**Issue by lilyzlt** [bmaltais/kohya_ss#1809]
Linux environment, using SD1.5, all the param using the default one, when it generate model, then get the error as following: 

100%|██████████| 5/5 [00:00<00:00, 93622.86it/s]
100%|██████████| 5/5 [00:01<00:00,  2.62it/s]
steps: 100%|██████████| 25/25 [03:20<00:00,  8.00s/it, avr_loss=0.127]Traceback (most recent call last):
  File "/data/kohya_ss/./train_db.py", line 495, in <module>
    train(args)
  File "/data/kohya_ss/./train_db.py", line 451, in train
    train_util.save_sd_model_on_train_end(
  File "/data/kohya_ss/library/train_util.py", line 4355, in save_sd_model_on_train_end
    save_sd_model_on_train_end_common(
  File "/data/kohya_ss/library/train_util.py", line 4378, in save_sd_model_on_train_end_common
    sd_saver(ckpt_file, epoch, global_step)
  File "/data/kohya_ss/library/train_util.py", line 4346, in sd_saver
    model_util.save_stable_diffusion_checkpoint(
  File "/data/kohya_ss/library/model_util.py", line 1190, in save_stable_diffusion_checkpoint
    unet_state_dict = convert_unet_state_dict_to_sd(v2, unet.state_dict())
  File "/data/kohya_ss/library/model_util.py", line 762, in convert_unet_state_dict_to_sd
    new_state_dict = {v: unet_state_dict[k] for k, v in mapping.items()}
  File "/data/kohya_ss/library/model_util.py", line 762, in <dictcomp>
    new_state_dict = {v: unet_state_dict[k] for k, v in mapping.items()}
KeyError: 'time_embedding.linear_1.weight'
steps: 100%|██████████| 25/25 [03:21<00:00,  8.05s/it, avr_loss=0.127]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 5083) of binary: /data/miniconda3/envs/env-novelai/bin/python
Traceback (most recent call last):
  File "/data/miniconda3/envs/env-novelai/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 977, in launch_command
    multi_gpu_launcher(args)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by lilyzlt** [comment]
Linux environment, using SD1.5, all the param using the default one, when it generate model, then get the error
