### ISSUE TITLE
Error when running under Conda env.

### ISSUE THREAD

**Issue by butaixianran** [bmaltais/kohya_ss#181]
So, I'm using Stable Diffusion WebUI's venv, so I don't have to re-install everything again.

And try to extract the lora from a model. Then get this error:

```
To create a public link, set `share=True` in `launch()`.
.\venv\Scripts\python.exe "networks\extract_lora_from_models.py" --save_precision fp16 --save_to "D:/Work/Dev/AI/stable-diffusion-webui/models/Lora/1real_base_lora.pt" --model_org "D:/Work/Dev/AI/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt" --model_tuned "D:/Work/Dev/AI/stable-diffusion-webui/models/Stable-diffusion/1realBase.safetensors" --dim 128
Traceback (most recent call last):
  File "D:\Work\Dev\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Work\Dev\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\Work\Dev\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Work\Dev\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Work\Dev\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Work\Dev\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Work\Dev\AI\stable-diffusion-webui\kohya_ss\library\extract_lora_gui.py", line 57, in extract_lora
    subprocess.run(run_cmd)
  File "D:\mambaforge\envs\sd\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\mambaforge\envs\sd\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\mambaforge\envs\sd\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2]
```

So, from the error msg, I can find out, it is trying to find python under your project's venv, which is not there.

I think this part should be modified, people have their own env, won't install another python under this project. Especially since most people are working with conda.

**Comment by butaixianran** [comment]
ok, I just check's `kohya-ss/sd-scripts` 's code, it forces user to use his own venv, otherwise nothing can be imported. So we have to re-install everything just for using this tool.

**Comment by bmaltais** [comment]
Correct, this is venv specific... just like auto1111.
