### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by marshalleq** [bmaltais/kohya_ss#1817]
Hi can anyone give me a pointer what is going on here?  Setup is opensuse, 4090, 128G ram

```
checking cache validity...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 350/350 [00:00<00:00, 953870.31it/s]
caching latents...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 350/350 [00:24<00:00, 14.07it/s]
create LoRA network. base dim (rank): 8, alpha: 1.0
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder 1:
create LoRA for Text Encoder 2:
create LoRA for Text Encoder: 264 modules.
create LoRA for U-Net: 722 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
use 8-bit AdamW optimizer | {}
Traceback (most recent call last):
  File "/mnt/ssd2tb_crucial/projects/kohya_ss/./sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "/mnt/ssd2tb_crucial/projects/kohya_ss/train_network.py", line 370, in train
    lr_scheduler = train_util.get_scheduler_fix(args, optimizer, accelerator.num_processes)
  File "/mnt/ssd2tb_crucial/projects/kohya_ss/library/train_util.py", line 3670, in get_scheduler_fix
    key, value = arg.split("=")
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/mnt/ssd2tb_crucial/projects/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/mnt/ssd2tb_crucial/projects/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/mnt/ssd2tb_crucial/projects/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/mnt/ssd2tb_crucial/projects/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/mnt/ssd2tb_crucial/projects/kohya_ss/venv/bin/python', './sdxl_train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--train_data_dir=/mnt/ssd2tb_crucial/projects/kohya_ss/workspace2/train/img', '--reg_data_dir=/mnt/ssd2tb_crucial/projects/kohya_ss/workspace2/train/reg', '--resolution=1024,1024', '--output_dir=/mnt/ssd2tb_crucial/projects/kohya_ss/workspace2/train/model', '--logging_dir=/mnt/ssd2tb_crucial/projects/kohya_ss/workspace2/train/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--network_dim=8', '--output_name=lora', '--lr_scheduler_num_cycles=2', '--no_half_vae', '--learning_rate=4e-07', '--lr_scheduler=constant_with_warmup', '--lr_warmup_steps=2464', '--train_batch_size=2', '--max_train_steps=24640', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--cache_latents', '--optimizer_type=AdamW8bit', '--lr_scheduler_args', 'cosine', '--max_grad_norm=1', '--max_data_loader_n_workers=0', '--resume=/mnt/ssd2tb_crucial/projects/kohya_ss/workspace2/savestate', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0', '--sample_sampler=euler_a', '--sample_prompts=/mnt/ssd2tb_crucial/projects/kohya_ss/workspace2/train/model/sample/prompt.txt', '--sample_every_n_epochs=1', '--sample_every_n_steps=10']' returned non-zero exit status 1.
```

**Comment by marshalleq** [comment]
I am getting this when I start, but it looks like it resolves itself.  I must say I find this installer quite unfriendly.  I'd rather just install my own dependencies, but we have to deal with these scripts instead by the looks - which don't seem to work very well.

```
./gui.sh 
Warning: LD_LIBRARY_PATH environment variable is not set.
Certain functionalities may not work correctly.
Please ensure that the required libraries are properly configured.
 
If you use WSL2 you may want to: export LD_LIBRARY_PATH=/usr/lib/wsl/lib/
 
13:26:39-786592 INFO     Version: v22.3.1                                                                                                                                         
                                                                                                                                                                                  
13:26:39-794786 INFO     nVidia toolkit detected                                                                                                                                  
13:26:41-179731 INFO     Torch 2.0.1+cu118                                                                                                                                        
13:26:41-210959 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700                                                                                                               
13:26:41-263135 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24216 Arch (8, 9) Cores 128                                                                             
13:26:41-265793 INFO     Verifying modules installation status from /mnt/ssd2tb_crucial/projects/kohya_ss/requirements_linux.txt...                                               
13:26:41-267751 WARNING  Package wrong version: torch 2.0.1+cu118 required 2.0.1                                                                                                  
13:26:41-268589 INFO     Installing package: torch==2.0.1                                                                                                                         
13:26:43-119477 WARNING  Package wrong version: torchvision 0.15.2+cu118 required 0.15.2                                                                                          
13:26:43-121364 INFO     Installing package: torchvision==0.15.2                                                                                                                  
13:26:47-199678 INFO     headless: False                                                                                                                                          
13:26:47-202970 INFO     Load CSS...                                                                                                                                              
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

**Comment by marshalleq** [comment]
So that was all on opensuse, I've now installed windows and run it there, exactly the same error.  So either there's part of the install I'm not getting right - something missing maybe, or my images / source files are causing it, or theres a bug effecting both versions.  Or perhaps a mixture of the last two.
