### ISSUE TITLE
Cannot use adafactor on dreambooth/checkpoints

### ISSUE THREAD

**Issue by OriginLive** [bmaltais/kohya_ss#1841]
Hi, i get the following error using adafactor on dreambooth/checkpoints (1.5).

[AnimeVN_v6_ada.json](https://github.com/bmaltais/kohya_ss/files/13841995/AnimeVN_v6_ada.json)

```
100%|██████████| 94/94 [00:00<?, ?it/s]
caching latents...
100%|██████████| 94/94 [00:05<00:00, 16.43it/s]
prepare optimizer, data loader etc.
use Adafactor optimizer | {'scale_parameter': False, 'relative_step': False, 'warmup_init': False}
because max_grad_norm is set, clip_grad_norm is enabled. consider set to 0 / max_grad_normが設定されているためclip_grad_normが有効になります。0に設定して無効にしたほうがいいかもしれません
constant_with_warmup will be good / スケジューラはconstant_with_warmupが良いかもしれません
Traceback (most recent call last):
  File "C:\ai\sm\Packages\kohya_ss\train_db.py", line 501, in <module>
    train(args)
  File "C:\ai\sm\Packages\kohya_ss\train_db.py", line 210, in train
    lr_scheduler = train_util.get_scheduler_fix(args, optimizer, accelerator.num_processes)
  File "C:\ai\sm\Packages\kohya_ss\library\train_util.py", line 3747, in get_scheduler_fix
    initial_lr = float(name.split(":")[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "C:\ai\sm\Packages\kohya_ss\venv\scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\ai\sm\Packages\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\ai\sm\Packages\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\ai\sm\Packages\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\ai\\sm\\Packages\\kohya_ss\\venv\\Scripts\\python.exe', './train_db.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--
pretrained_model_name_or_path=C:/ai/sm/Models/StableDiffusion/xrikishisUnstable_alpha60Anime.safetensors', '--train_data_dir=C:\\ai\\training\\AnimeVNStyle\\AnimeVN_training\\img', '--resolution=512,512', '--output_dir=C:\\ai\\training\\AnimeVNStyle\\AnimeVN_training\\model', '--logging_dir=C:\\ai\\training\\AnimeVNStyle\\AnimeVN_training\\log', '--save_model_as=safetensors', '--output_name=AnimeVN_v6', '--lr_scheduler_num_cycles=10', '--max_data_loader_n_workers=0', '--learning_rate_te=1.0', '--learning_rate=1.0', '--lr_scheduler=adafactor', '--train_batch_size=1', '--max_train_steps=9400', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=Adafactor', '--optimizer_args', 'scale_parameter=False', 'relative_step=False', 'warmup_init=False', '--max_data_loader_n_workers=0', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--noise_offset=0.0357', '--sample_sampler=k_dpm_2', '--sample_prompts=C:\\ai\\training\\AnimeVNStyle\\AnimeVN_training\\model\\sample\\prompt.txt', '--sample_every_n_steps=100']' returned non-zero exit status 1.
```

It looks like 
initial_lr = float(name.split(":")[1])
is trying to get the value of the right hand item, but gets out of bounds exception. Should be ez to fix regardless, just a split issue it seems.

Issue doesn't happen when i don't use `scale_parameter=False relative_step=False warmup_init=False`, but then i can't use adafactor scheduler as recommended.

Overall when using adamw and constant training i keep getting shit results lately. (not related to ticket)

**Comment by aa956** [comment]
For the command line scripts it looks like the script expects the following config:

```toml
optimizer_type="Adafactor"
optimizer_args = ["relative_step=True", "scale_parameter=True", "warmup_init=False",]
learning_rate = 1e-5
# scheduler_name:initial_lr for adafactor scheduler only:
lr_scheduler = "adafactor:1e-5"
```
