### ISSUE TITLE
Error when starting training LoRA

### ISSUE THREAD

**Issue by Ben10124** [bmaltais/kohya_ss#1850]
Every time when I try to train LoRA, this error show up after checking cache validity.
```

learning rate is used as initial_lr / 指定したlearning rateはinitial_lrとして使用されます
unet_lr and text_encoder_lr are ignored / unet_lrとtext_encoder_lrは無視されます
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 11330
  num reg images / 正則化画像の数: 294
  num batches per epoch / 1epochのバッチ数: 22660
  num epochs / epoch数: 15
  batch size per device / バッチサイズ: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 339900
steps:   0%|                                                                                | 0/339900 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\AI\kohya_ss\train_network.py", line 996, in <module>
    trainer.train(args)
  File "C:\AI\kohya_ss\train_network.py", line 689, in train
    accelerator.init_trackers(
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 615, in _inner
    return PartialState().on_main_process(function)(*args, **kwargs)
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 2412, in init_trackers
    tracker_init(project_name, self.logging_dir, **init_kwargs.get(str(tracker), {}))
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\tracking.py", line 71, in execute_on_main_process
    return PartialState().on_main_process(function)(self, *args, **kwargs)
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\tracking.py", line 182, in __init__
    self.writer = tensorboard.SummaryWriter(self.logging_dir, **kwargs)
  File "C:\AI\kohya_ss\venv\lib\site-packages\torch\utils\tensorboard\writer.py", line 247, in __init__
    self._get_file_writer()
  File "C:\AI\kohya_ss\venv\lib\site-packages\torch\utils\tensorboard\writer.py", line 277, in _get_file_writer
    self.file_writer = FileWriter(
  File "C:\AI\kohya_ss\venv\lib\site-packages\torch\utils\tensorboard\writer.py", line 76, in __init__
    self.event_writer = EventFileWriter(
  File "C:\AI\kohya_ss\venv\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 72, in __init__
    tf.io.gfile.makedirs(logdir)
  File "C:\AI\kohya_ss\venv\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 513, in recursive_create_dir_v2    _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.FailedPreconditionError: D:\訓練\log is not a directory
steps:   0%|                                                                                | 0/339900 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Python3106\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python3106\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\AI\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

```

Here is some debugging I tried:

- Reinstall Kohya_SS
- Reinstall Python 
- Setup option 3 0.35.0
- Reinstall vc_redist.x64 
Also, I checked the folder, D:\訓練\log does exist, it's an empty folder.

- Can someone see what's going wrong?

**Comment by Sfever** [comment]
Trying to change the folder name into English
That maybe works
