### ISSUE TITLE
Python-3.11 tracebacks

### ISSUE THREAD

**Issue by brcisna** [bmaltais/kohya_ss#1851]
New to kohya_ss.

Debian Bookworm (12)

EDIT: *SOLVED*- Used the following link to install correct version of Python (3.10.12) for reference.
Have done this in the past but has been many years ago,,and completely forgot the routine how to do this
https://k0nze.dev/posts/install-pyenv-venv-vscode/
pyenv allows you to install multiple versions of python into your home DIR , safely! and use these versions to hook to a venv. 

On install of koyha i seen error my machine is using Python-3.11.
I think the requirmenst does add a version of Python with kohya?. 

EDIT: Just noticed after posting this,it does appear kohya_ss is in fact using the systems Python version, Python-3.11. Is this to be expected? 
Debian Bookworm became the 'stable' version for Debian as of around last June 2023, and ships with Python3.11 

I am getting traceback errors when using the Blip caption generator. Get back traceback error when trying to start a Lara traning.

`Traceback (most recent call last):
  File "/home/brcisna/MyPrograms/kohya/kohya_ss/finetune/make_captions.py", line 16, in <module>
    from blip.blip import blip_decoder, is_url
  File "/home/brcisna/MyPrograms/kohya/kohya_ss/finetune/blip/blip.py", line 13, in <module>
    from blip.vit import VisionTransformer, interpolate_pos_embed
  File "/home/brcisna/MyPrograms/kohya/kohya_ss/finetune/blip/vit.py", line 16, in <module>
    from timm.models.vision_transformer import _cfg, PatchEmbed
  File "/home/brcisna/MyPrograms/kohya/kohya_ss/venv/lib/python3.11/site-packages/timm/__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "/home/brcisna/MyPrograms/kohya/kohya_ss/venv/lib/python3.11/site-packages/timm/models/__init__.py", line 28, in <module>
    from .maxxvit import *
  File "/home/brcisna/MyPrograms/kohya/kohya_ss/venv/lib/python3.11/site-packages/timm/models/maxxvit.py", line 225, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'timm.models.maxxvit.MaxxVitConvCfg'> for field conv_cfg is not allowed: use default_factory
`

Ideas?

TIA

**Comment by TheZaind** [comment]
kohya_ss says on there Installation page that you need Python 3.10. "Windows Pre-requirements
To install the necessary dependencies on a Windows system, follow these steps:

Install [Python 3.10](https://www.python.org/ftp/python/3.10.9/python-3.10.9-amd64.exe).

During the installation process, ensure that you select the option to add Python to the 'PATH' environment variable.
Install [Git](https://git-scm.com/download/win).

Install the [Visual Studio 2015, 2017, 2019, and 2022 redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe)." So just install this (and maby deinstall 3.11) and try it again. Or change a lot of source code 😅
