### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by artemsvit** [bmaltais/kohya_ss#1859]
Hello. I install all from instruction, start train and get this error and don't understand what happen here. Help Plese.

```
[Dataset 0]
caching latents.
checking cache validity...
100%|██████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<?, ?it/s]
caching latents...
100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 12.42it/s]
prepare optimizer, data loader etc.
Traceback (most recent call last):
  File "C:\Users\Admin\kohya_ss\library\train_util.py", line 3480, in get_optimizer
    import bitsandbytes as bnb
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 5, in <module>
    from .cuda_setup.main import evaluate_cuda_setup
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 21, in <module>
    from .paths import determine_cuda_runtime_lib_path
ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\kohya_ss\train_db.py", line 501, in <module>
    train(args)
  File "C:\Users\Admin\kohya_ss\train_db.py", line 182, in train
    _, _, optimizer = train_util.get_optimizer(args, trainable_params)
  File "C:\Users\Admin\kohya_ss\library\train_util.py", line 3482, in get_optimizer
    raise ImportError("No bitsandbytes / bitsandbytesがインストールされていないようです")
ImportError: No bitsandbytes / bitsandbytesがインストールされていないようです
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Admin\\kohya_ss\\venv\\Scripts\\python.exe', './train_db.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=E:/Fooocus/v1-5-pruned.safetensors', '--train_data_dir=C:/Users/Admin/OneDrive/Documents/Training/corporateillustrations/images', '--resolution=512,512', '--output_dir=C:/Users/Admin/OneDrive/Documents/Training/corporateillustrations/model', '--logging_dir=C:/Users/Admin/OneDrive/Documents/Training/corporateillustrations/log', '--save_model_as=safetensors', '--output_name=corporateillustrations', '--lr_scheduler_num_cycles=10', '--max_data_loader_n_workers=0', '--learning_rate_te=1e-05', '--learning_rate=1e-05', '--lr_scheduler=cosine', '--lr_warmup_steps=100', '--train_batch_size=1', '--max_train_steps=1000', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

```

**Comment by brappier** [comment]
install bitsnbytes

**Comment by artemsvit** [comment]
> install bitsnbytes

It's so easy. Maybe you have step by step instructions?

**Comment by TheZaind** [comment]
same problem but it is installed...

**Comment by TheZaind** [comment]
You need to change your optimizer! The bitsnbytes version for kohya_ss dont support AddamW8Bit rieght now... For me now AdamW works, other say they can only use Adafactor! :)

**Comment by TheZaind** [comment]
or if you wanne use the Adam8bit you can change in the "requirements_windows_torch2.tx"t the "bitsandbytes==0.41.1 # no_verify" to "bitsandbytes-windows". Worked for me! it can be that you need to delete the bitsandbytes folder from the venv.
