### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by Sfever** [bmaltais/kohya_ss#1910]
Console Logs:
[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 160/160 [00:00<00:00, 13898.49it/s]
prepare dataset
preparing accelerator
loading model for process 0/1
load Diffusers pretrained models: stabilityai/stable-diffusion-xl-refiner-1.0, variant=fp16
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.31it/s]
Traceback (most recent call last):
  File "D:\Administrator\Documents\kohya_ss\sdxl_train_network.py", line 184, in <module>
    trainer.train(args)
  File "D:\Administrator\Documents\kohya_ss\train_network.py", line 229, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "D:\Administrator\Documents\kohya_ss\sdxl_train_network.py", line 42, in load_target_model
    ) = sdxl_train_util.load_target_model(args, accelerator, sdxl_model_util.MODEL_VERSION_SDXL_BASE_V1_0, weight_dtype)
  File "D:\Administrator\Documents\kohya_ss\library\sdxl_train_util.py", line 34, in load_target_model
    ) = _load_target_model(
  File "D:\Administrator\Documents\kohya_ss\library\sdxl_train_util.py", line 101, in _load_target_model
    if text_encoder1.dtype != torch.float32:
AttributeError: 'NoneType' object has no attribute 'dtype'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Administrator\Documents\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\Administrator\Documents\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\Administrator\Documents\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "D:\Administrator\Documents\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\Administrator\\Documents\\kohya_ss\\venv\\Scripts\\python.exe', './sdxl_train_network.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-refiner-1.0', '--train_data_dir=D:/dataset/processes/prepared/img/', '--resolution=2048,2048', '--output_dir=D:/dataset/processes/prepared/model/', '--logging_dir=D:/dataset/processes/prepared/log/', '--network_alpha=32', '--training_comment=3 repeats. More info: https://civitai.com/articles/1771', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=3e-05', '--unet_lr=3e-05', '--network_dim=32', '--network_weights=D:/Administrator/Documents/stable-diffusion-webui/models/Lora/(v1)reg-any4.5-shenhe-000010-nsfw.safetensors', '--dim_from_weights', '--output_name=last', '--lr_scheduler_num_cycles=50', '--no_half_vae', '--learning_rate=3e-05', '--lr_scheduler=linear', '--train_batch_size=3', '--max_train_steps=4000', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--caption_extension=.txt', '--cache_latents', '--cache_latents_to_disk', '--optimizer_type=AdamW', '--max_grad_norm=1', '--max_train_epochs=50', '--max_data_loader_n_workers=0', '--caption_dropout_rate=0.05', '--bucket_reso_steps=64', '--min_snr_gamma=5', '--gradient_checkpointing', '--xformers', '--noise_offset=0.0']' returned non-zero exit status 1.

Not Sure What's happening
I'm training Lora

**Comment by Sfever** [comment]
I've tried again,
seems Dreambooth refuses to work as well
both using official SDXL-refiner model

**Comment by piotr-sikora-v** [comment]
I have same error using docker image on runpod.io

**Comment by muneeb2001** [comment]
@bmaltais I am still facing this issue while training LORA model: `stabilityai/stable-diffusion-xl-refiner-1.0`

```
File "/home/muneeb/Desktop/projects/proptexx/lora-training/kohya_update/kohya_ss/sd-scripts/sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "/home/muneeb/Desktop/projects/proptexx/lora-training/kohya_update/kohya_ss/sd-scripts/train_network.py", line 234, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "/home/muneeb/Desktop/projects/proptexx/lora-training/kohya_update/kohya_ss/sd-scripts/sdxl_train_network.py", line 44, in load_target_model
    ) = sdxl_train_util.load_target_model(args, accelerator, sdxl_model_util.MODEL_VERSION_SDXL_BASE_V1_0, weight_dtype)
  File "/home/muneeb/Desktop/projects/proptexx/lora-training/kohya_update/kohya_ss/sd-scripts/library/sdxl_train_util.py", line 40, in load_target_model
    ) = _load_target_model(
  File "/home/muneeb/Desktop/projects/proptexx/lora-training/kohya_update/kohya_ss/sd-scripts/library/sdxl_train_util.py", line 106, in _load_target_model
    if text_encoder1.dtype != torch.float32:
AttributeError: 'NoneType' object has no attribute 'dtype'
```

**Comment by lastYoueven** [comment]
I have same error using docker image on runpod.io
