### ISSUE TITLE
AttributeError: module 'triton' has no attribute '__version__'

### ISSUE THREAD

**Issue by ThisIsNetsu** [bmaltais/kohya_ss#1920]
Hey there!

Ever since kohya_ss updated to Torch 2.1.1. I am unable to run any sort of training anymore.

AttributeError: module 'triton' has no attribute '__version__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "I:\kohya_ss\sdxl_train_network.py", line 8, in <module>
    from library import sdxl_model_util, sdxl_train_util, train_util
  File "I:\kohya_ss\library\sdxl_model_util.py", line 7, in <module>
    from diffusers import AutoencoderKL, EulerDiscreteScheduler, UNet2DConditionModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "I:\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 701, in __getattr__
    value = getattr(module, name)
  File "I:\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 700, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "I:\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 712, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
module 'triton' has no attribute '__version__'

I am on Windows11 and have freshly installed kohya_ss.  Any idea what is happening here? :(

**Comment by ThisIsNetsu** [comment]
A complete reinstall from scratch has solved the problem.
