### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\xf8'. when custom model load

### ISSUE THREAD

**Issue by piotr-sikora-v** [bmaltais/kohya_ss#1927]
I have an error when I try to use i.e. animagine checkpoint model.
I selected custom model, and SDXL version.
When I try to start I have this error:

```
load StableDiffusion checkpoint: /sd-models/animagine.safetensor
Traceback (most recent call last):
  File "/workspace/kohya_ss/./train_network.py", line 1033, in <module>
    trainer.train(args)
  File "/workspace/kohya_ss/./train_network.py", line 229, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "/workspace/kohya_ss/./train_network.py", line 98, in load_target_model
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "/workspace/kohya_ss/library/train_util.py", line 3996, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "/workspace/kohya_ss/library/train_util.py", line 3950, in _load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(
  File "/workspace/kohya_ss/library/model_util.py", line 997, in load_models_from_stable_diffusion_checkpoint
    _, state_dict = load_checkpoint_with_text_encoder_conversion(ckpt_path, device)
  File "/workspace/kohya_ss/library/model_util.py", line 974, in load_checkpoint_with_text_encoder_conversion
    checkpoint = torch.load(ckpt_path, map_location=device)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xf8'.
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/workspace/kohya_ss/venv/bin/python3', './train_network.py', '--pretrained_model_name_or_path=/sd-models/animagine.safetensor', '--train_data_dir=/workspace/girls-out/', '--resolution=1024,1024', '--output_dir=/workspace/model/', '--logging_dir=/workspace/logs/', '--network_alpha=16', '--save_model_as=ckpt', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=8', '--output_name=fl-lora', '--lr_scheduler_num_cycles=10', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=8625', '--train_batch_size=4', '--max_train_steps=86250', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_grad_norm=1', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--noise_offset=0.0', '--sample_sampler=euler_a', '--sample_prompts=/workspace/model/sample/prompt.txt', '--sample_every_n_epochs=1', '--sample_every_n_steps=100']' returned non-zero exit status 1.
```

**Comment by elthariel** [comment]
Your path is missing an 's'. Must be  `/sd-models/animagine.safetensors` <
