### ISSUE TITLE
BLIP captioning broken

### ISSUE THREAD

**Issue by nathankrueger** [bmaltais/kohya_ss#1944]
Using Python 3.10.9 on Windows 11

Current Working Directory is:  C:\Users\natek\Apps\Khoya\kohya_ss
load images from C:\Users\natek\Downloads\test_blip
found 3 images.
loading BLIP caption: https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth
Traceback (most recent call last):
  File "C:\Users\natek\Apps\Khoya\kohya_ss\finetune\make_captions.py", line 202, in <module>
    main(args)
  File "C:\Users\natek\Apps\Khoya\kohya_ss\finetune\make_captions.py", line 88, in main
    model = blip_decoder(pretrained=args.caption_weights, image_size=IMAGE_SIZE, vit="large", med_config="./blip/med_config.json")
  File "C:\Users\natek\Apps\Khoya\kohya_ss\finetune\blip\blip.py", line 175, in blip_decoder
    model = BLIP_Decoder(**kwargs)
  File "C:\Users\natek\Apps\Khoya\kohya_ss\finetune\blip\blip.py", line 98, in __init__
    self.tokenizer = init_tokenizer()
  File "C:\Users\natek\Apps\Khoya\kohya_ss\finetune\blip\blip.py", line 189, in init_tokenizer
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
  File "C:\Users\natek\Apps\Khoya\kohya_ss\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 2028, in from_pretrained
    return cls._from_pretrained(
  File "C:\Users\natek\Apps\Khoya\kohya_ss\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 2260, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "C:\Users\natek\Apps\Khoya\kohya_ss\venv\lib\site-packages\transformers\models\bert\tokenization_bert.py", line 199, in __init__
    if not os.path.isfile(vocab_file):
  File "C:\Users\natek\.pyenv\pyenv-win\versions\3.10.9\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
18:58:26-939255 INFO     ...captioning done

**Comment by bmaltais** [comment]
This is an issue that should be directly to kohya's sd-script repo. I only copy his script files and this is not one I maintain.
