### ISSUE TITLE
No idea what the error is.

### ISSUE THREAD

**Issue by ppapepp** [bmaltais/kohya_ss#1955]
Going to start off by staying that this is probably one of the worst GUI's I've ever had the misfortune to use and I hope someone more competent makes a better fork because this has been a painful process. 

`
09:43:19-764971 INFO     Start training LoRA Standard ...
09:43:19-781880 INFO     Checking for duplicate image filenames in training data directory...
09:43:19-791800 INFO     Valid image folder names found in: C:/Users/NAME/Desktop/AI/Test/img
09:43:19-793786 INFO     Valid image folder names found in: C:/Users/NAME/Desktop/AI/Test/reg
09:43:19-795769 INFO     Folder 20_Test subject: 8 images found
09:43:19-798745 INFO     Folder 20_Test subject: 160 steps
09:43:19-800729 WARNING  Regularisation images are used... Will double the number of steps required...
09:43:19-802026 INFO     Total steps: 160
09:43:19-803514 INFO     Train batch size: 2
09:43:19-805001 INFO     Gradient accumulation steps: 1
09:43:19-808475 INFO     Epoch: 20
09:43:19-809963 INFO     Regulatization factor: 2
09:43:19-811946 INFO     max_train_steps (160 / 2 / 1 * 20 * 2) = 3200
09:43:19-816910 INFO     stop_text_encoder_training = 0
09:43:19-818891 INFO     lr_warmup_steps = 0
09:43:19-823377 INFO     Saving training config to C:/Users/NAME/Desktop/AI/Test\Test_20240210-094319.json...
09:43:19-832594 INFO     accelerate launch --num_cpu_threads_per_process=4 "./sdxl_train_network.py"
                         --enable_bucket --min_bucket_reso=256 --max_bucket_reso=1024
                         --pretrained_model_name_or_path="C:/Users/NAME/Desktop/AI/realismXL.safetensors"
                         --train_data_dir="C:/Users/NAME/Desktop/AI/Test/img"
                         --reg_data_dir="C:/Users/NAME/Desktop/AI/Test/reg" --resolution="1024,1024"
                         --output_dir="C:/Users/NAME/Desktop/AI/Test" --network_alpha="32" --training_comment="3
                         repeats. More info: https://civitai.com/articles/1771" --save_model_as=safetensors
                         --network_module=networks.lora --text_encoder_lr=3e-05 --unet_lr=3e-05 --network_dim=32
                         --output_name="Test" --lr_scheduler_num_cycles="20" --no_half_vae
                         --learning_rate="3e-05" --lr_scheduler="constant" --train_batch_size="2"
                         --max_train_steps="3200" --save_every_n_epochs="1" --mixed_precision="fp16"
                         --save_precision="fp16" --caption_extension=".txt" --cache_latents
                         --cache_latents_to_disk --optimizer_type="AdamW8bit" --max_grad_norm="1"
                         --max_train_epochs=20 --max_data_loader_n_workers="0" --caption_dropout_rate="0.05"
                         --bucket_reso_steps=64 --min_snr_gamma=5 --gradient_checkpointing --fp8_base --xformers
                         --noise_offset=0.0
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
prepare tokenizers
Using DreamBooth method.
prepare images.
found directory C:\Users\NAME\Desktop\AI\Test\img\20_Test subject contains 8 image files
found directory C:\Users\NAME\Desktop\AI\Test\reg\2_subject contains 48 image files
160 train images with repeating.
96 reg images.
[Dataset 0]
  batch_size: 2
  resolution: (1024, 1024)
  enable_bucket: True
  network_multiplier: 1.0
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: False

  [Subset 0 of Dataset 0]
    image_dir: "C:\Users\NAME\Desktop\AI\Test\img\20_Test subject"
    image_count: 8
    num_repeats: 20
    shuffle_caption: False
    keep_tokens: 0
    keep_tokens_separator:
    caption_dropout_rate: 0.05
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: Test subject
    caption_extension: .txt

  [Subset 1 of Dataset 0]
    image_dir: "C:\Users\NAME\Desktop\AI\Test\reg\2_subject"
    image_count: 48
    num_repeats: 2
    shuffle_caption: False
    keep_tokens: 0
    keep_tokens_separator:
    caption_dropout_rate: 0.05
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: True
    class_tokens: subject
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|██████████████████████████████████████████████████████████████████████████| 56/56 [00:00<00:00, 626.82it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (704, 1024), count: 215
bucket 1: resolution (768, 1024), count: 28
bucket 2: resolution (832, 1024), count: 11
bucket 3: resolution (896, 1024), count: 20
bucket 4: resolution (1024, 576), count: 20
bucket 5: resolution (1024, 704), count: 12
bucket 6: resolution (1024, 1024), count: 14
mean ar error (without repeats): 0.008428389886564183
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: C:/Users/NAME/Desktop/AI/realismXL.safetensors
building U-Net
loading U-Net from checkpoint
U-Net:  <All keys matched successfully>
building text encoders
loading text encoders from checkpoint
text encoder 1: <All keys matched successfully>
text encoder 2: <All keys matched successfully>
building VAE
loading VAE from checkpoint
VAE: <All keys matched successfully>
Enable xformers for U-Net
import network module: networks.lora
[Dataset 0]
caching latents.
checking cache validity...
100%|███████████████████████████████████████████████████████████████████████████| 56/56 [00:00<00:00, 80.53it/s]
caching latents...
100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.52s/it]
create LoRA network. base dim (rank): 32, alpha: 32.0
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder 1:
create LoRA for Text Encoder 2:
create LoRA for Text Encoder: 264 modules.
create LoRA for U-Net: 722 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: C:\Users\NAME\Desktop\AI\kohya_ss\venv\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary C:\Users\NAME\Desktop\AI\kohya_ss\venv\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
use 8-bit AdamW optimizer | {}
override steps. steps for 20 epochs is / 指定エポックまでのステップ数: 3220
enable fp8 training.
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 160
  num reg images / 正則化画像の数: 96
  num batches per epoch / 1epochのバッチ数: 161
  num epochs / epoch数: 20
  batch size per device / バッチサイズ: 2
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 3220
steps:   0%|                                                                           | 0/3220 [00:00<?, ?it/s]
epoch 1/20
C:\Users\NAME\Desktop\AI\kohya_ss\venv\lib\site-packages\torch\utils\checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
Traceback (most recent call last):
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\NAME\Desktop\AI\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\NAME\Desktop\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\NAME\Desktop\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\Users\NAME\Desktop\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\NAME\\Desktop\\AI\\kohya_ss\\venv\\Scripts\\python.exe', './sdxl_train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--pretrained_model_name_or_path=C:/Users/NAME/Desktop/AI/realismXL.safetensors', '--train_data_dir=C:/Users/NAME/Desktop/AI/Test/img', '--reg_data_dir=C:/Users/NAME/Desktop/AI/Test/reg', '--resolution=1024,1024', '--output_dir=C:/Users/NAME/Desktop/AI/Test', '--network_alpha=32', '--training_comment=3 repeats. More info: https://civitai.com/articles/1771', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=3e-05', '--unet_lr=3e-05', '--network_dim=32', '--output_name=Test', '--lr_scheduler_num_cycles=20', '--no_half_vae', '--learning_rate=3e-05', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=3200', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--caption_extension=.txt', '--cache_latents', '--cache_latents_to_disk', '--optimizer_type=AdamW8bit', '--max_grad_norm=1', '--max_train_epochs=20', '--max_data_loader_n_workers=0', '--caption_dropout_rate=0.05', '--bucket_reso_steps=64', '--min_snr_gamma=5', '--gradient_checkpointing', '--fp8_base', '--xformers', '--noise_offset=0.0']' returned non-zero exit status 1.
`

**Comment by OldNewDesign** [comment]
Getting the same errors. Fails with bitsandbytes.
