### ISSUE TITLE
Errors on top of errors

### ISSUE THREAD

**Issue by GuyFromTheInternet** [bmaltais/kohya_ss#1956]
I can barely do anything, I try to train a lora I get this?? whatever does that mean??? 
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
prepare tokenizer
Using DreamBooth method.
prepare images.
0 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: False
  network_multiplier: 1.0

[Dataset 0]
loading image sizes.
0it [00:00, ?it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
D:\kohya\kohya_ss\venv\lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
D:\kohya\kohya_ss\venv\lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
mean ar error (without repeats): nan
No data found. Please verify arguments (train_data_dir must be the parent of folders with images) / 画像がありません。引数指定を確認してください（train_data_dirには画像があるフォルダではなく、画像があるフォルダの親フォルダを指定する必要があります）

I try to caption stuff, but the only thing that works is clip, other ones say:
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
using existing wd14 tagger model
Traceback (most recent call last):
  File "D:\kohya\kohya_ss\finetune\tag_images_by_wd14_tagger.py", line 379, in <module>
    main(args)
  File "D:\kohya\kohya_ss\finetune\tag_images_by_wd14_tagger.py", line 140, in main
    model = load_model(f"{args.model_dir}")
  File "D:\kohya\kohya_ss\venv\lib\site-packages\keras\src\saving\saving_api.py", line 262, in load_model
    return legacy_sm_saving_lib.load_model(
  File "D:\kohya\kohya_ss\venv\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\kohya\kohya_ss\venv\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 119, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: SmilingWolf/wd-v1-4-convnextv2-tagger-v2\{saved_model.pbtxt|saved_model.pb}
Traceback (most recent call last):
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "D:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', './finetune/tag_images_by_wd14_tagger.py', '--batch_size=8', '--general_threshold=0.35', '--character_threshold=0.35', '--caption_extension=.txt', '--caption_separator=,', '--model=SmilingWolf/wd-v1-4-convnextv2-tagger-v2', '--max_data_loader_n_workers=2', 'D:/kohya/lora']' returned non-zero exit status 1.

I tried searching for fixes, uninstalled like 5 times, uninstalled git, python and everything but its all still the same

**Comment by codeliuyang** [comment]
It seems you should go to download `SmilingWolf/wd-v1-4-convnextv2-tagger-v2`

go to https://huggingface.co/SmilingWolf/wd-v1-4-convnextv2-tagger-v2
