### ISSUE TITLE
died with <Signals.SIGKILL: 9>

### ISSUE THREAD

**Issue by Rorutop** [bmaltais/kohya_ss#1958]
I just want to train an sdxl lora on the google colab kohya ss. Couldn't figure out how to fix this issue searching all over, I had to submit an issue for this

```
10:07:41-258207 INFO     Start training LoRA Standard ...                                           
10:07:41-259717 ERROR    The following folders do not match the required pattern <number>_<text>:   
                         /content/bodysketchimages/.ipynb_checkpoints,                              
                         /content/bodysketchimages/newstuff                                         
10:07:41-261075 ERROR    Please follow the folder structure documentation found at                  
                         docs\image_folder_structure.md ...                                         
10:07:41-262653 INFO     Headless mode, skipping verification if model already exist... if model    
                         already exist it will be overwritten...                                    
10:07:41-263877 INFO     Folder 4_sexo: 16 images found                                             
10:07:41-264839 INFO     Folder 4_sexo: 64 steps                                                    
10:07:41-265735 INFO     Error: 'newstuff' does not contain an underscore, skipping...              
10:07:41-266889 INFO     Error: '.ipynb_checkpoints' does not contain an underscore, skipping...    
10:07:41-268254 INFO     Folder 4_main: 203 images found                                            
10:07:41-269361 INFO     Folder 4_main: 812 steps                                                   
10:07:41-270508 INFO     Folder 3_chibis: 17 images found                                           
10:07:41-271584 INFO     Folder 3_chibis: 51 steps                                                  
10:07:41-272541 INFO     Total steps: 927                                                           
10:07:41-273466 INFO     Train batch size: 2                                                        
10:07:41-274350 INFO     Gradient accumulation steps: 1.0                                           
10:07:41-275231 INFO     Epoch: 10                                                                  
10:07:41-276069 INFO     Regulatization factor: 1                                                   
10:07:41-276943 INFO     max_train_steps (927 / 2 / 1.0 * 10 * 1) = 4635                            
10:07:41-277992 INFO     stop_text_encoder_training = 0                                             
10:07:41-278899 INFO     lr_warmup_steps = 0                                                        
10:07:41-286265 INFO     Saving training config to                                                  
                         /content/drive/MyDrive/LoRA/output/BodyPoseSketches_20240212-100741.json...
10:07:41-292418 INFO     accelerate launch --num_cpu_threads_per_process=2 "./sdxl_train_network.py"
                         --enable_bucket                                                            
                         --pretrained_model_name_or_path="/content/aamturbo.safetensors"            
                         --train_data_dir="/content/bodysketchimages" --resolution="768,768"        
                         --output_dir="/content/drive/MyDrive/LoRA/output"                          
                         --logging_dir="/content/drive/MyDrive/LoRA/output/tensorlog/"              
                         --network_alpha="16" --save_model_as=safetensors                           
                         --network_module=networks.lora --text_encoder_lr=1.0 --unet_lr=1.0         
                         --network_dim=32 --output_name="BodyPoseSketches"                          
                         --lr_scheduler_num_cycles="10" --scale_weight_norms="1"                    
                         --network_dropout="0.3" --no_half_vae --learning_rate="1.0"                
                         --lr_scheduler="cosine" --train_batch_size="2" --max_train_steps="4635"    
                         --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" 
                         --seed="1234" --caption_extension=".txt" --cache_latents                   
                         --optimizer_type="Prodigy" --optimizer_args "decouple=True"                
                         "weight_decay=0.01" "d_coef=0.5" "use_bias_correction=True"                
                         "safeguard_warmup=True" "betas=0.9,0.99" --max_data_loader_n_workers="1"   
                         --clip_skip=2 --bucket_reso_steps=64 --min_snr_gamma=5 --mem_eff_attn      
                         --shuffle_caption --gradient_checkpointing --xformers --bucket_no_upscale  
                         --multires_noise_iterations="6" --multires_noise_discount="0.14"           
                         --sample_sampler=euler_a                                                   
                         --sample_prompts="/content/drive/MyDrive/LoRA/output/sample/prompt.txt"    
                         --sample_every_n_epochs="2"                                                
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/dist-packages/torchvision/image.so: undefined symbol: _ZN3c104cuda9SetDeviceEi'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
2024-02-12 10:07:49.604797: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-12 10:07:49.604847: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-12 10:07:49.606144: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-12 10:07:50.683409: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/dist-packages/torchvision/image.so: undefined symbol: _ZN3c104cuda9SetDeviceEi'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
prepare tokenizers
Using DreamBooth method.
ignore directory without repeats / 繰り返し回数のないディレクトリを無視します: newstuff
ignore directory without repeats / 繰り返し回数のないディレクトリを無視します: .ipynb_checkpoints
prepare images.
found directory /content/bodysketchimages/4_sexo contains 16 image files
found directory /content/bodysketchimages/4_main contains 203 image files
found directory /content/bodysketchimages/3_chibis contains 17 image files
927 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 2
  resolution: (768, 768)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "/content/bodysketchimages/4_sexo"
    image_count: 16
    num_repeats: 4
    shuffle_caption: True
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: sexo
    caption_extension: .txt

  [Subset 1 of Dataset 0]
    image_dir: "/content/bodysketchimages/4_main"
    image_count: 203
    num_repeats: 4
    shuffle_caption: True
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: main
    caption_extension: .txt

  [Subset 2 of Dataset 0]
    image_dir: "/content/bodysketchimages/3_chibis"
    image_count: 17
    num_repeats: 3
    shuffle_caption: True
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: chibis
    caption_extension: .txt


[Dataset 0]
loading image sizes.
100% 236/236 [00:00<00:00, 10753.22it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (192, 256), count: 8
bucket 1: resolution (192, 320), count: 11
bucket 2: resolution (256, 320), count: 8
bucket 3: resolution (256, 384), count: 4
bucket 4: resolution (256, 512), count: 4
bucket 5: resolution (320, 256), count: 4
bucket 6: resolution (320, 320), count: 12
bucket 7: resolution (320, 384), count: 4
bucket 8: resolution (320, 448), count: 12
bucket 9: resolution (320, 512), count: 8
bucket 10: resolution (320, 576), count: 4
bucket 11: resolution (320, 640), count: 4
bucket 12: resolution (384, 384), count: 4
bucket 13: resolution (384, 448), count: 4
bucket 14: resolution (384, 512), count: 4
bucket 15: resolution (384, 576), count: 8
bucket 16: resolution (384, 896), count: 4
bucket 17: resolution (384, 1152), count: 3
bucket 18: resolution (448, 256), count: 4
bucket 19: resolution (448, 448), count: 8
bucket 20: resolution (448, 576), count: 16
bucket 21: resolution (448, 640), count: 24
bucket 22: resolution (448, 704), count: 12
bucket 23: resolution (448, 1024), count: 8
bucket 24: resolution (512, 512), count: 12
bucket 25: resolution (512, 704), count: 12
bucket 26: resolution (512, 768), count: 14
bucket 27: resolution (512, 832), count: 4
bucket 28: resolution (512, 896), count: 4
bucket 29: resolution (512, 960), count: 8
bucket 30: resolution (512, 1024), count: 8
bucket 31: resolution (512, 1088), count: 8
bucket 32: resolution (576, 384), count: 4
bucket 33: resolution (576, 448), count: 20
bucket 34: resolution (576, 576), count: 8
bucket 35: resolution (576, 640), count: 4
bucket 36: resolution (576, 768), count: 12
bucket 37: resolution (576, 832), count: 27
bucket 38: resolution (576, 896), count: 28
bucket 39: resolution (576, 960), count: 36
bucket 40: resolution (576, 1024), count: 43
bucket 41: resolution (640, 448), count: 4
bucket 42: resolution (640, 512), count: 12
bucket 43: resolution (640, 576), count: 4
bucket 44: resolution (640, 640), count: 8
bucket 45: resolution (640, 768), count: 32
bucket 46: resolution (640, 832), count: 95
bucket 47: resolution (640, 896), count: 107
bucket 48: resolution (704, 384), count: 4
bucket 49: resolution (704, 512), count: 4
bucket 50: resolution (704, 576), count: 24
bucket 51: resolution (704, 640), count: 8
bucket 52: resolution (704, 704), count: 11
bucket 53: resolution (704, 768), count: 36
bucket 54: resolution (704, 832), count: 8
bucket 55: resolution (768, 640), count: 8
bucket 56: resolution (768, 704), count: 8
bucket 57: resolution (768, 768), count: 28
bucket 58: resolution (832, 640), count: 92
mean ar error (without repeats): 0.021656006331568087
clip_skip will be unexpected / SDXL学習ではclip_skipは動作しません
Warning: SDXL has been trained with noise_offset=0.0357, but noise_offset is disabled due to multires_noise_iterations / SDXLはnoise_offset=0.0357で学習されていますが、multires_noise_iterationsが有効になっているためnoise_offsetは無効になります
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: /content/aamturbo.safetensors
building U-Net
loading U-Net from checkpoint
U-Net:  <All keys matched successfully>
building text encoders
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1023, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 643, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', './sdxl_train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=/content/aamturbo.safetensors', '--train_data_dir=/content/bodysketchimages', '--resolution=768,768', '--output_dir=/content/drive/MyDrive/LoRA/output', '--logging_dir=/content/drive/MyDrive/LoRA/output/tensorlog/', '--network_alpha=16', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=1.0', '--unet_lr=1.0', '--network_dim=32', '--output_name=BodyPoseSketches', '--lr_scheduler_num_cycles=10', '--scale_weight_norms=1', '--network_dropout=0.3', '--no_half_vae', '--learning_rate=1.0', '--lr_scheduler=cosine', '--train_batch_size=2', '--max_train_steps=4635', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=Prodigy', '--optimizer_args', 'decouple=True', 'weight_decay=0.01', 'd_coef=0.5', 'use_bias_correction=True', 'safeguard_warmup=True', 'betas=0.9,0.99', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--min_snr_gamma=5', '--mem_eff_attn', '--shuffle_caption', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale', '--multires_noise_iterations=6', '--multires_noise_discount=0.14', '--sample_sampler=euler_a', '--sample_prompts=/content/drive/MyDrive/LoRA/output/sample/prompt.txt', '--sample_every_n_epochs=2']' died with <Signals.SIGKILL: 9>.
```

Additionally using `--lowram` on the additional parameters does not work, I get this error
```
Warning: SDXL has been trained with noise_offset=0.0357, but noise_offset is disabled due to multires_noise_iterations / SDXLはnoise_offset=0.0357で学習されていますが、multires_noise_iterationsが有効になっているためnoise_offsetは無効になります
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: /content/aamturbo.safetensors
Traceback (most recent call last):
  File "/content/kohya_ss/./sdxl_train_network.py", line 167, in <module>
    trainer.train(args)
  File "/content/kohya_ss/train_network.py", line 213, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "/content/kohya_ss/./sdxl_train_network.py", line 34, in load_target_model
    ) = sdxl_train_util.load_target_model(args, accelerator, sdxl_model_util.MODEL_VERSION_SDXL_BASE_V0_9, weight_dtype)
  File "/content/kohya_ss/library/sdxl_train_util.py", line 34, in load_target_model
    ) = _load_target_model(args, model_version, weight_dtype, accelerator.device if args.lowram else "cpu")
  File "/content/kohya_ss/library/sdxl_train_util.py", line 69, in _load_target_model
    ) = sdxl_model_util.load_models_from_sdxl_checkpoint(model_version, name_or_path, device)
  File "/content/kohya_ss/library/sdxl_model_util.py", line 91, in load_models_from_sdxl_checkpoint
    state_dict = load_file(ckpt_path, device=map_location)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: device cuda is invalid
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1023, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 643, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', './sdxl_train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=/content/aamturbo.safetensors', '--train_data_dir=/content/bodysketchimages', '--resolution=768,768', '--output_dir=/content/drive/MyDrive/LoRA/output', '--logging_dir=/content/drive/MyDrive/LoRA/output/tensorlog/', '--network_alpha=16', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=1.0', '--unet_lr=1.0', '--network_dim=32', '--output_name=BodyPoseSketches', '--lr_scheduler_num_cycles=10', '--scale_weight_norms=1', '--network_dropout=0.3', '--no_half_vae', '--learning_rate=1.0', '--lr_scheduler=cosine', '--train_batch_size=2', '--max_train_steps=4635', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=Prodigy', '--optimizer_args', 'decouple=True', 'weight_decay=0.01', 'd_coef=0.5', 'use_bias_correction=True', 'safeguard_warmup=True', 'betas=0.9,0.99', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--min_snr_gamma=5', '--mem_eff_attn', '--shuffle_caption', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale', '--multires_noise_iterations=6', '--multires_noise_discount=0.14', '--lowram', '--sample_sampler=euler_a', '--sample_prompts=/content/drive/MyDrive/LoRA/output/sample/prompt.txt', '--sample_every_n_epochs=2']' returned non-zero exit status 1
```

**Comment by DKnight54** [comment]
<Signals.SIGKILL: 9> basically means that Colab killed your script due to one of 2 possible reasons: Out of RAM, or out of VRAM. I noticed that you were trying to load a safetensor file as your base model, and from my own experiences, loading a safetensor file costs more VRAM than loading a diffuser model, and usually causes a <Signals.SIGKILL: 9>

At a guess from the filename, which I could be wrong, you might be trying to train on [this model](https://civitai.com/models/269232?modelVersionId=330157), in which case, try loading the diffuser model(Which the creator has kindly put up on huggingface) by changing the base model arguement to point at the huggingface model `--pretrained_model_or_path="Lykon/AAM_XL_AnimeMix_Turbo"`

If that's not the model you are seeking to train, I think the only way is to either try to find the diffuser format model in huggingface, or converting the model to diffuser format first. I've got no experience in the later tho.
