### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by moesie** [bmaltais/kohya_ss#1973]
Issue is occuring anytime I want to train a LORA:

<
 ```
 [Subset 0 of Dataset 0]
    image_dir: "C:\Users\name\Downloads\name2\LORA_Training\image_dir\6_name2"
    image_count: 1323
    num_repeats: 6
    shuffle_caption: False
    keep_tokens: 0
    keep_tokens_separator: 
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: name2
    caption_extension: .txt


[Dataset 0]
loading image sizes.
100%|██████████| 1323/1323 [00:15<00:00, 87.38it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (384, 512), count: 660
bucket 1: resolution (384, 576), count: 5892
bucket 2: resolution (512, 384), count: 60
bucket 3: resolution (576, 384), count: 1326
mean ar error (without repeats): 4.7978881809717335e-05
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: C:/SM/Data/Models/StableDiffusion/modelname.safetensors
Traceback (most recent call last):
  File "C:\SM\Data\Packages\kohya_ss\train_network.py", line 1033, in <module>
    trainer.train(args)
  File "C:\SM\Data\Packages\kohya_ss\train_network.py", line 229, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "C:\SM\Data\Packages\kohya_ss\train_network.py", line 98, in load_target_model
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "C:\SM\Data\Packages\kohya_ss\library\train_util.py", line 3996, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "C:\SM\Data\Packages\kohya_ss\library\train_util.py", line 3950, in _load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(
  File "C:\SM\Data\Packages\kohya_ss\library\model_util.py", line 997, in load_models_from_stable_diffusion_checkpoint
    _, state_dict = load_checkpoint_with_text_encoder_conversion(ckpt_path, device)
  File "C:\SM\Data\Packages\kohya_ss\library\model_util.py", line 972, in load_checkpoint_with_text_encoder_conversion
    state_dict = load_file(ckpt_path)  # , device) # may causes error
  File "C:\SM\Data\Packages\kohya_ss\venv\lib\site-packages\safetensors\torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "C:\SM\Data\Packages\kohya_ss\venv\scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\SM\Data\Packages\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\SM\Data\Packages\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\SM\Data\Packages\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\SM\\Data\\Packages\\kohya_ss\\venv\\Scripts\\python.exe', './train_network.py', '--bucket_no_upscale', '--bucket_reso_steps=64', '--cache_latents', '--caption_extension=.txt', '--clip_skip=2', '--enable_bucket', '--min_bucket_reso=320', '--max_bucket_reso=768', '--learning_rate=0.0001', '--logging_dir=C:/Users/name/Downloads/name2/LORA_Training/Log', '--lr_scheduler=constant', '--lr_scheduler_num_cycles=5', '--max_data_loader_n_workers=1', '--max_grad_norm=1', '--resolution=512,512', '--max_token_length=225', '--max_train_steps=39690', '--min_snr_gamma=5', '--mixed_precision=fp16', '--network_alpha=128', '--network_dim=256', '--network_module=networks.lora', '--optimizer_type=AdamW8bit', '--output_dir=C:/Users/name/Downloads/name2/LORA_Training/output_dir', '--output_name=name2', '--pretrained_model_name_or_path=C:/SM/Data/Models/StableDiffusion/modelname.safetensors', '--save_every_n_epochs=1', '--save_model_as=safetensors', '--save_precision=fp16', '--seed=1234', '--text_encoder_lr=5e-05', '--train_batch_size=1', '--train_data_dir=C:/Users/name/Downloads/name2/LORA_Training/image_dir', '--unet_lr=0.0001', '--xformers']' returned non-zero exit status 1.
```
>

**Comment by bmaltais** [comment]
Look like the file you are trying to train against has a format issue... Try with the base model and see if that work...
