### ISSUE TITLE
Stable-cascade support

### ISSUE THREAD

**Issue by bmaltais** [bmaltais/kohya_ss#1982]
I have started work on supporting stable-cascade in the GUI,,, hope it will not be too much of a pain to implement. Let's discuss it in here.

**Comment by GamingDaveUk** [comment]
Happy to see this, not much I can add to the discussion other than a thank you for undertaking this. People like yourself creating and maintaining these tools are the reason so much content exists. Thank you

**Comment by futureflix87** [comment]
Thank you so much!!

**Comment by bmaltais** [comment]
Can someone share a toml config file for a simple one concept finetuning? I never do finetuning and apparently using .toml is the way to go now... and I have no clue how to configure it ;-)

**Comment by bmaltais** [comment]
I have figured it out...

```
[[datasets]]
resolution = 1024
batch_size = 4
keep_tokens = 1
enable_bucket = true

  [[datasets.subsets]]
  image_dir = 'd:\kohya_ss\examples\stable_cascade\test_dataset'
  num_repeats = 10
  class_tokens = 'toy'
  caption_extension = '.txt'
```

**Comment by bmaltais** [comment]
Look like I am successful in finetuning...

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/e3824387-486e-4d47-9fd7-e53602373d48)

Finetuning as `zxc` class `toy` and prompting with `zxc toy posing at the beach --W 800 --H 1200`... so there is hope

**Comment by bmaltais** [comment]
I have shared the test dataset in the stable_cascade branch. Look under the examples folder. You can play with it for now.

**Comment by bmaltais** [comment]
I tested the results of th model in COmfyUI and they are not great... sort of washed out... Most certainly bad training parameters... Will take a while to figureout proper SC finetuning parameters...

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/fb5aa5c5-906e-492b-aaa7-9531b2487763)

**Comment by brentjohnston** [comment]
Anything I could do help, or specific parameters you suspect? I could try to help narrow this down also by running some test trainings.

**Comment by bmaltais** [comment]
If you find better parameters for better results please share.  Training SC is hugely VRAM intensive.

**Comment by brentjohnston** [comment]
No problem, I have 4090 24gb. I'll dive into this today and report back.

How many photos do you recommend I use for ideal use in Cascade to test this, and how long do you think will take to train? If it's faster than sdxl dreambooth that would be ideal for quick testing. Also is this for dreambooth or lora? I could test both.

**Comment by bmaltais** [comment]
I did my test with 8… I don’t think the disappointing result is due to that… I tried using other optimiser but I don’t have enough vram.

**Comment by gesen2egee** [comment]
![image](https://github.com/bmaltais/kohya_ss/assets/79357052/1abccf1d-4673-4536-a84e-9c06d0bea6b0)
Maybe because this

**Comment by bmaltais** [comment]
Using the latest updated code in sd-scripts produce better results... still not perfect... kohya is working on allowing to train stage_b... hoping this will fix the issue with the final look:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/0e48b71d-2549-421c-9b13-f1b780d730c3)

**Comment by brentjohnston** [comment]
Not too bad already! I did try this out but got stuck. the "Image folder" section is missing under folders for SC fine tuning tab (to load in my images) like in the dreambooth tab. I tried adding  "train_data_dir": "H:/trncas\\img", to the configuration .json but it didn't work. 

I have images named 1.jpg, 2.jpg, etc in there and caption files with 1.txt, 2.txt, 3.txt. I would usually do that for SDXL using the Dreambooth tab and it works well.  Here is the error when trying to train Cascade (I am also unsure of the setting I am using, and not if you have a .json to share):

22:36:51-402611 INFO     Start Finetuning...
22:36:51-428644 INFO     Saving training config to H:/trncas\model\cascade-test_20240220-223651.json...
22:36:51-430644 INFO     accelerate launch --num_cpu_threads_per_process=4 --mixed_precision bf16
                         "./stable_cascade_train_stage_c.py" --stage_c_checkpoint_path
                         "D:/stable-diffusion-webui-master/models/Stable-diffusion/stage_c.safetensors"
                         --effnet_checkpoint_path
                         "D:\stable-diffusion-webui-master\models\Stable-diffusion\effnet_encoder.safetensors"
                         --previewer_checkpoint_path
                         "D:\stable-diffusion-webui-master\models\Stable-diffusion\previewer.safetensors"
                         --dataset_config "" --max_grad_norm=0.0 --no_half_vae --train_text_encoder --bucket_no_upscale
                         --bucket_reso_steps=64 --cache_latents --cache_latents_to_disk --dataset_repeats="20"
                         --full_bf16 --gradient_checkpointing --learning_rate="1e-05" --learning_rate_te="1e-05"
                         --logging_dir="H:/trncas\log" --lr_scheduler="constant" --max_data_loader_n_workers="0"
                         --mixed_precision="bf16" --optimizer_args scale_parameter=False relative_step=False
                         warmup_init=False weight_decay=0.01 --optimizer_type="Adafactor" --output_dir="H:/trncas\model"
                         --output_name="cascade-test" --save_every_n_steps="100" --save_precision="bf16"
                         --train_batch_size="3" --train_text_encoder --sample_sampler=dpm_2
                         --sample_prompts="H:/trncas\model\sample\prompt.txt" --sample_every_n_steps="100"
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
2024-02-20 22:36:57 INFO     prepare tokenizers                                               stable_cascade_utils.py:76
                    INFO     Load dataset config from .                               stable_cascade_train_stage_c.py:62
Traceback (most recent call last):
  File "C:\Users\NewPC\Documents\kohyacascade\kohya_ss\stable_cascade_train_stage_c.py", line 546, in <module>
    train(args)
  File "C:\Users\NewPC\Documents\kohyacascade\kohya_ss\stable_cascade_train_stage_c.py", line 63, in train
    user_config = config_util.load_user_config(args.dataset_config)
  File "C:\Users\NewPC\Documents\kohyacascade\kohya_ss\library\config_util.py", line 628, in load_user_config
    raise ValueError(f"file not found / ファイルが見つかりません: {file}")
ValueError: file not found / ファイルが見つかりません: .
Traceback (most recent call last):
  File "C:\Users\NewPC\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\NewPC\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\NewPC\Documents\kohyacascade\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "c:\users\newpc\documents\kohyacascade\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "c:\users\newpc\documents\kohyacascade\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "c:\users\newpc\documents\kohyacascade\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['c:\\users\\newpc\\documents\\kohyacascade\\kohya_ss\\venv\\scripts\\python.exe', './stable_cascade_train_stage_c.py', '--stage_c_checkpoint_path', 'D:/stable-diffusion-webui-master/models/Stable-diffusion/stage_c.safetensors', '--effnet_checkpoint_path', 'D:\\stable-diffusion-webui-master\\models\\Stable-diffusion\\effnet_encoder.safetensors', '--previewer_checkpoint_path', 'D:\\stable-diffusion-webui-master\\models\\Stable-diffusion\\previewer.safetensors', '--dataset_config', '', '--max_grad_norm=0.0', '--no_half_vae', '--train_text_encoder', '--bucket_no_upscale', '--bucket_reso_steps=64', '--cache_latents', '--cache_latents_to_disk', '--dataset_repeats=20', '--full_bf16', '--gradient_checkpointing', '--learning_rate=1e-05', '--learning_rate_te=1e-05', '--logging_dir=H:/trncas\\log', '--lr_scheduler=constant', '--max_data_loader_n_workers=0', '--mixed_precision=bf16', '--optimizer_args', 'scale_parameter=False', 'relative_step=False', 'warmup_init=False', 'weight_decay=0.01', '--optimizer_type=Adafactor', '--output_dir=H:/trncas\\model', '--output_name=cascade-test', '--save_every_n_steps=100', '--save_precision=bf16', '--train_batch_size=3', '--train_text_encoder', '--sample_sampler=dpm_2', '--sample_prompts=H:/trncas\\model\\sample\\prompt.txt', '--sample_every_n_steps=100']' returned non-zero exit status 1.

**Comment by brentjohnston** [comment]
I feel like i'm so close, but I'm nit familiar with your code. Is there any basic info you can provide of where to put the training images and the format of sample .json.

Then I will test various training parameters for you.

**Comment by bmaltais** [comment]
I did provide everything in the stable_cascade branch. Look in the example folder in that branch. You will find the dataset, toml file for the dataset, etc. The new way of configuring the image for finetuning in the latest sd-scripts code is to use a .toml file... this is what the new SC Finetuning tab is configured to use...

**Comment by brentjohnston** [comment]
Thank you, yeah I completely missed the examples folder. 

My last question would be after replacing the examples folder with my additions/images where do I place all of files? I am assuming either leave them there or to the "dataset" folder.

I had read the branch cascade readme, but it doesn't really say, just this part:


```
About the dataset for fine tuning
If the latents cache files for SD/SDXL exist (extension *.npz), it will be read and an error will occur during training. Please move them to another location in advance.

After that, run finetune/prepare_buckets_latents.py with the --stable_cascade option to create latents cache files for Stable Cascade (suffix _sc_latents.npz is added).
```

Thanks again.

**Comment by bmaltais** [comment]
The dataset can be anywhere. Simply edit the toml file to point to it and specify the repeats, resolution, etc.

**Comment by brentjohnston** [comment]
Ok, so the SC fine tuning tab always looks at the examples folder for the toml file, got it. Trying this out again today!

**Comment by bmaltais** [comment]
> Ok, so the SC fine tuning tab always looks at the examples folder for the toml file, got it. I will edit the toml with images path.
> 
> Trying this out again today!

Actually it does not. Just make sure to put the path to your toml in the SC Finetuning and it should work. It does not need to be in the example.

**Comment by brentjohnston** [comment]
Ahh! Thanks. I see it under SC Finetuning tab > folders > Dataset toml path. I apologize, as everything is so different now compared to the old dreambooth training tab where you would just load the images path in.

Not sure if you have plans to map the .toma file to the gradio interface with some instructions in there, but I think it would help a lot for novices like myself.

**Comment by bmaltais** [comment]
No worries, I keep editing mine to :-)

as fast as a GUI to manage and create the toml dataset file it might be possible but I feel it might just be easier to just create one by hand. The complexity of building a gradio interface for that is beyond my current knowledge… but I am sure someone could do it.

if someone want to take a crack at creating a toml dataset gradio gui class I will gladly add it to the interface.

**Comment by brentjohnston** [comment]
I had some luck with higher quality outputs but also a few issues, here are some samples:

![1](https://github.com/bmaltais/kohya_ss/assets/23625562/be16a58c-c757-451d-b2d6-d5a9b5b01713)
![2](https://github.com/bmaltais/kohya_ss/assets/23625562/0d6da19f-70f7-4f64-9ae4-25ab81992d07)
![3](https://github.com/bmaltais/kohya_ss/assets/23625562/90223dfc-c6da-426d-bf7a-744d317afd3d)
![4](https://github.com/bmaltais/kohya_ss/assets/23625562/bf791852-bd06-4669-8032-366463157ac6)

The first one is a fake prompt haha.

Problems: Samples during training look good at 800 steps as you can see when testing "a zxc on the surface of the moon holding an orange" but samples stuck at 192x192.
![samples-during-training](https://github.com/bmaltais/kohya_ss/assets/23625562/da9a0700-3dbd-470d-b90a-0bd7236b4d8f)

I could not find a comfyui workflow that would work for me (not even the official one) this is the 800 step results (problem I'm having):
![Samples-problem-though-in-comfyui](https://github.com/bmaltais/kohya_ss/assets/23625562/b16a116c-6402-43aa-9a1a-239a71b1c591)

I have attached a file here with a readme and a kohya ss gui preset (needs 24gb vram, and trains text encoder which gave me better results, but please mess with the settings as I have no idea what half of them do. 

I updated the examples folder a bit with some more dataset images of Ted (13 total), if anyone wants to try this out. Here is the file: [](https://mega.nz/file/E0RVWBhR#-MQ1adWQjQaZ6qE9S1Wawg3ucnD-hzZW6-Yhcj4mI30)

Here's the included readme for as far as I got:
```
This probably requires a 4090 as it trains with the text encoder. Close down any apps using memory. End windows explorer task during training if you need to.

I got this sort of working. 

Overwrite the examples folder under C:\kohya_ss with this one. 

1. Make sure you are are the on stable-cascade brand by opening cmd prompt and type "git clone -b stable-cascade https://github.com/bmaltais/kohya_ss.git" (As of 02/22/2024)

2. Also Make sure kohya_ss gui is put under C:\kohya_ss (unless you want to edit a bunch of stuff) and that C:\stable-diffusion-webui-master\outputs and C:\stable-diffusion-webui-master\models\Stable-diffusion exists, put all of the models under models folder there

Models list:
stage_c.safetensors
stage_c_bf16.safetensors
stage_b.safetensors
stage_b_bf16.safetensors
effnet_encoder.safetensors
stage_a.safetensors
stage_a.safetensors

3. Open kohya-ss gui, go to the SC finetuning tab, click open and choose the preset-13-images-1800steps-test.json (included here in the Kohya Preset folder) Feel free to adjust any settings, a lot of it is still a mystery to me.

4. Click start training. Once it hits 1800 steps on the ted training test you can stop training. In comfyui workflow (included), test with 1800 step and 1500step _text_model.safetensors for clip node.

(you can mess around with combinations, I've had luck using 1600 step checkpoint with
500-700 step _text_model.safetensors also, it seems to greatly affect results using previous text_model checkpoints for clip node)

5. Place the output training files under comfy ComfyUI_windows_portable\ComfyUI\models\clip (for the _text_model.safetensors) and ComfyUI_windows_portable\ComfyUI\models\unet for the checkpoints.

6. Delete any .npz files that show up in the C:\kohya_ss\examples\stable_cascade\test_dataset that show up after training. Before you train again.

Problem: I'm not getting the same image outputs as the training samples shown at step 800 or any of the checkpoints below 1000, not sure why. I'm probably doing something wrong, maybe with buckets.  I noticed the training images are only 192x192 and don't know how to change it. 

If you figure it out let me know on the kohya ss gui github here https://github.com/bmaltais/kohya_ss/issues/1982
```

**Comment by bmaltais** [comment]
Interesting results...

Unet and TE:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/def19395-2aaf-48ea-877b-f3344e31c261)

TE only:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/d5e88ac7-428c-4ec1-9571-e332ecb6b819)


UNet only:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/8c5c80c0-a2af-48ba-b704-e770ff7f6474)


Conclusion... TE has the most importance as far as likeness goes... but without the trained UNet the result is quite fuzzy...

**Comment by brentjohnston** [comment]
First one looks great! Could it be that the .json I included in the link doesn't train unet and text encoder together? I'm not sure how to enable both.

Did you have any trouble using the same checkpoint step with the same text_model checkpoint step?

I had to use a text_model (on clip node) that was about 200-300 less steps or it didn't listen to prompts well, for instance the woman in bikini would turn into a second Ted, or just randomly disappear.

**Comment by bmaltais** [comment]
Look like TE is overfitting while UNet is way underfitted. Maybe increasing UNet LR to 0.0001 might help balance learning between both and prevent overfit.

**Comment by brentjohnston** [comment]
I spent the last couple of days doing testing. I tried quite a few things, like no captions, changing classes, general tokens, training myself with 60 photos like I would do on SDXL. (SDXL would produce some very cool random stuff and different poses even when training over juggernaut v9, w/ ohwx man, captions, man class token, 20 repeats)

In SDXL dreambooth with batch size 3, 20 repeats, 55-60 images from various angles/environments, poses, captions, TE and Unet learning rate 0.00001, it seems it would hit a very accurate sweet spot at like 2000-2300 steps range even if using only general tokens and class the same like "40 year old man", with no captions, or sometimes I would use a token the "ohwx man" and captions made results a tad better. I never really had to use regularization images as I didn't care if everyone in the model looked like me. (if that's what it prevents from what I understood) I tried it a few times but it didn't seem worth the extra training time.

When I train ~60 photos in Casdcade at 0.00001 LR on "zxc man" and class token "man" the closest I could get to somewhat acceptable was was cascade-test-step00003400_text_model.safetensors for clip loader, and cascade-test-step00003100.safetensors for unet. The model was flexible and prompted in different environments and showed a sort of likeness of me, But it was not very good. I tried UNet LR to 0.0001 but it didn't seem to work and made results worse somehow, but maybe have to try it again with higher steps.

Overall this seems very difficult to figure out the right combination of unet model and text encoder model to use in comfyui, or what number of steps for 60 photos is actually the best for Cascade.

it takes a long time to fully finetune and I'm struggling to figure it out. It didn't look like me overall and looked pretty undertrained at even 3400 steps at batch size 3 with 60 photos. I am thinking this is going to need a lot more steps, which doesn't seem in line with it "training faster than SDXL". I could increase learning rate on everything here, but in SDXL that always seemed to make the results works.

I appears like this guy is getting pretty decent results of his cat at 8000 steps (but overfitting) and is using a very large 7 batch size https://www.reddit.com/r/StableDiffusion/comments/1azmhte/my_cat_in_different_stylesstablecascade_stagec/ so I'm just a little lost. A comment there seem in line with my findings for SDXL.

I ran out of disk space though because I fell asleep and it was saving too often at 300 steps. I seemed to have pretty noticeable changes every 300 steps I originally thought, so I wasn't able to test all the way to 7000-8000 steps test yet to compare. But at some point I will just have it save every 1000 steps and report back the results between 5000-8000 or so at batch size 3, 20 and 40 repeats.

**Comment by vgaggia** [comment]
I'm actually busy trying to training stable cascade with around a dataset of 180k images, although i am using onetrainer cause it seems to be less memory intensive for some reason.

I have also noticed the fact that the training gets better and worse constantly as it trains, it's gonna be a while for my training to finish on a single gpu so no clue when i can actually show some results

**Comment by brentjohnston** [comment]
Wow that's a good amount!

Yeah I noticed this in cascade training tests, and in SDXL training too. I can have a great one in sdxl at 2100 steps that listens to prompting well or has good headshots, looks fairly accurate for example.

Then 2200 steps could have nightmare limbs and inaccuracies and be not be as good, then at 2300 it  has something better than even 2100 had, like great poses and body shots. Sometimes after 2500 it's bad until at like 3600 steps i'll get basically various recreations of dataset images and model is mostly useless and overtrained, but it's so accurate I'll merge it at a very small 0.05 weight to the balanced one I like and it seems to improve the face and body. I also do this with lower 1700 step or so point sometimes for a bit more prompt listening (This is with batch size 3, 20 repeats, 0.00001 LR, 60 images) 

I still don't know how to do the math exactly if I ever did as many images as you are doing at 3 batch size (max I can do). I assume 60 images over 2100steps equals 180,000 images over x?) Not sure if it works linearly like that or not. So 6.9 million steps range if using settings above and my 4090. About 6-9 months for me to train that at batch size 3 if my math is right lol

**Comment by brentjohnston** [comment]
Yes trying that today actually, I didn't do it for sdxl because quality seemed to get worse but who knows, might work with Cascade.

**Comment by betterftr** [comment]
for me it generates samples 192x192 during training, trying to figure out why, since I set w and h 1024

**Comment by bmaltais** [comment]
The small samples is related to how the as-script code is actually being used. Nothing I can do. This is something only Koby’s can address… but given how heavy creating samples is I suspect this was by design.

**Comment by betterftr** [comment]
well as a temporary solution one can increase the --w and --h to 4096 for 4x size :D

**Comment by brentjohnston** [comment]
Someone posted a workflow for converting the models here to work for official comfyui workflow, simple enough. I've been out of town but will try it when I get back.

https://github.com/comfyanonymous/ComfyUI/issues/2893#issuecomment-1969508040

**Comment by jordoh** [comment]
> Someone posted a workflow for converting the unet models here to work with official comfyui workflow (to get rid of that error) Simple enough. I've been out of town but will try it when I get back.
> 
> [comfyanonymous/ComfyUI#2893 (comment)](https://github.com/comfyanonymous/ComfyUI/issues/2893#issuecomment-1969508040)

Note that only loads the unet, not the clip, so you aren't able to utilize the (more effective) text encoder training.

**Comment by brentjohnston** [comment]
Ahh, thanks for the info. Can we convert the clip model also and and just drag it into positive and negative prompt then? (for official comfyui workflow)

**Comment by jordoh** [comment]
> Thanks for the info. Can we convert the clip model also and and just drag it into positive and negative prompt then? (with load clip node for official comfyui workflow)

Maybe? I've been trying this with a model trained by the original Stable Cascade repo code and get errors as the model it produces isn't loadable as a clip model (I don't have a separate text encoder model from that process). It might work for kohya-ss trained models though - I'd be very interested to know if it does.

> and wondering if there's any point in doing this over just using unet, was hoping it might give better results.

Yes, there's definitely a point, see [this comment upthread](https://github.com/bmaltais/kohya_ss/issues/1982#issuecomment-1961584660) for comparisons. For person-trained models, I'm unable to achieve any likeness with just the UNET (vs. generating with Stable Cascade repo that uses the trained CLIP).

**Comment by brentjohnston** [comment]
Yup saw that before. Sorry for confusion, I meant "any point" to comfyui workflow vs unet workflow if we got unet and clip working in both.

**Comment by jordoh** [comment]
> Yup saw that before. Sorry for confusion, I meant "any point" to comfyui workflow vs unet workflow if we got unet and clip working in both workflows. I wonder if there would be a difference.

Oh, thanks for clarifying, I think I understand what you meant now: is there any difference between saving off a checkpoint with the trained unet then using that saved checkpoint vs. using the trained unet? Seems unlikely that would affect the output, as it's the same model, clip, and VAE either way, but might save some memory or load time to use the saved off checkpoint.

**Comment by brentjohnston** [comment]
Something I just discovered that I never knew. You can change prompt the prompt.txt in the samples folder as it's training to test things. .

This has been pretty hrlpful, and never knew that. I am finding it useful if you are saving a lot of checkpoints every 50 steps around what you think is getting close to a "general sweet spot", see how things are working. Need a lot of diskspace for that though.

I'll usually delete the first 1000 steps of checkpoints whem using 60 photos, 3 batch size, 20 repeat, 0.00001 LR

**Comment by segalinc** [comment]
will this feature work on multiple gpus?

**Comment by sapkun** [comment]
When the controlnet training script will be release for stable cascade?

**Comment by paboum** [comment]
> Look like TE is overfitting while UNet is way underfitted. Maybe increasing UNet LR to 0.0001 might help balance learning between both and prevent overfit.

Please try adaptive optimizers already, e.g Prodigy. I'm a newbie here, never even used those LR parameters. Also, I hope this new feature will work fine with those, so at least one test is in order.

**Comment by brentjohnston** [comment]
Just want to give an update, I tried all the stuff I mentioned earlier, and tried to train a 60's celebrity with 74 photos on Cascade, tried a ton of settings and text encoder mode/unet model combinations, LR settings, steps. 

I can't get sdxl dreambooth level results with a trained human or a flexible model. I tried a ton of stuff over like 8 hours. I think now that SD3 is coming out I may just wait it out, and focus on sdxl again for now.

I hope SD3 not as difficult to train as this is, but we'll see. I'm could still be doing something wrong here. I can't produce the results I had above with Ted.

**Comment by segalinc** [comment]
Have you checked what one trainer is doind that seems like people are
getting really nice results using it?

**Comment by brentjohnston** [comment]
I was actually thinking of trying that out but heard it may not train the text encoder like this does, and as we can see from bmaltais results, it seems very important in combination with the unet training. I will give it a go though just to see how it compares.

**Comment by brentjohnston** [comment]
I just read the kohya-ss scripts Cascade branch and official branch (probably should have done that from that start but got busy)

There's some stuff regarding learning rate I didn't know about in readme:

Official learning rate for Cascade default is 1e-4 or (0.0001) and official settings use bf16 for training. I think I was accidentally using fp16 which says is unstable. I will try again.

This I found also which makes sense why that is done this way in this repo.

`The first time, specify --text_model_checkpoint_path and --save_text_model to save the Text Encoder weights. From the next time, specify --text_model_checkpoint_path to load the saved weights.`

I was sort of confused by the note added to the official cascade repo readme about lora and controlnet only for stage C, does this mean full finetuning was not recommended and kohya just sort of figured it out?

```
#### Note:
A quick clarification, Stable Cascade uses Stage A & B to compress images and Stage C is used for the text-conditional
learning. Therefore, it makes sense to train a LoRA or ControlNet **only** for Stage C. You also don't train a LoRA or 
ControlNet for the Stable Diffusion VAE right?
```

Also I am definitely going to make sure I use large model next time for stage C because of this note:

```
If your GPU allows for it, you should definitely go for the **large** Stage C, which has 3.6 billion parameters.
It is a lot better and was finetuned a lot more. Also, the ControlNet and Lora examples are only for the large Stage C at the moment.
For Stage B the difference is not so big. The **large** Stage B is better at reconstructing small details,
but if your GPU is not so powerful, just go for the smaller one.
```

**Comment by mhaines94108** [comment]
> I tested the results of th model in COmfyUI and they are not great... sort of washed out... Most certainly bad training parameters... Will take a while to figureout proper SC finetuning parameters...
> 
> ![image](https://private-user-images.githubusercontent.com/7474674/305756103-fb5aa5c5-906e-492b-aaa7-9531b2487763.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MzU0NjMsIm5iZiI6MTcxMzYzNTE2MywicGF0aCI6Ii83NDc0Njc0LzMwNTc1NjEwMy1mYjVhYTVjNS05MDZlLTQ5MmItYWFhNy05NTMxYjI0ODc3NjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjBUMTc0NjAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTVlODcxYjQ2ZTQ2ZDNmODI3ZTBlZTQxMGQwOWY2MDNjODc3ZTc4Y2IzMTc2NzJmZDhmMjYzN2IzZjJkMWE1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4AFtvtzl8W7tt9kRuQL4CILzZ7EC-Q_dVlxxA9f3iS0)

I have spent several weeks trying to fine-tune Stable Cascade on a dataset of ~50K photos, and my results have a very similar finger-painted look.  I've been using the sample code straight from Stable Diffusion.  I guess I'll try Kohya's scripts.

**Comment by 3blackbar** [comment]
test.toml in examples is empty so cant test the bear on exact same settings
