### ISSUE TITLE
Document platform expectations that must be satisfied to run under Firejail

### ISSUE THREAD

**Issue by ssokolow** [bmaltais/kohya_ss#1984]
As a security measure, I run everything I can in sandboxes and, for these sorts of self-downloading things, that means Firejail. (For other things, I install them off Flathub and use Flatseal to tighten the default permissions.)

For easy-diffusion, this `run.sh` does the trick...

```sh
#!/bin/sh
cd -- "$(dirname -- "$(readlink -f -- "$0")")"
exec firejail --noprofile "--whitelist=$PWD" \
    --blacklist=/srv --blacklist=/mnt --private-tmp --caps.drop=all \
    --nodbus --nonewprivs --noroot --nosound --private-dev \
    bash ./start.sh
```

...and for automatic1111, this one does (A custom `run.sh` is a nice place to add things like `export python_cmd=python3.10` and `--medvram` that easy-diffusion either didn't need or offered GUI config for)...
```sh
#!/bin/sh
cd -- "$(dirname -- "$(readlink -f -- "$0")")"
export python_cmd=python3.10
exec firejail --noprofile "--whitelist=$PWD" \
    --blacklist=/srv --blacklist=/mnt --private-tmp --caps.drop=all \
    --nodbus --nonewprivs --noroot --nosound --private-dev \
    bash ./webui.sh --medvram "$@"
```

...but kohya_ss is proving a bit more temperamental.

First time, after waiting about 20 minutes for all of the models to download, it gave me this error:

```
Traceback (most recent call last):
  File "/home/ssokolow/opt/kohya_ss/./train_network.py", line 1033, in <module>
    trainer.train(args)
  File "/home/ssokolow/opt/kohya_ss/./train_network.py", line 345, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "/home/ssokolow/opt/kohya_ss/library/train_util.py", line 3510, in get_optimizer
    import bitsandbytes as bnb
  File "/home/ssokolow/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/ssokolow/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/ssokolow/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/ssokolow/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/ssokolow/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/ssokolow/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "/home/ssokolow/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 120, in run_cuda_setup
    binary_name, cudart_path, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/ssokolow/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 337, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
  File "/home/ssokolow/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 295, in determine_cuda_runtime_lib_path
    cuda_runtime_libs.update(find_cuda_lib_in(value))
  File "/home/ssokolow/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 232, in find_cuda_lib_in
    resolve_paths_list(paths_list_candidate)
  File "/home/ssokolow/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 227, in resolve_paths_list
    return remove_non_existent_dirs(extract_candidate_paths(paths_list_candidate))
  File "/home/ssokolow/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 201, in remove_non_existent_dirs
    raise exc
  File "/home/ssokolow/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 197, in remove_non_existent_dirs
    if path.exists():
  File "/usr/lib/python3.10/pathlib.py", line 1290, in exists
    self.stat()
  File "/usr/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/run/user/1000/gnupg/S.gpg-agent'
```

A simple addition of `unset GPG_AGENT_INFO` to my launcher script fixed that (why is it trying to communicate with my GPG agent in the first place?)... but my second attempt wanted to spend another 20 minutes re-downloading multiple gigabytes of models because, unlike easy-diffusion and automatic1111, you apparently download your models into somewhere not covered by the `--whitelist=$PWD` for the kohya_ss install directory, where they'll be persisted between runs.

Please document all of these assumptions so it's as easy to run kohya_ss under Firejail as it is with easy-diffusion and automatic1111.

(In fact, please also document where those models are getting downloaded to. With automatic1111, I saved a ton of time and space by just hardlinking the models easy-diffusion had downloaded before starting it up. I'm hoping it's something simple like "it crashed after downloading to `/tmp` but before moving them to `$PWD`" where the fix is "just download them directly to their final target location and use a temporary filename if needed" like web browsers do.)

**Comment by ssokolow** [comment]
I ripgrep'd through the source code and found it. Now I'm trying to decide whether I should open another bug that says "Games don't install their mods in `~/.cache`, so why are you installing *your* multi-gigabyte content packs into the system's 'these are cheap to re-download/re-generate, so blow them away if you need space' directory?"

In the mean time, the workaround in `run.sh` for for that problem looks like this:

```sh
#!/bin/sh
cd -- "$(dirname -- "$(readlink -f -- "$0")")"
unset GPG_AGENT_INFO

export XDG_CACHE_HOME="$PWD/fake_home/.cache"
mkdir -p "$XDG_CACHE_HOME"

exec firejail --noprofile "--whitelist=$PWD" \
    --blacklist=/srv --blacklist=/mnt --private-tmp --caps.drop=all \
    --nodbus --nonewprivs --noroot --nosound --private-dev \
    bash ./gui.sh "$@"
```

However, I then get a `libcusparse.so.11: cannot open shared object file: No such file or directory` error, which is a library that *is* present in easy-diffusion's conda venv.

Running `unset `GPG_AGENT_INFO` and then the advised `python -m bitsandbytes` displays lines like `The following directories listed in your path were found to be non-existent: {PosixPath('America/Toronto')}` which suggests the `GPG_AGENT_INFO` crash was due to it interpreting *every* environment variable as `PATH` and crashing when it ran into one whose status was "access denied" rather than either "present and accessible" or "missing".
