### ISSUE TITLE
Tensorboard doesn't start in headless docker container

### ISSUE THREAD

**Issue by PumpkinHat** [bmaltais/kohya_ss#1993]
I'm running kohya-ss headless in a docker container on my home server. Clicking the start tensorboard button triggers an exception as shown below.

```
kohya-ss-gui  | Traceback (most recent call last):
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 534, in predict
kohya-ss-gui  |     output = await route_utils.call_process_api(
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 226, in call_process_api
kohya-ss-gui  |     output = await app.get_blocks().process_api(
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1550, in process_api
kohya-ss-gui  |     result = await self.call_function(
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1185, in call_function
kohya-ss-gui  |     prediction = await anyio.to_thread.run_sync(
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 56, in run_sync
kohya-ss-gui  |     return await get_async_backend().run_sync_in_worker_thread(
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
kohya-ss-gui  |     return await future
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 851, in run
kohya-ss-gui  |     result = context.run(func, *args)
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 661, in wrapper
kohya-ss-gui  |     response = f(*args, **kwargs)
kohya-ss-gui  |   File "/app/library/tensorboard_gui.py", line 26, in start_tensorboard
kohya-ss-gui  |     if not os.listdir(logging_dir):
kohya-ss-gui  | FileNotFoundError: [Errno 2] No such file or directory: ''
```
Hard coding a logging directory triggers another exception:

```
kohya-ss-gui  | Traceback (most recent call last):
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 534, in predict
kohya-ss-gui  |     output = await route_utils.call_process_api(
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 226, in call_process_api
kohya-ss-gui  |     output = await app.get_blocks().process_api(
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1550, in process_api
kohya-ss-gui  |     result = await self.call_function(
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1185, in call_function
kohya-ss-gui  |     prediction = await anyio.to_thread.run_sync(
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 56, in run_sync
kohya-ss-gui  |     return await get_async_backend().run_sync_in_worker_thread(
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
kohya-ss-gui  |     return await future
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 851, in run
kohya-ss-gui  |     result = context.run(func, *args)
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 661, in wrapper
kohya-ss-gui  |     response = f(*args, **kwargs)
kohya-ss-gui  |   File "/app/library/tensorboard_gui.py", line 31, in start_tensorboard
kohya-ss-gui  |     msgbox(msg='Error: log folder is empty')
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/easygui/boxes/derived_boxes.py", line 230, in msgbox
kohya-ss-gui  |     return buttonbox(msg=msg,
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/easygui/boxes/button_box.py", line 95, in buttonbox
kohya-ss-gui  |     bb = ButtonBox(
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/easygui/boxes/button_box.py", line 147, in __init__
kohya-ss-gui  |     self.ui = GUItk(msg, title, choices, images, default_choice, cancel_choice, self.callback_ui)
kohya-ss-gui  |   File "/usr/local/lib/python3.10/dist-packages/easygui/boxes/button_box.py", line 263, in __init__
kohya-ss-gui  |     self.boxRoot = tk.Tk()
kohya-ss-gui  |   File "/usr/lib/python3.10/tkinter/__init__.py", line 2302, in __init__
kohya-ss-gui  |     self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
kohya-ss-gui  | _tkinter.TclError: couldn't connect to display ""
```

#1962 may be related but I am unsure.

**Comment by PumpkinHat** [comment]
I figured out what the problem was. It appears that you have to have a string pointing to a valid directory in the Logging folder box under the folders tab/. Even if you are currently training, if that string has been cleared it will give the error above.
