### ISSUE TITLE
Errors training Lora

### ISSUE THREAD

**Issue by OBI-Ron** [bmaltais/kohya_ss#2004]
Hello all - running on Ubuntu 22.04LTS.  Getting the following errors running training:
Using SD1.5 & safetensors

Traceback (most recent call last):
  File "/Programs/Kohya_GUI/kohya_ss/./train_network.py", line 1058, in <module>
    trainer.train(args)
  File "/Programs/Kohya_GUI/kohya_ss/./train_network.py", line 273, in train
    train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
  File "/Programs/Kohya_GUI/kohya_ss/library/train_util.py", line 1949, in cache_latents
    dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)
  File "/Programs/Kohya_GUI/kohya_ss/library/train_util.py", line 964, in cache_latents
    cache_batch_latents(vae, cache_to_disk, batch, subset.flip_aug, subset.random_crop)
  File "/Programs/Kohya_GUI/kohya_ss/library/train_util.py", line 2297, in cache_batch_latents
    raise RuntimeError(f"NaN detected in latents: {info.absolute_path}")
RuntimeError: NaN detected in latents: /Programs/Kohya_GUI/AU_Car Lora/image/150_AU_Car/AU_Car_0001.png
Traceback (most recent call last):
  File "/Programs/Kohya_GUI/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/Programs/Kohya_GUI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/Programs/Kohya_GUI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/Programs/Kohya_GUI/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/Programs/Kohya_GUI/kohya_ss/venv/bin/python', './train_network.py', '--bucket_no_upscale', '--bucket_reso_steps=64', '--cache_latents', '--caption_extension=.txt', '--clip_skip=2', '--gradient_checkpointing', '--learning_rate=0.0001', '--logging_dir=/Programs/Kohya_GUI/AU_Car Lora/log', '--lr_scheduler=constant', '--lr_scheduler_num_cycles=1', '--max_data_loader_n_workers=1', '--max_grad_norm=1', '--resolution=512,512', '--max_train_steps=1500', '--mem_eff_attn', '--mixed_precision=fp16', '--network_alpha=128', '--network_dim=128', '--network_module=networks.lora', '--optimizer_type=AdamW8bit', '--output_dir=/Programs/Kohya_GUI/AU_Car Lora/model', '--output_name=Addams', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--save_every_n_epochs=1', '--save_model_as=safetensors', '--save_precision=fp16', '--seed=1234', '--text_encoder_lr=5e-05', '--train_batch_size=1', '--train_data_dir=/Programs/Kohya_GUI/AU_Car Lora/image', '--unet_lr=0.0001', '--xformers']' returned non-zero exit status 1.

**Comment by Lecho303** [comment]
same issue like u,but i was chose customer(SD-v-2.1-ema-768),same error code,then i chose V 2\V 2.1,could not fix this issue
