### ISSUE TITLE
MAC M2 issue on the training process of the Dreambooth

### ISSUE THREAD

**Issue by ImpFaidon** [bmaltais/kohya_ss#2013]
<img width="1716" alt="Screenshot 2024-02-27 at 5 07 15 PM" src="https://github.com/bmaltais/kohya_ss/assets/160134727/d7b921dc-4328-456e-a478-48cf78d06fc5">
<img width="1709" alt="Screenshot 2024-02-27 at 5 07 45 PM" src="https://github.com/bmaltais/kohya_ss/assets/160134727/17acfe5d-94fa-42a1-ad44-065d9c7cc778">
I even set use_cpu in the default config file to true, I tried several time but I run again and again to the same error:

Traceback (most recent call last):
  File "/Users/imperius_f/kohya/kohya_ss/./train_network.py", line 1058, in <module>
    trainer.train(args)
  File "/Users/imperius_f/kohya/kohya_ss/./train_network.py", line 243, in train
    vae.set_use_memory_efficient_attention_xformers(args.xformers)
  File "/Users/imperius_f/kohya/kohya_ss/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 262, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/imperius_f/kohya/kohya_ss/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 258, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/imperius_f/kohya/kohya_ss/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 258, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/imperius_f/kohya/kohya_ss/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 258, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/imperius_f/kohya/kohya_ss/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 255, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/imperius_f/kohya/kohya_ss/venv/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 260, in set_use_memory_efficient_attention_xformers
    raise ValueError(
ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU 
Traceback (most recent call last):
  File "/Users/imperius_f/kohya/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/Users/imperius_f/kohya/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/Users/imperius_f/kohya/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/Users/imperius_f/kohya/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/Users/imperius_f/kohya/kohya_ss/venv/bin/python', './train_network.py', '--bucket_no_upscale', '--bucket_reso_steps=64', '--cache_latents', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--learning_rate=0.0001', '--logging_dir=/Users/imperius_f/Training_Model1/log', '--lr_scheduler=constant', '--lr_scheduler_num_cycles=10', '--max_data_loader_n_workers=0', '--max_grad_norm=1', '--resolution=512,512', '--max_train_steps=4120', '--mixed_precision=no', '--network_alpha=1', '--network_dim=8', '--network_module=networks.lora', '--optimizer_type=AdamW', '--output_dir=/Users/imperius_f/Training_Model1/model', '--output_name=influencer_vol2', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-2', '--save_every_n_epochs=2', '--save_model_as=safetensors', '--save_precision=fp16', '--text_encoder_lr=0.0001', '--train_batch_size=1', '--train_data_dir=/Users/imperius_f/Training_Model1/img', '--unet_lr=0.0001', '--v_parameterization', '--v2', '--xformers']' returned non-zero exit status 1.

Can anyone explain? I don't know what I suppose to do, I searched every documentation I found in the internet for the last 3 days!
<img width="1716" alt="Screenshot 2024-02-27 at 5 07 15 PM" src="https://github.com/bmaltais/kohya_ss/assets/160134727/9a901273-6948-40f9-900d-8830ebe7f088">
<img width="1709" alt="Screenshot 2024-02-27 at 5 07 45 PM" src="https://github.com/bmaltais/kohya_ss/assets/160134727/a35bee8f-ba53-4952-8a7f-3160963272ab">
<img width="1705" alt="Screenshot 2024-02-27 at 5 08 19 PM" src="https://github.com/bmaltais/kohya_ss/assets/160134727/47782cd3-34c6-4b14-a70d-497da970b564">

**Comment by elttaes** [comment]
you should not set '--xformers' as parameter.
In crossattention setting it to 'sdpa'
