### ISSUE TITLE
WD14 Error

### ISSUE THREAD

**Issue by Aconot** [bmaltais/kohya_ss#2015]
When i try to caption images with WD14 I have problem like above. Can you help me to fix it?

To create a public link, set `share=True` in `launch()`.
18:28:43-487341 INFO     Captioning files in C:/Users/../Desktop/folder...
18:28:43-488346 INFO     accelerate launch "./finetune/tag_images_by_wd14_tagger.py" --batch_size=16
                         --general_threshold=0.35 --character_threshold=0.35 --caption_extension=".txt"
                         --caption_separator="," --model="SmilingWolf/wd-v1-4-convnextv2-tagger-v2"
                         --max_data_loader_n_workers="2" --debug --remove_underscore --frequency_tags
                         "C:/Users/.../Desktop/deneme"
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
2024-02-27 18:28:51 INFO     using existing wd14 tagger model                           tag_images_by_wd14_tagger.py:102
Traceback (most recent call last):
  File "C:\...\kohya_ss\finetune\tag_images_by_wd14_tagger.py", line 386, in <module>
    main(args)
  File "C:\...\kohya_ss\finetune\tag_images_by_wd14_tagger.py", line 144, in main
    model = load_model(f"{args.model_dir}")
  File "C:\...\kohya_ss\venv\lib\site-packages\keras\src\saving\saving_api.py", line 262, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\...\kohya_ss\venv\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\...\kohya_ss\venv\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 703, in is_directory_v2
    return _pywrap_file_io.IsDirectory(compat.path_to_bytes(path))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 16: invalid start byte
Traceback (most recent call last):
  File "C:\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\...\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\...\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\...\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\...\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\...\\kohya_ss\\venv\\Scripts\\python.exe', './finetune/tag_images_by_wd14_tagger.py', '--batch_size=16', '--general_threshold=0.35', '--character_threshold=0.35', '--caption_extension=.txt', '--caption_separator=,', '--model=SmilingWolf/wd-v1-4-convnextv2-tagger-v2', '--max_data_loader_n_workers=2', '--debug', '--remove_underscore', '--frequency_tags', 'C:/Users/.../Desktop/...']' returned non-zero exit status 1.
18:28:52-357872 INFO     ...captioning done

**Comment by bmaltais** [comment]
Please raise this issue directly on kohya_ss repo as this is something that need to be addressed in his code. I only wrap his code in a GUI and can't fix this in my repo.
