### ISSUE TITLE
Getting an error after starting SDXL Lora training.

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [bmaltais/kohya_ss#2053]
I updated to the latest version. Running on RTX 3090.
I'm using settings that worked before with a dataset that I used for training before.
Error:
``` log
2024-03-10 18:07:41|[LyCORIS]-INFO: Using rank adaptation algo: locon
2024-03-10 18:07:41|[LyCORIS]-INFO: Apply different lora dim for conv layer
2024-03-10 18:07:41|[LyCORIS]-INFO: Conv Dim: 8, Linear Dim: 128
2024-03-10 18:07:41|[LyCORIS]-INFO: Apply different alpha value for conv layer
2024-03-10 18:07:41|[LyCORIS]-INFO: Conv alpha: 1.0, Linear alpha: 64.0
2024-03-10 18:07:41|[LyCORIS]-INFO: Use Dropout value: 0.1
2024-03-10 18:07:41|[LyCORIS]-INFO: Create LyCORIS Module
2024-03-10 18:07:42|[LyCORIS]-INFO: Create LyCORIS Module
2024-03-10 18:07:43|[LyCORIS]-INFO: create LyCORIS for Text Encoder: 264 modules.
2024-03-10 18:07:43|[LyCORIS]-INFO: Create LyCORIS Module
2024-03-10 18:07:47|[LyCORIS]-INFO: create LyCORIS for U-Net: 788 modules.
2024-03-10 18:07:47|[LyCORIS]-INFO: module type table: {'LoConModule': 1052}
2024-03-10 18:07:47|[LyCORIS]-INFO: enable LyCORIS for text encoder
2024-03-10 18:07:47|[LyCORIS]-INFO: enable LyCORIS for U-Net
prepare optimizer, data loader etc.
False

===================================BUG REPORT===================================
/workspace/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/workspace/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib64'), PosixPath('/usr/local/nvidia/lib64')}
/workspace/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /workspace/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('module'), PosixPath('//matplotlib_inline.backend_inline')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /workspace/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "/workspace/kohya_ss/sd-scripts/sdxl_train_network.py", line 184, in <module>
    trainer.train(args)
  File "/workspace/kohya_ss/sd-scripts/train_network.py", line 349, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "/workspace/kohya_ss/sd-scripts/library/train_util.py", line 3616, in get_optimizer
    import bitsandbytes as bnb
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/workspace/kohya_ss/venv/bin/python', '/workspace/kohya_ss/sd-scripts/sdxl_train_network.py', '--bucket_no_upscale', '--bucket_reso_steps=128', '--caption_dropout_rate=0.05', '--caption_extension=.txt', '--color_aug', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=1536', '--gradient_checkpointing', '--keep_tokens=1', '--learning_rate=8e-05', '--logging_dir=/workspace/logs/', '--lr_scheduler=constant', '--max_data_loader_n_workers=0', '--max_grad_norm=1', '--resolution=1024,1024', '--max_token_length=225', '--max_train_epochs=200', '--min_snr_gamma=5', '--mixed_precision=fp16', '--network_alpha=64', '--network_args', 'preset=full', 'conv_dim=8', 'conv_alpha=1', 'rank_dropout=0.1', 'module_dropout=0.1', 'use_tucker=False', 'use_scalar=False', 'rank_dropout_scale=False', 'algo=locon', 'train_norm=False', '--network_dim=128', '--network_dropout=0.1', '--network_module=lycoris.kohya', '--noise_offset=0.125', '--optimizer_type=AdamW8bit', '--output_dir=/workspace/output/', '--output_name=tr_01', '--pretrained_model_name_or_path=/workspace/model/model.safetensors', '--save_every_n_epochs=5', '--save_model_as=safetensors', '--save_precision=fp16', '--scale_weight_norms=1', '--seed=2552101', '--shuffle_caption', '--text_encoder_lr=5e-05', '--train_batch_size=8', '--train_data_dir=/workspace/input/dataset/', '--unet_lr=8e-05', '--log_with', 'wandb', '--wandb_api_key=\', '--xformers', '--sample_sampler=k_dpm_2', '--sample_prompts=/workspace/output/sample/prompt.txt', '--sample_every_n_epochs=5']' returned non-zero exit status 1.
```

Start of the log:
``` log
18:03:39-352434 INFO     Version: v23.0.1                                       
                                                                                
18:03:39-367743 INFO     nVidia toolkit detected                                
18:03:41-047086 INFO     Torch 2.1.2+cu118                                      
18:03:41-090416 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700             
18:03:41-108229 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24260 
                         Arch (8, 6) Cores 82                                   
18:03:41-208111 INFO     Submodule initialized and updated.                     
18:03:41-211217 INFO     Verifying modules installation status from             
                         /workspace/kohya_ss/requirements_linux.txt...          
18:03:41-218870 INFO     Installing package: torch==2.1.2+cu118                 
                         torchvision==0.16.2+cu118 xformers==0.0.23.post1+cu118 
                         --extra-index-url                                      
                         https://download.pytorch.org/whl/cu118                 
18:03:47-843377 INFO     Verifying modules installation status from             
                         requirements.txt...                                    
18:03:52-779947 INFO     headless: True                                         
18:03:52-785439 INFO     Load CSS...
```

**Comment by ashleykleynhans** [comment]
Read the release notes, v23.x.x are not official releases and can contain bugs.
I recommend using the v22.6.2 stable release instead.
bitsandbytes seems to be your issue here.
