### ISSUE TITLE
mean ar error (without repeats): 0.0 preparing accelerator

### ISSUE THREAD

**Issue by eriktavares** [bmaltais/kohya_ss#2080]
loading image sizes.
100% 297/297 [00:01<00:00, 193.45it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 512), count: 1120
mean ar error (without repeats): 0.0
preparing accelerator
Traceback (most recent call last):
  File "/content/kohya_ss/./train_network.py", line 974, in <module>
    trainer.train(args)
  File "/content/kohya_ss/./train_network.py", line 205, in train
    accelerator = train_util.prepare_accelerator(args)
  File "/content/kohya_ss/library/train_util.py", line 3269, in prepare_accelerator
    accelerator = Accelerator(
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 474, in __init__
    raise ValueError("bf16 mixed precision requires PyTorch >= 1.10 and a supported device.")
ValueError: bf16 mixed precision requires PyTorch >= 1.10 and a supported device.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1057, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 673, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', './train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=

**Comment by bmaltais** [comment]
Are you using the latest release? The logs do not appear to be the ones from v23.0.x
