### ISSUE TITLE
Setup fails on fresh install

### ISSUE THREAD

**Issue by fjuhec** [bmaltais/kohya_ss#2087]
Running setup.sh on a freshly cloned repo fails.

```
@:/media/files/ai$ git clone https://github.com/bmaltais/kohya_ss.git
@:/media/files/ai$ cd kohya_ss/
@:/media/files/ai/kohya_ss$ ./setup.sh
Skipping git operations.
Ubuntu detected.
Python TK found...
Switching to virtual Python environment.
Traceback (most recent call last):
  File "/media/files/ai/kohya_ss/setup/setup_linux.py", line 28, in <module>
    python_ver = setup_common.check_python_version()
  File "/media/files/ai/kohya_ss/setup/setup_common.py", line 23, in check_python_version
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
Exiting Python virtual environment.
Setup finished! Run ./gui.sh to start.
Please note if you'd like to expose your public server you need to run ./gui.sh --share
```

Checking setup_linux.py

```
if __name__ == '__main__':
    python_ver = setup_common.check_python_version()   # Here the code imports packaging and fails
    setup_common.ensure_base_requirements()            # Here the code installs packaging if not installed

```

Preparing the venv and installing packaging before running setup.sh works.

```
@:/media/files/ai$ git clone https://github.com/bmaltais/kohya_ss.git
@:/media/files/ai$ cd kohya_ss/
@:/media/files/ai/kohya_ss$ python3 -m venv /media/files/ai/kohya_ss/venv
@:/media/files/ai/kohya_ss$ source /media/files/ai/kohya_ss/venv/bin/activate
(venv) @:/media/files/ai/kohya_ss$ python3 -m pip install --upgrade packaging
Collecting packaging
  Using cached packaging-24.0-py3-none-any.whl (53 kB)
Installing collected packages: packaging
Successfully installed packaging-24.0
(venv) @:/media/files/ai/kohya_ss$ deactivate
@:/media/files/ai/kohya_ss$ ./setup.sh
Skipping git operations.
Ubuntu detected.
Python TK found...
Switching to virtual Python environment.
14:05:50-990358 INFO     Submodule initialized and updated.                                                                       
14:05:50-993358 INFO     Installing python dependencies. This could take a few minutes as it downloads files.                     
14:05:50-993928 INFO     If this operation ever runs too long, you can rerun this script in verbose mode to check.                
14:05:50-994579 INFO     Kohya_ss GUI version: v23.0.9                                                                            
14:05:50-995368 INFO     Installing modules from requirements_linux.txt...                                                        
14:05:50-996029 INFO     Installing package: torch==2.1.2+cu118 torchvision==0.16.2+cu118 xformers==0.0.23.post1+cu118            
                         --extra-index-url https://download.pytorch.org/whl/cu118                                                 
14:07:27-343336 INFO     Installing package: bitsandbytes==0.43.0                                                                 
14:07:31-732220 INFO     Installing package: tensorboard==2.15.2 tensorflow==2.15.0.post1                                         
14:07:57-705487 INFO     Installing modules from requirements.txt...                                                              
14:07:57-706283 INFO     Installing package: accelerate==0.25.0                                                                   
14:07:59-552769 INFO     Installing package: aiofiles==23.2.1                                                                     
14:08:00-270396 INFO     Installing package: altair==4.2.2                                                                        
14:08:05-337898 INFO     Installing package: dadaptation==3.1                                                                     
14:08:08-988436 INFO     Installing package: diffusers[torch]==0.25.0                                                             
14:08:11-438890 INFO     Installing package: easygui==0.98.3                                                                      
14:08:12-453606 INFO     Installing package: einops==0.7.0                                                                        
14:08:13-406066 INFO     Installing package: fairscale==0.4.13                                                                    
14:08:18-961702 INFO     Installing package: ftfy==6.1.1                                                                          
14:08:20-082992 INFO     Installing package: gradio==3.50.2                                                                       
14:08:29-315355 INFO     Installing package: huggingface-hub==0.20.1                                                              
14:08:30-656933 INFO     Installing package: invisible-watermark==0.2.0                                                           
14:08:33-306210 INFO     Installing package: lion-pytorch==0.0.6                                                                  
14:08:34-460254 INFO     Installing package: lycoris_lora==2.1.0.post3                                                            
14:08:40-007389 INFO     Installing package: omegaconf==2.3.0                                                                     
14:08:41-813722 INFO     Installing package: onnx==1.14.1                                                                         
14:08:45-041477 INFO     Installing package: onnxruntime-gpu==1.16.0                                                              
14:08:51-612857 INFO     Installing package: protobuf==3.20.3                                                                     
14:08:53-349388 INFO     Installing package: open-clip-torch==2.20.0                                                              
14:08:55-314156 INFO     Installing package: opencv-python==4.7.0.68                                                              
14:08:59-081998 INFO     Installing package: prodigyopt==1.0                                                                      
14:09:00-556910 INFO     Installing package: pytorch-lightning==1.9.0                                                             
14:09:04-190619 INFO     Installing package: rich==13.7.0                                                                         
14:09:05-861269 INFO     Installing package: safetensors==0.4.2                                                                   
14:09:07-288885 INFO     Installing package: timm==0.6.12                                                                         
14:09:09-228078 INFO     Installing package: tk==0.1.0                                                                            
14:09:10-761228 INFO     Installing package: toml==0.10.2                                                                         
14:09:12-215576 INFO     Installing package: transformers==4.36.2                                                                 
14:09:18-023438 INFO     Installing package: voluptuous==0.13.1                                                                   
14:09:19-573917 INFO     Installing package: wandb==0.15.11                                                                       
14:09:23-479789 INFO     Installing package: scipy==1.11.4                                                                        
14:09:28-245249 INFO     Installing package: -e ./sd-scripts                                                                      
14:09:29-877173 INFO     Configuring accelerate...                                                                                
14:09:29-878003 WARNING  Could not automatically configure accelerate. Please manually configure accelerate with the option in the
                         menu or with: accelerate config.                                                                         
Exiting Python virtual environment.
Setup finished! Run ./gui.sh to start.
Please note if you'd like to expose your public server you need to run ./gui.sh --share
@:/media/files/ai/kohya_ss$ 

```

Cheers!

**Comment by bmaltais** [comment]
Darn... I tought I had this under control... but apparently not... I will need to spend more time fixing the packaging requirement during setup.

**Comment by epicacrylic** [comment]
I figure similar vain, fresh install I get told no module is named "rich"

```
PS J:\..\kohya_ss> .\setup.bat
Creating venv...
Traceback (most recent call last):
  File "J:\..\kohya_ss\setup\setup_windows.py", line 235, in <module>
    setup_common.setup_logging()
  File "J:\..\kohya_ss\setup\setup_common.py", line 138, in setup_logging
    from rich.theme import Theme
ModuleNotFoundError: No module named 'rich'
```

**Comment by MisterLotto** [comment]
```Creating venv...
Traceback (most recent call last):
  File "H:\Projects\kohya_ss\setup\setup_windows.py", line 235, in <module>
    setup_common.setup_logging()
  File "H:\Projects\kohya_ss\setup\setup_common.py", line 138, in setup_logging
    from rich.theme import Theme
ModuleNotFoundError: No module named 'rich'```

Still getting that off the most recent release.

**Comment by bmaltais** [comment]
Now it is the rich module… strange

**Comment by bmaltais** [comment]
Try pulling from master and run setup again. I hope I have fixed everything this time. I tested both in WSL2 and Windows without errors...

**Comment by fjuhec** [comment]
Working fine now on a fresh install.
