### ISSUE TITLE
KeyError: 'time_embed.0.weight'   And    torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

### ISSUE THREAD

**Issue by zmy-08** [bmaltais/kohya_ss#2139]
Traceback (most recent call last):
  File "/icislab/volume1/zmy/A_MyProject/kohya_ss/sd-scripts/train_network.py", line 1058, in <module>
    trainer.train(args)
  File "/icislab/volume1/zmy/A_MyProject/kohya_ss/sd-scripts/train_network.py", line 235, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "/icislab/volume1/zmy/A_MyProject/kohya_ss/sd-scripts/train_network.py", line 103, in load_target_model
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "/icislab/volume1/zmy/A_MyProject/kohya_ss/sd-scripts/library/train_util.py", line 4114, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "/icislab/volume1/zmy/A_MyProject/kohya_ss/sd-scripts/library/train_util.py", line 4068, in _load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(
  File "/icislab/volume1/zmy/A_MyProject/kohya_ss/sd-scripts/library/model_util.py", line 1005, in load_models_from_stable_diffusion_checkpoint
    converted_unet_checkpoint = convert_ldm_unet_checkpoint(v2, state_dict, unet_config)
  File "/icislab/volume1/zmy/A_MyProject/kohya_ss/sd-scripts/library/model_util.py", line 267, in convert_ldm_unet_checkpoint
    new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
KeyError: 'time_embed.0.weight'
accelerator device: cuda:3
[2024-03-22 10:21:13,128] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 49258 closing signal SIGTERM
[2024-03-22 10:21:13,128] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 49259 closing signal SIGTERM
[2024-03-22 10:21:13,128] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 49260 closing signal SIGTERM
[2024-03-22 10:21:13,129] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 49263 closing signal SIGTERM
[2024-03-22 10:21:13,129] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 49264 closing signal SIGTERM
[2024-03-22 10:21:13,665] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 49257) of binary: /home/2023028046zmy/.conda/envs/env_kohya_ss/bin/python
Traceback (most recent call last):
  File "/home/2023028046zmy/.conda/envs/env_kohya_ss/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/2023028046zmy/.conda/envs/env_kohya_ss/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/2023028046zmy/.conda/envs/env_kohya_ss/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1008, in launch_command
    multi_gpu_launcher(args)
  File "/home/2023028046zmy/.conda/envs/env_kohya_ss/lib/python3.10/site-packages/accelerate/commands/launch.py", line 666, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/2023028046zmy/.conda/envs/env_kohya_ss/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/2023028046zmy/.conda/envs/env_kohya_ss/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/2023028046zmy/.conda/envs/env_kohya_ss/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/icislab/volume1/zmy/A_MyProject/kohya_ss/sd-scripts/train_network.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-22_10:21:13
  host      : admin007-NF5468M5
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 49257)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by bmaltais** [comment]
Make sure to install python following the README.md instructions. If you do not follow those you will run into issues like above. I see you use conda... I have not tested under conda and Kohya only support his sd-scripts under python.org installed python environments on windows.
