### ISSUE TITLE
Needing help to with my first time using Kohya_ss

### ISSUE THREAD

**Issue by Nerk0s** [bmaltais/kohya_ss#2142]
Hi guys,

I'm really new to this tool and every time I try to start a training I get this message:
![image](https://github.com/bmaltais/kohya_ss/assets/83953324/916c1bcc-135f-43f7-8241-8190a433c409)

**Comment by karen-pal** [comment]
just stumbled into this problem: it's because this system is very strict with your directory structure.

you have to have your dataset in a folder, then inside that folder have another folder with this format:

`{number_of_repeats} + "_"  + {your_lora_name}`

for example if i want to have 10 repeats:

```
myGreatTopicLora
|
|__10_myGreatTopic
      |__1.png
      |__1.txt
```

in this codebase the repeat is used in the training process this way:

```python

 # Calculate the total number of steps for this folder
                steps = repeats * num_images
                total_steps += steps
```


see more internal code here:
https://github.com/bmaltais/kohya_ss/blob/5bbb4fcf781f870a5cd58557dab87b4e2ef13c6d/kohya_gui/dreambooth_gui.py#L480

hope that helps

**Comment by Nerk0s** [comment]
now I've got this :
```Traceback (most recent call last):
  File "J:\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 710, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "J:\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "J:\kohya_ss\venv\lib\site-packages\diffusers\loaders\ip_adapter.py", line 34, in <module>
    from ..models.attention_processor import (
  File "J:\kohya_ss\venv\lib\site-packages\diffusers\models\attention_processor.py", line 32, in <module>
    import xformers.ops
  File "J:\kohya_ss\venv\lib\site-packages\xformers\ops\__init__.py", line 8, in <module>
    from .fmha import (
  File "J:\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 10, in <module>
    from . import attn_bias, cutlass, decoder, flash, small_k, triton, triton_splitk
  File "J:\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\triton_splitk.py", line 21, in <module>
    if TYPE_CHECKING or _has_triton21():
  File "J:\kohya_ss\venv\lib\site-packages\xformers\ops\common.py", line 192, in _has_triton21
    if not _has_a_version_of_triton():
  File "J:\kohya_ss\venv\lib\site-packages\xformers\ops\common.py", line 176, in _has_a_version_of_triton
    import triton  # noqa: F401
  File "J:\kohya_ss\venv\lib\site-packages\triton\__init__.py", line 8, in <module>
    from .runtime import (
  File "J:\kohya_ss\venv\lib\site-packages\triton\runtime\__init__.py", line 1, in <module>
    from .autotuner import (Autotuner, Config, Heuristics, OutOfResources, autotune, heuristics)
  File "J:\kohya_ss\venv\lib\site-packages\triton\runtime\autotuner.py", line 7, in <module>
    from ..testing import do_bench
  File "J:\kohya_ss\venv\lib\site-packages\triton\testing.py", line 7, in <module>
    from . import language as tl
  File "J:\kohya_ss\venv\lib\site-packages\triton\language\__init__.py", line 6, in <module>
    from .standard import (
  File "J:\kohya_ss\venv\lib\site-packages\triton\language\standard.py", line 3, in <module>
    from ..runtime.jit import jit
  File "J:\kohya_ss\venv\lib\site-packages\triton\runtime\jit.py", line 10, in <module>
    from ..runtime.driver import driver
  File "J:\kohya_ss\venv\lib\site-packages\triton\runtime\driver.py", line 1, in <module>
    from ..backends import backends
  File "J:\kohya_ss\venv\lib\site-packages\triton\backends\__init__.py", line 50, in <module>
    backends = _discover_backends()
  File "J:\kohya_ss\venv\lib\site-packages\triton\backends\__init__.py", line 44, in _discover_backends
    driver = _load_module(name, os.path.join(root, name, 'driver.py'))
  File "J:\kohya_ss\venv\lib\site-packages\triton\backends\__init__.py", line 12, in _load_module
    spec.loader.exec_module(module)
  File "J:\kohya_ss\venv\lib\site-packages\triton\backends\nvidia\driver.py", line 18, in <module>
    library_dir += [os.path.join(os.environ.get("CUDA_PATH"), "lib", "x64")]
  File "J:\Python\lib\ntpath.py", line 104, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "J:\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 710, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "J:\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "J:\kohya_ss\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 24, in <module>
    from ...loaders import FromSingleFileMixin, IPAdapterMixin, LoraLoaderMixin, TextualInversionLoaderMixin
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "J:\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 700, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "J:\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 712, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.loaders.ip_adapter because of the following error (look up to see its traceback):
expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "J:\kohya_ss\sd-scripts\train_db.py", line 20, in <module>
    import library.train_util as train_util
  File "J:\kohya_ss\sd-scripts\library\train_util.py", line 46, in <module>
    from diffusers import (
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "J:\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 701, in __getattr__
    value = getattr(module, name)
  File "J:\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 701, in __getattr__
    value = getattr(module, name)
  File "J:\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 700, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "J:\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 712, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.ip_adapter because of the following error (look up to see its traceback):
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "J:\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "J:\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "J:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "J:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "J:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "J:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['J:\\kohya_ss\\venv\\Scripts\\python.exe', 'J:\\kohya_ss/sd-scripts/train_db.py', '--bucket_no_upscale', '--bucket_reso_steps=64', '--cache_latents', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--learning_rate=1e-05', '--learning_rate_te=1e-05', '--logging_dir=J:/kohya_ss/logs', '--lr_scheduler=cosine', '--lr_scheduler_num_cycles=1', '--lr_warmup_steps=73102', '--max_data_loader_n_workers=0', '--resolution=512,512', '--max_train_steps=731025', '--mixed_precision=fp16', '--optimizer_type=AdamW8bit', '--output_dir=J:\\ai\\training\\H\\Cervina Output', '--output_name=last', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--save_every_n_epochs=1', '--save_model_as=safetensors', '--save_precision=fp16', '--train_batch_size=1', '--train_data_dir=J:\\ai\\training\\H\\Cervina7', '--xformers']' returned non-zero exit status 1.```

**Comment by karen-pal** [comment]
> library_dir += [os.path.join(os.environ.get("CUDA_PATH"), "lib", "x64")]

The error message is telling you - check your CUDA path and see if it's set

**Comment by bmaltais** [comment]
Did you follow the README.md and install CUDA 11.8 Toolkit?
