### ISSUE TITLE
Web GUI Launch Error

### ISSUE THREAD

**Issue by FranzRome** [bmaltais/kohya_ss#2145]
### Setup:
I have a clean installation of the **last version (23.0.15)** on my **Windows machine (GPU Nvidia 3080 laptop)** in the **root of my C** drive to avoid any permission issue. During the setup and the installation of packages everithing is ok:
```cmd
04:38:26-380713 INFO     Kohya_ss GUI version: v23.0.15
04:38:26-396767 INFO     Python version is 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
04:38:31-283766 INFO     Submodule initialized and updated.
04:38:31-283766 INFO     Installing modules from requirements_windows_torch2.txt...
04:38:31-283766 INFO     Installing package: torch==2.1.2+cu118 torchvision==0.16.2+cu118 torchaudio==2.1.2+cu118 xformers==0.0.23.post1+cu118 --index-url https://download.pytorch.org/whl/cu118
04:42:23-450805 INFO     Installing package: bitsandbytes==0.43.0
04:42:26-776344 INFO     Installing package: tensorboard==2.14.1 tensorflow==2.14.0
04:43:11-998218 INFO     Installing modules from requirements.txt...
04:43:12-045093 INFO     Installing package: accelerate==0.25.0
04:43:17-321821 INFO     Installing package: aiofiles==23.2.1
04:43:18-499406 INFO     Installing package: altair==4.2.2
04:43:37-553090 INFO     Installing package: dadaptation==3.1
04:43:43-573834 INFO     Installing package: diffusers[torch]==0.25.0
04:43:49-071810 INFO     Installing package: easygui==0.98.3
04:43:50-531257 INFO     Installing package: einops==0.7.0
04:43:51-961381 INFO     Installing package: fairscale==0.4.13
04:44:01-142055 INFO     Installing package: ftfy==6.1.1
04:44:02-776174 INFO     Installing package: gradio==3.50.2
04:44:22-261566 INFO     Installing package: huggingface-hub==0.20.1
04:44:24-727126 INFO     Installing package: invisible-watermark==0.2.0
04:44:27-617430 INFO     Installing package: lion-pytorch==0.0.6
04:44:28-967367 INFO     Installing package: lycoris_lora==2.2.0.post3
04:44:49-795470 INFO     Installing package: omegaconf==2.3.0
04:44:54-005363 INFO     Installing package: onnx==1.14.1
04:45:02-312556 INFO     Installing package: onnxruntime-gpu==1.16.0
04:45:09-189971 INFO     Installing package: protobuf==3.20.3
04:45:11-624101 INFO     Installing package: open-clip-torch==2.20.0
04:45:16-473396 INFO     Installing package: opencv-python==4.7.0.68
04:45:18-815736 INFO     Installing package: prodigyopt==1.0
04:45:20-558271 INFO     Installing package: pytorch-lightning==1.9.0
04:45:29-707755 INFO     Installing package: rich==13.7.0
04:45:32-325922 INFO     Installing package: safetensors==0.4.2
04:45:34-117321 INFO     Installing package: timm==0.6.12
04:45:37-808387 INFO     Installing package: tk==0.1.0
04:45:39-552040 INFO     Installing package: toml==0.10.2
04:45:41-233918 INFO     Installing package: transformers==4.36.2
04:46:00-521752 INFO     Installing package: voluptuous==0.13.1
04:46:02-442410 INFO     Installing package: wandb==0.15.11
04:46:14-749707 INFO     Installing package: scipy==1.11.4
04:46:25-178239 INFO     Installing package: -e ./sd-scripts
04:46:28-144544 INFO     Configuring accelerate...
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------In which compute environment are you running?
This machine
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Which type of machine are you using?
No distributed training
Do you want to run your training on CPU only (even if a GPU / Apple Silicon / Ascend NPU device is available)? [yes/NO]:
Do you wish to optimize your script with torch dynamo?[yes/NO]:
Do you want to use DeepSpeed? [yes/NO]:
What GPU(s) (by id) should be used for training on this machine as a comma-seperated list? [all]:
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Do you wish to use FP16 or BF16 (mixed precision)?
fp16
accelerate configuration saved at C:\Users\franc/.cache\huggingface\accelerate\default_config.yaml
```
I used **default settings** and **fp16 mixed precision**

### Problem:
The problem comes when i launch the Web GUI:
```cmd
04:59:29-804267 INFO     Kohya_ss GUI version: v23.0.15
04:59:30-322287 INFO     Submodule initialized and updated.
04:59:30-322287 INFO     nVidia toolkit detected
04:59:31-907757 INFO     Torch 2.1.2+cu118
04:59:33-470744 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
04:59:33-486371 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 Laptop GPU VRAM 8192 Arch (8, 6) Cores 48
04:59:33-486371 INFO     Python version is 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit
                         (AMD64)]
04:59:33-486371 INFO     Verifying modules installation status from requirements_windows_torch2.txt...
04:59:33-486371 INFO     Verifying modules installation status from requirements.txt...
Traceback (most recent call last):
  File "C:\kohya_ss\kohya_gui.py", line 4, in <module>
    from kohya_gui.class_gui_config import KohyaSSGUIConfig
  File "C:\kohya_ss\kohya_gui\class_gui_config.py", line 2, in <module>
    from .common_gui import scriptdir
  File "C:\kohya_ss\kohya_gui\common_gui.py", line 1, in <module>
    from tkinter import filedialog, Tk
ModuleNotFoundError: No module named 'tkinter'
```
Why tkinter is missing? It should get installed during the venv setup
**How can it be solved?**

**Comment by karen-pal** [comment]
please provide python version inside your virtualenv

**Comment by karen-pal** [comment]
I see the python version is correct. Just to be sure, can you check that you are running the gui with your virtualenv activated? I _just_ installed and run the latest version in linux and this didn't happen.

you can also try just installing tkinter using pip and seeing what happens.

**Comment by FranzRome** [comment]
@karen-pal thanks for the response. I manually activated the venv:
```cmd
C:\kohya_ss>venv\Scripts\activate

(venv) C:\kohya_ss>setup.bat
```
Then tried to run the GUI but i got the same error

I also tried to install tkinter in venv:
```cmd
(venv) C:\kohya_ss>python -V
Python 3.10.11

(venv) C:\kohya_ss>pip install tkinter
ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
```
It can't find tkinter... am I writing its name wrong?

**Comment by bmaltais** [comment]
Did you install python using the link provided on the readme? Other python install are lacking that module.

**Comment by FranzRome** [comment]
Reinstalled python using the link in readme. Now it works fine, thank you so much.
