### ISSUE TITLE
How to use multi-GPU or SLI to solve the GPU memory overflow?

### ISSUE THREAD

**Issue by littleyeson** [bmaltais/kohya_ss#2163]
If a V100 16G training process requires too much memory overflow, can using two V100 16Gs solve this problem? How do I set up distributed computing in Kohya_SS? Do I use the multi-GPU option or do I set it within the acceleration settings menu?

**Comment by littleyeson** [comment]
![Uploading QQ截图20240329211828.jpg…]()
[W socket.cpp:663] [c10d] The client socket has failed to connect to [api2.enscape3d.com]:29500 (system error: 10049 - 在其上下文中，该 请求的地址无效。).
Traceback (most recent call last):
  File "C:\AI\kohya_ss\sd-scripts\sdxl_train_network.py", line 184, in <module>
    trainer.train(args)
  File "C:\AI\kohya_ss\sd-scripts\train_network.py", line 227, in train
    accelerator = train_util.prepare_accelerator(args)
  File "C:\AI\kohya_ss\sd-scripts\library\train_util.py", line 4031, in prepare_accelerator
    accelerator = Accelerator(
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 371, in __init__
    self.state = AcceleratorState(
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\state.py", line 758, in __init__
    PartialState(cpu, **kwargs)
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\state.py", line 217, in __init__
    torch.distributed.init_process_group(backend=self.backend, **kwargs)
  File "C:\AI\kohya_ss\venv\lib\site-packages\torch\distributed\c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
  File "C:\AI\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 1148, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "C:\AI\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 1268, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL built in")
RuntimeError: Distributed package doesn't have NCCL built in
[2024-03-29 21:18:33,049] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 23648) of binary: C:\AI\kohya_ss\venv\Scripts\python.exe
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\AI\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1008, in launch_command
    multi_gpu_launcher(args)
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 666, in multi_gpu_launcher
    distrib_run.run(args)
  File "C:\AI\kohya_ss\venv\lib\site-packages\torch\distributed\run.py", line 797, in run
    elastic_launch(
  File "C:\AI\kohya_ss\venv\lib\site-packages\torch\distributed\launcher\api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\AI\kohya_ss\venv\lib\site-packages\torch\distributed\launcher\api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
C:\AI\kohya_ss/sd-scripts/sdxl_train_network.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-03-29_21:18:33
  host      : YAI.ciscovnp.com
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 4180)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-29_21:18:33
  host      : YAI.ciscovnp.com
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 23648)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by littleyeson** [comment]
![Uploading QQ截图20240329211828.jpg…]()

**Comment by littleyeson** [comment]
INFO     preparing accelerator                                                                  train_network.py:226
[W socket.cpp:663] [c10d] The client socket has failed to connect to [api2.enscape3d.com]:29500 (system error: 10049 - 在其上下文中，该 请求的地址无效。).
Traceback (most recent call last):
  File "C:\AI\kohya_ss\sd-scripts\sdxl_train_network.py", line 184, in <module>
    trainer.train(args)
  File "C:\AI\kohya_ss\sd-scripts\train_network.py", line 227, in train
    accelerator = train_util.prepare_accelerator(args)
  File "C:\AI\kohya_ss\sd-scripts\library\train_util.py", line 4031, in prepare_accelerator
    accelerator = Accelerator(
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 371, in __init__
    self.state = AcceleratorState(
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\state.py", line 758, in __init__
    PartialState(cpu, **kwargs)
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\state.py", line 217, in __init__
    torch.distributed.init_process_group(backend=self.backend, **kwargs)
  File "C:\AI\kohya_ss\venv\lib\site-packages\torch\distributed\c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
  File "C:\AI\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 1148, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "C:\AI\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 1268, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL built in")
RuntimeError: Distributed package doesn't have NCCL built in
[2024-03-29 21:25:18,612] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 24164) of binary: C:\AI\kohya_ss\venv\Scripts\python.exe
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\AI\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1008, in launch_command
    multi_gpu_launcher(args)
  File "C:\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 666, in multi_gpu_launcher
    distrib_run.run(args)
  File "C:\AI\kohya_ss\venv\lib\site-packages\torch\distributed\run.py", line 797, in run
    elastic_launch(
  File "C:\AI\kohya_ss\venv\lib\site-packages\torch\distributed\launcher\api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\AI\kohya_ss\venv\lib\site-packages\torch\distributed\launcher\api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
C:\AI\kohya_ss/sd-scripts/sdxl_train_network.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-03-29_21:25:18
  host      : YAI.ciscovnp.com
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 12856)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-29_21:25:18
  host      : YAI.ciscovnp.com
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 24164)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
