### ISSUE TITLE
" returned non-zero exit status 1 " issues - I can’t start lora training - 

### ISSUE THREAD

**Issue by RayMeen** [bmaltais/kohya_ss#2204]
Hello guys i cant run the lora training and i always have this error. I don't how fix this error, i all tried ...

Thanks in advance 

Here the errors lines : 

it status 1.19:52:53-790349 INFO     Start training Dreambooth...
19:52:53-791349 INFO     Validating model file or folder path
                         D:/sd/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0.safetensors existence...
19:52:53-793349 INFO     ...valid
19:52:53-794350 INFO     Validating output_dir path D:/Model/model existence...
19:52:53-795350 INFO     ...valid
19:52:53-796350 INFO     Validating train_data_dir path D:/Model/img existence...
19:52:53-797350 INFO     ...valid
19:52:53-798351 INFO     reg_data_dir not specified, skipping validation
19:52:53-799351 INFO     Validating logging_dir path D:/Model/log existence...
19:52:53-800351 INFO     ...valid
19:52:53-801351 INFO     log_tracker_config not specified, skipping validation
19:52:53-802351 INFO     resume not specified, skipping validation
19:52:53-803352 INFO     vae not specified, skipping validation
19:52:53-804352 INFO     dataset_config not specified, skipping validation
19:52:53-805352 INFO     Folder 40_thiccwithaqq style : steps 880
19:52:53-806352 INFO     max_train_steps (880 / 1 / 1 * 1 * 1) = 880
19:52:53-807353 INFO     stop_text_encoder_training = 0
19:52:53-809353 INFO     lr_warmup_steps = 88
19:52:53-811354 INFO     Saving training config to D:/Model/model\style_20240403-195253.json...
19:52:53-813354 INFO     accelerate launch --num_cpu_threads_per_process=2
                         "D:\sd\kohya\kohya_ss\kohya_ss/sd-scripts/train_db.py"  --bucket_no_upscale
                         --bucket_reso_steps=64 --cache_latents --enable_bucket --min_bucket_reso=256
                         --max_bucket_reso=2048 --learning_rate="1e-05" --learning_rate_te="1e-05"
                         --logging_dir="D:/Model/log" --lr_scheduler="cosine" --lr_scheduler_num_cycles="1"
                         --lr_warmup_steps="88" --max_data_loader_n_workers="0" --resolution="512,512"
                         --max_train_steps="880" --mixed_precision="bf16" --optimizer_type="AdamW"
                         --output_dir="D:/Model/model" --output_name="style"
                         --pretrained_model_name_or_path="D:/sd/stable-diffusion-webui/models/Stable-diffusion/sd_xl_bas                         e_1.0.safetensors" --save_every_n_epochs="1" --save_model_as=safetensors
                         --save_precision="fp16" --train_batch_size="1" --train_data_dir="D:/Model/img" --xformers
Traceback (most recent call last):
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 710, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\rayam\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\diffusers\loaders\ip_adapter.py", line 34, in <module>
    from ..models.attention_processor import (
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\diffusers\models\attention_processor.py", line 32, in <module>
    import xformers.ops
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\xformers\ops\__init__.py", line 8, in <module>
    from .fmha import (
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 10, in <module>
    from . import attn_bias, cutlass, decoder, flash, small_k, triton, triton_splitk
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\triton_splitk.py", line 21, in <module>
    if TYPE_CHECKING or _has_triton21():
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\xformers\ops\common.py", line 192, in _has_triton21
    if not _has_a_version_of_triton():
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\xformers\ops\common.py", line 176, in _has_a_version_of_triton
    import triton  # noqa: F401
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\triton\__init__.py", line 8, in <module>
    from .runtime import (
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\triton\runtime\__init__.py", line 1, in <module>
    from .autotuner import (Autotuner, Config, Heuristics, OutOfResources, autotune, heuristics)
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\triton\runtime\autotuner.py", line 7, in <module>
    from ..testing import do_bench
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\triton\testing.py", line 7, in <module>
    from . import language as tl
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\triton\language\__init__.py", line 6, in <module>
    from .standard import (
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\triton\language\standard.py", line 3, in <module>
    from ..runtime.jit import jit
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\triton\runtime\jit.py", line 10, in <module>
    from ..runtime.driver import driver
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\triton\runtime\driver.py", line 1, in <module>
    from ..backends import backends
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\triton\backends\__init__.py", line 50, in <module>
    backends = _discover_backends()
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\triton\backends\__init__.py", line 44, in _discover_backends
    driver = _load_module(name, os.path.join(root, name, 'driver.py'))
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\triton\backends\__init__.py", line 12, in _load_module
    spec.loader.exec_module(module)
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\triton\backends\nvidia\driver.py", line 18, in <module>
    library_dir += [os.path.join(os.environ.get("CUDA_PATH"), "lib", "x64")]
  File "C:\Users\rayam\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 104, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 710, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\rayam\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 24, in <module>
    from ...loaders import FromSingleFileMixin, IPAdapterMixin, LoraLoaderMixin, TextualInversionLoaderMixin
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 700, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 712, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.loaders.ip_adapter because of the following error (look up to see its traceback):
expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\sd\kohya\kohya_ss\kohya_ss\sd-scripts\train_db.py", line 20, in <module>
    import library.train_util as train_util
  File "D:\sd\kohya\kohya_ss\kohya_ss\sd-scripts\library\train_util.py", line 46, in <module>
    from diffusers import (
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 701, in __getattr__
    value = getattr(module, name)
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 701, in __getattr__
    value = getattr(module, name)
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 700, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 712, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.ip_adapter because of the following error (look up to see its traceback):
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "C:\Users\rayam\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rayam\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\sd\\kohya\\kohya_ss\\kohya_ss\\venv\\Scripts\\python.exe', 'D:\\sd\\kohya\\kohya_ss\\kohya_ss/sd-scripts/train_db.py', '--bucket_no_upscale', '--bucket_reso_steps=64', '--cache_latents', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--learning_rate=1e-05', '--learning_rate_te=1e-05', '--logging_dir=D:/Model/log', '--lr_scheduler=cosine', '--lr_scheduler_num_cycles=1', '--lr_warmup_steps=88', '--max_data_loader_n_workers=0', '--resolution=512,512', '--max_train_steps=880', '--mixed_precision=bf16', '--optimizer_type=AdamW', '--output_dir=D:/Model/model', '--output_name=style', '--pretrained_model_name_or_path=D:/sd/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0.safetensors', '--save_every_n_epochs=1', '--save_model_as=safetensors', '--save_precision=fp16', '--train_batch_size=1', '--train_data_dir=D:/Model/img', '--xformers']' returned non-zero exit status 1.

**Comment by RayMeen** [comment]
@5KilosOfCheese i will try to do what you said

**Comment by RayMeen** [comment]
@bmaltais i will do the same

**Comment by RayMeen** [comment]
@bmaltais Now i have this error i dont know how resolve the problem its hard. 

Thanks for advices.


Here error : 

00:46:01-097896 INFO     Loading config...
00:47:20-228095 INFO     Start training LoRA Standard ...
00:47:20-229095 INFO     Validating model file or folder path
                         D:/sd/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0.safetensors existence...
00:47:20-231315 INFO     ...valid
00:47:20-232096 INFO     Validating output_dir path D:/Model/model existence...
00:47:20-233096 INFO     ...valid
00:47:20-234096 INFO     Validating train_data_dir path D:/Model/img existence...
00:47:20-235097 INFO     ...valid
00:47:20-236097 INFO     reg_data_dir not specified, skipping validation
00:47:20-237098 INFO     Validating logging_dir path D:/Model/log existence...
00:47:20-237098 INFO     ...valid
00:47:20-238098 INFO     log_tracker_config not specified, skipping validation
00:47:20-239098 INFO     resume not specified, skipping validation
00:47:20-240098 INFO     vae not specified, skipping validation
00:47:20-241098 INFO     lora_network_weights not specified, skipping validation
00:47:20-241098 INFO     dataset_config not specified, skipping validation
00:47:20-243098 INFO     Folder 40_thiccwithaqq style: 22 images found
00:47:20-244098 INFO     Folder 40_thiccwithaqq style: 880 steps
00:47:20-245099 INFO     Total steps: 880
00:47:20-246099 INFO     Train batch size: 2
00:47:20-247099 INFO     Gradient accumulation steps: 1
00:47:20-248100 INFO     Epoch: 1
00:47:20-251100 INFO     Regulatization factor: 1
00:47:20-252100 INFO     max_train_steps (880 / 2 / 1 * 1 * 1) = 440
00:47:20-253101 INFO     stop_text_encoder_training = 0
00:47:20-254100 INFO     lr_warmup_steps = 0
00:47:20-255101 INFO     Saving training config to D:/Model/model\Thiccwithaq_20240404-004720.json...
00:47:20-257101 INFO     accelerate launch --num_cpu_threads_per_process=2
                         "D:\sd\kohya\kohya_ss\kohya_ss/sd-scripts/sdxl_train_network.py"  --bucket_no_upscale
                         --bucket_reso_steps=64 --cache_latents --caption_extension=".txt" --clip_skip=2
                         --gradient_checkpointing --learning_rate="0.0001" --logging_dir="D:/Model/log"
                         --lr_scheduler="constant" --lr_scheduler_num_cycles="1" --max_data_loader_n_workers="1"
                         --max_grad_norm="1" --resolution="712,712" --max_train_steps="440" --mem_eff_attn
                         --mixed_precision="fp16" --network_alpha="128" --network_dim=128 --network_module=networks.lora                         --no_half_vae --optimizer_type="Adafactor" --output_dir="D:/Model/model"
                         --output_name="Thiccwithaq"
                         --pretrained_model_name_or_path="D:/sd/stable-diffusion-webui/models/Stable-diffusion/sd_xl_bas                         e_1.0.safetensors" --save_every_n_epochs="1" --save_model_as=safetensors
                         --save_precision="fp16" --seed="1234" --text_encoder_lr=0.0003 --train_batch_size="2"
                         --train_data_dir="D:/Model/img" --unet_lr=0.0001 --xformers
2024-04-04 00:48:12 INFO     prepare tokenizers                                                   sdxl_train_util.py:1352024-04-04 00:48:13 INFO     Using DreamBooth method.                                               train_network.py:173                    INFO     prepare images.                                                          train_util.py:1469                    INFO     found directory D:\Model\img\40_thiccwithaqq style contains 22 image     train_util.py:1432                             files
                    WARNING  No caption file found for 22 images. Training will continue without      train_util.py:1459                             captions for these images. If class token exists, it will be used. /
                             22枚の画像にキャプションファイルが見つかりませんでした。これらの画像につ
                             いてはキャプションなしで学習を続行します。class
                             tokenが存在する場合はそれを使います。
                    WARNING  D:\Model\img\40_thiccwithaqq style\08f763127de8ecf20457ce8fd1e0736d.jpg  train_util.py:1466                    WARNING  D:\Model\img\40_thiccwithaqq style\1b8ada6d916f5885b6e8a2068e1bf719.png  train_util.py:1466                    WARNING  D:\Model\img\40_thiccwithaqq style\1ef3c4d6faf11876140275290947b130.jpg  train_util.py:1466                    WARNING  D:\Model\img\40_thiccwithaqq style\1f99db6bee709984530c0e629e9d85c7.png  train_util.py:1466                    WARNING  D:\Model\img\40_thiccwithaqq style\2820ab5ef60fab58bef83b236426abc3.png  train_util.py:1466                    WARNING  D:\Model\img\40_thiccwithaqq                                             train_util.py:1464                             style\386d2ddc35b93ad4bf1c63af05cc97f1.png... and 17 more
                    INFO     880 train images with repeating.                                         train_util.py:1508                    INFO     0 reg images.                                                            train_util.py:1511                    WARNING  no regularization images / 正則化画像が見つかりませんでした              train_util.py:1516                    INFO     [Dataset 0]                                                              config_util.py:544                               batch_size: 2
                               resolution: (712, 712)
                               enable_bucket: False
                               network_multiplier: 1.0

                               [Subset 0 of Dataset 0]
                                 image_dir: "D:\Model\img\40_thiccwithaqq style"
                                 image_count: 22
                                 num_repeats: 40
                                 shuffle_caption: False
                                 keep_tokens: 0
                                 keep_tokens_separator:
                                 caption_dropout_rate: 0.0
                                 caption_dropout_every_n_epoches: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 is_reg: False
                                 class_tokens: thiccwithaqq style
                                 caption_extension: .txt


                    INFO     [Dataset 0]                                                              config_util.py:550                    INFO     loading image sizes.                                                      train_util.py:794100%|█████████████████████████████████████████████████████████████████████████████████| 22/22 [00:00<00:00, 124.85it/s]
2024-04-04 00:48:14 INFO     prepare dataset                                                           train_util.py:802                    WARNING  clip_skip will be unexpected / SDXL学習ではclip_skipは動作しません   sdxl_train_util.py:344                    INFO     preparing accelerator                                                  train_network.py:226accelerator device: cuda
                    INFO     loading model for process 0/1                                         sdxl_train_util.py:31                    INFO     load StableDiffusion checkpoint:                                      sdxl_train_util.py:71                             D:/sd/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0.s
                             afetensors
2024-04-04 00:48:25 INFO     building U-Net                                                       sdxl_model_util.py:1922024-04-04 00:48:26 INFO     loading U-Net from checkpoint                                        sdxl_model_util.py:196
2024-04-04 00:52:45 INFO     U-Net: <All keys matched successfully>                                                                                                                                                    sdxl_model_util.py:202
2024-04-04 00:52:48 INFO     building text encoders                                                                                                                                                                    sdxl_model_util.py:205
2024-04-04 00:52:58 INFO     loading text encoders from checkpoint                                                                                                                                                     sdxl_model_util.py:258
2024-04-04 00:53:34 INFO     text encoder 1: <All keys matched successfully>                                                                                                                                           sdxl_model_util.py:272
2024-04-04 00:56:06 INFO     text encoder 2: <All keys matched successfully>                                                                                                                                           sdxl_model_util.py:276
                    INFO     building VAE                                                                                                                                                                              sdxl_model_util.py:279
2024-04-04 00:56:08 INFO     loading VAE from checkpoint                                                                                                                                                               sdxl_model_util.py:284
2024-04-04 00:56:22 INFO     VAE: <All keys matched successfully>                                                                                                                                                      sdxl_model_util.py:287
2024-04-04 00:56:47 INFO     Enable memory efficient attention for U-Net                                                                                                                                                   train_util.py:2526
import network module: networks.lora
2024-04-04 00:57:01 INFO     [Dataset 0]                                                                                                                                                                                   train_util.py:1948
                    INFO     caching latents.                                                                                                                                                                               train_util.py:915
                    INFO     checking cache validity...                                                                                                                                                                     train_util.py:925
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:00<00:00, 22012.09it/s]
                    INFO     caching latents...                                                                                                                                                                             train_util.py:962
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:25<00:00,  1.18s/it]
2024-04-04 00:57:30 INFO     create LoRA network. base dim (rank): 128, alpha: 128.0                                                                                                                                              lora.py:811
                    INFO     neuron dropout: p=None, rank dropout: p=None, module dropout: p=None                                                                                                                                 lora.py:812
                    INFO     create LoRA for Text Encoder 1:                                                                                                                                                                      lora.py:903
                    INFO     create LoRA for Text Encoder 2:                                                                                                                                                                      lora.py:903
2024-04-04 00:57:31 INFO     create LoRA for Text Encoder: 264 modules.                                                                                                                                                           lora.py:911
2024-04-04 00:57:33 INFO     create LoRA for U-Net: 722 modules.                                                                                                                                                                  lora.py:919
                    INFO     enable LoRA for text encoder                                                                                                                                                                         lora.py:962
                    INFO     enable LoRA for U-Net                                                                                                                                                                                lora.py:967
prepare optimizer, data loader etc.
2024-04-04 00:57:34 INFO     use Adafactor optimizer | {'relative_step': True}                                                                                                                                             train_util.py:3779
                    INFO     relative_step is true / relative_stepがtrueです                                                                                                                                               train_util.py:3782
                    WARNING  learning rate is used as initial_lr / 指定したlearning rateはinitial_lrとして使用されます                                                                                                     train_util.py:3784
                    WARNING  unet_lr and text_encoder_lr are ignored / unet_lrとtext_encoder_lrは無視されます                                                                                                              train_util.py:3796
                    INFO     use adafactor_scheduler / スケジューラにadafactor_schedulerを使用します                                                                                                                       train_util.py:3801
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 880
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 440
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 2
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 440
steps:   0%|                                                                                                                                                                                                        | 0/440 [00:00<?, ?it/s]
epoch 1/1
D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\torch\utils\checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
Traceback (most recent call last):
  File "D:\sd\kohya\kohya_ss\kohya_ss\sd-scripts\sdxl_train_network.py", line 184, in <module>
    trainer.train(args)
  File "D:\sd\kohya\kohya_ss\kohya_ss\sd-scripts\train_network.py", line 814, in train
    noise_pred = self.call_unet(
  File "D:\sd\kohya\kohya_ss\kohya_ss\sd-scripts\sdxl_train_network.py", line 164, in call_unet
    noise_pred = unet(noisy_latents, timesteps, text_embedding, vector_embedding)
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 680, in forward
    return model_forward(*args, **kwargs)
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 668, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\torch\amp\autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "D:\sd\kohya\kohya_ss\kohya_ss\sd-scripts\library\sdxl_original_unet.py", line 1110, in forward
    h = torch.cat([h, hs.pop()], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 46 but got size 45 for tensor number 1 in the list.
steps:   0%|                                                                                                                                                                                                        | 0/440 [02:26<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\rayam\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rayam\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "D:\sd\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\sd\\kohya\\kohya_ss\\kohya_ss\\venv\\Scripts\\python.exe', 'D:\\sd\\kohya\\kohya_ss\\kohya_ss/sd-scripts/sdxl_train_network.py', '--bucket_no_upscale', '--bucket_reso_steps=64', '--cache_latents', '--caption_extension=.txt', '--clip_skip=2', '--gradient_checkpointing', '--learning_rate=0.0001', '--logging_dir=D:/Model/log', '--lr_scheduler=constant', '--lr_scheduler_num_cycles=1', '--max_data_loader_n_workers=1', '--max_grad_norm=1', '--resolution=712,712', '--max_train_steps=440', '--mem_eff_attn', '--mixed_precision=fp16', '--network_alpha=128', '--network_dim=128', '--network_module=networks.lora', '--no_half_vae', '--optimizer_type=Adafactor', '--output_dir=D:/Model/model', '--output_name=Thiccwithaq', '--pretrained_model_name_or_path=D:/sd/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0.safetensors', '--save_every_n_epochs=1', '--save_model_as=safetensors', '--save_precision=fp16', '--seed=1234', '--text_encoder_lr=0.0003', '--train_batch_size=2', '--train_data_dir=D:/Model/img', '--unet_lr=0.0001', '--xformers']' returned non-zero exit status 1.
