### ISSUE TITLE
RuntimeError: File D:/kohya_ss/outputs cannot be opened.

### ISSUE THREAD

**Issue by koppimashin** [bmaltais/kohya_ss#2211]
14:04:17-424405 INFO     Merge model...
14:04:17-425415 INFO     "D:\kohya_ss\venv\Scripts\python.exe" "D:\kohya_ss/sd-scripts/networks/merge_lora.py"
                         --save_precision fp16 --precision float --save_to "D:/kohya_ss/outputs" --models
                         "E:/Downloads/Perfect_Pinay_01_v2-10.safetensors"
                         "E:/Downloads/Perfect_Pinay_02_v2-10.safetensors" --ratios 0.5 0.5
2024-04-05 14:04:22 INFO     loading: E:/Downloads/Perfect_Pinay_01_v2-10.safetensors                  merge_lora.py:124
                    INFO     dim: [64], alpha: [32.0]                                                  merge_lora.py:157
                    INFO     merging...                                                                merge_lora.py:160
                    INFO     loading: E:/Downloads/Perfect_Pinay_02_v2-10.safetensors                  merge_lora.py:124
2024-04-05 14:04:23 INFO     dim: [64], alpha: [32.0]                                                  merge_lora.py:157
                    INFO     merging...                                                                merge_lora.py:160
                    INFO     merged model                                                              merge_lora.py:202
                    INFO     dim: [64], alpha: [32.0]                                                  merge_lora.py:203
                    INFO     calculating hashes and creating metadata...                               merge_lora.py:281
                    INFO     saving model to: D:/kohya_ss/outputs                                      merge_lora.py:300
Traceback (most recent call last):
  File "D:\kohya_ss\sd-scripts\networks\merge_lora.py", line 360, in <module>
    merge(args)
  File "D:\kohya_ss\sd-scripts\networks\merge_lora.py", line 301, in merge
    save_to_file(args.save_to, state_dict, state_dict, save_dtype, metadata)
  File "D:\kohya_ss\sd-scripts\networks\merge_lora.py", line 39, in save_to_file
    torch.save(model, file_name)
  File "D:\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 618, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "D:\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 492, in _open_zipfile_writer
    return container(name_or_buffer)
  File "D:\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 463, in __init__
    super().__init__(torch._C.PyTorchFileWriter(self.name))
RuntimeError: File D:/kohya_ss/outputs cannot be opened.
14:04:24-497945 INFO     Done merging...
14:04:48-790860 INFO     Merge model...
14:04:48-792371 INFO     "D:\kohya_ss\venv\Scripts\python.exe" "D:\kohya_ss/sd-scripts/networks/merge_lora.py"
                         --save_precision fp16 --precision float --save_to "D:/kohya_ss" --models
                         "E:/Downloads/Perfect_Pinay_01_v2-10.safetensors"
                         "E:/Downloads/Perfect_Pinay_02_v2-10.safetensors" --ratios 0.5 0.5
2024-04-05 14:04:53 INFO     loading: E:/Downloads/Perfect_Pinay_01_v2-10.safetensors                  merge_lora.py:124
                    INFO     dim: [64], alpha: [32.0]                                                  merge_lora.py:157
                    INFO     merging...                                                                merge_lora.py:160
                    INFO     loading: E:/Downloads/Perfect_Pinay_02_v2-10.safetensors                  merge_lora.py:124
                    INFO     dim: [64], alpha: [32.0]                                                  merge_lora.py:157
                    INFO     merging...                                                                merge_lora.py:160
                    INFO     merged model                                                              merge_lora.py:202
                    INFO     dim: [64], alpha: [32.0]                                                  merge_lora.py:203
                    INFO     calculating hashes and creating metadata...                               merge_lora.py:281
2024-04-05 14:04:54 INFO     saving model to: D:/kohya_ss                                              merge_lora.py:300
Traceback (most recent call last):
  File "D:\kohya_ss\sd-scripts\networks\merge_lora.py", line 360, in <module>
    merge(args)
  File "D:\kohya_ss\sd-scripts\networks\merge_lora.py", line 301, in merge
    save_to_file(args.save_to, state_dict, state_dict, save_dtype, metadata)
  File "D:\kohya_ss\sd-scripts\networks\merge_lora.py", line 39, in save_to_file
    torch.save(model, file_name)
  File "D:\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 618, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "D:\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 492, in _open_zipfile_writer
    return container(name_or_buffer)
  File "D:\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 463, in __init__
    super().__init__(torch._C.PyTorchFileWriter(self.name))
RuntimeError: Parent directory D: does not exist.
14:04:55-358836 INFO     Done merging...
14:05:12-938627 INFO     Merge model...
14:05:12-939636 INFO     "D:\kohya_ss\venv\Scripts\python.exe" "D:\kohya_ss/sd-scripts/networks/merge_lora.py"
                         --save_precision fp16 --precision float --save_to "C:" --models
                         "E:/Downloads/Perfect_Pinay_01_v2-10.safetensors"
                         "E:/Downloads/Perfect_Pinay_02_v2-10.safetensors" --ratios 0.5 0.5
2024-04-05 14:05:17 INFO     loading: E:/Downloads/Perfect_Pinay_01_v2-10.safetensors                  merge_lora.py:124
                    INFO     dim: [64], alpha: [32.0]                                                  merge_lora.py:157
                    INFO     merging...                                                                merge_lora.py:160
                    INFO     loading: E:/Downloads/Perfect_Pinay_02_v2-10.safetensors                  merge_lora.py:124
2024-04-05 14:05:18 INFO     dim: [64], alpha: [32.0]                                                  merge_lora.py:157
                    INFO     merging...                                                                merge_lora.py:160
                    INFO     merged model                                                              merge_lora.py:202
                    INFO     dim: [64], alpha: [32.0]                                                  merge_lora.py:203
                    INFO     calculating hashes and creating metadata...                               merge_lora.py:281
                    INFO     saving model to: C:                                                       merge_lora.py:300
Traceback (most recent call last):
  File "D:\kohya_ss\sd-scripts\networks\merge_lora.py", line 360, in <module>
    merge(args)
  File "D:\kohya_ss\sd-scripts\networks\merge_lora.py", line 301, in merge
    save_to_file(args.save_to, state_dict, state_dict, save_dtype, metadata)
  File "D:\kohya_ss\sd-scripts\networks\merge_lora.py", line 39, in save_to_file
    torch.save(model, file_name)
  File "D:\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 618, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "D:\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 492, in _open_zipfile_writer
    return container(name_or_buffer)
  File "D:\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 463, in __init__
    super().__init__(torch._C.PyTorchFileWriter(self.name))
RuntimeError: File C: cannot be opened.
14:05:19-469568 INFO     Done merging...

**Comment by koppimashin** [comment]
[> --save_to "D:/kohya_ss/outputs"
> If I recall correctly this parameter should be a file name, not a directory?
> So something like --save_to "D:/kohya_ss/outputs/my-new-merged-model.safetensors"](
https://www.reddit.com/r/StableDiffusion/comments/1bwb2u9/comment/ky4xbob/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

**Comment by koppimashin** [comment]
> save_to "D:/kohya_ss/outputs"
> If I recall correctly this parameter should be a file name, not a directory?
> So something like --save_to "D:/kohya_ss/outputs/my-new-merged-model.safetensors"

`<blockquote class="reddit-embed-bq" data-embed-height="315"><a href="https://www.reddit.com/r/StableDiffusion/comments/1bwb2u9/comment/ky4xbob/">[Comment](https://www.reddit.com/r/StableDiffusion/comments/1bwb2u9/comment/ky4xbob/)</a><br> by<a href="https://www.reddit.com/user/DrySupermarket8830/">[u/DrySupermarket8830](https://www.reddit.com/user/DrySupermarket8830/)</a> from discussion<a href="https://www.reddit.com/r/[StableDiffusion](https://www.reddit.com/r/StableDiffusion/)/comments/1bwb2u9/cant_open_the_save_directory_im_merging_lora_with/"><no value=""></no></a><br> in<a href="https://www.reddit.com/r/StableDiffusion/">StableDiffusion</a></blockquote><script async="" src="https://embed.reddit.com/widgets.js" charset="UTF-8"></script>`
