### ISSUE TITLE
Resume from saved training state: error launching

### ISSUE THREAD

**Issue by rafstahelin** [bmaltais/kohya_ss#2216]
not sure why this is happening with resume from saved training state (path to last state)

Here's the error message when i tried to resume training:
```
Traceback (most recent call last):
  File "/workspace/kohya_ss/sd-scripts/sdxl_train.py", line 817, in <module>
    train(args)
  File "/workspace/kohya_ss/sd-scripts/sdxl_train.py", line 451, in train
    train_util.resume_from_local_or_hf_if_specified(accelerator, args)
  File "/workspace/kohya_ss/sd-scripts/library/train_util.py", line 3704, in resume_from_local_or_hf_if_specified
    accelerator.load_state(args.resume)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 2861, in load_state
    load_accelerator_state(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/checkpointing.py", line 212, in load_accelerator_state
    optimizer_state = torch.load(input_optimizer_file, map_location=map_location)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/serialization.py", line 993, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
```
Any thoughts as to why this is happening?

**Comment by bmaltais** [comment]
This appear to be an issue with the sd-scripts python code. You might want to open an issue about it on kohya sd-script repo…
