### ISSUE TITLE
Query: Is WD14 image tagging broken until smilingwolfv3 is implemented?

### ISSUE THREAD

**Issue by sukhysall** [bmaltais/kohya_ss#2226]
Hi

I just pulled down latest Kohya_ss as of 8th April 2024. (V23.1.1)

Went straight to image tagging and got the following error which is attributed from what I can see to the fact that the tool doesn't like the older keras format (did I get that right?)

Anyhow, here's the error log:

10:36:44-029056 INFO     Kohya_ss GUI version: v23.1.1
10:36:44-447615 INFO     Submodule initialized and updated.
10:36:44-448615 INFO     nVidia toolkit detected
10:36:45-523345 INFO     Torch 2.1.2+cu118
10:36:45-546351 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8905
10:36:45-547851 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9) Cores 128
10:36:45-550351 INFO     Python version is 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
10:36:45-551351 INFO     Verifying modules installation status from requirements_pytorch_windows.txt...
10:36:45-552851 INFO     Verifying modules installation status from requirements_windows.txt...
10:36:45-554351 INFO     Verifying modules installation status from requirements.txt...
10:36:48-876075 INFO     headless: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
10:39:18-880554 INFO     Captioning files in D:/#AI...
10:39:18-881553 INFO     accelerate launch "D:\Program_Files_AI\kohya_ss/sd-scripts/finetune/tag_images_by_wd14_tagger.py" --batch_size=8 --caption_extension=".txt" --caption_separator=", "
                         --character_threshold=0.35 --debug --frequency_tags --general_threshold=0.35 --max_data_loader_n_workers="2" --remove_underscore --repo_id="SmilingWolf/wd-v1-4-convnextv2-tagger-v2"
                         "D:/#AI"
2024-04-08 10:39:23.524094: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-08 10:39:23.963934: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
2024-04-08 10:39:25 INFO     using existing wd14 tagger model                                                                                                                    tag_images_by_wd14_tagger.py:111
Traceback (most recent call last):
  File "D:\Program_Files_AI\kohya_ss\sd-scripts\finetune\tag_images_by_wd14_tagger.py", line 514, in <module>
    main(args)
  File "D:\Program_Files_AI\kohya_ss\sd-scripts\finetune\tag_images_by_wd14_tagger.py", line 165, in main
    model = load_model(f"{model_location}")
  File "D:\Program_Files_AI\kohya_ss\venv\lib\site-packages\keras\src\saving\saving_api.py", line 191, in load_model
    raise ValueError(
ValueError: File format not supported: filepath=wd14_tagger_model\SmilingWolf_wd-v1-4-convnextv2-tagger-v2. Keras 3 only supports V3 `.keras` files and legacy H5 format files (`.h5` extension). Note that the legacy SavedModel format is not supported by `load_model()` in Keras 3. In order to reload a TensorFlow SavedModel as an inference-only layer in Keras 3, use `keras.layers.TFSMLayer(wd14_tagger_model\SmilingWolf_wd-v1-4-convnextv2-tagger-v2, call_endpoint='serving_default')` (note that your `call_endpoint` might have a different name).
Traceback (most recent call last):
  File "C:\Users\sukhy\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sukhy\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Program_Files_AI\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\Program_Files_AI\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\Program_Files_AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "D:\Program_Files_AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\Program_Files_AI\\kohya_ss\\venv\\Scripts\\python.exe', 'D:\\Program_Files_AI\\kohya_ss/sd-scripts/finetune/tag_images_by_wd14_tagger.py', '--batch_size=8', '--caption_extension=.txt', '--caption_separator=, ', '--character_threshold=0.35', '--debug', '--frequency_tags', '--general_threshold=0.35', '--max_data_loader_n_workers=2', '--remove_underscore', '--repo_id=SmilingWolf/wd-v1-4-convnextv2-tagger-v2', 'D:/#AI']' returned non-zero exit status 1.
10:39:25-740760 INFO     ...captioning done

**Comment by bmaltais** [comment]
The latest version of wd14 appear to only work with onnx checked. You also have to force download the model.

**Comment by sukhysall** [comment]
thanks. will try short.y

**Comment by FarAwaytarget** [comment]
I also encountered this problem. Is there any solution to the forced download?

**Comment by bmaltais** [comment]
You can use the option in the GUI, there is a chackbox for it:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/15cf9194-8669-4dfd-a4e7-2c0869181e7f)
