### ISSUE TITLE
%1 is not a valid win32 application

### ISSUE THREAD

**Issue by Loser02** [bmaltais/kohya_ss#2229]
sooo im getting this error: Traceback (most recent call last):
  File "C:\ai\kohya\kohya_ss\kohya_gui.py", line 4, in <module>
    from kohya_gui.class_gui_config import KohyaSSGUIConfig
  File "C:\ai\kohya\kohya_ss\kohya_gui\class_gui_config.py", line 2, in <module>
    from .common_gui import scriptdir
  File "C:\ai\kohya\kohya_ss\kohya_gui\common_gui.py", line 1, in <module>
    from tkinter import filedialog, Tk
  File "C:\Users\loope\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: DLL load failed while importing _tkinter: %1 is not a valid Win32 application.

**Comment by bmaltais** [comment]
Make sure to install the python.org version of Python as per the link provided in the README.md
