### ISSUE TITLE
module not found error while using dadaptation

### ISSUE THREAD

**Issue by DoguCatto** [bmaltais/kohya_ss#226]
I have pip installed dadaptation still get this error : Traceback (most recent call last):
  File "C:\kohya\kohya_ss\library\train_util.py", line 1606, in get_optimizer
    import dadaptation
ModuleNotFoundError: No module named 'dadaptation'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\kohya\kohya_ss\train_network.py", line 498, in <module>
    train(args)
  File "C:\kohya\kohya_ss\train_network.py", line 151, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "C:\kohya\kohya_ss\library\train_util.py", line 1608, in get_optimizer
    raise ImportError("No dadaptation / dadaptation がインストールされていないようです")
ImportError: No dadaptation / dadaptation がインストールされていないようです
Traceback (most recent call last):
  File "C:\Users\ROHIT\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ROHIT\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=E:/SD2/new web-ui/stable-diffusion-webui/stable-diffusion-webui/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt', '--train_data_dir=E:/SD2/gens/training/sgome69/selena', '--resolution=512,512', '--output_dir=E:/SD2/gens/training/sgome69/lora', '--logging_dir=E:/SD2/gens/training/sgome69/logs', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=Selena_3', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--train_batch_size=2', '--max_train_steps=2500', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=DAdaptation', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by martianunlimited** [comment]
Make sure you run 
`.\venv\Scripts\activate`
BEFORE you do 
`pip install dadaptation`

**Comment by bmaltais** [comment]
I have updated the requirements.txt file. Try doind an upgrade.ps1 and all should work.
