### ISSUE TITLE
Seed parameter empty leads to error

### ISSUE THREAD

**Issue by bjspi** [bmaltais/kohya_ss#2289]
Hi,
I'm using the DEV branch and just got this error when leaving the Parameter-field "seed" empty (which is as per default):

```
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "/workspace/kohya_ss/kohya_gui/dreambooth_gui.py", line 838, in train_model
    "seed": int(seed),
ValueError: invalid literal for int() with base 10: ''
```

This was no problem yesterday evening when I pulled the dev branch.
But I had seen this behavior earlier for other optional (!) fields as well, like the "Save every N steps" fields. If you leave it empty instead of entering "0",it leads to an abort/error.

Could you change the code so that an empty field is considered as "0" and doesnt lead to an error?

Thanks!

**Comment by bmaltais** [comment]
That is my goal. I need to address the compatibility with older config files… but I want to convert all those… starting with seed :-)

**Comment by bmaltais** [comment]
I have pushed an update to the `dev` branch that will convert all "string" form numbers to the proper `int` or `float`. Let me know how it goes.
