### ISSUE TITLE
New Bug in Dev-Branch

### ISSUE THREAD

**Issue by bjspi** [bmaltais/kohya_ss#2290]
Hi bmaltais,

yesterday it still worked on the dev branch - but some new commit seems to have introduced this new bug - not 100% sure where it is coming from, maybe a missing typecast of the accumulation parameter?

```
Traceback (most recent call last):
  File "/workspace/kohya_ss/sd-scripts/sdxl_train.py", line 818, in <module>
    train(args)
  File "/workspace/kohya_ss/sd-scripts/sdxl_train.py", line 454, in train
    num_update_steps_per_epoch = math.ceil(len(train_dataloader) / args.gradient_accumulation_steps)
TypeError: unsupported operand type(s) for /: 'int' and 'str'
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
```

In my GUI on Runpod, Gradient accumulate steps is set to 1. So I guess `args.gradient_accumulation_steps` needs to be converted to int, but not sure.

Could you have a look please?

Thanks

**Comment by bmaltais** [comment]
This is add... not sure why the gradio value is not properly taken as an int... probably due to how gradio is passing values to function... I will set it to an int and push to dev. Give it a try. Thank you for reporting the bugs you found. I spent a LOT of time rewriting how the GUI is passing values to sd-scripts via a toml config for better security and some bugs are bound to be discovered ;-)

**Comment by yesidobyte1** [comment]
My dev branch is updated to the most recent commit and I am still experiencing this error.

**Comment by yesidobyte1** [comment]
I have the dev branch updated and it is still erroring at the Accelerator step. 
`
Traceback (most recent call last):
  File "/notebooks/kohya_ss/sd-scripts/sdxl_train.py", line 818, in <module>
    train(args)
  File "/notebooks/kohya_ss/sd-scripts/sdxl_train.py", line 202, in train
    accelerator = train_util.prepare_accelerator(args)
  File "/notebooks/kohya_ss/sd-scripts/library/train_util.py", line 4305, in prepare_accelerator
    accelerator = Accelerator(
  File "/notebooks/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 450, in __init__
    raise ValueError(err.format(mode="bf16", requirement="PyTorch >= 1.10 and a supported device."))
ValueError: bf16 mixed precision requires PyTorch >= 1.10 and a supported device.
Traceback (most recent call last):
  File "/notebooks/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/notebooks/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/notebooks/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/notebooks/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/notebooks/kohya_ss/venv/bin/python', '/notebooks/kohya_ss/sd-scripts/sdxl_train.py', '--config_file', './outputs/tmpfiledbooth.toml', '--max_grad_norm=0.0', '--no_half_vae', '--train_text_encoder', '--learning_rate_te2=0', '--max_data_loader_n_workers', '0']' returned non-zero exit status 1.`

**Comment by bmaltais** [comment]
Can you try without you custom arguments? I see you are passing a bunch that should simply be set in the GUI. Does it make a difference?

Can you share the config file so I can try it on my system?

**Comment by bmaltais** [comment]
I tried to reproduce the issue but I have not been able to. Sharing your config file will allow me to use the same parameters as you and hopefully reproduce the error...

**Comment by yesidobyte1** [comment]
[24GB_TextEncoder.json](https://github.com/bmaltais/kohya_ss/files/14985334/24GB_TextEncoder.json)

It is the config file from ione of Furkan Gözükara's tutorials, I didn't catch that the custom arguments were settings I could use instead. But here is the file I have been using.

**Comment by bmaltais** [comment]
I tried the config file as it on windows and it worked flawlesly..:

```
D:\kohya gui> .\gui.bat --use_shell
20:24:47-619591 INFO     Kohya_ss GUI version: v24.0.0
20:24:48-101928 INFO     Submodule initialized and updated.
20:24:48-101928 INFO     nVidia toolkit detected
20:24:49-684315 INFO     Torch 2.1.2+cu118
20:24:49-712448 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8905
20:24:49-714924 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24576 Arch (8, 6) Cores 82
20:24:49-719921 INFO     Python version is 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
20:24:49-720920 INFO     Verifying modules installation status from requirements_pytorch_windows.txt...
20:24:49-723930 INFO     Verifying modules installation status from requirements_windows.txt...
20:24:49-725922 INFO     Verifying modules installation status from requirements.txt...
20:24:54-352857 INFO     headless: False
20:24:54-394828 INFO     Using shell=True when running external commands...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
21:04:29-393459 INFO     Loading config...
21:04:29-566851 INFO     SDXL model selected. Setting sdxl parameters
21:06:08-077618 INFO     Start training Dreambooth...
21:06:08-078619 INFO     Validating model file or folder path stabilityai/stable-diffusion-xl-base-1.0 existence...
21:06:08-080125 INFO     ...valid
21:06:08-081130 INFO     Validating output_dir path D:/kohya gui/outputs existence...
21:06:08-081130 INFO     ...valid
21:06:08-082638 INFO     Validating train_data_dir path D:/kohya gui/test/img existence...
21:06:08-084648 INFO     ...valid
21:06:08-085644 INFO     reg_data_dir not specified, skipping validation
21:06:08-086645 INFO     Validating logging_dir path D:/kohya gui/outputs\log existence...
21:06:08-087646 INFO     ...created folder at D:/kohya gui/outputs\log
21:06:08-088643 INFO     log_tracker_config not specified, skipping validation
21:06:08-089645 INFO     resume not specified, skipping validation
21:06:08-090711 INFO     vae not specified, skipping validation
21:06:08-092724 INFO     dataset_config not specified, skipping validation
21:06:08-093719 INFO     Folder 10_darius kawasaki person : steps 80
21:06:08-094721 INFO     max_train_steps (80 / 1 / 1 * 8 * 1) = 640
21:06:08-095721 INFO     stop_text_encoder_training = 0
21:06:08-096721 INFO     lr_warmup_steps = 0
21:06:08-098720 INFO     Saving training config to D:/kohya gui/outputs\24GB_TextEncoder_20240415-210608.json...
21:06:08-100783 INFO     Executing command: D:\kohya gui\venv\Scripts\accelerate.EXE launch --dynamo_backend no --dynamo_mode default --mixed_precision bf16 --num_processes 1 --num_machines 1
                         --num_cpu_threads_per_process 4 D:/kohya gui/sd-scripts/sdxl_train.py --config_file ./outputs/tmpfiledbooth.toml --max_grad_norm=0.0 --no_half_vae --train_text_encoder
                         --learning_rate_te2=0 --max_data_loader_n_workers 0 with shell=True
21:06:08-110304 INFO     Command executed.
2024-04-15 21:06:16 WARNING  A matching Triton is not available, some optimizations will not be enabled.                                                                                            __init__.py:55
                             Error caught was: No module named 'triton'                                                                                                                                           
2024-04-15 21:06:21 INFO     Loading settings from ./outputs/tmpfiledbooth.toml...                                                                                                              train_util.py:3744
                    INFO     ./outputs/tmpfiledbooth                                                                                                                                            train_util.py:3763
                    WARNING  clip_skip will be unexpected / SDXL学習ではclip_skipは動作しません                                                                                             sdxl_train_util.py:343
2024-04-15 21:06:21 INFO     prepare tokenizers                                                                                                                                             sdxl_train_util.py:134
                    INFO     update token length: 75                                                                                                                                        sdxl_train_util.py:159
                    INFO     Using DreamBooth method.                                                                                                                                            sdxl_train.py:144
                    INFO     prepare images.                                                                                                                                                    train_util.py:1572
                    INFO     found directory D:\kohya gui\test\img\10_darius kawasaki person contains 8 image files                                                                             train_util.py:1519
                    INFO     80 train images with repeating.                                                                                                                                    train_util.py:1613
                    INFO     0 reg images.                                                                                                                                                      train_util.py:1616
                    WARNING  no regularization images / 正則化画像が見つかりませんでした                                                                                                        train_util.py:1621
                    INFO     [Dataset 0]                                                                                                                                                        config_util.py:565
                               batch_size: 1                                                                                                                                                                      
                               resolution: (1024, 1024)                                                                                                                                                           
                               enable_bucket: False                                                                                                                                                               
                               network_multiplier: 1.0                                                                                                                                                            
                                                                                                                                                                                                                  
                               [Subset 0 of Dataset 0]                                                                                                                                                            
                                 image_dir: "D:\kohya gui\test\img\10_darius kawasaki person"                                                                                                                     
                                 image_count: 8                                                                                                                                                                   
                                 num_repeats: 10                                                                                                                                                                  
                                 shuffle_caption: False                                                                                                                                                           
                                 keep_tokens: 0                                                                                                                                                                   
                                 keep_tokens_separator:                                                                                                                                                           
                                 secondary_separator: None                                                                                                                                                        
                                 enable_wildcard: False                                                                                                                                                           
                                 caption_dropout_rate: 0.0                                                                                                                                                        
                                 caption_dropout_every_n_epoches: 0                                                                                                                                               
                                 caption_tag_dropout_rate: 0.0                                                                                                                                                    
                                 caption_prefix: None                                                                                                                                                             
                                 caption_suffix: None                                                                                                                                                             
                                 color_aug: False                                                                                                                                                                 
                                 flip_aug: False                                                                                                                                                                  
                                 face_crop_aug_range: None                                                                                                                                                        
                                 random_crop: False                                                                                                                                                               
                                 token_warmup_min: 1,                                                                                                                                                             
                                 token_warmup_step: 0,                                                                                                                                                            
                                 is_reg: False                                                                                                                                                                    
                                 class_tokens: darius kawasaki person                                                                                                                                             
                                 caption_extension: .txt                                                                                                                                                          
                                                                                                                                                                                                                  
                                                                                                                                                                                                                  
                    INFO     [Dataset 0]                                                                                                                                                        config_util.py:571
                    INFO     loading image sizes.                                                                                                                                                train_util.py:853
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 1293.99it/s] 
                    INFO     prepare dataset                                                                                                                                                     train_util.py:861
                    INFO     prepare accelerator                                                                                                                                                 sdxl_train.py:201
accelerator device: cuda
                    INFO     loading model for process 0/1                                                                                                                                   sdxl_train_util.py:30
                    INFO     load Diffusers pretrained models: stabilityai/stable-diffusion-xl-base-1.0, variant=None                                                                        sdxl_train_util.py:84
model_index.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 609/609 [00:00<?, ?B/s]
text_encoder/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 565/565 [00:00<?, ?B/s]
scheduler/scheduler_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 479/479 [00:00<?, ?B/s]
tokenizer_2/special_tokens_map.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 460/460 [00:00<?, ?B/s] 
tokenizer_2/merges.txt: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 525k/525k [00:00<00:00, 28.6MB/s] 
text_encoder_2/config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 575/575 [00:00<?, ?B/s] 
tokenizer_2/tokenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 725/725 [00:00<?, ?B/s] 
unet/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.68k/1.68k [00:00<00:00, 1.79MB/s]
tokenizer_2/vocab.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.06M/1.06M [00:00<00:00, 49.5MB/s] 
vae/config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 642/642 [00:00<?, ?B/s] 
diffusion_pytorch_model.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 335M/335M [00:07<00:00, 41.9MB/s]
model.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 492M/492M [00:17<00:00, 28.6MB/s] 
diffusion_pytorch_model.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 335M/335M [00:23<00:00, 14.3MB/s]
model.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.78G/2.78G [01:01<00:00, 44.9MB/s] 
diffusion_pytorch_model.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10.3G/10.3G [03:44<00:00, 45.8MB/s]
Fetching 15 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [03:44<00:00, 15.00s/it]
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:09<00:00,  1.60s/it]
2024-04-15 21:10:17 INFO     U-Net converted to original U-Net                                                                                                                              sdxl_train_util.py:120
Disable Diffusers' xformersetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 10.3G/10.3G [03:43<00:00, 48.0MB/s]
2024-04-15 21:10:18 INFO     [Dataset 0]                                                                                                                                                        train_util.py:2079
                    INFO     caching latents.                                                                                                                                                    train_util.py:974
                    INFO     checking cache validity...                                                                                                                                          train_util.py:984
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 138.56it/s] 
                    INFO     caching latents...                                                                                                                                                 train_util.py:1021
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:04<00:00,  1.61it/s] 
enable text encoder training
train unet: True, text_encoder1: True, text_encoder2: False
number of models: 2
number of trainable parameters: 2690524164
prepare optimizer, data loader etc.
2024-04-15 21:10:24 INFO     use Adafactor optimizer | {'scale_parameter': False, 'relative_step': False, 'warmup_init': False, 'weight_decay': 0.01}                                           train_util.py:4047
                    WARNING  constant_with_warmup will be good / スケジューラはconstant_with_warmupが良いかもしれません                                                                         train_util.py:4079
enable full bf16 training.
running training / 学習開始
  num examples / サンプル数: 80
  num batches per epoch / 1epochのバッチ数: 80
  num epochs / epoch数: 8
  batch size per device / バッチサイズ: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 640
steps:   0%|                                                                                                                                                                             | 0/640 [00:00<?, ?it/s] 
epoch 1/8
steps:   1%|█▍                                                                                                                                                   | 6/640 [00:15<27:38,  2.62s/it, avr_loss=0.121]21:10:43-204110 INFO     The running process has been terminated.
21:10:43-522525 INFO     Training has ended.
```

I used the latest code from the `dev` branch... Try it... maybe the recent updates I made fixed the issue?

**Comment by bmaltais** [comment]
So really odd... it work for me on windows without any complain... Not sure what cause it to error out... I will try to run it in my WSL2 ubuntu Linux Env to compare...

OK... somehow it is failing hard on Linux... really puzzling...

**Comment by bmaltais** [comment]
OK, I think I have nailed the fix. Sort of a mix of old way of running process and auto setting shell=True for posix systems...

```
git fetch origin
git checkout dev
git pull
```

**Comment by yesidobyte1** [comment]
BOOM! You rock :) 

I got to the training steps - I have to leave for work so couldn't test it thoroughly, but seems like it's good to go. THANK YOU!
