### ISSUE TITLE
tkinter.create issue on a new install when using "prepare training data"

### ISSUE THREAD

**Issue by phuc-aviatrix** [bmaltais/kohya_ss#2296]
Getting this issue on a new install. Tried with headless and with out inbrowser, various combinations.  Accelertor config set to this machine,  no, no , all, etc. 

Startup info:

pqa@pqa-sd:~/ai/kohya_ss$ ./gui.sh --listen 0.0.0.0 --inbrowser
10:34:20-889218 INFO     Kohya_ss GUI version: v23.1.5                                                                  
10:34:20-927715 INFO     Submodule initialized and updated.                                                             
10:34:20-928509 INFO     nVidia toolkit detected                                                                        
10:34:21-871890 INFO     Torch 2.1.2+cu118                                                                              
10:34:21-887233 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700                                                     
10:34:21-901207 INFO     Torch detected GPU: NVIDIA GeForce RTX 4070 VRAM 12009 Arch (8, 9) Cores 46                    
10:34:21-904147 INFO     Python version is 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]                           
10:34:21-904894 INFO     Verifying modules installation status from /home/pqa/ai/kohya_ss/requirements_linux.txt...     
10:34:21-906994 INFO     Verifying modules installation status from requirements.txt...                                 
10:34:25-415209 INFO     headless: False                                                                                
Running on local URL:  http://0.0.0.0:7860
system ubuntu 22.04.4 lts, 

Error produce while using Prepare training data:

Traceback (most recent call last):
  File "/home/pqa/ai/kohya_ss/venv/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/pqa/ai/kohya_ss/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 235, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/pqa/ai/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1627, in process_api
    result = await self.call_function(
  File "/home/pqa/ai/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1173, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/pqa/ai/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/pqa/ai/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/home/pqa/ai/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/pqa/ai/kohya_ss/venv/lib/python3.10/site-packages/gradio/utils.py", line 690, in wrapper
    response = f(*args, **kwargs)
  File "/home/pqa/ai/kohya_ss/kohya_gui/dreambooth_folder_creation_gui.py", line 48, in dreambooth_folder_preparation
    msgbox("Instance prompt missing...")
  File "/home/pqa/ai/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/derived_boxes.py", line 230, in msgbox
    return buttonbox(msg=msg,
  File "/home/pqa/ai/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 95, in buttonbox
    bb = ButtonBox(
  File "/home/pqa/ai/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 147, in __init__
    self.ui = GUItk(msg, title, choices, images, default_choice, cancel_choice, self.callback_ui)
  File "/home/pqa/ai/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 263, in __init__
    self.boxRoot = tk.Tk()
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by phuc-aviatrix** [comment]
230  git fetch origin
  231  git checkout dev
  232  git pull
  233  ll
  234  cat '=13.7.1' 
  235  mv '=13.7.1' verbak
  236  git checkout dev
  237  git pull
  238  ./gui.sh --listen 0.0.0.0 

****
11:28:22-207629 INFO     Copy /home/pqa/ai/m77 to /home/pqa/ai/m77o/img/50_mech77 person...      
11:28:22-224404 INFO     Regularization images directory is missing... not copying regularisation
                         images...                                                               
11:28:22-225196 INFO     Done creating kohya_ss training folder structure at /home/pqa/ai/m77o...

****
working as needed. Thank you so much!!!
