### ISSUE TITLE
Problem with the latest dev is that it has a fixed value of Epoch 0 and 0 steps.

### ISSUE THREAD

**Issue by CRCODE22** [bmaltais/kohya_ss#2305]
override steps. steps for 0 epochs is / 指定エポックまでのステップ数: 0
running training / 学習開始
num train images * repeats / 学習画像の数×繰り返し回数: 390
num reg images / 正則化画像の数: 0
num batches per epoch / 1epochのバッチ数: 195
num epochs / epoch数: 0
batch size per device / バッチサイズ: 2
gradient accumulation steps / 勾配を合計するステップ数 = 1
total optimization steps / 学習ステップ数: 0
steps: 0it [00:00, ?it/s]
saving checkpoint: K:/AI/Training/Dataset/test_woman_v1/model\test_woman_sd_xl_base_1280_1280_64_32_v1.safetensors
2024-04-17 05:30:45 INFO model saved. train_network.py:999
steps: 0it [00:03, ?it/s]

This is the settings it should be using:

05:27:00-143872 INFO log_tracker_config not specified, skipping validation
05:27:00-144880 INFO resume not specified, skipping validation
05:27:00-145879 INFO vae not specified, skipping validation
05:27:00-146881 INFO lora_network_weights not specified, skipping validation
05:27:00-148881 INFO dataset_config not specified, skipping validation
05:27:00-150881 INFO Folder 2_test_woman woman: 195 images found
05:27:00-152391 INFO Folder 2_test_woman woman: 390 steps
05:27:00-153908 INFO Total steps: 390
05:27:00-154916 INFO Train batch size: 2
05:27:00-155916 INFO Gradient accumulation steps: 1
05:27:00-157915 INFO Epoch: 12
05:27:00-158915 INFO Regulatization factor: 1
05:27:00-159916 INFO max_train_steps (390 / 2 / 1 * 12 * 1) = 2340
05:27:00-160916 INFO stop_text_encoder_training = 0
05:27:00-163432 INFO lr_warmup_steps = 0
05:27:00-164952 INFO Saving training config to K:/AI/Training/Dataset/test_woman_v1/model\test_woman_v1_20240417-052700.json...

**Comment by CRCODE22** [comment]
Git checkout dev solved the above issue but caused another issue:

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 195/195 [00:00<00:00, 2581.97it/s]
                    INFO     caching latents...                                                                                                                                                                                                                                                          train_util.py:1021
  0%|                                                                                                                                                                                                                                                                                             | 0/188 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "K:\kohya_ss\sd-scripts\sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "K:\kohya_ss\sd-scripts\train_network.py", line 272, in train
    train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
  File "K:\kohya_ss\sd-scripts\library\train_util.py", line 2080, in cache_latents
    dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)
  File "K:\kohya_ss\sd-scripts\library\train_util.py", line 1023, in cache_latents
    cache_batch_latents(vae, cache_to_disk, batch, subset.flip_aug, subset.random_crop)
  File "K:\kohya_ss\sd-scripts\library\train_util.py", line 2416, in cache_batch_latents
    latents = vae.encode(img_tensors).latent_dist.sample().to("cpu")
  File "K:\kohya_ss\venv\lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "K:\kohya_ss\venv\lib\site-packages\diffusers\models\autoencoders\autoencoder_kl.py", line 260, in encode
    h = self.encoder(x)
  File "K:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "K:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "K:\kohya_ss\venv\lib\site-packages\diffusers\models\autoencoders\vae.py", line 172, in forward
    sample = down_block(sample)
  File "K:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "K:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "K:\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 1323, in forward
    hidden_states = resnet(hidden_states, temb=None, scale=scale)
  File "K:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "K:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "K:\kohya_ss\venv\lib\site-packages\diffusers\models\resnet.py", line 258, in forward
    output_tensor = (input_tensor + hidden_states) / self.output_scale_factor
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 400.00 MiB. GPU 0 has a total capacty of 16.00 GiB of which 12.91 GiB is free. Of the allocated memory 1.89 GiB is allocated by PyTorch, and 47.76 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "E:\anaconda3\envs\kohya_ss\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\anaconda3\envs\kohya_ss\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "K:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "K:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "K:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "K:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['K:\\kohya_ss\\venv\\Scripts\\python.exe', 'K:/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', './outputs/tmpfilelora.toml']' returned non-zero exit status 1.

That above error is solved by unchecking cache latents and unchecking cache latents to disk

VRAM usage is abnormal compared to versions of Kohya_SS lets say from one month or two months ago. it is using 16GB VRAM with batch size 1 when in the past I could easily run batch size of 4 and only use 15GB VRAM.

**Comment by CRCODE22** [comment]
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 390
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 390
  num epochs / epoch数: 10
  batch size per device / バッチサイズ: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 3900
steps:   0%|                                                                                                                                                                                                                                                                                     | 0/3900 [00:00<?, ?it/s]
epoch 1/10
steps:   1%|██▎                                                                                                                                                                                                                                                       | 37/3900 [04:32<7:54:53,  7.38s/it, avr_loss=0.121]

I wonder if it will crash again once it completes 1 epoch like last time I will know once I have slept.
