### ISSUE TITLE
Version 24.0.1 not working on RunPod

### ISSUE THREAD

**Issue by ashleykleynhans** [bmaltais/kohya_ss#2308]
```
root@ffca3b61e554:/workspace# tail -f /workspace/logs/kohya_ss.log
13:49:32-732072 INFO     Verifying modules installation status from
                         /workspace/kohya_ss/requirements_runpod.txt...
13:49:32-734521 INFO     Verifying modules installation status from
                         requirements.txt...
13:49:36-768123 INFO     headless: True
13:49:36-817894 INFO     Using shell=True when running external commands...
Running on local URL:  http://0.0.0.0:3001

To create a public link, set `share=True` in `launch()`.
13:52:17-869644 INFO     Loading config...
13:53:18-907435 INFO     Copy /workspace/example-dataset to
                         /workspace/trained/img/40_ohwx man...
13:53:18-912946 INFO     Regularization images directory is missing... not
                         copying regularisation images...
13:53:18-915853 INFO     Done creating kohya_ss training folder structure at
                         /workspace/trained...
13:53:27-686121 INFO     Start training Dreambooth...
13:53:27-689042 INFO     Validating model file or folder path
                         runwayml/stable-diffusion-v1-5 existence...
13:53:27-692001 INFO     ...huggingface.co model, skipping validation
13:53:27-694182 INFO     Validating output_dir path /workspace/trained/model
                         existence...
13:53:27-696599 INFO     ...valid
13:53:27-698642 INFO     Validating train_data_dir path /workspace/trained/img
                         existence...
13:53:27-699667 INFO     ...valid
13:53:27-700343 INFO     reg_data_dir not specified, skipping validation
13:53:27-701084 INFO     Validating logging_dir path /workspace/trained/log
                         existence...
13:53:27-701959 INFO     ...valid
13:53:27-702645 INFO     log_tracker_config not specified, skipping validation
13:53:27-703384 INFO     resume not specified, skipping validation
13:53:27-704092 INFO     vae not specified, skipping validation
13:53:27-704795 INFO     dataset_config not specified, skipping validation
13:53:27-705540 INFO     Headless mode, skipping verification if model already
                         exist... if model already exist it will be
                         overwritten...
13:53:27-706584 INFO     Folder 40_ohwx man: 40 repeats found
13:53:27-707388 INFO     Folder 40_ohwx man: 10 images found
13:53:27-708136 INFO     Folder 40_ohwx man: 10 * 40 = 400 steps
13:53:27-708939 INFO     Regulatization factor: 1
13:53:27-709699 INFO     Total steps: 400
13:53:27-710405 INFO     Train batch size: 1
13:53:27-711123 INFO     Gradient accumulation steps: 1
13:53:27-711861 INFO     Epoch: 5
13:53:27-712544 INFO     max_train_steps (400 / 1 / 1 * 5 * 1) = 2000
13:53:27-713479 INFO     lr_warmup_steps = 200
13:53:27-714585 INFO     Saving training config to
                         /workspace/trained/model/example_20240417-135327.json..
                         .
13:53:27-715826 INFO     Executing command:
                         "/workspace/kohya_ss/venv/bin/accelerate" launch
                         --dynamo_backend no --dynamo_mode default
                         --mixed_precision fp16 --num_processes 1 --num_machines
                         1 --num_cpu_threads_per_process 2
                         "/workspace/kohya_ss/sd-scripts/train_db.py"
                         --config_file "./outputs/tmpfiledbooth.toml" with
                         shell=True
13:53:27-717847 INFO     Command executed.
2024-04-17 13:53:32.126903: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-17 13:53:32.126952: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-17 13:53:32.126971: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-17 13:53:32.131897: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-17 13:53:34 INFO     Loading settings from            train_util.py:3744
                             ./outputs/tmpfiledbooth.toml...
                    INFO     ./outputs/tmpfiledbooth          train_util.py:3763
2024-04-17 13:53:34 INFO     prepare tokenizer                train_util.py:4227
tokenizer_config.json: 100%|██████████| 905/905 [00:00<00:00, 4.13MB/s]
vocab.json: 100%|██████████| 961k/961k [00:00<00:00, 8.83MB/s]
merges.txt: 100%|██████████| 525k/525k [00:00<00:00, 2.30MB/s]
special_tokens_map.json: 100%|██████████| 389/389 [00:00<00:00, 2.47MB/s]
tokenizer.json: 100%|██████████| 2.22M/2.22M [00:00<00:00, 3.98MB/s]
2024-04-17 13:53:37 INFO     update token length: 75          train_util.py:4244
                    INFO     prepare images.                  train_util.py:1572
                    INFO     found directory                  train_util.py:1519
                             /workspace/trained/img/40_ohwx
                             man contains 10 image files
                    WARNING  No caption file found for 10     train_util.py:1550
                             images. Training will continue
                             without captions for these
                             images. If class token exists,
                             it will be used. /
                             10枚の画像にキャプションファイル
                             が見つかりませんでした。これらの
                             画像についてはキャプションなしで
                             学習を続行します。class
                             tokenが存在する場合はそれを使い
                             ます。
                    WARNING  /workspace/trained/img/40_ohwx   train_util.py:1557
                             man/IMG_20220701_190434536_HDR.j
                             pg
                    WARNING  /workspace/trained/img/40_ohwx   train_util.py:1557
                             man/IMG_20230118_152709446.jpg
                    WARNING  /workspace/trained/img/40_ohwx   train_util.py:1557
                             man/IMG_20230118_152845680_MP.jp
                             g
                    WARNING  /workspace/trained/img/40_ohwx   train_util.py:1557
                             man/IMG_20230118_152943787.jpg
                    WARNING  /workspace/trained/img/40_ohwx   train_util.py:1557
                             man/IMG_20230118_154016992_MP.jp
                             g
                    WARNING  /workspace/trained/img/40_ohwx   train_util.py:1555
                             man/IMG_20230118_154049852.jpg..
                             . and 5 more
                    INFO     400 train images with repeating. train_util.py:1613
                    INFO     0 reg images.                    train_util.py:1616
                    WARNING  no regularization images /       train_util.py:1621
                             正則化画像が見つかりませんでした
                    INFO     [Dataset 0]                      config_util.py:565
                               batch_size: 1
                               resolution: (512, 512)
                               enable_bucket: True
                               network_multiplier: 1.0
                               min_bucket_reso: 256
                               max_bucket_reso: 2048
                               bucket_reso_steps: 64
                               bucket_no_upscale: True

                               [Subset 0 of Dataset 0]
                                 image_dir:
                             "/workspace/trained/img/40_ohwx
                             man"
                                 image_count: 10
                                 num_repeats: 40
                                 shuffle_caption: False
                                 keep_tokens: 0
                                 keep_tokens_separator:
                                 secondary_separator: None
                                 enable_wildcard: False
                                 caption_dropout_rate: 0
                                 caption_dropout_every_n_epoc
                             hes: 0
                                 caption_tag_dropout_rate:
                             0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 is_reg: False
                                 class_tokens: ohwx man
                                 caption_extension: .caption


                    INFO     [Dataset 0]                      config_util.py:571
                    INFO     loading image sizes.              train_util.py:853
100%|██████████| 10/10 [00:00<00:00, 46448.55it/s]
                    INFO     make buckets                      train_util.py:859
                    WARNING  min_bucket_reso and               train_util.py:876
                             max_bucket_reso are ignored if
                             bucket_no_upscale is set, because
                             bucket reso is defined by image
                             size automatically /
                             bucket_no_upscaleが指定された場合
                             は、bucketの解像度は画像サイズか
                             ら自動計算されるため、min_bucket_
                             resoとmax_bucket_resoは無視されま
                             す
                    INFO     number of images (including       train_util.py:905
                             repeats) /
                             各bucketの画像枚数（繰り返し回数
                             を含む）
                    INFO     bucket 0: resolution (512, 512),  train_util.py:910
                             count: 400
                    INFO     mean ar error (without repeats):  train_util.py:915
                             0.0
                    INFO     prepare accelerator                 train_db.py:106
accelerator device: cuda
                    INFO     loading model for process 0/1    train_util.py:4385
                    INFO     load Diffusers pretrained        train_util.py:4347
                             models:
                             runwayml/stable-diffusion-v1-5
model_index.json: 100%|██████████| 541/541 [00:00<00:00, 2.72MB/s]
scheduler/scheduler_config.json: 100%|██████████| 308/308 [00:00<00:00, 3.63MB/s]
vae/config.json: 100%|██████████| 547/547 [00:00<00:00, 4.78MB/s]<?, ?B/s]
text_encoder/config.json: 100%|██████████| 617/617 [00:00<00:00, 3.45MB/s]?B/s]
unet/config.json: 100%|██████████| 743/743 [00:00<00:00, 4.43MB/s]
(…)ature_extractor/preprocessor_config.json: 100%|██████████| 342/342 [00:00<00:00, 1.92MB/s]
diffusion_pytorch_model.safetensors: 100%|██████████| 335M/335M [00:08<00:00, 38.7MB/s]]
model.safetensors: 100%|██████████| 492M/492M [00:11<00:00, 42.1MB/s]8<00:00, 45.3MB/s]
diffusion_pytorch_model.safetensors: 100%|██████████| 3.44G/3.44G [00:39<00:00, 87.0MB/s]
Fetching 9 files: 100%|██████████| 9/9 [00:39<00:00,  4.44s/it]G [00:11<01:06, 43.9MB/s]
Loading pipeline components...: 100%|██████████| 5/5 [00:00<00:00, 14.37it/s]0, 109MB/s]
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
2024-04-17 13:54:19 INFO     UNet2DConditionModel: 64, 8,  original_unet.py:1387
                             768, False, False
2024-04-17 13:54:25 INFO     U-Net converted to original      train_util.py:4372
                             U-Net
                    INFO     [Dataset 0]                      train_util.py:2079
                    INFO     caching latents.                  train_util.py:974
                    INFO     checking cache validity...        train_util.py:984
100%|██████████| 10/10 [00:00<00:00, 277768.48it/s]
                    INFO     caching latents...               train_util.py:1021
100%|██████████| 10/10 [00:02<00:00,  4.81it/s]
prepare optimizer, data loader etc.
2024-04-17 13:54:28 INFO     use 8-bit AdamW optimizer | {}   train_util.py:3889
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 400
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 400
  num epochs / epoch数: 5
  batch size per device / バッチサイズ: 1
  total train batch size (with parallel & distributed & accumulation) / 総バッチサイズ（並列学習、勾配合計含む）: 1
  gradient ccumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 2000
steps:   0%|          | 0/2000 [00:00<?, ?it/s]
epoch 1/5
Traceback (most recent call last):
  File "/workspace/kohya_ss/sd-scripts/train_db.py", line 529, in <module>
    train(args)
  File "/workspace/kohya_ss/sd-scripts/train_db.py", line 343, in train
    encoder_hidden_states = train_util.get_hidden_states(
  File "/workspace/kohya_ss/sd-scripts/library/train_util.py", line 4426, in get_hidden_states
    encoder_hidden_states = enc_out["hidden_states"][-args.clip_skip]
TypeError: bad operand type for unary -: 'str'
steps:   0%|          | 0/2000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/workspace/kohya_ss/venv/bin/python3', '/workspace/kohya_ss/sd-scripts/train_db.py', '--config_file', './outputs/tmpfiledbooth.toml']' returned non-zero exit status 1.
13:54:30-317493 INFO     Training has ended.
```

**Comment by Melodycloudu** [comment]
When I had this error switching to dev fixed it for me.. 
`git fetch origin
git pull
git checkout dev`
hope this helps

**Comment by bmaltais** [comment]
What clip_skip value do you use? I checked the toml file created on my computer and it is a proper number... not sure why this would not work on runpod

**Comment by ashleykleynhans** [comment]
> What clip_skip value do you use? I checked the toml file created on my computer and it is a proper number... not sure why this would not work on runpod

<img width="356" alt="Monosnap vim 2024-04-17 18-31-32" src="https://github.com/bmaltais/kohya_ss/assets/886709/0b5334bc-9779-42c0-85d0-ff2544add784">

I imported a previously saved JSON file and it is indeed a string, I'll set it to an int value and try again tomorrow, thanks!

**Comment by bmaltais** [comment]
OK... perhaps the import code does not convert that value to an int... I will check... should be an easy fix... I hope... do you see any other numbers that are between ""? If so, I need to handle those also.

**Comment by bmaltais** [comment]
What is the content of the generated toml file in the outputs folder? Is clip_skip between "" ? The import code should have changed it to an int...

**Comment by bmaltais** [comment]
I wonder if this is not a bug in kohya's code... He already ingest clip_skip as an int... so even passing it as a string should not cause it to be treated as a string... this might have nothing to do with the GUI...

**Comment by ashleykleynhans** [comment]
> I wonder if this is not a bug in kohya's code... He already ingest clip_skip as an int... so even passing it as a string should not cause it to be treated as a string... this might have nothing to do with the GUI... but who knows... Using a toml file for parameters is new... so maybe something is not aligning right... The content of your toml file should help figure it out... Would be nice if you shared it.

I don't have a pod running at the moment, I will share the toml file tomorrow.

In the meantime, this is my JSON file:
```json
{
  "adaptive_noise_scale": 0,
  "additional_parameters": "",
  "bucket_no_upscale": true,
  "bucket_reso_steps": 64,
  "cache_latents": true,
  "cache_latents_to_disk": false,
  "caption_dropout_every_n_epochs": 0.0,
  "caption_dropout_rate": 0,
  "caption_extension": "",
  "clip_skip": "1",
  "color_aug": false,
  "enable_bucket": true,
  "epoch": 5,
  "flip_aug": false,
  "full_bf16": false,
  "full_fp16": false,
  "gpu_ids": "",
  "gradient_accumulation_steps": "1",
  "gradient_checkpointing": false,
  "keep_tokens": "0",
  "learning_rate": 1e-06,
  "learning_rate_te": 1e-06,
  "learning_rate_te1": 1e-06,
  "learning_rate_te2": 1e-06,
  "logging_dir": "/workspace/trained/log",
  "lr_scheduler": "constant_with_warmup",
  "lr_scheduler_args": "",
  "lr_scheduler_num_cycles": "",
  "lr_scheduler_power": "",
  "lr_warmup": "10",
  "max_bucket_reso": 2048,
  "max_data_loader_n_workers": "0",
  "max_resolution": "512,512",
  "max_timestep": 1000,
  "max_token_length": "75",
  "max_train_epochs": "",
  "max_train_steps": "",
  "mem_eff_attn": false,
  "min_bucket_reso": 256,
  "min_snr_gamma": 0,
  "min_timestep": 0,
  "mixed_precision": "fp16",
  "model_list": "runwayml/stable-diffusion-v1-5",
  "multi_gpu": false,
  "multires_noise_discount": 0,
  "multires_noise_iterations": 0,
  "no_token_padding": false,
  "noise_offset": 0,
  "noise_offset_type": "Original",
  "num_cpu_threads_per_process": 2,
  "num_machines": 1,
  "num_processes": 1,
  "optimizer": "AdamW8bit",
  "optimizer_args": "",
  "output_dir": "/workspace/trained/model",
  "output_name": "example",
  "persistent_data_loader_workers": false,
  "pretrained_model_name_or_path": "runwayml/stable-diffusion-v1-5",
  "prior_loss_weight": 1.0,
  "random_crop": false,
  "reg_data_dir": "",
  "resume": "",
  "sample_every_n_epochs": 1,
  "sample_every_n_steps": 0,
  "sample_prompts": "ohwx man by tomer hanuka",
  "sample_sampler": "euler_a",
  "save_every_n_epochs": 1,
  "save_every_n_steps": 0,
  "save_last_n_steps": 0,
  "save_last_n_steps_state": 0,
  "save_model_as": "safetensors",
  "save_precision": "fp16",
  "save_state": false,
  "scale_v_pred_loss_like_noise_pred": false,
  "sdxl": false,
  "seed": "420420",
  "shuffle_caption": false,
  "stop_text_encoder_training": 0,
  "train_batch_size": 1,
  "train_data_dir": "/workspace/trained/img",
  "use_wandb": true,
  "v2": false,
  "v_parameterization": false,
  "v_pred_like_loss": 0,
  "vae": "",
  "vae_batch_size": 0,
  "wandb_api_key": "24d2b70b67b3c53dcb785218dc4623076ebe4cb3",
  "weighted_captions": false,
  "xformers": false
}
```

**Comment by bmaltais** [comment]
ARG!!!!! Please delete the wandb_api_key... you left it for everyone to view and abuse!

**Comment by ashleykleynhans** [comment]
> @ashleykleynhans ARG!!!!! Please destroy that wandb_api_key... you left it for everyone to view and abuse!
> 
> This is a dreambooth? I will try it on my system... minus the api key ;-)

Sorry, just very busy at didn't have time to check the JSON.  I deleted my W&B account, thanks.

Yeah its Dreambooth with SD 1.5.

**Comment by bmaltais** [comment]
It trained fine on windows with that file... Here is the toml file that was created:

```toml
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
caption_dropout_every_n_epochs = 0
caption_dropout_rate = 0
clip_skip = 1
debiased_estimation_loss = true
dynamo_backend = "no"
enable_bucket = true
epoch = 5
gradient_accumulation_steps = 1
huber_c = 0.1
huber_schedule = "snr"
ip_noise_gamma = 0.1
ip_noise_gamma_random_strength = true
keep_tokens = 0
learning_rate = 1e-6
learning_rate_te = 1e-6
logging_dir = "D:/kohya gui/outputs/log"
loss_type = "l2"
lr_scheduler = "constant_with_warmup"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 40
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_timestep = 1000
max_token_length = 75
max_train_steps = 400
min_bucket_reso = 256
mixed_precision = "fp16"
multires_noise_discount = 0
noise_offset_random_strength = true
noise_offset_type = "Original"
optimizer_type = "AdamW8bit"
output_dir = "D:/kohya gui/outputs"
output_name = "example"
pretrained_model_name_or_path = "runwayml/stable-diffusion-v1-5"
prior_loss_weight = 1
resolution = "512,512"
sample_every_n_epochs = 1
sample_prompts = "D:/kohya gui/outputs\\prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "fp16"
seed = 420420
train_batch_size = 1
train_data_dir = "D:/kohya gui/test/img"
use_wandb = true
```

I will try in on Ubuntu...

**Comment by bmaltais** [comment]
OK, I was able to reproduce... somehow on Linux the toml is not the same as on windows:

```toml
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
caption_dropout_every_n_epochs = 0
caption_dropout_rate = 0
clip_skip = "1"
dynamo_backend = "no"
enable_bucket = true
epoch = 5
gradient_accumulation_steps = 1
huber_c = 0.1
huber_schedule = "snr"
keep_tokens = 0
learning_rate = 1e-6
learning_rate_te = 1e-6
logging_dir = "./outputs/log"
loss_type = "l2"
lr_scheduler = "constant_with_warmup"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 40
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_timestep = 1000
max_token_length = 75
max_train_steps = 400
min_bucket_reso = 256
mixed_precision = "fp16"
multires_noise_discount = 0
noise_offset_type = "Original"
optimizer_type = "AdamW8bit"
output_dir = "./outputs"
output_name = "example"
pretrained_model_name_or_path = "runwayml/stable-diffusion-v1-5"
prior_loss_weight = 1
resolution = "512,512"
sample_every_n_epochs = 1
sample_prompts = "./outputs/prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "fp16"
seed = 420420
train_batch_size = 1
train_data_dir = "./test/img"
use_wandb = true
```

So at least I can reproduce and find a platform specific fix... so odd...

**Comment by ashleykleynhans** [comment]
Thats great news, my RunPod pod only just came up so you beat me to it, thanks!

**Comment by bmaltais** [comment]
Pushed a new release with the fix.

**Comment by bjspi** [comment]
> Thanks, I am getting a different issue with 24.0.3
> 
> ```
> 2024-04-18 07:58:18 INFO     Loading settings from            train_util.py:3744
>                              ./outputs/tmpfiledbooth.toml...
>                     INFO     ./outputs/tmpfiledbooth          train_util.py:3763
> Traceback (most recent call last):
>   File "/workspace/kohya_ss/sd-scripts/train_db.py", line 529, in <module>
>     train(args)
>   File "/workspace/kohya_ss/sd-scripts/train_db.py", line 51, in train
>     train_util.verify_training_args(args)
>   File "/workspace/kohya_ss/sd-scripts/library/train_util.py", line 3473, in verify_training_args
>     raise ValueError("adaptive_noise_scale requires noise_offset / adaptive_noise_scaleを使用するにはnoise_offsetが必要です")
> ValueError: adaptive_noise_scale requires noise_offset / adaptive_noise_scaleを使用するにはnoise_offsetが必要です
> Traceback (most recent call last):
>   File "/workspace/kohya_ss/venv/bin/accelerate", line 8, in <module>
>     sys.exit(main())
>   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
>     args.func(args)
>   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
>     simple_launcher(args)
>   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
>     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
> subprocess.CalledProcessError: Command '['/workspace/kohya_ss/venv/bin/python3', '/workspace/kohya_ss/sd-scripts/train_db.py', '--config_file', './outputs/tmpfiledbooth.toml']' returned non-zero exit status 1.
> 07:58:19-844146 INFO     Training has ended.
> ```
> 
> But I don't see a way to set `noise_offset` in the GUI.

Oh, I just posted the same error, now I found this report - seems like it's the same:
https://github.com/bmaltais/kohya_ss/issues/2330#issue-2250454456

You can set the offset under the advanced parameter section.
