### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Tyosei** [bmaltais/kohya_ss#234]
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Tyo\Desktop\Kohya\kohya_ss\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\Tyo\Desktop\Kohya\kohya_ss\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\Users\Tyo\Desktop\Kohya\kohya_ss\venv\lib\site-packages\pip\_internal\commands\install.py", line 461, in run
    installed = install_given_reqs(
  File "C:\Users\Tyo\Desktop\Kohya\kohya_ss\venv\lib\site-packages\pip\_internal\req\__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "C:\Users\Tyo\Desktop\Kohya\kohya_ss\venv\lib\site-packages\pip\_internal\req\req_install.py", line 790, in install
    install_wheel(
  File "C:\Users\Tyo\Desktop\Kohya\kohya_ss\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 727, in install_wheel
    _install_wheel(
  File "C:\Users\Tyo\Desktop\Kohya\kohya_ss\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 587, in _install_wheel
    file.save()
  File "C:\Users\Tyo\Desktop\Kohya\kohya_ss\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 388, in save
    shutil.copyfileobj(f, dest)
  File "C:\Users\Tyo\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 195, in copyfileobj
    buf = fsrc_read(length)
  File "C:\Users\Tyo\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 925, in read
    data = self._read1(n)
  File "C:\Users\Tyo\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1015, in _read1
    self._update_crc(data)
  File "C:\Users\Tyo\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 943, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'torch/lib/cusolver64_11.dll'

**Comment by jeremymccurdy** [comment]
Same error here.

**Comment by wanglaofei** [comment]
I have the another problem:
![image](https://github.com/user-attachments/assets/6555d0cf-8f48-4fa3-b69a-517f4100dd28)
