### ISSUE TITLE
Cannot use betas parameter for Lora

### ISSUE THREAD

**Issue by mykeehu** [bmaltais/kohya_ss#2343]
In version 24.0.4, the argument splitter is not good, because I get an error for this parameter, which I have been able to train Lora with:
use_bias_correction=True weight_decay=0.5 d_coef=0.65 "betas=(0.9, 0.901)"

This is my error:
```
Traceback (most recent call last):
  File "I:\kohya_ss\sd-scripts\train_network.py", line 1115, in <module>
    trainer.train(args)
  File "I:\kohya_ss\sd-scripts\train_network.py", line 348, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "I:\kohya_ss\sd-scripts\library\train_util.py", line 3854, in get_optimizer
    value = ast.literal_eval(value)
  File "C:\Users\Mykee\AppData\Local\Programs\Python\Python310\lib\ast.py", line 64, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "C:\Users\Mykee\AppData\Local\Programs\Python\Python310\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    (0.9,
    ^
SyntaxError: '(' was never closed
Traceback (most recent call last):
  File "C:\Users\Mykee\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Mykee\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "I:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "I:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "I:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "I:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['I:\\kohya_ss\\venv\\Scripts\\python.exe', 'I:/kohya_ss/sd-scripts/train_network.py', '--config_file', './outputs/tmpfilelora.toml']' returned non-zero exit status 1.
```

Please fix this!

**Comment by bmaltais** [comment]
Make sure Thera are no comma between each group of parameters. Can you share the json config that cause the issue?

**Comment by mykeehu** [comment]
Here is my config, I deleted the paths:

```
{
  "LoRA_type": "Standard",
  "LyCORIS_preset": "full",
  "adaptive_noise_scale": 0,
  "additional_parameters": "",
  "block_alphas": "",
  "block_dims": "",
  "block_lr_zero_threshold": "",
  "bucket_no_upscale": true,
  "bucket_reso_steps": 64,
  "bypass_mode": false,
  "cache_latents": true,
  "cache_latents_to_disk": false,
  "caption_dropout_every_n_epochs": 0,
  "caption_dropout_rate": 0,
  "caption_extension": ".txt",
  "clip_skip": 1,
  "color_aug": false,
  "constrain": 0,
  "conv_alpha": 1,
  "conv_block_alphas": "",
  "conv_block_dims": "",
  "conv_dim": 1,
  "dataset_config": "",
  "debiased_estimation_loss": false,
  "decompose_both": false,
  "dim_from_weights": false,
  "dora_wd": false,
  "down_lr_weight": "",
  "enable_bucket": false,
  "epoch": 10,
  "extra_accelerate_launch_args": "",
  "factor": -1,
  "flip_aug": false,
  "fp8_base": false,
  "full_bf16": true,
  "full_fp16": false,
  "gpu_ids": "",
  "gradient_accumulation_steps": 1,
  "gradient_checkpointing": false,
  "huber_c": 0.1,
  "huber_schedule": "snr",
  "ip_noise_gamma": 0,
  "ip_noise_gamma_random_strength": false,
  "keep_tokens": 0,
  "learning_rate": 1,
  "log_tracker_config": "",
  "log_tracker_name": "",
  "lora_network_weights": "",
  "loss_type": "l2",
  "lr_scheduler": "cosine",
  "lr_scheduler_args": "",
  "lr_scheduler_num_cycles": "",
  "lr_scheduler_power": "",
  "lr_warmup": 0,
  "main_process_port": 0,
  "masked_loss": false,
  "max_bucket_reso": 2048,
  "max_data_loader_n_workers": "0",
  "max_grad_norm": 1,
  "max_resolution": "512,512",
  "max_timestep": 1000,
  "max_token_length": "225",
  "max_train_epochs": "",
  "max_train_steps": "",
  "mem_eff_attn": false,
  "mid_lr_weight": "",
  "min_bucket_reso": 512,
  "min_snr_gamma": 5,
  "min_timestep": 0,
  "mixed_precision": "bf16",
  "model_list": "custom",
  "module_dropout": 0,
  "multi_gpu": false,
  "multires_noise_discount": 0,
  "multires_noise_iterations": 0,
  "network_alpha": 64,
  "network_dim": 64,
  "network_dropout": 0,
  "noise_offset": 0,
  "noise_offset_random_strength": false,
  "noise_offset_type": "Original",
  "num_cpu_threads_per_process": 2,
  "num_machines": 1,
  "num_processes": 1,
  "optimizer": "Prodigy",
  "optimizer_args": "use_bias_correction=True weight_decay=0.5 d_coef=0.65 \"betas=(0.9, 0.901)\"",
  "output_name": "xxxxxx",
  "persistent_data_loader_workers": false,
  "pretrained_model_name_or_path": "M:/!SDModels/!Edzeni/realisticVisionV51_v51VAE_full.safetensors",
  "prior_loss_weight": 1,
  "random_crop": false,
  "rank_dropout": 0,
  "rank_dropout_scale": false,
  "rescaled": false,
  "resume": "",
  "sample_every_n_epochs": 1,
  "sample_every_n_steps": 0,
  "sample_prompts": "a xxxxxx woman in restaurant, upper body, red hair, realistic photo, many people in background, RAW photo, 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3 --n lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry",
  "sample_sampler": "euler_a",
  "save_as_bool": false,
  "save_every_n_epochs": 1,
  "save_every_n_steps": 0,
  "save_last_n_steps": 0,
  "save_last_n_steps_state": 0,
  "save_model_as": "safetensors",
  "save_precision": "bf16",
  "save_state": false,
  "save_state_on_train_end": false,
  "scale_v_pred_loss_like_noise_pred": false,
  "scale_weight_norms": 1,
  "sdxl": false,
  "sdxl_cache_text_encoder_outputs": false,
  "sdxl_no_half_vae": true,
  "seed": "1217930809",
  "shuffle_caption": false,
  "stop_text_encoder_training": 0,
  "text_encoder_lr": 1,
  "train_batch_size": 1,
  "train_norm": false,
  "train_on_input": true,
  "training_comment": "",
  "unet_lr": 1,
  "unit": 1,
  "up_lr_weight": "",
  "use_cp": false,
  "use_scalar": false,
  "use_tucker": false,
  "use_wandb": false,
  "v2": false,
  "v_parameterization": false,
  "v_pred_like_loss": 0,
  "vae": "",
  "vae_batch_size": 0,
  "wandb_api_key": "",
  "wandb_run_name": "",
  "weighted_captions": false,
  "xformers": "xformers"
}
```

**Comment by mykeehu** [comment]
Okay, but the parameter for betas looks like this, so I can't get around the comma: (0.9, 0.999) 
So if I need the comma, what's the solution?

**Comment by 5KilosOfCheese** [comment]
> Okay, but the parameter for betas looks like this, so I can't get around the comma: (0.9, 0.999) https://github.com/konstmish/prodigy So if I need the comma, what's the solution? I do not use toml.

`"betas=(0.9,0.99)" `
 You can't have a space in the brackets.

**Comment by bmaltais** [comment]
Hummm... might be interesting co write a validator for things like this to raise an error when the syntax does not comply with what sd-scripts expect... or maybe just to remove the offending characters... I will think about it... should not be too difficult...

**Comment by bmaltais** [comment]
The `dev` branch code will now validate the arguments and prevent starting the training if they do not comply with the needed format.

**Comment by bmaltais** [comment]
I wish kohya did. It would really be a document he should maintain.
