### ISSUE TITLE
WD14 captioning Issue with Undesired tags nor Tag Replacement

### ISSUE THREAD

**Issue by rafstahelin** [bmaltais/kohya_ss#2346]
This is the error with latest v24

Neither `Undesired tags` nor `Tag Replacement` work

```
13:37:23-372524 INFO     Executing command: "E:\kohya_ss\venv\Scripts\accelerate.EXE" launch
                         "E:/kohya_ss/sd-scripts/finetune/tag_images_by_wd14_tagger.py" --batch_size 1
                         --caption_extension .txt --caption_separator ,  --debug --frequency_tags
                         --max_data_loader_n_workers 2 --onnx --remove_underscore --repo_id
                         SmilingWolf/wd-v1-4-convnextv2-tagger-v2 --tag_replacement 1girl,woman;1boy,man;cowboy
                         shot,midshot --undesired_tags solo,male focus,nose,lips,forehead,mouth,black hair,brown
                         hair,black eyes, brown eyes,scar,scar on face,watermark,webaddress,art parody,flat chest,artist
                         name,small breasts,solo focus,breasts,closed mouth,realistic,expressionless,
                         portrait,bald,badge,parody,crossdressing,censored,character name,contrapposto,fat
                         man,ganguro,traditional media,unmoving pattern,v,what,white background, simple background,
                         monochrome, greyscale, bw, black and white "E:\studio
                         Dropbox\studio\ai\data\styles\style_lighting_graphicwhite\2datasets\new-dataset\2caption\_test"
                         with shell=True
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
usage: tag_images_by_wd14_tagger.py [-h] [--repo_id REPO_ID] [--model_dir MODEL_DIR] [--force_download]
                                    [--batch_size BATCH_SIZE] [--max_data_loader_n_workers MAX_DATA_LOADER_N_WORKERS]
                                    [--caption_extention CAPTION_EXTENTION] [--caption_extension CAPTION_EXTENSION]
                                    [--thresh THRESH] [--general_threshold GENERAL_THRESHOLD]
                                    [--character_threshold CHARACTER_THRESHOLD] [--recursive] [--remove_underscore]
                                    [--debug] [--undesired_tags UNDESIRED_TAGS] [--frequency_tags] [--onnx]
                                    [--append_tags] [--use_rating_tags] [--use_rating_tags_as_last_tag]
                                    [--character_tags_first] [--always_first_tags ALWAYS_FIRST_TAGS]
                                    [--caption_separator CAPTION_SEPARATOR] [--tag_replacement TAG_REPLACEMENT]
                                    [--character_tag_expand]
                                    train_data_dir
tag_images_by_wd14_tagger.py: error: unrecognized arguments: focus,nose,lips,forehead,mouth,black hair,brown hair,black eyes, brown eyes,scar,scar on face,watermark,webaddress,art parody,flat chest,artist name,small breasts,solo focus,breasts,closed mouth,realistic,expressionless, portrait,bald,badge,parody,crossdressing,censored,character name,contrapposto,fat man,ganguro,traditional media,unmoving pattern,v,what,white background, simple background, monochrome, greyscale, bw, black and white E:\studio Dropbox\studio\ai\data\styles\style_lighting_graphicwhite\2datasets\new-dataset\2caption\_test
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\kohya_ss\\venv\\Scripts\\python.exe', 'E:/kohya_ss/sd-scripts/finetune/tag_images_by_wd14_tagger.py', '--batch_size', '1', '--caption_extension', '.txt', '--caption_separator', ',', '--debug', '--frequency_tags', '--max_data_loader_n_workers', '2', '--onnx', '--remove_underscore', '--repo_id', 'SmilingWolf/wd-v1-4-convnextv2-tagger-v2', '--tag_replacement', '1girl,woman;1boy,man;cowboy', 'shot,midshot', '--undesired_tags', 'solo,male', 'focus,nose,lips,forehead,mouth,black', 'hair,brown', 'hair,black', 'eyes,', 'brown', 'eyes,scar,scar', 'on', 'face,watermark,webaddress,art', 'parody,flat', 'chest,artist', 'name,small', 'breasts,solo', 'focus,breasts,closed', 'mouth,realistic,expressionless,', 'portrait,bald,badge,parody,crossdressing,censored,character', 'name,contrapposto,fat', 'man,ganguro,traditional', 'media,unmoving', 'pattern,v,what,white', 'background,', 'simple', 'background,', 'monochrome,', 'greyscale,', 'bw,', 'black', 'and', 'white', 'E:\\studio Dropbox\\studio\\ai\\data\\styles\\style_lighting_graphicwhite\\2datasets\\new-dataset\\2caption\\_test']' returned non-zero exit status 2.
13:37:33-446597 INFO     ...captioning done
```

**Comment by bmaltais** [comment]
Humm... still fail with onnx on... so perhaps they have change the model location on huggingface?

**Comment by bmaltais** [comment]
Nah... it worked with onnx... just had to force redownload of model... so I will see if I can force onnx in the GUI

**Comment by rafstahelin** [comment]
I am having major issues. Never happened before with captioning on kohya.

Here's my setup 
```
 Kohya_ss GUI version: v24.0.4
13:45:43-501294 INFO     Submodule initialized and updated.
13:45:43-503294 INFO     nVidia toolkit detected
13:45:45-096780 INFO     Torch 2.1.2+cu118
13:45:45-112781 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
13:45:45-114780 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24563 Arch (8, 9) Cores 128
13:45:45-119297 INFO     Python version is 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit
                         (AMD64)]
13:45:45-120321 INFO     Verifying modules installation status from requirements_pytorch_windows.txt...
13:45:45-123315 INFO     Verifying modules installation status from requirements_windows.txt...
13:45:45-125317 INFO     Verifying modules installation status from requirements.txt...
```

```
13:46:32-677834 INFO     Captioning files in E:\studio
                         Dropbox\studio\ai\data\styles\style_lighting_graphicwhite\2datasets\new-dataset\2caption\_test.
                         ..
13:46:32-679834 INFO     Executing command: "E:\kohya_ss\venv\Scripts\accelerate.EXE" launch
                         "E:/kohya_ss/sd-scripts/finetune/tag_images_by_wd14_tagger.py" --batch_size 1
                         --caption_extension .txt --caption_separator ,  --debug --force_download --frequency_tags
                         --max_data_loader_n_workers 2 --onnx --remove_underscore --repo_id
                         SmilingWolf/wd-v1-4-convnextv2-tagger-v2 --undesired_tags solo,male
                         focus,nose,lips,forehead,mouth,black hair,brown hair,black eyes,brown eyes,scar,scar on
                         face,watermark,webaddress,art parody,flat chest,artist name,small breasts,solo
                         focus,breasts,closed
                         mouth,realistic,expressionless,portrait,bald,badge,parody,crossdressing,censored,character
                         name,contrapposto,fat man,ganguro,traditional media,unmoving pattern,v,what,white
                         background,simple background,monochrome, greyscale,bw,black and white "E:\studio
                         Dropbox\studio\ai\data\styles\style_lighting_graphicwhite\2datasets\new-dataset\2caption\_test"
                         with shell=True
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
usage: tag_images_by_wd14_tagger.py [-h] [--repo_id REPO_ID] [--model_dir MODEL_DIR] [--force_download]
                                    [--batch_size BATCH_SIZE] [--max_data_loader_n_workers MAX_DATA_LOADER_N_WORKERS]
                                    [--caption_extention CAPTION_EXTENTION] [--caption_extension CAPTION_EXTENSION]
                                    [--thresh THRESH] [--general_threshold GENERAL_THRESHOLD]
                                    [--character_threshold CHARACTER_THRESHOLD] [--recursive] [--remove_underscore]
                                    [--debug] [--undesired_tags UNDESIRED_TAGS] [--frequency_tags] [--onnx] [--append_tags]
                                    [--use_rating_tags] [--use_rating_tags_as_last_tag] [--character_tags_first]
                                    [--always_first_tags ALWAYS_FIRST_TAGS] [--caption_separator CAPTION_SEPARATOR]
                                    [--tag_replacement TAG_REPLACEMENT] [--character_tag_expand]
                                    train_data_dir
tag_images_by_wd14_tagger.py: error: unrecognized arguments: hair,brown hair,black eyes,brown eyes,scar,scar on face,watermark,webaddress,art parody,flat chest,artist name,small breasts,solo focus,breasts,closed mouth,realistic,expressionless,portrait,bald,badge,parody,crossdressing,censored,character name,contrapposto,fat man,ganguro,traditional media,unmoving pattern,v,what,white background,simple background,monochrome, greyscale,bw,black and white E:\studio Dropbox\studio\ai\data\styles\style_lighting_graphicwhite\2datasets\new-dataset\2caption\_test
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\kohya_ss\\venv\\Scripts\\python.exe', 'E:/kohya_ss/sd-scripts/finetune/tag_images_by_wd14_tagger.py', '--batch_size', '1', '--caption_extension', '.txt', '--caption_separator', ',', '--debug', '--force_download', '--frequency_tags', '--max_data_loader_n_workers', '2', '--onnx', '--remove_underscore', '--repo_id', 'SmilingWolf/wd-v1-4-convnextv2-tagger-v2', '--undesired_tags', 'solo,male', 'focus,nose,lips,forehead,mouth,black', 'hair,brown', 'hair,black', 'eyes,brown', 'eyes,scar,scar', 'on', 'face,watermark,webaddress,art', 'parody,flat', 'chest,artist', 'name,small', 'breasts,solo', 'focus,breasts,closed', 'mouth,realistic,expressionless,portrait,bald,badge,parody,crossdressing,censored,character', 'name,contrapposto,fat', 'man,ganguro,traditional', 'media,unmoving', 'pattern,v,what,white', 'background,simple', 'background,monochrome,', 'greyscale,bw,black', 'and', 'white', 'E:\\studio Dropbox\\studio\\ai\\data\\styles\\style_lighting_graphicwhite\\2datasets\\new-dataset\\2caption\\_test']' returned non-zero exit status 2.
13:46:42-890786 INFO     ...captioning done
```
![image](https://github.com/bmaltais/kohya_ss/assets/64715158/e28f2851-26eb-4fd6-a2c8-8f3db9f4ccb4)

**Comment by rafstahelin** [comment]
the model download was fixed by going back to v23, downloading, then back to v24... where now neither undesired nor tag replacement works. And getting the above error

**Comment by rafstahelin** [comment]
it doesnt recognise arguments `undesired tags` and `Image folder`

Why?

**Comment by rafstahelin** [comment]
also is this the correct way to replace?

`1girl,woman;1boy,man;cowboy shot,midshot`
 As in girl1 will be replaced by woman?

Thanks

**Comment by bmaltais** [comment]
I did not wrote the tagger code but I think this is how they documented the way to swap the values

**Comment by rafstahelin** [comment]
ok. not working either

**Comment by rafstahelin** [comment]
another issue i am having is, i am running wd14 with Append Tags with an existing caption txt file. After about 10 images, the process errors out

```
                             /model.onnx
2024-04-19 14:35:25 INFO     found 200 images.                                          tag_images_by_wd14_tagger.py:220
  0%|                                                                                          | 0/200 [00:00<?, ?it/s]A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
  6%|████▊                                                                            | 12/200 [00:39<10:23,  3.32s/it]
Traceback (most recent call last):
  File "E:\kohya_ss\sd-scripts\finetune\tag_images_by_wd14_tagger.py", line 514, in <module>
    main(args)
  File "E:\kohya_ss\sd-scripts\finetune\tag_images_by_wd14_tagger.py", line 364, in main
    run_batch(b_imgs)
  File "E:\kohya_ss\sd-scripts\finetune\tag_images_by_wd14_tagger.py", line 310, in run_batch
    existing_content = f.read().strip("\n")  # Remove newlines
  File "C:\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 111: invalid continuation byte
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\kohya_ss\\venv\\Scripts\\python.exe', 'E:\\kohya_ss/sd-scripts/finetune/tag_images_by_wd14_tagger.py', '--append_tags', '--batch_size=1', '--caption_extension=.txt', '--caption_separator=, ', '--character_threshold=0.25', '--frequency_tags', '--general_threshold=0.25', '--max_data_loader_n_workers=2', '--onnx', '--remove_underscore', '--repo_id=SmilingWolf/wd-v1-4-convnextv2-tagger-v2', 'E:\\studio Dropbox\\studio\\ai\\data\\styles\\style_lighting_graphicwhite\\2datasets\\new-dataset\\2caption\\wd14']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "E:\kohya_ss\venv\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\kohya_ss\venv\lib\site-packages\gradio\route_utils.py", line 235, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1627, in process_api
    result = await self.call_function(
  File "E:\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1173, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "E:\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "E:\kohya_ss\venv\lib\site-packages\gradio\utils.py", line 690, in wrapper
    response = f(*args, **kwargs)
  File "E:\kohya_ss\kohya_gui\wd14_caption_gui.py", line 100, in caption_images
    add_pre_postfix(
  File "E:\kohya_ss\kohya_gui\common_gui.py", line 684, in add_pre_postfix
    content = f.read().rstrip()
  File "C:\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 111: invalid continuation byte
```

Unusable

**Comment by rafstahelin** [comment]
I am going to move over to comfyui for captioning till this is worked out

**Comment by rafstahelin** [comment]
i was fine with how it was before in Kohya. Just need it to work :-)

**Comment by bmaltais** [comment]
Try it again in the `dev` branch:

```
git fetch origin
git checkout dev
git pull
```

kohya's sd-scripts have been updated so I had to add a bunch of new options to get it to work... and this might lead to new bugs... I hope the new version work better now... it should.

**Comment by rafstahelin** [comment]
> Try it again in the `dev` branch:
> 
> ```
> git fetch origin
> git checkout dev
> git pull
> ```
> 
> kohya's sd-scripts have been updated so I had to add a bunch of new options to get it to work... and this might lead to new bugs... I hope the new version work better now... it should.

Yup its all working now in dev! Please merge

**Comment by bmaltais** [comment]
I will merge to master when I push the next release... hopefully tonight.
