### ISSUE TITLE
SDXL lora fraining failling before completion

### ISSUE THREAD

**Issue by hungryformelons** [bmaltais/kohya_ss#2363]
After some hours training a SDXL lora, the training fail itself after some hours of training:

steps:  33%|█████████████████                                  | 2711/8100 [1:59:29<3:57:31,  2.64s/it, avr_loss=0.105]Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "A:\AI\SD\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "A:\AI\SD\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "A:\AI\SD\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "A:\AI\SD\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['A:\\AI\\SD\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'A:/AI/SD/Kohya/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', './outputs/tmpfilelora.toml', '--optimizer_args', 'weight_decay=0.01', 'd_coef=1', 'use_bias_correction=True', 'safeguard_warmup=False', 'betas=0.9,0.99']' returned non-zero exit status 3221225477.
04:49:47-372639 INFO     Training has ended.

These are the configs i was using:
![Screenshot 2024-04-21 110105](https://github.com/bmaltais/kohya_ss/assets/129033306/4faf52ab-15c9-438d-a53b-4e5efe00f822)

**Comment by hungryformelons** [comment]
![Screenshot 2024-04-21 110637](https://github.com/bmaltais/kohya_ss/assets/129033306/fc24cac4-62dd-4b95-b42a-abc7ad1e7b9d)

**Comment by bmaltais** [comment]
What is the error message when it fail? Can you copy the full text? The screen capture does not show what is happening.

**Comment by hungryformelons** [comment]
The screen captures only shows the configs, the error message itself i copypasted. The training stopped after 33% shortly after saving the first checkpoint.

**Comment by bmaltais** [comment]
Maybe it can’t properly write to that location? I could possibly try to write a temp file there to test and if the GUI can’t write the file I could wand the user… This would spare wasting time training the checkpoint to only discover it can’t be written to…
