### ISSUE TITLE
Can't merge Lora anymore.. Don't know why

### ISSUE THREAD

**Issue by Aurety** [bmaltais/kohya_ss#2365]
Hello, since two days, Can't merge Lora anymore.. Don't know why ? It result the same error.. Any Idea ?

20:16:08-341973 INFO     Merge model...
20:16:08-345976 INFO     Executing command: "G:\KohyaSS\kohya_ss\venv\Scripts\python.exe"
                         "G:/KohyaSS/kohya_ss/sd-scripts/networks/sdxl_merge_lora.py" --sd_model
                         "G:/Automatic_1111/stable-diffusion-webui/models/Stable-diffusion/_CHINOOK_0.9_45.fp16.safeten
                         sors" --save_precision fp16 --precision float --save_to
                         "G:/Automatic_1111/stable-diffusion-webui/models/Stable-diffusion/_CHINOOK_0.9_46.fp16.safeten
                         sors" --models G:/Automatic_1111/stable-diffusion-webui/models/Lora/1604/inferno.safetensors
                         G:/Automatic_1111/stable-diffusion-webui/models/Lora/1604/XL_World_of_Warcraft_Elf_Knight.safe
                         tensors G:/Automatic_1111/stable-diffusion-webui/models/Lora/1604/abslandsdxl.safetensors
                         G:/Automatic_1111/stable-diffusion-webui/models/Lora/1604/dvr-mthng-sdxl.safetensors --ratios
                         0.35 0.25 0.35 0.34 with shell=False
2024-04-21 20:16:28 WARNING  A matching Triton is not available, some optimizations will not be enabled. __init__.py:55
                             Error caught was: No module named 'triton'
2024-04-21 20:16:32 INFO     loading SD model:                                                   sdxl_merge_lora.py:249
                             G:/Automatic_1111/stable-diffusion-webui/models/Stable-diffusion/_C
                             HINOOK_0.9_45.fp16.safetensors
                    INFO     building U-Net                                                      sdxl_model_util.py:192
2024-04-21 20:16:33 INFO     loading U-Net from checkpoint                                       sdxl_model_util.py:196
2024-04-21 20:16:35 INFO     U-Net: <All keys matched successfully>                              sdxl_model_util.py:202
                    INFO     building text encoders                                              sdxl_model_util.py:205
                    INFO     loading text encoders from checkpoint                               sdxl_model_util.py:258
2024-04-21 20:16:36 INFO     text encoder 1: <All keys matched successfully>                     sdxl_model_util.py:272
                    INFO     convert_sdxl_text_encoder_2_checkpoint: convert                     sdxl_model_util.py:137
                             text_projection.weight.weight to text_projection.weight
Traceback (most recent call last):
  File "G:\KohyaSS\kohya_ss\sd-scripts\networks\sdxl_merge_lora.py", line 351, in <module>
    merge(args)
  File "G:\KohyaSS\kohya_ss\sd-scripts\networks\sdxl_merge_lora.py", line 258, in merge
    ) = sdxl_model_util.load_models_from_sdxl_checkpoint(sdxl_model_util.MODEL_VERSION_SDXL_BASE_V1_0, args.sd_model, "cpu")
  File "G:\KohyaSS\kohya_ss\sd-scripts\library\sdxl_model_util.py", line 275, in load_models_from_sdxl_checkpoint
    info2 = _load_state_dict_on_device(text_model2, converted_sd, device=map_location)  # remain fp32
  File "G:\KohyaSS\kohya_ss\sd-scripts\library\sdxl_model_util.py", line 163, in _load_state_dict_on_device
    raise RuntimeError("Error(s) in loading state_dict for {}:\n\t{}".format(model.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CLIPTextModelWithProjection:
        Unexpected key(s) in state_dict: "text_model.encoder.text_projection.weight".
20:16:38-235072 INFO     Done merging...

**Comment by efhosci** [comment]
Can also confirm this is broken, same with the "resize LoRA" utility. Here's the output for running that:

`8:19:10-408428 INFO     Executing command:                                     
                         "/home/stuart/kohya_ss/kohya_ss/venv/bin/python"       
                         "/home/stuart/kohya_ss/kohya_ss/sd-scripts/networks/res
                         ize_lora.py" --save_precision fp16 --save_to           
                         "/media/hdd1/SD/training/models/salamence_resized.safet
                         ensors" --model                                        
                         "/media/hdd1/SD/training/models/salamence.safetensors" 
                         --new_rank 16 --device cuda --dynamic_method sv_fro    
                         --dynamic_param 0.9 --verbose with shell=False         
Traceback (most recent call last):
  File "/home/stuart/kohya_ss/kohya_ss/venv/lib/python3.10/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/home/stuart/kohya_ss/kohya_ss/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/stuart/kohya_ss/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "/home/stuart/kohya_ss/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/stuart/kohya_ss/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/stuart/kohya_ss/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/home/stuart/kohya_ss/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/stuart/kohya_ss/kohya_ss/venv/lib/python3.10/site-packages/gradio/utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "/home/stuart/kohya_ss/kohya_ss/kohya_gui/resize_lora_gui.py", line 105, in resize_lora
    subprocess.run(command_to_run, env=env, shell=use_shell)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '"/home/stuart/kohya_ss/kohya_ss/venv/bin/python" "/home/stuart/kohya_ss/kohya_ss/sd-scripts/networks/resize_lora.py" --save_precision fp16 --save_to "/media/hdd1/SD/training/models/salamence_resized.safetensors" --model "/media/hdd1/SD/training/models/salamence.safetensors" --new_rank 16 --device cuda --dynamic_method sv_fro --dynamic_param 0.9 --verbose'`

I'm not certain exactly what's going on here, but it looks like it might be trying to interpret the entire launch argument as a file path?

**Comment by Aurety** [comment]
Any advice ? It's hard to work on a modele and stuck in the middle of process.. For information, I tried with some other models than mine and it works sometimes.. I don't know what is different and how I can find a workaround to fix that.. Thanks again for your hard work ! Kohya_SS is incredible..

**Comment by Aurety** [comment]
I'm not an expert unfortunatly but I think this is a problem with the size of the modele I tried to merge.. I use extension supermerger to merge my models and the size is very different as expected ( 3,371 Go ) instead ( 6,675 Go ). It works with the 6,675.. So nothing to wrong with Kohya_SS so forgive me !! Now I have to figure why Supermerger reduce my SDXL modele like this !!
