### ISSUE TITLE
Problems with LoRA traning 

### ISSUE THREAD

**Issue by iemskl** [bmaltais/kohya_ss#2376]
Hi everybody! I found this instructions and take all arguments from video https://www.youtube.com/watch?v=y2J7EZUk_a0 I double checked all  but can't start LoRA training with the next error:
```
prepare optimizer, data loader etc.
Traceback (most recent call last):
  File "C:\git_proj\kohya_ss\sd-scripts\sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "C:\git_proj\kohya_ss\sd-scripts\train_network.py", line 348, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "C:\git_proj\kohya_ss\sd-scripts\library\train_util.py", line 3854, in get_optimizer
    value = ast.literal_eval(value)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\ast.py", line 64, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 0

SyntaxError: invalid syntax
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\python.exe',
 'C:\\git_proj\\kohya_ss/sd-scripts/sdxl_train_network.py', '--bucket_no_upscale', '--bucket_reso_steps=64', '--cache_latents',
 '--cache_latents_to_disk', '--caption_extension=.txt', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', 
'--gradient_checkpointing', '--huber_c=0.1', '--huber_schedule=snr', '--learning_rate=0.0003', 
'--logging_dir=C:/git_proj/kohya_ss/dataset/log', '--loss_type=l2', '--lr_scheduler=constant', '--lr_scheduler_num_cycles=12', 
'--max_data_loader_n_workers=0', '--max_grad_norm=1', '--resolution=1024,1024', '--max_train_steps=15840', 
'--min_timestep=0', '--mixed_precision=bf16', '--network_alpha=1', '--network_dim=8', '--network_module=networks.lora', 
'--optimizer_args', 'scale_parameter=', 'False', 'relative_step=False', 'warmup_init=False', '--optimizer_type=Adafactor', 
'--output_dir=C:/git_proj/kohya_ss/dataset/model', '--output_name=Alexa_Gonzales-Gal_Gadot',
 '--pretrained_model_name_or_path=C:/git_proj/kohya_ss/models/rsmpornxlEmbraceTheSuck_v081Beta.safetensors',
 '--reg_data_dir=C:/git_proj/kohya_ss/dataset\\reg', '--save_every_n_epochs=2', '--save_model_as=safetensors',
 '--save_precision=bf16', '--train_batch_size=1', '--train_data_dir=C:/git_proj/kohya_ss/dataset/img',
 '--xformers', '--sample_sampler=euler_a', '--sample_prompts=C:/git_proj/kohya_ss/dataset/model\\sample\\prompt.txt',
 '--sample_every_n_epochs=5']' returned non-zero exit status 1.
```

What could be the launch problem?

**Comment by iemskl** [comment]
My bad... "scale_parameter= False relative_step=False warmup_init=False" I wrote an extra space where it shouldn't have been
