### ISSUE TITLE
Error when starting LoRa training: FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

### ISSUE THREAD

**Issue by ptrprkrz** [bmaltais/kohya_ss#2392]
Traceback (most recent call last):
  File "C:\Users\x\Desktop\kohya\kohya_ss\venv\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\x\Desktop\kohya\kohya_ss\venv\lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\x\Desktop\kohya\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "C:\Users\x\Desktop\kohya\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\x\Desktop\kohya\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\x\Desktop\kohya\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\Users\x\Desktop\kohya\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Users\x\Desktop\kohya\kohya_ss\venv\lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\x\Desktop\kohya\kohya_ss\kohya_gui\lora_gui.py", line 1220, in train_model
    SaveConfigFile(
  File "C:\Users\x\Desktop\kohya\kohya_ss\kohya_gui\common_gui.py", line 1251, in SaveConfigFile
    os.makedirs(os.path.dirname(folder_path))
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

I’ve been looking for a solution for a while, reinstalled python and deleted venv but didn’t help.

**Comment by ptrprkrz** [comment]
Forgive me! I figured it out, I just hadn’t picked a location for the model to output to… 🤦‍♂️
