### ISSUE TITLE
LR Scheduler adafactor help needed (Kohya_ss GUI template on Runpod/ashleykza/kohya:24.0.6) 

### ISSUE THREAD

**Issue by dwarfstar5** [bmaltais/kohya_ss#2394]
Getting this error when training Lora using LR Scheduler adafactor with Optimizer Adafactor.  Not sure if I’m making a mistake or if this is a bug.  Should I not be using adafactor Scheduler with Adafactor Optimizer? Or is the issue something else? 

Appreciate any insight anyone may have,

Traceback (most recent call last):
  File "/workspace/kohya_ss/sd-scripts/sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "/workspace/kohya_ss/sd-scripts/train_network.py", line 376, in train
    lr_scheduler = train_util.get_scheduler_fix(args, optimizer, accelerator.num_processes)
  File "/workspace/kohya_ss/sd-scripts/library/train_util.py", line 4155, in get_scheduler_fix
    initial_lr = float(name.split(":")[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/workspace/kohya_ss/venv/bin/python3', '/workspace/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', './outputs/tmpfilelora.toml']' returned non-zero exit status 1.
11:25:08-585356 INFO     Training has ended.

**Comment by bmaltais** [comment]
can you share the json config file so I can try to reproduce it?

**Comment by dwarfstar5** [comment]
Here's the file:

[Roy2_V1.4C_20240426-102855.json](https://github.com/bmaltais/kohya_ss/files/15138577/Roy2_V1.4C_20240426-102855.json)

I tried again today with this same config on version 24.0.8 on runpod, and got the same error.  Does the adafactor LR scheduler need any extra arguments, as we do with Adafactor Optimizer ie..."scale_parameter=False relative_step=False warmup_init=False"

I'm not quite clear how the adafactor LR scheduler is intended to be used.

Thanks for looking into this bmaltais

**Comment by ttait-vantim** [comment]
See this issue for patch:
https://github.com/bmaltais/kohya_ss/issues/1419#issuecomment-1694876051
