### ISSUE TITLE
Resume training from LyCORIS

### ISSUE THREAD

**Issue by Haoming02** [bmaltais/kohya_ss#2411]
Does **LyCORIS/LoHa** currently support **Network weights** `(Path to an existing LoRA network weights to resume training from)`?

When I try to continue training one, it throws the following:

```bash
2024-04-29 08:25:49|[LyCORIS]-INFO: Create LyCORIS Module
2024-04-29 08:25:49|[LyCORIS]-INFO: Create LyCORIS Module
2024-04-29 08:25:49|[LyCORIS]-INFO: create LyCORIS for Text Encoder: 264 modules.
2024-04-29 08:25:49|[LyCORIS]-INFO: Create LyCORIS Module
2024-04-29 08:25:49|[LyCORIS]-INFO: create LyCORIS for U-Net: 788 modules.
2024-04-29 08:25:49|[LyCORIS]-INFO: module type table: {'LoConModule': 1052}
Traceback (most recent call last):
  File "C:\Users\admin\Documents\GitHub\kohya_ss\sd-scripts\sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "C:\Users\admin\Documents\GitHub\kohya_ss\sd-scripts\train_network.py", line 293, in train
    network, _ = network_module.create_network_from_weights(1, args.network_weights, vae, text_encoder, unet, **net_kwargs)
  File "C:\Users\admin\Documents\GitHub\kohya_ss\venv\lib\site-packages\lycoris\kohya\__init__.py", line 214, in create_network_from_weights
    module = make_module(lyco_type, params, lora_name, orig_modules)
  File "C:\Users\admin\Documents\GitHub\kohya_ss\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\admin\Documents\GitHub\kohya_ss\venv\lib\site-packages\lycoris\modules\__init__.py", line 29, in make_module
    w1a, w1b, w2a, w2b, t1, t2, alpha = params
ValueError: too many values to unpack (expected 7)
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\Documents\GitHub\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\admin\Documents\GitHub\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\admin\Documents\GitHub\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\Users\admin\Documents\GitHub\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\admin\\Documents\\GitHub\\kohya_ss\\venv\\Scripts\\python.exe', 'C:/Users/admin/Documents/GitHub/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', './outputs/tmpfilelora.toml']' returned non-zero exit status 1.
08:25:51-985218 INFO     Training has ended.
```

- **GUI:** `v24.0.8`

**Comment by bmaltais** [comment]
Maybe I am doing something wrong when passing the args but I doubt. I think you might want to reach out to @KohakuBlueleaf to see what he think... his repo is at https://github.com/KohakuBlueleaf/LyCORIS
