### ISSUE TITLE
Errors while trying to run setup.bat

### ISSUE THREAD

**Issue by lideborg** [bmaltais/kohya_ss#2421]
Getting this error while trying to install. Same error when execturing the file as well as from terminal. Any idea on how to fix?

`PS C:\Users\hampu> git clone --recursive https://github.com/bmaltais/kohya_ss.git
fatal: destination path 'kohya_ss' already exists and is not an empty directory.
PS C:\Users\hampu> cd kohya_ss
PS C:\Users\hampu\kohya_ss> .\setup.bat
C:\Users\hampu\kohya_ss\setup\setup_windows.py:251: SyntaxWarning: invalid escape sequence '\g'
  "start cmd /k .\gui.bat --inbrowser", shell=True
Traceback (most recent call last):
  File "C:\Users\hampu\kohya_ss\setup\setup_windows.py", line 7, in <module>
    import setup_common
  File "C:\Users\hampu\kohya_ss\setup\setup_common.py", line 8, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
PS C:\Users\hampu\kohya_ss>`

**Comment by bmaltais** [comment]
Make sure you delete the original kohya_ss folder. It was not able to clone the latest code because it complained that there was already a folder called kohya_ss.

**Comment by lideborg** [comment]
Thanks guys, downgrading to an earlier version of Pyhton (3.10) worked!
