### ISSUE TITLE
ValueError: persistent_workers option needs num_workers > 0

### ISSUE THREAD

**Issue by ThisIsNetsu** [bmaltais/kohya_ss#2435]
Hello! I have recently come back to kohya and have since been completely unable to start training. I have done a complete reinstall but I still get an error when trying to train:

```
Traceback (most recent call last):
  File "I:\kohya_2\kohya_ss\sd-scripts\sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "I:\kohya_2\kohya_ss\sd-scripts\train_network.py", line 354, in train
    train_dataloader = torch.utils.data.DataLoader(
  File "I:\kohya_2\kohya_ss\venv\lib\site-packages\torch\utils\data\dataloader.py", line 253, in __init__
    raise ValueError('persistent_workers option needs num_workers > 0')
ValueError: persistent_workers option needs num_workers > 0
Traceback (most recent call last):
  File "C:\Users\Jakxx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Jakxx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "I:\kohya_2\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "I:\kohya_2\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "I:\kohya_2\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "I:\kohya_2\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['I:\\kohya_2\\kohya_ss\\venv\\Scripts\\python.exe', 'I:/kohya_2/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', './outputs/config_lora-20240502-212926.toml', '--network_train_unet_only', '--zero_terminal_snr']' returned non-zero exit status 1.
21:29:49-522023 INFO     Training has ended.
```

Does anyone have any idea what I am doing wrong? Google gives exactly two results and none seem helpful :(

**Comment by bmaltais** [comment]
Try setting the persistent_data_loader_workers to something larger than 0.

**Comment by ThisIsNetsu** [comment]
> Try setting the persistent_data_loader_workers to something larger than 0.

I have found your reply on another threat. Unfortunately I have not found this option anywhere. It is perhaps an argument I need to set? I am a little at loss here where I would have to look for this.

**Comment by ThisIsNetsu** [comment]
edit: I found the option. I might be just blind. It's
"Max num workers for DataLoader
Override number of epoch. Default: 0"

For some reason the default of 0 gives me an error.
