### ISSUE TITLE
Can not train lora

### ISSUE THREAD

**Issue by firsthandlemon** [bmaltais/kohya_ss#2442]
Hi. I am very new to all the coding thing. I have issue trying to train a lora. I'd be greatly thankful if anyone can tell me what is wrong with my settings. I am using windows (idk what else info should i provide).

04:55:16-193031 INFO     Command executed.
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
2024-05-05 04:55:26 INFO     Loading settings from ./outputs/config_lora-20240505-045516.toml...      train_util.py:3744
                    INFO     ./outputs/config_lora-20240505-045516                                    train_util.py:3763
2024-05-05 04:55:26 INFO     prepare tokenizers                                                   sdxl_train_util.py:134
2024-05-05 04:55:27 INFO     update token length: 75                                              sdxl_train_util.py:159
                    INFO     Loading dataset config from C:\AI 2\2024exhibition\log                 train_network.py:161
Traceback (most recent call last):
  File "D:\AI\kohya_ss\sd-scripts\sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "D:\AI\kohya_ss\sd-scripts\train_network.py", line 162, in train
    user_config = config_util.load_user_config(args.dataset_config)
  File "D:\AI\kohya_ss\sd-scripts\library\config_util.py", line 649, in load_user_config
    raise ValueError(f"file not found / ファイルが見つかりません: {file}")
ValueError: file not found / ファイルが見つかりません: C:\AI 2\2024exhibition\log
Traceback (most recent call last):
  File "C:\Users\Voeed\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Voeed\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\AI\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "D:\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\AI\\kohya_ss\\venv\\Scripts\\python.exe', 'D:/AI/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', './outputs/config_lora-20240505-045516.toml', '--lr_scheduler_type', 'CosineAnnealingLR', '--lr_scheduler_args', 'T_max=1000', 'eta_min=0e-0']' returned non-zero exit status 1.
04:55:28-468562 INFO     Training has ended.

**Comment by RockyFong** [comment]
@firsthandlemon Hi. I have the same problem as yours. how did you solve?
