### ISSUE TITLE
Error loading state_dict for SdxlUNet2DConditionModel: Unexpected keys in state_dict

### ISSUE THREAD

**Issue by mronceray** [bmaltais/kohya_ss#2445]
Hi, I tried to do a training for a Lora on Runpod but I can't seem to start the training. I keep getting this error and I've tried several pretrained models, so I don't understand where the problem is coming from.

```
16:28:21-961387 INFO     Command executed.
2024-05-05 16:28:27.705977: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-05 16:28:27.706031: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-05 16:28:27.706049: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-05-05 16:28:27.712316: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-05 16:28:29 INFO     Loading settings from            train_util.py:3744
                             ./outputs/config_lora-20240505-1
                             62821.toml...
                    INFO     ./outputs/config_lora-20240505-1 train_util.py:3763
                             62821
2024-05-05 16:28:29 INFO     prepare tokenizers           sdxl_train_util.py:134
2024-05-05 16:28:30 INFO     update token length: 75      sdxl_train_util.py:159
                    INFO     Using DreamBooth method.       train_network.py:172
                    WARNING  ignore directory without repeats config_util.py:584
                             /
                             繰り返し回数のないディレクトリを
                             無視します: .ipynb_checkpoints
                    INFO     prepare images.                  train_util.py:1572
                    INFO     found directory                  train_util.py:1519
                             /workspace/training/maxime/img/4
                             0_maxime 1boy contains 83 image
                             files
                    INFO     3320 train images with           train_util.py:1613
                             repeating.
                    INFO     0 reg images.                    train_util.py:1616
                    WARNING  no regularization images /       train_util.py:1621
                             正則化画像が見つかりませんでした
                    INFO     [Dataset 0]                      config_util.py:565
                               batch_size: 3
                               resolution: (1024, 1024)
                               enable_bucket: True
                               network_multiplier: 1.0
                               min_bucket_reso: 256
                               max_bucket_reso: 2048
                               bucket_reso_steps: 64
                               bucket_no_upscale: False

                               [Subset 0 of Dataset 0]
                                 image_dir:
                             "/workspace/training/maxime/img/
                             40_maxime 1boy"
                                 image_count: 83
                                 num_repeats: 40
                                 shuffle_caption: False
                                 keep_tokens: 0
                                 keep_tokens_separator:
                                 secondary_separator: None
                                 enable_wildcard: False
                                 caption_dropout_rate: 0.05
                                 caption_dropout_every_n_epoc
                             hes: 0
                                 caption_tag_dropout_rate:
                             0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 is_reg: False
                                 class_tokens: maxime 1boy
                                 caption_extension: .txt


                    INFO     [Dataset 0]                      config_util.py:571
                    INFO     loading image sizes.              train_util.py:853
100%|██████████| 83/83 [00:00<00:00, 69045.46it/s]
                    INFO     make buckets                      train_util.py:859
                    INFO     number of images (including       train_util.py:905
                             repeats) /
                             各bucketの画像枚数（繰り返し回数
                             を含む）
                    INFO     bucket 0: resolution (1024,       train_util.py:910
                             1024), count: 3320
                    INFO     mean ar error (without repeats):  train_util.py:915
                             0.0
                    WARNING  clip_skip will be unexpected sdxl_train_util.py:343
                             /
                             SDXL学習ではclip_skipは動作
                             しません
                    INFO     preparing accelerator          train_network.py:225
accelerator device: cuda
                    INFO     loading model for process 0/1 sdxl_train_util.py:30
                    INFO     load StableDiffusion          sdxl_train_util.py:70
                             checkpoint:
                             /workspace/stable-diffusion-w
                             ebui/models/Stable-diffusion/
                             epicphotogasm_ultimateFidelit
                             y.safetensors
                    INFO     building U-Net               sdxl_model_util.py:192
2024-05-05 16:28:31 INFO     loading U-Net from           sdxl_model_util.py:196
                             checkpoint
Traceback (most recent call last):
  File "/workspace/kohya_ss/sd-scripts/sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "/workspace/kohya_ss/sd-scripts/train_network.py", line 234, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "/workspace/kohya_ss/sd-scripts/sdxl_train_network.py", line 44, in load_target_model
    ) = sdxl_train_util.load_target_model(args, accelerator, sdxl_model_util.MODEL_VERSION_SDXL_BASE_V1_0, weight_dtype)
  File "/workspace/kohya_ss/sd-scripts/library/sdxl_train_util.py", line 40, in load_target_model
    ) = _load_target_model(
  File "/workspace/kohya_ss/sd-scripts/library/sdxl_train_util.py", line 78, in _load_target_model
    ) = sdxl_model_util.load_models_from_sdxl_checkpoint(model_version, name_or_path, device, model_dtype)
  File "/workspace/kohya_ss/sd-scripts/library/sdxl_model_util.py", line 201, in load_models_from_sdxl_checkpoint
    info = _load_state_dict_on_device(unet, unet_sd, device=map_location, dtype=dtype)
  File "/workspace/kohya_ss/sd-scripts/library/sdxl_model_util.py", line 163, in _load_state_dict_on_device
    raise RuntimeError("Error(s) in loading state_dict for {}:\n\t{}".format(model.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SdxlUNet2DConditionModel:
        Unexpected key(s) in state_dict: "output_blocks.11.1.transformer_blocks.0.norm2.bias", "output_blocks.10.1.transformer_blocks.0.norm3.bias", "output_blocks.6.1.transformer_blocks.0.attn1.to_out.0.bias", "output_blocks.7.1.proj_out.weight", "output_blocks.7.1.transformer_blocks.0.attn1.to_out.0.weight", "output_blocks.11.1.transformer_blocks.0.norm1.bias", "output_blocks.9.1.transformer_blocks.0.attn2.to_k.weight", "output_blocks.10.0.in_layers.2.weight", "output_blocks.10.1.transformer_blocks.0.attn1.to_out.0.bias", "output_blocks.10.1.transformer_blocks.0.attn2.to_v.weight", "output_blocks.10.1.proj_out.weight", "output_blocks.8.1.transformer_blocks.0.norm1.weight", "output_blocks.9.0.in_layers.2.bias", "output_blocks.7.1.transformer_blocks.0.attn1.to_q.weight",...

Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/workspace/kohya_ss/venv/bin/python3', '/workspace/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', './outputs/config_lora-20240505-162821.toml']' returned non-zero exit status 1.
16:28:32-644132 INFO     Training has ended.
```

Thanks

**Comment by mronceray** [comment]
Finally, I succeeded by testing with other models.

**Comment by zhinangubei** [comment]
hay,what models you test succeeded?

**Comment by mronceray** [comment]
> hay,what models you test succeeded?

I have managed to start training with epicphotogasm_ultimateFidelity, however, my training parameters must not be good because I have an extremely long estimated time for a 4090
