### ISSUE TITLE
Can't merge LoRA's anymore

### ISSUE THREAD

**Issue by Asaghon** [bmaltais/kohya_ss#2463]
I had an old version of Kohya untill recently (I never updated since it worked fine for what I need)

Had to reinstall windows and reinstall Kohya and I can now not merge LoRA's anymore.
I know very little of python btw, just enough to installl stuff but it's pretty much all chinese to me.
Tried intalling an older version but same problem.
Keep getting this error:

Traceback (most recent call last):
  File "C:\kohya_ss-24.0.1\venv\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "C:\kohya_ss-24.0.1\venv\lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\kohya_ss-24.0.1\venv\lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "C:\kohya_ss-24.0.1\venv\lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\kohya_ss-24.0.1\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\kohya_ss-24.0.1\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\kohya_ss-24.0.1\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\kohya_ss-24.0.1\venv\lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "C:\kohya_ss-24.0.1\kohya_gui\svd_merge_lora_gui.py", line 105, in svd_merge_lora
    command_to_run = " ".join(run_cmd)
TypeError: sequence item 17: expected str instance, int found

**Comment by bmaltais** [comment]
Hummm... look like an issue I might have introduced... let me look at it...

**Comment by bmaltais** [comment]
OK, I have fixed it. It is n the `dev` branch until I merge changes into a new release.

**Comment by Asaghon** [comment]
Nice, ty!
I assumed it was me doing something wrong
