### ISSUE TITLE
v24.1.2 - Tensorboard not starting?

### ISSUE THREAD

**Issue by zadokov** [bmaltais/kohya_ss#2471]
Trying to start Tensorboard I get the below.
@bmaltais  - It worked ok in the past.

19:09:59-097961 INFO     ['tensorboard', '--logdir', 'F:/SD/workspace/output/Lora/LogByRun/XLJC10', '--host', '0.0.0.0',
                         '--port', '6006']
19:09:59-098962 INFO     Starting TensorBoard on port 6006
Traceback (most recent call last):
  File "C:\SD\kohya_ss\kohya_gui\class_tensorboard.py", line 76, in start_tensorboard
    env = setup_environment(scriptdir=scriptdir)
NameError: name 'scriptdir' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\SD\kohya_ss\venv\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "C:\SD\kohya_ss\venv\lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\SD\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "C:\SD\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\SD\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\SD\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\SD\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\SD\kohya_ss\venv\lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "C:\SD\kohya_ss\kohya_gui\class_tensorboard.py", line 79, in start_tensorboard
    self.log.error("Failed to start Tensorboard:", e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1624, in _log
    self.handle(record)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 968, in handle
    self.emit(record)
  File "C:\SD\kohya_ss\venv\lib\site-packages\rich\logging.py", line 128, in emit
    message = self.format(record)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 678, in format
    record.message = record.getMessage()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting

**Comment by bmaltais** [comment]
Hummm...`NameError: name 'scriptdir' is not defined` I need to check what is going on there...
