### ISSUE TITLE
Starting TensorBoard - TypeError

### ISSUE THREAD

**Issue by Xkipper** [bmaltais/kohya_ss#2476]
When press _Start tensorboard_ button, Kohya log show this error and wont run Tensorboard...

**ERROR LOG:**
```PY
16:39:06-731714 INFO     Starting TensorBoard on port 6006
Traceback (most recent call last):
  File "D:\kohya_ss\kohya_gui\class_tensorboard.py", line 76, in start_tensorboard
    env = setup_environment(scriptdir=scriptdir)
NameError: name 'scriptdir' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\kohya_ss\venv\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "D:\kohya_ss\venv\lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "D:\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "D:\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\kohya_ss\venv\lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "D:\kohya_ss\kohya_gui\class_tensorboard.py", line 79, in start_tensorboard
    self.log.error("Failed to start Tensorboard:", e)
  File "C:\Python\Python310\lib\logging\__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Python\Python310\lib\logging\__init__.py", line 1624, in _log
    self.handle(record)
  File "C:\Python\Python310\lib\logging\__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "C:\Python\Python310\lib\logging\__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "C:\Python\Python310\lib\logging\__init__.py", line 968, in handle
    self.emit(record)
  File "D:\kohya_ss\venv\lib\site-packages\rich\logging.py", line 128, in emit
    message = self.format(record)
  File "C:\Python\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Python\Python310\lib\logging\__init__.py", line 678, in format
    record.message = record.getMessage()
  File "C:\Python\Python310\lib\logging\__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

**Kohya ver log:**
```CMD
Kohya_ss GUI version: v24.1.2
nVidia toolkit detected
Torch 2.1.2+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8905
Torch detected GPU: NVIDIA GeForce RTX 4070 SUPER VRAM 12282 Arch (8, 9) Cores 56
Python version is 3.10.11 (tags/v3.10.11:7d4cc5a, Apr 5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
```

The misstake in **kohya_ss\kohya_gui\class_tensorboard.py**, line 18
```PY
from .common_gui import setup_environment, scriptdir
```

**Comment by bmaltais** [comment]
Hi, I have resolved this issue in the `dev` branch. Will push it to master later tonight.
