### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/config_lora-20240510-152313.toml'

### ISSUE THREAD

**Issue by FrakerKill** [bmaltais/kohya_ss#2483]
Hello,

I'm just starting with kohya ss at local and I'm a bit lost:

15:23:13-914129 INFO     Start training LoRA Standard ...
15:23:13-915103 INFO     Validating lr scheduler arguments...
15:23:13-916082 INFO     Validating optimizer arguments...
15:23:13-917057 INFO     Validating C:/Users/ronsa/Downloads/kohya_ss/config.toml existence... SUCCESS
15:23:13-917057 INFO     Validating C:/Users/ronsa/Downloads/kohya_ss/models/sdXL_v10VAEFix.safetensors existence...
                         SUCCESS
15:23:13-918033 INFO     Validating C:/Users/ronsa/Downloads/kohya_ss/dataset/images existence... SUCCESS
15:23:13-919541 INFO     Dataset config toml file used, skipping total_steps, train_batch_size,
                         gradient_accumulation_steps, epoch, reg_factor, max_train_steps calculations...
15:23:13-920524 INFO     Train batch size: 1
15:23:13-920524 INFO     Gradient accumulation steps: 1
15:23:13-921500 INFO     Epoch: 1
15:23:13-922505 INFO     Max train steps: 1600
15:23:13-923489 INFO     stop_text_encoder_training = 0
15:23:13-923489 INFO     lr_warmup_steps = 160
Traceback (most recent call last):
  File "C:\Users\ronsa\Downloads\kohya_ss\venv\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\ronsa\Downloads\kohya_ss\venv\lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\ronsa\Downloads\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "C:\Users\ronsa\Downloads\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\ronsa\Downloads\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\ronsa\Downloads\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\Users\ronsa\Downloads\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Users\ronsa\Downloads\kohya_ss\venv\lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\ronsa\Downloads\kohya_ss\kohya_gui\lora_gui.py", line 1255, in train_model
    with open(tmpfilename, "w", encoding="utf-8") as toml_file:
PermissionError: [Errno 13] Permission denied: '/config_lora-20240510-152313.toml'

**Comment by FrakerKill** [comment]
Sorry, finally touching and creating the json. It works

**Comment by dooj888** [comment]
> Sorry, finally touching and creating the json. It works

What json? I have the same exact error and I'm not sure what to do

**Comment by Ferric-AU** [comment]
Yes I had the same error.

For me the fix was to add the "Output directory for the trained model", under the Folders section of the LORA gui.

/app/outputs worked (using the Docker version).

**Comment by Kadah** [comment]
This error seems to mean that the webui does not have permission to write to the set output directory or if the output directory field is left blank.
