### ISSUE TITLE
RuntimeError: Calculated padded input size per channel: (514 x 2). Kernel size: (3 x 3). Kernel size can't be greater than actual input size

### ISSUE THREAD

**Issue by drgrib** [bmaltais/kohya_ss#2489]
Would have reopened #1149 but I don't have the option. Reposting [my comment from there](https://github.com/bmaltais/kohya_ss/issues/1149#issuecomment-2105973810):

I'm getting this error for a training set with small images. The proposed solution for unchecking "Don't upscale bucket resolution" is no longer available in the UI. I also just upgraded to the latest version and the referencing commit has not fixed the issue.

## Error
```
RuntimeError: Calculated padded input size per channel: (514 x 2). Kernel size: (3 x 3). Kernel size can't be greater than actual input size
```

## Stack Trace
```
10:42:57-289612 INFO     Kohya_ss GUI version: v24.1.3
10:42:57-758808 INFO     Submodule initialized and updated.
10:42:57-760808 INFO     nVidia toolkit detected
10:42:59-305114 INFO     Torch 2.1.2+cu118
10:42:59-320111 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
10:42:59-323113 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9) Cores 128
10:42:59-327613 INFO     Python version is 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit
                         (AMD64)]
10:42:59-329408 INFO     Verifying modules installation status from requirements_pytorch_windows.txt...
10:42:59-332412 INFO     Verifying modules installation status from requirements_windows.txt...
10:42:59-334416 INFO     Verifying modules installation status from requirements.txt...
10:43:08-366953 INFO     headless: False
10:43:08-419116 INFO     Using shell=True when running external commands...
IMPORTANT: You are using gradio version 4.26.0, however version 4.29.0 is available, please upgrade.
--------
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
10:43:40-234216 INFO     Loading config...
10:47:49-525607 INFO     Save...
10:48:28-320383 INFO     Copy C:/Users/drgrib/Drive/Files/Interests/2024/4-SDXL-Input/test/lora/_final_pd to
                         D:/loras/11-test-ec\img/20_test woman woman...
10:48:28-382564 INFO     Copy D:/loras/0-regularization_images/1024_WOMAN to
                         D:/loras/11-test-ec\reg/1_woman...
10:48:30-263855 INFO     Done creating kohya_ss training folder structure at D:/loras/11-test-ec...
10:48:47-785343 INFO     Start training LoRA Standard ...
10:48:47-786343 INFO     Validating lr scheduler arguments...
10:48:47-787343 INFO     Validating optimizer arguments...
10:48:47-789347 INFO     Validating D:/loras/11-test-ec\log existence and writability... SUCCESS
10:48:47-790343 INFO     Validating D:/loras/11-test-ec\model existence and writability... SUCCESS
10:48:47-791342 INFO     Validating
                         D:/stable-diffusion-webui/models/Stable-diffusion/everclearPNYByZovya_v2VAE.safetensors
                         existence... SUCCESS
10:48:47-792342 INFO     Validating D:/loras/11-test-ec\reg existence... SUCCESS
10:48:47-793342 INFO     Validating D:/loras/11-test-ec\img existence... SUCCESS
10:48:47-794341 INFO     Folder 20_test woman woman: 20 repeats found
10:48:47-795342 INFO     Folder 20_test woman woman: 42 images found
10:48:47-795342 INFO     Folder 20_test woman woman: 42 * 20 = 840 steps
10:48:47-796343 WARNING  Regularisation images are used... Will double the number of steps required...
10:48:47-798345 INFO     Regulatization factor: 2
10:48:47-799349 INFO     Total steps: 840
10:48:47-800343 INFO     Train batch size: 2
10:48:47-801342 INFO     Gradient accumulation steps: 1
10:48:47-802342 INFO     Epoch: 5
10:48:47-803342 INFO     max_train_steps (840 / 2 / 1 * 5 * 2) = 4200
10:48:47-804343 INFO     stop_text_encoder_training = 0
10:48:47-804343 INFO     lr_warmup_steps = 0
10:48:47-806343 INFO     Saving training config to
                         D:/loras/11-test-ec\model\TEST_EC_20240511-104847.json...
10:48:47-810354 INFO     Executing command: D:\kohya_ss\venv\Scripts\accelerate.EXE launch --dynamo_backend no
                         --dynamo_mode default --mixed_precision bf16 --num_processes 1 --num_machines 1
                         --num_cpu_threads_per_process 2 D:/kohya_ss/sd-scripts/sdxl_train_network.py --config_file
                         D:/loras/11-test-ec\model/config_lora-20240511-104847.toml --optimizer_args
                         weight_decay=0.01 d_coef=1 use_bias_correction=True safeguard_warmup=False betas=0.9,0.99
10:48:47-815344 INFO     Command executed.
2024-05-11 10:48:58 INFO     Loading settings from                                                    train_util.py:3744
                             D:/loras/11-test-ec\model/config_lora-20240511-104847.toml...
                    INFO     D:/loras/11-test-ec\model/config_lora-20240511-104847          train_util.py:3763
2024-05-11 10:48:58 INFO     prepare tokenizers                                                   sdxl_train_util.py:134
2024-05-11 10:48:59 INFO     update token length: 75                                              sdxl_train_util.py:159
                    INFO     Using DreamBooth method.                                               train_network.py:172
                    INFO     prepare images.                                                          train_util.py:1572
                    INFO     found directory D:\loras\11-test-ec\img\20_test      train_util.py:1519
                             woman woman contains 42 image files
                    WARNING  No caption file found for 42 images. Training will continue without      train_util.py:1550
                             captions for these images. If class token exists, it will be used. /
                             42枚の画像にキャプションファイルが見つかりませんでした。これらの画像につ
                             いてはキャプションなしで学習を続行します。class
                             tokenが存在する場合はそれを使います。
                    WARNING  D:\loras\11-test-ec\img\20_test woman woman\00.jpeg  train_util.py:1557
                    WARNING  D:\loras\11-test-ec\img\20_test woman woman\01.jpeg  train_util.py:1557
                    WARNING  D:\loras\11-test-ec\img\20_test woman woman\02.jpeg  train_util.py:1557
                    WARNING  D:\loras\11-test-ec\img\20_test woman woman\03.jpeg  train_util.py:1557
                    WARNING  D:\loras\11-test-ec\img\20_test woman woman\04.jpeg  train_util.py:1557
                    WARNING  D:\loras\11-test-ec\img\20_test woman                train_util.py:1555
                             woman\05.jpeg... and 37 more
                    INFO     found directory D:\loras\11-test-ec\reg\1_woman contains 1000  train_util.py:1519
                             image files
                    WARNING  No caption file found for 1000 images. Training will continue without    train_util.py:1550
                             captions for these images. If class token exists, it will be used. /
                             1000枚の画像にキャプションファイルが見つかりませんでした。これらの画像に
                             ついてはキャプションなしで学習を続行します。class
                             tokenが存在する場合はそれを使います。
                    WARNING  D:\loras\11-test-ec\reg\1_woman\woman_0001.jpg                 train_util.py:1557
                    WARNING  D:\loras\11-test-ec\reg\1_woman\woman_0002.jpg                 train_util.py:1557
                    WARNING  D:\loras\11-test-ec\reg\1_woman\woman_0003.jpg                 train_util.py:1557
                    WARNING  D:\loras\11-test-ec\reg\1_woman\woman_0004.jpg                 train_util.py:1557
                    WARNING  D:\loras\11-test-ec\reg\1_woman\woman_0005.jpg                 train_util.py:1557
                    WARNING  D:\loras\11-test-ec\reg\1_woman\woman_0006.jpg... and 995 more train_util.py:1555
                    INFO     840 train images with repeating.                                         train_util.py:1613
                    INFO     1000 reg images.                                                         train_util.py:1616
                    WARNING  some of reg images are not used /                                        train_util.py:1618
                             正則化画像の数が多いので、一部使用されない正則化画像があります
                    INFO     [Dataset 0]                                                              config_util.py:565
                               batch_size: 2
                               resolution: (1024, 1024)
                               enable_bucket: True
                               network_multiplier: 1.0
                               min_bucket_reso: 512
                               max_bucket_reso: 2048
                               bucket_reso_steps: 256
                               bucket_no_upscale: True

                               [Subset 0 of Dataset 0]
                                 image_dir: "D:\loras\11-test-ec\img\20_test
                             woman woman"
                                 image_count: 42
                                 num_repeats: 20
                                 shuffle_caption: False
                                 keep_tokens: 0
                                 keep_tokens_separator:
                                 secondary_separator: None
                                 enable_wildcard: False
                                 caption_dropout_rate: 0.0
                                 caption_dropout_every_n_epoches: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 is_reg: False
                                 class_tokens: test woman woman
                                 caption_extension: .caption

                               [Subset 1 of Dataset 0]
                                 image_dir: "D:\loras\11-test-ec\reg\1_woman"
                                 image_count: 1000
                                 num_repeats: 1
                                 shuffle_caption: False
                                 keep_tokens: 0
                                 keep_tokens_separator:
                                 secondary_separator: None
                                 enable_wildcard: False
                                 caption_dropout_rate: 0.0
                                 caption_dropout_every_n_epoches: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 is_reg: True
                                 class_tokens: woman
                                 caption_extension: .caption


                    INFO     [Dataset 0]                                                              config_util.py:571
                    INFO     loading image sizes.                                                      train_util.py:853
100%|███████████████████████████████████████████████████████████████████████████████| 882/882 [00:02<00:00, 332.73it/s]
2024-05-11 10:49:02 INFO     make buckets                                                              train_util.py:859
                    WARNING  min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is   train_util.py:876
                             set, because bucket reso is defined by image size automatically /
                             bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計
                             算されるため、min_bucket_resoとmax_bucket_resoは無視されます
                    INFO     number of images (including repeats) /                                    train_util.py:905
                             各bucketの画像枚数（繰り返し回数を含む）
                    INFO     bucket 0: resolution (0, 256), count: 100                                 train_util.py:910
                    INFO     bucket 1: resolution (0, 512), count: 120                                 train_util.py:910
                    INFO     bucket 2: resolution (0, 768), count: 40                                  train_util.py:910
                    INFO     bucket 3: resolution (256, 256), count: 260                               train_util.py:910
                    INFO     bucket 4: resolution (256, 512), count: 60                                train_util.py:910
                    INFO     bucket 5: resolution (256, 768), count: 40                                train_util.py:910
                    INFO     bucket 6: resolution (256, 1280), count: 20                               train_util.py:910
                    INFO     bucket 7: resolution (512, 256), count: 100                               train_util.py:910
                    INFO     bucket 8: resolution (512, 1280), count: 40                               train_util.py:910
                    INFO     bucket 9: resolution (768, 512), count: 20                                train_util.py:910
                    INFO     bucket 10: resolution (768, 768), count: 20                               train_util.py:910
                    INFO     bucket 11: resolution (768, 1024), count: 20                              train_util.py:910
                    INFO     bucket 12: resolution (1024, 1024), count: 840                            train_util.py:910
                    INFO     mean ar error (without repeats): 0.014010217811068232                     train_util.py:915
                    WARNING  clip_skip will be unexpected / SDXL学習ではclip_skipは動作しません   sdxl_train_util.py:343
                    INFO     preparing accelerator                                                  train_network.py:225
accelerator device: cuda
                    INFO     loading model for process 0/1                                         sdxl_train_util.py:30
                    INFO     load StableDiffusion checkpoint:                                      sdxl_train_util.py:70
                             D:/stable-diffusion-webui/models/Stable-diffusion/everclearPNYByZovya
                             _v2VAE.safetensors
                    INFO     building U-Net                                                       sdxl_model_util.py:192
2024-05-11 10:49:03 INFO     loading U-Net from checkpoint                                        sdxl_model_util.py:196
2024-05-11 10:49:43 INFO     U-Net: <All keys matched successfully>                               sdxl_model_util.py:202
                    INFO     building text encoders                                               sdxl_model_util.py:205
2024-05-11 10:49:44 INFO     loading text encoders from checkpoint                                sdxl_model_util.py:258
2024-05-11 10:49:46 INFO     text encoder 1: <All keys matched successfully>                      sdxl_model_util.py:272
2024-05-11 10:49:54 INFO     text encoder 2: <All keys matched successfully>                      sdxl_model_util.py:276
                    INFO     building VAE                                                         sdxl_model_util.py:279
2024-05-11 10:49:55 INFO     loading VAE from checkpoint                                          sdxl_model_util.py:284
2024-05-11 10:49:56 INFO     VAE: <All keys matched successfully>                                 sdxl_model_util.py:287
2024-05-11 10:49:58 INFO     Enable xformers for U-Net                                                train_util.py:2660
import network module: networks.lora
                    INFO     [Dataset 0]                                                              train_util.py:2079
                    INFO     caching latents.                                                          train_util.py:974
                    INFO     checking cache validity...                                                train_util.py:984
100%|█████████████████████████████████████████████████████████████████████████████| 882/882 [00:00<00:00, 48993.17it/s]
                    INFO     caching latents...                                                       train_util.py:1021
  0%|                                                                                          | 0/882 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\kohya_ss\sd-scripts\sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "D:\kohya_ss\sd-scripts\train_network.py", line 272, in train
    train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
  File "D:\kohya_ss\sd-scripts\library\train_util.py", line 2080, in cache_latents
    dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)
  File "D:\kohya_ss\sd-scripts\library\train_util.py", line 1023, in cache_latents
    cache_batch_latents(vae, cache_to_disk, batch, subset.flip_aug, subset.random_crop)
  File "D:\kohya_ss\sd-scripts\library\train_util.py", line 2416, in cache_batch_latents
    latents = vae.encode(img_tensors).latent_dist.sample().to("cpu")
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\models\autoencoders\autoencoder_kl.py", line 260, in encode
    h = self.encoder(x)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\models\autoencoders\vae.py", line 143, in forward
    sample = self.conv_in(sample)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (514 x 2). Kernel size: (3 x 3). Kernel size can't be greater than actual input size
Traceback (most recent call last):
  File "C:\Users\drgrib\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\drgrib\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohya_ss\\venv\\Scripts\\python.exe', 'D:/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', 'D:/loras/11-test-ec\\model/config_lora-20240511-104847.toml', '--optimizer_args', 'weight_decay=0.01', 'd_coef=1', 'use_bias_correction=True', 'safeguard_warmup=False', 'betas=0.9,0.99']' returned non-zero exit status 1.
10:50:03-772973 INFO     Training has ended.
```

**Comment by bmaltais** [comment]
The option is located under the "Advanced" training tab:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/776c4f81-4167-4318-be8f-b8f9ec114923)

**Comment by bmaltais** [comment]
As far as the source of the issue goes... you should report it directly to kohya on his sd-scripts repo se he can address it there.

**Comment by drgrib** [comment]
That worked. Thank you.

**Comment by drgrib** [comment]
Actually, after caching it broke again:
```
13:10:34-029455 INFO     Kohya_ss GUI version: v24.1.3
13:10:34-714336 INFO     Submodule initialized and updated.
13:10:34-716839 INFO     nVidia toolkit detected
13:10:55-251612 INFO     Torch 2.1.2+cu118
13:10:55-336010 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
13:10:55-341131 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9) Cores 128
13:10:55-379195 INFO     Python version is 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit
                         (AMD64)]
13:10:55-380195 INFO     Verifying modules installation status from requirements_pytorch_windows.txt...
13:10:55-382196 INFO     Verifying modules installation status from requirements_windows.txt...
13:10:55-384196 INFO     Verifying modules installation status from requirements.txt...
13:11:39-664155 INFO     headless: False
13:11:39-716362 INFO     Using shell=True when running external commands...
IMPORTANT: You are using gradio version 4.26.0, however version 4.29.0 is available, please upgrade.
--------
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
13:21:04-332195 INFO     Loading config...
13:21:46-732729 INFO     Save...
13:22:08-713195 INFO     Save...
13:22:09-380893 INFO     Save...
13:23:20-770679 INFO     Copy C:/Users/drgrib/Drive/Files/Interests/2024/4-SDXL-Input/test/lora/_final_pd to
                         D:/loras/11-test-ec\img/20_test woman woman...
13:23:20-999011 INFO     Copy D:/loras/0-regularization_images/1024_WOMAN to
                         D:/loras/11-test-ec\reg/1_woman...
13:23:22-970045 INFO     Done creating kohya_ss training folder structure at D:/loras/11-test-ec...
13:24:00-571807 INFO     Start training Dreambooth...
13:24:00-573808 INFO     Validating lr scheduler arguments...
13:24:00-575807 INFO     Validating optimizer arguments...
13:24:00-576807 INFO     Validating D:/loras/11-test-ec\log existence and writability... SUCCESS
13:24:00-577807 INFO     Validating D:/loras/11-test-ec\model existence and writability... SUCCESS
13:24:00-578807 INFO     Validating
                         D:/stable-diffusion-webui/models/Stable-diffusion/everclearPNYByZovya_v2VAE.safetensors
                         existence... SUCCESS
13:24:00-579807 INFO     Validating D:/loras/11-test-ec\reg existence... SUCCESS
13:24:00-580808 INFO     Validating D:/loras/11-test-ec\img existence... SUCCESS
13:24:00-581808 INFO     Folder 20_test woman woman: 20 repeats found
13:24:00-582808 INFO     Folder 20_test woman woman: 42 images found
13:24:00-583809 INFO     Folder 20_test woman woman: 42 * 20 = 840 steps
13:24:00-584809 WARNING  Regularisation images are used... Will double the number of steps required...
13:24:00-585809 INFO     Regulatization factor: 2
13:24:00-586845 INFO     Total steps: 840
13:24:00-587813 INFO     Train batch size: 2
13:24:00-588814 INFO     Gradient accumulation steps: 1
13:24:00-589809 INFO     Epoch: 5
13:24:00-590811 INFO     max_train_steps (840 / 2 / 1 * 5 * 2) = 4200
13:24:00-592813 INFO     lr_warmup_steps = 0
13:24:00-595809 INFO     Saving training config to
                         D:/loras/11-test-ec\model\TEST_EC_20240511-132400.json...
13:24:00-597808 INFO     Executing command: D:\kohya_ss\venv\Scripts\accelerate.EXE launch --dynamo_backend no
                         --dynamo_mode default --mixed_precision bf16 --num_processes 1 --num_machines 1
                         --num_cpu_threads_per_process 2 D:/kohya_ss/sd-scripts/sdxl_train.py --config_file
                         D:/loras/11-test-ec\model/config_dreambooth-20240511-132400.toml --optimizer_args
                         weight_decay=0.01 d_coef=1 use_bias_correction=True safeguard_warmup=False betas=0.9,0.99
13:24:00-642843 INFO     Command executed.
2024-05-11 13:24:12 INFO     Loading settings from                                                    train_util.py:3744
                             D:/loras/11-test-ec\model/config_dreambooth-20240511-132400.to
                             ml...
                    INFO     D:/loras/11-test-ec\model/config_dreambooth-20240511-132400    train_util.py:3763
                    WARNING  clip_skip will be unexpected / SDXL学習ではclip_skipは動作しません   sdxl_train_util.py:343
2024-05-11 13:24:12 INFO     prepare tokenizers                                                   sdxl_train_util.py:134
                    INFO     update token length: 75                                              sdxl_train_util.py:159
                    INFO     Using DreamBooth method.                                                  sdxl_train.py:144
                    INFO     prepare images.                                                          train_util.py:1572
                    INFO     found directory D:\loras\11-test-ec\img\20_test      train_util.py:1519
                             woman woman contains 42 image files
                    WARNING  No caption file found for 42 images. Training will continue without      train_util.py:1550
                             captions for these images. If class token exists, it will be used. /
                             42枚の画像にキャプションファイルが見つかりませんでした。これらの画像につ
                             いてはキャプションなしで学習を続行します。class
                             tokenが存在する場合はそれを使います。
                    WARNING  D:\loras\11-test-ec\img\20_test woman woman\00.jpeg  train_util.py:1557
                    WARNING  D:\loras\11-test-ec\img\20_test woman woman\01.jpeg  train_util.py:1557
                    WARNING  D:\loras\11-test-ec\img\20_test woman woman\02.jpeg  train_util.py:1557
                    WARNING  D:\loras\11-test-ec\img\20_test woman woman\03.jpeg  train_util.py:1557
                    WARNING  D:\loras\11-test-ec\img\20_test woman woman\04.jpeg  train_util.py:1557
                    WARNING  D:\loras\11-test-ec\img\20_test woman                train_util.py:1555
                             woman\05.jpeg... and 37 more
2024-05-11 13:24:13 INFO     found directory D:\loras\11-test-ec\reg\1_woman contains 1000  train_util.py:1519
                             image files
                    WARNING  No caption file found for 1000 images. Training will continue without    train_util.py:1550
                             captions for these images. If class token exists, it will be used. /
                             1000枚の画像にキャプションファイルが見つかりませんでした。これらの画像に
                             ついてはキャプションなしで学習を続行します。class
                             tokenが存在する場合はそれを使います。
                    WARNING  D:\loras\11-test-ec\reg\1_woman\woman_0001.jpg                 train_util.py:1557
                    WARNING  D:\loras\11-test-ec\reg\1_woman\woman_0002.jpg                 train_util.py:1557
                    WARNING  D:\loras\11-test-ec\reg\1_woman\woman_0003.jpg                 train_util.py:1557
                    WARNING  D:\loras\11-test-ec\reg\1_woman\woman_0004.jpg                 train_util.py:1557
                    WARNING  D:\loras\11-test-ec\reg\1_woman\woman_0005.jpg                 train_util.py:1557
                    WARNING  D:\loras\11-test-ec\reg\1_woman\woman_0006.jpg... and 995 more train_util.py:1555
                    INFO     840 train images with repeating.                                         train_util.py:1613
                    INFO     1000 reg images.                                                         train_util.py:1616
                    WARNING  some of reg images are not used /                                        train_util.py:1618
                             正則化画像の数が多いので、一部使用されない正則化画像があります
                    INFO     [Dataset 0]                                                              config_util.py:565
                               batch_size: 2
                               resolution: (1024, 1024)
                               enable_bucket: True
                               network_multiplier: 1.0
                               min_bucket_reso: 512
                               max_bucket_reso: 2048
                               bucket_reso_steps: 256
                               bucket_no_upscale: False

                               [Subset 0 of Dataset 0]
                                 image_dir: "D:\loras\11-test-ec\img\20_test
                             woman woman"
                                 image_count: 42
                                 num_repeats: 20
                                 shuffle_caption: False
                                 keep_tokens: 0
                                 keep_tokens_separator:
                                 secondary_separator: None
                                 enable_wildcard: False
                                 caption_dropout_rate: 0.0
                                 caption_dropout_every_n_epoches: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 is_reg: False
                                 class_tokens: test woman woman
                                 caption_extension: .caption

                               [Subset 1 of Dataset 0]
                                 image_dir: "D:\loras\11-test-ec\reg\1_woman"
                                 image_count: 1000
                                 num_repeats: 1
                                 shuffle_caption: False
                                 keep_tokens: 0
                                 keep_tokens_separator:
                                 secondary_separator: None
                                 enable_wildcard: False
                                 caption_dropout_rate: 0.0
                                 caption_dropout_every_n_epoches: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 is_reg: True
                                 class_tokens: woman
                                 caption_extension: .caption


                    INFO     [Dataset 0]                                                              config_util.py:571
                    INFO     loading image sizes.                                                      train_util.py:853
100%|███████████████████████████████████████████████████████████████████████████████| 882/882 [00:02<00:00, 337.99it/s]
2024-05-11 13:24:15 INFO     make buckets                                                              train_util.py:859
                    INFO     number of images (including repeats) /                                    train_util.py:905
                             各bucketの画像枚数（繰り返し回数を含む）
                    INFO     bucket 0: resolution (512, 1536), count: 180                              train_util.py:910
                    INFO     bucket 1: resolution (512, 1792), count: 60                               train_util.py:910
                    INFO     bucket 2: resolution (512, 2048), count: 60                               train_util.py:910
                    INFO     bucket 3: resolution (768, 1280), count: 380                              train_util.py:910
                    INFO     bucket 4: resolution (1024, 1024), count: 940                             train_util.py:910
                    INFO     bucket 5: resolution (1280, 768), count: 60                               train_util.py:910
                    INFO     mean ar error (without repeats): 0.0038361599947824786                    train_util.py:915
                    INFO     prepare accelerator                                                       sdxl_train.py:201
accelerator device: cuda
                    INFO     loading model for process 0/1                                         sdxl_train_util.py:30
                    INFO     load StableDiffusion checkpoint:                                      sdxl_train_util.py:70
                             D:/stable-diffusion-webui/models/Stable-diffusion/everclearPNYByZovya
                             _v2VAE.safetensors
2024-05-11 13:24:16 INFO     building U-Net                                                       sdxl_model_util.py:192
                    INFO     loading U-Net from checkpoint                                        sdxl_model_util.py:196
2024-05-11 13:26:39 INFO     U-Net: <All keys matched successfully>                               sdxl_model_util.py:202
                    INFO     building text encoders                                               sdxl_model_util.py:205
2024-05-11 13:26:40 INFO     loading text encoders from checkpoint                                sdxl_model_util.py:258
2024-05-11 13:26:41 INFO     text encoder 1: <All keys matched successfully>                      sdxl_model_util.py:272
2024-05-11 13:26:50 INFO     text encoder 2: <All keys matched successfully>                      sdxl_model_util.py:276
                    INFO     building VAE                                                         sdxl_model_util.py:279
                    INFO     loading VAE from checkpoint                                          sdxl_model_util.py:284
2024-05-11 13:26:51 INFO     VAE: <All keys matched successfully>                                 sdxl_model_util.py:287
Disable Diffusers' xformers
2024-05-11 13:26:53 INFO     Enable xformers for U-Net                                                train_util.py:2660
2024-05-11 13:26:54 INFO     [Dataset 0]                                                              train_util.py:2079
                    INFO     caching latents.                                                          train_util.py:974
                    INFO     checking cache validity...                                                train_util.py:984
100%|█████████████████████████████████████████████████████████████████████████████| 882/882 [00:00<00:00, 55124.89it/s]
                    INFO     caching latents...                                                       train_util.py:1021
100%|████████████████████████████████████████████████████████████████████████████████| 882/882 [03:50<00:00,  3.83it/s]
train unet: True, text_encoder1: False, text_encoder2: False
number of models: 1
number of trainable parameters: 2567463684
prepare optimizer, data loader etc.
2024-05-11 13:30:46 INFO     use Prodigy optimizer | {'weight_decay': 0.01, 'd_coef': 1,              train_util.py:4034
                             'use_bias_correction': True, 'safeguard_warmup': False, 'betas': (0.9,
                             0.99)}
Using decoupled weight decay
override steps. steps for 5 epochs is / 指定エポックまでのステップ数: 4200
enable full bf16 training.
running training / 学習開始
  num examples / サンプル数: 840
  num batches per epoch / 1epochのバッチ数: 840
  num epochs / epoch数: 5
  batch size per device / バッチサイズ: 2
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 4200
steps:   0%|                                                                                  | 0/4200 [00:00<?, ?it/s]
epoch 1/5
Traceback (most recent call last):
  File "D:\kohya_ss\sd-scripts\sdxl_train.py", line 818, in <module>
    train(args)
  File "D:\kohya_ss\sd-scripts\sdxl_train.py", line 628, in train
    optimizer.step()
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\optimizer.py", line 145, in step
    self.optimizer.step(closure)
  File "D:\kohya_ss\venv\lib\site-packages\torch\optim\lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\torch\optim\optimizer.py", line 373, in wrapper
    out = func(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\prodigyopt\prodigy.py", line 168, in step
    state['exp_avg'] = torch.zeros_like(p.data).detach()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB. GPU 0 has a total capacty of 23.99 GiB of which 0 bytes is free. Of the allocated memory 28.99 GiB is allocated by PyTorch, and 1.05 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
steps:   0%|                                                                                  | 0/4200 [00:27<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\drgrib\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\drgrib\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohya_ss\\venv\\Scripts\\python.exe', 'D:/kohya_ss/sd-scripts/sdxl_train.py', '--config_file', 'D:/loras/11-test-ec\\model/config_dreambooth-20240511-132400.toml', '--optimizer_args', 'weight_decay=0.01', 'd_coef=1', 'use_bias_correction=True', 'safeguard_warmup=False', 'betas=0.9,0.99']' returned non-zero exit status 1.
13:31:34-291674 INFO     Training has ended.
```

**Comment by drgrib** [comment]
I'll report the issue to https://github.com/kohya-ss/sd-scripts

**Comment by drgrib** [comment]
I ended up just upscaling all my images x2 using [Upscayl](https://www.upscayl.org/#download) then deleting any that came out deformed. Kohya is now training using the normal settings.
