### ISSUE TITLE
LoRA Training Kohya no safetensors file 

### ISSUE THREAD

**Issue by Agnusse** [bmaltais/kohya_ss#2490]
**Hey, i want to train a LoRA with Kohya, but i keep running into the same issue: There is no safetensors file getting stored. Does anyone have an idea?

Than you in advance.**

8:13:43-561653 INFO Start training Dreambooth...

18:13:43-564770 INFO Validating lr scheduler arguments...

18:13:43-566190 INFO Validating optimizer arguments...

18:13:43-567656 INFO Validating /home/jovyan/kohya_ss/outputs/log existence and writability... SUCCESS

18:13:43-569118 INFO Validating /home/jovyan/kohya_ss/outputs/model existence and writability... SUCCESS

18:13:43-570559 INFO Validating stabilityai/stable-diffusion-xl-base-1.0 existence... SUCCESS

18:13:43-571198 INFO Validating /home/jovyan/kohya_ss/outputs/img existence... SUCCESS

18:13:43-571918 INFO Folder 40_Flora1 plant: 40 repeats found

18:13:43-572563 INFO Folder 40_Flora1 plant: 20 images found

18:13:43-573164 INFO Folder 40_Flora1 plant: 20 * 40 = 800 steps

18:13:43-573802 INFO Regulatization factor: 1

18:13:43-574358 INFO Total steps: 800

18:13:43-574895 INFO Train batch size: 1

18:13:43-575438 INFO Gradient accumulation steps: 1

18:13:43-575994 INFO Epoch: 30

18:13:43-576520 INFO Max train steps: 1600

18:13:43-577059 INFO lr_warmup_steps = 0

18:13:43-578083 INFO Saving training config to /home/jovyan/kohya_ss/outputs/model/Flora1_20240511-181343.json...

18:13:43-579175 INFO Executing command: /home/jovyan/.conda_envs/kohya/bin/accelerate launch --dynamo_backend no --dynamo_mode default --mixed_precision fp16 --num_processes 1 --num_machines 1

--num_cpu_threads_per_process 2 /home/jovyan/kohya_ss/sd-scripts/sdxl_train.py --config_file /home/jovyan/kohya_ss/outputs/model/config_dreambooth-20240511-181343.toml

18:13:43-581062 INFO Command executed.

/home/jovyan/.conda_envs/kohya/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.

torch.utils._pytree._register_pytree_node(

2024-05-11 18:13:49.169188: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

2024-05-11 18:13:49.208161: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered

2024-05-11 18:13:49.208243: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered

2024-05-11 18:13:49.209188: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

2024-05-11 18:13:49.215287: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.

To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

2024-05-11 18:13:50.015640: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

/home/jovyan/.conda_envs/kohya/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.

torch.utils._pytree._register_pytree_node(

/home/jovyan/.conda_envs/kohya/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.

torch.utils._pytree._register_pytree_node(

2024-05-11 18:13:50 INFO Loading settings from /home/jovyan/kohya_ss/outputs/model/config_dreambooth-20240511-181343.toml... train_util.py:3744

INFO /home/jovyan/kohya_ss/outputs/model/config_dreambooth-20240511-181343 train_util.py:3763

WARNING clip_skip will be unexpected / SDXL学習ではclip_skipは動作しません sdxl_train_util.py:343

2024-05-11 18:13:50 INFO prepare tokenizers sdxl_train_util.py:134

2024-05-11 18:13:51 INFO update token length: 75 sdxl_train_util.py:159

INFO Using DreamBooth method. sdxl_train.py:144

INFO prepare images. train_util.py:1572

INFO found directory /home/jovyan/kohya_ss/outputs/img/40_Flora1 plant contains 20 image files train_util.py:1519

INFO 800 train images with repeating. train_util.py:1613

INFO 0 reg images. train_util.py:1616

WARNING no regularization images / 正則化画像が見つかりませんでした train_util.py:1621

INFO [Dataset 0] config_util.py:565

batch_size: 1

resolution: (1024, 1024)

enable_bucket: True

network_multiplier: 1.0

min_bucket_reso: 256

max_bucket_reso: 2048

bucket_reso_steps: 64

bucket_no_upscale: True

[Subset 0 of Dataset 0]

image_dir: "/home/jovyan/kohya_ss/outputs/img/40_Flora1 plant"

image_count: 20

num_repeats: 40

shuffle_caption: False

keep_tokens: 0

keep_tokens_separator:

secondary_separator: None

enable_wildcard: False

caption_dropout_rate: 0.05

caption_dropout_every_n_epoches: 0

caption_tag_dropout_rate: 0.0

caption_prefix: None

caption_suffix: None

color_aug: False

flip_aug: False

face_crop_aug_range: None

random_crop: False

token_warmup_min: 1,

token_warmup_step: 0,

is_reg: False

class_tokens: Flora1 plant

caption_extension: .txt

INFO [Dataset 0] config_util.py:571

INFO loading image sizes. train_util.py:853

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 75777.85it/s]

INFO make buckets train_util.py:859

WARNING min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / train_util.py:876

bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます

INFO number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む） train_util.py:905

INFO bucket 0: resolution (1024, 1024), count: 800 train_util.py:910

INFO mean ar error (without repeats): 0.0 train_util.py:915

INFO prepare accelerator sdxl_train.py:201

WARNING Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel [logging.py:61](http://logging.py:61/)

to the minimum version or higher.

accelerator device: cuda

INFO loading model for process 0/1 sdxl_train_util.py:30

INFO load Diffusers pretrained models: stabilityai/stable-diffusion-xl-base-1.0, variant=fp16 sdxl_train_util.py:84

Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:04<00:00, 1.40it/s]

2024-05-11 18:13:56 INFO U-Net converted to original U-Net sdxl_train_util.py:120

Disable Diffusers' xformers

INFO Enable xformers for U-Net train_util.py:2660

Traceback (most recent call last):

File "/home/jovyan/kohya_ss/sd-scripts/library/train_util.py", line 2662, in replace_unet_modules

import xformers.ops

ModuleNotFoundError: No module named 'xformers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/home/jovyan/kohya_ss/sd-scripts/sdxl_train.py", line 818, in <module>

train(args)

File "/home/jovyan/kohya_ss/sd-scripts/sdxl_train.py", line 256, in train

train_util.replace_unet_modules(unet, args.mem_eff_attn, args.xformers, args.sdpa)

File "/home/jovyan/kohya_ss/sd-scripts/library/train_util.py", line 2664, in replace_unet_modules

raise ImportError("No xformers / xformersがインストールされていないようです")

ImportError: No xformers / xformersがインストールされていないようです

Traceback (most recent call last):

File "/home/jovyan/.conda_envs/kohya/bin/accelerate", line 8, in <module>

sys.exit(main())

File "/home/jovyan/.conda_envs/kohya/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main

args.func(args)

File "/home/jovyan/.conda_envs/kohya/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command

simple_launcher(args)

File "/home/jovyan/.conda_envs/kohya/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher

raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

subprocess.CalledProcessError: Command '['/home/jovyan/.conda_envs/kohya/bin/python3.10', '/home/jovyan/kohya_ss/sd-scripts/sdxl_train.py', '--config_file', '/home/jovyan/kohya_ss/outputs/model/config_dreambooth-20240511-181343.toml']' returned non-zero exit status 1.

18:13:59-781327 INFO Training has ended.

**Comment by bmaltais** [comment]
Those errors at the beginnind are probably related to issues with the nvidia drivers or CUDA / torch release used...

Make sure you have recent NVidia drivers with CUDA 11.8 installed. THe GUI is made to run with CUDA 11.8 and not 12.1...
