### ISSUE TITLE
ModuleNotFoundError: No module named 'albumentations'

### ISSUE THREAD

**Issue by lolxdmainkaisemaanlu** [bmaltais/kohya_ss#25]
Traceback (most recent call last):
  File "C:\Users\Siddhesh\Desktop\kohya_ss\train_network.py", line 21, in <module>
    import albumentations as albu
ModuleNotFoundError: No module named 'albumentations'
Traceback (most recent call last):
  File "C:\Users\Siddhesh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Siddhesh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Siddhesh\AppData\Local\Programs\Python\Python310\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\Siddhesh\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\Siddhesh\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\Siddhesh\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Siddhesh\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', 'train_network.py', '--cache_latents', '--enable_bucket', '--use_8bit_adam', '--xformers', '--pretrained_model_name_or_path=C:/Users/Siddhesh/Desktop/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned.ckpt', '--train_data_dir=C:/Users/Siddhesh/Desktop/test\\img', '--resolution=512,512', '--output_dir=C:/Users/Siddhesh/Desktop/test\\model', '--train_batch_size=1', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=800', '--use_8bit_adam', '--xformers', '--mixed_precision=fp16', '--save_every_n_epochs=1', '--seed=1234', '--save_precision=fp16', '--logging_dir=C:/Users/Siddhesh/Desktop/test\\log', '--network_module=networks.lora', '--text_encoder_lr=1e-06', '--unet_lr=0.0001', '--network_dim=4']' returned non-zero exit status 1.

**Comment by lolxdmainkaisemaanlu** [comment]
I already had albumentations in my venv, but it started working after I installed albumentations on my non-venv python..

**Comment by bmaltais** [comment]
> I already had albumentations in my venv, but it got past this after I installed albumentations on my non-venv python..

When using venv alongside local python library can lead to issues. I have seen users who could not get the solution to work because some local module install prevented the proper installation of venv based module.

Solution was to wipe out the local python modules and redo the venv based install.

To wipe out the local module:

1. Open a terminal outside the venv
2. `pip freeze > uninstall.txt`
3. `pip uninstall -y -r uninstall.txt`

**Comment by AyoKeito** [comment]
Do we even need --system-site-packages when creating venv?
It seems to work just fine with
`python -m venv venv`
and does not requite wiping conflicts from the system.

**Comment by bmaltais** [comment]
Good point. I will adjust the readme accordingly
