### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by NonDesu** [bmaltais/kohya_ss#250]
Using the provided command during installation throws an exception

```
(venv) PS N:\AI\kohya_ss> pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
Collecting torch==1.12.1+cu116
  Using cached https://download.pytorch.org/whl/cu116/torch-1.12.1%2Bcu116-cp310-cp310-win_amd64.whl (2388.4 MB)
Collecting torchvision==0.13.1+cu116
  Using cached https://download.pytorch.org/whl/cu116/torchvision-0.13.1%2Bcu116-cp310-cp310-win_amd64.whl (2.6 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting numpy
  Using cached numpy-1.24.2-cp310-cp310-win_amd64.whl (14.8 MB)
Collecting requests
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached Pillow-9.4.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.0.1-cp310-cp310-win_amd64.whl (96 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Installing collected packages: charset-normalizer, urllib3, typing-extensions, pillow, numpy, idna, certifi, torch, requests, torchvision
ERROR: Exception:
Traceback (most recent call last):
  File "N:\AI\kohya_ss\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "N:\AI\kohya_ss\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
  File "N:\AI\kohya_ss\venv\lib\site-packages\pip\_internal\commands\install.py", line 494, in run
    installed = install_given_reqs(
  File "N:\AI\kohya_ss\venv\lib\site-packages\pip\_internal\req\__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "N:\AI\kohya_ss\venv\lib\site-packages\pip\_internal\req\req_install.py", line 792, in install
    install_wheel(
  File "N:\AI\kohya_ss\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 729, in install_wheel
    _install_wheel(
  File "N:\AI\kohya_ss\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 589, in _install_wheel
    file.save()
  File "N:\AI\kohya_ss\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 388, in save
    shutil.copyfileobj(f, dest)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 195, in copyfileobj
    buf = fsrc_read(length)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 925, in read
    data = self._read1(n)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1015, in _read1
    self._update_crc(data)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 943, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'torch/lib/torch_cuda_cu.dll'
```

**Comment by bmaltais** [comment]
Look like some of the files you have on your SSD or downloaded are corrupted... you might want to delete the full venv and start from scratch.

**Comment by NonDesu** [comment]
Appears to have been a pip cache issue, had to purge it to make everything work
