### ISSUE TITLE
Kohya ss Lora training is not working at all. Please help!

### ISSUE THREAD

**Issue by Yoongi22** [bmaltais/kohya_ss#2502]
10:13:44-588801 INFO     Loading config...
10:14:18-605059 INFO     Start training LoRA Standard ...
10:14:18-607049 INFO     Validating lr scheduler arguments...
10:14:18-609055 INFO     Validating optimizer arguments...
10:14:18-610059 INFO     Validating D:/AID/SEAIT/Lora/DREAM/log existence and writability... SUCCESS
10:14:18-612098 INFO     Validating D:/AID/SEAIT/Lora/DREAM/model existence and writability...
                         SUCCESS
10:14:18-614104 INFO     Validating D:/PRO/AI/models/SD/chilloutmix_NiPrunedFp16Fix.safetensors
                         existence... SUCCESS
10:14:18-617102 INFO     Validating D:/AID/SEAIT/Lora/DREAM/img existence... SUCCESS
10:14:18-619118 INFO     Folder 50_KRST_style: 50 repeats found
10:14:18-621036 INFO     Folder 50_KRST_style: 38 images found
10:14:18-623041 INFO     Folder 50_KRST_style: 38 * 50 = 1900 steps
10:14:18-624033 INFO     Regulatization factor: 1
10:14:18-626033 INFO     Total steps: 1900
10:14:18-627627 INFO     Train batch size: 1
10:14:18-628624 INFO     Gradient accumulation steps: 1
10:14:18-630623 INFO     Epoch: 1
10:14:18-633619 INFO     max_train_steps (1900 / 1 / 1 * 1 * 1) = 1900
10:14:18-635781 INFO     stop_text_encoder_training = 0
10:14:18-637759 INFO     lr_warmup_steps = 0
10:14:18-640758 INFO     Saving training config to
                         D:/AID/SEAIT/Lora/DREAM/model\Al_20240516-101418.json...
10:14:18-645214 INFO     Executing command: C:\Users\Admin\kohya_ss\venv\Scripts\accelerate.EXE
                         launch --dynamo_backend no --dynamo_mode default --mixed_precision fp16
                         --num_processes 1 --num_machines 1 --num_cpu_threads_per_process 4
                         C:/Users/Admin/kohya_ss/sd-scripts/train_network.py --config_file
                         D:/AID/SEAIT/Lora/DREAM/model/config_lora-20240516-101418.toml
10:14:18-649214 INFO     Command executed.
Traceback (most recent call last):
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\transformers\utils\import_utils.py", line 1390, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\transformers\models\clip\image_processing_clip.py", line 21, in <module>
    from ...image_processing_utils import BaseImageProcessor, BatchFeature, get_size_dict
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\transformers\image_processing_utils.py", line 28, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\transformers\image_transforms.py", line 47, in <module>
    import tensorflow as tf
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\tensorflow\__init__.py", line 42, in <module>
    from tensorflow.python import tf2 as _tf2
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\tensorflow\python\tf2.py", line 21, in <module>
    from tensorflow.python.platform import _pywrap_tf2
ImportError: DLL load failed while importing _pywrap_tf2: Произошел сбой в программе инициализации библиотеки динамической компоновки (DLL).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 710, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 20, in <module>
    from transformers import CLIPImageProcessor, CLIPTextModel, CLIPTokenizer, CLIPVisionModelWithProjection
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\transformers\utils\import_utils.py", line 1381, in __getattr__
    value = getattr(module, name)
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\transformers\utils\import_utils.py", line 1380, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\transformers\utils\import_utils.py", line 1392, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.image_processing_clip because of the following error (look up to see its traceback):
DLL load failed while importing _pywrap_tf2: Произошел сбой в программе инициализации библиотеки динамической компоновки (DLL).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\kohya_ss\sd-scripts\train_network.py", line 21, in <module>
    from library import deepspeed_utils, model_util
  File "C:\Users\Admin\kohya_ss\sd-scripts\library\model_util.py", line 13, in <module>
    from diffusers import AutoencoderKL, DDIMScheduler, StableDiffusionPipeline  # , UNet2DConditionModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 701, in __getattr__
    value = getattr(module, name)
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 701, in __getattr__
    value = getattr(module, name)
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 700, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\diffusers\utils\import_utils.py", line 712, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion because of the following error (look up to see its traceback):
Failed to import transformers.models.clip.image_processing_clip because of the following error (look up to see its traceback):
DLL load failed while importing _pywrap_tf2: Произошел сбой в программе инициализации библиотеки динамической компоновки (DLL).
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\Users\Admin\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Admin\\kohya_ss\\venv\\Scripts\\python.exe', 'C:/Users/Admin/kohya_ss/sd-scripts/train_network.py', '--config_file', 'D:/AID/SEAIT/Lora/DREAM/model/config_lora-20240516-101418.toml']' returned non-zero exit status 1.
10:14:31-193185 INFO     Training has ended.

**Comment by bmaltais** [comment]
Look like there is an issue with tensorflow... Is this on a fresh install? Have you tried deleting the venv folder and run setup.bat again?

**Comment by Yoongi22** [comment]
yes. Its on fresh install. I tried to delete and install it again. I also tried deleting the venv folder and run setup.bat again, but seems like it doesnt worked...

**Comment by bmaltais** [comment]
Have you validated you have the right. Erosion of CUDA drivers 11.8 installed? There must be something missing of not meeting the requirements on your computer.

**Comment by Yoongi22** [comment]
I installed the old version and it works.

**Comment by Yoongi22** [comment]
This instruction helped me to run my LoRa:

Download the 21.7.10 version from https://github.com/bmaltais/kohya_ss/releases?page=2 Change the Gradio version in requirements_windows_torch1.txt to gradio==3.36.1 (see @bmaltais comment above) Run Setup.bat and install it using Torch1 (important!, torch2 v not working)
