### ISSUE TITLE
ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend

### ISSUE THREAD

**Issue by lawliet198t** [bmaltais/kohya_ss#2521]
Traceback (most recent call last):
  File "/workspace/all_data/kohya_ss/venv/lib/python3.10/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/workspace/all_data/kohya_ss/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 260, in call_process_api
    with utils.MatplotlibBackendMananger():
  File "/workspace/all_data/kohya_ss/venv/lib/python3.10/site-packages/gradio/utils.py", line 948, in __enter__
    import matplotlib
  File "/workspace/all_data/kohya_ss/venv/lib/python3.10/site-packages/matplotlib/__init__.py", line 1270, in <module>
    rcParams['backend'] = os.environ.get('MPLBACKEND')
  File "/workspace/all_data/kohya_ss/venv/lib/python3.10/site-packages/matplotlib/__init__.py", line 738, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None
ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']

**Comment by khushalishah1** [comment]
same issue occured

**Comment by joshuacwnewton** [comment]
This issue is specific to Jupyter notebooks. And, `pip install matplotlib-inline` should fix this issue. :)

**Comment by FelahBr** [comment]
> This issue is specific to Jupyter notebooks. And, `pip install matplotlib-inline` should fix this issue. :)

Thanks, man! Helped me a lot!

**Comment by nininikeni** [comment]
> 此问题特定于 Jupyter 笔记本。并且，应该解决这个问题。:)`pip install matplotlib-inline`

You solved the problem that had been bothering me all morning, thank you!!! :)

**Comment by Guilherme99** [comment]
> This issue is specific to Jupyter notebooks. And, `pip install matplotlib-inline` should fix this issue. :)

Thank you!

**Comment by hemanthkotaprolu** [comment]
This and then restarting the kernel helped solve this.
