### ISSUE TITLE
 assert abs_path is not None, f"no image / 画像がありません: {image_key}"

### ISSUE THREAD

**Issue by D3voz** [bmaltais/kohya_ss#2522]
Can't use finetune after updating to latest version. 

2024-05-22 19:14:33 INFO     found 140 images.                                             prepare_buckets_latents.py:70
                    INFO     loading existing metadata: meta_cap.json                      prepare_buckets_latents.py:73
                    INFO     load VAE:                                                                model_util.py:1268
                             D:/github/stable-diffusion-webui/models/Stable-diffusion/sd1.5/v1-5-prun
                             ed-emaonly.safetensors
100%|████████████████████████████████████████████████████████████████████████████████| 140/140 [00:30<00:00,  4.54it/s]
2024-05-22 19:15:04 INFO     bucket 0 (640, 384): 140                                     prepare_buckets_latents.py:194
                    INFO     mean ar error: 0.11111111111111094                           prepare_buckets_latents.py:196
                    INFO     writing metadata: meta_lat.json                              prepare_buckets_latents.py:199
                    INFO     done!                                                        prepare_buckets_latents.py:202
19:15:05-197253 INFO     image_num = 140
19:15:05-198252 INFO     repeats = 140
19:15:05-199252 INFO     Max train steps: 875
19:15:05-200252 INFO     lr_warmup_steps = 0
19:15:05-202252 INFO     Saving training config to D:/github/lora/models\newstyle_20240522-191505.json...
19:15:05-203252 INFO     Executing command: D:\github\kohya_ss\venv\Scripts\accelerate.EXE launch --dynamo_backend no
                         --dynamo_mode default --mixed_precision fp16 --num_processes 1 --num_machines 1
                         --num_cpu_threads_per_process 2 D:/github/kohya_ss/sd-scripts/fine_tune.py --config_file
                         D:/github/lora/models/config_finetune-20240522-191505.toml
19:15:05-207254 INFO     Command executed.
2024-05-22 19:15:13 INFO     Loading settings from                                                    train_util.py:3744
                             D:/github/lora/models/config_finetune-20240522-191505.toml...
                    INFO     D:/github/lora/models/config_finetune-20240522-191505                    train_util.py:3763
2024-05-22 19:15:13 INFO     prepare tokenizer                                                        train_util.py:4227
2024-05-22 19:15:14 INFO     update token length: 75                                                  train_util.py:4244
                    INFO     loading existing metadata: /meta_lat.json                                train_util.py:1679
Traceback (most recent call last):
  File "D:\github\kohya_ss\sd-scripts\fine_tune.py", line 526, in <module>
    train(args)
  File "D:\github\kohya_ss\sd-scripts\fine_tune.py", line 85, in train
    train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.dataset_group)
  File "D:\github\kohya_ss\sd-scripts\library\config_util.py", line 482, in generate_dataset_group_by_blueprint
    dataset = dataset_klass(subsets=subsets, **asdict(dataset_blueprint.params))
  File "D:\github\kohya_ss\sd-scripts\library\train_util.py", line 1714, in __init__
    assert abs_path is not None, f"no image / 画像がありません: {image_key}"
AssertionError: no image / 画像がありません: D:\github\lora\images\10_level\1.jpg
Traceback (most recent call last):
  File "C:\Users\This PC\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\This PC\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\github\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "D:\github\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\github\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "D:\github\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\github\\kohya_ss\\venv\\Scripts\\python.exe', 'D:/github/kohya_ss/sd-scripts/fine_tune.py', '--config_file', 'D:/github/lora/models/config_finetune-20240522-191505.toml']' returned non-zero exit status 1.
19:15:16-504837 INFO     Training has ended.

I do not know where does it get the D:\github\lora\images\10_level\1.jpg , it is not in anywhere . Tried reinstalling, deleting all data, still it gives same error with D:\github\lora\images\10_level\1.jpg.

**Comment by bmaltais** [comment]
Does this image exist? the sd-script complain it can't find it: `D:\github\lora\images\10_level\1.jpg`

You may have to open an issue with kohya directly at https://github.com/kohya-ss/sd-scripts as this appear to be something his script is reporting and not the GUI.
