### ISSUE TITLE
Didn't change anything, Lora training spits out non-zero exit status 1 json error?

### ISSUE THREAD

**Issue by ToolB0xx** [bmaltais/kohya_ss#2523]
Traceback (most recent call last):
  File "F:\kohya\kohya_ss\sd-scripts\sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "F:\kohya\kohya_ss\sd-scripts\train_network.py", line 154, in train
    tokenizer = self.load_tokenizer(args)
  File "F:\kohya\kohya_ss\sd-scripts\sdxl_train_network.py", line 53, in load_tokenizer
    tokenizer = sdxl_train_util.load_tokenizers(args)
  File "F:\kohya\kohya_ss\sd-scripts\library\sdxl_train_util.py", line 147, in load_tokenizers
    tokenizer = CLIPTokenizer.from_pretrained(original_path)
  File "F:\kohya\kohya_ss\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1989, in from_pretrained
    tokenizer_config = json.load(reader)
  File "C:\Users\Xenobyte\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Xenobyte\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Xenobyte\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Xenobyte\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Xenobyte\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Xenobyte\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\kohya\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "F:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "F:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "F:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['F:\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'F:/kohya/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', 'F:/stable-diffusion-webui/models/Lora/trained loras/config_lora-20240522-194000.toml']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
Hi, this is an issue with the training scripts. You should raise this as an issue directly on kohya's sd-scripts repo: https://github.com/kohya-ss/sd-scripts
