### ISSUE TITLE
unable to train sdxl lora using runpod

### ISSUE THREAD

**Issue by Light-7777** [bmaltais/kohya_ss#2535]
I am using runpod with template : https://runpod.io/gsc?template=ya6013lj5a&ref=w18gds2n and a 3090ti.

after uploading my image dataset and updating parameters I click start training. Then it create some json files and in output models and just stops the training without throwing any error. 

I some logs from setup.log file it didn't created any logs in my output directory. It's not thrwoing error anywhere just stopping training mid way without alerting anything. 

`2024-05-25 13:50:59,994 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Start training LoRA Standard ...
2024-05-25 13:50:59,997 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Validating lr scheduler arguments...
2024-05-25 13:50:59,999 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Validating optimizer arguments...
2024-05-25 13:51:00,000 | INFO | /workspace/kohya_ss/kohya_gui/common_gui.py | Validating /workspace/kohya_ss/directory/log existence and writability... SUCCESS
2024-05-25 13:51:00,000 | INFO | /workspace/kohya_ss/kohya_gui/common_gui.py | Validating /workspace/kohya_ss/directory/model existence and writability... SUCCESS
2024-05-25 13:51:00,001 | INFO | /workspace/kohya_ss/kohya_gui/common_gui.py | Validating /workspace/stable-diffusion-webui/models/Stable-diffusion/ponyDiffusionV6XL_v6StartWithThisOne.safetensors existence... SUCCESS
2024-05-25 13:51:00,001 | INFO | /workspace/kohya_ss/kohya_gui/common_gui.py | Validating /workspace/kohya_ss/directory/img existence... SUCCESS
2024-05-25 13:51:00,002 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Folder 30_y_char woman: 30 repeats found
2024-05-25 13:51:00,002 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Folder 30_y_char woman: 19 images found
2024-05-25 13:51:00,003 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Folder 30_y_char woman: 19 * 30 = 570 steps
2024-05-25 13:51:00,003 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Regulatization factor: 1
2024-05-25 13:51:00,004 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Total steps: 570
2024-05-25 13:51:00,004 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Train batch size: 1
2024-05-25 13:51:00,004 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Gradient accumulation steps: 1
2024-05-25 13:51:00,005 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Epoch: 10
2024-05-25 13:51:00,005 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Max train steps: 1600
2024-05-25 13:51:00,006 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | stop_text_encoder_training = 0
2024-05-25 13:51:00,006 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | lr_warmup_steps = 160
2024-05-25 13:51:00,007 | WARNING | /workspace/kohya_ss/kohya_gui/common_gui.py | Here is the trainer command as a reference. It will not be executed:

2024-05-25 13:51:00,007 | INFO | /workspace/kohya_ss/kohya_gui/common_gui.py | /workspace/kohya_ss/venv/bin/accelerate launch --dynamo_backend no --dynamo_mode default --mixed_precision fp16 --num_processes 1 --num_machines 1 --num_cpu_threads_per_process 2 /workspace/kohya_ss/sd-scripts/sdxl_train_network.py --config_file /workspace/kohya_ss/directory/model/config_lora-20240525-135100.toml
2024-05-25 13:51:00,008 | INFO | /workspace/kohya_ss/kohya_gui/common_gui.py | Showing toml config file: /workspace/kohya_ss/directory/model/config_lora-20240525-135100.toml
2024-05-25 13:51:00,009 | INFO | /workspace/kohya_ss/kohya_gui/common_gui.py | bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
clip_skip = 1
dynamo_backend = "no"
enable_bucket = true
epoch = 10
gradient_accumulation_steps = 1
gradient_checkpointing = true
huber_c = 0.1
huber_schedule = "snr"
learning_rate = 0.0003
logging_dir = "/workspace/kohya_ss/directory/log"
loss_type = "l2"
lr_scheduler = "cosine"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 160
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_grad_norm = 1
max_timestep = 1000
max_token_length = 75
max_train_steps = 1600
min_bucket_reso = 256
mixed_precision = "fp16"
multires_noise_discount = 0.3
network_alpha = 1
network_args = []
network_dim = 256
network_module = "networks.lora"
no_half_vae = true
noise_offset_type = "Original"
optimizer_args = [ "scale_parameter=False", "relative_step=False", "warmup_init=False",]
optimizer_type = "AdamW8bit"
output_dir = "/workspace/kohya_ss/directory/model"
output_name = "y"
pretrained_model_name_or_path = "/workspace/stable-diffusion-webui/models/Stable-diffusion/ponyDiffusionV6XL_v6StartWithThisOne.safetensors"
prior_loss_weight = 1
resolution = "1024,1024"
sample_prompts = "/workspace/kohya_ss/directory/model/prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "bf16"
text_encoder_lr = 0.0003
train_batch_size = 1
train_data_dir = "/workspace/kohya_ss/directory/img"
unet_lr = 0.0003
xformers = true

2024-05-25 13:51:00,012 | INFO | /workspace/kohya_ss/kohya_gui/common_gui.py | end of toml config file: /workspace/kohya_ss/directory/model/config_lora-20240525-135100.toml
2024-05-25 13:51:03,717 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Start training LoRA Standard ...
2024-05-25 13:51:03,720 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Validating lr scheduler arguments...
2024-05-25 13:51:03,722 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Validating optimizer arguments...
2024-05-25 13:51:03,724 | INFO | /workspace/kohya_ss/kohya_gui/common_gui.py | Validating /workspace/kohya_ss/directory/log existence and writability... SUCCESS
2024-05-25 13:51:03,724 | INFO | /workspace/kohya_ss/kohya_gui/common_gui.py | Validating /workspace/kohya_ss/directory/model existence and writability... SUCCESS
2024-05-25 13:51:03,725 | INFO | /workspace/kohya_ss/kohya_gui/common_gui.py | Validating /workspace/stable-diffusion-webui/models/Stable-diffusion/ponyDiffusionV6XL_v6StartWithThisOne.safetensors existence... SUCCESS
2024-05-25 13:51:03,725 | INFO | /workspace/kohya_ss/kohya_gui/common_gui.py | Validating /workspace/kohya_ss/directory/img existence... SUCCESS
2024-05-25 13:51:03,726 | INFO | /workspace/kohya_ss/kohya_gui/common_gui.py | Headless mode, skipping verification if model already exist... if model already exist it will be overwritten...
2024-05-25 13:51:03,726 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Folder 30_y_char woman: 30 repeats found
2024-05-25 13:51:03,727 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Folder 30_y_char woman: 19 images found
2024-05-25 13:51:03,727 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Folder 30_y_char woman: 19 * 30 = 570 steps
2024-05-25 13:51:03,728 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Regulatization factor: 1
2024-05-25 13:51:03,728 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Total steps: 570
2024-05-25 13:51:03,728 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Train batch size: 1
2024-05-25 13:51:03,729 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Gradient accumulation steps: 1
2024-05-25 13:51:03,729 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Epoch: 10
2024-05-25 13:51:03,730 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Max train steps: 1600
2024-05-25 13:51:03,730 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | stop_text_encoder_training = 0
2024-05-25 13:51:03,730 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | lr_warmup_steps = 160
2024-05-25 13:51:03,731 | INFO | /workspace/kohya_ss/kohya_gui/lora_gui.py | Saving training config to /workspace/kohya_ss/directory/model/y_20240525-135103.json...
2024-05-25 13:51:03,732 | INFO | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Executing command: /workspace/kohya_ss/venv/bin/accelerate launch --dynamo_backend no --dynamo_mode default --mixed_precision fp16 --num_processes 1 --num_machines 1 --num_cpu_threads_per_process 2 /workspace/kohya_ss/sd-scripts/sdxl_train_network.py --config_file /workspace/kohya_ss/directory/model/config_lora-20240525-135103.toml
2024-05-25 13:51:03,733 | INFO | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Command executed.
2024-05-25 13:51:05,867 | DEBUG | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Waiting for training to end...
2024-05-25 13:51:06,868 | DEBUG | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Waiting for training to end...
2024-05-25 13:51:07,869 | DEBUG | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Waiting for training to end...
2024-05-25 13:51:08,870 | DEBUG | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Waiting for training to end...
2024-05-25 13:51:09,871 | DEBUG | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Waiting for training to end...
2024-05-25 13:51:10,873 | DEBUG | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Waiting for training to end...
2024-05-25 13:51:11,874 | DEBUG | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Waiting for training to end...
2024-05-25 13:51:12,875 | DEBUG | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Waiting for training to end...
2024-05-25 13:51:13,876 | DEBUG | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Waiting for training to end...
2024-05-25 13:51:14,878 | DEBUG | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Waiting for training to end...
2024-05-25 13:51:15,879 | DEBUG | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Waiting for training to end...
2024-05-25 13:51:16,880 | DEBUG | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Waiting for training to end...
2024-05-25 13:51:17,881 | DEBUG | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Waiting for training to end...
2024-05-25 13:51:18,883 | DEBUG | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Waiting for training to end...
2024-05-25 13:51:19,884 | DEBUG | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Waiting for training to end...
2024-05-25 13:51:20,885 | DEBUG | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Waiting for training to end...
2024-05-25 13:51:21,886 | DEBUG | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Waiting for training to end...
2024-05-25 13:51:22,887 | DEBUG | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Waiting for training to end...
2024-05-25 13:51:22,887 | INFO | /workspace/kohya_ss/kohya_gui/class_command_executor.py | Training has ended.
`

**Comment by Light-7777** [comment]
kohya_SS logs

```
23:15:25-499525 INFO     Command executed.                                      
/workspace/kohya_ss/venv/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
/workspace/kohya_ss/venv/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
2024-05-25 23:15:30.772890: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-25 23:15:30.772924: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-25 23:15:30.772942: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-05-25 23:15:30.777820: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/workspace/kohya_ss/venv/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
2024-05-25 23:15:32 INFO     Loading settings from            train_util.py:3744
                             /workspace/kohya_ss/lora2/model/                   
                             config_lora-20240525-231525.toml                   
                             ...                                                
                    INFO     /workspace/kohya_ss/lora2/model/ train_util.py:3763
                             config_lora-20240525-231525                        
2024-05-25 23:15:32 INFO     prepare tokenizers           sdxl_train_util.py:134
2024-05-25 23:15:33 INFO     update token length: 75      sdxl_train_util.py:159
                    INFO     Using DreamBooth method.       train_network.py:172
                    INFO     prepare images.                  train_util.py:1572
                    INFO     found directory                  train_util.py:1519
                             /workspace/kohya_ss/lora2/img/30                   
                             _yuuk1 woman contains 34 image                     
                             files                                              
                    INFO     1020 train images with           train_util.py:1613
                             repeating.                                         
                    INFO     0 reg images.                    train_util.py:1616
                    WARNING  no regularization images /       train_util.py:1621
                             正則化画像が見つかりませんでした                   
                    INFO     [Dataset 0]                      config_util.py:565
                               batch_size: 1                                    
                               resolution: (1024, 1024)                         
                               enable_bucket: True                              
                               network_multiplier: 1.0                          
                               min_bucket_reso: 256                             
                               max_bucket_reso: 2048                            
                               bucket_reso_steps: 64                            
                               bucket_no_upscale: True                          
                                                                                
                               [Subset 0 of Dataset 0]                          
                                 image_dir:                                     
                             "/workspace/kohya_ss/lora2/img/3                   
                             0_yuuk1 woman"                                     
                                 image_count: 34                                
                                 num_repeats: 30                                
                                 shuffle_caption: False                         
                                 keep_tokens: 0                                 
                                 keep_tokens_separator:                         
                                 secondary_separator: None                      
                                 enable_wildcard: False                         
                                 caption_dropout_rate: 0.0                      
                                 caption_dropout_every_n_epoc                   
                             hes: 0                                             
                                 caption_tag_dropout_rate:                      
                             0.0                                                
                                 caption_prefix: None                           
                                 caption_suffix: None                           
                                 color_aug: False                               
                                 flip_aug: False                                
                                 face_crop_aug_range: None                      
                                 random_crop: False                             
                                 token_warmup_min: 1,                           
                                 token_warmup_step: 0,                          
                                 is_reg: False                                  
                                 class_tokens: yuuk1 woman                      
                                 caption_extension: .txt                        
                                                                                
                                                                                
                    INFO     [Dataset 0]                      config_util.py:571
                    INFO     loading image sizes.              train_util.py:853
100%|██████████| 34/34 [00:00<00:00, 76423.55it/s]
                    INFO     make buckets                      train_util.py:859
                    WARNING  min_bucket_reso and               train_util.py:876
                             max_bucket_reso are ignored if                     
                             bucket_no_upscale is set, because                  
                             bucket reso is defined by image                    
                             size automatically /                               
                             bucket_no_upscaleが指定された場合                  
                             は、bucketの解像度は画像サイズか                   
                             ら自動計算されるため、min_bucket_                  
                             resoとmax_bucket_resoは無視されま                  
                             す                                                 
                    INFO     number of images (including       train_util.py:905
                             repeats) /                                         
                             各bucketの画像枚数（繰り返し回数                   
                             を含む）                                           
                    INFO     bucket 0: resolution (384, 704),  train_util.py:910
                             count: 60                                          
                    INFO     bucket 1: resolution (640, 896),  train_util.py:910
                             count: 30                                          
                    INFO     bucket 2: resolution (640, 960),  train_util.py:910
                             count: 30                                          
                    INFO     bucket 3: resolution (640, 1088), train_util.py:910
                             count: 120                                         
                    INFO     bucket 4: resolution (640, 1216), train_util.py:910
                             count: 30                                          
                    INFO     bucket 5: resolution (768, 1088), train_util.py:910
                             count: 30                                          
                    INFO     bucket 6: resolution (832, 704),  train_util.py:910
                             count: 30                                          
                    INFO     bucket 7: resolution (832, 1088), train_util.py:910
                             count: 30                                          
                    INFO     bucket 8: resolution (1024,       train_util.py:910
                             1024), count: 210                                  
                    INFO     bucket 9: resolution (1088, 832), train_util.py:910
                             count: 450                                         
                    INFO     mean ar error (without repeats):  train_util.py:915
                             0.024796466791225116                               
                    WARNING  clip_skip will be unexpected sdxl_train_util.py:343
                             /                                                  
                             SDXL学習ではclip_skipは動作                        
                             しません                                           
                    INFO     preparing accelerator          train_network.py:225
accelerator device: cuda
                    INFO     loading model for process 0/1 sdxl_train_util.py:30
                    INFO     load StableDiffusion          sdxl_train_util.py:70
                             checkpoint:                                        
                             /workspace/stable-diffusion-w                      
                             ebui/models/Stable-diffusion/                      
                             ponyDiffusionV6XL_v6StartWith                      
                             ThisOne.safetensors                                
                    INFO     building U-Net               sdxl_model_util.py:192
                    INFO     loading U-Net from           sdxl_model_util.py:196
                             checkpoint                                         
2024-05-25 23:15:35 INFO     U-Net: <All keys matched     sdxl_model_util.py:202
                             successfully>                                      
                    INFO     building text encoders       sdxl_model_util.py:205
                    INFO     loading text encoders from   sdxl_model_util.py:258
                             checkpoint                                         
                    INFO     text encoder 1: <All keys    sdxl_model_util.py:272
                             matched successfully>                              
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/workspace/kohya_ss/venv/bin/python3', '/workspace/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', '/workspace/kohya_ss/lora2/model/config_lora-20240525-231525.toml']' died with <Signals.SIGKILL: 9>.
```

**Comment by b-fission** [comment]
You are using these optimizer args `scale_parameter=False relative_step=False warmup_init=False` which are not applicable to AdamW8bit.

Try running it again without any of those options.
