### ISSUE TITLE
 Very crazy mistake! When I want to train, it reports an error! I don't know where the problem is! Can you help me?

### ISSUE THREAD

**Issue by dike1080** [bmaltais/kohya_ss#2546]
17:23:50-923757 INFO     Kohya_ss GUI version: v24.1.4
17:23:51-726265 INFO     Submodule initialized and updated.
17:23:51-726265 INFO     nVidia toolkit detected
17:23:53-757607 INFO     Torch 2.1.2+cu118
17:23:53-788883 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8905
17:23:53-804472 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12287 Arch (8, 6) Cores 28
17:23:53-804472 INFO     Python version is 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit
                         (AMD64)]
17:23:53-804472 INFO     Verifying modules installation status from requirements_pytorch_windows.txt...
17:23:53-804472 INFO     Verifying modules installation status from requirements_windows.txt...
17:23:53-820114 WARNING  Package wrong version: bitsandbytes 0.41.2.post2 required 0.43.0
17:23:53-820114 INFO     Installing package: bitsandbytes==0.43.0
17:23:59-724379 INFO     Verifying modules installation status from requirements.txt...
17:24:12-959364 INFO     headless: False
17:24:13-037471 INFO     Using shell=True when running external commands...
Running on local URL:  http://127.0.0.1:7860
IMPORTANT: You are using gradio version 4.26.0, however version 4.29.0 is available, please upgrade.
--------

To create a public link, set `share=True` in `launch()`.
17:27:16-700795 INFO     Copy E:/MLORA/IMG to E:/TEMPOUT\img/40_MLORA BK...
17:27:16-922097 INFO     Regularization images directory is missing... not copying regularisation images...
17:27:16-925048 INFO     Done creating kohya_ss training folder structure at E:/TEMPOUT...
17:27:33-065613 INFO     Start training LoRA Standard ...
17:27:33-066609 INFO     Validating lr scheduler arguments...
17:27:33-068604 INFO     Validating optimizer arguments...
17:27:33-069601 INFO     Validating E:/MLORA/LOG existence and writability... SUCCESS
17:27:33-070599 INFO     Validating E:/MLORA/MODELS existence and writability... SUCCESS
17:27:33-072593 INFO     Validating E:/XLMODEL/sd_xl_base_1.0.safetensors existence... SUCCESS
17:27:33-073591 INFO     Validating E:/MLORA/IMG existence... SUCCESS
17:27:33-076588 INFO     Folder 40_MLORA: 40 repeats found
17:27:33-077580 INFO     Folder 40_MLORA: 19 images found
17:27:33-080620 INFO     Folder 40_MLORA: 19 * 40 = 760 steps
17:27:33-082614 INFO     Regulatization factor: 1
17:27:33-084591 INFO     Total steps: 760
17:27:33-086585 INFO     Train batch size: 1
17:27:33-088581 INFO     Gradient accumulation steps: 1
17:27:33-089577 INFO     Epoch: 1
17:27:33-091572 INFO     Max train steps: 1600
17:27:33-093567 INFO     stop_text_encoder_training = 0
17:27:33-095840 INFO     lr_warmup_steps = 160
17:27:33-098832 INFO     Saving training config to E:/MLORA/MODELS\last_20240528-172733.json...
17:27:33-101825 INFO     Executing command: E:\kohya_ss\venv\Scripts\accelerate.EXE launch --dynamo_backend no
                         --dynamo_mode default --mixed_precision fp16 --num_processes 1 --num_machines 1
                         --num_cpu_threads_per_process 2 E:/kohya_ss/sd-scripts/sdxl_train_network.py --config_file
                         E:/MLORA/MODELS/config_lora-20240528-172733.toml
17:27:33-107668 INFO     Command executed.
2024-05-28 17:27:46 INFO     Loading settings from                                                    train_util.py:3744                             E:/MLORA/MODELS/config_lora-20240528-172733.toml...
                    INFO     E:/MLORA/MODELS/config_lora-20240528-172733                              train_util.py:37632024-05-28 17:27:46 INFO     prepare tokenizers                                                   sdxl_train_util.py:134Traceback (most recent call last):
  File "E:\kohya_ss\sd-scripts\sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "E:\kohya_ss\sd-scripts\train_network.py", line 154, in train
    tokenizer = self.load_tokenizer(args)
  File "E:\kohya_ss\sd-scripts\sdxl_train_network.py", line 53, in load_tokenizer
    tokenizer = sdxl_train_util.load_tokenizers(args)
  File "E:\kohya_ss\sd-scripts\library\sdxl_train_util.py", line 147, in load_tokenizers
    tokenizer = CLIPTokenizer.from_pretrained(original_path)
  File "E:\kohya_ss\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 2048, in from_pretrained
    return cls._from_pretrained(
  File "E:\kohya_ss\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 2225, in _from_pretrained
    special_tokens_map = json.load(special_tokens_map_handle)
  File "C:\PY310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\PY310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\PY310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\PY310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\PY310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\PY310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\kohya_ss\\venv\\Scripts\\python.exe', 'E:/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', 'E:/MLORA/MODELS/config_lora-20240528-172733.toml']' returned non-zero exit status 1.
17:27:48-492424 INFO     Training has ended.

**Comment by dike1080** [comment]
19:09:05-842456 INFO     Version: v22.4.0

19:09:05-851959 INFO     nVidia toolkit detected
19:09:07-713851 INFO     Torch 2.0.1+cu118
19:09:07-743835 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
19:09:07-748463 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12287 Arch (8, 6) Cores 28
19:09:07-751531 INFO     Verifying modules installation status from requirements_windows_torch2.txt...
19:09:07-755520 INFO     Verifying modules installation status from requirements.txt...
19:09:07-761504 WARNING  Package wrong version: huggingface-hub 0.23.2 required 0.19.4
19:09:07-763499 INFO     Installing package: huggingface-hub==0.19.4
E:\kohya_ss-22.4.0\venv\lib\site-packages\gradio_client\documentation.py:103: UserWarning: Could not get documentation group for <class 'gradio.mix.Parallel'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
E:\kohya_ss-22.4.0\venv\lib\site-packages\gradio_client\documentation.py:103: UserWarning: Could not get documentation group for <class 'gradio.mix.Series'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
19:09:17-091687 INFO     headless: False
19:09:17-099825 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
19:19:23-607274 INFO     Start training LoRA Standard ...
19:19:23-609269 INFO     Checking for duplicate image filenames in training data directory...
19:19:23-611264 INFO     Valid image folder names found in: E:/kohya_ss-22.4.0/train/image
19:19:23-613258 INFO     Folder 40_train: 19 images found
19:19:23-615253 INFO     Folder 40_train: 760 steps
19:19:23-617254 INFO     Total steps: 760
19:19:23-618245 INFO     Train batch size: 2
19:19:23-620250 INFO     Gradient accumulation steps: 1
19:19:23-621237 INFO     Epoch: 15
19:19:23-622235 INFO     Regulatization factor: 1
19:19:23-625226 INFO     max_train_steps (760 / 2 / 1 * 15 * 1) = 5700
19:19:23-627221 INFO     stop_text_encoder_training = 0
19:19:23-630213 INFO     lr_warmup_steps = 570
19:19:23-633204 INFO     Saving training config to E:/kohya_ss-22.4.0/train/model\train_20240528-191923.json...
19:19:23-635199 INFO     accelerate launch --num_cpu_threads_per_process=2 "./sdxl_train_network.py" --enable_bucket
                         --min_bucket_reso=256 --max_bucket_reso=2048
                         --pretrained_model_name_or_path="E:/XLMODEL/sd_xl_base_1.0.safetensors"
                         --train_data_dir="E:/kohya_ss-22.4.0/train/image" --resolution="1024,1024"
                         --output_dir="E:/kohya_ss-22.4.0/train/model" --logging_dir="E:/kohya_ss-22.4.0/train/log"
                         --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora
                         --text_encoder_lr=5e-05 --unet_lr=0.0001 --network_dim=8 --output_name="train"
                         --lr_scheduler_num_cycles="15" --no_half_vae --learning_rate="0.0001" --lr_scheduler="cosine"
                         --lr_warmup_steps="570" --train_batch_size="2" --max_train_steps="5700"
                         --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="bf16" --cache_latents
                         --optimizer_type="AdamW8bit" --max_grad_norm="1" --max_data_loader_n_workers="0"
                         --bucket_reso_steps=64 --gradient_checkpointing --xformers --bucket_no_upscale
                         --noise_offset=0.0
prepare tokenizers
Traceback (most recent call last):
  File "E:\kohya_ss-22.4.0\sdxl_train_network.py", line 189, in <module>
    trainer.train(args)
  File "E:\kohya_ss-22.4.0\train_network.py", line 154, in train
    tokenizer = self.load_tokenizer(args)
  File "E:\kohya_ss-22.4.0\sdxl_train_network.py", line 56, in load_tokenizer
    tokenizer = sdxl_train_util.load_tokenizers(args)
  File "E:\kohya_ss-22.4.0\library\sdxl_train_util.py", line 142, in load_tokenizers
    tokenizer = CLIPTokenizer.from_pretrained(original_path)
  File "E:\kohya_ss-22.4.0\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1825, in from_pretrained
    return cls._from_pretrained(
  File "E:\kohya_ss-22.4.0\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 2004, in _from_pretrained
    special_tokens_map = json.load(special_tokens_map_handle)
  File "C:\PY310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\PY310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\PY310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\PY310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\PY310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\PY310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\kohya_ss-22.4.0\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "E:\kohya_ss-22.4.0\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "E:\kohya_ss-22.4.0\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "E:\kohya_ss-22.4.0\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\kohya_ss-22.4.0\\venv\\Scripts\\python.exe', './sdxl_train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=E:/XLMODEL/sd_xl_base_1.0.safetensors', '--train_data_dir=E:/kohya_ss-22.4.0/train/image', '--resolution=1024,1024', '--output_dir=E:/kohya_ss-22.4.0/train/model', '--logging_dir=E:/kohya_ss-22.4.0/train/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=8', '--output_name=train', '--lr_scheduler_num_cycles=15', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=570', '--train_batch_size=2', '--max_train_steps=5700', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=bf16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_grad_norm=1', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.
