### ISSUE TITLE
Training Fails To Initialise

### ISSUE THREAD

**Issue by paulerbear** [bmaltais/kohya_ss#2555]
16:37:11-529713 INFO     Command executed.
C:\Program Files\Python310\python.exe: can't open file 'D:\\kohya_ss-master\\sd-scripts\\sdxl_train_network.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya_ss-master\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "D:\kohya_ss-master\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\kohya_ss-master\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "D:\kohya_ss-master\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohya_ss-master\\venv\\Scripts\\python.exe', 'D:/kohya_ss-master/sd-scripts/sdxl_train_network.py', '--config_file', 'D:/001-PROJECTS/LoRA-Training/Sensi-Cartoon-Character-LoRA/001-Dataset-Preparation-Destination\\model/config_lora-20240531-163711.toml']' returned non-zero exit status 2.
16:37:15-724357 INFO     Training has ended.

**Comment by paulerbear** [comment]
UPDATE: I had to manually download the contents of the sd-scripts folder separately

**Comment by bmaltais** [comment]
Make sure you glit clone --recursive the kohya_gui repo... if you don't recursivelly clone... or use a zip file of the repo... it will fail.
