### ISSUE TITLE
Error message on Paperspace when start training SDXL Lora

### ISSUE THREAD

**Issue by X004** [bmaltais/kohya_ss#2564]
I get this message first

Running setup_linux.py...
21:48:07-085846 INFO     Python version is 3.11.7 (main, Dec  8 2023, 18:56:58) [GCC 11.4.0]                                                                                                           
21:48:07-088725 ERROR    The current version of python (sys.version_info(major=3, minor=11, micro=7, releaselevel='final', serial=0)) is not appropriate to run Kohya_ss GUI                           
21:48:07-090173 ERROR    The python version needs to be greater or equal to 3.10.9 and less than 3.11.0 

So I just extend Python version to 3.12 in **setup - setup_common.py** and everything runs fine until i start training than I get this message:

Traceback (most recent call last):
  File "/notebooks/kohya_ss/venv/bin/accelerate", line 5, in <module>
    from accelerate.commands.accelerate_cli import main
  File "/notebooks/kohya_ss/venv/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 21, in <module>
    from accelerate.commands.estimate import estimate_command_parser
  File "/notebooks/kohya_ss/venv/lib/python3.11/site-packages/accelerate/commands/estimate.py", line 35, in <module>
    import timm
  File "/notebooks/kohya_ss/venv/lib/python3.11/site-packages/timm/__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "/notebooks/kohya_ss/venv/lib/python3.11/site-packages/timm/models/__init__.py", line 28, in <module>
    from .maxxvit import *
  File "/notebooks/kohya_ss/venv/lib/python3.11/site-packages/timm/models/maxxvit.py", line 225, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'timm.models.maxxvit.MaxxVitConvCfg'> for field conv_cfg is not allowed: use default_factory

How do I downgrade Python? or is there any other way to go around this? I have no issue Extracting Lora from Checkpoint or captioning images...

**Comment by busetolunay** [comment]
I get the same error, how to resolve?

**Comment by bbecausereasonss** [comment]
Getting same error for Flux now.
