### ISSUE TITLE
RuntimeError: The size of tensor a (64) must match the size of tensor b (62) at non-singleton dimension 3

### ISSUE THREAD

**Issue by ContrastingRealities** [bmaltais/kohya_ss#2579]
I'm having issues training a LoHa, this error always occurs right before training begins

steps:   0%|                                                                                  | 0/7776 [00:00<?, ?it/s]
epoch 1/18
Traceback (most recent call last):
  File "C:\Users\Alan\kohya_ss\train_network.py", line 1033, in <module>
    trainer.train(args)
  File "C:\Users\Alan\kohya_ss\train_network.py", line 810, in train
    noise_pred = self.call_unet(
  File "C:\Users\Alan\kohya_ss\train_network.py", line 123, in call_unet
    noise_pred = unet(noisy_latents, timesteps, text_conds).sample
  File "C:\Users\Alan\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Alan\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Alan\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 680, in forward
    return model_forward(*args, **kwargs)
  File "C:\Users\Alan\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 668, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "C:\Users\Alan\kohya_ss\venv\lib\site-packages\torch\amp\autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "C:\Users\Alan\kohya_ss\library\original_unet.py", line 1585, in forward
    sample, res_samples = downsample_block(
  File "C:\Users\Alan\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Alan\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Alan\kohya_ss\library\original_unet.py", line 1019, in forward
    hidden_states = resnet(hidden_states, temb)
  File "C:\Users\Alan\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Alan\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Alan\kohya_ss\library\original_unet.py", line 477, in forward
    output_tensor = input_tensor + hidden_states
RuntimeError: The size of tensor a (8) must match the size of tensor b (6) at non-singleton dimension 3
steps:   0%|                                                                                  | 0/7776 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Alan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Alan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alan\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\Alan\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\Alan\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\Users\Alan\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Alan\\kohya_ss\\venv\\Scripts\\python.exe', './train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=C:/Users/Alan/Downloads/anyloraCheckpoint_bakedvaeBlessedFp16 (1).safetensors', '--train_data_dir=C:/Users/Alan/Downloads/ShadowAndFaceFRevised', '--resolution=512,512', '--output_dir=C:/Users/Alan/Documents/ShadowAndFaceFRevised', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=lycoris.kohya', '--network_args', 'preset=full', 'conv_dim=1', 'conv_alpha=1', 'rank_dropout=0.1', 'module_dropout=0.1', 'use_tucker=False', 'use_scalar=False', 'rank_dropout_scale=False', 'algo=loha', 'train_norm=False', '--network_dropout=0', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=8', '--output_name=ShadowAndFaceFRevised', '--lr_scheduler_num_cycles=18', '--scale_weight_norms=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=778', '--train_batch_size=2', '--max_train_steps=7776', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--caption_extension=txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_grad_norm=1', '--max_data_loader_n_workers=0', '--clip_skip=2', '--bucket_reso_steps=64', '--shuffle_caption', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0', '--sample_sampler=euler_a', '--sample_prompts=C:/Users/Alan/Documents/ShadowAndFaceFRevised\\sample\\prompt.txt', '--sample_every_n_epochs=1']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
I suggest you try to reach the author of LyCORIS and raise this issue with him. Either an issue with LyCORIS or sd-scripts...

https://github.com/KohakuBlueleaf/LyCORIS/issues

**Comment by ContrastingRealities** [comment]
Thank you I will try that
