### ISSUE TITLE
Cannot use sdxl fine tune

### ISSUE THREAD

**Issue by D3voz** [bmaltais/kohya_ss#2583]
I have metadata created by the gui in kohya folder. But it says no metadata /meta_lat.json found

3522024-06-10 12:40:25 INFO     prepare tokenizers                                                   sdxl_train_util.py:138                    INFO     update token length: 150                                             sdxl_train_util.py:163                    INFO     Training with captions.                                                   sdxl_train.py:155Traceback (most recent call last):
  File "C:\ai\kohya_ss\sd-scripts\sdxl_train.py", line 944, in <module>
    train(args)
  File "C:\ai\kohya_ss\sd-scripts\sdxl_train.py", line 170, in train
    train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.dataset_group)
  File "C:\ai\kohya_ss\sd-scripts\library\config_util.py", line 483, in generate_dataset_group_by_blueprint
    dataset = dataset_klass(subsets=subsets, **asdict(dataset_blueprint.params))
  File "C:\ai\kohya_ss\sd-scripts\library\train_util.py", line 1683, in __init__
    raise ValueError(f"no metadata / メタデータファイルがありません: {subset.metadata_file}")
ValueError: no metadata / メタデータファイルがありません: /meta_lat.json
Traceback (most recent call last):
  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ai\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "C:\ai\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\ai\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\ai\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\ai\\kohya_ss\\venv\\Scripts\\python.exe', 'C:/ai/kohya_ss/sd-scripts/sdxl_train.py', '--config_file', 'C:/ai/kohya_ss/models/config_finetune-20240610-124010.toml']' returned non-zero exit status 1.
12:40:28-514579 INFO     Training has ended.

I tried with another windows pc. It didn't work . 

But it works with vast.ai which uses linux i think.

**Comment by D3voz** [comment]
Ok, checked with vast.ai . It doesn't work there too.

**Comment by D3voz** [comment]
Fixed it by adding   metadata_file_path = os.path.abspath('C:\\ai\\kohya_ss\\meta_lat.json') Under   def train(args):  
and changing to  -    else:
                logger.info("Training with captions.")
                user_config = {
                    "datasets": [
                        {
                            "subsets": [
                                {
                                    "image_dir": args.train_data_dir,
                                    "metadata_file": metadata_file_path,

**Comment by PsilAxis** [comment]
keep running into this issue with kohya and so i just switched to a different program for training that worked without an issue
