### ISSUE TITLE
Strange [Errno 13]. I think it's my fault.

### ISSUE THREAD

**Issue by annihilatered** [bmaltais/kohya_ss#2640]
Traceback (most recent call last):
  File "C:\Users\hidden4safety\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\hidden4safety\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\hidden4safety\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "C:\Users\hidden4safety\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\hidden4safety\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\hidden4safety\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\hidden4safety\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\hidden4safety\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\hidden4safety\Downloads\123ez\kohya_ss\kohya_gui\lora_gui.py", line 1255, in train_model
    with open(tmpfilename, "w", encoding="utf-8") as toml_file:
PermissionError: [Errno 13] Permission denied: '/config_lora-20240712-041040.toml'

**Comment by bmaltais** [comment]
Look like it can’t create the toml file in the model output folder. Make sure it is writable.

**Comment by b-fission** [comment]
Maybe they didn't specify an output folder yet since the path starts with /

**Comment by bmaltais** [comment]
Possible… and on docker based system like vast.ai / can’t usually be written to.
