### ISSUE TITLE
Cache latents error

### ISSUE THREAD

**Issue by DucPecc29** [bmaltais/kohya_ss#2641]
Hi,
I can't train model, i got everytime this error :
```
Traceback (most recent call last):
  File "E:\Stable-Diffusion\kohya_ss\sd-scripts\train_db.py", line 529, in <module>
    train(args)
  File "E:\Stable-Diffusion\kohya_ss\sd-scripts\train_db.py", line 149, in train
    train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
  File "E:\Stable-Diffusion\kohya_ss\sd-scripts\library\train_util.py", line 2080, in cache_latents
    dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)
  File "E:\Stable-Diffusion\kohya_ss\sd-scripts\library\train_util.py", line 1023, in cache_latents
    cache_batch_latents(vae, cache_to_disk, batch, subset.flip_aug, subset.random_crop)
  File "E:\Stable-Diffusion\kohya_ss\sd-scripts\library\train_util.py", line 2403, in cache_batch_latents
    image = load_image(info.absolute_path) if info.image is None else np.array(info.image, np.uint8)
  File "E:\Stable-Diffusion\kohya_ss\sd-scripts\library\train_util.py", line 2349, in load_image
    image = Image.open(image_path)
  File "E:\Stable-Diffusion\kohya_ss\venv\lib\site-packages\PIL\Image.py", line 3288, in open
    im = _open_core(fp, filename, prefix, formats)
  File "E:\Stable-Diffusion\kohya_ss\venv\lib\site-packages\PIL\Image.py", line 3275, in _open_core
    _decompression_bomb_check(im.size)
  File "E:\Stable-Diffusion\kohya_ss\venv\lib\site-packages\PIL\Image.py", line 3183, in _decompression_bomb_check
    raise DecompressionBombError(msg)
PIL.Image.DecompressionBombError: Image size (191102976 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.
Traceback (most recent call last):
  File "C:\Users\piroh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\piroh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Stable-Diffusion\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "E:\Stable-Diffusion\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "E:\Stable-Diffusion\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "E:\Stable-Diffusion\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\Stable-Diffusion\\kohya_ss\\venv\\Scripts\\python.exe', 'E:/Stable-Diffusion/kohya_ss/sd-scripts/train_db.py', '--config_file', 'E:/Stable-Diffusion/kohya_ss/outputs/config_dreambooth-20240712-183233.toml']' returned non-zero exit status 1.
18:32:53-434020 INFO     Training has ended.
```

Sometime it work but only with SD 1.5, i have hight resolution sample and want to make an SDXL Lora with 2048x2048.
GPU: RTX 4080

**Comment by DucPecc29** [comment]
Fixx bomb issue, picture too much large
