### ISSUE TITLE
SDXL Training Error - RuntimeError: NaN detected in latents

### ISSUE THREAD

**Issue by PENGUINADELIE** [bmaltais/kohya_ss#2674]
I am trying to create an SDXL LoRA using Runpod. My dataset consists of 25 images of women, each with a size of 1024x1024 pixels. I keep encountering error logs indicating issues with the images. All images are 1024x1024 pixels, and I've tried using both PNG and JPG formats, but the issue persists. Does anyone know how to fix this?

**[Error log]**
  File "/workspace/kohya_ss/sd-scripts/sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "/workspace/kohya_ss/sd-scripts/train_network.py", line 272, in train
    train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
  File "/workspace/kohya_ss/sd-scripts/library/train_util.py", line 2324, in cache_latents
    dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process, file_suffix)
  File "/workspace/kohya_ss/sd-scripts/library/train_util.py", line 1146, in cache_latents
    cache_batch_latents(vae, cache_to_disk, batch, subset.flip_aug, subset.alpha_mask, subset.random_crop)
  File "/workspace/kohya_ss/sd-scripts/library/train_util.py", line 2772, in cache_batch_latents
    raise RuntimeError(f"NaN detected in latents: {info.absolute_path}")
RuntimeError: NaN detected in latents: /workspace/data/img_xyzminji/40_xyzminji woman/xyzminji_(1).jpg
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/workspace/kohya_ss/venv/bin/python', '/workspace/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', '/workspace/data/model_lora/config_lora-20240729-035252.toml']' returned non-zero exit status 1.
03:53:26-826393 INFO     Training has ended.

**Comment by liushaog** [comment]
fp16 change to fb16 and checked full fb16

**Comment by 5KilosOfCheese** [comment]
Could you post your settings, the config file so we can see if there is something wrong there.

Also things you should check:
- Make sure there are no images with same file name, as in check that there is no `Image.jpg` and `Image.png` present. Otherwise there will be a conflict.

**Comment by PENGUINADELIE** [comment]
![슬라이드1](https://github.com/user-attachments/assets/50d77925-e505-4469-a92b-c97fce69d41a)
![슬라이드2](https://github.com/user-attachments/assets/f455a9be-ef21-4030-8111-e179f6a7b8ce)
![슬라이드3](https://github.com/user-attachments/assets/938ca6ad-c0a4-4ffa-bb87-83fd8385ad57)
![슬라이드4](https://github.com/user-attachments/assets/7083977d-49fa-403e-b181-004e7a1c2349)
![슬라이드5](https://github.com/user-attachments/assets/d328d527-8d48-4449-b650-9b2372264aec)
![슬라이드6](https://github.com/user-attachments/assets/88f4c6ff-0d06-4d6f-94d6-eac93003dc90)
![슬라이드7](https://github.com/user-attachments/assets/5bb8d853-07be-4840-a4cc-1a9f37433b23)
![슬라이드8](https://github.com/user-attachments/assets/d90ef942-0be9-4aef-9faf-e3d5c897016e)
![슬라이드9](https://github.com/user-attachments/assets/0e259020-2fc4-42f4-b796-eee8c4e42323)
![슬라이드10](https://github.com/user-attachments/assets/2c96dff1-6764-43b2-b6e0-00f720ef94ce)
![슬라이드11](https://github.com/user-attachments/assets/4f51f755-f4b6-411a-8677-c5b5103823b4)
![슬라이드12](https://github.com/user-attachments/assets/5555a2ae-4af8-4e76-9e82-0bdca1f220cb)
![슬라이드13](https://github.com/user-attachments/assets/b66a256b-aa7c-4da2-832f-6784a82b2ea5)
![슬라이드14](https://github.com/user-attachments/assets/83262126-c83c-4e3f-9dce-b981f4612afb)

**Comment by PENGUINADELIE** [comment]
> 설정과 구성 파일을 게시해 주시면 문제가 있는지 확인할 수 있을 것 같습니다.
> 
> 또한 확인해야 할 사항:
> 
> * 같은 파일 이름을 가진 이미지가 없는지 확인하세요. 존재하지 않는지 확인하세요 `Image.jpg`. `Image.png`그렇지 않으면 충돌이 발생합니다.
Thank you so much for answering my question. I've put together an image of how I prepared the data and what I clicked to get this result. Do you have any idea what might be causing this? I'd be very grateful for an answer.

**Comment by PENGUINADELIE** [comment]
> Could you post your settings, the config file so we can see if there is something wrong there.
> 
> Also things you should check:
> 
> * Make sure there are no images with same file name, as in check that there is no `Image.jpg` and `Image.png` present. Otherwise there will be a conflict.

**Thank you so much for answering my question. I've put together an image of how I prepared the data and what I clicked to get this result. Do you have any idea what might be causing this? I'd be very grateful for an answer.**

**Comment by PENGUINADELIE** [comment]
> I am trying to create an SDXL LoRA using Runpod. My dataset consists of 25 images of women, each with a size of 1024x1024 pixels. I keep encountering error logs indicating issues with the images. All images are 1024x1024 pixels, and I've tried using both PNG and JPG formats, but the issue persists. Does anyone know how to fix this?
> 
> **[Error log]** File "/workspace/kohya_ss/sd-scripts/sdxl_train_network.py", line 185, in trainer.train(args) File "/workspace/kohya_ss/sd-scripts/train_network.py", line 272, in train train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process) File "/workspace/kohya_ss/sd-scripts/library/train_util.py", line 2324, in cache_latents dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process, file_suffix) File "/workspace/kohya_ss/sd-scripts/library/train_util.py", line 1146, in cache_latents cache_batch_latents(vae, cache_to_disk, batch, subset.flip_aug, subset.alpha_mask, subset.random_crop) File "/workspace/kohya_ss/sd-scripts/library/train_util.py", line 2772, in cache_batch_latents raise RuntimeError(f"NaN detected in latents: {info.absolute_path}") RuntimeError: NaN detected in latents: /workspace/data/img_xyzminji/40_xyzminji woman/xyzminji_(1).jpg Traceback (most recent call last): File "/workspace/kohya_ss/venv/bin/accelerate", line 8, in sys.exit(main()) File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main args.func(args) File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command simple_launcher(args) File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd) subprocess.CalledProcessError: Command '['/workspace/kohya_ss/venv/bin/python', '/workspace/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', '/workspace/data/model_lora/config_lora-20240729-035252.toml']' returned non-zero exit status 1. 03:53:26-826393 INFO Training has ended.


![01](https://github.com/user-attachments/assets/e7829c1c-46fd-4caa-a015-dc058e4a6213)
![02](https://github.com/user-attachments/assets/ba4ec116-b6e4-443a-b6a1-fc024b1b4a1a)
![03](https://github.com/user-attachments/assets/cfa3633b-0a5e-4f28-8962-1bc63109abf5)
![04](https://github.com/user-attachments/assets/b855e771-6057-45d4-aa6f-65beaf3f2419)
![05](https://github.com/user-attachments/assets/dc44af76-6b24-4fc2-b22c-f5e07bb7204d)
![06](https://github.com/user-attachments/assets/6b713f50-2875-4e4d-99b4-fd3545fcc276)
![07](https://github.com/user-attachments/assets/f5c9061a-2805-490b-be0a-89d6bec57b48)
![08](https://github.com/user-attachments/assets/60e96dfb-cad8-40e4-ae97-d23642c63d64)
![09](https://github.com/user-attachments/assets/2dd25ea8-a46e-4bd8-99dd-3a6baea0660d)
![10](https://github.com/user-attachments/assets/9456ec3d-9923-4aea-b18a-3f6d8859c380)
![11](https://github.com/user-attachments/assets/41f1837e-a5b7-49ea-aecb-f9500c6f0522)
![12](https://github.com/user-attachments/assets/37d5be5d-271b-4986-adef-19c09fc78114)

**Comment by 5KilosOfCheese** [comment]
Disable the image augmentations (Crop, colour...), you can't use those while caching latents (except flip). Or disable caching of latents.

**Comment by b-fission** [comment]
@PENGUINADELIE 

You'll need to enable the **No half VAE** checkbox if you're getting the NaN detected error on SDXL.

**Comment by PENGUINADELIE** [comment]
> Disable the image augmentations (Crop, colour...), you can't use those while caching latents (except flip). Or disable caching of latents.



> Disable the image augmentations (Crop, colour...), you can't use those while caching latents (except flip). Or disable caching of latents.

Thank you so much for your reply. You helped me solve the problem!

**Comment by PENGUINADELIE** [comment]
> @PENGUINADELIE
> 
> You'll need to enable the **No half VAE** checkbox if you're getting the NaN detected error on SDXL.

The no half vae check worked well for me, thank you so much for your answer.

**Comment by choowkee** [comment]
> @PENGUINADELIE
> 
> You'll need to enable the **No half VAE** checkbox if you're getting the NaN detected error on SDXL.

Helped me as well. SDXL 1.0 base model was giving me errors when training a LORA but this solved it. Thanks!

**Comment by iootclab** [comment]
> [@PENGUINADELIE](https://github.com/PENGUINADELIE)
> 
> You'll need to enable the **No half VAE** checkbox if you're getting the NaN detected error on SDXL.如果你在 SDXL 中遇到 NaN 检测错误，需要勾选 No half VAE 复选框。

Thank you for helping me solve this problem.

**Comment by Sohlis-afk** [comment]
where to enable no half vae?
