### ISSUE TITLE
Having problems training with Error:  ValueError: torch.cuda.is_available() 

### ISSUE THREAD

**Issue by Fredrum** [bmaltais/kohya_ss#2692]
Hello and Thank you for providing this tool for everyone to use!
Your work is much appreciated! 
I'm looking forward to trying to create some lora's of my own!  :)

So I am running on a Win11 + RTX 3060 12GB.
I have cuda install globally as,
NVIDIA-SMI 551.23                 Driver Version: 551.23         CUDA Version: 12.4  

I have python 3.10.11 installed
I installed kohya_ss
I started a venv like this:  (in windows shell)
> C:\Users\fred_\AppData\Local\Programs\Python\Python310\python.exe -m venv venv
> .\venv\Scripts\activate
I checked the correct python is activated
I also check cuda was there, like this:
> python
>>> import torch
>>> torch.cuda.is_available()
True

so to me is seems good?

But once I click the start training button and after a short startup it exists with a:
ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU

Any idea what I'm doing wrong?
Thank You!

Full command output:

(venv) D:\ai\lora_train_1\kohya_ss>python kohya_gui.py
18:41:08-333168 INFO     headless: False
18:41:08-369584 INFO     Using shell=True when running external commands...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
18:41:28-127453 INFO     Loading config...
18:41:33-319535 INFO     Start training Dreambooth...
18:41:33-320535 INFO     Validating lr scheduler arguments...
18:41:33-321535 INFO     Validating optimizer arguments...
18:41:33-322535 INFO     Validating D:/ai/lora_train_1/out_loras existence and writability... SUCCESS
18:41:33-323535 INFO     Validating D:/ai/lora_train_1/out_loras existence and writability... SUCCESS
18:41:33-325037 INFO     Validating D:/ai/lora_train_1/kohya_ss/models/sd_xl_base_1.0.safetensors existence... SUCCESS
18:41:33-326040 INFO     Validating D:/ai/lora_train_1/training_image_folders existence... SUCCESS
18:41:33-327040 INFO     Folder 5_blanchelora: 5 repeats found
18:41:33-328041 INFO     Folder 5_blanchelora: 20 images found
18:41:33-329040 INFO     Folder 5_blanchelora: 20 * 5 = 100 steps
18:41:33-329040 INFO     Regulatization factor: 1
18:41:33-330040 INFO     Total steps: 100
18:41:33-331040 INFO     Train batch size: 2
18:41:33-331040 INFO     Gradient accumulation steps: 1
18:41:33-332040 INFO     Epoch: 10
18:41:33-332040 INFO     Max train steps: 1600
18:41:33-333040 INFO     lr_warmup_steps = 320
18:41:33-334542 INFO     Saving training config to D:/ai/lora_train_1/out_loras\blanchelora_20240805-184133.json...
18:41:33-335545 INFO     Executing command: D:\ai\lora_train_1\kohya_ss\venv\Scripts\accelerate.EXE launch --dynamo_backend no --dynamo_mode default --gpu_ids 1
                         --mixed_precision fp16 --num_processes 1 --num_machines 1 --num_cpu_threads_per_process 2 D:/ai/lora_train_1/kohya_ss/sd-scripts/sdxl_train.py
                         --config_file D:/ai/lora_train_1/out_loras/config_dreambooth-20240805-184133.toml
18:41:33-339545 INFO     Command executed.
2024-08-05 18:41:39 INFO     Loading settings from D:/ai/lora_train_1/out_loras/config_dreambooth-20240805-184133.toml...                                      train_util.py:4174
                    INFO     D:/ai/lora_train_1/out_loras/config_dreambooth-20240805-184133                                                                    train_util.py:4193
                    WARNING  clip_skip will be unexpected / SDXL学習ではclip_skipは動作しません                                                            sdxl_train_util.py:352
2024-08-05 18:41:39 INFO     prepare tokenizers                                                                                                            sdxl_train_util.py:138
2024-08-05 18:41:40 INFO     update token length: 75                                                                                                       sdxl_train_util.py:163
                    INFO     Using DreamBooth method.                                                                                                           sdxl_train.py:144
                    INFO     prepare images.                                                                                                                   train_util.py:1815
                    INFO     found directory D:\ai\lora_train_1\training_image_folders\5_blanchelora contains 20 image files                                   train_util.py:1762
                    INFO     100 train images with repeating.                                                                                                  train_util.py:1856
                    INFO     0 reg images.                                                                                                                     train_util.py:1859
                    WARNING  no regularization images / 正則化画像が見つかりませんでした                                                                       train_util.py:1864
                    INFO     [Dataset 0]                                                                                                                       config_util.py:572
                               batch_size: 2
                               resolution: (1024, 1024)
                               enable_bucket: True
                               network_multiplier: 1.0
                               min_bucket_reso: 256
                               max_bucket_reso: 2048
                               bucket_reso_steps: 64
                               bucket_no_upscale: True

                               [Subset 0 of Dataset 0]
                                 image_dir: "D:\ai\lora_train_1\training_image_folders\5_blanchelora"
                                 image_count: 20
                                 num_repeats: 5
                                 shuffle_caption: False
                                 keep_tokens: 0
                                 keep_tokens_separator:
                                 caption_separator: ,
                                 secondary_separator: None
                                 enable_wildcard: False
                                 caption_dropout_rate: 0.0
                                 caption_dropout_every_n_epoches: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 alpha_mask: False,
                                 is_reg: False
                                 class_tokens: blanchelora
                                 caption_extension: .txt

                    INFO     [Dataset 0]                                                                                                                       config_util.py:578
                    INFO     loading image sizes.                                                                                                               train_util.py:911
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 19953.87it/s]
                    INFO     make buckets                                                                                                                       train_util.py:917
                    WARNING  min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size          train_util.py:934
                             automatically /
                             bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視され
                             ます
                    INFO     number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）                                                    train_util.py:963
                    INFO     bucket 0: resolution (1024, 960), count: 5                                                                                         train_util.py:968
                    INFO     bucket 1: resolution (1024, 1024), count: 95                                                                                       train_util.py:968
                    INFO     mean ar error (without repeats): 0.0027903915761763763                                                                             train_util.py:973
                    INFO     prepare accelerator                                                                                                                sdxl_train.py:201
accelerator device: cpu
                    INFO     loading model for process 0/1                                                                                                  sdxl_train_util.py:33
                    INFO     load StableDiffusion checkpoint: D:/ai/lora_train_1/kohya_ss/models/sd_xl_base_1.0.safetensors                                 sdxl_train_util.py:74
                    INFO     building U-Net                                                                                                                sdxl_model_util.py:198
                    INFO     loading U-Net from checkpoint                                                                                                 sdxl_model_util.py:202
2024-08-05 18:41:42 INFO     U-Net: <All keys matched successfully>                                                                                        sdxl_model_util.py:208
                    INFO     building text encoders                                                                                                        sdxl_model_util.py:211
2024-08-05 18:41:43 INFO     loading text encoders from checkpoint                                                                                         sdxl_model_util.py:264
                    INFO     text encoder 1: <All keys matched successfully>                                                                               sdxl_model_util.py:278
                    INFO     text encoder 2: <All keys matched successfully>                                                                               sdxl_model_util.py:282
                    INFO     building VAE                                                                                                                  sdxl_model_util.py:285
                    INFO     loading VAE from checkpoint                                                                                                   sdxl_model_util.py:290
                    INFO     VAE: <All keys matched successfully>                                                                                          sdxl_model_util.py:293
Disable Diffusers' xformers
                    INFO     Enable xformers for U-Net                                                                                                         train_util.py:3040
Traceback (most recent call last):
  File "D:\ai\lora_train_1\kohya_ss\sd-scripts\sdxl_train.py", line 948, in <module>
    train(args)
  File "D:\ai\lora_train_1\kohya_ss\sd-scripts\sdxl_train.py", line 258, in train
    vae.set_use_memory_efficient_attention_xformers(args.xformers)
  File "D:\ai\lora_train_1\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 262, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "D:\ai\lora_train_1\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 258, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "D:\ai\lora_train_1\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 258, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "D:\ai\lora_train_1\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 258, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "D:\ai\lora_train_1\kohya_ss\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 255, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "D:\ai\lora_train_1\kohya_ss\venv\lib\site-packages\diffusers\models\attention_processor.py", line 260, in set_use_memory_efficient_attention_xformers
    raise ValueError(
ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU
Traceback (most recent call last):
  File "C:\Users\fred_\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\fred_\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\ai\lora_train_1\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "D:\ai\lora_train_1\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\ai\lora_train_1\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "D:\ai\lora_train_1\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\ai\\lora_train_1\\kohya_ss\\venv\\Scripts\\python.exe', 'D:/ai/lora_train_1/kohya_ss/sd-scripts/sdxl_train.py', '--config_file', 'D:/ai/lora_train_1/out_loras/config_dreambooth-20240805-184133.toml']' returned non-zero exit status 1.
18:41:46-559563 INFO     Training has ended.

**Comment by b-fission** [comment]
Your log says the training process is running with `--gpu_ids 1`

Did you manually fill the GPU IDs option under "Accelerate launch"? It should stay blank (see the screenshot below) unless your system has more than one GPU and you want to set which GPU to train on.
![gpuid](https://github.com/user-attachments/assets/9b00ed84-32fe-4b66-a840-024cf9d20b66)

**Comment by Fredrum** [comment]
Hi! Yes I manually set it to '1' because in the windows Task Manager I noticed that it seems to have a 'GPU' from my CPU 'Intel(R) UHD Graphics 770' and that called GPU 0 in the manager.
It lists my NVidia card as GPU 1.

But let me try and see what happens. I just don't want to risk start training on my CPU and not realize it.

**Comment by b-fission** [comment]
> I just don't want to risk start training on my CPU and not realize it.

Ironically, that's exactly what happened. This showed up on your log:
```
INFO prepare accelerator sdxl_train.py:201
accelerator device: cpu
```

And consequently, xformers can't run on a CPU.

**Comment by Fredrum** [comment]
Ok awesome I removed my entry and left that at default empty and now I don't get that error! :)
Instead I get another error heh, 
RuntimeError: NaN detected in latents: D:\ai\lora_train_1\training_image_folders\5_blanchelora\blanche_05.png

**Comment by b-fission** [comment]
That's a common one. You'll need to enable "No Half VAE" if you encounter that while training SDXL.

I think the checkbox for it is missing on the Dreambooth tab, so you may need to manually put in `--no_half_vae` on Advanced->Additional parameters

![vae](https://github.com/user-attachments/assets/6175d7b8-e8df-44a7-b631-3e3ddade60d8)

**Comment by Fredrum** [comment]
Nice thank you so much for the help! :)
I found another 'issue' that said the same and when I looked for the option I realized I had been reloading my settings into the 'Dreambooth' tab in not the Lora one! ouch!  I started with the Lora tab but then I forgot to select back after re-starts. Embarrasing.
But not it all seems to work after also checking that option! Sweet! 

Thanks so much!

**Comment by emosGambler** [comment]
For the original issue, reason is not compatible packages. Answer from https://github.com/bmaltais/kohya_ss/issues/1638#issuecomment-2606963865 helped me
