### ISSUE TITLE
Model train causes TypeError issue

### ISSUE THREAD

**Issue by RoG7eR** [bmaltais/kohya_ss#2700]
If I try to train a model, I get the following issue:

Traceback (most recent call last):
  File "E:\Important\Kohya\kohya_ss\sd-scripts\train_db.py", line 529, in <module>
    train(args)
  File "E:\Important\Kohya\kohya_ss\sd-scripts\train_db.py", line 149, in train
    train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
  File "E:\Important\Kohya\kohya_ss\sd-scripts\library\train_util.py", line 2324, in cache_latents
    dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process, file_suffix)
TypeError: ControlNetDataset.cache_latents() takes from 2 to 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "C:\Users\Abc\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Abc\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Important\Kohya\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "E:\Important\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "E:\Important\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "E:\Important\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\Important\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'E:/Important/Kohya/kohya_ss/sd-scripts/train_db.py', '--config_file', 'E:/Important/LoRA making/Model/config_dreambooth-20240808-101253.toml']' returned non-zero exit status 1.

Been trying to fix it on visual studio but no luck.

**Comment by b-fission** [comment]
Are you running the latest master branch, v24.1.5, or v24.1.6 of the gui?
I think something's wrong with the given version of sd-scripts.

Does the same error show up if you reverted back to v24.1.4

**Comment by RoG7eR** [comment]
It's the latest version: v24.1.6

**Comment by b-fission** [comment]
I'm suspecting v24.1.5 and the latest version pulled in an unstable dev copy of sd-scripts. I've had some other odd errors, and rolling back to v24.1.4 seems to work.

**Comment by RoG7eR** [comment]
It's the latest version: v24.1.6

Right, I'll check out the previous version.

**Comment by RoG7eR** [comment]
I tried v24.1.4 with sd-scripts v0.8.4, it didn't work. Here's the issue now: 

Traceback (most recent call last):
  File "E:\Important\Kohya\kohya_ss-24.1.4\sd-scripts\train_db.py", line 504, in <module>
    train(args)
  File "E:\Important\Kohya\kohya_ss-24.1.4\sd-scripts\train_db.py", line 185, in train
    train_dataloader = torch.utils.data.DataLoader(
  File "E:\Important\Kohya\kohya_ss-24.1.4\venv\lib\site-packages\torch\utils\data\dataloader.py", line 349, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "E:\Important\Kohya\kohya_ss-24.1.4\venv\lib\site-packages\torch\utils\data\sampler.py", line 140, in __init__
    raise ValueError(f"num_samples should be a positive integer value, but got num_samples={self.num_samples}")
ValueError: num_samples should be a positive integer value, but got num_samples=0
Traceback (most recent call last):
  File "C:\Users\Abc\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Abc\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Important\Kohya\kohya_ss-24.1.4\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "E:\Important\Kohya\kohya_ss-24.1.4\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "E:\Important\Kohya\kohya_ss-24.1.4\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "E:\Important\Kohya\kohya_ss-24.1.4\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\Important\\Kohya\\kohya_ss-24.1.4\\venv\\Scripts\\python.exe', 'E:/Important/Kohya/kohya_ss-24.1.4/sd-scripts/train_db.py', '--config_file', 'E:/Important/LoRA making/Model/config_dreambooth-20240808-214434.toml']' returned non-zero exit status 1.

I tried v0.8.5 but it yielded same error hence thought to another version but it turned out to be same.

Whilst installing kohya v24.1.4 it wouldn't grab the sd-script files hence I had to manually download them from the repository of that version and paste them into the folder.

**Comment by b-fission** [comment]
Are you trying to use a dataset config toml and masked loss? The past two error logs seem to imply that.

The dataloader error for `num_samples=0` means there were no images found. Does the path for `image_dir` actually exist and contain images?

**Comment by RoG7eR** [comment]
Oh alright, the path was correct but I will reinstall and try again.

**Comment by RoG7eR** [comment]
Thanks a lot dude, it's working all fine now. You are a lifesaver, thanks for all the efforts in troubleshooting.

**Comment by n0kovo** [comment]
![image](https://github.com/user-attachments/assets/56704b74-46b0-41d0-814f-419533ecc8dc)

sorry

**Comment by SeverianVoid** [comment]
I am running into the exact same error as was initially posted

"TypeError: ControlNetDataset.cache_latents() takes from 2 to 5 positional arguments but 6 were given"

After just updating with a git pull, using previously saved config.jsons to try and start training

Disabling cache latents and cache latents to disk did allow it to start training using the same exact config.json as previous training. Not sure what has changed

**Comment by 12309kajsd8123b** [comment]
Are there plans to fix this issue in near future?
I am running a TOML file for masked loss and the only way to progress to training is to disable caching latents. I have tried changing the mask images/source images file types, names etc. and sadly there is no change. 
v24.1.7
