### ISSUE TITLE
kohya_ss无法训练

### ISSUE THREAD

**Issue by Anshengsen** [bmaltais/kohya_ss#2702]
`00:37:34-733948 ERROR    Error: logging folder does not exist or does not contain logs.
00:37:38-572917 INFO     Start training LoRA Standard ...
00:37:38-573916 INFO     Validating lr scheduler arguments...
00:37:38-574917 INFO     Validating optimizer arguments...
00:37:38-575917 INFO     Validating D:\Downs\kohya_ss\kohya_ss\xhyq_v1.0\log existence and writability... SUCCESS
00:37:38-576918 INFO     Validating D:\Downs\kohya_ss\kohya_ss\xhyq_v1.0\model existence and writability... SUCCESS
00:37:38-577917 INFO     Validating runwayml/stable-diffusion-v1-5 existence... SKIPPING: huggingface.co model
00:37:38-578917 INFO     Validating D:\Downs\kohya_ss\kohya_ss\xhyq_v1.0\image existence... SUCCESS
00:37:38-579917 INFO     Folder 20_a gril: 20 repeats found
00:37:38-580916 INFO     Folder 20_a gril: 15 images found
00:37:38-580916 INFO     Folder 20_a gril: 15 * 20 = 300 steps
00:37:38-581918 INFO     Regulatization factor: 1
00:37:38-582917 INFO     Total steps: 300
00:37:38-582917 INFO     Train batch size: 1
00:37:38-583916 INFO     Gradient accumulation steps: 1
00:37:38-584917 INFO     Epoch: 5
00:37:38-584917 INFO     Max train steps: 1600
00:37:38-585916 INFO     stop_text_encoder_training = 0
00:37:38-586917 INFO     lr_warmup_steps = 160
00:37:38-588917 INFO     Saving training config to D:\Downs\kohya_ss\kohya_ss\xhyq_v1.0\model\last_20240813-003738.json...
00:37:38-589917 INFO     Executing command: D:\Downs\kohya_ss\kohya_ss\venv\Scripts\accelerate.EXE launch --dynamo_backend no --dynamo_mode default --mixed_precision fp16 --num_processes 1 --num_machines 1 --num_cpu_threads_per_process
                         10 D:/Downs/kohya_ss/kohya_ss/sd-scripts/train_network.py --config_file D:\Downs\kohya_ss\kohya_ss\xhyq_v1.0\model/config_lora-20240813-003738.toml
00:37:38-612916 INFO     Command executed.
2024-08-13 00:37:47 INFO     Loading settings from D:\Downs\kohya_ss\kohya_ss\xhyq_v1.0\model/config_lora-20240813-003738.toml...                                                                                          train_util.py:4174
Traceback (most recent call last):
  File "D:\Downs\kohya_ss\kohya_ss\venv\lib\site-packages\toml\decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "D:\Downs\kohya_ss\kohya_ss\venv\lib\site-packages\toml\decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "D:\Downs\kohya_ss\kohya_ss\venv\lib\site-packages\toml\decoder.py", line 866, in load_value
    raise ValueError("Reserved escape sequence used")
ValueError: Reserved escape sequence used

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Downs\kohya_ss\kohya_ss\sd-scripts\train_network.py", line 1239, in <module>
    args = train_util.read_config_from_file(args, parser)
  File "D:\Downs\kohya_ss\kohya_ss\sd-scripts\library\train_util.py", line 4176, in read_config_from_file
    config_dict = toml.load(f)
  File "D:\Downs\kohya_ss\kohya_ss\venv\lib\site-packages\toml\decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "D:\Downs\kohya_ss\kohya_ss\venv\lib\site-packages\toml\decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Reserved escape sequence used (line 13 column 1 char 255)
Traceback (most recent call last):
  File "D:\Downs\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Downs\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Downs\kohya_ss\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "D:\Downs\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\Downs\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "D:\Downs\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\Downs\\kohya_ss\\kohya_ss\\venv\\Scripts\\python.exe', 'D:/Downs/kohya_ss/kohya_ss/sd-scripts/train_network.py', '--config_file', 'D:\\Downs\\kohya_ss\\kohya_ss\\xhyq_v1.0\\model/config_lora-20240813-003738.toml']' returned non-zero exit status 1.
00:37:48-825222 INFO     Training has ended.`

**Comment by Anshengsen** [comment]
I need help😭

**Comment by b-fission** [comment]
Make sure your folder paths are using forward slash /
and not backslashes \

example OK:
```
D:/Downs/kohya_ss/kohya_ss/xhyq_v1.0/log
D:/Downs/kohya_ss/kohya_ss/xhyq_v1.0/model
D:/Downs/kohya_ss/kohya_ss/xhyq_v1.0/image
```
...

example BAD:
```
D:\Downs\kohya_ss\kohya_ss\xhyq_v1.0\log
D:\Downs\kohya_ss\kohya_ss\xhyq_v1.0\model
D:\Downs\kohya_ss\kohya_ss\xhyq_v1.0\image
```

**Comment by Anshengsen** [comment]
> 确保您的文件夹路径使用正斜杠 / 而不是反斜杠 \
> 
> 示例确定：
> 
> ```
> D:/Downs/kohya_ss/kohya_ss/xhyq_v1.0/log
> D:/Downs/kohya_ss/kohya_ss/xhyq_v1.0/model
> D:/Downs/kohya_ss/kohya_ss/xhyq_v1.0/image
> ```
> 
> ...
> 
> 示例错误：
> 
> ```
> D:\Downs\kohya_ss\kohya_ss\xhyq_v1.0\log
> D:\Downs\kohya_ss\kohya_ss\xhyq_v1.0\model
> D:\Downs\kohya_ss\kohya_ss\xhyq_v1.0\image
> ```

However, this path was not manually entered by me, but was automatically triggered when the command was executed. How can I modify it?😭

**Comment by b-fission** [comment]
The paths should be coming from the gui where you input the folders.

**Comment by Anshengsen** [comment]
Do I need to reinstall kohya_ss and CUDN?

**Comment by b-fission** [comment]
> Do I need to reinstall kohya_ss and CUDN?

No

**Comment by Anshengsen** [comment]
Then should I set parameters in the ui or do I need specific operation?

**Comment by Anshengsen** [comment]
> > 我需要重新安装 kohya_ss 和 CUDN 吗？
> 
> 不

Then should I set parameters in the ui or do I need specific operation?

**Comment by b-fission** [comment]
Can you show me what your paths look like in the config GUI?
If you are using backslashes \  in the paths like the example below, it can cause the error.

![paths1](https://github.com/user-attachments/assets/20e6231c-fd13-4235-88e7-29c3cb39b312)
