### ISSUE TITLE
Please Help with sudden error while training lora model!

### ISSUE THREAD

**Issue by vantablackndark** [bmaltais/kohya_ss#2703]
I have no clue what this means, please if someone understand how to solve this issue, much appreciated!
I did reinstall Kohya + Python from scratch and ended with same issue
I have no idea what caused this.

 Diffusion\Dev\01\XL\Styles\horror\xenomorph\raw\model/config_lora-202408
                             13-071413.toml...
Traceback (most recent call last):
  File "E:\AI\Kohya\kohya_ss\venv\lib\site-packages\toml\decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "E:\AI\Kohya\kohya_ss\venv\lib\site-packages\toml\decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "E:\AI\Kohya\kohya_ss\venv\lib\site-packages\toml\decoder.py", line 866, in load_value
    raise ValueError("Reserved escape sequence used")
ValueError: Reserved escape sequence used

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\AI\Kohya\kohya_ss\sd-scripts\train_network.py", line 1239, in <module>
    args = train_util.read_config_from_file(args, parser)
  File "E:\AI\Kohya\kohya_ss\sd-scripts\library\train_util.py", line 4176, in read_config_from_file
    config_dict = toml.load(f)
  File "E:\AI\Kohya\kohya_ss\venv\lib\site-packages\toml\decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "E:\AI\Kohya\kohya_ss\venv\lib\site-packages\toml\decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Reserved escape sequence used (line 14 column 1 char 285)
Traceback (most recent call last):
  File "C:\Users\malyn\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\malyn\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\AI\Kohya\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "E:\AI\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "E:\AI\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "E:\AI\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\AI\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'E:/AI/Kohya/kohya_ss/sd-scripts/train_network.py', '--config_file', 'F:\\untited\\Stable Diffusion\\Dev\\01\\XL\\Styles\\horror\\xenomorph\\raw\\model/config_lora-20240813-071413.toml']' returned non-zero exit status 1.
07:14:23-125036 INFO     Training has ended.

**Comment by b-fission** [comment]
Someone else had the same error today.
It looks like you're using a backslash \ in your folder paths. You need to make them forward slash /

For example, your output directory might look like
`....Diffusion\Dev\01\XL\Styles\horror\xenomorph\raw\model`

change those slashes to the correct form
`....Diffusion/Dev/01/XL/Styles/horror/xenomorph/raw/model`

Ideally the gui should already be doing this, so it may possibly be a bug somewhere.
