### ISSUE TITLE
SDXL training error failure on caching latents

### ISSUE THREAD

**Issue by mgscab** [bmaltais/kohya_ss#2708]
as of yesterday apparently my training parameters have stopped working. 

I have no idea what may have caused it. 

here's the error output

have attempted to reinstall python 3.10.9 but that also seems to have failed. 
```
Traceback (most recent call last):
  File "D:\Downloads\kohyascripts3\kohya_ss\sd-scripts\sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "D:\Downloads\kohyascripts3\kohya_ss\sd-scripts\train_network.py", line 272, in train
    train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
  File "D:\Downloads\kohyascripts3\kohya_ss\sd-scripts\library\train_util.py", line 2080, in cache_latents
    dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)
  File "D:\Downloads\kohyascripts3\kohya_ss\sd-scripts\library\train_util.py", line 1023, in cache_latents
    cache_batch_latents(vae, cache_to_disk, batch, subset.flip_aug, subset.random_crop)
  File "D:\Downloads\kohyascripts3\kohya_ss\sd-scripts\library\train_util.py", line 2416, in cache_batch_latents
    latents = vae.encode(img_tensors).latent_dist.sample().to("cpu")
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\autoencoders\autoencoder_kl.py", line 260, in encode
    h = self.encoder(x)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\autoencoders\vae.py", line 143, in forward
    sample = self.conv_in(sample)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (770 x 2). Kernel size: (3 x 3). Kernel size can't be greater than actual input size
Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\<user>\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', 'D:/Downloads/kohyascripts3/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', 'E:/SD/backup/<training>/config_lora-20240815-162121.toml', '--optimizer_args', 'weight_decay=0.01', 'd_coef=1', 'use_bias_correction=True', 'safeguard_warmup=False', 'betas=0.9,0.99']' returned non-zero exit status 1.
```
`

**Comment by nokeyfan** [comment]
Hi, take a look here: https://github.com/bmaltais/kohya_ss/issues/1149. Post with a similar runtime error, error because off too small images for buckets.

**Comment by mgscab** [comment]
ah, thanks, I now realize one of the images I had was too thin even after upscaling 
thanks
