### ISSUE TITLE
please add lora merge for flux for the gui, sd scripts has it

### ISSUE THREAD

**Issue by DarkViewAI** [bmaltais/kohya_ss#2714]

**Comment by diodiogod** [comment]
I have tried it, but I always get this error; anyone manage to merge a flux lora? (they are from AIToolkit), I did check the "Diffusers LoRA" parameter. I actually tried them all, same error:

```
2024-08-24 08:36:22 INFO     loading:                    flux_merge_lora.py:374
                             J:/stablediffusion1111s2/Da                       
                             ta/Models/Lora/flux/my/a/                       
                             Flux_v3_014.safete                       
                             nsors                                             
                    INFO     dim: [], alpha: []          flux_merge_lora.py:405
                    INFO     merging...                  flux_merge_lora.py:408
  0%|          | 0/988 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "J:\stablediffusion1111s2\Data\Packages\kohya_ss\sd-scripts\networks\flux_merge_lora.py", line 621, in <module>
    merge(args)
  File "J:\stablediffusion1111s2\Data\Packages\kohya_ss\sd-scripts\networks\flux_merge_lora.py", line 523, in merge
    state_dict, metadata = merge_lora_models(args.models, args.ratios, merge_dtype, args.concat, args.shuffle)
  File "J:\stablediffusion1111s2\Data\Packages\kohya_ss\sd-scripts\networks\flux_merge_lora.py", line 422, in merge_lora_models
    base_alpha = base_alphas[lora_module_name]
KeyError: 'transformer.single_transformer_blocks.0.attn.to_k'

```

**Comment by RayHell** [comment]
+1 same issue
