### ISSUE TITLE
AssertionError: train_blocks must be single for split mode

### ISSUE THREAD

**Issue by gurilagardnr** [bmaltais/kohya_ss#2722]
I've got split mode on, and train_blocks=single

Why does it die?

Kohya_FLUX\kohya_ss\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:480: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
attn_output = torch.nn.functional.scaled_dot_product_attention(
Traceback (most recent call last):
File "J:\Kohya_FLUX\kohya_ss\sd-scripts\flux_train_network.py", line 408, in
trainer.train(args)
File "J:\Kohya_FLUX\kohya_ss\sd-scripts\train_network.py", line 1099, in train
noise_pred, target, timesteps, huber_c, weighting = self.get_noise_pred_and_target(
File "J:\Kohya_FLUX\kohya_ss\sd-scripts\flux_train_network.py", line 323, in get_noise_pred_and_target
assert network.train_blocks == "single", "train_blocks must be single for split mode"
AssertionError: train_blocks must be single for split mode
steps: 0%| | 0/3000 [00:03<?, ?it/s]
Traceback (most recent call last):
File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Program Files\Python310\lib\runpy.py", line 86, in run_code
exec(code, run_globals)
File "J:\Kohya_FLUX\kohya_ss\venv\Scripts\accelerate.EXE_main.py", line 7, in
File "J:\Kohya_FLUX\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
args.func(args)
File "J:\Kohya_FLUX\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
simple_launcher(args)
File "J:\Kohya_FLUX\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['J:\Kohya_FLUX\kohya_ss\venv\Scripts\python.exe', 'J:/Kohya_FLUX/kohya_ss/sd-scripts/flux_train_network.py', '--config_file', 'J:/workspace/jeff-flux/model/config_lora-20240820-015605.toml']' returned non-zero exit status 1.
02:00:54-726899 INFO Training has ended.
[myconfig.json](https://github.com/user-attachments/files/16677485/myconfig.json)

**Comment by gurilagardnr** [comment]
Well, you changed something with the latest commit because the issue magically disappeared using same config.  so, thanks.
