### ISSUE TITLE
TypeError: Adafactor.__init__() got an unexpected keyword argument 'fused_backward_pass'

### ISSUE THREAD

**Issue by michP247** [bmaltais/kohya_ss#2759]
Apparently 'fused_backward_pass' has been implemented according to this 2a359e0
But I'm not sure how to use it, I get an error:

Traceback (most recent call last):
  File "C:\AI-Stuff\kohya_ss\sd-scripts\train_db.py", line 529, in <module>
    train(args)
  File "C:\AI-Stuff\kohya_ss\sd-scripts\train_db.py", line 185, in train
    _, _, optimizer = train_util.get_optimizer(args, trainable_params)
  File "C:\AI-Stuff\kohya_ss\sd-scripts\library\train_util.py", line 4522, in get_optimizer
    optimizer = optimizer_class(trainable_params, lr=lr, **optimizer_kwargs)
TypeError: Adafactor.__init__() got an unexpected keyword argument 'fused_backward_pass'
Traceback (most recent call last):
  File "C:\Users\jnpie\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jnpie\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\AI-Stuff\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "C:\AI-Stuff\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\AI-Stuff\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\AI-Stuff\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\AI-Stuff\\kohya_ss\\venv\\Scripts\\python.exe', 'C:/AI-Stuff/kohya_ss/sd-scripts/train_db.py', '--config_file', 'C:\\AI-Stuff\\Characters\\Training\\model/config_dreambooth-20240830-092733.toml']' returned non-zero exit status 1.

Is this the correct way to set this argument?
![Screenshot](https://github.com/user-attachments/assets/22b988a9-5d40-45fb-88ca-c4125f05bfa8)

**Comment by b-fission** [comment]
The current release (v24.1.6) doesn't have it yet, so you'll need to switch over to dev branch to try it. When you do, it will appear under SDXL Specific Parameters.

![sdxl](https://github.com/user-attachments/assets/57a8e3ef-3290-46c5-ab9b-9868408ac7c1)

**Comment by michP247** [comment]
> The current release (v24.1.6) doesn't have it yet, so you'll need to switch over to dev branch to try it. When you do, it will appear under SDXL Specific Parameters.
> 
> ![sdxl](https://private-user-images.githubusercontent.com/131207849/363269405-57a8e3ef-3290-46c5-ab9b-9868408ac7c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMzgzNTMsIm5iZiI6MTcyNTAzODA1MywicGF0aCI6Ii8xMzEyMDc4NDkvMzYzMjY5NDA1LTU3YThlM2VmLTMyOTAtNDZjNS1hYjliLTk4Njg0MDhhYzdjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQxNzE0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTcxM2ViZTk2Yzk0ZGQ0NGE5ZDk1YzdlZjFkMmE5NDJkZjE4N2IwOTI2ZTkzZDYzYzU0NjczMzQ4YjYzMjllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.skrUSzic9GRjql9tsQXEbYlBTcFNtcMMmrjQAuTs9xA)

noted thx
