### ISSUE TITLE
Help Question - Permission set

### ISSUE THREAD

**Issue by AsaTyr2018** [bmaltais/kohya_ss#2762]
### Intro:
Good day,
this is not an Issue with Kohya_SS itself. But i hope someone of you can help me.

here is the thing. I run a Ubuntu 22.04.4 LTS GPU Cluster.
To run all my AI´s (A1111/Forge, Fooocus etc....) smoothly via a web gui, i set services for each one.
While all others working perfectly fine, Kohya_SS refuse.

It starts smoothly and i can set everything for training and capture.
Once the Proccess starts. it just throw this error in the logs and refuse to work. (Error Code at the end)

I set a central storage at /aicore and give the main user (hle) and the root recursive full authority. (Read, write, execute)
I will also include the service File. 

### Directory Rights:

(kohya-env) hle@aicore:/aicore$ ls -lisa
 3145733 4 drwxrwsrwx  3 root root 4096 Aug 31 14:08 dataset
 3145763 4 drwxrwsrwx  2 root root 4096 Aug 30 20:40 envs
 3145731 4 drwxrwsrwx 32 root root 4096 Aug 30 20:01 models
 3145732 4 drwxrwsrwx  5 root root 4096 Aug 30 20:16 output
 3145730 4 drwxrwsrwx  8 root root 4096 Aug 30 17:32 server
17563649 4 drwxrwsrwx  3 root root 4096 Aug 30 20:11 web

Mainfolder:
3145729       4 drwxrwsrwx   9 root root       4096 Aug 31 12:33 aicore

### Servicefile:
[Unit]
Description=Kohya_ss Training Service
After=network.target

[Service]
User=hle
WorkingDirectory=/aicore/server/kohya_ss
ExecStart=/home/hle/.pyenv/versions/kohya-env/bin/python /aicore/server/kohya_ss/kohya_gui.py --listen 0.0.0.0
Restart=always

SyslogIdentifier=Kohya
StandardOutput=journal
StandardError=journal
Environment=PYTHONUNBUFFERED=1

ProtectSystem=false
ProtectHome=false

[Install]
WantedBy=multi-user.target

### Error:
Aug 31 14:09:16 aicore Kohya[334841]: Traceback (most recent call last):
Aug 31 14:09:16 aicore Kohya[334841]:   File "/home/hle/.pyenv/versions/kohya-env/lib/python3.10/site-packages/gradio/queueing.py", line 532, in process_events
Aug 31 14:09:16 aicore Kohya[334841]:     response = await route_utils.call_process_api(
Aug 31 14:09:16 aicore Kohya[334841]:   File "/home/hle/.pyenv/versions/kohya-env/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
Aug 31 14:09:16 aicore Kohya[334841]:     output = await app.get_blocks().process_api(
Aug 31 14:09:16 aicore Kohya[334841]:   File "/home/hle/.pyenv/versions/kohya-env/lib/python3.10/site-packages/gradio/blocks.py", line 1928, in process_api
Aug 31 14:09:16 aicore Kohya[334841]:     result = await self.call_function(
Aug 31 14:09:16 aicore Kohya[334841]:   File "/home/hle/.pyenv/versions/kohya-env/lib/python3.10/site-packages/gradio/blocks.py", line 1514, in call_function
Aug 31 14:09:16 aicore Kohya[334841]:     prediction = await anyio.to_thread.run_sync(
Aug 31 14:09:16 aicore Kohya[334841]:   File "/home/hle/.pyenv/versions/kohya-env/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
Aug 31 14:09:16 aicore Kohya[334841]:     return await get_async_backend().run_sync_in_worker_thread(
Aug 31 14:09:16 aicore Kohya[334841]:   File "/home/hle/.pyenv/versions/kohya-env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
Aug 31 14:09:16 aicore Kohya[334841]:     return await future
Aug 31 14:09:16 aicore Kohya[334841]:   File "/home/hle/.pyenv/versions/kohya-env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
Aug 31 14:09:16 aicore Kohya[334841]:     result = context.run(func, *args)
Aug 31 14:09:16 aicore Kohya[334841]:   File "/home/hle/.pyenv/versions/kohya-env/lib/python3.10/site-packages/gradio/utils.py", line 832, in wrapper
Aug 31 14:09:16 aicore Kohya[334841]:     response = f(*args, **kwargs)
Aug 31 14:09:16 aicore Kohya[334841]:   File "/aicore/server/kohya_ss/kohya_gui/wd14_caption_gui.py", line 127, in caption_images
Aug 31 14:09:16 aicore Kohya[334841]:     subprocess.run(run_cmd, env=env)
Aug 31 14:09:16 aicore Kohya[334841]:   File "/home/hle/.pyenv/versions/3.10.6/lib/python3.10/subprocess.py", line 501, in run
Aug 31 14:09:16 aicore Kohya[334841]:     with Popen(*popenargs, **kwargs) as process:
Aug 31 14:09:16 aicore Kohya[334841]:   File "/home/hle/.pyenv/versions/3.10.6/lib/python3.10/subprocess.py", line 969, in __init__
Aug 31 14:09:16 aicore Kohya[334841]:     self._execute_child(args, executable, preexec_fn, close_fds,
Aug 31 14:09:16 aicore Kohya[334841]:   File "/home/hle/.pyenv/versions/3.10.6/lib/python3.10/subprocess.py", line 1845, in _execute_child
Aug 31 14:09:16 aicore Kohya[334841]:     raise child_exception_type(errno_num, err_msg, err_filename)
Aug 31 14:09:16 aicore Kohya[334841]: PermissionError: [Errno 13] Permission denied: ''

**Comment by AsaTyr2018** [comment]
Got it solved with a little 'Dirty' trick.
created a shell file and added this in the service file. now the service starts the shell script witch activated the pyenv and then starts kohya. not the 'wonderfull' way but it do that trick ^^ Still thanks =)
