### ISSUE TITLE
PydanticSchemaGenerationError for class starlette.requests.Request

### ISSUE THREAD

**Issue by Mark-Reiser** [bmaltais/kohya_ss#2783]
Hi, 

I did a fresh install via git clone and then install venv.
However, within the web UI I can´t press any button.

There always comes the following error -- please help:

20:25:05-475127 INFO     Kohya_ss GUI version: v24.1.6
20:25:06-124442 INFO     Submodule initialized and updated.
20:25:06-128434 INFO     nVidia toolkit detected
20:25:08-140996 INFO     Torch 2.1.2+cu118
20:25:08-162538 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8905
20:25:08-165540 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9) Cores 128
20:25:08-171524 INFO     Python version is 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit
                         (AMD64)]
20:25:08-174893 INFO     Verifying modules installation status from requirements_pytorch_windows.txt...
20:25:08-177885 INFO     Verifying modules installation status from requirements_windows.txt...
20:25:08-180876 INFO     Verifying modules installation status from requirements.txt...
20:25:17-088963 INFO     headless: False
20:25:17-143523 INFO     Using shell=True when running external commands...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\type_adapter.py", line 279, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\type_adapter.py", line 121, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\gradio\route_utils.py", line 720, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\gradio\route_utils.py", line 736, in simple_response
    await self.app(scope, receive, send)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\fastapi\routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\fastapi\dependencies\utils.py", line 639, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\fastapi\dependencies\utils.py", line 810, in request_body_to_args
    fields_to_extract = get_model_fields(first_field.type_)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\fastapi\_compat.py", line 283, in get_model_fields
    return [
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\fastapi\_compat.py", line 284, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\fastapi\_compat.py", line 109, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\type_adapter.py", line 266, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\type_adapter.py", line 144, in wrapped
    return func(self, *args, **kwargs)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\type_adapter.py", line 286, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\type_adapter.py", line 104, in _get_schema
    schema = gen.generate_schema(type_)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2025, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2104, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2186, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2182, in <lambda>
    lambda source, handler: handler(source)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2085, in inner_handler    schema = self._generate_schema_inner(obj)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1378, in _union_schema    choices.append(self.generate_schema(arg))
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
  File "E:\SD\kohya\kohya_ss\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type

**Comment by cobanov** [comment]
Same here

**Comment by xcrashdayx** [comment]
can confirm same here. fresh install from 5th sept 20:00

**Comment by Websteria** [comment]
Same exact thing.

**Comment by RayHell** [comment]
+1

**Comment by cobanov** [comment]
It's temporary solution but, you can modify the `requirements.txt` file to downgrade the gradio package to version 3.50.2. 

`gradio==3.50.2`

**Comment by Websteria** [comment]
That works for now. Thank you!!!

**Comment by DanielCurtiss** [comment]
I was stuck for two hours. cobanov`s solution was the only one to work

**Comment by FurkanGozukara** [comment]
> It's temporary solution but, you can modify the `requirements.txt` file to downgrade the gradio package to version 3.50.2.
> 
> `gradio==3.50.2`

i made better one fast api 0.111.0 at my auto installer :D

**Comment by PheonixAi420** [comment]
> It's temporary solution but, you can modify the `requirements.txt` file to downgrade the gradio package to version 3.50.2.
> 
> `gradio==3.50.2`

Wow yeah this quick fix works. I have been thinking all day it was me having an issue. Thanks!!

**Comment by bmaltais** [comment]
> It's temporary solution but, you can modify the `requirements.txt` file to downgrade the gradio package to version 3.50.2.
> 
> `gradio==3.50.2`

This is too old a release to even think of rolling back. So the issue is caused by a fastapi change?

**Comment by phillipxkang** [comment]
> > It's temporary solution but, you can modify the `requirements.txt` file to downgrade the gradio package to version 3.50.2.
> > `gradio==3.50.2`
> 
> This is too old a release to even think of rolling back. So the issue is caused by a fastapi change?

@bmaltais I fixed this by pinning gradio to 4.43.0

**Comment by MasterRuma** [comment]
> It's temporary solution but, you can modify the `requirements.txt` file to downgrade the gradio package to version 3.50.2.
> 
> `gradio==3.50.2`

thanks! it works!

**Comment by henryruhs** [comment]
Use latest `gradio==4.43.0`

see changelog: https://github.com/gradio-app/gradio/blob/main/CHANGELOG.md#4430
