### ISSUE TITLE
resize lora flux - slow

### ISSUE THREAD

**Issue by kalle07** [bmaltais/kohya_ss#2804]
its must be a bug  ;)
why is it such as slow
from float to fp16

i use CUDA 16GB Vram (8GB used)
on SDXL it was maybe one minute
FLUX is 20min

and no check if new file name right:

2024-09-11 16:29:11 INFO     resizing complete                                                        resize_lora.py:294
                    INFO     saving model to: .safetensors                                            resize_lora.py:356
Traceback (most recent call last):
  File "e:\kohya_ss\sd-scripts\networks\resize_lora.py", line 411, in <module>
    resize(args)
  File "e:\kohya_ss\sd-scripts\networks\resize_lora.py", line 357, in resize
    save_to_file(args.save_to, state_dict, save_dtype, metadata)
  File "e:\kohya_ss\sd-scripts\networks\resize_lora.py", line 51, in save_to_file
    torch.save(state_dict, file_name)
  File "e:\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 651, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "e:\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 525, in _open_zipfile_writer
    return container(name_or_buffer)
  File "e:\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 496, in __init__
    super().__init__(torch._C.PyTorchFileWriter(self.name))
RuntimeError: [enforce fail at inline_container.cc:642] . invalid file name: .safetensors
16:29:12-773619 INFO     Done resizing...

and no Stop Button

i mean the resized lora works ...

**Comment by kalle07** [comment]
and btw you could check if its realy right RANK and Network Alpha
and more importand if float and fp16 is set right
for me 
Save precision Fp16, RANK 32, Alpha 4 -> filesize ~300MB
on civitai ( idont know how they save?)
RANK 32, Alpha 4 -> filesize ~38MB

**Comment by kalle07** [comment]
no one have slow speed on resize ?
