### ISSUE TITLE
Runway removed repo, so 1.5 training will not download model

### ISSUE THREAD

**Issue by revolvedai** [bmaltais/kohya_ss#2806]
Since Runway completely shut down their account, the repo link for 1.5 no longer works to download the model.

```
Traceback (most recent call last):

  File "/miniconda3/envs/KOYA/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status

    response.raise_for_status()

  File "/miniconda3/envs/KOYA/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/runwayml/stable-diffusion-v1-5
```

**Comment by revolvedai** [comment]
It has been hosted here, perhaps we could switch to this?
https://huggingface.co/benjamin-paine/stable-diffusion-v1-5

The person who hosted it turned on the permission flag but it's on auto approve.
