### ISSUE TITLE
"No module named 'global_state'" in gui.bat

### ISSUE THREAD

**Issue by AndreR** [bmaltais/kohya_ss#2814]
Whenever I run gui.bat on my Windows 11 machine, get the following error:

```
PS P:\AI\kohya_ss\kohya_ss> .\gui.bat
18:34:13-251402 INFO     Kohya_ss GUI version: v24.1.7
git: 'submodule' is not a git command. See 'git --help'.
18:34:15-681950 ERROR    Error during Git operation: Command '['git', 'submodule', 'update', '--init', '--recursive',
                         '--quiet']' returned non-zero exit status 1.
18:34:15-684952 INFO     nVidia toolkit detected
18:34:19-214034 INFO     Torch 2.1.2+cu118
18:34:20-358960 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
18:34:20-361959 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9) Cores 128
18:34:20-362971 INFO     Python version is 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit
                         (AMD64)]
18:34:20-363961 INFO     Verifying modules installation status from requirements_pytorch_windows.txt...
18:34:20-365963 INFO     Verifying modules installation status from requirements_windows.txt...
18:34:20-367965 INFO     Verifying modules installation status from requirements.txt...
Traceback (most recent call last):
  File "P:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\easygui\boxes\utils.py", line 29, in <module>
    import tkinter as tk  # python3
ModuleNotFoundError: No module named 'tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "P:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\easygui\boxes\utils.py", line 36, in <module>
    import Tkinter as tk  # python2
ModuleNotFoundError: No module named 'Tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "P:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\easygui\boxes\button_box.py", line 15, in <module>
    from . import utils as ut
  File "P:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\easygui\boxes\utils.py", line 43, in <module>
    raise ImportError("Unable to find tkinter package.")
ImportError: Unable to find tkinter package.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "P:\AI\kohya_ss\kohya_ss\kohya_gui.py", line 4, in <module>
    from kohya_gui.class_gui_config import KohyaSSGUIConfig
  File "P:\AI\kohya_ss\kohya_ss\kohya_gui\class_gui_config.py", line 2, in <module>
    from .common_gui import scriptdir
  File "P:\AI\kohya_ss\kohya_ss\kohya_gui\common_gui.py", line 5, in <module>
    from easygui import msgbox, ynbox
  File "P:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\easygui\__init__.py", line 34, in <module>
    from .boxes.button_box import buttonbox
  File "P:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\easygui\boxes\button_box.py", line 18, in <module>
    import global_state
ModuleNotFoundError: No module named 'global_state'
```

All mentioned modules should be installed:

```
PS P:\AI\kohya_ss\kohya_ss> pip install tk
Requirement already satisfied: tk in p:\ai\forge ai image generator\system\python\lib\site-packages (0.1.0)
PS P:\AI\kohya_ss\kohya_ss> pip install --upgrade easygui
Requirement already satisfied: easygui in p:\ai\forge ai image generator\system\python\lib\site-packages (0.98.3)
```

How can I fix that?

**Comment by kopyl** [comment]
Same thing. The gui does not run because of this

**Comment by Rocketman1105** [comment]
It looks like tkinter isn't handled by pip for some reason. You have to have it installed as a package on your system, for the right version of python.
On ubuntu that was: ```sudo apt-get install python3.10-tk```
There is probably a manual install of some kind you will need to do on windows.

**Comment by driqeks** [comment]
I have the same issue

**Comment by PresTrembleyIIIEsq** [comment]
Anyone else still running into this? I tried running `sudo apt-get install python3.10-tk`, but I just get: `E: Unable to locate package python3.10-tk`

This is on Ubuntu, latest version, trying a fresh install.

**Comment by PresTrembleyIIIEsq** [comment]
> It looks like tkinter isn't handled by pip for some reason. You have to have it installed as a package on your system, for the right version of python. On ubuntu that was: `sudo apt-get install python3.10-tk` There is probably a manual install of some kind you will need to do on windows.

Did you confirm this? I tried running `sudo apt-get install python3.10-tk`, but I just get: `E: Unable to locate package python3.10-tk`

This is on Ubuntu, latest version, trying a fresh install.

**Comment by PresTrembleyIIIEsq** [comment]
> I have the same issue

Did you ever end up finding a solution?

**Comment by Rocketman1105** [comment]
> Did you confirm this? I tried running `sudo apt-get install python3.10-tk`, but I just get: `E: Unable to locate package python3.10-tk`
> 
> This is on Ubuntu, latest version, trying a fresh install.

Sorry, I forgot that I had the deadsnakes repo added.
After running `sudo add-apt-repository ppa:deadsnakes/ppa` I am then able to install tkinter with `sudo apt-get install python3.10-tk`

**Comment by PresTrembleyIIIEsq** [comment]
> Sorry, I forgot that I had the deadsnakes repo added. After running `sudo add-apt-repository ppa:deadsnakes/ppa` I am then able to install tkinter with `sudo apt-get install python3.10-tk`

I feel like I'm going crazy here - I did those two steps, and it worked fine the first time, and then for unrelated reasons I had to delete the whole Kohya_ss installation and start over.

Now while installing again, I can run setup.sh without any issues, but when I run gui.sh, I get `ModuleNotFoundError: No module named '_tkinter'` and `ModuleNotFoundError: No module named 'global_state'` errors.

So I take your advice again and run `sudo add-apt-repository ppa:deadsnakes/ppa`, which seems to work, and then `sudo apt-get install python3.10-tk`, which now gives me the following. Any ideas?

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python3.10-tk
E: Couldn't find any package by glob 'python3.10-tk'
E: Couldn't find any package by regex 'python3.10-tk'
```
