### ISSUE TITLE
cant start training   File "D:\KohyaNew\kohya_ss\kohya_gui\lora_gui.py", line 994, in train_model     if max_train_steps > 0 and stop_text_encoder_training > 0: TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by DarkViewAI** [bmaltais/kohya_ss#2817]
12:08:38-630149 INFO     Dataset config TOML file used; skipping calculations for total_steps, train_batch_size, gradient_accumulation_steps,
                         epoch, reg_factor, and max_train_steps.
Traceback (most recent call last):
  File "D:\KohyaNew\kohya_ss\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\KohyaNew\kohya_ss\venv\lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\KohyaNew\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "D:\KohyaNew\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\KohyaNew\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\KohyaNew\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "D:\KohyaNew\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "D:\KohyaNew\kohya_ss\venv\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "D:\KohyaNew\kohya_ss\kohya_gui\lora_gui.py", line 994, in train_model
    if max_train_steps > 0 and stop_text_encoder_training > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by DarkViewAI** [comment]
works on this commit dedda58c5e362cd0c1fc2abd271c89d3ab07994e

not sure what has changed

**Comment by bmaltais** [comment]
I pushed a fix for it. Give it a try

**Comment by DarkViewAI** [comment]
@bmaltais 

seem to be getting this now

Traceback (most recent call last):
  File "D:\KohyaNew\kohya_ss\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\KohyaNew\kohya_ss\venv\lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\KohyaNew\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "D:\KohyaNew\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\KohyaNew\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\KohyaNew\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "D:\KohyaNew\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "D:\KohyaNew\kohya_ss\venv\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "D:\KohyaNew\kohya_ss\kohya_gui\lora_gui.py", line 1014, in train_model
    log.info(max_train_steps_info)
UnboundLocalError: local variable 'max_train_steps_info' referenced before assignment

**Comment by bmaltais** [comment]
OK, I have reverted a bunch of updates. Give it a try now.

**Comment by DarkViewAI** [comment]
@bmaltais thank you very much! works now :)
