### ISSUE TITLE
Training has ended

### ISSUE THREAD

**Issue by jigrain** [bmaltais/kohya_ss#2824]
Recently downloaded kohya_ss and did everything according to the instructions then prepared the dataset and started training lora. In the process I always get this error:

```
Traceback (most recent call last):
  File "D:\programming\kohya_ss\sd-scripts\sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "D:\programming\kohya_ss\sd-scripts\train_network.py", line 222, in train
    self.assert_extra_args(args, train_dataset_group)
  File "D:\programming\kohya_ss\sd-scripts\sdxl_train_network.py", line 33, in assert_extra_args
    train_dataset_group.verify_bucket_reso_steps(32)
  File "D:\programming\kohya_ss\sd-scripts\library\train_util.py", line 2353, in verify_bucket_reso_steps
    dataset.verify_bucket_reso_steps(min_steps)
  File "D:\programming\kohya_ss\sd-scripts\library\train_util.py", line 1009, in verify_bucket_reso_steps
    assert self.bucket_reso_steps is None or self.bucket_reso_steps % min_steps == 0, (
AssertionError: bucket_reso_steps is 1. it must be divisible by 32.
bucket_reso_stepsが1です。32で割り切れる必要があります
Traceback (most recent call last):
  File "D:\Programs\Python_3_10\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Programs\Python_3_10\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\programming\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "D:\programming\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\programming\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "D:\programming\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\programming\\kohya_ss\\venv\\Scripts\\python.exe', 'D:/programming/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', 'C:\\Users\\Admin\\Desktop\\ruina-sprite\\lora\\model/config_lora-20240915-152623.toml']' returned non-zero exit status 1.
```

I can write you the training parameters if it helps.

**Comment by iamrohitanshu** [comment]
@jigrain Your error says this: `bucket_reso_steps` is `1`. it must be divisible by `32`
Can you check if it resolves your issue?
