### ISSUE TITLE
LR warmup error AttributeError: 'BasicTraining' object has no attribute 'old_lr_warmup_steps'. Did you mean: 'lr_warmup_steps'?

### ISSUE THREAD

**Issue by Kikunu** [bmaltais/kohya_ss#2834]
Traceback (most recent call last):
  File "E:\Kohya_GUI_Flux_Installer_21\kohya_ss\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "E:\Kohya_GUI_Flux_Installer_21\kohya_ss\venv\lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Kohya_GUI_Flux_Installer_21\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "E:\Kohya_GUI_Flux_Installer_21\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "E:\Kohya_GUI_Flux_Installer_21\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\Kohya_GUI_Flux_Installer_21\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "E:\Kohya_GUI_Flux_Installer_21\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "E:\Kohya_GUI_Flux_Installer_21\kohya_ss\venv\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "E:\Kohya_GUI_Flux_Installer_21\kohya_ss\kohya_gui\class_basic_training.py", line 324, in lr_scheduler_changed
    if self.old_lr_warmup_steps != 0:
AttributeError: 'BasicTraining' object has no attribute 'old_lr_warmup_steps'. Did you mean: 'lr_warmup_steps'?

**Comment by bmaltais** [comment]
Should be fixed in the latest commit.
