### ISSUE TITLE
returned non-zero exit status 3221225477.

### ISSUE THREAD

**Issue by max-k54** [bmaltais/kohya_ss#2843]
NEED HELP, getting this issue when training Lora in Kohya SS

11:00:26-382341 INFO Command executed.

2024-09-21 11:00:40 INFO Loading settings from D:\sd\oil train_util.py:4174

paint\loras\model/config_dreambooth-20240921-110026.toml...

INFO D:\sd\oil paint\loras\model/config_dreambooth-20240921-110026 train_util.py:4193

WARNING clip_skip will be unexpected / SDXL学習ではclip_skipは動作しません sdxl_train_util.py:352

2024-09-21 11:00:40 INFO prepare tokenizers sdxl_train_util.py:138

2024-09-21 11:00:42 INFO update token length: 75 sdxl_train_util.py:163

INFO Using DreamBooth method. sdxl_train.py:144

INFO prepare images. train_util.py:1815

INFO found directory D:\sd\oil paint\loras\img\20_ohwx man contains 12 image train_util.py:1762

files

WARNING No caption file found for 12 images. Training will continue without train_util.py:1793

captions for these images. If class token exists, it will be used. /

12枚の画像にキャプションファイルが見つかりませんでした。これらの画像につ

いてはキャプションなしで学習を続行します。class

tokenが存在する場合はそれを使います。

WARNING D:\sd\oil paint\loras\img\20_ohwx man\mordecai (1).png train_util.py:1800

WARNING D:\sd\oil paint\loras\img\20_ohwx man\mordecai (10).png train_util.py:1800

WARNING D:\sd\oil paint\loras\img\20_ohwx man\mordecai (11).png train_util.py:1800

WARNING D:\sd\oil paint\loras\img\20_ohwx man\mordecai (12).png train_util.py:1800

WARNING D:\sd\oil paint\loras\img\20_ohwx man\mordecai (2).png train_util.py:1800

WARNING D:\sd\oil paint\loras\img\20_ohwx man\mordecai (3).png... and 7 more train_util.py:1798

INFO 240 train images with repeating. train_util.py:1856

INFO 0 reg images. train_util.py:1859

WARNING no regularization images / 正則化画像が見つかりませんでした train_util.py:1864

INFO [Dataset 0] config_util.py:572

batch_size: 1

resolution: (768, 768)

enable_bucket: True

network_multiplier: 1.0

min_bucket_reso: 256

max_bucket_reso: 2048

bucket_reso_steps: 64

bucket_no_upscale: True

[Subset 0 of Dataset 0]

image_dir: "D:\sd\oil paint\loras\img\20_ohwx man"

image_count: 12

num_repeats: 20

shuffle_caption: False

keep_tokens: 0

keep_tokens_separator:

caption_separator: ,

secondary_separator: None

enable_wildcard: False

caption_dropout_rate: 0.0

caption_dropout_every_n_epoches: 0

caption_tag_dropout_rate: 0.0

caption_prefix: None

caption_suffix: None

color_aug: False

flip_aug: False

face_crop_aug_range: None

random_crop: False

token_warmup_min: 1,

token_warmup_step: 0,

alpha_mask: False,

is_reg: False

class_tokens: ohwx man

caption_extension: .txt

INFO [Dataset 0] config_util.py:578

INFO loading image sizes. train_util.py:911

100%|█████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 160.37it/s]

INFO make buckets train_util.py:917

WARNING min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is train_util.py:934

set, because bucket reso is defined by image size automatically /

bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計

算されるため、min_bucket_resoとmax_bucket_resoは無視されます

INFO number of images (including repeats) / train_util.py:963

各bucketの画像枚数（繰り返し回数を含む）

INFO bucket 0: resolution (768, 768), count: 240 train_util.py:968

INFO mean ar error (without repeats): 0.0 train_util.py:973

INFO prepare accelerator sdxl_train.py:201

accelerator device: cuda

INFO loading model for process 0/1 sdxl_train_util.py:33

INFO load StableDiffusion checkpoint: sdxl_train_util.py:74

D:/sd/sd.webui/webui/models/Stable-diffusion/sd_xl_base_1.0.safetenso

rs

Traceback (most recent call last):

File "C:\Users\smart\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main

return _run_code(code, main_globals, None,

File "C:\Users\smart\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code

exec(code, run_globals)

File "D:\sd\kohya_ss\venv\Scripts\accelerate.EXE_main_.py", line 7, in <module>

File "D:\sd\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main

args.func(args)

File "D:\sd\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command

simple_launcher(args)

File "D:\sd\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher

raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

subprocess.CalledProcessError: Command '['D:\sd\kohya_ss\venv\Scripts\python.exe', 'D:/sd/kohya_ss/sd-scripts/sdxl_train.py', '--config_file', 'D:\sd\oil paint\loras\model/config_dreambooth-20240921-110026.toml']' returned non-zero exit status 3221225477.

11:01:00-603863 INFO Training has ended.

**Comment by kitamo1981** [comment]
U sure that you choose LORA from tab (not Dreambooth)?

**Comment by max-k54** [comment]
> U sure that you choose LORA from tab (not Dreambooth)?

Yes i chose the lora section

**Comment by b-fission** [comment]
> Yes i chose the lora section

Are you sure? If you did, your log should contain a few mentions of `train_network`
but I'm seeing `sdxl_train.py` which sounds like Dreambooth.
