### ISSUE TITLE
Overwrite pop up error on RunPod - no desktop UI - sd3-flux.1

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#2849]
I had same file name and overwrite pop up gave below error

Run on ubuntu - no desktop - Jupyterlab interface - tested on sd3-flux.1 branch

```
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/workspace/kohya_ss/kohya_gui/dreambooth_gui.py", line 699, in train_model
    if not print_only and check_if_model_exist(
  File "/workspace/kohya_ss/kohya_gui/common_gui.py", line 141, in check_if_model_exist
    if not ynbox(msg, "Overwrite Existing Model?"):
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/derived_boxes.py", line 54, in ynbox
    return boolbox(msg=msg,
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/derived_boxes.py", line 133, in boolbox
    reply = buttonbox(msg=msg,
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 95, in buttonbox
    bb = ButtonBox(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 147, in __init__
    self.ui = GUItk(msg, title, choices, images, default_choice, cancel_choice, self.callback_ui)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 263, in __init__
    self.boxRoot = tk.Tk()
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

**Comment by hben35096** [comment]
Me too
