### ISSUE TITLE
after 1epoch,the trainning is interrunpt,can not load the pre-trained data

### ISSUE THREAD

**Issue by Lecho303** [bmaltais/kohya_ss#2856]
i was setting 3epochs,but the 1epoch finished,the sample was not creat,and send this error:
  generating sample images at step / サンプル画像生成 ステップ: 2100       train_util.py:5569
2024-09-27 01:42:06 INFO     prompt: masterpiece,1big bowl, chopped green onion,Chicken soup, waste   train_util.py:5722
                             paper placed in the bottom of the bowl to dissipate
                             heat,warmlight,Chinese-food-style
2024-09-27 01:42:07 INFO     negative_prompt: low quality, worst quality, bad anatomy, bad            train_util.py:5723
                             composition, poor, low effort
                    INFO     height: 1200                                                             train_util.py:5724
                    INFO     width: 1024                                                              train_util.py:5725
                    INFO     sample_steps: 20                                                         train_util.py:5726
                    INFO     scale: 7.5                                                               train_util.py:5727
                    INFO     sample_sampler: euler_a                                                  train_util.py:5728
                    INFO     seed: 1                                                                  train_util.py:5730
C:\Users\ningl\kohya_ss\venv\lib\site-packages\torch\utils\checkpoint.py:61: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
                                                                                                                       Traceback (most recent call last):
  File "C:\Users\ningl\kohya_ss\sd-scripts\sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "C:\Users\ningl\kohya_ss\sd-scripts\train_network.py", line 1085, in train
    self.sample_images(accelerator, args, epoch + 1, global_step, accelerator.device, vae, tokenizer, text_encoder, unet)
  File "C:\Users\ningl\kohya_ss\sd-scripts\sdxl_train_network.py", line 168, in sample_images
    sdxl_train_util.sample_images(accelerator, args, epoch, global_step, device, vae, tokenizer, text_encoder, unet)
  File "C:\Users\ningl\kohya_ss\sd-scripts\library\sdxl_train_util.py", line 381, in sample_images
    return train_util.sample_images_common(SdxlStableDiffusionLongPromptWeightingPipeline, *args, **kwargs)
  File "C:\Users\ningl\kohya_ss\sd-scripts\library\train_util.py", line 5644, in sample_images_common
    sample_image_inference(
  File "C:\Users\ningl\kohya_ss\sd-scripts\library\train_util.py", line 5732, in sample_image_inference
    latents = pipeline(
  File "C:\Users\ningl\kohya_ss\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ningl\kohya_ss\sd-scripts\library\sdxl_lpw_stable_diffusion.py", line 1012, in __call__
    noise_pred = self.unet(latent_model_input, t, text_embedding, vector_embedding)
  File "C:\Users\ningl\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\ningl\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ningl\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 680, in forward
    return model_forward(*args, **kwargs)
  File "C:\Users\ningl\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 668, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "C:\Users\ningl\kohya_ss\venv\lib\site-packages\torch\amp\autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "C:\Users\ningl\kohya_ss\sd-scripts\library\sdxl_original_unet.py", line 1110, in forward
    h = torch.cat([h, hs.pop()], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 76 but got size 75 for tensor number 1 in the list.
steps:  25%|▎| 2100/8400 [33:10:44<99:32:13, 56.88s/it, Average key norm=tensor(2.4855, device='cuda:0'), Keys Scaled=t
Traceback (most recent call last):
  File "C:\Users\ningl\miniconda3\envs\kohyass\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ningl\miniconda3\envs\kohyass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ningl\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "C:\Users\ningl\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\ningl\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\Users\ningl\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\ningl\\kohya_ss\\venv\\Scripts\\python.exe', 'C:/Users/ningl/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', 'C:/Users/ningl/Desktop/2new/model/config_lora-20240925-163127.toml']' returned non-zero exit status 1.
01:42:38-420432 INFO     Training has ended.

and i want to try loading the last Resume,found the 1epoch-state folder,then getting start,then i got this error:
Traceback (most recent call last):
  File "C:\Users\ningl\kohya_ss\sd-scripts\sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "C:\Users\ningl\kohya_ss\sd-scripts\train_network.py", line 539, in train
    train_util.resume_from_local_or_hf_if_specified(accelerator, args)
  File "C:\Users\ningl\kohya_ss\sd-scripts\library\train_util.py", line 4209, in resume_from_local_or_hf_if_specified
    accelerator.load_state(args.resume)
  File "C:\Users\ningl\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 2861, in load_state
    load_accelerator_state(
  File "C:\Users\ningl\kohya_ss\venv\lib\site-packages\accelerate\checkpointing.py", line 204, in load_accelerator_state
    state_dict = torch.load(input_model_file, map_location=map_location)
  File "C:\Users\ningl\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\ningl\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\ningl\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ningl\\Desktop\\2new\\model\\Chinese-food-style-000001-state\\pytorch_model.bin'
Traceback (most recent call last):
  File "C:\Users\ningl\miniconda3\envs\kohyass\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ningl\miniconda3\envs\kohyass\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ningl\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "C:\Users\ningl\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\ningl\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\Users\ningl\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\ningl\\kohya_ss\\venv\\Scripts\\python.exe', 'C:/Users/ningl/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', 'C:/Users/ningl/Desktop/2new/model/config_lora-20240927-105417.toml']' returned non-zero exit status 1.
10:54:45-511841 INFO     Training has ended.

i am confuse:what should i do ? i can not find the"pytorch_model.bin"in this state folder,just find the optimizer\scheduler.bin document

**Comment by b-fission** [comment]
```
INFO height: 1200 train_util.py:5724
INFO width: 1024 train_util.py:5725
```

Make sure the width and height values on your sample prompt are divisible by 32.
1200 won't work, but you can change it to 1216.

**Comment by Lecho303** [comment]
> ```
> INFO height: 1200 train_util.py:5724
> INFO width: 1024 train_util.py:5725
> ```
> 
> Make sure the width and height values on your sample prompt are divisible by 32. 1200 won't work, but you can change it to 1216.

OK~thanks，i do not not know that is a problem…and when i continue to train, will tell me that can not load the 1epoch state?

**Comment by franklygeorgy** [comment]
I have the same error, but the path it is searching is different. My problem path is `'H:\\Dev\\AI\\lora_training\\cuminuterus\\training_data\\outputs\\pytorch_model.bin` which is the path I have set for `Resume from saved training state (path to "last-state" state folder)` but with `\\pytorch_model.bin` added to the end

<details>
  <summary>Config</summary>
  
  ```json
{
  "LoRA_type": "Standard",
  "LyCORIS_preset": "full",
  "adaptive_noise_scale": 0,
  "additional_parameters": "",
  "async_upload": false,
  "block_alphas": "",
  "block_dims": "",
  "block_lr_zero_threshold": "",
  "bucket_no_upscale": true,
  "bucket_reso_steps": 64,
  "bypass_mode": false,
  "cache_latents": true,
  "cache_latents_to_disk": false,
  "caption_dropout_every_n_epochs": 0,
  "caption_dropout_rate": 0,
  "caption_extension": ".txt",
  "clip_skip": 1,
  "color_aug": false,
  "constrain": 0,
  "conv_alpha": 1,
  "conv_block_alphas": "",
  "conv_block_dims": "",
  "conv_dim": 1,
  "dataset_config": "",
  "debiased_estimation_loss": false,
  "decompose_both": false,
  "dim_from_weights": false,
  "dora_wd": false,
  "down_lr_weight": "",
  "dynamo_backend": "no",
  "dynamo_mode": "default",
  "dynamo_use_dynamic": false,
  "dynamo_use_fullgraph": false,
  "enable_bucket": true,
  "epoch": 10,
  "extra_accelerate_launch_args": "",
  "factor": -1,
  "flip_aug": false,
  "fp8_base": false,
  "full_bf16": false,
  "full_fp16": false,
  "gpu_ids": "",
  "gradient_accumulation_steps": 1,
  "gradient_checkpointing": false,
  "huber_c": 0.1,
  "huber_schedule": "snr",
  "huggingface_path_in_repo": "",
  "huggingface_repo_id": "",
  "huggingface_repo_type": "",
  "huggingface_repo_visibility": "",
  "huggingface_token": "",
  "ip_noise_gamma": 0,
  "ip_noise_gamma_random_strength": false,
  "keep_tokens": 0,
  "learning_rate": 0.0001,
  "log_tracker_config": "",
  "log_tracker_name": "",
  "log_with": "",
  "logging_dir": "H:/Dev/AI/lora_training/cuminuterus/training_data\\log",
  "loss_type": "l2",
  "lr_scheduler": "constant_with_warmup",
  "lr_scheduler_args": "",
  "lr_scheduler_num_cycles": 1,
  "lr_scheduler_power": 1,
  "lr_warmup": 10,
  "main_process_port": 0,
  "masked_loss": false,
  "max_bucket_reso": 2048,
  "max_data_loader_n_workers": 0,
  "max_grad_norm": 1,
  "max_resolution": "1024,1024",
  "max_timestep": 1000,
  "max_token_length": 150,
  "max_train_epochs": 0,
  "max_train_steps": 0,
  "mem_eff_attn": false,
  "metadata_author": "",
  "metadata_description": "",
  "metadata_license": "",
  "metadata_tags": "",
  "metadata_title": "",
  "mid_lr_weight": "",
  "min_bucket_reso": 256,
  "min_snr_gamma": 0,
  "min_timestep": 0,
  "mixed_precision": "fp16",
  "model_list": "custom",
  "module_dropout": 0,
  "multi_gpu": false,
  "multires_noise_discount": 0,
  "multires_noise_iterations": 0,
  "network_alpha": 16,
  "network_dim": 16,
  "network_dropout": 0,
  "network_weights": "",
  "noise_offset": 0,
  "noise_offset_random_strength": false,
  "noise_offset_type": "Original",
  "num_cpu_threads_per_process": 2,
  "num_machines": 1,
  "num_processes": 1,
  "optimizer": "Adafactor",
  "optimizer_args": "scale_parameter=False relative_step=False warmup_init=False",
  "output_dir": "H:/Dev/AI/lora_training/cuminuterus/training_data/model",
  "output_name": "cuminuterus",
  "persistent_data_loader_workers": false,
  "pretrained_model_name_or_path": "H:/Dev/AI/SD_models/checkpoints/illustrious/prefectiousXLNSFW_v10.safetensors",
  "prior_loss_weight": 1,
  "random_crop": false,
  "rank_dropout": 0,
  "rank_dropout_scale": false,
  "reg_data_dir": "",
  "rescaled": false,
  "resume": "H:/Dev/AI/lora_training/cuminuterus/training_data/outputs",
  "resume_from_huggingface": "",
  "sample_every_n_epochs": 1,
  "sample_every_n_steps": 100,
  "sample_prompts": "1girl, --w 1024, --h 1024, --d 03214323435, --l 5.5, --s 32,",
  "sample_sampler": "euler_a",
  "save_as_bool": false,
  "save_every_n_epochs": 1,
  "save_every_n_steps": 100,
  "save_last_n_steps": 0,
  "save_last_n_steps_state": 0,
  "save_model_as": "safetensors",
  "save_precision": "bf16",
  "save_state": true,
  "save_state_on_train_end": true,
  "save_state_to_huggingface": false,
  "scale_v_pred_loss_like_noise_pred": false,
  "scale_weight_norms": 0,
  "sdxl": true,
  "sdxl_cache_text_encoder_outputs": false,
  "sdxl_no_half_vae": true,
  "seed": 1234,
  "shuffle_caption": false,
  "stop_text_encoder_training": 0,
  "text_encoder_lr": 0.0001,
  "train_batch_size": 1,
  "train_data_dir": "H:/Dev/AI/lora_training/cuminuterus/training_data\\img",
  "train_norm": false,
  "train_on_input": true,
  "training_comment": "@franklygeorge",
  "unet_lr": 0.0001,
  "unit": 1,
  "up_lr_weight": "",
  "use_cp": false,
  "use_scalar": false,
  "use_tucker": false,
  "v2": false,
  "v_parameterization": false,
  "v_pred_like_loss": 0,
  "vae": "",
  "vae_batch_size": 0,
  "wandb_api_key": "",
  "wandb_run_name": "",
  "weighted_captions": false,
  "xformers": "xformers"
}
  ```
</details>

<details>
  <summary>Log</summary>
  
  ```
01:16:04-727789 INFO     Start training LoRA Standard ...
01:16:04-728790 INFO     Validating lr scheduler arguments...
01:16:04-730789 INFO     Validating optimizer arguments...
01:16:04-731789 INFO     Validating H:/Dev/AI/lora_training/cuminuterus/training_data\log existence and writability... SUCCESS
01:16:04-733789 INFO     Validating H:/Dev/AI/lora_training/cuminuterus/training_data/model existence and writability... SUCCESS
01:16:04-734790 INFO     Validating H:/Dev/AI/SD_models/checkpoints/illustrious/prefectiousXLNSFW_v10.safetensors existence... SUCCESS
01:16:04-736789 INFO     Validating H:/Dev/AI/lora_training/cuminuterus/training_data/outputs existence... SUCCESS
01:16:04-737789 INFO     Validating H:/Dev/AI/lora_training/cuminuterus/training_data\img existence... SUCCESS
01:16:04-739789 INFO     Folder 40_instance class: 40 repeats found
01:16:04-741790 INFO     Folder 40_instance class: 17 images found
01:16:04-743789 INFO     Folder 40_instance class: 17 * 40 = 680 steps
01:16:04-744789 INFO     Regulatization factor: 1
01:16:04-746789 INFO     Total steps: 680
01:16:04-747789 INFO     Train batch size: 1
01:16:04-748789 INFO     Gradient accumulation steps: 1
01:16:04-749789 INFO     Epoch: 10
01:16:04-750789 INFO     max_train_steps (680 / 1 / 1 * 10 * 1) = 6800
01:16:04-753789 INFO     stop_text_encoder_training = 0
01:16:04-754789 INFO     lr_warmup_steps = 680
01:16:04-757791 INFO     Saving training config to H:/Dev/AI/lora_training/cuminuterus/training_data/model\cuminuterus_20250101-011604.json...
01:16:05-115837 INFO     Executing command: H:\Dev\AI\kohya_ss\venv\Scripts\accelerate.EXE launch --dynamo_backend no --dynamo_mode default
                         --mixed_precision fp16 --num_processes 1 --num_machines 1 --num_cpu_threads_per_process 2
                         H:/Dev/AI/kohya_ss/sd-scripts/sdxl_train_network.py --config_file
                         H:/Dev/AI/lora_training/cuminuterus/training_data/model/config_lora-20250101-011604.toml
01:16:05-121838 INFO     Command executed.
2025-01-01 01:16:13 INFO     Loading settings from                                                                             train_util.py:4174
                             H:/Dev/AI/lora_training/cuminuterus/training_data/model/config_lora-20250101-011604.toml...
                    INFO     H:/Dev/AI/lora_training/cuminuterus/training_data/model/config_lora-20250101-011604               train_util.py:4193
2025-01-01 01:16:13 INFO     prepare tokenizers                                                                            sdxl_train_util.py:138
                    INFO     update token length: 150                                                                      sdxl_train_util.py:163
                    INFO     Using DreamBooth method.                                                                        train_network.py:172
2025-01-01 01:16:14 INFO     prepare images.                                                                                   train_util.py:1815
                    INFO     found directory H:\Dev\AI\lora_training\cuminuterus\training_data\img\40_instance class contains  train_util.py:1762
                             17 image files
                    INFO     680 train images with repeating.                                                                  train_util.py:1856
                    INFO     0 reg images.                                                                                     train_util.py:1859
                    WARNING  no regularization images / 正則化画像が見つかりませんでした                                       train_util.py:1864
                    INFO     [Dataset 0]                                                                                       config_util.py:572
                               batch_size: 1
                               resolution: (1024, 1024)
                               enable_bucket: True
                               network_multiplier: 1.0
                               min_bucket_reso: 256
                               max_bucket_reso: 2048
                               bucket_reso_steps: 64
                               bucket_no_upscale: True

                               [Subset 0 of Dataset 0]
                                 image_dir: "H:\Dev\AI\lora_training\cuminuterus\training_data\img\40_instance class"
                                 image_count: 17
                                 num_repeats: 40
                                 shuffle_caption: False
                                 keep_tokens: 0
                                 keep_tokens_separator:
                                 caption_separator: ,
                                 secondary_separator: None
                                 enable_wildcard: False
                                 caption_dropout_rate: 0.0
                                 caption_dropout_every_n_epoches: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 alpha_mask: False,
                                 is_reg: False
                                 class_tokens: instance class
                                 caption_extension: .txt


                    INFO     [Dataset 0]                                                                                       config_util.py:578
                    INFO     loading image sizes.                                                                               train_util.py:911
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 17009.34it/s]
                    INFO     make buckets                                                                                       train_util.py:917
                    WARNING  min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso   train_util.py:934
                             is defined by image size automatically /
                             bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_
                             resoとmax_bucket_resoは無視されます
                    INFO     number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）                    train_util.py:963
                    INFO     bucket 0: resolution (640, 832), count: 40                                                         train_util.py:968
                    INFO     bucket 1: resolution (768, 768), count: 40                                                         train_util.py:968
                    INFO     bucket 2: resolution (768, 1344), count: 40                                                        train_util.py:968
                    INFO     bucket 3: resolution (832, 1088), count: 200                                                       train_util.py:968
                    INFO     bucket 4: resolution (832, 1152), count: 120                                                       train_util.py:968
                    INFO     bucket 5: resolution (832, 1216), count: 80                                                        train_util.py:968
                    INFO     bucket 6: resolution (896, 1024), count: 120                                                       train_util.py:968
                    INFO     bucket 7: resolution (1024, 960), count: 40                                                        train_util.py:968
                    INFO     mean ar error (without repeats): 0.012960950925708833                                              train_util.py:973
                    WARNING  clip_skip will be unexpected / SDXL学習ではclip_skipは動作しません                            sdxl_train_util.py:352
                    INFO     preparing accelerator                                                                           train_network.py:225
accelerator device: cuda
                    INFO     loading model for process 0/1                                                                  sdxl_train_util.py:33
                    INFO     load StableDiffusion checkpoint:                                                               sdxl_train_util.py:74
                             H:/Dev/AI/SD_models/checkpoints/illustrious/prefectiousXLNSFW_v10.safetensors
                    INFO     building U-Net                                                                                sdxl_model_util.py:198
                    INFO     loading U-Net from checkpoint                                                                 sdxl_model_util.py:202
2025-01-01 01:16:16 INFO     U-Net: <All keys matched successfully>                                                        sdxl_model_util.py:208
                    INFO     building text encoders                                                                        sdxl_model_util.py:211
                    INFO     loading text encoders from checkpoint                                                         sdxl_model_util.py:264
                    INFO     text encoder 1: <All keys matched successfully>                                               sdxl_model_util.py:278
2025-01-01 01:16:17 INFO     text encoder 2: <All keys matched successfully>                                               sdxl_model_util.py:282
                    INFO     building VAE                                                                                  sdxl_model_util.py:285
                    INFO     loading VAE from checkpoint                                                                   sdxl_model_util.py:290
                    INFO     VAE: <All keys matched successfully>                                                          sdxl_model_util.py:293
                    INFO     Enable xformers for U-Net                                                                         train_util.py:3040
import network module: networks.lora
                    INFO     [Dataset 0]                                                                                       train_util.py:2323
                    INFO     caching latents.                                                                                  train_util.py:1095
                    INFO     checking cache validity...                                                                        train_util.py:1105
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<?, ?it/s]
                    INFO     caching latents...                                                                                train_util.py:1144
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:14<00:00,  1.17it/s]
2025-01-01 01:16:33 INFO     create LoRA network. base dim (rank): 16, alpha: 16                                                      lora.py:928
                    INFO     neuron dropout: p=None, rank dropout: p=None, module dropout: p=None                                     lora.py:929
                    INFO     create LoRA for Text Encoder 1:                                                                         lora.py:1020
                    INFO     create LoRA for Text Encoder 2:                                                                         lora.py:1020
                    INFO     create LoRA for Text Encoder: 264 modules.                                                              lora.py:1028
                    INFO     create LoRA for U-Net: 722 modules.                                                                     lora.py:1036
                    INFO     enable LoRA for text encoder: 264 modules                                                               lora.py:1077
                    INFO     enable LoRA for U-Net: 722 modules                                                                      lora.py:1082
prepare optimizer, data loader etc.
                    INFO     use Adafactor optimizer | {'scale_parameter': False, 'relative_step': False, 'warmup_init':       train_util.py:4485
                             False}
                    WARNING  because max_grad_norm is set, clip_grad_norm is enabled. consider set to 0 /                      train_util.py:4513
                             max_grad_normが設定されているためclip_grad_normが有効になります。0に設定して無効にしたほうがいい
                             かもしれません
2025-01-01 01:16:36 INFO     resume training from local state: H:/Dev/AI/lora_training/cuminuterus/training_data/outputs       train_util.py:4208
                    INFO     Loading states from H:/Dev/AI/lora_training/cuminuterus/training_data/outputs                          logging.py:61
Traceback (most recent call last):
  File "H:\Dev\AI\kohya_ss\sd-scripts\sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "H:\Dev\AI\kohya_ss\sd-scripts\train_network.py", line 539, in train
    train_util.resume_from_local_or_hf_if_specified(accelerator, args)
  File "H:\Dev\AI\kohya_ss\sd-scripts\library\train_util.py", line 4209, in resume_from_local_or_hf_if_specified
    accelerator.load_state(args.resume)
  File "H:\Dev\AI\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 2861, in load_state
    load_accelerator_state(
  File "H:\Dev\AI\kohya_ss\venv\lib\site-packages\accelerate\checkpointing.py", line 204, in load_accelerator_state
    state_dict = torch.load(input_model_file, map_location=map_location)
  File "H:\Dev\AI\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "H:\Dev\AI\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "H:\Dev\AI\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\Dev\\AI\\lora_training\\cuminuterus\\training_data\\outputs\\pytorch_model.bin'
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "H:\Dev\AI\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
    sys.exit(main())
  File "H:\Dev\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "H:\Dev\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "H:\Dev\AI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['H:\\Dev\\AI\\kohya_ss\\venv\\Scripts\\python.exe', 'H:/Dev/AI/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', 'H:/Dev/AI/lora_training/cuminuterus/training_data/model/config_lora-20250101-011604.toml']' returned non-zero exit status 1.
01:16:38-573871 INFO     Training has ended.
  ```
</details>

**Comment by franklygeorgy** [comment]
If someone could help me figure out what model it is trying to download I am fine with manually downloading it and putting it at that path

**Comment by franklygeorgy** [comment]
@Lecho303 the end user solution to this issue is to make sure `Resume from saved training state (path to "last-state" state folder)` (the resume keyword if you are editing a config file) is empty if you don't have resume data

I am working on a small patch that will make this throw a warning instead of just crashing. That will be coming in a pull request once I actually test it (after my current LoRA's training finishes)
