### ISSUE TITLE
Please help me！！

### ISSUE THREAD

**Issue by H-SUN-jpg** [bmaltais/kohya_ss#2862]
09:39:57-989260 INFO     Training has ended.
10:24:20-642172 INFO     Start training LoRA Standard ...
10:24:20-643736 INFO     Validating lr scheduler arguments...
10:24:20-644258 INFO     Validating optimizer arguments...
10:24:20-645822 INFO     Validating D:\sd-test\kohya_ss\dataset\meishi\log existence and writability... SUCCESS
10:24:20-646865 INFO     Validating D:\sd-test\kohya_ss\dataset\meishi\houmodel existence and writability... SUCCESS
10:24:20-647907 INFO     Validating D:/sd-test/kohya_ss/dataset/meishi/meishimodel/1.5model.safetensors existence...
                         SUCCESS
10:24:20-648954 INFO     Validating D:/sd-test/kohya_ss/dataset/meishi/img existence... SUCCESS
10:24:20-649961 INFO     Folder 10_meishi: 10 repeats found
10:24:20-650961 INFO     Folder 10_meishi: 115 images found
10:24:20-651964 INFO     Folder 10_meishi: 115 * 10 = 1150 steps
10:24:20-652961 INFO     Regulatization factor: 1
10:24:20-653961 INFO     Total steps: 1150
10:24:20-654963 INFO     Train batch size: 1
10:24:20-655960 INFO     Gradient accumulation steps: 1
10:24:20-656962 INFO     Epoch: 10
10:24:20-656962 INFO     max_train_steps (1150 / 1 / 1 * 10 * 1) = 11500
10:24:20-657962 INFO     stop_text_encoder_training = 0
10:24:20-658961 INFO     lr_warmup_steps = 0
10:24:20-662962 INFO     Saving training config to
                         D:\sd-test\kohya_ss\dataset\meishi\houmodel\China_20240929-102420.json...
10:24:20-665597 INFO     Executing command: D:\sd-test\kohya_ss\venv\Scripts\accelerate.EXE launch --dynamo_backend no
                         --dynamo_mode default --mixed_precision fp16 --num_processes 1 --num_machines 1
                         --num_cpu_threads_per_process 2 D:/sd-test/kohya_ss/sd-scripts/train_network.py --config_file
                         D:\sd-test\kohya_ss\dataset\meishi\houmodel/config_lora-20240929-102420.toml
10:24:20-673545 INFO     Command executed.
2024-09-29 10:24:39 INFO     Loading settings from                                                    train_util.py:4174
                             D:\sd-test\kohya_ss\dataset\meishi\houmodel/config_lora-20240929-102420.
                             toml...
                    INFO     D:\sd-test\kohya_ss\dataset\meishi\houmodel/config_lora-20240929-102420  train_util.py:4193
2024-09-29 10:24:39 INFO     prepare tokenizer                                                        train_util.py:4665
                    INFO     update token length: 75                                                  train_util.py:4682
                    INFO     Using DreamBooth method.                                               train_network.py:172
2024-09-29 10:24:40 INFO     prepare images.                                                          train_util.py:1815
                    INFO     found directory D:\sd-test\kohya_ss\dataset\meishi\img\10_meishi         train_util.py:1762
                             contains 115 image files
                    INFO     1150 train images with repeating.                                        train_util.py:1856
                    INFO     0 reg images.                                                            train_util.py:1859
                    WARNING  no regularization images / 正則化画像が見つかりませんでした              train_util.py:1864
                    INFO     [Dataset 0]                                                              config_util.py:572
                               batch_size: 1
                               resolution: (768, 768)
                               enable_bucket: True
                               network_multiplier: 1.0
                               min_bucket_reso: 640
                               max_bucket_reso: 1000
                               bucket_reso_steps: 32
                               bucket_no_upscale: True

                               [Subset 0 of Dataset 0]
                                 image_dir: "D:\sd-test\kohya_ss\dataset\meishi\img\10_meishi"
                                 image_count: 115
                                 num_repeats: 10
                                 shuffle_caption: False
                                 keep_tokens: 0
                                 keep_tokens_separator:
                                 caption_separator: ,
                                 secondary_separator: None
                                 enable_wildcard: False
                                 caption_dropout_rate: 0.0
                                 caption_dropout_every_n_epoches: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 alpha_mask: False,
                                 is_reg: False
                                 class_tokens: meishi
                                 caption_extension: .txt

                    INFO     [Dataset 0]                                                              config_util.py:578
                    INFO     loading image sizes.                                                      train_util.py:911
100%|██████████████████████████████████████████████████████████████████████████████| 115/115 [00:00<00:00, 5475.53it/s]
                    INFO     make buckets                                                              train_util.py:917
                    WARNING  min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is   train_util.py:934
                             set, because bucket reso is defined by image size automatically /
                             bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計
                             算されるため、min_bucket_resoとmax_bucket_resoは無視されます
                    INFO     number of images (including repeats) /                                    train_util.py:963
                             各bucketの画像枚数（繰り返し回数を含む）
                    INFO     bucket 0: resolution (800, 512), count: 1150                              train_util.py:968
                    INFO     mean ar error (without repeats): 0.06156191369606013                      train_util.py:973
                    INFO     preparing accelerator                                                  train_network.py:225
accelerator device: cuda
                    INFO     loading model for process 0/1                                            train_util.py:4823
                    INFO     load StableDiffusion checkpoint:                                         train_util.py:4779
                             D:/sd-test/kohya_ss/dataset/meishi/meishimodel/1.5model.safetensors
                    INFO     UNet2DConditionModel: 64, 8, 768, False, False                        original_unet.py:1387
2024-09-29 10:24:51 INFO     loading u-net: <All keys matched successfully>                           model_util.py:1009
2024-09-29 10:24:52 INFO     loading vae: <All keys matched successfully>                             model_util.py:1017
2024-09-29 10:24:55 INFO     loading text encoder: <All keys matched successfully>                    model_util.py:1074
                    INFO     Enable memory efficient attention for U-Net                              train_util.py:3037
import network module: networks.lora
2024-09-29 10:24:56 INFO     [Dataset 0]                                                              train_util.py:2323
                    INFO     caching latents.                                                         train_util.py:1095
                    INFO     checking cache validity...                                               train_util.py:1105
100%|████████████████████████████████████████████████████████████████████████████████████████| 115/115 [00:00<?, ?it/s]
                    INFO     caching latents...                                                       train_util.py:1144
100%|██████████████████████████████████████████████████████████████████████████████████| 58/58 [00:25<00:00,  2.30it/s]
Traceback (most recent call last):
  File "D:\sd-test\kohya_ss\sd-scripts\train_network.py", line 1242, in <module>
    trainer.train(args)
  File "D:\sd-test\kohya_ss\sd-scripts\train_network.py", line 299, in train
    network = network_module.create_network(
  File "D:\sd-test\kohya_ss\sd-scripts\networks\lora.py", line 446, in create_network
    block_lr_weight = parse_block_lr_kwargs(is_sdxl, kwargs)
  File "D:\sd-test\kohya_ss\sd-scripts\networks\lora.py", line 411, in parse_block_lr_kwargs
    return get_block_lr_weight(
  File "D:\sd-test\kohya_ss\sd-scripts\networks\lora.py", line 635, in get_block_lr_weight
    down_lr_weight = get_list(down_lr_weight)
  File "D:\sd-test\kohya_ss\sd-scripts\networks\lora.py", line 629, in get_list
    "Unknown lr_weight argument %s is used. Valid arguments:  / 不明なlr_weightの引数 %s が使われました。有効な引数:\n\tcosine, sine, linear, reverse_linear, zeros"
TypeError: not enough arguments for format string
Traceback (most recent call last):
  File "C:\Users\15989\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\15989\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\sd-test\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "D:\sd-test\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\sd-test\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "D:\sd-test\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\sd-test\\kohya_ss\\venv\\Scripts\\python.exe', 'D:/sd-test/kohya_ss/sd-scripts/train_network.py', '--config_file', 'D:\\sd-test\\kohya_ss\\dataset\\meishi\\houmodel/config_lora-20240929-102420.toml']' returned non-zero exit status 1.
10:25:23-499009 INFO     Training has ended.

**Comment by SagarChandra07** [comment]
maybe this will help

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA

Password: changeme
I put the necessary dlls in the archive
