### ISSUE TITLE
TypeError: ForwardRef.__init__() got an unexpected keyword argument 'is_class'

### ISSUE THREAD

**Issue by DarkPulse** [bmaltais/kohya_ss#2869]
I decided to do a complete clean Git pull and install since I had some PC issues that I resolved, and I've finally got something I want to train a LoRA for. Fresh install. All pre-requisites met. I've done plenty of training before.

```
19:13:23-650506 INFO     Kohya_ss GUI version: v24.1.7
19:13:24-073396 INFO     Submodule initialized and updated.
19:13:24-075398 INFO     nVidia toolkit detected
19:13:25-557250 INFO     Torch 2.1.2+cu118
19:13:25-581272 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8905
19:13:25-584275 INFO     Torch detected GPU: NVIDIA GeForce RTX 4080 SUPER VRAM 16376 Arch (8, 9) Cores 80
19:13:25-589279 INFO     Python version is 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit
                         (AMD64)]
19:13:25-592282 INFO     Verifying modules installation status from requirements_pytorch_windows.txt...
19:13:25-594284 INFO     Verifying modules installation status from requirements_windows.txt...
19:13:25-596285 INFO     Verifying modules installation status from requirements.txt...
Traceback (most recent call last):
  File "P:\Kohya-GUI\kohya_ss\kohya_gui.py", line 1, in <module>
    import gradio as gr
  File "P:\Kohya-GUI\kohya_ss\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "P:\Kohya-GUI\kohya_ss\venv\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "P:\Kohya-GUI\kohya_ss\venv\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import Component, FormComponent
  File "P:\Kohya-GUI\kohya_ss\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "P:\Kohya-GUI\kohya_ss\venv\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio import processing_utils, utils
  File "P:\Kohya-GUI\kohya_ss\venv\lib\site-packages\gradio\processing_utils.py", line 22, in <module>
    from gradio import utils, wasm_utils
  File "P:\Kohya-GUI\kohya_ss\venv\lib\site-packages\gradio\utils.py", line 58, in <module>
    from gradio.data_classes import (
  File "P:\Kohya-GUI\kohya_ss\venv\lib\site-packages\gradio\data_classes.py", line 26, in <module>
    from pydantic import BaseModel, RootModel, ValidationError
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "P:\Kohya-GUI\kohya_ss\venv\lib\site-packages\pydantic\__init__.py", line 411, in __getattr__
    module = import_module(module_name, package=package)
  File "C:\Users\DarkPulse\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "P:\Kohya-GUI\kohya_ss\venv\lib\site-packages\pydantic\root_model.py", line 35, in <module>
    class RootModel(BaseModel, typing.Generic[RootModelRootType], metaclass=_RootModelMetaclass):
  File "P:\Kohya-GUI\kohya_ss\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 219, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "P:\Kohya-GUI\kohya_ss\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 512, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
  File "P:\Kohya-GUI\kohya_ss\venv\lib\site-packages\pydantic\_internal\_fields.py", line 105, in collect_model_fields
    type_hints = get_cls_type_hints_lenient(cls, types_namespace)
  File "P:\Kohya-GUI\kohya_ss\venv\lib\site-packages\pydantic\_internal\_typing_extra.py", line 245, in get_cls_type_hints_lenient
    hints[name] = eval_type_lenient(value, globalns, localns)
  File "P:\Kohya-GUI\kohya_ss\venv\lib\site-packages\pydantic\_internal\_typing_extra.py", line 254, in eval_type_lenient
    value = _make_forward_ref(value, is_argument=False, is_class=True)
TypeError: ForwardRef.__init__() got an unexpected keyword argument 'is_class'
```

**Comment by DarkPulse** [comment]
No reply on this at all? That's kind of disappointing. I genuinely don't know why it's doing this.

- Python 3.10.11 is installed, with no other Python versions in there.
- All requirements met as far as I can tell.
- Tried nuking venv to see if that was anything. Nope, it still won't start up.
- Meanwhile I can generate images fine, so I know I've got working installs of SD.

I have genuinely no idea why Kohya-GUI is failing to work. And I'd really like it to work, because I'd really like to train some stuff...

**Comment by DarkPulse** [comment]
Figured it out myself.

For the benefit of anyone who may stumble upon this problem, the short answer is that you probably accidentally downloaded a version of Python other than **_3.10.11_** (in my case, 3.10.**_0_**). Uninstall that, wipe out the cached Python stuff from your %AppData%/Local/Programs/Python folder, and install 3.10.11.

Everything should then work.
