### ISSUE TITLE
Sizes of tensors must match except in dimension 1

### ISSUE THREAD

**Issue by jigrain** [bmaltais/kohya_ss#2888]
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 52 but got size 51 for tensor number 1 in the list.
steps:  10%|█████▌                                                  | 492/4920 [11:15<1:41:22,  1.37s/it, avr_loss=nan]
Traceback (most recent call last):
  File "D:\Programs\Python_3_10\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Programs\Python_3_10\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\programming\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "D:\programming\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\programming\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "D:\programming\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\programming\\kohya_ss\\venv\\Scripts\\python.exe', 'D:/programming/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', 'C:/Users/Admin/Desktop/ruina-sprite/model/config_lora-20241007-231252.toml']' returned non-zero exit status 1.

Received this error today. I've attached a file with the settings for the voice training:
[SDXL_Style.json](https://github.com/user-attachments/files/17284279/SDXL_Style.json)

**Comment by b-fission** [comment]
Check your sample prompt. Your config file has `--w 512 --h 819` for the sizing.
The width and height must be divisible by 32, so try using a height such as 832 instead of 819.
