### ISSUE TITLE
[rank2]:[W1014 03:47:39.789025589 socket.cpp:428] [c10d] While waitForInput, poolFD failed with (errno: 0 - Success).             

### ISSUE THREAD

**Issue by AbstractEyes** [bmaltais/kohya_ss#2899]
[rank2]:[W1014 03:47:39.789025589 socket.cpp:428] [c10d] While waitForInput, poolFD failed with (errno: 0 - Success).                                  | 1061/13485 [09:20<1:49:30,  1.89it/s]
[rank2]: Traceback (most recent call last):                                                                                                            | 1060/13485 [09:20<1:44:20,  1.98it/s]
[rank2]:   File "/workspace/kohya_ss/sd-scripts/flux_train_network.py", line 519, in <module>                                                          | 1059/13485 [09:19<1:42:57,  2.01it/s]
[rank2]:     trainer.train(args)                                                                                                                       | 1058/13485 [09:19<1:17:41,  2.67it/s]
[rank2]:   File "/workspace/kohya_ss/sd-scripts/train_network.py", line 392, in train                                                                  | 1057/13485 [09:18<1:27:35,  2.36it/s]
[rank2]:     accelerator.wait_for_everyone()                                                                                                           | 1056/13485 [09:18<1:36:31,  2.15it/s]
[rank2]:   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 2564, in wait_for_everyone                     | 1055/13485 [09:17<3:27:04,  1.00it/s]
[rank2]:     wait_for_everyone()                                                                                                                       | 1054/13485 [09:16<3:01:39,  1.14it/s]
[rank2]:   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/utils/other.py", line 138, in wait_for_everyone                      | 1053/13485 [09:15<1:31:20,  2.27it/s]
[rank2]:     PartialState().wait_for_everyone()                                                                                                        | 1052/13485 [09:15<1:37:55,  2.12it/s]
[rank2]:   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/state.py", line 374, in wait_for_everyone                            | 1051/13485 [09:14<1:26:02,  2.41it/s]
[rank2]:     torch.distributed.barrier()                                                                                                               | 1050/13485 [09:14<1:36:50,  2.14it/s]
[rank2]:   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper                           | 959/13485 [08:21<1:38:13,  2.13it/s]
[rank2]:     return func(*args, **kwargs)                                                                                                               | 958/13485 [08:21<1:32:54,  2.25it/s]
[rank2]:   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3936, in barrier                    | 957/13485 [08:20<1:23:12,  2.51it/s]
[rank2]:     work = default_pg.barrier(opts=opts)                                                                                                       | 956/13485 [08:20<2:10:22,  1.60it/s]
[rank2]: torch.distributed.DistBackendError: [2] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Sock
et Timeout������                                                                                                                                        | 954/13485 [08:19<1:50:13,  1.89it/s]
[rank2]: Exception raised from doWait at ../torch/csrc/distributed/c10d/TCPStore.cpp:570 (most recent call first):                                      | 953/13485 [08:18<2:33:24,  1.36it/s]
[rank2]: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7d0e53c9af86 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libc10.so)1:35:58,  2.18it/s]
[rank2]: frame #1: <unknown function> + 0x164b9c5 (0x7d0e3b24b9c5 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)   | 951/13485 [08:17<1:34:37,  2.21it/s]
[rank2]: frame #2: c10d::TCPStore::doGet(std::string const&) + 0x32 (0x7d0e3f8fbd92 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so):34<2:08:14,  1.64it/s]
[rank2]: frame #3: c10d::TCPStore::get(std::string const&) + 0xa1 (0x7d0e3f8fcf81 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)07:34<1:34:12,  2.23it/s]
[rank2]: frame #4: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7d0e3f8b19d1 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)33<1:57:10,  1.79it/s]
[rank2]: frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7d0e3f8b19d1 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)33<1:19:30,  2.65it/s]
[rank2]: frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7d0e3f8b19d1 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)32<1:27:32,  2.40it/s]
[rank2]: frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7d0e3f8b19d1 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)32<1:38:03,  2.14it/s]
[rank2]: frame #8: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::string const&, int) + 0xaf (0x7d0e0618ef8f in /workspace/kohya_ss/venv/lib/python3.10/site-packages
/torch/lib/libtorch_cuda.so)                                                                                                                            | 863/13485 [07:31<1:26:35,  2.43it/s]
[rank2]: frame #9: c10d::ProcessGroupNCCL::getNCCLComm(std::string const&, c10::Device&, c10d::OpType, int, bool) + 0x114c (0x7d0e0619ad6c in /workspace/kohya_ss/venv/lib/python3.10/site-pac
kages/torch/lib/libtorch_cuda.so)                                                                                                                       | 861/13485 [07:30<2:23:23,  1.47it/s]
[rank2]: frame #10: <unknown function> + 0x11a31cf (0x7d0e061a31cf in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so) | 860/13485 [07:29<1:18:32,  2.68it/s]
[rank2]: frame #11: c10d::ProcessGroupNCCL::allreduce_impl(at::Tensor&, c10d::AllreduceOptions const&) + 0x10 (0x7d0e061a4600 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/l
ib/libtorch_cuda.so)                                                                                                                                    | 777/13485 [06:47<1:39:20,  2.13it/s]
[rank2]: frame #12: c10d::ProcessGroupNCCL::barrier(c10d::BarrierOptions const&) + 0x69c (0x7d0e061b170c in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)]
[rank2]: frame #13: <unknown function> + 0x5ca4202 (0x7d0e3f8a4202 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)  | 775/13485 [06:46<1:37:21,  2.18it/s]
[rank2]: frame #14: <unknown function> + 0x5caea05 (0x7d0e3f8aea05 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)  | 774/13485 [06:46<1:38:40,  2.15it/s]
[rank2]: frame #15: <unknown function> + 0x52d0c1b (0x7d0e3eed0c1b in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)  | 773/13485 [06:45<2:02:21,  1.73it/s]
[rank2]: frame #16: <unknown function> + 0x52ce494 (0x7d0e3eece494 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)  | 772/13485 [06:45<1:38:03,  2.16it/s]
[rank2]: frame #17: <unknown function> + 0x1ace5a8 (0x7d0e3b6ce5a8 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)  | 771/13485 [06:44<1:29:22,  2.37it/s]
[rank2]: frame #18: <unknown function> + 0x5cb8974 (0x7d0e3f8b8974 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)  | 770/13485 [06:44<1:22:42,  2.56it/s]
[rank2]: frame #19: <unknown function> + 0x5cb9705 (0x7d0e3f8b9705 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)  | 769/13485 [06:43<1:55:56,  1.83it/s]
[rank2]: frame #20: <unknown function> + 0xdb0b68 (0x7d0e52bb0b68 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_python.so)| 768/13485 [06:43<1:37:43,  2.17it/s]
[rank2]: frame #21: <unknown function> + 0x4b00e4 (0x7d0e522b00e4 in /workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_python.so)| 687/13485 [06:01<2:34:00,  1.38it/s]
[rank2]: frame #22: <unknown function> + 0x15cb2e (0x6518fc73cb2e in /workspace/kohya_ss/venv/bin/python)                                               | 686/13485 [06:00<1:42:44,  2.08it/s]
[rank2]: frame #23: _PyObject_MakeTpCall + 0x25b (0x6518fc7332db in /workspace/kohya_ss/venv/bin/python)                                                | 685/13485 [06:00<1:48:26,  1.97it/s]
[rank2]: frame #24: <unknown function> + 0x16b55b (0x6518fc74b55b in /workspace/kohya_ss/venv/bin/python)                                               | 684/13485 [05:59<2:51:43,  1.24it/s]
[rank2]: frame #25: _PyEval_EvalFrameDefault + 0x1983 (0x6518fc726b93 in /workspace/kohya_ss/venv/bin/python)                                           | 683/13485 [05:59<1:20:28,  2.65it/s]
[rank2]: frame #26: _PyFunction_Vectorcall + 0x7c (0x6518fc73d42c in /workspace/kohya_ss/venv/bin/python)                                               | 682/13485 [05:58<1:53:33,  1.88it/s]
[rank2]: frame #27: _PyEval_EvalFrameDefault + 0x285e (0x6518fc727a6e in /workspace/kohya_ss/venv/bin/python)                                           | 681/13485 [05:58<1:49:31,  1.95it/s]
[rank2]: frame #28: _PyFunction_Vectorcall + 0x7c (0x6518fc73d42c in /workspace/kohya_ss/venv/bin/python)                                               | 680/13485 [05:57<1:37:17,  2.19it/s]
[rank2]: frame #29: _PyEval_EvalFrameDefault + 0x613a (0x6518fc72b34a in /workspace/kohya_ss/venv/bin/python)                                           | 679/13485 [05:57<1:35:03,  2.25it/s]
[rank2]: frame #30: <unknown function> + 0x16b281 (0x6518fc74b281 in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #31: _PyEval_EvalFrameDefault + 0x613a (0x6518fc72b34a in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #32: _PyFunction_Vectorcall + 0x7c (0x6518fc73d42c in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #33: _PyEval_EvalFrameDefault + 0x6bc (0x6518fc7258cc in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #34: _PyFunction_Vectorcall + 0x7c (0x6518fc73d42c in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #35: _PyEval_EvalFrameDefault + 0x8ab (0x6518fc725abb in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #36: _PyFunction_Vectorcall + 0x7c (0x6518fc73d42c in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #37: _PyEval_EvalFrameDefault + 0x8ab (0x6518fc725abb in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #38: <unknown function> + 0x142016 (0x6518fc722016 in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #39: PyEval_EvalCode + 0x86 (0x6518fc8178b6 in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #40: <unknown function> + 0x262918 (0x6518fc842918 in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #41: <unknown function> + 0x25c1db (0x6518fc83c1db in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #42: <unknown function> + 0x262665 (0x6518fc842665 in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #43: _PyRun_SimpleFileObject + 0x1a8 (0x6518fc841b48 in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #44: _PyRun_AnyFileObject + 0x43 (0x6518fc841793 in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #45: Py_RunMain + 0x2be (0x6518fc8342ce in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #46: Py_BytesMain + 0x2d (0x6518fc80a70d in /workspace/kohya_ss/venv/bin/python)
[rank2]: frame #47: <unknown function> + 0x29d90 (0x7d0e548b6d90 in /lib/x86_64-linux-gnu/libc.so.6)
[rank2]: frame #48: __libc_start_main + 0x80 (0x7d0e548b6e40 in /lib/x86_64-linux-gnu/libc.so.6)
[rank2]: frame #49: _start + 0x25 (0x6518fc80a605 in /workspace/kohya_ss/venv/bin/python)
[rank2]: . This may indicate a possible application crash on rank 0 or a network set up issue.
  8%|�������������                                                                                                                                     | 1132/13485 [09:59<1:34:01,  2.19it/s]W1014 03:47:41.144000 130521776504832 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 7562 closing signal SIGTERM
W1014 03:47:41.147000 130521776504832 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 7563 closing signal SIGTERM
W1014 03:47:41.147000 130521776504832 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 7565 closing signal SIGTERM
E1014 03:47:41.614000 130521776504832 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 2 (pid: 7564) of binary: /workspace/kohya_ss/venv/bin/python
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
    multi_gpu_launcher(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 734, in multi_gpu_launcher
    distrib_run.run(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/workspace/kohya_ss/sd-scripts/flux_train_network.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-14_03:47:41
  host      : bd889cebf45f
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 7564)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
03:47:42-852638 INFO     Training has ended.

**Comment by AbstractEyes** [comment]
https://github.com/kohya-ss/sd-scripts/issues/1693

**Comment by AbstractEyes** [comment]
Now kohya_ss just needs the updated sd-scripts to match and it'll fix the problem.
