### ISSUE TITLE
When one of the option from "Caption file extension" is not selected, the "Presets" drop down will not work

### ISSUE THREAD

**Issue by toyssamurai** [bmaltais/kohya_ss#2903]
I am on the sd3-flux.1 branch and I found that on the LoRA training tab, if I do not select one of the option from the "Caption file extension" drop down, selecting a preset from the "Presets" drop down will not work. In the log, I will see:

```
venv/lib/python3.10/site-packages/gradio/components/dropdown.py:201: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: .none-use-foldername or set allow_custom_value=True.
  warnings.warn(
Traceback (most recent call last):
  File "/storage/kohya_flux/venv/lib/python3.10/site-packages/gradio/queueing.py", line 622, in process_events
    response = await route_utils.call_process_api(
  File "/storage/kohya_flux/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/storage/kohya_flux/venv/lib/python3.10/site-packages/gradio/blocks.py", line 2012, in process_api
    inputs = await self.preprocess_data(
  File "/storage/kohya_flux/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1711, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "/storage/kohya_flux/venv/lib/python3.10/site-packages/gradio/components/dropdown.py", line 177, in preprocess
    raise Error(
gradio.exceptions.Error: "Value: .none-use-foldername is not in the list of choices: ['', '.cap', '.caption', '.txt']"
```

**Comment by YacratesWyh** [comment]
![Image](https://github.com/user-attachments/assets/3d4ab4a5-5af3-4bec-a743-d9a0a6979047)
