### ISSUE TITLE
Getting this issue - argparse.ArgumentError: argument --skip_cache_check: conflicting option string: --skip_cache_check

### ISSUE THREAD

**Issue by DarkViewAI** [bmaltais/kohya_ss#2914]
D:\kohya_ss\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
D:\kohya_ss\venv\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "D:\kohya_ss\sd-scripts\sd3_train.py", line 1076, in <module>
    parser = setup_parser()
  File "D:\kohya_ss\sd-scripts\sd3_train.py", line 1061, in setup_parser
    parser.add_argument(
  File "C:\Python310\lib\argparse.py", line 1448, in add_argument
    return self._add_action(action)
  File "C:\Python310\lib\argparse.py", line 1814, in _add_action
    self._optionals._add_action(action)
  File "C:\Python310\lib\argparse.py", line 1650, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "C:\Python310\lib\argparse.py", line 1462, in _add_action
    self._check_conflict(action)
  File "C:\Python310\lib\argparse.py", line 1599, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "C:\Python310\lib\argparse.py", line 1608, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --skip_cache_check: conflicting option string: --skip_cache_check
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohya_ss\\venv\\Scripts\\python.exe', 'D:/kohya_ss/sd-scripts/sd3_train.py', '--config_file', 'C:/Users/Desktop/Pictures/New folder/config_dreambooth-20241021-020115.toml']' returned non-zero exit status 1.

**Comment by b-fission** [comment]
Looks like redundant arg handling code in `sd3_train.py` which should be fixable by commenting out [these lines in the file](https://github.com/kohya-ss/sd-scripts/blob/138dac4aea57716e2f23580305f6e40836a87228/sd3_train.py#L1061-L1065)

You may also want report this bug at kohya's [sd-scripts](https://github.com/kohya-ss/sd-scripts).
