### ISSUE TITLE
getting this error whenever i press train lora

### ISSUE THREAD

**Issue by Braeden90000** [bmaltais/kohya_ss#2920]
17:36:23-876770 INFO     Start training LoRA Standard ...
17:36:23-877770 INFO     Validating lr scheduler arguments...
17:36:23-878770 INFO     Validating optimizer arguments...
17:36:23-878770 INFO     Validating
                         C:/Users/Braeden/Desktop/webui/webui/models/Stable-diffusion/cyberrealisticPony_v65.safetensors
                         existence... SUCCESS
17:36:23-879769 INFO     Validating C:/Users/Braeden/Downloads/underwater/img existence... SUCCESS
17:36:23-882769 INFO     Regulatization factor: 1
17:36:23-883770 INFO     Total steps: 0
17:36:23-883770 INFO     Train batch size: 1
17:36:23-884770 INFO     Gradient accumulation steps: 1
17:36:23-884770 INFO     Epoch: 1
17:36:23-885770 INFO     Max train steps: 1600
17:36:23-886770 INFO     stop_text_encoder_training = 0
17:36:23-886770 INFO     lr_warmup_steps = 160
17:36:23-888770 INFO     Saving training config to last_20241024-173623.json...
Traceback (most recent call last):
  File "C:\Users\Braeden\Desktop\LoraTrainer\kohya_ss\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\Braeden\Desktop\LoraTrainer\kohya_ss\venv\lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\Braeden\Desktop\LoraTrainer\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\Braeden\Desktop\LoraTrainer\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\Braeden\Desktop\LoraTrainer\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\Braeden\Desktop\LoraTrainer\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Braeden\Desktop\LoraTrainer\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "C:\Users\Braeden\Desktop\LoraTrainer\kohya_ss\venv\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\Braeden\Desktop\LoraTrainer\kohya_ss\kohya_gui\lora_gui.py", line 1283, in train_model
    SaveConfigFile(
  File "C:\Users\Braeden\Desktop\LoraTrainer\kohya_ss\kohya_gui\common_gui.py", line 1263, in SaveConfigFile
    os.makedirs(os.path.dirname(folder_path))
  File "C:\Users\Braeden\AppData\Local\Programs\Python\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

**Comment by b-fission** [comment]
You need to have a folder path in the "Output directory for trained model" box.
