### ISSUE TITLE
Getting "ValueError: Default process group has not been initialized, please make sure to call init_process_group"

### ISSUE THREAD

**Issue by iamrohitanshu** [bmaltais/kohya_ss#2923]
I have the latest update of the sd3-flux.1 branch, though I'm trying to train an **SDXL lora** here.
I'm repeatedly getting this error. First (unrelated) error was that bucket resolution should at least be 64, though I've been training with 32 so far, and it has always worked. 
I'm using the same config which was used to train a lora just a couple of days ago, so I don't think it's about the config.

```
 INFO     preparing accelerator
Traceback (most recent call last):
  File "D:\kohya_ss\sd-scripts\sdxl_train_network.py", line 228, in <module>
    trainer.train(args)
  File "D:\kohya_ss\sd-scripts\train_network.py", line 370, in train
    accelerator = train_util.prepare_accelerator(args)
  File "D:\kohya_ss\sd-scripts\library\train_util.py", line 5178, in prepare_accelerator
    accelerator = Accelerator(
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 383, in __init__
    self.state = AcceleratorState(
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\state.py", line 846, in __init__
    PartialState(cpu, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\state.py", line 270, in __init__
    self.num_processes = torch.distributed.get_world_size()
  File "D:\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 1832, in get_world_size
    return _get_group_size(group)
  File "D:\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 864, in _get_group_size
    default_pg = _get_default_group()
  File "D:\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 1025, in _get_default_group
    raise ValueError(
ValueError: Default process group has not been initialized, please make sure to call init_process_group.
Traceback (most recent call last):
  File "C:\Users\tanshu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\tanshu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohya_ss\\venv\\Scripts\\python.exe', 'D:/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', 'D:/createLora/all-amxl/model/config_lora-20241026-154300.toml', '--network_train_unet_only']' returned non-zero exit status 1.
15:43:38-377239 INFO     Training has ended.
```

**Comment by iamrohitanshu** [comment]
The issue has been resolved. (I'm on the next step of training).
For future reference, Under "Accelerate launch" tab, "Distributed GPUs", I set "GPU IDs" to 0. (I have 2 different GPUs)
I've left it blank up until now, but something in the code must have changed and it is now required to be set explicitly, I guess.

**Comment by AfterHAL** [comment]
> The issue has been resolved. (I'm on the next step of training). For future reference, Under "Accelerate launch" tab, "Distributed GPUs", I set "GPU IDs" to 0. (I have 2 different GPUs) I've left it blank up until now, but something in the code must have changed and it is now required to be set explicitly, I guess.

Hey @iamrohitanshu  ! 
I solved this problem in 2 minutes thanks to you.
Thank you very much.

**Comment by pspkurara** [comment]
I had the same problem.
I think you should force a value in the GUI.
You shouldn't allow blanks.
If it's an empty string, you should force it to have an initial value (e.g. 0).
