### ISSUE TITLE
FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated

### ISSUE THREAD

**Issue by toxsickcity** [bmaltais/kohya_ss#2935]
Hello,

Help!, Can anyone advise what I need to do to resolve the below.?
I am trying to create a flux lora on my RTX 3060 12GB.

Cheers,
Shaun

```
20:39:58-455865 INFO     Start training LoRA Flux1 ...
20:39:58-457366 INFO     Validating lr scheduler arguments...
20:39:58-459367 INFO     Validating optimizer arguments...
20:39:58-461866 INFO     Validating lora type is Flux1 if flux1 checkbox is checked...
20:39:58-463366 INFO     Validating U:/tmp existence and writability... SUCCESS
20:39:58-464365 INFO     Validating U:/kohya_ss-sd3-flux1/kohya_ss/models/flux-dev-fp8.safetensors existence... SUCCESS
20:39:58-465903 INFO     Validating U:\kohya_ss-sd3-flux1\kohya_ss\Input\img\8_TedModel3Flux existence... SUCCESS
20:39:58-472409 INFO     Regularization factor: 1
20:39:58-473908 INFO     Train batch size: 3
20:39:58-474908 INFO     Gradient accumulation steps: 1
20:39:58-475408 INFO     Epoch: 1
20:39:58-475908 INFO     Max train steps: 100
20:39:58-476408 INFO     stop_text_encoder_training = 0
20:39:58-476907 INFO     lr_warmup_steps = 0
20:39:58-480408 INFO     Saving training config to U:/tmp\TedModel3_flux_20241028-203958.json...
20:39:58-482419 INFO     Executing command:
                         C:\Users\User\AppData\Local\Programs\Python\Python310\Scripts\accelerate.EXE launch
                         --dynamo_backend no --dynamo_mode default --mixed_precision bf16 --num_processes 1
                         --num_machines 1 --num_cpu_threads_per_process 2
                         U:/kohya_ss-sd3-flux1/kohya_ss/sd-scripts/flux_train_network.py --config_file
                         U:/tmp/config_lora-20241028-203958.toml
C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\utils\outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "U:\kohya_ss-sd3-flux1\kohya_ss\sd-scripts\flux_train_network.py", line 13, in <module>
    from library import flux_models, flux_train_utils, flux_utils, sd3_train_utils, strategy_base, strategy_flux, train_util
  File "U:\kohya_ss-sd3-flux1\kohya_ss\sd-scripts\library\flux_train_utils.py", line 17, in <module>
    from library import flux_models, flux_utils, strategy_base, train_util
  File "U:\kohya_ss-sd3-flux1\kohya_ss\sd-scripts\library\flux_utils.py", line 15, in <module>
    from library.utils import setup_logging, MemoryEfficientSafeOpen
ImportError: cannot import name 'MemoryEfficientSafeOpen' from 'library.utils' (U:\kohya_ss-sd3-flux1\kohya_ss\sd-scripts\library\utils.py)
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', 'U:/kohya_ss-sd3-flux1/kohya_ss/sd-scripts/flux_train_network.py', '--config_file', 'U:/tmp/config_lora-20241028-203958.toml']' returned non-zero exit status 1.
20:40:05-715519 INFO     Training has ended.
```

**Comment by b-fission** [comment]
There's something wrong with your copy of `sd-scripts/library/utils.py`

Have you cloned/pulled the latest version of the sd3-flux.1 branch and the corresponding submodule for sd-scripts?
