### ISSUE TITLE
Blocks to swap for flux and sd3.5 lora? its available 

### ISSUE THREAD

**Issue by DriveHabits** [bmaltais/kohya_ss#2964]
how can we use it in the gui? or have you added it yet? @bmaltais

**Comment by DriveHabits** [comment]
i manually added it in the command, also seems spilt mode is now deprecated

**Comment by DriveHabits** [comment]
doesn't seem to work though, i end up getting

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by DriveHabits** [comment]
steps:   0%|                                                                                                                                                                                                                        | 0/4000 [00:00<?, ?it/s]2024-11-15 09:43:02 INFO     unet dtype: torch.bfloat16, device: cuda:0                                                                                                                                                                  train_network.py:1098
                    INFO     text_encoder [0] dtype: torch.bfloat16, device: cuda:0                                                                                                                                                      train_network.py:1104
                    INFO     text_encoder [1] dtype: torch.bfloat16, device: cpu                                                                                                                                                         train_network.py:1104

epoch 1/6
                    INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                                                                train_util.py:715
                    INFO     epoch is incremented. current_epoch: 0, epoch: 1                                                                                                                                                                train_util.py:715
D:\kohya_ss\venv\lib\site-packages\torch\autograd\graph.py:825: UserWarning: cuDNN SDPA backward got grad_output.strides() != output.strides(), attempting to materialize a grad_output with matching strides... (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cudnn\MHA.cpp:676.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
steps:   0%|                                                                                                                                                                                              | 2/4000 [00:08<4:52:03,  4.38s/it, avr_loss=0.519]Traceback (most recent call last):
  File "D:\kohya_ss\sd-scripts\flux_train_network.py", line 573, in <module>
    trainer.train(args)
  File "D:\kohya_ss\sd-scripts\train_network.py", line 1196, in train
    noise_pred, target, timesteps, huber_c, weighting = self.get_noise_pred_and_target(
  File "D:\kohya_ss\sd-scripts\flux_train_network.py", line 449, in get_noise_pred_and_target
    model_pred_prior = call_dit(
  File "D:\kohya_ss\sd-scripts\flux_train_network.py", line 371, in call_dit
    model_pred = unet(
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 819, in forward
    return model_forward(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 807, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "D:\kohya_ss\venv\lib\site-packages\torch\amp\autocast_mode.py", line 44, in decorate_autocast
    return func(*args, **kwargs)
  File "D:\kohya_ss\sd-scripts\library\flux_models.py", line 1045, in forward
    img, txt = block(img=img, txt=txt, vec=vec, pe=pe, txt_attention_mask=txt_attention_mask)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\kohya_ss\sd-scripts\library\flux_models.py", line 742, in forward
    return checkpoint(self._forward, img, txt, vec, pe, txt_attention_mask, use_reentrant=False)
  File "D:\kohya_ss\venv\lib\site-packages\torch\_compile.py", line 32, in inner
    return disable_fn(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\torch\_dynamo\eval_frame.py", line 632, in _fn
    return fn(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\torch\utils\checkpoint.py", line 496, in checkpoint
    ret = function(*args, **kwargs)
  File "D:\kohya_ss\sd-scripts\library\flux_models.py", line 691, in _forward
    img_mod1, img_mod2 = self.img_mod(vec)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\kohya_ss\sd-scripts\library\flux_models.py", line 640, in forward
    out = self.lin(nn.functional.silu(vec))[:, None, :].chunk(self.multiplier, dim=-1)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\lycoris\modules\locon.py", line 306, in forward
    weight = weight + diff_weight * self.multiplier
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by DriveHabits** [comment]
im using lycoris

**Comment by DriveHabits** [comment]
even with standard flux lora

Traceback (most recent call last):
  File "D:\kohya_ss\sd-scripts\flux_train_network.py", line 573, in <module>
    trainer.train(args)
  File "D:\kohya_ss\sd-scripts\train_network.py", line 1196, in train
    noise_pred, target, timesteps, huber_c, weighting = self.get_noise_pred_and_target(
  File "D:\kohya_ss\sd-scripts\flux_train_network.py", line 449, in get_noise_pred_and_target
    model_pred_prior = call_dit(
  File "D:\kohya_ss\sd-scripts\flux_train_network.py", line 371, in call_dit
    model_pred = unet(
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 819, in forward
    return model_forward(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 807, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "D:\kohya_ss\venv\lib\site-packages\torch\amp\autocast_mode.py", line 44, in decorate_autocast
    return func(*args, **kwargs)
  File "D:\kohya_ss\sd-scripts\library\flux_models.py", line 1045, in forward
    img, txt = block(img=img, txt=txt, vec=vec, pe=pe, txt_attention_mask=txt_attention_mask)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\kohya_ss\sd-scripts\library\flux_models.py", line 742, in forward
    return checkpoint(self._forward, img, txt, vec, pe, txt_attention_mask, use_reentrant=False)
  File "D:\kohya_ss\venv\lib\site-packages\torch\_compile.py", line 32, in inner
    return disable_fn(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\torch\_dynamo\eval_frame.py", line 632, in _fn
    return fn(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\torch\utils\checkpoint.py", line 496, in checkpoint
    ret = function(*args, **kwargs)
  File "D:\kohya_ss\sd-scripts\library\flux_models.py", line 691, in _forward
    img_mod1, img_mod2 = self.img_mod(vec)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\kohya_ss\sd-scripts\library\flux_models.py", line 640, in forward
    out = self.lin(nn.functional.silu(vec))[:, None, :].chunk(self.multiplier, dim=-1)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_addmm)
steps:   0%|                                                                                                                                                                                                                        | 0/4000 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohya_ss\\venv\\Scripts\\python.exe', 'D:/kohya_ss/sd-scripts/flux_train_network.py', '--config_file', 'C:/Users/Desktop/Pictures/cCC3e5vxxscc4455vv/config_lora-20241115-094806.toml', '--blocks_to_swap', '18', '--fused_backward_pass']' returned non-zero exit status 1.
09:50:28-986232 INFO     Training has ended.

**Comment by FurkanGozukara** [comment]
yes lora currently missing block swap

i notified @bmaltais

**Comment by bmaltais** [comment]
> yes lora currently missing block swap
> 
> i notified @bmaltais

Check the latest commit gor the GUI. Should be visible now.

**Comment by DriveHabits** [comment]
@bmaltais @FurkanGozukara blocks to swap for lora actually doesn't work, also you need to enable Blockwise Fused Optimizer and fused backward pass for lora as well, there is no option for it

**Comment by FurkanGozukara** [comment]
@DriveHabits on the contrary it is working i made it work :)

i am testing every config to update here my values

as low as 4 GB can train 🗡️ 

![image](https://github.com/user-attachments/assets/f1fee5fb-0056-4d0b-9ed5-5d476573f098)

**Comment by DriveHabits** [comment]
oohh i just figured it out as well

**Comment by DriveHabits** [comment]
@bmaltais Prior reg as well as adding reg images with split mode doesnt seem to to work. it works without reg images. i get the same errors above.

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_addmm)
steps:   0%|

**Comment by bmaltais** [comment]
I have fixed an issue where the actual parameters were not put in the
toml... should be there now. I guess I rushed the change before my road
trip.

**Comment by DriveHabits** [comment]
@bmaltais safe travels thank you! enjoy your trip!

**Comment by DriveHabits** [comment]
@bmaltais doesn't seem to work with reg images with dop, still giving issues

**Comment by bmaltais** [comment]
Is there a missing parameter in the GUI? What do I need to add to pass the right config to sd-scripts?

**Comment by DriveHabits** [comment]
@bmaltais he fixed it with his latest update, it all works good now

**Comment by bmaltais** [comment]
Saw that. I already updated the GUI to use the latest commit.
