### ISSUE TITLE
ERROR: UnboundLocalError: local variable 'max_train_steps_info' referenced before assignment

### ISSUE THREAD

**Issue by bbecausereasonss** [bmaltais/kohya_ss#2969]
Was just working until I updated it. Trying to continue a Dreambooth training (same config that was working before) Furkans...

UnboundLocalError: local variable 'max_train_steps_info' referenced before assignment
Is this a new bug? I just updated Kohya....

Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\kohya_ss_flux\kohya_ss\venv\lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\xxxx\Deep\kohya_ss_flux\kohya_ss\venv\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\xxxx\Deep\kohya_ss_flux\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 2018, in process_api
    result = await self.call_function(
  File "C:\Users\xxxx\Deep\kohya_ss_flux\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1567, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\xxxx\Deep\kohya_ss_flux\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\xxxx\Deep\kohya_ss_flux\kohya_ss\venv\lib\site-packages\anyio_backends_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "C:\Users\xxxx\Deep\kohya_ss_flux\kohya_ss\venv\lib\site-packages\anyio_backends_asyncio.py", line 943, in run
    result = context.run(func, args)
  File "C:\Users\xxxx\Deep\kohya_ss_flux\kohya_ss\venv\lib\site-packages\gradio\utils.py", line 846, in wrapper
    response = f(args, **kwargs)
  File "C:\Users\xxxx\Deep\kohya_ss_flux\kohya_ss\kohya_gui\dreambooth_gui.py", line 817, in train_model
    log.info(max_train_steps_info)
UnboundLocalError: local variable

**Comment by bbecausereasonss** [comment]
Changing Max train epoch or steps to a super high number does not fix error.

**Comment by bbecausereasonss** [comment]
Confirming after rolling back to checkout d47e3e6, it fixed the error. Last commit to fix (match steps) actually created the error.

**Comment by Diastro** [comment]
Seeing the same thing.

**Comment by Sylsatra** [comment]
Go into the mentioned file "kohya_ss_flux\kohya_ss\kohya_gui\dreambooth_gui.py" and add max_train_steps_info = 0 before the "if" at line 814 or sth!

**Comment by Sylsatra** [comment]
> Go into the mentioned file "kohya_ss_flux\kohya_ss\kohya_gui\dreambooth_gui.py" and add max_train_steps_info = 0 before the "if" at line 814 or sth!

This will use the default value of 1600

**Comment by FurkanGozukara** [comment]
same error

this commit working

https://github.com/bmaltais/kohya_ss/commit/d47e3e664286314c6b9728bb38b1c7a576211572

**Comment by bmaltais** [comment]
Latest commit should fix this issue. Missed the fact that in some cases it would not be set as a variable and trying to call it would cause this error...

**Comment by FurkanGozukara** [comment]
> Latest commit should fix this issue. Missed the fact that in some cases it would not be set as a variable and trying to call it would cause this error...

thank you so much for swift fix
