### ISSUE TITLE
Kohya and Flux resulting in access violation error (returned non-zero exit status 3221225477)

### ISSUE THREAD

**Issue by Diastro** [bmaltais/kohya_ss#2977]
Using https://github.com/bmaltais/kohya_ss/tree/sd3-flux.1 branch, I keep getting access violation errors.
System has 16Gb of ram and using RTX 4070Ti Super.

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\WUI\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\WUI\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "D:\WUI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "D:\WUI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\WUI\\kohya_ss\\venv\\Scripts\\python.exe', 'D:/WUI/kohya_ss/sd-scripts/flux_train.py', '--config_file', 'C:/Users/User/Desktop/loratest2/out2/config_dreambooth-20241118-145210.toml']' returned non-zero exit status 3221225477
```

Configuration :
```
{
  "adaptive_noise_scale": 0,
  "additional_parameters": "",
  "ae": "D:/WUI/CUI/ComfyUI/models/vae/ae.safetensors",
  "apply_t5_attn_mask": false,
  "async_upload": false,
  "blocks_to_swap": 24,
  "blockwise_fused_optimizers": false,
  "bucket_no_upscale": true,
  "bucket_reso_steps": 64,
  "cache_latents": true,
  "cache_latents_to_disk": false,
  "caption_dropout_every_n_epochs": 0,
  "caption_dropout_rate": 0,
  "caption_extension": ".txt",
  "clip_g": "",
  "clip_l": "",
  "clip_skip": 1,
  "color_aug": false,
  "cpu_offload_checkpointing": false,
  "dataset_config": "",
  "debiased_estimation_loss": false,
  "disable_mmap_load_safetensors": false,
  "discrete_flow_shift": 3,
  "double_blocks_to_swap": 0,
  "dynamo_backend": "no",
  "dynamo_mode": "default",
  "dynamo_use_dynamic": false,
  "dynamo_use_fullgraph": false,
  "enable_bucket": true,
  "epoch": 1,
  "extra_accelerate_launch_args": "",
  "flip_aug": false,
  "flux1_cache_text_encoder_outputs": false,
  "flux1_cache_text_encoder_outputs_to_disk": false,
  "flux1_checkbox": true,
  "flux1_clip_l": "D:/WUI/CUI/ComfyUI/models/clip/clip_l.safetensors",
  "flux1_t5xxl": "D:/WUI/CUI/ComfyUI/models/clip/t5xxl_fp8_e4m3fn.safetensors",
  "flux_fused_backward_pass": true,
  "fp8_base": true,
  "full_bf16": false,
  "full_fp16": false,
  "fused_backward_pass": false,
  "fused_optimizer_groups": 0,
  "gpu_ids": "0",
  "gradient_accumulation_steps": 1,
  "gradient_checkpointing": false,
  "guidance_scale": 3.5,
  "huber_c": 0.1,
  "huber_schedule": "snr",
  "huggingface_path_in_repo": "",
  "huggingface_repo_id": "",
  "huggingface_repo_type": "",
  "huggingface_repo_visibility": "",
  "huggingface_token": "",
  "ip_noise_gamma": 0,
  "ip_noise_gamma_random_strength": false,
  "keep_tokens": 0,
  "learning_rate": 1e-05,
  "learning_rate_te": 1e-05,
  "learning_rate_te1": 1e-05,
  "learning_rate_te2": 1e-05,
  "log_config": false,
  "log_tracker_config": "",
  "log_tracker_name": "",
  "log_with": "",
  "logging_dir": "",
  "logit_mean": 0,
  "logit_std": 1,
  "loss_type": "l2",
  "lr_scheduler": "cosine",
  "lr_scheduler_args": "",
  "lr_scheduler_num_cycles": 1,
  "lr_scheduler_power": 1,
  "lr_scheduler_type": "",
  "lr_warmup": 10,
  "lr_warmup_steps": 0,
  "main_process_port": 0,
  "masked_loss": false,
  "max_bucket_reso": 2048,
  "max_data_loader_n_workers": 0,
  "max_resolution": "512,512",
  "max_timestep": 1000,
  "max_token_length": 75,
  "max_train_epochs": 0,
  "max_train_steps": 1600,
  "mem_eff_attn": false,
  "mem_eff_save": false,
  "metadata_author": "",
  "metadata_description": "",
  "metadata_license": "",
  "metadata_tags": "",
  "metadata_title": "",
  "min_bucket_reso": 256,
  "min_snr_gamma": 0,
  "min_timestep": 0,
  "mixed_precision": "fp16",
  "mode_scale": 1.29,
  "model_list": "",
  "model_prediction_type": "sigma_scaled",
  "multi_gpu": false,
  "multires_noise_discount": 0.3,
  "multires_noise_iterations": 0,
  "no_token_padding": false,
  "noise_offset": 0,
  "noise_offset_random_strength": false,
  "noise_offset_type": "Original",
  "num_cpu_threads_per_process": 2,
  "num_machines": 1,
  "num_processes": 1,
  "optimizer": "AdamW8bit",
  "optimizer_args": "",
  "output_dir": "C:/Users/User/Desktop/loratest2/out2",
  "output_name": "last",
  "persistent_data_loader_workers": false,
  "pretrained_model_name_or_path": "D:/WUI/CUI/ComfyUI/models/unet/flux1-dev-fp8.safetensors",
  "prior_loss_weight": 1,
  "random_crop": false,
  "reg_data_dir": "",
  "resume": "",
  "resume_from_huggingface": "",
  "sample_every_n_epochs": 0,
  "sample_every_n_steps": 0,
  "sample_prompts": "",
  "sample_sampler": "euler_a",
  "save_as_bool": false,
  "save_clip": false,
  "save_every_n_epochs": 1,
  "save_every_n_steps": 0,
  "save_last_n_epochs": 0,
  "save_last_n_epochs_state": 0,
  "save_last_n_steps": 0,
  "save_last_n_steps_state": 0,
  "save_model_as": "safetensors",
  "save_precision": "fp16",
  "save_state": false,
  "save_state_on_train_end": false,
  "save_state_to_huggingface": false,
  "save_t5xxl": false,
  "scale_v_pred_loss_like_noise_pred": false,
  "sd3_cache_text_encoder_outputs": false,
  "sd3_cache_text_encoder_outputs_to_disk": false,
  "sd3_checkbox": false,
  "sd3_text_encoder_batch_size": 1,
  "sdxl": false,
  "sdxl_cache_text_encoder_outputs": false,
  "sdxl_no_half_vae": false,
  "seed": 0,
  "shuffle_caption": false,
  "single_blocks_to_swap": 0,
  "skip_cache_check": false,
  "split_mode": false,
  "stop_text_encoder_training": 0,
  "t5xxl": "",
  "t5xxl_device": "",
  "t5xxl_dtype": "bf16",
  "t5xxl_max_token_length": 512,
  "timestep_sampling": "sigma",
  "train_batch_size": 1,
  "train_blocks": "all",
  "train_data_dir": "C:/Users/User/Desktop/loratest2/out2/img",
  "v2": false,
  "v_parameterization": false,
  "v_pred_like_loss": 0,
  "vae": "",
  "vae_batch_size": 0,
  "wandb_api_key": "",
  "wandb_run_name": "",
  "weighted_captions": false,
  "weighting_scheme": "logit_normal",
  "xformers": "xformers"
}
```

**Comment by Diastro** [comment]
Was running out of RAM. Also make sure to select "Lora" and not "Dreambooth" as dreambooth has higher memory requirements.
