### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by Pippipylup** [bmaltais/kohya_ss#298]
```
max_train_steps = 2400
stop_text_encoder_training = 0
lr_warmup_steps = 0
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" --train_data_dir="C:/Users/ihigg/Downloads/dataset/lora/image" --resolution=512,512 --output_dir="C:/Users/ihigg/Downloads/dataset/lora/model" --logging_dir="C:/Users/ihigg/Downloads/dataset/lora/log" --network_alpha="128" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=128 --output_name="Miku1" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="1" --max_train_steps="2400" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --seed="1234" --caption_extension=".txt" --cache_latents --optimizer_type="AdamW" --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --mem_eff_attn --gradient_checkpointing --xformers --bucket_no_upscale
prepare tokenizer
Use DreamBooth method.
Traceback (most recent call last):
  File "G:\!SD_LoRA\kohya_ss\train_network.py", line 507, in <module>
    train(args)
  File "G:\!SD_LoRA\kohya_ss\train_network.py", line 61, in train
    train_dataset = DreamBoothDataset(args.train_batch_size, args.train_data_dir, args.reg_data_dir,
TypeError: DreamBoothDataset.__init__() takes 13 positional arguments but 21 were given
Traceback (most recent call last):
  File "C:\Users\ihigg\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ihigg\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "G:\!SD_LoRA\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "G:\!SD_LoRA\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "G:\!SD_LoRA\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "G:\!SD_LoRA\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['G:\\!SD_LoRA\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=C:/Users/ihigg/Downloads/dataset/lora/image', '--resolution=512,512', '--output_dir=C:/Users/ihigg/Downloads/dataset/lora/model', '--logging_dir=C:/Users/ihigg/Downloads/dataset/lora/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=Miku1', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=2400', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.
```

I've read lots of other reports about similar error messages, but I still can't get it to work
Things I've tried:
-Unchecking use 8bit adam/using a different optimizer
-Lowering the resolution
-Replacing the train_util.py file
-Using bf16 instead of fp16
-One-by-one unchecking individual boxes and testing that
-Reinstalling it but told it to use the CPU only

Don't really know where to go from here, any ideas? Thanks

edit: Fixed code block for readability

**Comment by Mctwost** [comment]
Make sure you are in the dreambooth lora tab and not the dreambooth. Not saying that is that but just in case.

**Comment by kuanos** [comment]
same issue here
