### ISSUE TITLE
Can you add support for sd3.5 lora training, its available on sd scripts

### ISSUE THREAD

**Issue by DriveHabits** [bmaltais/kohya_ss#2982]
sd3.5 options for lora training is not available on the gui, like clip l t5 etc

**Comment by PGCRT** [comment]
I don't understand why there is a [[sd3-sd3.5-flux]](https://github.com/bmaltais/kohya_ss/tree/sd3-sd3.5-flux) branch If it's not working yet? Has anyone ever managed to train SD3.5 LoRA with kohya_ss?

**Comment by Reapermaid** [comment]
I am having endless problems with this. The model seems to be incompatible with Kohya. I am not an expert, but this is some of the log showing the error. I have been trying to understand what is going wrong...

  INFO     loading model for process 0/1                                                                                                       train_util.py:5274
                    INFO     load StableDiffusion checkpoint: D:/kohya_ss/models/sd3.5_large.safetensors                                                         train_util.py:5230
Key 'time_embed.0.weight' not found in checkpoint.
Key 'time_embed.0.bias' not found in checkpoint.
Key 'time_embed.2.weight' not found in checkpoint.
Key 'time_embed.2.bias' not found in checkpoint.
Key 'input_blocks.0.0.weight' not found in checkpoint.
Key 'out.0.weight' not found in checkpoint.
Key 'out.0.bias' not found in checkpoint.
Key 'out.2.weight' not found in checkpoint.
Key 'out.2.bias' not found in checkpoint.
Traceback (most recent call last):
  File "D:\kohya_ss\sd-scripts\train_network.py", line 1479, in <module>
    trainer.train(args)
  File "D:\kohya_ss\sd-scripts\train_network.py", line 382, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "D:\kohya_ss\sd-scripts\train_network.py", line 102, in load_target_model
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "D:\kohya_ss\sd-scripts\library\train_util.py", line 5276, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "D:\kohya_ss\sd-scripts\library\train_util.py", line 5231, in _load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(
  File "D:\kohya_ss\sd-scripts\library\model_util.py", line 1031, in load_models_from_stable_diffusion_checkpoint
    converted_unet_checkpoint = convert_ldm_unet_checkpoint(v2, state_dict, unet_config)
  File "D:\kohya_ss\sd-scripts\library\model_util.py", line 346, in convert_ldm_unet_checkpoint
    resnet_0 = middle_blocks[0]
KeyError: 0
Traceback (most recent call last):
  File "C:\Users\Windows 11\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Windows 11\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Windows 11\AppData\Local\Programs\Python\Python310\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Windows 11\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "C:\Users\Windows 11\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "C:\Users\Windows 11\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Windows 11\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', 'D:/kohya_ss/sd-scripts/train_network.py', '--config_file', 'D:/Lora Training Data/BanjoV1/Model/config_lora-20241207-005430.toml']' returned non-zero exit status 1.
00:54:46-743818 INFO     Training has ended.

**Comment by bmaltais** [comment]
> *This was generated by AI during triage.*
## Triage outcome: already implemented

**Category:** enhancement  
**State:** wontfix (already shipped)

SD3.5 LoRA training is supported in current sd-scripts (`sd3_train_network.py`, including SD3.5-specific options such as scaled positional embeddings and positional-embedding random crop) and is wired in the GUI under the **SD3** training controls (shared SD3 / SD3.5 path).

### Where it lives

1. Open the **LoRA** tab.
2. Enable **SD3** (not only the model path — the SD3 checkbox/toggle).
3. Open the **SD3** accordion and set **CLIP-L**, **CLIP-G**, **T5XXL**, and other SD3/SD3.5 options as needed.
4. Point the pretrained model at your SD3.5 weights.

That path launches `sd3_train_network.py`. Related request #2924 was closed the same way.

### About the failure log on this issue

The traceback that runs:

```text
.../sd-scripts/train_network.py --config_file ...
load StableDiffusion checkpoint: .../sd3.5_large.safetensors
Key 'time_embed.0.weight' not found ...
KeyError in convert_ldm_unet_checkpoint
```

is the **SD 1.x** trainer loading an **SD3.5** checkpoint (UNet LDM conversion). That happens when SD3 is **not** enabled, so the GUI falls through to `train_network.py`. It is not evidence that SD3.5 is missing.

If something still fails **with SD3 enabled** and the command line shows `sd3_train_network.py`, open a new **bug** with GUI version, full log, and exact model filenames.

Closing as already implemented.

**Comment by bmaltais** [comment]
Closing: already implemented (see triage comment).
