### ISSUE TITLE
ValueError: bypass mode is not supported in Full algo.

### ISSUE THREAD

**Issue by DarkAlchy** [bmaltais/kohya_ss#2990]
Traceback (most recent call last):
  File "/mnt/Win_D/kohya_ss/sd-scripts/flux_train_network.py", line 574, in <module>
    trainer.train(args)
  File "/mnt/Win_D/kohya_ss/sd-scripts/train_network.py", line 453, in train
    network = network_module.create_network(
  File "/mnt/Win_D/kohya_ss/venv/lib/python3.10/site-packages/lycoris/kohya.py", line 91, in create_network
    network = LycorisNetworkKohya(
  File "/mnt/Win_D/kohya_ss/venv/lib/python3.10/site-packages/lycoris/kohya.py", line 469, in __init__
    create_modules(
  File "/mnt/Win_D/kohya_ss/venv/lib/python3.10/site-packages/lycoris/kohya.py", line 425, in create_modules
    create_modules_(f"{prefix}_{name}", module, algo, next_config)[
  File "/mnt/Win_D/kohya_ss/venv/lib/python3.10/site-packages/lycoris/kohya.py", line 398, in create_modules_
    lora = create_single_module(lora_name, module, algo, **configs)
  File "/mnt/Win_D/kohya_ss/venv/lib/python3.10/site-packages/lycoris/kohya.py", line 355, in create_single_module
    lora = network_module_dict[algo_name](
  File "/mnt/Win_D/kohya_ss/venv/lib/python3.10/site-packages/lycoris/modules/full.py", line 70, in __init__
    raise ValueError("bypass mode is not supported in Full algo.")
ValueError: bypass mode is not supported in Full algo.

Where do I turn that off as I never turned it on in the first place, at least not by name?

edit:  I looked at the .json file

  "blocks_to_swap": 0,
  "bucket_no_upscale": true,
  "bucket_reso_steps": 64,
  "bypass_mode": false,
  "cache_latents": true,
  
  
bypass is off here.

**Comment by chi9230** [comment]
Kohya_ss GUI version: v25.0.3

I tried changing line 61 in kohya_ss\venv\Lib\site-packages\lycoris\kohya.py from:

`bypass_mode = str_bool(kwargs.get("bypass_mode", None))`

to:

`bypass_mode = str_bool(kwargs.get("bypass_mode", False))`

and the training was able to start normally after that.

Sorry, I’m not very familiar with Python, so I’m not sure about the exact behavior of the second argument in str_bool(), but it seems like when it’s set to None here, it returns True by default.

@

**Comment by DarkAlchy** [comment]
Bool is boolean so True or False not that None as you pointed out.  I haven't used Kohya in eons (this was the last straw for me) as I went to a much saner trainer, but I must ask if this is still a thing?

**Comment by chi9230** [comment]
> Bool is boolean so True or False not that None as you pointed out. I haven't used Kohya in eons (this was the last straw for me) as I went to a much saner trainer, but I must ask if this is still a thing?

I only encounter this issue when I set the LoRA type to LyCORIS/Native Fine-Tuning. Most of the time I use LyCORIS/LoCon, and everything always runs smoothly with that.

By the way, I’m curious to know which trainer you moved to.

**Comment by DarkAlchy** [comment]
SimpleTuner.  I haven't trained in a while, not publicly, and that one was Linux only (has a V2 now and we now have triton on Windows).  I may soon start training again for video models, which it does.
