### ISSUE TITLE
SDXL training stops after generate first sample image

### ISSUE THREAD

**Issue by kalle07** [bmaltais/kohya_ss#2999]
024-12-01 16:59:50 INFO                                                                              train_util.py:6115
                    INFO     generating sample images at step / サンプル画像生成 ステップ: 100        train_util.py:6116
                    INFO     prompt: A photograph of a ...      train_util.py:6264
                                                 INFO     negative_prompt: None                                                    train_util.py:6265
                    INFO     height: 512                                                              train_util.py:6266
                    INFO     width: 512                                                               train_util.py:6267
                    INFO     sample_steps: 30                                                         train_util.py:6268
                    INFO     scale: 7.5                                                               train_util.py:6269
                    INFO     sample_sampler: dpmsolver++                                              train_util.py:6270
                                                                                                                       e:\kohya_ss\venv\lib\site-packages\torch\utils\checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
                                                                                                                       2024-12-01 17:00:01 INFO     prompt: --n sketch, cartoon, signature, label, monochrome, jewelry,      train_util.py:6264
                    INFO     negative_prompt: None                                                    train_util.py:6265
                    INFO     height: 1024                                                             train_util.py:6266
                    INFO     width: 680                                                               train_util.py:6267
                    INFO     sample_steps: 40                                                         train_util.py:6268
                    INFO     scale: 4.0                                                               train_util.py:6269
                    INFO     sample_sampler: dpmsolver++                                              train_util.py:6270
                    INFO     seed: 500000                                                             train_util.py:6272
                                                    
raceback (most recent call last):
  File "e:\kohya_ss\sd-scripts\sdxl_train_network.py", line 228, in <module>
    trainer.train(args)
  File "e:\kohya_ss\sd-scripts\train_network.py", line 1251, in train
    self.sample_images(
  File "e:\kohya_ss\sd-scripts\sdxl_train_network.py", line 211, in sample_images
    sdxl_train_util.sample_images(accelerator, args, epoch, global_step, device, vae, tokenizer, text_encoder, unet)
  File "e:\kohya_ss\sd-scripts\library\sdxl_train_util.py", line 382, in sample_images
    return train_util.sample_images_common(SdxlStableDiffusionLongPromptWeightingPipeline, *args, **kwargs)
  File "e:\kohya_ss\sd-scripts\library\train_util.py", line 6187, in sample_images_common
    sample_image_inference(
  File "e:\kohya_ss\sd-scripts\library\train_util.py", line 6274, in sample_image_inference
    latents = pipeline(
  File "e:\kohya_ss\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "e:\kohya_ss\sd-scripts\library\sdxl_lpw_stable_diffusion.py", line 936, in __call__
    noise_pred = self.unet(latent_model_input, t, text_embedding, vector_embedding)
  File "e:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "e:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "e:\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 819, in forward
    return model_forward(*args, **kwargs)
  File "e:\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 807, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "e:\kohya_ss\venv\lib\site-packages\torch\amp\autocast_mode.py", line 44, in decorate_autocast
    return func(*args, **kwargs)
  File "e:\kohya_ss\sd-scripts\library\sdxl_original_unet.py", line 1110, in forward
    h = torch.cat([h, hs.pop()], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 44 but got size 43 for tensor number 1 in the list.
steps:   9%|█▍             | 100/1067 [13:28<2:10:22,  8.09s/it, Average key norm=0.083, Keys Scaled=0, avr_loss=0.101]
Traceback (most recent call last):
  File "C:\Users\kallemst\.pyenv\pyenv-win\versions\3.10.11\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\kallemst\.pyenv\pyenv-win\versions\3.10.11\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "e:\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "e:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "e:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "e:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['e:\\kohya_ss\\venv\\Scripts\\python.exe', 'e:/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', 'D:/123/model/config_lora-20241201-164539.toml', '--network_train_unet_only']' returned non-zero exit status 1.
17:00:05-975731 INFO     Training has ended.

**Comment by joshgura** [comment]
i don't know what caused that for you but for me i set the sample size to 512x768 because anything higher than that was seemingly creating an oom situation on my 12gb 3060
