### ISSUE TITLE
LoRa training with no results

### ISSUE THREAD

**Issue by YARAZ-EX** [bmaltais/kohya_ss#3006]
**I'm a newbie and can't figure out what the problem is. Please help me.**

**Here's the history of the console**

INFO     [Dataset 0]                                               config_util.py:578
                    INFO     loading image sizes.                                       train_util.py:911
100%|█████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 7377.58it/s]
                    INFO     make buckets                                               train_util.py:917
                    WARNING  min_bucket_reso and max_bucket_reso are ignored if         train_util.py:934
                             bucket_no_upscale is set, because bucket reso is defined
                             by image size automatically /
                             bucket_no_upscaleが指定された場合は、bucketの解像度は画像
                             サイズから自動計算されるため、min_bucket_resoとmax_bucket_
                             resoは無視されます
                    INFO     number of images (including repeats) /                     train_util.py:963
                             各bucketの画像枚数（繰り返し回数を含む）
                    INFO     bucket 0: resolution (1024, 1024), count: 1000             train_util.py:968
                    INFO     mean ar error (without repeats): 0.0                       train_util.py:973
                    WARNING  clip_skip will be unexpected /                        sdxl_train_util.py:352
                             SDXL学習ではclip_skipは動作しません
                    INFO     preparing accelerator                                   train_network.py:225
accelerator device: cuda
                    INFO     loading model for process 0/1                          sdxl_train_util.py:33
                    INFO     load StableDiffusion checkpoint:                       sdxl_train_util.py:74
                             D:\Donwloads\sd_xl_base_1.0.safetensors
                    INFO     building U-Net                                        sdxl_model_util.py:198
                    INFO     loading U-Net from checkpoint                         sdxl_model_util.py:202
2024-12-08 17:57:17 INFO     U-Net: <All keys matched successfully>                sdxl_model_util.py:208
                    INFO     building text encoders                                sdxl_model_util.py:211
2024-12-08 17:57:18 INFO     loading text encoders from checkpoint                 sdxl_model_util.py:264
2024-12-08 17:57:21 INFO     text encoder 1: <All keys matched successfully>       sdxl_model_util.py:278
2024-12-08 17:57:37 INFO     text encoder 2: <All keys matched successfully>       sdxl_model_util.py:282
                    INFO     building VAE                                          sdxl_model_util.py:285
2024-12-08 17:57:43 INFO     loading VAE from checkpoint                           sdxl_model_util.py:290
2024-12-08 17:57:45 INFO     VAE: <All keys matched successfully>                  sdxl_model_util.py:293
                    INFO     Enable xformers for U-Net                                 train_util.py:3040
import network module: networks.lora
2024-12-08 17:57:47 INFO     [Dataset 0]                                               train_util.py:2323
                    INFO     caching latents.                                          train_util.py:1095
                    INFO     checking cache validity...                                train_util.py:1105
100%|█████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 3581.08it/s]
                    INFO     caching latents...                                        train_util.py:1144
100%|███████████████████████████████████████████████████████████████████| 50/50 [00:41<00:00,  1.20it/s]
2024-12-08 17:58:29 INFO     create LoRA network. base dim (rank): 32, alpha: 1               lora.py:928
                    INFO     neuron dropout: p=None, rank dropout: p=None, module dropout:    lora.py:929
                             p=None
                    INFO     create LoRA for Text Encoder 1:                                 lora.py:1020
                    INFO     create LoRA for Text Encoder 2:                                 lora.py:1020
2024-12-08 17:58:30 INFO     create LoRA for Text Encoder: 264 modules.                      lora.py:1028
                    INFO     create LoRA for U-Net: 722 modules.                             lora.py:1036
                    INFO     enable LoRA for text encoder: 264 modules                       lora.py:1077
                    INFO     enable LoRA for U-Net: 722 modules                              lora.py:1082
prepare optimizer, data loader etc.
                    INFO     use Adafactor optimizer | {'scale_parameter': False,      train_util.py:4485
                             'relative_step': False, 'warmup_init': False}
                    WARNING  because max_grad_norm is set, clip_grad_norm is enabled.  train_util.py:4513
                             consider set to 0 /
                             max_grad_normが設定されているためclip_grad_normが有効にな
                             ります。0に設定して無効にしたほうがいいかもしれません
                    WARNING  constant_with_warmup will be good /                       train_util.py:4517
                             スケジューラはconstant_with_warmupが良いかもしれません
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 1000
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 1000
  num epochs / epoch数: 10
  batch size per device / バッチサイズ: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 10000
steps:   0%|                                                                  | 0/10000 [00:00<?, ?it/s]
epoch 1/10
2024-12-08 17:59:42 INFO     epoch is incremented. current_epoch: 0, epoch: 1           train_util.py:703
Traceback (most recent call last):
  File "D:\Programs\KohyaTrainer\kohya_ss\sd-scripts\sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "D:\Programs\KohyaTrainer\kohya_ss\sd-scripts\train_network.py", line 967, in train
    noise_pred = self.call_unet(
  File "D:\Programs\KohyaTrainer\kohya_ss\sd-scripts\sdxl_train_network.py", line 164, in call_unet
    noise_pred = unet(noisy_latents, timesteps, text_embedding, vector_embedding)
  File "D:\Programs\KohyaTrainer\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Programs\KohyaTrainer\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Programs\KohyaTrainer\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 680, in forward
    return model_forward(*args, **kwargs)
  File "D:\Programs\KohyaTrainer\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 668, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "D:\Programs\KohyaTrainer\kohya_ss\venv\lib\site-packages\torch\amp\autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "D:\Programs\KohyaTrainer\kohya_ss\sd-scripts\library\sdxl_original_unet.py", line 1111, in forward
    h = call_module(module, h, emb, context)
  File "D:\Programs\KohyaTrainer\kohya_ss\sd-scripts\library\sdxl_original_unet.py", line 1095, in call_module
    x = layer(x, context)
  File "D:\Programs\KohyaTrainer\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Programs\KohyaTrainer\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Programs\KohyaTrainer\kohya_ss\sd-scripts\library\sdxl_original_unet.py", line 750, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "D:\Programs\KohyaTrainer\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Programs\KohyaTrainer\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Programs\KohyaTrainer\kohya_ss\sd-scripts\library\sdxl_original_unet.py", line 673, in forward
    output = self.forward_body(hidden_states, context, timestep)
  File "D:\Programs\KohyaTrainer\kohya_ss\sd-scripts\library\sdxl_original_unet.py", line 648, in forward_body
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "D:\Programs\KohyaTrainer\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Programs\KohyaTrainer\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Programs\KohyaTrainer\kohya_ss\sd-scripts\library\sdxl_original_unet.py", line 443, in forward
    return self.forward_memory_efficient_xformers(hidden_states, context, mask)
  File "D:\Programs\KohyaTrainer\kohya_ss\sd-scripts\library\sdxl_original_unet.py", line 494, in forward_memory_efficient_xformers
    q_in = self.to_q(x)
  File "D:\Programs\KohyaTrainer\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Programs\KohyaTrainer\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Programs\KohyaTrainer\kohya_ss\sd-scripts\networks\lora.py", line 121, in forward
    return org_forwarded + lx * self.multiplier * scale
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacty of 8.00 GiB of which 0 bytes is free. Of the allocated memory 14.47 GiB is allocated by PyTorch, and 181.14 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
steps:   0%|                                                                  | 0/10000 [00:16<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\kykyr\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\kykyr\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Programs\KohyaTrainer\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Programs\KohyaTrainer\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\Programs\KohyaTrainer\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "D:\Programs\KohyaTrainer\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\Programs\\KohyaTrainer\\kohya_ss\\venv\\Scripts\\python.exe', 'D:/Programs/KohyaTrainer/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', 'D:\\Donwloads\\lora\\model/config_lora-20241208-175620.toml']' returned non-zero exit status 1.
18:00:11-354875 INFO     Training has ended.

**Comment by Sylsatra** [comment]
CUDA is out of memory, can you provide the training configuration?
