### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by RalkeyOfficial** [bmaltais/kohya_ss#3007]
I am getting this error when pressing start training

```
Traceback (most recent call last):
  File "C:\kohya_ss\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\kohya_ss\venv\lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "C:\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "C:\kohya_ss\venv\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "C:\kohya_ss\kohya_gui\lora_gui.py", line 1138, in train_model
    int(lr_scheduler_num_cycles)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

I don't have any other information to give, sadly enough.
I can give my training settings .json file if requested.

**Comment by RalkeyOfficial** [comment]
Nevermind,
I found out my issue.

I removed the LR # cycles and LR power option..
