### ISSUE TITLE
Lora Training ending with monitor refresh?

### ISSUE THREAD

**Issue by Squeedwad** [bmaltais/kohya_ss#3009]
I've noticed when I'm running a Lora training, if I turn all of my monitors off and then on, or sometimes when I wake my monitors up, I receive the following error:

Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\Pictures\Stable_Diffusion\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\username\Pictures\Stable_Diffusion\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\username\Pictures\Stable_Diffusion\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\Users\username\Pictures\Stable_Diffusion\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\username\\Pictures\\Stable_Diffusion\\kohya_ss\\venv\\Scripts\\python.exe', 'C:/Users/username/Pictures/Stable_Diffusion/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', 'C:\\Users\\username\\Pictures\\Stable_Diffusion\\12_8_24\\ogadenmon\\model/config_lora-20241210-081916.toml']' returned non-zero exit status 1.

It's every time I turn my monitors on after they are off, and only sometimes when I wake my monitors up from being asleep. If I wake the monitors up from being asleep, IF they appear to "refresh" and the training stops and shows the error. If the monitors don't "refresh", then the training continues as normal. It also stops me from resuming from the previous training state, which means I have to restart the training process all over again. Hoping someone has an answer to this problem.

**Comment by 5KilosOfCheese** [comment]
Sounds like an issue of your graphics driver crashing and windows resetting it. If you press: Windows key and Ctrl + Shift + B; and this seems like a similar flicker, then it is an issue of graphics driver crashing and reseting - and you should try updating or re-installing the graphics driver.

**Comment by Squeedwad** [comment]
It looks like that resolved the issue, thanks!
