### ISSUE TITLE
Someone could help me? returned non-zero exit status 1. 

### ISSUE THREAD

**Issue by Explyy** [bmaltais/kohya_ss#3013]
Traceback (most recent call last):
  File "C:\Users\DAVIDE\AI\Kohya_ss\kohya_ss\sd-scripts\flux_train_network.py", line 583, in <module>
    trainer.train(args)
  File "C:\Users\DAVIDE\AI\Kohya_ss\kohya_ss\sd-scripts\train_network.py", line 442, in train
    vae.to(accelerator.device, dtype=vae_dtype)
  File "C:\Users\DAVIDE\AI\Kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1340, in to
    return self._apply(convert)
  File "C:\Users\DAVIDE\AI\Kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "C:\Users\DAVIDE\AI\Kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "C:\Users\DAVIDE\AI\Kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "C:\Users\DAVIDE\AI\Kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 927, in _apply
    param_applied = fn(param)
  File "C:\Users\DAVIDE\AI\Kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1333, in convert
    raise NotImplementedError(
NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.
Traceback (most recent call last):
  File "C:\Users\DAVIDE\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\DAVIDE\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\DAVIDE\AI\Kohya_ss\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\DAVIDE\AI\Kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "C:\Users\DAVIDE\AI\Kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "C:\Users\DAVIDE\AI\Kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\DAVIDE\\AI\\Kohya_ss\\kohya_ss\\venv\\Scripts\\python.exe', 'C:/Users/DAVIDE/AI/Kohya_ss/kohya_ss/sd-scripts/flux_train_network.py', '--config_file', 'C:/Users/DAVIDE/AI/Kohya_ss/Lora/Train_Data\\model/config_lora-20241212-125307.toml']' returned non-zero exit status 1.

**Comment by Explyy** [comment]
Thank you a lot! it seems that i can`t describe the image with any text, if i start the training without LLM image description it does work..

**Comment by Sylsatra** [comment]
> Thank you a lot! it seems that i can`t describe the image with any text, if i start the training without LLM image description it does work..

That is weird, can you provide the config and the full error if possible?
