### ISSUE TITLE
C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'E:\\SD\\kohya_ss-24.1.7\\sd-scripts\\train_network.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mmzc666** [bmaltais/kohya_ss#3018]
## HOW CAN I DEAL WITH IT? ##

16:45:57-546267 INFO     Start training LoRA LyCORIS/iA3 ...
16:45:57-547266 INFO     Validating lr scheduler arguments...
16:45:57-548266 INFO     Validating optimizer arguments...
16:45:57-549268 INFO     Validating D:\Desktop\PhotoData_Training\JayChou\Logs existence and writability... SUCCESS
16:45:57-550267 INFO     Validating D:\Desktop\PhotoData_Training\JayChou\Models existence and writability... SUCCESS
16:45:57-551267 INFO     Validating runwayml/stable-diffusion-v1-5 existence... SKIPPING: huggingface.co model
16:45:57-552772 INFO     Validating D:\Desktop\PhotoData_Training\JayChou\Images existence... SUCCESS
16:45:57-553279 INFO     Headless mode, skipping verification if model already exist... if model already exist it will
                         be overwritten...
16:45:57-554285 INFO     Folder 15_JayChou: 15 repeats found
16:45:57-555290 INFO     Folder 15_JayChou: 43 images found
16:45:57-556291 INFO     Folder 15_JayChou: 43 * 15 = 645 steps
16:45:57-557290 INFO     Regulatization factor: 1
16:45:57-557290 INFO     Total steps: 645
16:45:57-558291 INFO     Train batch size: 1
16:45:57-559291 INFO     Gradient accumulation steps: 1
16:45:57-560291 INFO     Epoch: 300
16:45:57-560291 INFO     Max train steps: 2000
16:45:57-561291 INFO     stop_text_encoder_training = 0
16:45:57-562291 INFO     lr_warmup_steps = 0
16:45:57-566312 INFO     Saving training config to
                         D:\Desktop\PhotoData_Training\JayChou\Models\JayChou_20241222-164557.json...
16:45:57-568862 INFO     Executing command: E:\SD\kohya_ss-24.1.7\venv\Scripts\accelerate.EXE launch --dynamo_backend no
                         --dynamo_mode default --mixed_precision fp16 --num_processes 1 --num_machines 1
                         --num_cpu_threads_per_process 2 E:/SD/kohya_ss-24.1.7/sd-scripts/train_network.py --config_file
                         D:\Desktop\PhotoData_Training\JayChou\Models/config_lora-20241222-164557.toml
16:45:57-573886 INFO     Command executed.
`C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'E:\\SD\\kohya_ss-24.1.7\\sd-scripts\\train_network.py': [Errno 2] No such file or directory`
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\SD\kohya_ss-24.1.7\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
    sys.exit(main())
  File "E:\SD\kohya_ss-24.1.7\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "E:\SD\kohya_ss-24.1.7\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "E:\SD\kohya_ss-24.1.7\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\SD\\kohya_ss-24.1.7\\venv\\Scripts\\python.exe', 'E:/SD/kohya_ss-24.1.7/sd-scripts/train_network.py', '--config_file', 'D:\\Desktop\\PhotoData_Training\\JayChou\\Models/config_lora-20241222-164557.toml']' returned non-zero exit status 2.
16:46:02-940889 INFO     Training has ended.

**Comment by ZfE0QQ6ds92W** [comment]
Hi, this might be related to differences how windows/linux systems handel "/" and "\" within a path.
If you are using windows, try to use everywhere the "/" separator for paths (especially within the "Additional parameters" box).
