### ISSUE TITLE
Before I could train images 768x768 now I can't

### ISSUE THREAD

**Issue by euri412** [bmaltais/kohya_ss#302]
For a month I have been able to train 768x768 images, I have a 3060, the point is that this morning when I tried to train a model, it did not let me. I got all this error that you will see below. Yes I can train at 512x512 but I can't at 768x768. Any solution?

Traceback (most recent call last):
  File "C:\Users\EstudioEpika\Desktop\1EntrenamientoNuevo\kohya_ss\train_network.py", line 507, in <module>
    train(args)
  File "C:\Users\EstudioEpika\Desktop\1EntrenamientoNuevo\kohya_ss\train_network.py", line 373, in train
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "C:\Users\EstudioEpika\Desktop\1EntrenamientoNuevo\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\EstudioEpika\Desktop\1EntrenamientoNuevo\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 490, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "C:\Users\EstudioEpika\Desktop\1EntrenamientoNuevo\kohya_ss\venv\lib\site-packages\torch\amp\autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "C:\Users\EstudioEpika\Desktop\1EntrenamientoNuevo\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 381, in forward
    sample, res_samples = downsample_block(
  File "C:\Users\EstudioEpika\Desktop\1EntrenamientoNuevo\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\EstudioEpika\Desktop\1EntrenamientoNuevo\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 612, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
  File "C:\Users\EstudioEpika\Desktop\1EntrenamientoNuevo\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\EstudioEpika\Desktop\1EntrenamientoNuevo\kohya_ss\venv\lib\site-packages\diffusers\models\attention.py", line 216, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "C:\Users\EstudioEpika\Desktop\1EntrenamientoNuevo\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\EstudioEpika\Desktop\1EntrenamientoNuevo\kohya_ss\venv\lib\site-packages\diffusers\models\attention.py", line 484, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "C:\Users\EstudioEpika\Desktop\1EntrenamientoNuevo\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\EstudioEpika\Desktop\1EntrenamientoNuevo\kohya_ss\venv\lib\site-packages\diffusers\models\attention.py", line 589, in forward
    hidden_states = self._attention(query, key, value)
  File "C:\Users\EstudioEpika\Desktop\1EntrenamientoNuevo\kohya_ss\venv\lib\site-packages\diffusers\models\attention.py", line 604, in _attention
    attention_scores = torch.baddbmm(
RuntimeError: CUDA out of memory. Tried to allocate 5.06 GiB (GPU 0; 12.00 GiB total capacity; 8.24 GiB already allocated; 960.70 MiB free; 8.99 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
steps:   0%|                                                                                                                                                     | 0/1260 [00:50<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\EstudioEpika\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\EstudioEpika\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\EstudioEpika\Desktop\1EntrenamientoNuevo\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\EstudioEpika\Desktop\1EntrenamientoNuevo\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)

**Comment by bmaltais** [comment]
I think the latest trainer code is possible causing some issue... Also... were you using 8bitadam before? Make sure to select AdamW8bit as the Optimizer to get the same effect.

**Comment by TABABI** [comment]
@bmaltais Hi Bmaltais, I was training Lora with GUI today. I could't run with AdamW8bit optimizer as the GUI force me to tick the "use 8bit Adam". I could not uncheck the "use 8bit adam". I can only train lora with the adamW8bit optimizer in sd-scripts. I think this is a problem

**Comment by Koronos** [comment]
@TABABI Disable it manually in the json and then  re-load it:

![image](https://user-images.githubusercontent.com/7765638/222943974-fbff8008-0c94-4254-9151-ce32d0ce5fa3.png)

**Comment by JackShimada** [comment]
> @TABABI Disable it manually in the json and then re-load it:
> 
> ![image](https://user-images.githubusercontent.com/7765638/222943974-fbff8008-0c94-4254-9151-ce32d0ce5fa3.png)

Sorry, where can I find this json?

**Comment by bmaltais** [comment]
So you can't train with Adam,8bit and need it disable? Select AdamW nstead.

**Comment by TABABI** [comment]
So [AdamW with unticked adam 8bit checkbox] is equivalent to [adamw8bit with adam 8bit checkbox tiecked] right? adamw just use a bit more ram?

**Comment by bmaltais** [comment]
AdamW8bit with untickwd checkbox is. I will remove the 8bit checkbox in a next release to remove confusion.

**Comment by bmaltais** [comment]
I have published a new release where I removed trhe legacy use 8bit adam checkbox. This should lift confusion. The GUI will use the older config file config to properly set the optimizer based on the old 8 bit adam checkbox.

**Comment by euri412** [comment]
the problem continues. In the forums they are talking about uninstalling python and installing it again or leaving python 13 and going for 17.

![image](https://user-images.githubusercontent.com/120108555/222970116-5a3dddbf-8470-4a59-9b47-c1f5871a6f88.png)
![image](https://user-images.githubusercontent.com/120108555/222970154-132fb05f-4efb-4542-a065-0d61fe12580f.png)

Here I leave the configuration that I am using. In my despair I uninstalled the previous Kohya and installed the new one that now comes with LOCON and other things, I just did the AdamW thing and even changed to False in the json. If you let me work with 512,512 but not with 768,768

![image](https://user-images.githubusercontent.com/120108555/222970257-2ab541c9-966a-4652-8a85-08ac8b54b779.png)
![image](https://user-images.githubusercontent.com/120108555/222970266-6c336766-2af7-4b86-8708-088bbbbbbe6a.png)

I also paste my used Json.

{
  "pretrained_model_name_or_path": "C:/Users/EstudioEpika/Desktop/1EntrenamientoNuevo/kohya_ss/Modelos de Entrenamiento/AOM3A3.safetensors",
  "v2": false,
  "v_parameterization": false,
  "logging_dir": "C:/Users/EstudioEpika/Desktop/1EntrenamientoNuevo/Cammy/log",
  "train_data_dir": "C:/Users/EstudioEpika/Desktop/1 Entrenamientos/Cammy/img",
  "reg_data_dir": "",
  "output_dir": "C:/Users/EstudioEpika/Desktop/1EntrenamientoNuevo/Cammy/model",
  "max_resolution": "768,768",
  "learning_rate": "2e-6",
  "lr_scheduler": "constant",
  "lr_warmup": "0",
  "train_batch_size": 4,
  "epoch": "6",
  "save_every_n_epochs": "1",
  "mixed_precision": "fp16",
  "save_precision": "fp16",
  "seed": "1234",
  "num_cpu_threads_per_process": 2,
  "cache_latents": false,
  "caption_extension": "",
  "enable_bucket": true,
  "gradient_checkpointing": false,
  "full_fp16": false,
  "no_token_padding": false,
  "stop_text_encoder_training": 0,
  "use_8bit_adam": false,
  "xformers": true,
  "save_model_as": "safetensors",
  "shuffle_caption": true,
  "save_state": false,
  "resume": "",
  "prior_loss_weight": 1.0,
  "text_encoder_lr": "5e-5",
  "unet_lr": "2e-6",
  "network_dim": 128,
  "lora_network_weights": "",
  "color_aug": false,
  "flip_aug": false,
  "clip_skip": 2,
  "gradient_accumulation_steps": 1.0,
  "mem_eff_attn": false,
  "output_name": "CammyV1",
  "model_list": "custom",
  "max_token_length": "150",
  "max_train_epochs": "",
  "max_data_loader_n_workers": "",
  "network_alpha": 128,
  "training_comment": "",
  "keep_tokens": 1,
  "lr_scheduler_num_cycles": "",
  "lr_scheduler_power": "",
  "persistent_data_loader_workers": false,
  "bucket_no_upscale": true,
  "random_crop": false,
  "bucket_reso_steps": 64.0,
  "caption_dropout_every_n_epochs": 0.0,
  "caption_dropout_rate": 0,
  "optimizer": "AdamW",
  "optimizer_args": "",
  "noise_offset": "",
  "LoRA_type": "Standard",
  "conv_dim": 1,
  "conv_alpha": 1
}

**Comment by bmaltais** [comment]
I think it really is the trainer code change that introduced the new optimiser that is causing the issue. I suggest to switch to the release before the that release to get back to a code base that you can use. Simply find the release name and run 

git checkout release_name

**Comment by euri412** [comment]
I reinstalled python and now I get a different error that has nothing to do with CUDA memory. This really is frustrating.
![image](https://user-images.githubusercontent.com/120108555/222974886-4c64f383-96e4-411f-8c0b-ba9d9442c781.png)
