### ISSUE TITLE
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by Ylelmon** [bmaltais/kohya_ss#3020]
any one know how to fix this 

'''Traceback (most recent call last):
  File "C:\Users\dell\Desktop\pp\kohya_ss\sd-scripts\train_network.py", line 1242, in <module>
    trainer.train(args)
  File "C:\Users\dell\Desktop\pp\kohya_ss\sd-scripts\train_network.py", line 272, in train
    train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
  File "C:\Users\dell\Desktop\pp\kohya_ss\sd-scripts\library\train_util.py", line 2324, in cache_latents
    dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process, file_suffix)
  File "C:\Users\dell\Desktop\pp\kohya_ss\sd-scripts\library\train_util.py", line 1146, in cache_latents
    cache_batch_latents(vae, cache_to_disk, batch, subset.flip_aug, subset.alpha_mask, subset.random_crop)
  File "C:\Users\dell\Desktop\pp\kohya_ss\sd-scripts\library\train_util.py", line 2760, in cache_batch_latents
    latents = vae.encode(img_tensors).latent_dist.sample().to("cpu")
  File "C:\Users\dell\Desktop\pp\kohya_ss\venv\lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\dell\Desktop\pp\kohya_ss\venv\lib\site-packages\diffusers\models\autoencoders\autoencoder_kl.py", line 260, in encode
    h = self.encoder(x)
  File "C:\Users\dell\Desktop\pp\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\dell\Desktop\pp\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\dell\Desktop\pp\kohya_ss\venv\lib\site-packages\diffusers\models\autoencoders\vae.py", line 143, in forward
    sample = self.conv_in(sample)
  File "C:\Users\dell\Desktop\pp\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\dell\Desktop\pp\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\dell\Desktop\pp\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\dell\Desktop\pp\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\dell\Desktop\pp\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\dell\Desktop\pp\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\dell\Desktop\pp\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\Users\dell\Desktop\pp\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\dell\\Desktop\\pp\\kohya_ss\\venv\\Scripts\\python.exe', 'C:/Users/dell/Desktop/pp/kohya_ss/sd-scripts/train_network.py', '--config_file', 'C:/Users/dell/Pictures/Haru/model/config_lora-20241224-205633.toml']' returned non-zero exit status 1."""

the first thing i tried is change the configure Accelerate :
![image](https://github.com/user-attachments/assets/401f7ef1-9787-4b2d-9f57-99dd39ad0b44)

second this :
![image](https://github.com/user-attachments/assets/64d61f67-b27f-4295-9aad-cec3715127cc)

3- the same thing i did in the first image but i put 0,1 

4- i uninstall torch then ai use this pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

All those solutions were a solution for this problem, but they didn't work.

**Comment by Sylsatra** [comment]
Hey, can you provide your kohya_ss branch and your GPU? I think you might have the wrong Cuda version.
If you want to train using your CPU, the mixed precision should be none ([Original Answer](https://github.com/kohya-ss/sd-scripts/issues/481#issuecomment-1565960191)).
