### ISSUE TITLE
KeyError: 'time_embed.0.weight

### ISSUE THREAD

**Issue by G-force78** [bmaltais/kohya_ss#306]
When using the inference cell in collab https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-finetuner.ipynb

Where are the weights saved before being converted to safetensors?

```

Traceback (most recent call last):
  File "gen_img_diffusers.py", line 2728, in <module>
    main(args)
  File "gen_img_diffusers.py", line 1894, in main
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, args.ckpt)
  File "/content/kohya-trainer/library/model_util.py", line 877, in load_models_from_stable_diffusion_checkpoint
    converted_unet_checkpoint = convert_ldm_unet_checkpoint(v2, state_dict, unet_config)
  File "/content/kohya-trainer/library/model_util.py", line 234, in convert_ldm_unet_checkpoint
    new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
KeyError: 'time_embed.0.weight'
```

**Comment by codeklenn** [comment]
having the same error too, only problem is i am having the error in train_network.py:

File "E:\AI\Kohya\kohya_ss\train_network.py", line 507, in <module>
    train(args)
  File "E:\AI\Kohya\kohya_ss\train_network.py", line 96, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype)
  File "E:\AI\Kohya\kohya_ss\library\train_util.py", line 2696, in load_target_model
    ) = model_util.load_models_from_stable_diffusion_checkpoint(
  File "E:\AI\Kohya\kohya_ss\library\model_util.py", line 1169, in load_models_from_stable_diffusion_checkpoint
    converted_unet_checkpoint = convert_ldm_unet_checkpoint(
  File "E:\AI\Kohya\kohya_ss\library\model_util.py", line 261, in convert_ldm_unet_checkpoint
    new_checkpoint['time_embedding.linear_1.weight'] = unet_state_dict[
KeyError: 'time_embed.0.weight'
