### ISSUE TITLE
utilities of merge lora have some issues

### ISSUE THREAD

**Issue by Meennow** [bmaltais/kohya_ss#316]
./venv/Scripts/python.exe "networks\merge_lora.py" --save_precision float --precision float --save_to "F:/3.safetensors" --models "F:/1.safetensors" "F:/2.safetensors" --ratios 0.75 0.25
Traceback (most recent call last):
  File "G:\anaconda3\envs\base310\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\anaconda3\envs\base310\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "G:\anaconda3\envs\base310\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\anaconda3\envs\base310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\anaconda3\envs\base310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "G:\anaconda3\envs\base310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\python\ai painting\sd-webui启动器【一键启动器】\train\script\kohya_ss\library\merge_lora_gui.py", line 60, in merge_lora
    subprocess.run(run_cmd)
  File "G:\anaconda3\envs\base310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "G:\anaconda3\envs\base310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "G:\anaconda3\envs\base310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2]

**Comment by bmaltais** [comment]
Are you trying to merge a LoCon with a LoRA maybe? LoCon can't be merged at the moment.

**Comment by Meennow** [comment]
I trained the two LORA models in the same way under your program, but I can't merge them

**Comment by bmaltais** [comment]
I only provide the front-end to kohya come. You should open on issue on his repo to directly report the merge issue.

**Comment by bmaltais** [comment]
Just to be sure... You created two Standard LoRa... Not two LoCon... Right? LoCon can't be merged.

**Comment by Meennow** [comment]
yes,i just created two Standard LoRa

**Comment by Meennow** [comment]
Haha, I'm not familiar with github. I thought kohya training programs were created by you, but thank you very much for your help
