### ISSUE TITLE
error when i start train model

### ISSUE THREAD

**Issue by protoxx91** [bmaltais/kohya_ss#332]
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "C:\Windows\System32\kohya_ss\train_network.py", line 1, in <module>
    from torch.cuda.amp import autocast
  File "C:\WINDOWS\system32\kohya_ss\venv\lib\site-packages\torch\__init__.py", line 129, in <module>
    raise err
OSError: [WinError 1455] Le fichier de pagination est insuffisant pour terminer cette opération. Error loading "C:\WINDOWS\system32\kohya_ss\venv\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
Traceback (most recent call last):
  File "C:\Users\vizzi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\vizzi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Windows\System32\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\WINDOWS\system32\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\WINDOWS\system32\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\WINDOWS\system32\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\WINDOWS\\system32\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=F:/LORA/finished LoRA/img', '--resolution=512,512', '--output_dir=F:/LORA/finished LoRA/model', '--logging_dir=F:/LORA/finished LoRA/log', '--network_alpha=112', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=pretty', '--lr_scheduler_num_cycles=30', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=84840', '--train_batch_size=1', '--max_train_steps=848400', '--save_every_n_epochs=10', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by GeoTronZ** [comment]
did u find fix?

**Comment by bmaltais** [comment]
I noticed this error. I think your wondows pagefile is too small. Try increasing the page file system size:

```
The error message "OSError: [WinError 1455] Le fichier de pagination est insuffisant pour terminer cette opération. Error loading 'C:\WINDOWS\system32\kohya_ss\venv\lib\site-packages\torch\lib\shm.dll' or one of its dependencies."
```
