### ISSUE TITLE
LORA Training Suddenly Broken?

### ISSUE THREAD

**Issue by AlexRC1** [bmaltais/kohya_ss#336]
I had this running fine the other day. Now, for some reason, whenever I try to re-create my old work, I get the following:

Traceback (most recent call last):
  File "C:\SD\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\SD\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1024, in process_api
    result = await self.call_function(
  File "C:\SD\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 836, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\SD\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\SD\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\SD\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\SD\Kohya_ss\lora_gui.py", line 385, in train_model
    repeats = int(folder.split('_')[0])
ValueError: invalid literal for int() with base 10: 'output'

I have no idea what changed (although I've installed and messed around with other software in the interim). I've tried a variety of things to fix this, but... no luck.

**Comment by laserprec** [comment]
The program is trying to convert folder names to an integer. You might have a folder called `output` in your image directory. It's complaining about not being able to convert "output" to an integer. Try removing that folder?

**Comment by AlexRC1** [comment]
Yeah, it seems the repo created one of those at some point (as I hardly did it myself). Deleting the folder seems to have fixed the issue.

I'll write more in a half hour or so, when my initial test training is done.

**Comment by AlexRC1** [comment]
Seems to have worked. Alright. That was... generally bizarre.
