### ISSUE TITLE
Errors when trying to create a Lora

### ISSUE THREAD

**Issue by MuscleEnjoyer** [bmaltais/kohya_ss#338]
Hello! I'm not entirely sure what this means, but I'm unable to create a lora through the gui. Can someone help me decipher this and help me make this work? Thank you!

"Traceback (most recent call last):
  File "C:\Users\aalop\kohya_ss\kohya_ss\train_db.py", line 355, in <module>
    train(args)
  File "C:\Users\aalop\kohya_ss\kohya_ss\train_db.py", line 94, in train
    train_dataset.cache_latents(vae)
  File "C:\Users\aalop\kohya_ss\kohya_ss\library\train_util.py", line 508, in cache_latents
    info.latents = vae.encode(img_tensor).latent_dist.sample().squeeze(0).to("cpu")
  File "C:\Users\aalop\kohya_ss\kohya_ss\venv\lib\site-packages\diffusers\models\vae.py", line 566, in encode
    h = self.encoder(x)
  File "C:\Users\aalop\kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\aalop\kohya_ss\kohya_ss\venv\lib\site-packages\diffusers\models\vae.py", line 130, in forward
    sample = self.conv_in(sample)
  File "C:\Users\aalop\kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\aalop\kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\aalop\kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
  File "C:\Users\aalop\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\aalop\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\aalop\kohya_ss\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\aalop\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main    args.func(args)
  File "C:\Users\aalop\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\aalop\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\aalop\\kohya_ss\\kohya_ss\\venv\\Scripts\\python.exe', 'train_db.py', '--enable_bucket', '--pretrained_model_name_or_path=D:/stable-diffusion/stable-diffusion-webui/models/Stable-diffusion/nai.ckpt', '--train_data_dir=D:/project folder/img', '--resolution=512,512', '--output_dir=D:/project folder/model', '--logging_dir=D:/project folder/log', '--save_model_as=safetensors', '--output_name=vane', '--learning_rate=1e-5', '--lr_scheduler=cosine', '--lr_warmup_steps=568', '--train_batch_size=1', '--max_train_steps=5680', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--cache_latents', '--bucket_reso_steps=64', '--mem_eff_attn', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1."

**Comment by AI-Casanova** [comment]
> RuntimeError: CUDA error: out of memory

Lower your batch size or use gradient checkpointing. You're overloading your VRAM

**Comment by MuscleEnjoyer** [comment]
Thanks! That removed that error, but now I'm receiving another error. I have a decent graphics card (RTX 3060), and it has about 12gb of vram. 

Use DreamBooth method.
prepare train images.
found directory 40_vane character model contains 142 image files
5680 train images with repeating.
loading image sizes.
100%|██████████████████████████████████████████████████████████████████████████████| 142/142 [00:00<00:00, 6763.78it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (320, 448), count: 40
bucket 1: resolution (320, 512), count: 40
bucket 2: resolution (320, 576), count: 160
bucket 3: resolution (384, 512), count: 1280
bucket 4: resolution (384, 576), count: 1080
bucket 5: resolution (384, 640), count: 280
bucket 6: resolution (448, 448), count: 360
bucket 7: resolution (448, 512), count: 720
bucket 8: resolution (448, 576), count: 160
bucket 9: resolution (512, 384), count: 240
bucket 10: resolution (512, 448), count: 640
bucket 11: resolution (512, 512), count: 560
bucket 12: resolution (576, 384), count: 40
bucket 13: resolution (576, 448), count: 40
bucket 14: resolution (640, 384), count: 40
mean ar error (without repeats): 0.031905673830221484
prepare accelerator
Using accelerator 0.15.0 or above.
load StableDiffusion checkpoint
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
Traceback (most recent call last):
  File "C:\Users\aalop\kohya_ss\train_network.py", line 507, in <module>
    train(args)
  File "C:\Users\aalop\kohya_ss\train_network.py", line 96, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype)
  File "C:\Users\aalop\kohya_ss\library\train_util.py", line 2696, in load_target_model
    ) = model_util.load_models_from_stable_diffusion_checkpoint(
  File "C:\Users\aalop\kohya_ss\library\model_util.py", line 1219, in load_models_from_stable_diffusion_checkpoint
    text_model = CLIPTextModel.from_pretrained(
  File "C:\Users\aalop\kohya_ss\venv\lib\site-packages\transformers\modeling_utils.py", line 2362, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "C:\Users\aalop\kohya_ss\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 776, in __init__    self.text_model = CLIPTextTransformer(config)
  File "C:\Users\aalop\kohya_ss\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 682, in __init__    self.encoder = CLIPEncoder(config)
  File "C:\Users\aalop\kohya_ss\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 585, in __init__    self.layers = nn.ModuleList([CLIPEncoderLayer(config) for _ in range(config.num_hidden_layers)])
  File "C:\Users\aalop\kohya_ss\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 585, in <listcomp>
    self.layers = nn.ModuleList([CLIPEncoderLayer(config) for _ in range(config.num_hidden_layers)])
  File "C:\Users\aalop\kohya_ss\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 358, in __init__    self.self_attn = CLIPAttention(config)
  File "C:\Users\aalop\kohya_ss\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 253, in __init__    self.v_proj = nn.Linear(self.embed_dim, self.embed_dim)
  File "C:\Users\aalop\kohya_ss\venv\lib\site-packages\torch\nn\modules\linear.py", line 96, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 2359296 bytes.
Traceback (most recent call last):
  File "C:\Users\aalop\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\aalop\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\aalop\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\aalop\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\aalop\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\aalop\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\aalop\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=D:/stable-diffusion/stable-diffusion-webui/models/Stable-diffusion/nai.ckpt', '--train_data_dir=D:/project folder/img', '--resolution=512,512', '--output_dir=D:/project folder/model', '--logging_dir=D:/project folder/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=vane', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=568', '--train_batch_size=1', '--max_train_steps=5680', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by ruSauron** [comment]
Now you need more ram. Increase size of paging file, close all programs including Chrome, lower training options again, add more ram

**Comment by MuscleEnjoyer** [comment]
Hi, everyone! After changing my paging file to "System Manager", it seems to have fixed this issue. Thank you!

**Comment by UmarCGA** [comment]
MuscleEnjoyer what do you mean by "changing my paging file to "System Manager"?
