### ISSUE TITLE
Error when trying to save checkpoint

### ISSUE THREAD

**Issue by Disorbs** [bmaltais/kohya_ss#344]
I tried saving as .ckpt and safetensor both give same error.

this is with koyha trainer for colab.

steps:   5% 140/2800 [04:15<1:20:50,  1.82s/it, loss=0.139]saving checkpoint: /content/training_dir/output/Test-NT1-000001.ckpt

```
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/kohya-trainer/fine_tune.py', '--output_name=Test-NT1', '--pretrained_model_name_or_path=/content/pretrained_model/v1-5-pruned-emaonly.ckpt', '--vae=/content/vae/stablediffusion.vae.pt', '--train_data_dir=/content/training_dir/train_data', '--in_json=/content/training_dir/meta_lat.json', '--output_dir=/content/training_dir/output', '--optimizer_type=AdamW8bit', '--learning_rate=2e-06', '--lr_scheduler=constant', '--lr_warmup_steps=250', '--dataset_repeats=10', '--resolution=768', '--lowram', '--mixed_precision=fp16', '--save_precision=fp16', '--save_every_n_epochs=1', '--save_model_as=ckpt', '--train_batch_size=2', '--max_token_length=225', '--max_train_epochs=20', '--clip_skip=2', '--logging_dir=/content/training_dir/logs', '--log_prefix=Test-NT1', '--shuffle_caption', '--xformers']' died with <Signals.SIGKILL: 9>.
```

**Comment by bmaltais** [comment]
You should report this issue in kohya_ss sd-scriot repo. The saving of ckpt is something his code does and I can't fix that.
