### ISSUE TITLE
UnboundLocalError: local variable 'pipe' referenced before assignment

### ISSUE THREAD

**Issue by larssn** [bmaltais/kohya_ss#345]
Keep getting the following exception. This is  using Python 3.10.10.
I've tried all the troubleshooting options mentioned - reinstalling python etc.
It hasn't helped, sadly.

```
Traceback (most recent call last):
  File "F:\Software\kohya_ss\train_network.py", line 652, in <module>
    train(args)
  File "F:\Software\kohya_ss\train_network.py", line 114, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype)
  File "F:\Software\kohya_ss\library\train_util.py", line 2024, in load_target_model
    text_encoder = pipe.text_encoder
UnboundLocalError: local variable 'pipe' referenced before assignment

Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\Software\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "F:\Software\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "F:\Software\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "F:\Software\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
```

**Comment by bmaltais** [comment]
This is an issue that kohya need to address as it is not directly related to the GUI. I suggest you submit an issue in his sd-script repo.

Did it ever worked for you?

**Comment by larssn** [comment]
No it has never worked. Thought it was memory related initially, so I was hesitant in opening an issue about it. But my 6GB VRAM card can run with batchsize 4 using DreamBooth lora, using all the memory saving tricks in the book.

So maybe it's something else. I'll open an issue over there, thanks!
