### ISSUE TITLE
KeyError: 'encoder.conv_in.weight'

### ISSUE THREAD

**Issue by axsddlr** [bmaltais/kohya_ss#346]
```
Traceback (most recent call last):
  File "D:\Programs\gitrepos\PROJS\AI\kohya_ss\train_network.py", line 652, in <module>
    train(args)
  File "D:\Programs\gitrepos\PROJS\AI\kohya_ss\train_network.py", line 114, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype)
  File "D:\Programs\gitrepos\PROJS\AI\kohya_ss\library\train_util.py", line 2016, in load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, name_or_path)
  File "D:\Programs\gitrepos\PROJS\AI\kohya_ss\library\model_util.py", line 885, in load_models_from_stable_diffusion_checkpoint
    converted_vae_checkpoint = convert_ldm_vae_checkpoint(state_dict, vae_config)
  File "D:\Programs\gitrepos\PROJS\AI\kohya_ss\library\model_util.py", line 398, in convert_ldm_vae_checkpoint
    new_checkpoint["encoder.conv_in.weight"] = vae_state_dict["encoder.conv_in.weight"]
KeyError: 'encoder.conv_in.weight'
```

**Comment by pbz134** [comment]
Hey, I’m running into the same error on a GTX 1080 8GB. How did you solve this problem?

**Comment by axsddlr** [comment]
it was a corrupt checkpoint file
