### ISSUE TITLE
Error when trying to use custom model 

### ISSUE THREAD

**Issue by vizsumit** [bmaltais/kohya_ss#349]
Training with default directory models is going fine but when I use any other model from custom directory it throws this error =

Traceback (most recent call last):
  File "D:\Others\StableDiffusion\kohya_ss\train_network.py", line 20, in <module>
    import library.config_util as config_util
  File "D:\Others\StableDiffusion\kohya_ss\library\config_util.py", line 19, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
Traceback (most recent call last):
  File "C:\Users\Aster\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Aster\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Others\StableDiffusion\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\Others\StableDiffusion\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\Others\StableDiffusion\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\Others\StableDiffusion\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\Others\\StableDiffusion\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=D:/Others/StableDiffusion/models/mo-di-v1-pruned.ckpt', '--train_data_dir=D:/Others/StableDiffusion/training_data/test/images', '--resolution=512,512', '--output_dir=D:/Others/StableDiffusion/training_data/test/model', '--logging_dir=D:/Others/StableDiffusion/training_data/stest/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=test', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=3350', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by Hunter-857** [comment]
No module named 'toml'， just try to install this module by `pip install toml`  in your shell

**Comment by bmaltais** [comment]
Oh... did I forgot to add this to the requirements? No, it is there. Just run `upgrade.ps1` to install the missing module.

**Comment by vizsumit** [comment]
Already tried those things, still facing issue.

**Comment by vizsumit** [comment]
So I reinstalled whole thing.
Looks like it is giving error with non .SAFETENSOR files specially with pruned models. .CKPT models are working fine.
I don't know the reason.
