### ISSUE TITLE
Getting Error when Train "Folder: 0 Step"

### ISSUE THREAD

**Issue by MamMakara** [bmaltais/kohya_ss#367]
Can any body please help?
Thanks in advance.

To create a public link, set `share=True` in `launch()`.
Folder 100_Hyji: 0 steps
max_train_steps = 0
stop_text_encoder_training = 0
lr_warmup_steps = 0
accelerate launch --num_cpu_threads_per_process=2 "train_db.py" --enable_bucket --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" --train_data_dir="C:/Users/mamma/Desktop/Hyji_Train/image" --resolution=512,512 --output_dir="C:/Users/mamma/Desktop/Hyji_Train/model" --logging_dir="C:/Users/mamma/Desktop/Hyji_Train/log" --save_model_as=safetensors --output_name="Hyji" --learning_rate="1e-5" --lr_scheduler="cosine" --train_batch_size="1" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --cache_latents --optimizer_type="AdamW8bit" --bucket_reso_steps=64 --xformers --bucket_no_upscale
2023-03-13 13:22:08.672768: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-03-13 13:22:08.673010: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-03-13 13:22:28.417119: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-03-13 13:22:28.417294: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Could not find module 'C:\Users\mamma\Desktop\Kohya\kohya_ss\venv\Lib\site-packages\xformers\_C.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
WARNING:root:WARNING: Could not find module 'C:\Users\mamma\Desktop\Kohya\kohya_ss\venv\Lib\site-packages\xformers\_C.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
Need to compile C++ extensions to get sparse attention suport. Please run python setup.py build develop
prepare tokenizer
prepare images.
found directory C:\Users\mamma\Desktop\Hyji_Train\image\100_Hyji contains 5 image files
500 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "C:\Users\mamma\Desktop\Hyji_Train\image\100_Hyji"
    image_count: 5
    num_repeats: 100
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    is_reg: False
    class_tokens: Hyji
    caption_extension: .caption

[Dataset 0]
loading image sizes.
100%|███████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 297.36it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 512), count: 500
mean ar error (without repeats): 0.0
prepare accelerator
Traceback (most recent call last):
  File "C:\Users\mamma\Desktop\Kohya\kohya_ss\train_db.py", line 364, in <module>
    train(args)
  File "C:\Users\mamma\Desktop\Kohya\kohya_ss\train_db.py", line 75, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "C:\Users\mamma\Desktop\Kohya\kohya_ss\library\train_util.py", line 1984, in prepare_accelerator
    accelerator = Accelerator(gradient_accumulation_steps=args.gradient_accumulation_steps, mixed_precision=args.mixed_precision,
  File "C:\Users\mamma\Desktop\Kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 355, in __init__
    raise ValueError(err.format(mode="fp16", requirement="a GPU"))
ValueError: fp16 mixed precision requires a GPU
Traceback (most recent call last):
  File "C:\Users\mamma\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mamma\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\mamma\Desktop\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\mamma\Desktop\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\mamma\Desktop\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\mamma\Desktop\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\mamma\\Desktop\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_db.py', '--enable_bucket', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=C:/Users/mamma/Desktop/Hyji_Train/image', '--resolution=512,512', '--output_dir=C:/Users/mamma/Desktop/Hyji_Train/model', '--logging_dir=C:/Users/mamma/Desktop/Hyji_Train/log', '--save_model_as=safetensors', '--output_name=Hyji', '--learning_rate=1e-5', '--lr_scheduler=cosine', '--train_batch_size=1', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by yeshenyong** [comment]
me too

**Comment by yeshenyong** [comment]
您好，我是叶燊泳，已收到你的邮件。
