### ISSUE TITLE
Error when starting training ValueError: fp16 mixed precision requires a GPU

### ISSUE THREAD

**Issue by CNMagicturtle** [bmaltais/kohya_ss#378]
prepare accelerator
Traceback (most recent call last):
  File "E:\Kohya_Lora\kohya_ss\train_network.py", line 659, in <module>
    train(args)
  File "E:\Kohya_Lora\kohya_ss\train_network.py", line 108, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "E:\Kohya_Lora\kohya_ss\library\train_util.py", line 1984, in prepare_accelerator
    accelerator = Accelerator(gradient_accumulation_steps=args.gradient_accumulation_steps, mixed_precision=args.mixed_precision,
  File "E:\Kohya_Lora\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 355, in __init__
    raise ValueError(err.format(mode="fp16", requirement="a GPU"))
ValueError: fp16 mixed precision requires a GPU
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Kohya_Lora\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "E:\Kohya_Lora\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "E:\Kohya_Lora\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "E:\Kohya_Lora\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\Kohya_Lora\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=E:/StableDiffusion/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned.ckpt', '--train_data_dir=E:\\traindata\\wangyibo', '--resolution=512,768', '--output_dir=E:\\traindata\\lora-wangyibo', '--logging_dir=', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=wangyibo', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant_with_warmup', '--lr_warmup_steps=110', '--train_batch_size=2', '--max_train_steps=1100', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--cache_latents', '--optimizer_type=Lion', '--max_train_epochs=5', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.05']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
Look like your Nvdia GPU is not detected. What GPU do you use?

**Comment by shawncaple** [comment]
I am also having this issue. My GPU is the AMD FirePro D700 (FireGL V)

**Comment by ljjewell** [comment]
I believe I have the same issue where it doesn't detect my GPU. I have an RTX 3060. Fresh install and chose [all] during accelerator config when it asked me to pick GPU. 

Here's my error:

prepare accelerator
Traceback (most recent call last):
  File "D:\Documents\StableDiffusion3\Kohya_ss\kohya_ss\train_network.py", line 659, in <module>
    train(args)
  File "D:\Documents\StableDiffusion3\Kohya_ss\kohya_ss\train_network.py", line 108, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "D:\Documents\StableDiffusion3\Kohya_ss\kohya_ss\library\train_util.py", line 1984, in prepare_accelerator
    accelerator = Accelerator(gradient_accumulation_steps=args.gradient_accumulation_steps, mixed_precision=args.mixed_precision,
  File "D:\Documents\StableDiffusion3\Kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 355, in __init__
    raise ValueError(err.format(mode="fp16", requirement="a GPU"))
ValueError: fp16 mixed precision requires a GPU
Traceback (most recent call last):
  File "C:\Users\MASK\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\MASK\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Documents\StableDiffusion3\Kohya_ss\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\Documents\StableDiffusion3\Kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\Documents\StableDiffusion3\Kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\Documents\StableDiffusion3\Kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\Documents\\StableDiffusion3\\Kohya_ss\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=D:\\Documents\\StableDiffusion3\\stable-diffusion-webui\\Lora\\gg\\image', '--resolution=512,512', '--output_dir=D:\\Documents\\StableDiffusion3\\stable-diffusion-webui\\Lora\\gg\\model', '--logging_dir=D:\\Documents\\StableDiffusion3\\stable-diffusion-webui\\Lora\\gg\\log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=last', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=350', '--train_batch_size=1', '--max_train_steps=3500', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.
