### ISSUE TITLE
bitsandbytes package generating an OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by healthyfat** [bmaltais/kohya_ss#39]
Replace CrossAttention.forward to use xformers
caching latents.
0it [00:00, ?it/s]
prepare optimizer, data loader etc.

Traceback (most recent call last):
  File "C:\Programs\bmaltais GUI\kohya_ss\train_db.py", line 332, in <module>
    train(args)
  File "C:\Programs\bmaltais GUI\kohya_ss\train_db.py", line 119, in train
    import bitsandbytes as bnb
  File "C:\Programs\Python\Python310\lib\site-packages\bitsandbytes\__init__.py", line 5, in <module>
    from .optim import adam
  File "C:\Programs\Python\Python310\lib\site-packages\bitsandbytes\optim\__init__.py", line 5, in <module>
    from .adam import Adam, Adam8bit, Adam32bit
  File "C:\Programs\Python\Python310\lib\site-packages\bitsandbytes\optim\adam.py", line 11, in <module>
    from bitsandbytes.optim.optimizer import Optimizer2State
  File "C:\Programs\Python\Python310\lib\site-packages\bitsandbytes\optim\optimizer.py", line 6, in <module>
    import bitsandbytes.functional as F
  File "C:\Programs\Python\Python310\lib\site-packages\bitsandbytes\functional.py", line 13, in <module>
    lib = ct.cdll.LoadLibrary(os.path.dirname(__file__) + '/libbitsandbytes.so')
  File "C:\Programs\Python\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 193] %1 is not a valid Win32 application 

Traceback (most recent call last):
  File "C:\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Programs\Python\Python310\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Programs\Python\Python310\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

subprocess.CalledProcessError: Command '['C:\\Programs\\Python\\Python310\\python.exe', 'train_db.py', '--cache_latents', '--enable_bucket', '--use_8bit_adam', '--xformers', '--pretrained_model_name_or_path=C:/Programs/stable-diffusion-webui/models/Stable-diffusion/sd-v1-4.ckpt', '--train_data_dir=C:/Users/pdept/Desktop/AI pics/training/wrathshp/edited', '--resolution=512,512', '--output_dir=C:/Programs/stable-diffusion-webui/models/Stable-diffusion', '--train_batch_size=1', '--learning_rate=1e-06', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=0', '--use_8bit_adam', '--xformers', '--mixed_precision=fp16', '--save_every_n_epochs=1', '--seed=1234', '--save_precision=fp16', '--logging_dir=', '--output_name=wny']' returned non-zero exit status 1.

**Comment by healthyfat** [comment]
This error message is indicating that the file 'libbitsandbytes.so' cannot be loaded as a valid Win32 application. This is likely because the file is a shared object file, which is a type of executable file used on Linux and macOS systems. It is not compatible with Windows.

It seems that the package 'bitsandbytes' that you are trying to use is not compatible with the Windows operating system. The package 'bitsandbytes' is likely only compatible with Linux or macOS systems.

You may try checking the package documentation or contacting the package developer to see if there is a version of the package that is compatible with Windows or if there is any known workaround.

Alternatively, you could try running your code on a Linux or macOS system if that is possible for you.

You can also try searching for alternative packages that provide similar functionality and are compatible with Windows.

**Comment by healthyfat** [comment]
@bmaltais 

Can I run this GUI on Windows?

**Comment by bmaltais** [comment]
Hi,

This typically happen if you are installing modules outside the venv... or if you already have installed similar modules outside the venv.

One quick fix is to uninstall everything from the local env and re-install everything in the venv:

Open a new powershell window and run:

```
pip freeze > uninstall.txt
pip uninstall -r uninstall.txt
```

This can be cause if you did not give unrestricted script access to powershell so venv can work:

- Open an administrator powershell window
- Type `Set-ExecutionPolicy Unrestricted` and answer A
- Close admin powershell window

**Comment by healthyfat** [comment]
@bmaltais 

Thank you. That solved the problem.
