### ISSUE TITLE
Igot this error -- ValueError: invalid literal for int() with base 10: 'fine'

### ISSUE THREAD

**Issue by Quironn** [bmaltais/kohya_ss#393]
Folder 150_TeaganPresley: 1500 steps
Traceback (most recent call last):
  File "H:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\gradio\blocks.py", line 1024, in process_api
    result = await self.call_function(
  File "H:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\gradio\blocks.py", line 836, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "H:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "H:\Kohya_ss-GUI-LoRA-Portable-main\lora_gui.py", line 407, in train_model
    repeats = int(folder.split('_')[0])
ValueError: invalid literal for int() with base 10: 'fine'

**Comment by Quironn** [comment]
How can i fix it?

**Comment by Arnold2006** [comment]
Yep....
Got the same error on a FRESH Kohya install . So irritating
