### ISSUE TITLE
KeyError: 'time_embed.0.weight'

### ISSUE THREAD

**Issue by zxzxde** [bmaltais/kohya_ss#397]
Window10
python3.10.9
CPU: AMD 5950x
GPU:  Nvidia 3080ti

found directory D:\CGAI\stable_diffusion_webui\sucai\imgs\100_test contains 30 image files
3000 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "D:\CGAI\stable_diffusion_webui\sucai\imgs\100_test"
    image_count: 30
    num_repeats: 100
    shuffle_caption: True
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    is_reg: False
    class_tokens: test
    caption_extension: .caption

[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 3332.52it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (320, 512), count: 3000
mean ar error (without repeats): 0.05859375
prepare accelerator
Using accelerator 0.15.0 or above.
load StableDiffusion checkpoint
Traceback (most recent call last):
  File "D:\CGAI\stable_diffusion_webui\kohya_ss\train_network.py", line 659, in <module>
    train(args)
  File "D:\CGAI\stable_diffusion_webui\kohya_ss\train_network.py", line 115, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype)
  File "D:\CGAI\stable_diffusion_webui\kohya_ss\library\train_util.py", line 2027, in load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, name_or_path)
  File "D:\CGAI\stable_diffusion_webui\kohya_ss\library\model_util.py", line 877, in load_models_from_stable_diffusion_checkpoint
    converted_unet_checkpoint = convert_ldm_unet_checkpoint(v2, state_dict, unet_config)
  File "D:\CGAI\stable_diffusion_webui\kohya_ss\library\model_util.py", line 234, in convert_ldm_unet_checkpoint
    new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
KeyError: 'time_embed.0.weight'
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\CGAI\stable_diffusion_webui\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\CGAI\stable_diffusion_webui\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\CGAI\stable_diffusion_webui\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\CGAI\stable_diffusion_webui\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\CGAI\\stable_diffusion_webui\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=D:/CGAI/stable_diffusion_webui/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/hipoly3DModelLora_v10.safetensors', '--train_data_dir=D:/CGAI/stable_diffusion_webui/sucai/imgs', '--resolution=512,512', '--output_dir=D:/CGAI/stable_diffusion_webui/kohya_ss/output/models', '--logging_dir=D:/CGAI/stable_diffusion_webui/kohya_ss/output/logs', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=last', '--lr_scheduler_num_cycles=15', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=4500', '--train_batch_size=1', '--max_train_steps=45000', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--bucket_reso_steps=64', '--mem_eff_attn', '--shuffle_caption', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
I have no idea. Best I can recommend at this point is to try to run `upgrade.ps1` to see if there a no modules missing or requiring updates.
