### ISSUE TITLE
Can't start training, "dynamo_config" issue

### ISSUE THREAD

**Issue by Archer-Dante** [bmaltais/kohya_ss#414]
Hello
Tried everything I can, still can't make any training, always got this error about "dynamo config"

`accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --v2 --enable_bucket --pretrained_model_name_or_path="C:\neuro\stable-diffusion-webui-master\models\Stable-diffusion\wd-1-4-anime_e1.ckpt" --train_data_dir="C:\Users\user\Desktop\lora_model\image" --resolution=512,512 --output_dir="C:\Users\user\Desktop\lora_model\model" --logging_dir="C:\Users\user\Desktop\lora_model\log" --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=8 --output_name="last" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="cosine" --lr_warmup_steps="1700" --train_batch_size="1" --max_train_steps="17000" --save_every_n_epochs="1" --mixed_precision="bf16" --save_precision="bf16" --cache_latents --optimizer_type="AdamW8bit" --bucket_reso_steps=64 --xformers --bucket_no_upscale  --sample_sampler=euler_a --sample_prompts="C:\Users\user\Desktop\lf2remaster_lora_model\model\sample\prompt.txt" --sample_every_n_steps="200"
Traceback (most recent call last):
  File "C:\Program Files\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\neuro\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\neuro\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\neuro\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1000, in launch_command
    defaults = load_config_from_file(args.config_file)
  File "C:\neuro\kohya_ss\venv\lib\site-packages\accelerate\commands\config\config_args.py", line 64, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "C:\neuro\kohya_ss\venv\lib\site-packages\accelerate\commands\config\config_args.py", line 122, in from_yaml_file
    return cls(**config_dict)
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'dynamo_config'`

Any solution to this?
I followed all instructions
==================

Also if i run same training command (printed with webui) with console (and install all requirments) it works but freezes on 
`dataset 0 caching latents`
(looks similar to this https://github.com/kohya-ss/sd-scripts/issues/281 i.e.),

So i don't know maybe both issues somehow related to each other.

Using 2080 8gb if it matters...

**Comment by bmaltais** [comment]
I don't think kohya_ss support dynamo. I suggest you open an issue directly with him on this: https://github.com/kohya-ss/sd-scripts/issues

**Comment by Archer-Dante** [comment]
It's not about scripts, since it's clear install without any other scripts from sd-scripts repo.

I'm just using web-ui with my own configuration (or even those I found on web) - it doesn't matters, still same error

**Comment by Archer-Dante** [comment]
Ok, here is the solution after 2 days of tries and errors!

Delete all contents within path `C:\Users\user\.cache\huggingface` and `C:\Users\user\.cache\torch` 
Looks like other webui's or libraries I've used before cached something right there and it ruined everything somehow.

That's why no re-install of webui or python helps, since issue was in cache.

**Comment by Andie-Squirrel** [comment]
Hi Archer.

I tried deleting the contents in the paths you specified but after running the webui and clicking 'train', I got the following error.

`[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 40/40 [00:00<00:00, 1329.84it/s]
prepare dataset
prepare accelerator
Traceback (most recent call last):
  File "C:\Users\[MyPCName]\stable-diffusion-webui\Kohya\kohya_ss\train_db.py", line 364, in <module>
    train(args)
  File "C:\Users\[MyPCName]\stable-diffusion-webui\Kohya\kohya_ss\train_db.py", line 75, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "C:\Users\[MyPCName]\stable-diffusion-webui\Kohya\kohya_ss\library\train_util.py", line 1984, in prepare_accelerator
    accelerator = Accelerator(gradient_accumulation_steps=args.gradient_accumulation_steps, mixed_precision=args.mixed_precision,
  File "C:\Users\[MyPCName]\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 355, in __init__
    raise ValueError(err.format(mode="fp16", requirement="a GPU"))
ValueError: fp16 mixed precision requires a GPU
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\[MyPCName]\stable-diffusion-webui\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\[MyPCName]\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\[MyPCName]\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\[MyPCName]\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\[MyPCName]\\stable-diffusion-webui\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_db.py', '--v2', '--v_parameterization', '--pretrained_model_name_or_path=S:\\AI\\Stable-Diffusion-Webui 2.1 Models\\v2-1_768-nonema-pruned.ckpt', '--train_data_dir=S:/AI/_LORA TRAINING/Training Lora/image', '--resolution=768,768', '--output_dir=S:/AI/_LORA TRAINING/Training Lora/model', '--logging_dir=S:/AI/_LORA TRAINING/Training Lora/log', '--save_model_as=safetensors', '--output_name=Training 1', '--max_data_loader_n_workers=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=6000', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.`

Either way, it doesn't seem to be able to work properly.

**Comment by Archer-Dante** [comment]
Idk
Maybe Python version related error, since 3.10 needed, and log says something about 3.9

Anyway I've wiped the whole `C:\Users\user\.cache\...` and then re-installed Kohya-ss

**Comment by Andie-Squirrel** [comment]
That's possible, I set Python 3.10 to Path, and maybe I'm just too much of a novice, but I haven't been able to get Stable Diffusion or Kohya to run on Python 3.9. Been trying to fresh install Xformers because I have been getting alerts on that, but it's probably something wrong on my doing.

Before I deleted the cache Kohya looked as if it was working but got stuck at 0% Caching latent information, I believe, but now it's yielding a series of errors. I literally have no clue what else could be the problem. Maybe if a setting is changed and then the cache flushed might solve the problem, but I have no idea what else I can do to fix this issue.

I do however appreciate the advice, and I'm probably missing something really simple.

**Comment by Andie-Squirrel** [comment]
Oh and yes I did reinstall Kohya and upgraded it to no avail.
