### ISSUE TITLE
can't run train in windows 11 as raise "Distributed package doesn't have NCCL built in"

### ISSUE THREAD

**Issue by sjsanjsrh** [bmaltais/kohya_ss#431]
I try train, but get some error. 
someone is success train in windows 11. 
but my system is can't. how solve it??

System environment
> CPU : i9 13900KS
> RAM : 64G
> GPU : RTX 4080 16G
> OS : Windows 11 22H2
> Python : 3.10.6

console log
```
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --enable_bucket --pretrained_model_name_or_path="<some path>.ckpt" --train_data_dir="<some path>/kohya_ss/images/img" --resolution=512,512 --output_dir="<some path>/kohya_ss/images/output" --logging_dir="" --network_alpha="1" --network_module=networks.lora --text_encoder_lr=0.0005 --unet_lr=0.0001 --network_dim=128 --output_name="reizeimako" --lr_scheduler_num_cycles="1" --learning_rate="0.001" --lr_scheduler="cosine" --lr_warmup_steps="3582" --train_batch_size="4" --max_train_steps="35825" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --cache_latents --optimizer_type="AdamW8bit" --clip_skip=2 --bucket_reso_steps=64 --xformers --bucket_no_upscale
NOTE: Redirects are currently not supported in Windows or MacOs.
[W ..\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [DESKTOP-7Q77KOJ]:29500 (system error: 10049 - 요청한 주소는 해당 컨텍스트에서 유효하지 않습니다.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [DESKTOP-7Q77KOJ]:29500 (system error: 10049 - 요청한 주소는 해당 컨텍스트에서 유효하지 않습니다.).
prepare tokenizer
Use DreamBooth method.
prepare images.
found directory <some path>\kohya_ss\images\img\100_iom reizei mako,mako,mako reizei contains 2868 image files
286800 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 4
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "<some path>\kohya_ss\images\img\<some path>"
    image_count: 2868
    num_repeats: 100
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    is_reg: False
    class_tokens: iom reizei mako,mako,mako reizei
    caption_extension: .caption


[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████| 1434/1434 [00:00<00:00, 1893.36it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (128, 256), count: 100
---------------------------------------------omitted---------------------------------------------
bucket 40: resolution (1024, 192), count: 100
mean ar error (without repeats): 0.0347410106525277
prepare accelerator
[W ..\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [DESKTOP-7Q77KOJ]:29500 (system error: 10049 - 요청한 주소는 해당 컨텍스트에서 유효하지 않습니다.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [DESKTOP-7Q77KOJ]:29500 (system error: 10049 - 요청한 주소는 해당 컨텍스트에서 유효하지 않습니다.).
Traceback (most recent call last):
  File "<some path>\kohya_ss\train_network.py", line 699, in <module>
    train(args)
  File "<some path>\kohya_ss\train_network.py", line 119, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "<some path>\kohya_ss\library\train_util.py", line 2498, in prepare_accelerator
    accelerator = Accelerator(
  File "<some path>\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 308, in __init__
    self.state = AcceleratorState(
  File "<some path>\kohya_ss\venv\lib\site-packages\accelerate\state.py", line 150, in __init__
    torch.distributed.init_process_group(backend="nccl", **kwargs)
  File "<some path>\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 602, in init_process_group
    default_pg = _new_process_group_helper(
  File "<some path>\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 727, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 9352) of binary: <some path>\kohya_ss\venv\Scripts\python.exe
```

**Comment by bmaltais** [comment]
You should open an issue directly with kohya as this is related to the trainer: https://github.com/kohya-ss/sd-scripts/issues
