### ISSUE TITLE
cudart64_110.dll lose

### ISSUE THREAD

**Issue by lazyq666** [bmaltais/kohya_ss#437]
My graphics card is 4060 and the CUDA version is 12.0.147. I encountered an error when training the lora model using Kohya. please help me

To create a public link, set `share=True` in `launch()`.
Loading config...
Folder 54_giftlora230323: 28 images found
Folder 54_giftlora230323: 1512 steps
max_train_steps = 1512
stop_text_encoder_training = 0
lr_warmup_steps = 0
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" --train_data_dir="E:/OneDrive/Mywork/AItrain/gift_lora_230323/Image" --resolution=512,512 --output_dir="E:/OneDrive/Mywork/AItrain/gift_lora_230323/Model" --logging_dir="E:/OneDrive/Mywork/AItrain/gift_lora_230323/Log" --network_alpha="128" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=128 --output_name="icon_gift230203_sd15" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="1" --max_train_steps="1512" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --seed="1234" --caption_extension=".txt" --cache_latents --optimizer_type="AdamW" --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --mem_eff_attn --gradient_checkpointing --xformers --bucket_no_upscale
2023-03-23 22:14:57.749602: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-03-23 22:14:57.749898: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-03-23 22:15:03.410777: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-03-23 22:15:03.410904: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Could not find module 'E:\Software\SD\kohya\kohya_ss\venv\Lib\site-packages\xformers\_C.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
WARNING:root:WARNING: Could not find module 'E:\Software\SD\kohya\kohya_ss\venv\Lib\site-packages\xformers\_C.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
Need to compile C++ extensions to get sparse attention suport. Please run python setup.py build develop
prepare tokenizer
Use DreamBooth method.
prepare images.
found directory E:\OneDrive\Mywork\AItrain\gift_lora_230323\Image\54_giftlora230323 contains 28 image files
1512 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: False

  [Subset 0 of Dataset 0]
    image_dir: "E:\OneDrive\Mywork\AItrain\gift_lora_230323\Image\54_giftlora230323"
    image_count: 28
    num_repeats: 54
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    is_reg: False
    class_tokens: giftlora230323
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [00:00<00:00, 1695.16it/s]
prepare dataset
prepare accelerator
Traceback (most recent call last):
  File "E:\Software\SD\kohya\kohya_ss\train_network.py", line 659, in <module>
    train(args)
  File "E:\Software\SD\kohya\kohya_ss\train_network.py", line 108, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "E:\Software\SD\kohya\kohya_ss\library\train_util.py", line 1984, in prepare_accelerator
    accelerator = Accelerator(gradient_accumulation_steps=args.gradient_accumulation_steps, mixed_precision=args.mixed_precision,
  File "E:\Software\SD\kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 355, in __init__
    raise ValueError(err.format(mode="fp16", requirement="a GPU"))
ValueError: fp16 mixed precision requires a GPU
Traceback (most recent call last):
  File "E:\Software\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Software\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Software\SD\kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "E:\Software\SD\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "E:\Software\SD\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "E:\Software\SD\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\Software\\SD\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=E:/OneDrive/Mywork/AItrain/gift_lora_230323/Image', '--resolution=512,512', '--output_dir=E:/OneDrive/Mywork/AItrain/gift_lora_230323/Model', '--logging_dir=E:/OneDrive/Mywork/AItrain/gift_lora_230323/Log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=icon_gift230203_sd15', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=1512', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by cpy1990** [comment]
same issue

**Comment by DarksealStudios** [comment]
cudart64_110.dll not found, using 21.5.5

**Comment by r1nd0x** [comment]
same issue
