### ISSUE TITLE
Error after "load StableDiffusion checkpoint"

### ISSUE THREAD

**Issue by AniMoster** [bmaltais/kohya_ss#447]
What might the possible solution for this?

Validating that requirements are satisfied.
All requirements satisfied.
Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loading config...
←[33mFolder 100_Validating that requirements are satisfied.
All requirements satisfied.
Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loading config...
←[33mFolder 100_train : 4700 steps←[0m
max_train_steps = 4700
stop_text_encoder_training = 0
lr_warmup_steps = 0
accelerate launch --num_cpu_threads_per_process=2 "train_db.py" --v_parameterization --enable_bucket --pretrained_model_name_or_path="C:/Users/name/AI/stable-diffusion-webui/models/Stable-diffusion/chilloutmix_NiPrunedFp32Fix.safetensors" --train_data_dir="C:/Users/name/AI/Kohya/LoRA/train LoRA/image" --resolution=512,512 --output_dir="C:/Users/name/AI/Kohya/LoRA/train LoRA/model" --logging_dir="C:/Users/name/AI/Kohya/LoRA/train LoRA/log" --save_model_as=safetensors --output_name="train" --max_data_loader_n_workers="1" --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="1" --max_train_steps="4700" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --seed="1234" --caption_extension=".txt" --cache_latents --optimizer_type="AdamW" --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --mem_eff_attn --gradient_checkpointing --xformers --bucket_no_upscale
prepare tokenizer
prepare images.
found directory C:\Users\name\AI\Kohya\LoRA\train LoRA\image\100_train contains 94 image files
9400 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "C:\Users\name\AI\Kohya\LoRA\train LoRA\image\100_train"
    image_count: 94
    num_repeats: 100
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    is_reg: False
    class_tokens: train
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|█████████████████████████████████████████████████████████████████████████████████| 47/47 [00:00<00:00, 676.04it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (320, 576), count: 100
bucket 1: resolution (320, 704), count: 100
bucket 2: resolution (384, 512), count: 700
bucket 3: resolution (384, 576), count: 1100
bucket 4: resolution (448, 448), count: 100
bucket 5: resolution (512, 384), count: 1000
bucket 6: resolution (512, 448), count: 100
bucket 7: resolution (576, 384), count: 1400
bucket 8: resolution (640, 320), count: 100
mean ar error (without repeats): 0.01843941421052905
prepare accelerator
Using accelerator 0.15.0 or above.
load StableDiffusion checkpoint
Traceback (most recent call last):
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\name\AI\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\name\AI\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\name\AI\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\name\AI\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\name\\AI\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_db.py', '--enable_bucket', '--pretrained_model_name_or_path=C:/Users/name/AI/stable-diffusion-webui/models/Stable-diffusion/chilloutmix_NiPrunedFp32Fix.safetensors', '--train_data_dir=C:/Users/name/AI/Kohya/LoRA/train LoRA/image', '--resolution=512,512', '--output_dir=C:/Users/name/AI/Kohya/LoRA/train LoRA/model', '--logging_dir=C:/Users/name/AI/Kohya/LoRA/train LoRA/log', '--save_model_as=safetensors', '--output_name=train', '--max_data_loader_n_workers=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=4700', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 3221225477

**Comment by Big-ANGELO** [comment]
THE same problem~who exactly knows what the FXXXing problem is??~~~!!!

**Comment by AniMoster** [comment]
> THE same problem~who exactly knows what the FXXXing problem is??~~~!!!

How much vram do you have?

**Comment by Agnyy** [comment]
https://github.com/bmaltais/kohya_ss/issues/633
