### ISSUE TITLE
Error after update it

### ISSUE THREAD

**Issue by merecesarchviz** [bmaltais/kohya_ss#451]
any idea what is happening and how to solve! :

poch 1/1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ryzen_Reaper\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Ryzen_Reaper\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Ryzen_Reaper\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Ryzen_Reaper\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Ryzen_Reaper\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Ryzen_Reaper\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Ryzen_Reaper\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\kohya\sd-scripts\train_network.py", line 1, in <module>
    from torch.nn.parallel import DistributedDataParallel as DDP
  File "F:\kohya\sd-scripts\venv\lib\site-packages\torch\__init__.py", line 129, in <module>
    raise err
OSError: [WinError 1455] O ficheiro de estrutura de página é demasiado pequeno para que esta operação seja concluída. Error loading "F:\kohya\sd-scripts\venv\lib\site-packages\torch\lib\cusparse64_11.dll" or one of its dependencies.

**Comment by merecesarchviz** [comment]
solved
