### ISSUE TITLE
unable to detect GPU (ValueError: fp16 mixed precision requires a GPU)

### ISSUE THREAD

**Issue by runner22k** [bmaltais/kohya_ss#46]
**I am totally new to dreambooth so I am following this [video](https://www.youtube.com/watch?v=RlvqEKj03WI) based on that I have chosen 350 repeats for 16 images.**

**After Pressing on the Train button, i am getting below errors. Please look into this and guide me through the resolution.**

ValueError: fp16 mixed precision requires a GPU

```
Save...
Folder 350_sonar123 woman: 5600 steps
Regularisation images are used... Will double the number of steps required...
max_train_steps = 11200
stop_text_encoder_training = 0
lr_warmup_steps = 0
accelerate launch --num_cpu_threads_per_process=14 "train_db.py" --cache_latents --enable_bucket --use_8bit_adam --xformers --pretrained_model_name_or_path="D:/models/dreamlike-diffusion-1.0.ckpt" --train_data_dir="E:/0train/sonar123\img" --reg_data_dir="E:/0train/sonar123\reg" --resolution=512,512 --output_dir="E:/0train/sonar123\model" --train_batch_size=1 --learning_rate=1e-06 --lr_scheduler=constant --lr_warmup_steps=0 --max_train_steps=11200 --use_8bit_adam --xformers --mixed_precision=fp16 --save_every_n_epochs=1 --seed=1234 --save_precision=fp16 --logging_dir="E:/0train/sonar123\log" --save_model_as=ckpt --output_name="sonar123"
prepare tokenizer
prepare train images.
found directory 350_sonar123 woman contains 16 image files
5600 train images with repeating.
prepare reg images.
found directory 1_woman contains 1516 image files
1516 reg images.
loading image sizes.
100%|██████████████████████████████████████████████████████████████████████████████████████████| 1532/1532 [00:00<00:00, 12652.87it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (256, 832), count: 0
bucket 1: resolution (256, 896), count: 0
bucket 2: resolution (256, 960), count: 0
bucket 3: resolution (256, 1024), count: 0
bucket 4: resolution (320, 704), count: 0
bucket 5: resolution (320, 768), count: 0
bucket 6: resolution (384, 640), count: 0
bucket 7: resolution (448, 576), count: 0
bucket 8: resolution (512, 512), count: 11200
bucket 9: resolution (576, 448), count: 0
bucket 10: resolution (640, 384), count: 0
bucket 11: resolution (704, 320), count: 0
bucket 12: resolution (768, 320), count: 0
bucket 13: resolution (832, 256), count: 0
bucket 14: resolution (896, 256), count: 0
bucket 15: resolution (960, 256), count: 0
bucket 16: resolution (1024, 256), count: 0
mean ar error (without repeats): 0.0
prepare accelerator
Traceback (most recent call last):
  File "D:\kohya_ss\train_db.py", line 332, in <module>
    train(args)
  File "D:\kohya_ss\train_db.py", line 56, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "D:\kohya_ss\library\train_util.py", line 1162, in prepare_accelerator
    accelerator = Accelerator(gradient_accumulation_steps=args.gradient_accumulation_steps, mixed_precision=args.mixed_precision,
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 355, in __init__
    raise ValueError(err.format(mode="fp16", requirement="a GPU"))
ValueError: fp16 mixed precision requires a GPU
Traceback (most recent call last):
  File "C:\Users\jan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohya_ss\\venv\\Scripts\\python.exe', 'train_db.py', '--cache_latents', '--enable_bucket', '--use_8bit_adam', '--xformers', '--pretrained_model_name_or_path=D:/models/dreamlike-diffusion-1.0.ckpt', '--train_data_dir=E:/0train/sonar123\\img', '--reg_data_dir=E:/0train/sonar123\\reg', '--resolution=512,512', '--output_dir=E:/0train/sonar123\\model', '--train_batch_size=1', '--learning_rate=1e-06', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=11200', '--use_8bit_adam', '--xformers', '--mixed_precision=fp16', '--save_every_n_epochs=1', '--seed=1234', '--save_precision=fp16', '--logging_dir=E:/0train/sonar123\\log', '--save_model_as=ckpt', '--output_name=sonar123']' returned non-zero exit status 1.
```

**Comment by bmaltais** [comment]
What type of graphic card do you have? Do you have an NVdia GPU?

**Comment by runner22k** [comment]
yes. Nvidia 2080Super 8GB VRAM 64GB system RAM

**Comment by runner22k** [comment]
> What type of graphic card do you have? Do you have an NVdia GPU?

Hi @bmaltais I solved this issue. this Problem raises when we didn't Install CUDA in the system before installing Kohya. So, after installing CUDA, we should install Kohya_ss.

As I am already using Automatic1111, I assumed this will work too. But, maybe,  kohya_ss needs CUDA drivers installed in the base system irrespective of venv.
