### ISSUE TITLE
How to disable usage of xfromers?

### ISSUE THREAD

**Issue by kgonia** [bmaltais/kohya_ss#470]
I'm trining to finetune on AWS DLAMI machine. 

because I have problem with xformers installation on this machine I wanted to train without xformers but uncheck 'Use xformers' has no effect. I got this error:
```

NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 2, 1, 40) (torch.float32)
     key         : shape=(1, 2, 1, 40) (torch.float32)
     value       : shape=(1, 2, 1, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
`tritonflashattF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
    requires A100 GPU
`cutlassF` is not supported because:
    xFormers wasn't build with CUDA support
`smallkF` is not supported because:
    xFormers wasn't build with CUDA support
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 40
Traceback (most recent call last):
  File "/home/ubuntu/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/ubuntu/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/home/ubuntu/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/kohya_ss/venv/bin/python3.10', './fine_tune.py', '--train_text_encoder', '--pretrained_model_name_or_path=/mnt/datas/sd_checkpoints/avalonTruvision_v2.safetensors', '--in_json=/mnt/datas/midjourney/config2/meta_lat.json', '--train_data_dir=/mnt/datas/midjourney/small', '--output_dir=/mnt/datas/midjourney/model_result', '--logging_dir=/mnt/datas/midjourney/logs', '--dataset_repeats=40', '--learning_rate=1e-5', '--enable_bucket', '--resolution=512,512', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--save_model_as=safetensors', '--output_name=stylejourney15k', '--max_token_length=225', '--learning_rate=1e-5', '--lr_scheduler=cosine', '--lr_warmup_steps=14', '--train_batch_size=8', '--max_train_steps=135', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW', '--max_data_loader_n_workers=0', '--max_token_length=225', '--bucket_reso_steps=64', '--full_fp16', '--sample_sampler=euler_a', '--sample_prompts=/mnt/datas/midjourney/model_result/sample/prompt.txt', '--sample_every_n_steps=1000']'
```

My question is how to effectivly disable xformers or properly install it on ubuntu with CUDA 11.7?

**Comment by Exponential-Workload** [comment]
having issues with xformers myself on arch linux

**Comment by bmaltais** [comment]
Hello @kgonia 

This is really a question for kohya_ss... I suggest you reach out to him at https://github.com/kohya-ss/sd-scripts
