### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'unscale_'

### ISSUE THREAD

**Issue by Jiaqian-Xu** [bmaltais/kohya_ss#476]

**Comment by steveauai** [comment]
I have the same error with training Lora as below

import network module: networks.lora
create LoRA network. base dim (rank): 128, alpha: 128.0
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
use AdamW optimizer | {}
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 1500
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 750
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 2
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 750
steps:   0%|                                                                                                                            | 0/750 [00:00<?, ?it/s]epoch 1/1
Traceback (most recent call last):
  File "/Users/steveworkspace/Workspace/Projects/Kohya/kohya_ss/train_network.py", line 748, in <module>
    train(args)
  File "/Users/steveworkspace/Workspace/Projects/Kohya/kohya_ss/train_network.py", line 605, in train
    accelerator.clip_grad_norm_(params_to_clip, args.max_grad_norm)
  File "/Users/steveworkspace/Workspace/Projects/Kohya/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1373, in clip_grad_norm_
    self.unscale_gradients()
  File "/Users/steveworkspace/Workspace/Projects/Kohya/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1336, in unscale_gradients
    self.scaler.unscale_(opt)
AttributeError: 'NoneType' object has no attribute 'unscale_'
steps:   0%|

**Comment by steveauai** [comment]
Finally I found, I have to set Mixed precision = no, this is working on Macbook Pro M2

**Comment by Whyjsee** [comment]
> Finally I found, I have to set Mixed precision = no, this is working on Macbook Pro M2

it works , thx
