### ISSUE TITLE
OSError: [WinError 127]  Error loading specified procedure ore one of its dependencies "cudnn_adv_infer64-8.dll "

### ISSUE THREAD

**Issue by nakry** [bmaltais/kohya_ss#486]
Hi everyone,

I'm facing a problem with `cudnn_adv_infer64-8.dll `
When trying to launch a training, i have the following error:

`Traceback (most recent call last):
  File "C:\Users\AAAA\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\AAAA\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\SSD\SuperSD2.0\kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 4, in <module>
  File "E:\SSD\SuperSD2.0\kohya\kohya_ss\venv\lib\site-packages\accelerate\__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "E:\SSD\SuperSD2.0\kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 25, in <module>
    import torch
  File "E:\SSD\SuperSD2.0\kohya\kohya_ss\venv\lib\site-packages\torch\__init__.py", line 129, in <module>
    raise err
OSError: [WinError 127] La procédure spécifiée est introuvable. Error loading "E:\SSD\SuperSD2.0\kohya\kohya_ss\venv\lib\site-packages\torch\lib\cudnn_adv_infer64_8.dll" or one of its dependencies.`

I verified and the called file is on the folder.

Any ideas?

**Comment by bmaltais** [comment]
You might consider uninstalling (deleting) the kohya_ss folder and redo the installation from scratch.

If that does not work then it must be related to some software/drivers combination on your PC.

Make sure to install the latest NVIDIA drivers for your card and Python 3.10.9 (not 3.11)

**Comment by nakry** [comment]
Absolutely, I juste cleanly reinstalled everything and it worked perfectly! Thanks!
