### ISSUE TITLE
Can't train model - Traceback Error?

### ISSUE THREAD

**Issue by dnihil** [bmaltais/kohya_ss#498]
I have no idea how I would word this so sorry in advance if this has been solved or asked about already.

I can't train my model and honestly the whole process is very confusing.

`Folder 150_fade_valorant: 15 images found
Folder 150_fade_valorant: 2250 steps
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\koyha_ss\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion-webui\koyha_ss\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1024, in process_api
    result = await self.call_function(
  File "E:\stable-diffusion-webui\koyha_ss\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 836, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\stable-diffusion-webui\koyha_ss\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\stable-diffusion-webui\koyha_ss\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\stable-diffusion-webui\koyha_ss\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\stable-diffusion-webui\koyha_ss\kohya_ss\lora_gui.py", line 422, in train_model
    repeats = int(folder.split('_')[0])
ValueError: invalid literal for int() with base 10: 'log'`

**Comment by dnihil** [comment]
I am stupid and set my folder up wrong. I required an "img" folder and putting my "150_fade_valorant" folder inside "img"
