### ISSUE TITLE
TypeError unexpected keyword argument 'command_file'

### ISSUE THREAD

**Issue by dkzx319** [bmaltais/kohya_ss#505]
Been getting this error when I click on `Train model`.
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/opt/homebrew/lib/python3.10/site-packages/accelerate/commands/launch.py", line 747, in launch_command
    defaults = load_config_from_file(args.config_file)
  File "/opt/homebrew/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 64, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "/opt/homebrew/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 117, in from_yaml_file
    return cls(**config_dict)
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'command_file'
```

Running on macOS with Python 3.11.2. 
Anyone knows what's the issue?

**Comment by bmaltais** [comment]
My understanding is that you need python 3.10... 3.11 is not supported by kohya_ss code.

**Comment by howardgriffin** [comment]
Same problem, my python version is 3.8.13. How to solve it?

**Comment by SophiaDz001** [comment]
Creating a new environment has solved the problem

**Comment by hey0chen** [comment]
It seems to be caused by the accelerate's version, try to install the corresponding version
`
pip install accelerate==0.15.0
`
