### ISSUE TITLE
 Can you please update to torch2.0 and cudnn8.8?

### ISSUE THREAD

**Issue by zzisme1** [bmaltais/kohya_ss#531]
Could not locate cublasLt64_12.dll. Please make sure it is in your library path!
Traceback (most recent call last):
  File "C:\Users\z\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\z\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya_ss_2023-03-02\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\kohya_ss_2023-03-02\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\kohya_ss_2023-03-02\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\kohya_ss_2023-03-02\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher

I tried to manually upgrade touch 2.0, cuda 12.1, and cudnn 8.81, but it failed. What should I do? Can you please update the kernel? I heard it has accelerated a lot

**Comment by bmaltais** [comment]
I will once Kohya does in his main repo. He write the trainer code
