### ISSUE TITLE
No module named 'fairscale' when BLIP captioning on Windows

### ISSUE THREAD

**Issue by filloax** [bmaltais/kohya_ss#533]
Title, more or less. Tried running BLIP captioning and got that. fairscale seems to be installed in the venv, as running venv activate and then pip install fairscale says it is already install.

Full log (edited folder names for privacy):

```
Validating that requirements are satisfied.
All requirements satisfied.
The arguments passed to this script were:
Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Captioning files in C:\Users\filloax\<path>...
./venv/Scripts/python.exe "finetune/make_captions.py" --batch_size="1" --num_beams="1" --top_p="0.9" --max_length="75" --min_length="5" --beam_search --caption_extension=".txt" "C:\Users\filloax\<path>" --caption_weights="https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth"
Traceback (most recent call last):
  File "C:\Dati\Misc_Programmi\KohyaSS\kohya_ss\finetune\make_captions.py", line 13, in <module>
    from blip.blip import blip_decoder
  File "C:\Dati\Misc_Programmi\KohyaSS\kohya_ss\finetune\blip\blip.py", line 13, in <module>
    from blip.vit import VisionTransformer, interpolate_pos_embed
  File "C:\Dati\Misc_Programmi\KohyaSS\kohya_ss\finetune\blip\vit.py", line 21, in <module>
    from fairscale.nn.checkpoint.checkpoint_activations import checkpoint_wrapper
ModuleNotFoundError: No module named 'fairscale'
...captioning done
```

**Comment by filloax** [comment]
Update: reinstalling fairscale inside the venv with `pip install --upgrade --no-deps --no-cache-dir --force-reinstall fairscale`, so also clearing the cache, worked.

(For people googling this, try this if a module in a venv is acting weird/is "not found")
