### ISSUE TITLE
FileNotFoundError: [WinError 3]

### ISSUE THREAD

**Issue by Woisek** [bmaltais/kohya_ss#559]
Today, I wanted to start Tensorboard, but when I click "Start tensorboard" I get an error instead:

Validating that requirements are satisfied.
All requirements satisfied.
Load CSS...
Running on local URL:  http://127.0.0.1:7870

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "I:\Super SD 2.0\Kohya\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\Super SD 2.0\Kohya\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1024, in process_api
    result = await self.call_function(
  File "I:\Super SD 2.0\Kohya\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 836, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "I:\Super SD 2.0\Kohya\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "I:\Super SD 2.0\Kohya\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "I:\Super SD 2.0\Kohya\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "I:\Super SD 2.0\Kohya\kohya_ss\library\tensorboard_gui.py", line 14, in start_tensorboard
    if not os.listdir(logging_dir):
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: ''

I used dev branch before, now I switched to master because I thought it would be solved there, but obviously not.
Any suggestions?

**Comment by Teragron** [comment]
This just happened to me as well

**Comment by bai0012** [comment]
me too

**Comment by bai0012** [comment]
> me too

Solved, you have to start a training process then start tenserboard
