### ISSUE TITLE
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'downcase_fp16'

### ISSUE THREAD

**Issue by YKefasu** [bmaltais/kohya_ss#564]
Traceback (most recent call last):
  File "C:\Users\yosia\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\yosia\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\KOh\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\KOh\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\KOh\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1000, in launch_command
    defaults = load_config_from_file(args.config_file)
  File "C:\KOh\kohya_ss\venv\lib\site-packages\accelerate\commands\config\config_args.py", line 64, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "C:\KOh\kohya_ss\venv\lib\site-packages\accelerate\commands\config\config_args.py", line 122, in from_yaml_file
    return cls(**config_dict)
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'downcase_fp16'

**Comment by YKefasu** [comment]
![image](https://user-images.githubusercontent.com/129555908/230641037-b707fd38-5ab0-4547-b999-365fbe685fe7.png)
solved by removing downcase_fp16: 'NO' line in C:\Users\＜username＞/.cache\huggingface\accelerate\default_config.yaml
