### ISSUE TITLE
CANT SET 0 LR in GUI (ValueError: adafactor does not require `num_warmup_steps`. Set None or 0.)

### ISSUE THREAD

**Issue by YKefasu** [bmaltais/kohya_ss#565]
Traceback (most recent call last):
  File "C:\KOh\kohya_ss\train_network.py", line 748, in <module>
    train(args)
  File "C:\KOh\kohya_ss\train_network.py", line 250, in train
    lr_scheduler = train_util.get_scheduler_fix(args, optimizer, accelerator.num_processes)
  File "C:\KOh\kohya_ss\library\train_util.py", line 2512, in get_scheduler_fix
    return wrap_check_needless_num_warmup_steps(transformers.optimization.AdafactorSchedule(optimizer, initial_lr))
  File "C:\KOh\kohya_ss\library\train_util.py", line 2489, in wrap_check_needless_num_warmup_steps
    raise ValueError(f"{name} does not require `num_warmup_steps`. Set None or 0.")
ValueError: adafactor:1.0 does not require `num_warmup_steps`. Set None or 0.
Traceback (most recent call last):
  File "C:\Users\yosia\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\yosia\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\KOh\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\KOh\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\KOh\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\KOh\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

![image](https://user-images.githubusercontent.com/129555908/230643899-29c354a0-325b-4ec2-a4f9-feea5dd743c6.png)

**Comment by DKnight54** [comment]
Er... I think you are looking in the wrong place. I believe that you should be setting this to zero, and learning rate to 1, Text Encoder to 0.5 and Unet learning rate to 1.
![image](https://user-images.githubusercontent.com/126916963/230649372-aaf94988-1a11-4bba-8b48-280c92d58dd7.png)

**Comment by YKefasu** [comment]
Thnankyou
