### ISSUE TITLE
Train Model stops with error

### ISSUE THREAD

**Issue by ChrisVonFrosta** [bmaltais/kohya_ss#568]
when press "Train model" in web ui, i got a lot of errors. 
```
Validating that requirements are satisfied.
All requirements satisfied.
Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loading config...
Folder 100_test: 14 images found
Folder 100_test: 1400 steps
max_train_steps = 700
stop_text_encoder_training = 0
lr_warmup_steps = 70
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --v2 --v_parameterization --enable_bucket --pretrained_model_name_or_path="C:/Users/Christian/stable-diffusion-webui/models/Stable-diffusion/realisticVisionV20_v20.safetensors" --train_data_dir="C:/Users/Christian/LoraTrainingData/test1/image" --resolution=512,512 --output_dir="C:/Users/Christian/LoraTrainingData/test1/model" --logging_dir="C:/Users/Christian/LoraTrainingData/test1/log" --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=8 --output_name="last" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="cosine" --lr_warmup_steps="70" --train_batch_size="2" --max_train_steps="700" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --cache_latents --optimizer_type="AdamW8bit" --max_data_loader_n_workers="0" --bucket_reso_steps=64 --mem_eff_attn --gradient_checkpointing --xformers --bucket_no_upscale
Traceback (most recent call last):
  File "C:\Users\Christian\kohya_ss\train_network.py", line 27, in <module>
    import library.huggingface_util as huggingface_util
ModuleNotFoundError: No module named 'library.huggingface_util'
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Christian\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\Christian\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\Christian\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\Christian\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Christian\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--v2', '--v_parameterization', '--enable_bucket', '--pretrained_model_name_or_path=C:/Users/Christian/stable-diffusion-webui/models/Stable-diffusion/realisticVisionV20_v20.safetensors', '--train_data_dir=C:/Users/Christian/LoraTrainingData/test1/image', '--resolution=512,512', '--output_dir=C:/Users/Christian/LoraTrainingData/test1/model', '--logging_dir=C:/Users/Christian/LoraTrainingData/test1/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=last', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=70', '--train_batch_size=2', '--max_train_steps=700', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.
```

how to fix it?

**Comment by bmaltais** [comment]
Try to run `upgrade.ps1` to make sure you have the latest library code in place.

**Comment by ChrisVonFrosta** [comment]
i just tried but i doesn't help.
any other ideas?

**Comment by bmaltais** [comment]
Try deleti g the kohya_ss folder and go through the installation steps again.
