### ISSUE TITLE
LoRA training crashing

### ISSUE THREAD

**Issue by Exozze** [bmaltais/kohya_ss#573]
```
From https://github.com/bmaltais/kohya_ss
 * branch            master     -> FETCH_HEAD
Already up to date.
Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loading config...
Folder 100_test: 16 images found
Folder 100_test: 1600 steps
max_train_steps = 800
stop_text_encoder_training = 0
lr_warmup_steps = 80
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --pretrained_model_name_or_path="F:/stable-diffusion-webui/models/Stable-diffusion/NovelAI.ckpt" --train_data_dir="F:\dataset" --resolution=512,512 --output_dir="F:\dataset" --logging_dir="" --network_alpha="128" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=128 --output_name="test" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="constant" --lr_warmup_steps="80" --train_batch_size="2" --max_train_steps="800" --save_every_n_epochs="1" --mixed_precision="bf16" --save_precision="bf16" --seed="1" --cache_latents --optimizer_type="AdamW8bit" --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --xformers --bucket_no_upscale
prepare tokenizer
Use DreamBooth method.
prepare images.
found directory F:\dataset\100_test contains 16 image files
1600 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 2
  resolution: (512, 512)
  enable_bucket: False

  [Subset 0 of Dataset 0]
    image_dir: "F:\dataset\100_test"
    image_count: 16
    num_repeats: 100
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: test
    caption_extension: .caption


[Dataset 0]
loading image sizes.
100%|██████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 271.32it/s]
prepare dataset
prepare accelerator
Using accelerator 0.15.0 or above.
loading model for process 0/1
load StableDiffusion checkpoint
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
Replace CrossAttention.forward to use xformers
[Dataset 0]
caching latents.
100%|███████████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  7.73it/s]
import network module: networks.lora
create LoRA network. base dim (rank): 128, alpha: 128.0
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary F:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit AdamW optimizer | {}
Traceback (most recent call last):
  File "F:\Kohya_ss-GUI-LoRA-Portable-main\train_network.py", line 748, in <module>
    train(args)
  File "F:\Kohya_ss-GUI-LoRA-Portable-main\train_network.py", line 250, in train
    lr_scheduler = train_util.get_scheduler_fix(args, optimizer, accelerator.num_processes)
  File "F:\Kohya_ss-GUI-LoRA-Portable-main\library\train_util.py", line 2517, in get_scheduler_fix
    return wrap_check_needless_num_warmup_steps(schedule_func(optimizer))
  File "F:\Kohya_ss-GUI-LoRA-Portable-main\library\train_util.py", line 2489, in wrap_check_needless_num_warmup_steps
    raise ValueError(f"{name} does not require `num_warmup_steps`. Set None or 0.")
ValueError: SchedulerType.CONSTANT does not require `num_warmup_steps`. Set None or 0.
Traceback (most recent call last):
  File "F:\Kohya_ss-GUI-LoRA-Portable-main\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\Kohya_ss-GUI-LoRA-Portable-main\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\Kohya_ss-GUI-LoRA-Portable-main\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "F:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "F:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "F:\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['F:\\Kohya_ss-GUI-LoRA-Portable-main\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=F:/stable-diffusion-webui/models/Stable-diffusion/NovelAI.ckpt', '--train_data_dir=F:\\dataset', '--resolution=512,512', '--output_dir=F:\\dataset', '--logging_dir=', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=test', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=80', '--train_batch_size=2', '--max_train_steps=800', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.
```

**Comment by DKnight54** [comment]
Erm... From the error message? Same as this [issue](https://github.com/bmaltais/kohya_ss/issues/565)...
