### ISSUE TITLE
Haw to fix this 

### ISSUE THREAD

**Issue by imran123223** [bmaltais/kohya_ss#592]
running training / 学习开始
  num train images * repeats / 学习图像数×重复次数: 1080
  num reg images / 正则化图像数: 0
  num batches per epoch / 1epoch批数: 1080
  num epochs / epoch数: 1
  batch size per device / 批量大小: 1
  gradient accumulation steps / 坡度合计步数 = 1
  total optimization steps / 学习步数: 1080
steps:   0%|                                     | 0/1080 [00:00<?, ?it/s]epoch 1/1
Traceback (most recent call last):
  File "/Users/imran/kohya_ss/train_network.py", line 724, in <module>
    train(args)
  File "/Users/imran/kohya_ss/train_network.py", line 559, in train
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/Users/imran/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/imran/miniconda3/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 381, in forward
    sample, res_samples = downsample_block(
  File "/Users/imran/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/imran/miniconda3/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 612, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
  File "/Users/imran/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/imran/miniconda3/lib/python3.10/site-packages/diffusers/models/attention.py", line 216, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "/Users/imran/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/imran/miniconda3/lib/python3.10/site-packages/diffusers/models/attention.py", line 484, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "/Users/imran/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/imran/kohya_ss/library/train_util.py", line 1790, in forward_xformers
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None)  # 最適なのを選んでくれる
  File "/Users/imran/miniconda3/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 196, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/Users/imran/miniconda3/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 299, in _memory_efficient_attention
    return _fMHA.apply(
  File "/Users/imran/miniconda3/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/Users/imran/miniconda3/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 41, in forward
    out, op_ctx = _memory_efficient_attention_forward_requires_grad(
  File "/Users/imran/miniconda3/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 324, in _memory_efficient_attention_forward_requires_grad
    op = _dispatch_fw(inp)
  File "/Users/imran/miniconda3/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py", line 98, in _dispatch_fw
    return _run_priority_list(
  File "/Users/imran/miniconda3/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py", line 73, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 4096, 8, 40) (torch.float32)
     key         : shape=(1, 4096, 8, 40) (torch.float32)
     value       : shape=(1, 4096, 8, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`cutlassF` is not supported because:
    device=cpu (supported: {'cuda'})
    Operator wasn't built - see `python -m xformers.info` for more info
`flshattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    Operator wasn't built - see `python -m xformers.info` for more info
`tritonflashattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    Operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    Operator wasn't built - see `python -m xformers.info` for more info
    unsupported embed per head: 40
steps:   0%|                                     | 0/1080 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/Users/imran/miniconda3/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/Users/imran/miniconda3/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/Users/imran/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/Users/imran/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/Users/imran/miniconda3/bin/python3.10', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=/Users/imran/sd/models/Stable-diffusion/uberRealistic.safetensors', '--train_data_dir=/Users/imran/Desktop/birme-512x512/2/img', '--resolution=512,512', '--output_dir=/Users/imran/sd/models/train_lora', '--logging_dir=/Users/imran/sd/models/train_lora/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=5', '--output_name=imran', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0004', '--lr_scheduler=cosine', '--lr_warmup_steps=216', '--train_batch_size=1', '--max_train_steps=1080', '--mixed_precision=no', '--save_precision=bf16', '--seed=1234', '--cache_latents', '--optimizer_type=AdamW', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by imran123223** [comment]
I have encountered this error when running program on Mac

**Comment by yangyanghoho** [comment]
@imran123223 did you solve this issue ? thanks

**Comment by zjc2233** [comment]
> imran123223

me too,  Did you know how to resolve this issue?

**Comment by congdc00** [comment]
Please check your pytorch version with the command
`python -m xformers.info`
In my case, it showed as pytorch==2.0.1+cu118 and xformers==0.0.20. The xformers version is completely incompatible with pytorch. So I ran the following command

`pip install xformers==0.0.23.dev650`
It worked for me. In the future, if anyone encounters this error, please upgrade your xformers to the latest version! Good luck <3
