### ISSUE TITLE
(ERROR v21.5.1) ImportError: DLL load failed while importing _C: The specified module could not be found.

### ISSUE THREAD

**Issue by YKefasu** [bmaltais/kohya_ss#593]
```
Traceback (most recent call last):
  File "C:\Users\yosia\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\yosia\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\yosia\AppData\Local\Programs\Python\Python310\Scripts\accelerate.exe\__main__.py", line 4, in <module>
  File "C:\Users\yosia\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "C:\Users\yosia\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\accelerator.py", line 25, in <module>
    import torch
  File "C:\Users\yosia\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\__init__.py", line 218, in <module>
    from torch._C import *  # noqa: F403
ImportError: DLL load failed while importing _C: The specified module could not be found.
```
error after update to v21.5.1

**Comment by Mozoloa** [comment]
I have basically the same problem, dunno why, from withing a clean conda env

```Ps
(khoya) PS G:\AI\Training\kohya_ss> .\setup.bat
Error: Command '['G:\\AI\\Training\\kohya_ss\\venv\\Scripts\\python.exe', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
'.\venv\Scripts\activate.bat' is not recognized as an internal or external command,
operable program or batch file.
Do you want to uninstall previous versions of torch and associated files before installing? Usefull if you are upgrading from torch 1.12.1 to torch 2.0.0 or if you are downgrading from torch 2.0.0 to torch 1.12.1.
[1] - Yes
[2] - No (recommanded for most)
Enter your choice (1 or 2): 1
Traceback (most recent call last):
  File "C:\Users\Emperor\miniconda3\envs\khoya\Scripts\pip-script.py", line 5, in <module>
    from pip._internal.cli.main import main
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\utils\logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\utils\misc.py", line 44, in <module>
    from pip._internal.locations import get_major_minor_version
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\locations\__init__.py", line 14, in <module>
    from . import _sysconfig
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\locations\_sysconfig.py", line 11, in <module>
    from .base import change_root, get_major_minor_version, is_osx_framework
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\locations\base.py", line 9, in <module>
    from pip._internal.utils import appdirs
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\utils\appdirs.py", line 13, in <module>
    from pip._vendor import platformdirs as _appdirs
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 43, in <module>
    PlatformDirs = _set_platform_dir_class()  #: Currently active platform
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 23, in _set_platform_dir_class
    from pip._vendor.platformdirs.windows import Windows as Result
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_vendor\platformdirs\windows.py", line 3, in <module>
    import ctypes
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\ctypes\__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed while importing _ctypes: The specified module could not be found.
Traceback (most recent call last):
  File "C:\Users\Emperor\miniconda3\envs\khoya\Scripts\pip-script.py", line 5, in <module>
    from pip._internal.cli.main import main
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\utils\logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\utils\misc.py", line 44, in <module>
    from pip._internal.locations import get_major_minor_version
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\locations\__init__.py", line 14, in <module>
    from . import _sysconfig
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\locations\_sysconfig.py", line 11, in <module>
    from .base import change_root, get_major_minor_version, is_osx_framework
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\locations\base.py", line 9, in <module>
    from pip._internal.utils import appdirs
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_internal\utils\appdirs.py", line 13, in <module>
    from pip._vendor import platformdirs as _appdirs
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 43, in <module>
    PlatformDirs = _set_platform_dir_class()  #: Currently active platform
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 23, in _set_platform_dir_class
    from pip._vendor.platformdirs.windows import Windows as Result
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\site-packages\pip\_vendor\platformdirs\windows.py", line 3, in <module>
    import ctypes
  File "C:\Users\Emperor\miniconda3\envs\khoya\lib\ctypes\__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed while importing _ctypes: The specified module could not be found.
```
