### ISSUE TITLE
Error while downloading pytorch_model.bin 

### ISSUE THREAD

**Issue by Timellie** [bmaltais/kohya_ss#599]
_Hello,
The installation was fine, however when I begin to train lora, I get an error.
Setup is fine everything matching and looking like this:_

[Dataset 0]
loading image sizes.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 265/265 [00:00<00:00, 9129.44it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 512), count: 25400
mean ar error (without repeats): 0.0
prepare accelerator
Using accelerator 0.15.0 or above.
load StableDiffusion checkpoint
loading u-net:
loading vae:

_But then a big 1.71GB file begins downloading and always crashing_

Downloading pytorch_model.bin:  11%|████████████████▉                                                                                                                                         | 189M/1.71G [02:08<11:02, 2.30MB/s]Traceback (most recent call last):
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\urllib3\response.py", line 444, in _error_catcher
    yield
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\urllib3\response.py", line 567, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\urllib3\response.py", line 533, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\tymek\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 465, in read
    s = self.fp.read(amt)
  File "C:\Users\tymek\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\tymek\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\tymek\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\urllib3\response.py", line 628, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\urllib3\response.py", line 566, in read
    with self._error_catcher():
  File "C:\Users\tymek\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\urllib3\response.py", line 449, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\train_network.py", line 752, in <module>
    train(args)
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\train_network.py", line 152, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\library\train_util.py", line 2739, in load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, name_or_path, device)
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\library\model_util.py", line 898, in load_models_from_stable_diffusion_checkpoint
    text_model = CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14").to(device)
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\transformers\modeling_utils.py", line 2222, in from_pretrained
    resolved_archive_file = cached_file(
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\huggingface_hub\file_download.py", line 1326, in hf_hub_download
    http_get(
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\huggingface_hub\file_download.py", line 538, in http_get
    for chunk in r.iter_content(chunk_size=10 * 1024 * 1024):
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\requests\models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.
Downloading pytorch_model.bin:  11%|████████████████▉                                                                                                                                         | 189M/1.71G [02:24<19:21, 1.31MB/s]
Traceback (most recent call last):
  File "C:\Users\tymek\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\tymek\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\tymek\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\tymek\\stable-diffusion-webui\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=C:/Users/tymek/stable-diffusion-webui/models/Stable-diffusion/babes_11.safetensors', '--train_data_dir=C:/Users/tymek/stable-diffusion-webui/Kohya/Lora Training Data/Incase/image', '--resolution=768,768', '--output_dir=C:/Users/tymek/stable-diffusion-webui/Kohya/Lora Training Data/Incase/model', '--logging_dir=C:/Users/tymek/stable-diffusion-webui/Kohya/Lora Training Data/Incase/log', '--network_alpha=1024', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=1024', '--output_name=incase_v1.0.0', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=2540', '--train_batch_size=1', '--max_train_steps=25400', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers']' returned non-zero exit status 1.

_I tried to play with some settings, ensured I have pip and torch up to date and set up kohya_ss once more but cannot resolve the issue._

**Comment by bmaltais** [comment]
Look like something is halting the download. Try again later and see if things work again.

**Comment by bmaltais** [comment]
I wish I could tell you why... I think you are the 1st user reporting this... so it must be specific to your configuration.

**Comment by Timellie** [comment]
Hmm. I get it. I will dig deeper. Do you think it is more likely that it's connected with python config or stable diffusion or hardware or other? Any idea where to look?

**Comment by greg7125** [comment]
> Hmm. I get it. I will dig deeper. Do you think it is more likely that it's connected with python config or stable diffusion or hardware or other? Any idea where to look?

the problem is solved by launching the VPN before downloading the file (reconfiguration of some network settings in your Windows or on the router may also help)

**Comment by bmceachnie** [comment]
Any updates on this?

I have the same problem. The issue seems to be the host of `pytorch_model.bin`, as the download of the  BLIP caption checkpoint from Google servers worked flawlessly. 

Could you please tell me the URL of the files I need to download and where to put them so that I can add them manually?
