### ISSUE TITLE
During the training, the program did not respond for a long time

### ISSUE THREAD

**Issue by MIkoshiPA** [bmaltais/kohya_ss#603]
When I started training, the program would not respond for a long time.  I watched the process, maybe it was PYTHON problem, I reinstalled it, but it still reported the error.

I don't know if it's an error here：
**SyntaxError: invalid character '·' (U+00B7)**

THANK YOU FOR YOUR HELP

accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --enable_bucket --pretrained_model_name_or_path="D:/aiHuihua/Base model/rev12.EzQi.safetensors" --train_data_dir="D:/aiHuihua/Lora_Image_Kai/zhaixishengwu" --resolution=512,512 --output_dir="D:/aiHuihua/Lora_model_ending" --logging_dir="" --network_alpha="128" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=0.5 --unet_lr=1 --network_dim=128 --output_name="zxsw" --lr_scheduler_num_cycles="8" --learning_rate="1" --lr_scheduler="constant_with_warmup" --lr_warmup_steps="154" --train_batch_size="1" --max_train_steps="3080" --save_every_n_epochs="8" --mixed_precision="fp16" --save_precision="fp16" --cache_latents --optimizer_type="Adafactor" --max_data_loader_n_workers="0" --bucket_reso_steps=64 --shuffle_caption --xformers --bucket_no_upscale
Traceback (most recent call last):
  File "D:\aiHuihua\AI folder\kohya_ss\train_network.py", line 18, in <module>
    import library.train_util as train_util
  File "D:\aiHuihua\AI folder\kohya_ss\library\train_util.py", line 75
    <title>sd-scripts/train_util.py at main · kohya-ss/sd-scripts · GitHub</title>
                                            ^
SyntaxError: invalid character '·' (U+00B7)
Traceback (most recent call last):
  File "D:\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\aiHuihua\AI folder\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\aiHuihua\AI folder\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\aiHuihua\AI folder\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\aiHuihua\AI folder\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\aiHuihua\\AI folder\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=D:/aiHuihua/Base model/rev12.EzQi.safetensors', '--train_data_dir=D:/aiHuihua/Lora_Image_Kai/zhaixishengwu', '--resolution=512,512', '--output_dir=D:/aiHuihua/Lora_model_ending', '--logging_dir=', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=0.5', '--unet_lr=1', '--network_dim=128', '--output_name=zxsw', '--lr_scheduler_num_cycles=8', '--learning_rate=1', '--lr_scheduler=constant_with_warmup', '--lr_warmup_steps=154', '--train_batch_size=1', '--max_train_steps=3080', '--save_every_n_epochs=8', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=Adafactor', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--shuffle_caption', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by MIkoshiPA** [comment]
After reinstalling it, it's ready to use

**Comment by MIkoshiPA** [comment]
and i replace python 3.10.9
