### ISSUE TITLE
Train model causes "non-existent: {WindowsPath('/usr/local/cuda/lib64')"

### ISSUE THREAD

**Issue by bigboss97** [bmaltais/kohya_ss#612]
I'm following the tutorial: https://www.youtube.com/watch?v=9MT1n97ITaE
I ran gui.bat and was able to launch http://127.0.0.1:7860/. When I ran Train model I encountered:
```
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
C:\Users\home\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cuda_setup\paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary C:\Users\home\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
Traceback (most recent call last):
  File "E:\bin\LORA_kohya_ss\train_network.py", line 752, in <module>
    train(args)
  File "E:\bin\LORA_kohya_ss\train_network.py", line 225, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "E:\bin\LORA_kohya_ss\library\train_util.py", line 2397, in get_optimizer
    import bitsandbytes as bnb
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\autograd\_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.py", line 41, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.py", line 37, in get_instance
    cls._instance.initialize()
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.py", line 31, in initialize
    self.lib = ct.cdll.LoadLibrary(binary_path)
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'WindowsPath' is not iterable
Traceback (most recent call last):
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
```
'/usr/local/cuda/lib64' looks like a Linux path. Do I have to change it according to my Windows environment?
My CUDA stuff should be available because my automatic1111 is working.

**Comment by bmaltais** [comment]
I have a feeling your card does not support AdamW8bit... Are you using this optimizer? Try using AdamW instead.

**Comment by bigboss97** [comment]
Where can I change that to AdamW? I'm absolutely new in this.

**Comment by bmaltais** [comment]
I is an option in the training parameters called Optimizer. Select AdamW in the drop down.

**Comment by bigboss97** [comment]
Thanks for your help. Looks like it's progressing and has moved to next error:
local variable 'pipe' referenced before assignment
```
Downloading model.safetensors:  49%|████████████████████████                         | 241M/492M [05:34<05:48, 721kB/s]
Downloading pytorch_model.bin:  45%|█████████████████████▉                           | 220M/492M [05:34<06:53, 658kB/s]
Downloading (…)on_pytorch_model.bin:   6%|██▍                                     | 210M/3.44G [05:31<1:25:01, 633kB/s]
Downloading (…)ch_model.safetensors:   4%|█▌                                      | 136M/3.44G [05:29<2:12:53, 414kB/s]
Downloading (…)on_pytorch_model.bin:  41%|█████████████████▌                         | 136M/335M [05:24<07:51, 420kB/s]
Downloading (…)ch_model.safetensors:  41%|█████████████████▌                         | 136M/335M [05:22<07:49, 423kB/s]
Traceback (most recent call last):
  File "E:\bin\LoRA_kohya_ss\train_network.py", line 752, in <module>
    train(args)
  File "E:\bin\LoRA_kohya_ss\train_network.py", line 152, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(
  File "E:\bin\LoRA_kohya_ss\library\train_util.py", line 2749, in load_target_model
    text_encoder = pipe.text_encoder
UnboundLocalError: local variable 'pipe' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\home\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=E:\\work\\gimp\\StableDiffusion\\LoRA\\bigBOSS97\\test\\image', '--resolution=512,512', '--output_dir=E:\\work\\gimp\\StableDiffusion\\LoRA\\bigBOSS97\\test\\model', '--logging_dir=E:\\work\\gimp\\StableDiffusion\\LoRA\\bigBOSS97\\test\\log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=last', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=100', '--train_batch_size=2', '--max_train_steps=1000', '--save_every_n_epochs=1', '--mixed_precision=no', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.
```

**Comment by bmaltais** [comment]
Something is strange with your computer. Never seen those errors before. Must be something specific to your configuration.

**Comment by bingzibaba666** [comment]
I have the same problem.I try  "pip uninstall" and "pip install " many times ,but it still throw the same exception. Then i delete the whole  "kohyb_ss " folder . And git clone again ,setup . Incredibly it can start up successfully.
