### ISSUE TITLE
Error in first training

### ISSUE THREAD

**Issue by plusmmm** [bmaltais/kohya_ss#646]
The following error occurs and training cannot be completed.
--------------------------------------------------------------------
CUDA SETUP: Loading binary D:\KohyaSS230417\sd-scripts\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit AdamW optimizer | {}
override steps. steps for 10 epochs is / 指定エポックまでのステップ数: 200
Traceback (most recent call last):
  File "D:\KohyaSS230417\sd-scripts\train_network.py", line 773, in <module>
    train(args)
  File "D:\KohyaSS230417\sd-scripts\train_network.py", line 268, in train
    unet, text_encoder, network, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
  File "D:\KohyaSS230417\sd-scripts\venv\lib\site-packages\accelerate\accelerator.py", line 876, in prepare
    result = tuple(
  File "D:\KohyaSS230417\sd-scripts\venv\lib\site-packages\accelerate\accelerator.py", line 877, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "D:\KohyaSS230417\sd-scripts\venv\lib\site-packages\accelerate\accelerator.py", line 741, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "D:\KohyaSS230417\sd-scripts\venv\lib\site-packages\accelerate\accelerator.py", line 912, in prepare_model
    model = model.to(self.device)
  File "D:\KohyaSS230417\sd-scripts\venv\lib\site-packages\transformers\modeling_utils.py", line 1749, in to
    return super().to(*args, **kwargs)
  File "D:\KohyaSS230417\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 927, in to
    return self._apply(convert)
  File "D:\KohyaSS230417\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "D:\KohyaSS230417\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "D:\KohyaSS230417\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "D:\KohyaSS230417\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 602, in _apply
    param_applied = fn(param)
  File "D:\KohyaSS230417\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.42 GiB already allocated; 0 bytes free; 3.48 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "C:\Users\padpl\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\padpl\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\KohyaSS230417\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\KohyaSS230417\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\KohyaSS230417\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\KohyaSS230417\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\KohyaSS230417\\sd-scripts\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=C:\\sd.webui\\webui\\models\\Stable-diffusion\\v1-5-pruned-emaonly.safetensors', '--output_dir=D:\\TrainingData\\outputs', '--dataset_config=D:\\TrainingData\\datasetconfig.toml', '--train_batch_size=1', '--max_train_epochs=10', '--resolution=512,512', '--optimizer_type=AdamW8bit', '--learning_rate=1e-4', '--network_dim=128', '--network_alpha=64', '--enable_bucket', '--bucket_no_upscale', '--lr_scheduler=cosine_with_restarts', '--lr_scheduler_num_cycles=4', '--lr_warmup_steps=500', '--keep_tokens=1', '--shuffle_caption', '--caption_dropout_rate=0.05', '--save_model_as=safetensors', '--clip_skip=2', '--seed=42', '--color_aug', '--xformers', '--mixed_precision=fp16', '--network_module=networks.lora', '--persistent_data_loader_workers']' returned non-zero exit status 1.

**Comment by plusmmm** [comment]
I'm using RTX 3050 Laptop GPU.
Insufficient memory?

**Comment by bmaltais** [comment]
It seems like the error is related to CUDA memory allocation. The error message suggests that the script tried to allocate 20.00 MiB of memory, but the GPU had only 0 bytes of free memory available. The total capacity of the GPU is reported as 4.00 GiB, but 3.42 GiB have already been allocated, leaving only 0 bytes free.

4GB is not enough to run kohya_ss. I would say the 12 is a good minimum. Some run it with 8 but it is a stretch.

**Comment by plusmmm** [comment]
Thank you!
I would like to buy rtx4070.
