### ISSUE TITLE
Stable Diffusion "Command returned non-zero exit status 1." Issue

### ISSUE THREAD

**Issue by vitoolr** [bmaltais/kohya_ss#657]
I've been struggling with this issue while trying to create a LoRA for Stable Diffusion. Could anyone help me how to fix it? I've tried a few things but nothing really helped. Thanks!

*Note: the NAME in the folder is to keep a privacy.

Traceback (most recent call last):
  File "E:\IA\Kohya\kohya_ss\train_network.py", line 773, in <module>
    train(args)
  File "E:\IA\Kohya\kohya_ss\train_network.py", line 268, in train
    unet, text_encoder, network, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
  File "E:\IA\Kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 876, in prepare
    result = tuple(
  File "E:\IA\Kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 877, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "E:\IA\Kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 741, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "E:\IA\Kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 912, in prepare_model
    model = model.to(self.device)
  File "E:\IA\Kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 927, in to
    return self._apply(convert)
  File "E:\IA\Kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "E:\IA\Kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "E:\IA\Kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "E:\IA\Kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 602, in _apply
    param_applied = fn(param)
  File "E:\IA\Kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 3.00 GiB total capacity; 2.46 GiB already allocated; 0 bytes free; 2.54 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "C:\Users\vitor\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\vitor\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\IA\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "E:\IA\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "E:\IA\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "E:\IA\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\IA\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=E:/IA/Images/StableDifusion/LoRA/NAME/Selected/Upscale/Embbed/NAME/image', '--resolution=240,240', '--output_dir=E:/IA/Images/StableDifusion/LoRA/NAMEs/Selected/Upscale/Embbed/NAME/model', '--logging_dir=E:/IA/Images/StableDifusion/LoRA/NAME/Selected/Upscale/Embbed/NAME/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=NAME', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=1250', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=SGDNesterov', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by poeticoncept** [comment]
I have the same issue, you manage to fix it? TY!!
