### ISSUE TITLE
Trained LoRA not functioning (not enough values to unpack (expected 2, got 1))

### ISSUE THREAD

**Issue by alternateaccount11111** [bmaltais/kohya_ss#670]
After training a LoRA using Automatic1111's interface on a specific art style, I can't manage to get the LoRA to actually function. When I run a prompt with the LoRA, 
![image](https://user-images.githubusercontent.com/131862529/234526963-d190ff28-4abd-44d0-8944-2fc0a7327332.png)

I don't see any other mentions of the issue except for one or two threads on reddit of which did not provide helpful responses. The only thing I can see being wrong was I downloaded the new version of torch (2.0), but then proceeded to uninstall and revert back to the one that supposedly works (1.12.1)

If anyone has experienced this issue and/or knows a fix or knows what I did wrong, that would be greatly appreciated.

**Comment by marshalleq** [comment]
Because I haven't found it anywhere else, I thought I'd just add an 'I'm getting this too' but actually while attempting to train.  I cut off at the training command below.  The system keeps running but just gets this error and nothing happens.

```
create LoRA for Text Encoder 1:
create LoRA for Text Encoder 2:
create LoRA for Text Encoder: 264 modules.
create LoRA for U-Net: 722 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
use Adafactor optimizer | {'relative_step': True}
relative_step is true / relative_stepがtrueですlearning rate is used as initial_lr / 指定したlearning rateはinitial_lrとして使用されますunet_lr and text_encoder_lr are ignored / unet_lrとtext_encoder_lrは無視されますoverride steps. steps for 30 epochs is / 指定エポックまでのステップ数: 147840
Traceback (most recent call last):
  File "/mnt/ssd2tb_crucial/projects/kohya_ss/./sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "/mnt/ssd2tb_crucial/projects/kohya_ss/train_network.py", line 370, in train
    lr_scheduler = train_util.get_scheduler_fix(args, optimizer, accelerator.num_processes)
  File "/mnt/ssd2tb_crucial/projects/kohya_ss/library/train_util.py", line 3670, in get_scheduler_fix
    key, value = arg.split("=")
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/mnt/ssd2tb_crucial/projects/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/mnt/ssd2tb_crucial/projects/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/mnt/ssd2tb_crucial/projects/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/mnt/ssd2tb_crucial/projects/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/mnt/ssd2tb_crucial/projects/kohya_ss/venv/bin/python', './sdxl_train_network.py',
```
