### ISSUE TITLE
The unexpected situation that occurred may be caused by environment variable configuration issues.

### ISSUE THREAD

**Issue by ColdCodeHah** [bmaltais/kohya_ss#673]
I have successfully installed and run stable-diffusion-webui, but I encountered some issues while trying to install kohya_ss. I am a beginner, please help me resolve this problem. Thank you!

OS:windows 10;
CUDA Version:12.0.

> Do you want to uninstall previous versions of torch and associated files before installing? Usefull if you are upgrading from torch 1.12.1 to torch 2.0.0 or if you are downgrading from torch 2.0.0 to torch 1.12.1.
[1] - Yes
[2] - No (recommanded for most)
Enter your choice (1 or 2): 2
Please choose the version of torch you want to install:
[1] - v1 (torch 1.12.1) (Recommended)
[2] - v2 (torch 2.0.0) (Experimental)
Enter your choice (1 or 2): 1
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
ERROR: Exception:
Traceback (most recent call last):
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in _main
    status = self.run(options, args)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_internal\commands\install.py", line 318, in run
    requirement_set = resolver.resolve(
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 127, in resolve
    result = self._result = resolver.resolve(
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _merge_into_criterion
    if not criterion.candidates:
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 139, in __bool__
    return bool(self._sequence)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in __bool__
    return any(self)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 129, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 30, in _iter_built
    for version, func in infos:
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 269, in iter_index_candidate_infos
    result = self._finder.find_best_candidate(
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_internal\index\package_finder.py", line 879, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_internal\index\package_finder.py", line 824, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_internal\index\sources.py", line 134, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_internal\index\package_finder.py", line 783, in process_project_url
    html_page = self._link_collector.fetch_page(project_url)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_internal\index\collector.py", line 512, in fetch_page
    return _get_html_page(location, session=self.session)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_internal\index\collector.py", line 422, in _get_html_page
    resp = _get_html_response(url, session=session)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_internal\index\collector.py", line 120, in _get_html_response
    resp = session.get(
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_internal\network\session.py", line 449, in request
    return super().request(method, url, *args, **kwargs)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_vendor\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_vendor\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_vendor\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "d:\stable-diffusion\kohya_ss\venv\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python39\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname
Ignoring gradio: markers 'sys_platform == "darwin"' don't match your environment
Ignoring tensorboard: markers 'sys_platform == "darwin"' don't match your environment
Ignoring huggingface-hub: markers 'sys_platform == "darwin"' don't match your environment
Processing d:\stable-diffusion\kohya_ss
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 2:
   command: 'd:\stable-diffusion\kohya_ss\venv\scripts\python.exe' 'C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip' install --ignore-installed --no-user --prefix 'C:\Users\24496\AppData\Local\Temp\pip-build-env-febx9ste\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (69 lines):
  ERROR: Exception:
  Traceback (most recent call last):
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_internal\cli\base_command.py", line 180, in _main
      status = self.run(options, args)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_internal\cli\req_command.py", line 205, in wrapper
      return func(self, options, args)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_internal\commands\install.py", line 318, in run
      requirement_set = resolver.resolve(
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_internal\resolution\resolvelib\resolver.py", line 127, in resolve
      result = self._result = resolver.resolve(
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_vendor\resolvelib\resolvers.py", line 473, in resolve
      state = resolution.resolve(requirements, max_rounds=max_rounds)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
      name, crit = self._merge_into_criterion(r, parent=None)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_vendor\resolvelib\resolvers.py", line 172, in _merge_into_criterion
      if not criterion.candidates:
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_vendor\resolvelib\structs.py", line 139, in __bool__
      return bool(self._sequence)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in __bool__
      return any(self)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_internal\resolution\resolvelib\found_candidates.py", line 129, in <genexpr>
      return (c for c in iterator if id(c) not in self._incompatible_ids)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_internal\resolution\resolvelib\found_candidates.py", line 30, in _iter_built
      for version, func in infos:
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_internal\resolution\resolvelib\factory.py", line 269, in iter_index_candidate_infos
      result = self._finder.find_best_candidate(
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_internal\index\package_finder.py", line 879, in find_best_candidate
      candidates = self.find_all_candidates(project_name)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_internal\index\package_finder.py", line 824, in find_all_candidates
      page_candidates = list(page_candidates_it)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_internal\index\sources.py", line 134, in page_candidates
      yield from self._candidates_from_page(self._link)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_internal\index\package_finder.py", line 783, in process_project_url
      html_page = self._link_collector.fetch_page(project_url)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_internal\index\collector.py", line 512, in fetch_page
      return _get_html_page(location, session=self.session)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_internal\index\collector.py", line 422, in _get_html_page
      resp = _get_html_response(url, session=session)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_internal\index\collector.py", line 120, in _get_html_response
      resp = session.get(
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_vendor\requests\sessions.py", line 555, in get
      return self.request('GET', url, **kwargs)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_internal\network\session.py", line 449, in request
      return super().request(method, url, *args, **kwargs)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_vendor\requests\sessions.py", line 542, in request
      resp = self.send(prep, **send_kwargs)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_vendor\requests\sessions.py", line 655, in send
      r = adapter.send(request, **kwargs)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_vendor\cachecontrol\adapter.py", line 53, in send
      resp = super(CacheControlAdapter, self).send(request, **kw)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_vendor\requests\adapters.py", line 439, in send
      resp = conn.urlopen(
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_vendor\urllib3\connectionpool.py", line 696, in urlopen
      self._prepare_proxy(conn)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_vendor\urllib3\connectionpool.py", line 964, in _prepare_proxy
      conn.connect()
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_vendor\urllib3\connection.py", line 359, in connect
      conn = self._connect_tls_proxy(hostname, conn)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_vendor\urllib3\connection.py", line 500, in _connect_tls_proxy
      return ssl_wrap_socket(
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_vendor\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
      ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
    File "C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip\_vendor\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
      return ssl_context.wrap_socket(sock)
    File "C:\Python39\lib\ssl.py", line 500, in wrap_socket
      return self.sslsocket_class._create(
    File "C:\Python39\lib\ssl.py", line 997, in _create
      raise ValueError("check_hostname requires server_hostname")
  ValueError: check_hostname requires server_hostname
  ----------------------------------------
WARNING: Discarding file:///D:/stable-diffusion/kohya_ss. Command errored out with exit status 2: 'd:\stable-diffusion\kohya_ss\venv\scripts\python.exe' 'C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip' install --ignore-installed --no-user --prefix 'C:\Users\24496\AppData\Local\Temp\pip-build-env-febx9ste\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
ERROR: Command errored out with exit status 2: 'd:\stable-diffusion\kohya_ss\venv\scripts\python.exe' 'C:\Users\24496\AppData\Local\Temp\pip-standalone-pip-yy3q41ys\__env_pip__.zip\pip' install --ignore-installed --no-user --prefix 'C:\Users\24496\AppData\Local\Temp\pip-build-env-febx9ste\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
ERROR: xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.
.\bitsandbytes_windows\libbitsandbytes_cpu.dll
The system cannot find the specified path。
.\bitsandbytes_windows\libbitsandbytes_cuda116.dll
The system cannot find the specified path。
0 files copied。
The system cannot find the specified path。
0 files copied。
The system cannot find the specified path。
0 files copied。
'accelerate' is not an internal or external command, nor is it a runnable program or batch file.

**Comment by kieranxsomer** [comment]
Because this isn't a A1111 extension? XD
