### ISSUE TITLE
"slow_conv2d_cpu" not implemented for 'Half' AND returned non-zero exit status 1.

### ISSUE THREAD

**Issue by NaughtDZ** [bmaltais/kohya_ss#69]
Traceback (most recent call last):
  File "I:\kohya_ss\train_network.py", line 462, in <module>
    train(args)
  File "I:\kohya_ss\train_network.py", line 94, in train
    train_dataset.cache_latents(vae)
  File "I:\kohya_ss\library\train_util.py", line 285, in cache_latents
    info.latents = vae.encode(img_tensor).latent_dist.sample().squeeze(0).to("cpu")
  File "I:\kohya_ss\venv\lib\site-packages\diffusers\models\vae.py", line 566, in encode
    h = self.encoder(x)
  File "I:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "I:\kohya_ss\venv\lib\site-packages\diffusers\models\vae.py", line 130, in forward
    sample = self.conv_in(sample)
  File "I:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "I:\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "I:\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
Traceback (most recent call last):
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "I:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "I:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "I:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "I:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['I:\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--v_parameterization', '--enable_bucket', '--pretrained_model_name_or_path=I:\\stable-diffusion-webui\\models\\Stable-diffusion\\anything-v4.5-pruned.ckpt', '--train_data_dir=H:\\SD-GUI-1.5.0\\abmayo_MIKU\\LoRA\\pre\\img', '--reg_data_dir=H:\\SD-GUI-1.5.0\\abmayo_MIKU\\LoRA\\pre\\reg', '--resolution=512,512', '--output_dir=H:\\SD-GUI-1.5.0\\abmayo_MIKU\\LoRA\\pre\\model', '--logging_dir=H:\\SD-GUI-1.5.0\\abmayo_MIKU\\LoRA\\pre\\log', '--network_alpha=1', '--save_model_as=ckpt', '--network_module=networks.lora', '--text_encoder_lr=1.5e-5', '--unet_lr=1.5e-4', '--network_dim=128', '--output_name=abmk', '--learning_rate=1e-5', '--lr_scheduler=constant_with_warmup', '--lr_warmup_steps=200', '--train_batch_size=1', '--max_train_steps=2000', '--save_every_n_epochs=5', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--cache_latents', '--clip_skip=2', '--shuffle_caption', '--xformers', '--use_8bit_adam']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
It is quite possible this is a but with the new TI trainer code of kohya. Take note of the command used by the GUI and the error and open an issue on kohya's repo. I don't think this one is related to the GUI:

https://github.com/kohya-ss/sd-scripts/issues
