### ISSUE TITLE
Error with WD14 captioning

### ISSUE THREAD

**Issue by Coiler12** [bmaltais/kohya_ss#700]
Might be similar to [this issue ](https://github.com/bmaltais/kohya_ss/issues/188), but thought I'd report it anyway. Attempting to caption a folder with WD14 does nothing and leads to this error. New and not the most technically astute so I don't know what the main issue is-it could just be an issue I had with setting it up. Have the latest Visual C++ Redists installed. 

Captioning files in C:/Users/UnLoc/OneDrive/Desktop/LimstellaDS...
accelerate launch "./finetune/tag_images_by_wd14_tagger.py" --batch_size="3" --thresh="0.35" --caption_extension=".txt" "C:/Users/UnLoc/OneDrive/Desktop/LimstellaDS"
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
2023-05-01 20:05:11.482622: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-05-01 20:05:11.482994: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
using existing wd14 tagger model
2023-05-01 20:05:17.240496: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "C:\Users\UnLoc\kohya_ss\finetune\tag_images_by_wd14_tagger.py", line 298, in <module>
    main(args)
  File "C:\Users\UnLoc\kohya_ss\finetune\tag_images_by_wd14_tagger.py", line 99, in main
    model = load_model(args.model_dir)
  File "C:\Users\UnLoc\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\UnLoc\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\eager\context.py", line 622, in ensure_initialized
    context_handle = pywrap_tfe.TFE_NewContext(opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: cudaGetErrorString symbol not found.
Traceback (most recent call last):
  File "C:\Users\UnLoc\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\UnLoc\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\UnLoc\AppData\Local\Programs\Python\Python310\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\UnLoc\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\UnLoc\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\UnLoc\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\UnLoc\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', './finetune/tag_images_by_wd14_tagger.py', '--batch_size=3', '--thresh=0.35', '--caption_extension=.txt', 'C:/Users/UnLoc/OneDrive/Desktop/LimstellaDS']' returned non-zero exit status 1.
...captioning done

**Comment by bmaltais** [comment]
Are you running the GUI using gui.ps1 or gui.bat? THe accelerate values should have been configured when the setup.bat was ran.

**Comment by Coiler12** [comment]
> Are you running the GUI using gui.ps1 or gui.bat? THe accelerate values should have been configured when the setup.bat was ran.

Gui.bat. I may have just installed the program wrong.

**Comment by bmaltais** [comment]
I suggest you delete the kohya_ss folder, clone it from github then re-run setup.bat to set things up.

But before you do, check if you have python modules installed globally. Those can wreck havoc with venv if they supperceed the selected python module for the venv.

Run `pip freeze` and see if there are a lot of modules listed. If there are you may want to uninstall all of them before proceeding with .\setup.exe

**Comment by Coiler12** [comment]
Deleted the folder, ran the pip freeze uninstall cleanup (which did remove a lot of things), and reinstalled. Now it works fine.
