### ISSUE TITLE
Someone get it running on vast.ai?

### ISSUE THREAD

**Issue by 15ky3** [bmaltais/kohya_ss#713]
Hi, tried several machines with several images on vast.ai and didn’t get this running. Has someone an idea?

**Comment by bmaltais** [comment]
@jstayco has been doing hard worn on a new installer that I think might help with the task: https://github.com/bmaltais/kohya_ss/pull/680

I will let him chime in on the subject...

**Comment by 15ky3** [comment]
Oh that sounds nice, so let me know when the beta comes out and I will test it 👍

**Comment by jstayco** [comment]
How are you trying to run it in on vast.ai? Linux VMs? OCI Container?

**Comment by 15ky3** [comment]
That’s a docker container and you can choose the base image for example stable diffusion (it’s the automatic1111 gui which runs perfect) or pytorch. Have tryed these two images and none work. I can’t start training, the gui runs fine.

**Comment by jstayco** [comment]
Understood. I think I'll change the --runpod switch to something more generic, as it doesn't make sense to support one singular cloud platform provider. I think this new installer will be much better for you. It can log all the details of the install and log errors of kohya_gui.py starting up, so if you run into more issues the log or some error output on the console should help there.

**Comment by OClement** [comment]
I'm here for the "same reason" but maybe not the same reasons as OP (there's not much details to work with)

I managed to have it run on Vast.ai using the pytorch docker image; I can run the GUI but running BlipCaption or training  fails (trying Dreambooth Lora).

I cloned the repo, created a VENV (within the cloned repo folder) and ran `setup.sh` IIRC. There was a few errors regarding package conflicts that I fixed by manually installing the mentioned packages. I may have needed to run `pip install --force-reinstall`, can't quite recall. I'm not well versed in Python so I tried everything I could find.



When trying to use Blip Captioning:
```
Captioning files in /workspace/mltplprdx/Process lora/MLTPLPRDX LORA/image/...
python3 "finetune/make_captions.py" --batch_size="1" --num_beams="1" --top_p="0.9" --max_length="75" --min_length="5" --beam_search --caption_extension=".txt" "/workspace/mltplprdx/Process lora/MLTPLPRDX LORA/image/" --caption_weights="https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth"
2023-05-05 21:02:33.993275: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-05 21:02:34.154389: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-05-05 21:02:34.824195: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-05-05 21:02:34.824303: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-05-05 21:02:34.824326: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /workspace/kohya_ss/venv/lib/python3.10/site-packages/xformers/_C.so)
WARNING:root:WARNING: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /workspace/kohya_ss/venv/lib/python3.10/site-packages/xformers/_C.so)
Need to compile C++ extensions to get sparse attention suport. Please run python setup.py build develop
Traceback (most recent call last):
  File "/workspace/kohya_ss/finetune/make_captions.py", line 15, in <module>
    import library.train_util as train_util
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/library/train_util.py", line 56, in <module>
    import albumentations as albu
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/albumentations/__init__.py", line 5, in <module>
    from .augmentations import *
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/albumentations/augmentations/__init__.py", line 2, in <module>
    from .blur.functional import *
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/albumentations/augmentations/blur/__init__.py", line 1, in <module>
    from .functional import *
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/albumentations/augmentations/blur/functional.py", line 5, in <module>
    import cv2
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
...captioning done
```

When trying to run the training itself:
```
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/workspace/kohya_ss/lora_gui.py", line 415, in train_model
    msgbox('Image folder does not exist')
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/derived_boxes.py", line 230, in msgbox
    return buttonbox(msg=msg,
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 95, in buttonbox
    bb = ButtonBox(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 147, in __init__
    self.ui = GUItk(msg, title, choices, images, default_choice, cancel_choice, self.callback_ui)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 263, in __init__
    self.boxRoot = tk.Tk()
  File "/opt/conda/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```


As the error suggests, there is no exported Env Var with the name $DISPLAY that `tkinter` is looking for. Bit of googling made me try to `export DISPLAY=:0` but then the error is `Could not connect to display :0`
More googling led me to see there's an `--inbrowser` flag, that seem to be referenced in the koya code too

So I tried to run `./gui.sh --share --inbrowser` but that didnt work either (same errors as above)

That's as far as I could go, for what it's worth

**Comment by bmaltais** [comment]
Yeah, the TK GUI is called in many places in the code. I never thought it would be used on non windows system... Especially headless. Maybe I will look into adding a --headless flag and add off statements to hold back all TK usage when present... Should prevent those errors.

**Comment by bmaltais** [comment]
@OClement Try the new version I just pushed to the dev branch. Start it with `./gui.sh --headless` and see if this help. It should remove most (if not all) GUI interractions when running headless.

Please let me know if I forgot some...

To use the dev branch simply do:

```
git checkout dev
git pull
./setup.sh
```

**Comment by jstayco** [comment]
I was already going to do a --cloud option to have all the behavior containers need. Could I just do --cloud and on the backend in kohya_gui.py it'll translate that to the headless stuff you need?

**Comment by bmaltais** [comment]
Humm... we shoul go for a single option name... To me headless is more generic and can cover non cloud headless systems... Why not call it --headless?

**Comment by jstayco** [comment]
I'll go for headless to keep it consistent. I'll have to think on how we want to handle PaaS type stuff. We have some very specific runpod code in here and it's clear this project is outgrowing that use case. So my plan was to add a --cloud that did the Nvidia library symlinking stuff we had for runpod. 

Do we want to keep those bits under the --headless switch as well or are we just better off with --cloud for the install stuff and --headless for runtime stuff?

**Comment by jstayco** [comment]
@bmaltais prelim support added on the installer branch for headless option. It currently breaks runtime because I don't have all your headless stuff around, but it's good to the point of passing it to kohya_gui.py.

**Comment by kieranxsomer** [comment]
I'm gonna keep watch on this, because there's stuff i can't do locally AND can't seem to figure out with my non existent brain (yea yea yea) how to piece this into a colab( we know, colab sucks XD i'm limited by only a n imac and an old mbp XD) -- Runpod drives me nuts, is vast "VASTLY" better? XD

**Comment by 15ky3** [comment]
So, tryed another few instances to collect the errors.

Here a few examples:
**Running on RTX 3090 with pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime**
Cant start the Gui, following error (this is the only instance where i get this error):
`Traceback (most recent call last):
  File "/workspace/kohya_ss/kohya_gui.py", line 1, in <module>
    import gradio as gr
  File "/opt/conda/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/opt/conda/lib/python3.10/site-packages/gradio/components.py", line 25, in <module>
    import altair as alt
  File "/opt/conda/lib/python3.10/site-packages/altair/__init__.py", line 4, in <module>
    from .vegalite import *
  File "/opt/conda/lib/python3.10/site-packages/altair/vegalite/__init__.py", line 2, in <module>
    from .v4 import *
  File "/opt/conda/lib/python3.10/site-packages/altair/vegalite/v4/__init__.py", line 2, in <module>
    from .schema import *
  File "/opt/conda/lib/python3.10/site-packages/altair/vegalite/v4/schema/__init__.py", line 2, in <module>
    from .core import *
  File "/opt/conda/lib/python3.10/site-packages/altair/vegalite/v4/schema/core.py", line 4, in <module>
    from altair.utils.schemapi import SchemaBase, Undefined, _subclasses
  File "/opt/conda/lib/python3.10/site-packages/altair/utils/__init__.py", line 13, in <module>
    from .html import spec_to_html
  File "/opt/conda/lib/python3.10/site-packages/altair/utils/html.py", line 2, in <module>
    import jinja2
  File "/opt/conda/lib/python3.10/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/opt/conda/lib/python3.10/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/opt/conda/lib/python3.10/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/opt/conda/lib/python3.10/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/conda/lib/python3.10/site-packages/markupsafe/__init__.py)
`
**Running on RTX 3090 with tensorflow/tensorflow:latest-gpu**
This error i get on many other instances, like pytorch, tensorflow, cuda etc. Its allways the same Error when i start the Training.
`Folder 100_vik: 14 images found
Folder 100_vik: 1400 steps
max_train_steps = 1400
stop_text_encoder_training = 0
lr_warmup_steps = 140
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --enable_bucket --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" --train_data_dir="/root/pic/image" --resolution=512,512 --output_dir="/root/pic/model" --logging_dir="/root/pic/log" --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-05 --unet_lr=0.0001 --network_dim=8 --output_name="last" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="cosine" --lr_warmup_steps="140" --train_batch_size="1" --max_train_steps="1400" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --cache_latents --optimizer_type="AdamW8bit" --max_data_loader_n_workers="0" --bucket_reso_steps=64 --xformers --bucket_no_upscale --noise_offset=0.0
2023-05-06 09:22:48.043007: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-06 09:22:48.237777: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-05-06 09:22:48.827404: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-05-06 09:22:48.827496: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-05-06 09:22:48.827509: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
2023-05-06 09:22:51.178594: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-05-06 09:22:51.741611: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-05-06 09:22:51.741680: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-05-06 09:22:51.741697: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "train_network.py", line 17, in <module>
    import library.train_util as train_util
  File "/root/kohya_ss/library/train_util.py", line 56, in <module>
    import albumentations as albu
  File "/usr/local/lib/python3.8/dist-packages/albumentations/__init__.py", line 5, in <module>
    from .augmentations import *
  File "/usr/local/lib/python3.8/dist-packages/albumentations/augmentations/__init__.py", line 2, in <module>
    from .blur.functional import *
  File "/usr/local/lib/python3.8/dist-packages/albumentations/augmentations/blur/__init__.py", line 1, in <module>
    from .functional import *
  File "/usr/local/lib/python3.8/dist-packages/albumentations/augmentations/blur/functional.py", line 5, in <module>
    import cv2
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 923, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=/root/pic/image', '--resolution=512,512', '--output_dir=/root/pic/model', '--logging_dir=/root/pic/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=8', '--output_name=last', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=140', '--train_batch_size=1', '--max_train_steps=1400', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.`

**Comment by bmaltais** [comment]
Wish I could help troubleshoot those but I don't run linux

**Comment by 15ky3** [comment]
Finaly, got it running.

Here are my steps:
Used a machine with a RTX3090 and image: pytorch/pytorch_2.0.0-cuda11.7-cudnn8-runtime

Then git clone the repo and install normally via setup.sh
Installed xformers via` pip install xformers==0.0.19`

Then execute `cp $(ls /opt/conda/lib/python3.10/site-packages/bitsandbytes/*cuda*.so | grep -v nocublaslt | tail -1) /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
` as mentioned [here](https://github.com/oobabooga/text-generation-webui/discussions/528) 
Then execute `export LD_LIBRARY_PATH=/opt/conda/lib:$LD_LIBRARY_PATH
`
And finaly disable the checks in the gui.sh because xformers==0.0.19 installs pytorch 2.0 etc and the script is not happy with it.

My gui.sh script lokks:
`#!/usr/bin/env bash

# This gets the directory the script is run from so pathing can work relative to the script where needed.
SCRIPT_DIR=$(cd -- "$(dirname -- "$0")" && pwd)

# Step into GUI local directory
cd "$SCRIPT_DIR"

# Activate the virtual environment
source "$SCRIPT_DIR/venv/bin/activate"

# If the requirements are validated, run the kohya_gui.py script with the command-line arguments
#if python  "$SCRIPT_DIR"/tools/validate_requirements.py -r "$SCRIPT_DIR"/requirements.txt; then
python "$SCRIPT_DIR/kohya_gui.py" "$@"
#fi`

**Comment by kieranxsomer** [comment]
*cries in just saw this now* Ok so i'll have to see how this works more, because 'im on vast and MOST OF THE INSTALL WORKS but i'm currently having this issue: 
https://github.com/bmaltais/kohya_ss/issues/419

XD I got it to caption A OK, I went to go do the copy to folders it was A OK - but went to do Dataset prep and this is the same error as I got. 

I'm on vast, and yea i'm on an RTX 3090, usually runs sweet for Automatic, maybe i need to reinstall of course :3 that wont' be difficult lol... 

If i struggle still i'll report!
