### ISSUE TITLE
Key Error for key "encoder.conv_in.weight" while loading VAE

### ISSUE THREAD

**Issue by chetankumar** [bmaltais/kohya_ss#721]
I'm trying out the lora training. I tried with 1 model, which ran fine. 
Now when I try with the model: Realistic Vision V2.0, I'm getting an key error during the vae loading phase.

https://civitai.com/models/4201/realistic-vision-v20

### Command:
----------------------------------------------------
Folder 100_test: 11 images found
Folder 100_test: 1100 steps
max_train_steps = 1100
stop_text_encoder_training = 0
lr_warmup_steps = 110
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --enable_bucket --pretrained_model_name_or_path="D:/Playground/StableDiffusion/stable-diffusion-webui/models/Stable-diffusion/Realistic_Vision_V1.4-pruned-fp16.safetensors" --train_data_dir="D:/Playground/StableDiffusion/lora-training/chetan/image" --resolution=512,512 --output_dir="D:/Playground/StableDiffusion/lora-training/chetan/model" --logging_dir="D:/Playground/StableDiffusion/lora-training/chetan/log" --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-05 --unet_lr=0.0001 --network_dim=8 --output_name="last" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="cosine" --lr_warmup_steps="110" --train_batch_size="1" --max_train_steps="1100" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --cache_latents --optimizer_type="AdamW8bit" --max_data_loader_n_workers="0" --bucket_reso_steps=64 --mem_eff_attn --gradient_checkpointing --xformers --bucket_no_upscale --noise_offset=0.0

### Error
------------------
loading u-net: <All keys matched successfully>
Traceback (most recent call last):
  File "D:\Playground\StableDiffusion\kohya_ss\train_network.py", line 773, in <module>
    train(args)
  File "D:\Playground\StableDiffusion\kohya_ss\train_network.py", line 146, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "D:\Playground\StableDiffusion\kohya_ss\library\train_util.py", line 2928, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "D:\Playground\StableDiffusion\kohya_ss\library\train_util.py", line 2894, in _load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, name_or_path, device)
  File "D:\Playground\StableDiffusion\kohya_ss\library\model_util.py", line 868, in load_models_from_stable_diffusion_checkpoint
    converted_vae_checkpoint = convert_ldm_vae_checkpoint(state_dict, vae_config)
  File "D:\Playground\StableDiffusion\kohya_ss\library\model_util.py", line 384, in convert_ldm_vae_checkpoint
    new_checkpoint["encoder.conv_in.weight"] = vae_state_dict["encoder.conv_in.weight"]
KeyError: 'encoder.conv_in.weight'
Traceback (most recent call last):
  File "C:\Users\cheta\.conda\envs\kohya\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\cheta\.conda\envs\kohya\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\cheta\.conda\envs\kohya\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\cheta\.conda\envs\kohya\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\cheta\.conda\envs\kohya\lib\site-packages\accelerate\commands\launch.py", line 923, in launch_command
    simple_launcher(args)
  File "C:\Users\cheta\.conda\envs\kohya\lib\site-packages\accelerate\commands\launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

### Code that is failing
------------------------------
Method: def convert_ldm_vae_checkpoint(checkpoint, config):
Line 384: new_checkpoint["encoder.conv_in.weight"] = vae_state_dict["encoder.conv_in.weight"]

**Comment by bmaltais** [comment]
This is something that would need to be investigated by kohya on his repo where he publish the training code: https://github.com/kohya-ss/sd-scripts
