### ISSUE TITLE
Installation error: [WinError 126] The specified module could not be found. \torch\lib\caffe2_nvrtc.dll or one of its dependencies.

### ISSUE THREAD

**Issue by srbustdown** [bmaltais/kohya_ss#732]
Windows 10
Python 3.10.10
RTX 4090
Installed CUDA toolkit 12.1

Steps to reproduce:
1. Clone this repo
2. Run setup.bat
3. Error observed: 

`OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\h1dde\Downloads\kohya_ss\venv\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.`

Rerunning the setup multiple times results in the same error. 
Selecting uninstall previous versions of torch also results in the same error.
Running the above commands in different directories did not work.
Tried running gui.bat despite the errors to see what the result would be, when printing the training command I see the same error as above.

Please let me know what additional information is required.

Log shortened to fit comment limit:
```
Warning: Python version 3.10.9 is recommended.
venv folder already exists, skipping creation...
Do you want to uninstall previous versions of torch and associated files before installing? Usefull if you are upgrading from torch 1.12.1 to torch 2.0.0 or if you are downgrading from torch 2.0.0 to torch 1.12.1.
[1] - Yes
[2] - No (recommanded for most)
Enter your choice (1 or 2): 2
Please choose the version of torch you want to install:
[1] - v1 (torch 1.12.1) (Recommended)
[2] - v2 (torch 2.0.0) (Experimental)
Enter your choice (1 or 2): 2
Found existing installation: bitsandbytes 0.35.0
Uninstalling bitsandbytes-0.35.0:
  Successfully uninstalled bitsandbytes-0.35.0
The directory is not empty.
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Collecting torch==2.0.0+cu118
  Using cached https://download.pytorch.org/whl/cu118/torch-2.0.0%2Bcu118-cp310-cp310-win_amd64.whl (2611.3 MB)
Collecting torchvision==0.15.1+cu118
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.15.1%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)

...

Installing collected packages: torch, torchvision
  Attempting uninstall: torch
    Found existing installation: torch 2.0.0
    Uninstalling torch-2.0.0:
      Successfully uninstalled torch-2.0.0
  Rolling back uninstall of torch
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\functorch\
   from C:\Users\h1dde\Downloads\kohya_ss\venv\Lib\site-packages\~unctorch
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch-2.0.0.dist-info\
   from C:\Users\h1dde\Downloads\kohya_ss\venv\Lib\site-packages\~orch-2.0.0.dist-info
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\__config__.py
   from C:\Users\h1dde\AppData\Local\Temp\pip-uninstall-4a7dmwa3\__config__.py
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\__future__.py
   from C:\Users\h1dde\AppData\Local\Temp\pip-uninstall-4a7dmwa3\__future__.py
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\__init__.py
   from C:\Users\h1dde\AppData\Local\Temp\pip-uninstall-4a7dmwa3\__init__.py
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\__pycache__\
   from C:\Users\h1dde\Downloads\kohya_ss\venv\Lib\site-packages\torch\~_pycache__
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_appdirs.py
   from C:\Users\h1dde\AppData\Local\Temp\pip-uninstall-4a7dmwa3\_appdirs.py
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_awaits\
   from C:\Users\h1dde\Downloads\kohya_ss\venv\Lib\site-packages\torch\~awaits
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_c.cp310-win_amd64.pyd
   from C:\Users\h1dde\AppData\Local\Temp\pip-uninstall-4a7dmwa3\_c.cp310-win_amd64.pyd
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_c\
   from C:\Users\h1dde\Downloads\kohya_ss\venv\Lib\site-packages\torch\~c
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_c_flatbuffer.cp310-win_amd64.pyd
   from C:\Users\h1dde\AppData\Local\Temp\pip-uninstall-4a7dmwa3\_c_flatbuffer.cp310-win_amd64.pyd
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_c_flatbuffer\
   from C:\Users\h1dde\Downloads\kohya_ss\venv\Lib\site-packages\torch\~c_flatbuffer
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_classes.py
   from C:\Users\h1dde\AppData\Local\Temp\pip-uninstall-4a7dmwa3\_classes.py
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_decomp\
   from C:\Users\h1dde\Downloads\kohya_ss\venv\Lib\site-packages\torch\~decomp
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_deploy.py
   from C:\Users\h1dde\AppData\Local\Temp\pip-uninstall-4a7dmwa3\_deploy.py
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_dispatch\
   from C:\Users\h1dde\Downloads\kohya_ss\venv\Lib\site-packages\torch\~dispatch
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_dynamo\
   from C:\Users\h1dde\Downloads\kohya_ss\venv\Lib\site-packages\torch\~dynamo
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_export\
   from C:\Users\h1dde\Downloads\kohya_ss\venv\Lib\site-packages\torch\~export
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_functorch\
   from C:\Users\h1dde\Downloads\kohya_ss\venv\Lib\site-packages\torch\~functorch
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_guards.py
   from C:\Users\h1dde\AppData\Local\Temp\pip-uninstall-4a7dmwa3\_guards.py
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_inductor\
   from C:\Users\h1dde\Downloads\kohya_ss\venv\Lib\site-packages\torch\~inductor
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_jit_internal.py
   from C:\Users\h1dde\AppData\Local\Temp\pip-uninstall-4a7dmwa3\_jit_internal.py
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_lazy\
   from C:\Users\h1dde\Downloads\kohya_ss\venv\Lib\site-packages\torch\~lazy
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_linalg_utils.py
   from C:\Users\h1dde\AppData\Local\Temp\pip-uninstall-4a7dmwa3\_linalg_utils.py
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_lobpcg.py
   from C:\Users\h1dde\AppData\Local\Temp\pip-uninstall-4a7dmwa3\_lobpcg.py
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_lowrank.py
   from C:\Users\h1dde\AppData\Local\Temp\pip-uninstall-4a7dmwa3\_lowrank.py
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_meta_registrations.py
   from C:\Users\h1dde\AppData\Local\Temp\pip-uninstall-4a7dmwa3\_meta_registrations.py
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_namedtensor_internals.py
   from C:\Users\h1dde\AppData\Local\Temp\pip-uninstall-4a7dmwa3\_namedtensor_internals.py
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torch\_ops.py
   from C:\Users\h1dde\AppData\Local\Temp\pip-uninstall-4a7dmwa3\_ops.py
 
...

  Moving to c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages\torchgen\
   from C:\Users\h1dde\Downloads\kohya_ss\venv\Lib\site-packages\~orchgen
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\scripts\convert-caffe2-to-onnx.exe
   from C:\Users\h1dde\AppData\Local\Temp\pip-uninstall-oxz68mbk\convert-caffe2-to-onnx.exe
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\scripts\convert-onnx-to-caffe2.exe
   from C:\Users\h1dde\AppData\Local\Temp\pip-uninstall-oxz68mbk\convert-onnx-to-caffe2.exe
  Moving to c:\users\h1dde\downloads\kohya_ss\venv\scripts\torchrun.exe
   from C:\Users\h1dde\AppData\Local\Temp\pip-uninstall-oxz68mbk\torchrun.exe
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\h1dde\Downloads\kohya_ss\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\h1dde\Downloads\kohya_ss\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\Users\h1dde\Downloads\kohya_ss\venv\lib\site-packages\pip\_internal\commands\install.py", line 494, in run
    installed = install_given_reqs(
  File "C:\Users\h1dde\Downloads\kohya_ss\venv\lib\site-packages\pip\_internal\req\__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "C:\Users\h1dde\Downloads\kohya_ss\venv\lib\site-packages\pip\_internal\req\req_install.py", line 792, in install
    install_wheel(
  File "C:\Users\h1dde\Downloads\kohya_ss\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 729, in install_wheel
    _install_wheel(
  File "C:\Users\h1dde\Downloads\kohya_ss\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 589, in _install_wheel
    file.save()
  File "C:\Users\h1dde\Downloads\kohya_ss\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 388, in save
    shutil.copyfileobj(f, dest)
  File "C:\Users\h1dde\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 195, in copyfileobj
    buf = fsrc_read(length)
  File "C:\Users\h1dde\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 925, in read
    data = self._read1(n)
  File "C:\Users\h1dde\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1015, in _read1
    self._update_crc(data)
  File "C:\Users\h1dde\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 943, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'torch/lib/cublas64_11.dll'

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Ignoring bitsandbytes: markers 'sys_platform == "darwin" or sys_platform == "linux"' don't match your environment
Ignoring gradio: markers 'sys_platform == "darwin"' don't match your environment
Ignoring tensorboard: markers 'sys_platform == "darwin"' don't match your environment
Ignoring huggingface-hub: markers 'sys_platform == "darwin"' don't match your environment
Processing c:\users\h1dde\downloads\kohya_ss
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: accelerate==0.18.0 in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from -r requirements.txt (line 2)) (0.18.0)
Requirement already satisfied: albumentations==1.3.0 in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from -r requirements.txt (line 3)) (1.3.0)
Requirement already satisfied: altair==4.2.2 in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from -r requirements.txt (line 4)) (4.2.2)
Collecting bitsandbytes==0.35.0
  Using cached bitsandbytes-0.35.0-py3-none-any.whl (62.5 MB)

...

Building wheels for collected packages: library
  Building wheel for library (pyproject.toml) ... done
  Created wheel for library: filename=library-1.0.3-py3-none-any.whl size=110826 sha256=55e51bd36f920359000388f671a5f7ed0132e3930c93474623ea48baa62835dd
  Stored in directory: C:\Users\h1dde\AppData\Local\Temp\pip-ephem-wheel-cache-5wyzz31v\wheels\9d\c2\7f\8a6ca04916f562cb03fcb980620651fb6b8eb1aeefd421b902
Successfully built library
Installing collected packages: library, bitsandbytes
  Attempting uninstall: library
    Found existing installation: library 1.0.3
    Uninstalling library-1.0.3:
      Successfully uninstalled library-1.0.3
Successfully installed bitsandbytes-0.35.0 library-1.0.3

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Requirement already satisfied: xformers==0.0.17 in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (0.0.17)
Requirement already satisfied: pyre-extensions==0.0.23 in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from xformers==0.0.17) (0.0.23)
Requirement already satisfied: torch==2.0.0 in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from xformers==0.0.17) (2.0.0)
Requirement already satisfied: numpy in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from xformers==0.0.17) (1.24.3)
Requirement already satisfied: typing-inspect in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from pyre-extensions==0.0.23->xformers==0.0.17) (0.8.0)
Requirement already satisfied: typing-extensions in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from pyre-extensions==0.0.23->xformers==0.0.17) (4.5.0)
Requirement already satisfied: filelock in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from torch==2.0.0->xformers==0.0.17) (3.12.0)
Requirement already satisfied: networkx in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from torch==2.0.0->xformers==0.0.17) (3.1)
Requirement already satisfied: sympy in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from torch==2.0.0->xformers==0.0.17) (1.11.1)
Requirement already satisfied: jinja2 in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from torch==2.0.0->xformers==0.0.17) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from jinja2->torch==2.0.0->xformers==0.0.17) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from sympy->torch==2.0.0->xformers==0.0.17) (1.3.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from typing-inspect->pyre-extensions==0.0.23->xformers==0.0.17) (1.0.0)

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Collecting triton==2.0.0
  Downloading https://huggingface.co/r4ziel/xformers_pre_built/resolve/main/triton-2.0.0-cp310-cp310-win_amd64.whl (12.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.6/12.6 MB 81.8 MB/s eta 0:00:00
Requirement already satisfied: cmake in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from triton==2.0.0) (3.26.3)
Requirement already satisfied: filelock in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from triton==2.0.0) (3.12.0)
Requirement already satisfied: torch in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from triton==2.0.0) (2.0.0)
Requirement already satisfied: networkx in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from torch->triton==2.0.0) (3.1)
Requirement already satisfied: jinja2 in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from torch->triton==2.0.0) (3.1.2)
Requirement already satisfied: typing-extensions in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from torch->triton==2.0.0) (4.5.0)
Requirement already satisfied: sympy in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from torch->triton==2.0.0) (1.11.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from jinja2->torch->triton==2.0.0) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in c:\users\h1dde\downloads\kohya_ss\venv\lib\site-packages (from sympy->torch->triton==2.0.0) (1.3.0)

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
.\bitsandbytes_windows\libbitsandbytes_cpu.dll
.\bitsandbytes_windows\libbitsandbytes_cuda116.dll
        2 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
Traceback (most recent call last):
  File "C:\Users\h1dde\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\h1dde\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\h1dde\Downloads\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 4, in <module>
  File "C:\Users\h1dde\Downloads\kohya_ss\venv\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\h1dde\Downloads\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 28, in <module>
    import torch
  File "C:\Users\h1dde\Downloads\kohya_ss\venv\lib\site-packages\torch\__init__.py", line 133, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\h1dde\Downloads\kohya_ss\venv\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.

[process exited with code 1 (0x00000001)]
```

**Comment by srbustdown** [comment]
The issue was caused by this error: 
`zipfile.BadZipFile: Bad CRC-32 for file 'torch/lib/cublas64_11.dll'`

Found the fix here: https://github.com/pytorch/pytorch/issues/40268

I tested the fix by using the `--no-cache` flag when using `pip install`

The change was made in the setup.bat script:

`
pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 --extra-index-url https://download.pytorch.org/whl/cu118 --no-cache
    pip install --use-pep517 --upgrade -r requirements.txt --no-cache
    pip install --upgrade xformers==0.0.17 --no-cache
    rem pip install -U -I --no-deps --no-cache https://files.pythonhosted.org/packages/d6/f7/02662286419a2652c899e2b3d1913c47723fc164b4ac06a85f769c291013/xformers-0.0.17rc482-cp310-cp310-win_amd64.whl
    pip install --no-cache https://huggingface.co/r4ziel/xformers_pre_built/resolve/main/triton-2.0.0-cp310-cp310-win_amd64.whl
`

**Comment by Armorgeddan** [comment]
How exactly do I do pip install when it's run by the setup script?
