### ISSUE TITLE
Training fails after 1000 steps due to RuntimeError: CUDA error: unspecified launch failure

### ISSUE THREAD

**Issue by srbustdown** [bmaltais/kohya_ss#733]
Windows 10
Python 3.10.10
RTX 4090

Usually it fails during epoch 2/4 around step 1100 but this time it failed around 3500 steps on epoch 3/4.

```
steps:  86%|██████████████████████████████████████████████████▊        | 3508/4070 [37:27<06:00,  1.56it/s, loss=0.113]Traceback (most recent call last):
  File "C:\Users\h1dde\Documents\kohya_ss\train_network.py", line 773, in <module>
    train(args)
  File "C:\Users\h1dde\Documents\kohya_ss\train_network.py", line 629, in train
    optimizer.step()
  File "C:\Users\h1dde\Documents\kohya_ss\venv\lib\site-packages\accelerate\optimizer.py", line 136, in step
    scale_after = self.scaler.get_scale()
  File "C:\Users\h1dde\Documents\kohya_ss\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 446, in get_scale
    return self._init_scale if self._scale is None else self._get_scale_async().item()
RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

steps:  86%|██████████████████████████████████████████████████▊        | 3508/4070 [37:28<06:00,  1.56it/s, loss=0.113]
Traceback (most recent call last):
  File "C:\Users\h1dde\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\h1dde\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\h1dde\Documents\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\h1dde\Documents\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\h1dde\Documents\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 923, in launch_command
    simple_launcher(args)
  File "C:\Users\h1dde\Documents\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\h1dde\\Documents\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=C:/Users/h1dde/Documents/Data/SD Models/Base/animefull-final-pruned-fp16.safetensors', '--train_data_dir=C:/Users/h1dde/Documents/Data/SD Training/Futanari/futanarimix/img', '--resolution=800,800', '--output_dir=C:/Users/h1dde/Documents/Data/SD Training/Futanari/futanarimix/out', '--logging_dir=C:/Users/h1dde/Documents/Data/SD Training/Futanari/futanarimix/log', '--network_alpha=24', '--save_model_as=safetensors', '--network_module=lycoris.kohya', '--network_args', 'conv_dim=24', 'conv_alpha=24', 'algo=lora', '--text_encoder_lr=0.5', '--unet_lr=0.5', '--network_dim=24', '--output_name=futanarimix-dim24-alpha24-midLR-ExtraArgs', '--lr_scheduler_num_cycles=4', '--learning_rate=0.5', '--lr_scheduler=cosine', '--lr_warmup_steps=407', '--train_batch_size=4', '--max_train_steps=4070', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=DAdaptation', '--optimizer_args', 'decouple=True', 'weight_decay=0.02', '--max_data_loader_n_workers=0', '--max_token_length=150', '--clip_skip=2', '--keep_tokens=1', '--vae_batch_size=4', '--bucket_reso_steps=64', '--shuffle_caption', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.
```

**Comment by bmaltais** [comment]
Please open an issue directly with kohya_ss about this as it is related to his code.

**Comment by surfingnirvana** [comment]
Was this error fixed?

epoch 13/70
steps:  18%|█████████▊                                            | 507/2800 [15:41<1:10:59,  1.86s/it, avr_loss=0.134]Traceback (most recent call last):
  File "C:\NEURAL\kohya_ss\sd-scripts\sdxl_train_network.py", line 184, in <module>
    trainer.train(args)
  File "C:\NEURAL\kohya_ss\sd-scripts\train_network.py", line 855, in train
    optimizer.step()
  File "C:\NEURAL\kohya_ss\venv\lib\site-packages\accelerate\optimizer.py", line 132, in step
    self.scaler.step(self.optimizer, closure)
  File "C:\NEURAL\kohya_ss\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 416, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "C:\NEURAL\kohya_ss\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 314, in _maybe_opt_step
    if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
  File "C:\NEURAL\kohya_ss\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 314, in <genexpr>
    if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

steps:  18%|█████████▊                                            | 507/2800 [15:43<1:11:06,  1.86s/it, avr_loss=0.134]
Traceback (most recent call last):
  File "C:\Users\Workstation64V1NC\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Workstation64V1NC\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\NEURAL\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\NEURAL\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\NEURAL\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\NEURAL\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command...

... returned non-zero exit status 1.
