### ISSUE TITLE
common_gui needs extra paraenthesis

### ISSUE THREAD

**Issue by wcole3** [bmaltais/kohya_ss#734]
Just a missing set of parenthesis in common_gui.py line 108 for isdigit.  If you have an older config file, you can get an error loading it due to the old noise offset default value being `noise_offset=''`

If you encounter an error like you can manually change the noise offset value to a 0.
```
Traceback (most recent call last):
  File "D:\StableDiff\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\StableDiff\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "D:\StableDiff\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\StableDiff\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\StableDiff\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\StableDiff\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\StableDiff\kohya_ss\lora_gui.py", line 305, in open_configuration
    my_data = update_my_data(my_data)
  File "D:\StableDiff\kohya_ss\library\common_gui.py", line 109, in update_my_data
    my_data[key] = float(value)
ValueError: could not convert string to float: ''
```

**Comment by bmaltais** [comment]
I will try to fix that at load time, thanks for reporting.

**Comment by bmaltais** [comment]
The latest code in master should now have the fix. Thanks!
