### ISSUE TITLE
LoRA Training can't start when HF is down since it tries to access some kind of OpenAI model.

### ISSUE THREAD

**Issue by okageblade** [bmaltais/kohya_ss#746]
LoRA training offline or when HF is down because it tries accessing some kind of OpenAI repo for a model I don't even think exists:

Traceback (most recent call last):
  File "D:\AI\ImageGen Tools\KohyaGUI\kohya_ss\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "D:\AI\ImageGen Tools\KohyaGUI\kohya_ss\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/model.safetensors

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\AI\ImageGen Tools\KohyaGUI\kohya_ss\venv\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "D:\AI\ImageGen Tools\KohyaGUI\kohya_ss\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\AI\ImageGen Tools\KohyaGUI\kohya_ss\venv\lib\site-packages\huggingface_hub\file_download.py", line 1160, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "D:\AI\ImageGen Tools\KohyaGUI\kohya_ss\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\AI\ImageGen Tools\KohyaGUI\kohya_ss\venv\lib\site-packages\huggingface_hub\file_download.py", line 1501, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "D:\AI\ImageGen Tools\KohyaGUI\kohya_ss\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 301, in hf_raise_for_status
    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 502 Server Error: Bad Gateway for url: https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/model.safetensors

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\ImageGen Tools\KohyaGUI\kohya_ss\train_network.py", line 773, in <module>
    train(args)
  File "D:\AI\ImageGen Tools\KohyaGUI\kohya_ss\train_network.py", line 146, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "D:\AI\ImageGen Tools\KohyaGUI\kohya_ss\library\train_util.py", line 2928, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "D:\AI\ImageGen Tools\KohyaGUI\kohya_ss\library\train_util.py", line 2894, in _load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, name_or_path, device)
  File "D:\AI\ImageGen Tools\KohyaGUI\kohya_ss\library\model_util.py", line 904, in load_models_from_stable_diffusion_checkpoint
    text_model = CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14").to(device)
  File "D:\AI\ImageGen Tools\KohyaGUI\kohya_ss\venv\lib\site-packages\transformers\modeling_utils.py", line 2208, in from_pretrained
    resolved_archive_file = cached_file(pretrained_model_name_or_path, filename, **cached_file_kwargs)
  File "D:\AI\ImageGen Tools\KohyaGUI\kohya_ss\venv\lib\site-packages\transformers\utils\hub.py", line 466, in cached_file
    raise EnvironmentError(f"There was a specific connection error when trying to load {path_or_repo_id}:\n{err}")
OSError: There was a specific connection error when trying to load openai/clip-vit-large-patch14:
502 Server Error: Bad Gateway for url: https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/model.safetensors
Traceback (most recent call last):
  File "C:\Users\Rehis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Rehis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\AI\ImageGen Tools\KohyaGUI\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\AI\ImageGen Tools\KohyaGUI\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\AI\ImageGen Tools\KohyaGUI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 923, in launch_command
    simple_launcher(args)
  File "D:\AI\ImageGen Tools\KohyaGUI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

**Comment by arthurb123** [comment]
I fixed this issue by manually downloading the missing model from an older branch located [here](https://huggingface.co/openai/clip-vit-large-patch14/tree/refs%2Fpr%2F5). After downloading the _model.safetensors_ file, place the file in the folder `kohya_ss\venv\Lib\site-packages\transformers\models\openai`. Make sure to rename the file from _model.safetensors_ to _clip-vit-large-patch14.safetensors_ and you should be good to go.
