### ISSUE TITLE
Error for diffusers

### ISSUE THREAD

**Issue by BeautyyuYanli** [bmaltais/kohya_ss#749]
I'm tring to train a Dreambooth LoRA, but encountered the following diffusers error
```
Traceback (most recent call last):
  File "/home/beautyyu/Application/kohya_ss/train_network.py", line 773, in <module>
    train(args)
  File "/home/beautyyu/Application/kohya_ss/train_network.py", line 146, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "/home/beautyyu/Application/kohya_ss/library/train_util.py", line 2928, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "/home/beautyyu/Application/kohya_ss/library/train_util.py", line 2899, in _load_target_model
    pipe = StableDiffusionPipeline.from_pretrained(name_or_path, tokenizer=None, safety_checker=None)
  File "/home/beautyyu/.conda/envs/kohya/lib/python3.10/site-packages/diffusers/pipeline_utils.py", line 660, in from_pretrained
    class_obj = getattr(library, class_name)
AttributeError: module 'diffusers' has no attribute 'DEISMultistepScheduler'. Did you mean: 'DPMSolverMultistepScheduler'?

```
If I update the diffusers version to 0.14 , another error would raise:
```
TypeError: replace_unet_cross_attn_to_xformers.<locals>.forward_xformers() got an unexpected keyword argument 'encoder_hidden_states'
```

My env (within conda):

- CUDA 11.7
- PyTorch 1.13.1

**Comment by bmaltais** [comment]
Hi, is this from the latest release? Or the dev branch?

**Comment by BeautyyuYanli** [comment]
The main branch
