### ISSUE TITLE
save every n steps error on latest release, although no value is specified in gui

### ISSUE THREAD

**Issue by DoguCatto** [bmaltais/kohya_ss#751]
Folder 100_raiden: 13 images found
Folder 100_raiden: 1300 steps
max_train_steps = 1300
stop_text_encoder_training = 0
lr_warmup_steps = 0
Traceback (most recent call last):
  File "C:\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "C:\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\kohya\kohya_ss\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\kohya\kohya_ss\kohya_ss\lora_gui.py", line 749, in train_model
    run_cmd += run_cmd_advanced_training(
  File "C:\kohya\kohya_ss\kohya_ss\library\common_gui.py", line 1081, in run_cmd_advanced_training
    if int(kwargs.get('save_every_n_steps')) > 0
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by Trojaner** [comment]
Did you load config from a file? If yes, try removing the related save_every_n_steps line or setting it to 0 instead

**Comment by DoguCatto** [comment]
> Did you load config from a file? If yes, try removing the related save_every_n_steps line or setting it to 0 instead

I will try, thank u

**Comment by DoguCatto** [comment]
> Did you load config from a file? If yes, try removing the related save_every_n_steps line or setting it to 0 instead

it worked, for some reason the old json had some arguements that did not bode well with new release, removing them worked!!
