### ISSUE TITLE
TI errors.

### ISSUE THREAD

**Issue by DarkAlchy** [bmaltais/kohya_ss#76]
Traceback (most recent call last):
  File "D:\kohya_ss\train_textual_inversion.py", line 498, in <module>
    train(args)
  File "D:\kohya_ss\train_textual_inversion.py", line 260, in train
    train_util.patch_accelerator_for_fp16_training(accelerator)
  File "D:\kohya_ss\library\train_util.py", line 1345, in patch_accelerator_for_fp16_training
    org_unscale_grads = accelerator.scaler._unscale_grads_
AttributeError: 'NoneType' object has no attribute '_unscale_grads_'

I am getting a few errors when trying to do a TI training and this is just one of them.  Another is about -  File "D:\kohya_ss\train_textual_inversion.py", line 356, in train
    unwrap_model(text_encoder).get_input_embeddings().weight[index_no_updates] = orig_embeds_params[index_no_updates]
RuntimeError: Index put requires the source and destination dtypes match, got Half for the destination and Float for the source.

  File "D:\kohya_ss\train_textual_inversion.py", line 498, in <module>
    train(args)
  File "D:\kohya_ss\train_textual_inversion.py", line 260, in train
    train_util.patch_accelerator_for_fp16_training(accelerator)
  File "D:\kohya_ss\library\train_util.py", line 1345, in patch_accelerator_for_fp16_training
    org_unscale_grads = accelerator.scaler._unscale_grads_
AttributeError: 'NoneType' object has no attribute '_unscale_grads_'

**Comment by bmaltais** [comment]
It is quite possible this is a but with the new TI trainer code of kohya. Take note of the command used by the GUI and the error and open an issue on kohya's repo. I don't think this one is related to the GUI:

https://github.com/kohya-ss/sd-scripts/issues
