### ISSUE TITLE
How to merge with a lora when getting error 'AssertionError: weights shape mismatch merging v1 and v2, different dims?'

### ISSUE THREAD

**Issue by trihardseven** [bmaltais/kohya_ss#772]
I want to make a lora and merge with a specific older lora someone made. When I try to do it I get the error 
```
dim: [16], alpha: [16.0]
merging...
Traceback (most recent call last):
  File "N:\AI\LoRaS Folder\Kohya GUI Installation\kohya_ss\networks\merge_lora.py", line 243, in <module>
    merge(args)
  File "N:\AI\LoRaS Folder\Kohya GUI Installation\kohya_ss\networks\merge_lora.py", line 199, in merge
    state_dict = merge_lora_models(args.models, args.ratios, merge_dtype)
  File "N:\AI\LoRaS Folder\Kohya GUI Installation\kohya_ss\networks\merge_lora.py", line 155, in merge_lora_models
    merged_sd[key].size() == lora_sd[key].size()
AssertionError: weights shape mismatch merging v1 and v2, different dims? / 重みのサイズが合いません。v1とv2、または次元数の異なるモデルはマージできません
```

What settings should I make my own lora to be able to merge witht this one? Do I need an older version of the application?

**Comment by bmaltais** [comment]
I think it is telling you that you are trying to merge LoRAs intended for different checkpoint versions and the two don't mix... You probably have a SD1.5 LoRA that you try to merge with a SD 2.x LoRA and this can't be done. There are no way to merge the two.
