### ISSUE TITLE
RuntimeError: No such operator xformers::efficient_attention_forward_cutlass - did you forget to build xformers with `python setup.py develop`?

### ISSUE THREAD

**Issue by 24mlight** [bmaltais/kohya_ss#784]
`running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 1300
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 1300
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 1300
steps:   0%|                                                         | 0/1300 [00:00<?, ?it/s]epoch 1/1
Traceback (most recent call last):
  File "/data/7082/train_network.py", line 773, in <module>
    train(args)
  File "/data/7082/train_network.py", line 605, in train
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/data/7082/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/7082/venv/lib/python3.10/site-packages/accelerate/utils/operations.py", line 495, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/data/7082/venv/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "/data/7082/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 381, in forward
    sample, res_samples = downsample_block(
  File "/data/7082/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/7082/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 612, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
  File "/data/7082/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/7082/venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 216, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "/data/7082/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/7082/venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 484, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "/data/7082/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/7082/library/train_util.py", line 1845, in forward_xformers
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None)  # 最適なのを選んでくれる
  File "/data/7082/venv/lib/python3.10/site-packages/xformers/ops.py", line 865, in memory_efficient_attention
    return op.apply(query, key, value, attn_bias, p).reshape(output_shape)
  File "/data/7082/venv/lib/python3.10/site-packages/xformers/ops.py", line 319, in forward
    out, lse = cls.FORWARD_OPERATOR(
  File "/data/7082/venv/lib/python3.10/site-packages/xformers/ops.py", line 46, in no_such_operator
    raise RuntimeError(
RuntimeError: No such operator xformers::efficient_attention_forward_cutlass - did you forget to build xformers with `python setup.py develop`?
steps:   0%|                                                         | 0/1300 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/7082/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/data/7082/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/data/7082/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 923, in launch_command
    simple_launcher(args)
  File "/data/7082/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/data/7082/venv/bin/python', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=./sdmodels/anything-v4.5.ckpt', '--train_data_dir=./train_data/sanyueqi_1/image', '--resolution=512,512', '--output_dir=./train_data/sanyueqi_1/model', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=8', '--output_name=last', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=130', '--train_batch_size=1', '--max_train_steps=1300', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.
`

**Comment by 15ky3** [comment]
Are you running on Linux? You can try a newer version of xformers.

`pip install xformers==0.0.19` worked for me.

**Comment by Beyond5229** [comment]
> Are you running on Linux? You can try a newer version of xformers.
> 
> `pip install xformers==0.0.19` worked for me.

it‘s work for me
