### ISSUE TITLE
error when starting training 

### ISSUE THREAD

**Issue by demirklvc** [bmaltais/kohya_ss#817]
Traceback (most recent call last):
  File "C:\Users\RTX01\kohya_ss\train_db.py", line 477, in <module>
    train(args)
  File "C:\Users\RTX01\kohya_ss\train_db.py", line 66, in train
    train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.dataset_group)
  File "C:\Users\RTX01\kohya_ss\library\config_util.py", line 436, in generate_dataset_group_by_blueprint
    dataset.make_buckets()
  File "C:\Users\RTX01\kohya_ss\library\train_util.py", line 604, in make_buckets
    info.image_size = self.get_image_size(info.absolute_path)
  File "C:\Users\RTX01\kohya_ss\library\train_util.py", line 830, in get_image_size
    image = Image.open(image_path)
  File "C:\Users\RTX01\kohya_ss\venv\lib\site-packages\PIL\Image.py", line 3277, in open
    im = _open_core(fp, filename, prefix, formats)
  File "C:\Users\RTX01\kohya_ss\venv\lib\site-packages\PIL\Image.py", line 3263, in _open_core
    im = factory(fp, filename)
  File "C:\Users\RTX01\kohya_ss\venv\lib\site-packages\PIL\ImageFile.py", line 117, in __init__
    self._open()
  File "C:\Users\RTX01\kohya_ss\venv\lib\site-packages\PIL\PngImagePlugin.py", line 734, in _open
    s = self.png.call(cid, pos, length)
  File "C:\Users\RTX01\kohya_ss\venv\lib\site-packages\PIL\PngImagePlugin.py", line 203, in call
    return getattr(self, "chunk_" + cid.decode("ascii"))(pos, length)
  File "C:\Users\RTX01\kohya_ss\venv\lib\site-packages\PIL\PngImagePlugin.py", line 412, in chunk_iCCP
    icc_profile = _safe_zlib_decompress(s[i + 2 :])
  File "C:\Users\RTX01\kohya_ss\venv\lib\site-packages\PIL\PngImagePlugin.py", line 150, in _safe_zlib_decompress
    raise ValueError(msg)
ValueError: Decompressed Data Too Large
Traceback (most recent call last):
  File "C:\Users\RTX01\miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\RTX01\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\RTX01\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\RTX01\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\RTX01\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 923, in launch_command
    simple_launcher(args)
  File "C:\Users\RTX01\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\RTX01\\kohya_ss\\venv\\Scripts\\python.exe', 'train_db.py', '--no_token_padding', '--pretrained_model_name_or_path=C:\\Users\\RTX01\\Desktop\\v1-5-pruned-emaonly.ckpt', '--train_data_dir=C:\\Users\\RTX01\\Desktop\\NEUSYSTEM\\TRAININGORDNER\\training_1', '--reg_data_dir=C:\\Users\\RTX01\\Desktop\\NEUSYSTEM\\TRAININGORDNER\\reg', '--resolution=512,512', '--output_dir=C:\\Users\\RTX01\\Desktop\\outputkohya', '--stop_text_encoder_training=2912', '--output_name=sander', '--max_data_loader_n_workers=0', '--learning_rate=1e-06', '--lr_scheduler=constant', '--train_batch_size=10', '--max_train_steps=2912', '--save_every_n_epochs=2', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1

**Comment by Rojinski** [comment]
I have the exact same problem

**Comment by demirklvc** [comment]
> I have the exact same problem. I have a RTX-3070i and a recent i9 Cpu (32 Go ram). I had no problem with Kohya before.

i use an trx 3090 ti. few weeks ago ive used kohya withouth problems too.

**Comment by Rojinski** [comment]
Are you trying to train a model or a LORA?

**Comment by demirklvc** [comment]
yeah just ignore issues..

**Comment by demirklvc** [comment]
@bmaltais

**Comment by demirklvc** [comment]
closed because ..............

**Comment by maxenko** [comment]
Still getting this error.
