### ISSUE TITLE
"MemoryError" (not CUDA) crashes training (dreambooth)

### ISSUE THREAD

**Issue by official-elinas** [bmaltais/kohya_ss#82]
Specs
* 3090
* 32GB RAM
* i7-5820K
* Win10

Notes
* Everything was working minus the epoch pausing #36 
* Installed Cudnn
* Running CLI only

Error
```
Traceback (most recent call last):
  File "C:\Development\kohya_ss\train_db.py", line 337, in <module>
    train(args)
  File "C:\Development\kohya_ss\train_db.py", line 211, in train
    for step, batch in enumerate(train_dataloader):
  File "C:\Development\kohya_ss\venv\lib\site-packages\accelerate\data_loader.py", line 383, in __iter__
    next_batch = next(dataloader_iter)
  File "C:\Development\kohya_ss\venv\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "C:\Development\kohya_ss\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1356, in _next_data
    return self._process_data(data)
  File "C:\Development\kohya_ss\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1402, in _process_data
    data.reraise()
  File "C:\Development\kohya_ss\venv\lib\site-packages\torch\_utils.py", line 461, in reraise
    raise exception
MemoryError: Caught MemoryError in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "C:\Development\kohya_ss\venv\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop    data = fetcher.fetch(index)
  File "C:\Development\kohya_ss\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Development\kohya_ss\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Development\kohya_ss\library\train_util.py", line 419, in __getitem__
    img, face_cx, face_cy, face_w, face_h = self.load_image_with_face_info(image_info.absolute_path)
  File "C:\Development\kohya_ss\library\train_util.py", line 323, in load_image_with_face_info
    img = self.load_image(image_path)
  File "C:\Development\kohya_ss\library\train_util.py", line 270, in load_image
    img = np.array(image, np.uint8)
  File "C:\Development\kohya_ss\venv\lib\site-packages\PIL\Image.py", line 701, in __array_interface__
    new["data"] = self.tobytes()
  File "C:\Development\kohya_ss\venv\lib\site-packages\PIL\Image.py", line 779, in tobytes
    return b"".join(data)
MemoryError
```

Occurs when running the following for dreambooth
```
accelerate launch --num_cpu_threads_per_process=12 "train_db.py" --enable_bucket --gradient_checkpointing --no_token_padding --xformers --save_state --pretrained_model_name_or_path="C:\Development\stable-diffusion-webui\models\Stable-diffusion\animefull-final-pruned.ckpt" --train_data_dir="C:\Development\kohya_ss\db_models\xyz\img" --resolution=768,768 --output_dir="C:\Development\kohya_ss\db_models\xyz\model" --train_batch_size=4 --learning_rate=4e-06 --lr_scheduler=constant --lr_warmup_steps=0 --max_train_steps=1150 --xformers --mixed_precision=bf16 --save_every_n_epochs=100 --seed=69 --save_precision=float --logging_dir="C:\Development\kohya_ss\db_models\xyz\log" --caption_extension=.txt --stop_text_encoder_training=1150
```

**Comment by bmaltais** [comment]
I have run into super wrird thing when I tried to move to a fress build of Windows 11 22H2 on a new SSD. It still does not work like my current build. Something with the new Windows 11 22H2 release is causing trouble... so this might be related. Try installing the latest NVDia drivers and see if it help.

**Comment by official-elinas** [comment]
I am on the latest drivers and running windows 10. There doesn't seem to be a performance hit with lowering threads.
