### ISSUE TITLE
Reocurring Error Code When Training as well as Image Captioning - "returned non-zero exit status 1"

### ISSUE THREAD

**Issue by GodFistToad** [bmaltais/kohya_ss#828]
Folder 100_Ana6 : 2600 steps
max_train_steps = 2600
stop_text_encoder_training = 0
lr_warmup_steps = 0
accelerate launch --num_cpu_threads_per_process=2 "train_db.py" --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" --train_data_dir="D:/for stable/Ana6Lora/image" --resolution=512,512 --output_dir="D:/for stable/Ana6Lora/model" --logging_dir="D:/for stable/Ana6Lora/log" --save_model_as=safetensors --output_name="Ana" --max_data_loader_n_workers="1" --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="1" --max_train_steps="2600" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --seed="1234" --caption_extension=".txt" --optimizer_type="AdamW" --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --mem_eff_attn --gradient_checkpointing --xformers --bucket_no_upscale --sample_sampler=euler_a --sample_prompts="D:/for stable/Ana6Lora/model\sample\prompt.txt" --sample_every_n_steps="100"
prepare tokenizer
prepare images.
found directory D:\for stable\Ana6Lora\image\100_Ana6 contains 26 image files
2600 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: False

  [Subset 0 of Dataset 0]
    image_dir: "D:\for stable\Ana6Lora\image\100_Ana6"
    image_count: 26
    num_repeats: 100
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: Ana6
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|██████████████████████████████████████████████████████████████████████████████████| 26/26 [00:00<00:00, 77.92it/s]
prepare dataset
prepare accelerator
H:\kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:249: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
Using accelerator 0.15.0 or above.
loading model for process 0/1
load Diffusers pretrained models: runwayml/stable-diffusion-v1-5
safety_checker\model.safetensors not found
Fetching 19 files: 100%|████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 18987.80it/s]
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Replace CrossAttention.forward to use FlashAttention (not xformers)
prepare optimizer, data loader etc.
use AdamW optimizer | {}
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 2600
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 2600
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 1
  total train batch size (with parallel & distributed & accumulation) / 総バッチサイズ（並列学習、勾配合計含む）: 1
  gradient ccumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 2600
steps:   0%|                                                                                  | 0/2600 [00:00<?, ?it/s]
epoch 1/1
Traceback (most recent call last):
  File "H:\kohya\kohya_ss\train_db.py", line 477, in <module>
    train(args)
  File "H:\kohya\kohya_ss\train_db.py", line 259, in train
    for step, batch in enumerate(train_dataloader):
  File "H:\kohya\kohya_ss\venv\lib\site-packages\accelerate\data_loader.py", line 378, in __iter__
    current_batch = next(dataloader_iter)
  File "H:\kohya\kohya_ss\venv\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "H:\kohya\kohya_ss\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "H:\kohya\kohya_ss\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1402, in _process_data
    data.reraise()
  File "H:\kohya\kohya_ss\venv\lib\site-packages\torch\_utils.py", line 461, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "H:\kohya\kohya_ss\venv\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "H:\kohya\kohya_ss\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "H:\kohya\kohya_ss\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "H:\kohya\kohya_ss\venv\lib\site-packages\torch\utils\data\dataset.py", line 235, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "H:\kohya\kohya_ss\library\train_util.py", line 951, in __getitem__
    im_h == self.height and im_w == self.width
AssertionError: image size is small / 画像サイズが小さいようです: D:\for stable\Ana6Lora\image\100_Ana6\aka6artstyle-004.jpg

steps:   0%|                                                                                  | 0/2600 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "H:\kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "H:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "H:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 923, in launch_command
    simple_launcher(args)
  File "H:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['H:\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_db.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=D:/for stable/Ana6Lora/image', '--resolution=512,512', '--output_dir=D:/for stable/Ana6Lora/model', '--logging_dir=D:/for stable/Ana6Lora/log', '--save_model_as=safetensors', '--output_name=Ana', '--max_data_loader_n_workers=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=2600', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--optimizer_type=AdamW', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale', '--sample_sampler=euler_a', '--sample_prompts=D:/for stable/Ana6Lora/model\\sample\\prompt.txt', '--sample_every_n_steps=100']' returned non-zero exit status 1.

**Comment by GodFistToad** [comment]
j

**Comment by GodFistToad** [comment]
Error when captioning Images:

Captioning files in C:\Users\rayqu\Downloads\birme-512x512 (1)...
accelerate launch "./finetune/tag_images_by_wd14_tagger.py" --batch_size=8 --general_threshold=0.05 --character_threshold=0.05 --caption_extension=".txt" --model="SmilingWolf/wd-v1-4-convnextv2-tagger-v2" --max_data_loader_n_workers="2" --debug --remove_underscore --frequency_tags "C:\Users\rayqu\Downloads\birme-512x512 (1)"
2023-05-21 19:24:19.441060: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-05-21 19:24:19.483628: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
downloading wd14 tagger model from hf_hub. id: SmilingWolf/wd-v1-4-convnext-tagger-v2
H:\kohya\kohya_ss\venv\lib\site-packages\huggingface_hub\file_download.py:1076: FutureWarning: The `force_filename` parameter is deprecated as a new caching system, which keeps the filenames as they are on the Hub, is now in place.
  warnings.warn(
Downloading keras_metadata.pb: 100%|████████████████████████████████████████████████| 654k/654k [00:00<00:00, 5.95MB/s]
Downloading saved_model.pb: 100%|█████████████████████████████████████████████████| 5.71M/5.71M [00:00<00:00, 24.4MB/s]
Downloading (…)in/selected_tags.csv: 100%|██████████████████████████████████████████| 254k/254k [00:00<00:00, 2.62MB/s]
Downloading (…).data-00000-of-00001: 100%|██████████████████████████████████████████| 388M/388M [00:08<00:00, 45.0MB/s]
Downloading variables.index: 100%|████████████████████████████████████████████████| 22.6k/22.6k [00:00<00:00, 6.45MB/s]
2023-05-21 19:24:36.324559: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "H:\kohya\kohya_ss\finetune\tag_images_by_wd14_tagger.py", line 303, in <module>
    main(args)
  File "H:\kohya\kohya_ss\finetune\tag_images_by_wd14_tagger.py", line 99, in main
    model = load_model(args.model_dir)
  File "H:\kohya\kohya_ss\venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "H:\kohya\kohya_ss\venv\lib\site-packages\tensorflow\python\eager\context.py", line 622, in ensure_initialized
    context_handle = pywrap_tfe.TFE_NewContext(opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: cudaGetErrorString symbol not found.
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "H:\kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "H:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "H:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 923, in launch_command
    simple_launcher(args)
  File "H:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['H:\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', './finetune/tag_images_by_wd14_tagger.py', '--batch_size=8', '--general_threshold=0.05', '--character_threshold=0.05', '--caption_extension=.txt', '--model=SmilingWolf/wd-v1-4-convnextv2-tagger-v2', '--max_data_loader_n_workers=2', '--debug', '--remove_underscore', '--frequency_tags', 'C:\\Users\\rayqu\\Downloads\\birme-512x512 (1)']' returned non-zero exit status 1.
...captioning done

**Comment by pstadnyk** [comment]
Has anyone ever figured out a solve for this? Seem to have been an open issue for a while and I dont see a fix. I have to note that the same installation that worked once, did not work later (or since). Very frustrating TBH.
