### ISSUE TITLE
Error when training started

### ISSUE THREAD

**Issue by tomato-ga** [bmaltais/kohya_ss#829]
I started my first LoRA training.
When I started the training after completing the settings in the GUI,
I got the following error.

How can I resolve this?

Windows 11
Core i7 13700K
RTX 4090
DDR5 80GB 

```
[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [00:00<00:00, 6200.15it/s]
prepare dataset
prepare accelerator
Using accelerator 0.15.0 or above.
loading model for process 0/1
load StableDiffusion checkpoint: C:/Users/katud/OneDrive/ドキュメント/sd/stable-diffusion-webui/models/Stable-diffusion/chill_mix_03.safetensors
Traceback (most recent call last):
  File "C:\Users\katud\OneDrive\ドキュメント\kohya\kohya_ss\train_network.py", line 783, in <module>
    train(args)
  File "C:\Users\katud\OneDrive\ドキュメント\kohya\kohya_ss\train_network.py", line 146, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "C:\Users\katud\OneDrive\ドキュメント\kohya\kohya_ss\library\train_util.py", line 2968, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "C:\Users\katud\OneDrive\ドキュメント\kohya\kohya_ss\library\train_util.py", line 2934, in _load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, name_or_path, device)
  File "C:\Users\katud\OneDrive\ドキュメント\kohya\kohya_ss\library\model_util.py", line 863, in load_models_from_stable_diffusion_checkpoint
    info = unet.load_state_dict(converted_unet_checkpoint)
```

**Comment by tomato-ga** [comment]
I specified the Stable diffusion model and it started.

**Comment by CokeMango** [comment]
> I specified the Stable diffusion model and it started.

Can you explain how to specify the model.

**Comment by MikkelNielsen2** [comment]
> I specified the Stable diffusion model and it started.

What exactly do you mean? Could you tell how you did this?
