### ISSUE TITLE
Error while trying to train

### ISSUE THREAD

**Issue by MarekLeet** [bmaltais/kohya_ss#835]
Im getting this Error can someone please help mit how i can fix it?
Im using this lowvramsettings [config](https://mega.nz/file/zFNjlJAL#uB2uTAvcqLohSUzYBgtuBcAMt4Jnclg6jVV5YE4s0F4) with a nvidia quadro K2200

[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 3197.49it/s]
prepare dataset
prepare accelerator
C:\Users\xxx\Desktop\sd\koya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:249: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
Using accelerator 0.15.0 or above.
loading model for process 0/1
load Diffusers pretrained models: runwayml/stable-diffusion-v1-5
safety_checker\model.safetensors not found
Fetching 19 files: 100%|████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 18978.75it/s]
C:\Users\xxx\Desktop\sd\koya\kohya_ss\venv\lib\site-packages\safetensors\torch.py:98: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
CrossAttention.forward has been replaced to FlashAttention (not xformers)
[Dataset 0]
caching latents.
  0%|                                                                                           | 0/16 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\sd\koya\kohya_ss\train_network.py", line 783, in <module>
    train(args)
  File "C:\Users\xxx\Desktop\sd\koya\kohya_ss\train_network.py", line 157, in train
    train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
  File "C:\Users\xxx\Desktop\sd\koya\kohya_ss\library\train_util.py", line 1399, in cache_latents
    dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)
  File "C:\Users\xxx\Desktop\sd\koya\kohya_ss\library\train_util.py", line 812, in cache_latents
    latents = vae.encode(img_tensors).latent_dist.sample().to("cpu")
  File "C:\Users\xxx\Desktop\sd\koya\kohya_ss\venv\lib\site-packages\diffusers\models\vae.py", line 566, in encode
    h = self.encoder(x)
  File "C:\Users\xxx\Desktop\sd\koya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\xxx\Desktop\sd\koya\kohya_ss\venv\lib\site-packages\diffusers\models\vae.py", line 130, in forward
    sample = self.conv_in(sample)
  File "C:\Users\xxx\Desktop\sd\koya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\xxx\Desktop\sd\koya\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\xxx\Desktop\sd\koya\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\Desktop\sd\koya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxx\Desktop\sd\koya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\xxx\Desktop\sd\koya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 923, in launch_command
    simple_launcher(args)
  File "C:\Users\xxx\Desktop\sd\koya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\xxx\\Desktop\\sd\\koya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=C:/Users/xxx/Desktop/Neuer Ordner (6)/images', '--resolution=512,512', '--output_dir=C:/Users/xxx/Desktop/Neuer Ordner (6)/model', '--logging_dir=C:/Users/xxx/Desktop/Neuer Ordner (6)/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=128', '--output_name=Ichi', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=1600', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by MarekLeet** [comment]
That Error appears trying to train dreambooth and dreambooth LoRA

**Comment by MarekLeet** [comment]
After i deleted Python and reinstalled with PATH i started training again and this time i got more output:

Loading config...
Folder 100_Ichi: 16 images found
Folder 100_Ichi: 1600 steps
max_train_steps = 1600
stop_text_encoder_training = 0
lr_warmup_steps = 0
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" --train_data_dir="C:/Users/xxx/Desktop/Neuer Ordner (6)/images" --resolution=512,512 --output_dir="C:/Users/xxx/Desktop/Neuer Ordner (6)/model" --logging_dir="C:/Users/xxx/Desktop/Neuer Ordner (6)/log" --network_alpha="128" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-05 --unet_lr=0.0001 --network_dim=128 --output_name="Ichi" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="1" --max_train_steps="1600" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --seed="1234" --caption_extension=".txt" --cache_latents --optimizer_type="AdamW8bit" --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --mem_eff_attn --gradient_checkpointing --xformers --bucket_no_upscale
2023-05-24 10:31:55.499305: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-05-24 10:31:55.499420: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-05-24 10:31:59.933081: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
prepare tokenizer
Use DreamBooth method.
prepare images.
found directory C:\Users\xxx\Desktop\Neuer Ordner (6)\images\100_Ichi contains 16 image files
1600 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: False

  [Subset 0 of Dataset 0]
    image_dir: "C:\Users\xxx\Desktop\Neuer Ordner (6)\images\100_Ichi"
    image_count: 16
    num_repeats: 100
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: Ichi
    caption_extension: .txt


[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 2663.90it/s]
prepare dataset
prepare accelerator
C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\accelerator.py:249: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
Using accelerator 0.15.0 or above.
loading model for process 0/1
load Diffusers pretrained models: runwayml/stable-diffusion-v1-5
text_encoder\model.safetensors not found
Fetching 19 files: 100%|███████████████████████████████████████████████████████████████████████| 19/19 [00:00<?, ?it/s]
C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py:402: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(checkpoint_file, framework="pt") as f:
C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\safetensors\torch.py:98: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
CrossAttention.forward has been replaced to FlashAttention (not xformers)
[Dataset 0]
caching latents.
  0%|                                                                                           | 0/16 [00:00<?, ?it/s]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\xxx\Desktop\sd\koya\kohya_ss\train_network.py:783 in <module>                         │
│                                                                                                  │
│   780 │   args = parser.parse_args()                                                             │
│   781 │   args = train_util.read_config_from_file(args, parser)                                  │
│   782 │                                                                                          │
│ ❱ 783 │   train(args)                                                                            │
│   784                                                                                            │
│                                                                                                  │
│ C:\Users\xxx\Desktop\sd\koya\kohya_ss\train_network.py:157 in train                            │
│                                                                                                  │
│   154 │   │   vae.requires_grad_(False)                                                          │
│   155 │   │   vae.eval()                                                                         │
│   156 │   │   with torch.no_grad():                                                              │
│ ❱ 157 │   │   │   train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_laten   │
│   158 │   │   vae.to("cpu")                                                                      │
│   159 │   │   if torch.cuda.is_available():                                                      │
│   160 │   │   │   torch.cuda.empty_cache()                                                       │
│                                                                                                  │
│ C:\Users\xxx\Desktop\sd\koya\kohya_ss\library\train_util.py:1399 in cache_latents              │
│                                                                                                  │
│   1396 │   def cache_latents(self, vae, vae_batch_size=1, cache_to_disk=False, is_main_process=  │
│   1397 │   │   for i, dataset in enumerate(self.datasets):                                       │
│   1398 │   │   │   print(f"[Dataset {i}]")                                                       │
│ ❱ 1399 │   │   │   dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)    │
│   1400 │                                                                                         │
│   1401 │   def is_latent_cacheable(self) -> bool:                                                │
│   1402 │   │   return all([dataset.is_latent_cacheable() for dataset in self.datasets])          │
│                                                                                                  │
│ C:\Users\xxx\Desktop\sd\koya\kohya_ss\library\train_util.py:812 in cache_latents               │
│                                                                                                  │
│    809 │   │   │   img_tensors = torch.stack(images, dim=0)                                      │
│    810 │   │   │   img_tensors = img_tensors.to(device=vae.device, dtype=vae.dtype)              │
│    811 │   │   │                                                                                 │
│ ❱  812 │   │   │   latents = vae.encode(img_tensors).latent_dist.sample().to("cpu")              │
│    813 │   │   │                                                                                 │
│    814 │   │   │   for info, latent in zip(batch, latents):                                      │
│    815 │   │   │   │   if cache_to_disk:                                                         │
│                                                                                                  │
│ C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\vae.py │
│ :566 in encode                                                                                   │
│                                                                                                  │
│   563 │   │   self.use_slicing = False                                                           │
│   564 │                                                                                          │
│   565 │   def encode(self, x: torch.FloatTensor, return_dict: bool = True) -> AutoencoderKLOut   │
│ ❱ 566 │   │   h = self.encoder(x)                                                                │
│   567 │   │   moments = self.quant_conv(h)                                                       │
│   568 │   │   posterior = DiagonalGaussianDistribution(moments)                                  │
│   569                                                                                            │
│                                                                                                  │
│ C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module │
│ .py:1501 in _call_impl                                                                           │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\vae.py │
│ :130 in forward                                                                                  │
│                                                                                                  │
│   127 │                                                                                          │
│   128 │   def forward(self, x):                                                                  │
│   129 │   │   sample = x                                                                         │
│ ❱ 130 │   │   sample = self.conv_in(sample)                                                      │
│   131 │   │                                                                                      │
│   132 │   │   # down                                                                             │
│   133 │   │   for down_block in self.down_blocks:                                                │
│                                                                                                  │
│ C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module │
│ .py:1501 in _call_impl                                                                           │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\conv.p │
│ y:463 in forward                                                                                 │
│                                                                                                  │
│    460 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                         │
│    461 │                                                                                         │
│    462 │   def forward(self, input: Tensor) -> Tensor:                                           │
│ ❱  463 │   │   return self._conv_forward(input, self.weight, self.bias)                          │
│    464                                                                                           │
│    465 class Conv3d(_ConvNd):                                                                    │
│    466 │   __doc__ = r"""Applies a 3D convolution over an input signal composed of several inpu  │
│                                                                                                  │
│ C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\conv.p │
│ y:459 in _conv_forward                                                                           │
│                                                                                                  │
│    456 │   │   │   return F.conv2d(F.pad(input, self._reversed_padding_repeated_twice, mode=sel  │
│    457 │   │   │   │   │   │   │   weight, bias, self.stride,                                    │
│    458 │   │   │   │   │   │   │   _pair(0), self.dilation, self.groups)                         │
│ ❱  459 │   │   return F.conv2d(input, weight, bias, self.stride,                                 │
│    460 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                         │
│    461 │                                                                                         │
│    462 │   def forward(self, input: Tensor) -> Tensor:                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main   │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code              │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\acc │
│ elerate_cli.py:45 in main                                                                        │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\lau │
│ nch.py:923 in launch_command                                                                     │
│                                                                                                  │
│   920 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   921 │   │   sagemaker_launcher(defaults, args)                                                 │
│   922 │   else:                                                                                  │
│ ❱ 923 │   │   simple_launcher(args)                                                              │
│   924                                                                                            │
│   925                                                                                            │
│   926 def main():                                                                                │
│                                                                                                  │
│ C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\lau │
│ nch.py:579 in simple_launcher                                                                    │
│                                                                                                  │
│   576 │   process.wait()                                                                         │
│   577 │   if process.returncode != 0:                                                            │
│   578 │   │   if not args.quiet:                                                                 │
│ ❱ 579 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   580 │   │   else:                                                                              │
│   581 │   │   │   sys.exit(1)                                                                    │
│   582                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['C:\\Users\\xxx\\AppData\\Local\\Programs\\Python\\Python310\\python.exe',
'train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5',
'--train_data_dir=C:/Users/xxx/Desktop/Neuer Ordner (6)/images', '--resolution=512,512',
'--output_dir=C:/Users/xxx/Desktop/Neuer Ordner (6)/model', '--logging_dir=C:/Users/xxx/Desktop/Neuer Ordner
(6)/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora',
'--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=128', '--output_name=Ichi',
'--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1',
'--max_train_steps=1600', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234',
'--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1',
'--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers',
'--bucket_no_upscale']' returned non-zero exit status 1.
