### ISSUE TITLE
Linux setup.sh cuda installation issue - libcudnn_cnn_infer.so.8. Error

### ISSUE THREAD

**Issue by amrakm** [bmaltais/kohya_ss#849]
```

prepare accelerator
/home/<username>/repos/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator.py:249: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
Using accelerator 0.15.0 or above.
loading model for process 0/1
load StableDiffusion checkpoint: /home/<username>/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned.safetensors
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
CrossAttention.forward has been replaced to enable xformers.
[Dataset 0]
caching latents.
  0%|                                                                                                     | 0/628 [00:00<?, ?it/s]Could not load library libcudnn_cnn_infer.so.8. Error: libcuda.so: cannot open shared object file: No such file or directory
Please make sure libcudnn_cnn_infer.so.8 is in your library path!
Traceback (most recent call last):
  File "/home/<username>/repos/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/<username>/repos/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/<username>/repos/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 923, in launch_command
    simple_launcher(args)
  File "/home/<username>/repos/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/<username>/repos/kohya_ss/venv/bin/python', 'train_db.py', '--enable_bucket', '--pretrained_model_name_or_path=/home/<username>/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned.safetensors', '--train_data_dir=/home/<username>/data/lusthome/images', '--resolution=512,512', '--output_dir=/home/<username>/data/lusthome/model', '--logging_dir=/home/<username>/data/lusthome/log', '--save_model_as=safetensors', '--output_name=lusthome', '--max_data_loader_n_workers=0', '--learning_rate=1e-05', '--lr_scheduler=cosine', '--lr_warmup_steps=10048', '--train_batch_size=1', '--max_train_steps=100480', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' died with <Signals.SIGABRT: 6>.


```

**Comment by Flaegster** [comment]
i have the same issue
