### ISSUE TITLE
OSError: We couldn't connect to 'https://huggingface.co'

### ISSUE THREAD

**Issue by wlchn** [bmaltais/kohya_ss#855]
怎么办？遇到这个问题的应该都能看懂中文吧？不使用梯子的前提有解吗？（公司服务器禁止梯子）

error log:
```
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1253, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/train_network.py", line 783, in <module>
    train(args)
  File "/app/train_network.py", line 146, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "/app/library/train_util.py", line 3023, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "/app/library/train_util.py", line 2989, in _load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, name_or_path, device)
  File "/app/library/model_util.py", line 904, in load_models_from_stable_diffusion_checkpoint
    text_model = CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14").to(device)
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2079, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/configuration_clip.py", line 134, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 565, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 620, in _get_config_dict
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 443, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like openai/clip-vit-large-patch14 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 923, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
```

**Comment by bmaltais** [comment]
I have seen something similar in the past. The issue was on huggingface end. They had issues with some model access.

**Comment by wlchn** [comment]
> I have seen something similar in the past. The issue was on huggingface end. They had issues with some model access.

Yeah, It's not kohya_ss reason, but most likely because of network restrictions in my area for some reason,  I open the issue looking for some else who have solved the same problem that could help.

**Comment by wlchn** [comment]
I have resolved this issue by manually installing `openai/clip-vit-large-patch14`.

1. Open the huggingface repo: https://huggingface.co/openai/clip-vit-large-patch14/tree/main
Then download all the files to local.

2. scp all the files of the repo to server's folder(relative to kohya_ss dir):
kohya_ss/.cache/user/huggingface/hub/models--openai--clip-vit-large-patch14/snapshots/8d052a0f05efbaefbc9e8786ba291cfdf93e5bff

**Comment by QimingLee** [comment]
你好，我把clip按照您说的下载到cache路径下依然报之前的错误，请问需要在代码中修改什么路径么？
