### ISSUE TITLE
Script deleted my img folder and I can't get it back

### ISSUE THREAD

**Issue by hobolyra** [bmaltais/kohya_ss#872]
When using the folder utility to move images, this deleted my image folder and all the images/captions, said there was an error moving them, and now I can't get any of them back or find a way to restore them. 20k images and captions, all ready to go, gone.

It gave me this error:
```
Destination training directory is missing... can't perform the required task...
Removing existing directory C:/Stable_Diffusion/Training/DREAD\img/dreadtrain...
Copy C:/Stable_Diffusion/Training/DREAD/img/dreadtrain to C:/Stable_Diffusion/Training/DREAD\img/2_DREAD horror...
Traceback (most recent call last):
  File "C:\Stable_Diffusion\LoRa\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Stable_Diffusion\LoRa\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "C:\Stable_Diffusion\LoRa\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Stable_Diffusion\LoRa\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Stable_Diffusion\LoRa\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Stable_Diffusion\LoRa\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Stable_Diffusion\LoRa\kohya_ss\library\dreambooth_folder_creation_gui.py", line 69, in dreambooth_folder_preparation
    shutil.copytree(util_training_images_dir_input, training_dir)
  File "C:\Program Files\Python310\lib\shutil.py", line 557, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Stable_Diffusion/Training/DREAD/img/dreadtrain'
```

so it deleted the images before moving then couldn't move them, and now I'm freaking out because if I lost all of these I am screwed for this.

**Comment by bmaltais** [comment]
Really sorry about that. I think I will need to disable this tool to prevent such catastrophe. I guess the code is not failing cleanly and proceeding to delete things are not ready. AEG! Not good.
