### ISSUE TITLE
Error when trying to train

### ISSUE THREAD

**Issue by csNeptune** [bmaltais/kohya_ss#880]
Not sure what the issue is, I've tried disabling xformers, using different optimizers, and bf16.
```
Folder 20_Test: 43 images found
Folder 20_Test: 860 steps
Total steps: 860
Train batch size: 1
Gradient accumulation steps: 1.0
Epoch: 1
Regulatization factor: 1
max_train_steps (860 / 1 / 1.0 * 1 * 1) = 860
stop_text_encoder_training = 0
lr_warmup_steps = 86
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --enable_bucket --pretrained_model_name_or_path="C:/Users/roblo/Downloads/v1-5-pruned.safetensors" --train_data_dir="C:/Users/roblo/Downloads/ca/images/" --resolution=512,512 --output_dir="C:/Users/roblo/Downloads/ca/model" --logging_dir="C:/Users/roblo/Downloads/ca/logs" --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-05 --unet_lr=0.0001 --network_dim=32 --output_name="ca_sm" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="cosine" --lr_warmup_steps="86" --train_batch_size="1" --max_train_steps="860" --save_every_n_epochs="10" --mixed_precision="fp16" --save_precision="fp16" --cache_latents --optimizer_type="AdamW8bit" --max_data_loader_n_workers="0" --bucket_reso_steps=64 --xformers --bucket_no_upscale
2023-05-31 12:28:47.927533: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-05-31 12:28:47.927616: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-05-31 12:28:53.607409: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-05-31 12:28:53.607500: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.0+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.10.11 (you have 3.10.9)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
C:\Users\roblo\Downloads\kohya-demo\kohya_ss\venv\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\roblo\Downloads\kohya-demo\kohya_ss\venv\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
prepare tokenizer
Use DreamBooth method.
prepare images.
found directory C:\Users\roblo\Downloads\ca\images\20_Test contains 43 image files
860 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "C:\Users\roblo\Downloads\ca\images\20_Test"
    image_count: 43
    num_repeats: 20
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: Test
    caption_extension: .caption


[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 43/43 [00:00<00:00, 1802.85it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (320, 576), count: 20
bucket 1: resolution (384, 512), count: 140
bucket 2: resolution (384, 640), count: 700
mean ar error (without repeats): 0.02972222222222222
prepare accelerator
C:\Users\roblo\Downloads\kohya-demo\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:249: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
Using accelerator 0.15.0 or above.
loading model for process 0/1
load StableDiffusion checkpoint: C:/Users/roblo/Downloads/v1-5-pruned.safetensors
C:\Users\roblo\Downloads\kohya-demo\kohya_ss\venv\lib\site-packages\safetensors\torch.py:98: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
CrossAttention.forward has been replaced to enable xformers.
[Dataset 0]
caching latents.
  0%|                                                                                           | 0/43 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\roblo\Downloads\kohya-demo\kohya_ss\train_network.py", line 783, in <module>
    train(args)
  File "C:\Users\roblo\Downloads\kohya-demo\kohya_ss\train_network.py", line 157, in train
    train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
  File "C:\Users\roblo\Downloads\kohya-demo\kohya_ss\library\train_util.py", line 1399, in cache_latents
    dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)
  File "C:\Users\roblo\Downloads\kohya-demo\kohya_ss\library\train_util.py", line 812, in cache_latents
    latents = vae.encode(img_tensors).latent_dist.sample().to("cpu")
  File "C:\Users\roblo\Downloads\kohya-demo\kohya_ss\venv\lib\site-packages\diffusers\models\vae.py", line 566, in encode
    h = self.encoder(x)
  File "C:\Users\roblo\Downloads\kohya-demo\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\roblo\Downloads\kohya-demo\kohya_ss\venv\lib\site-packages\diffusers\models\vae.py", line 130, in forward
    sample = self.conv_in(sample)
  File "C:\Users\roblo\Downloads\kohya-demo\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\roblo\Downloads\kohya-demo\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\roblo\Downloads\kohya-demo\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
Traceback (most recent call last):
  File "C:\Users\roblo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\roblo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\roblo\Downloads\kohya-demo\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\roblo\Downloads\kohya-demo\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\roblo\Downloads\kohya-demo\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 923, in launch_command
    simple_launcher(args)
  File "C:\Users\roblo\Downloads\kohya-demo\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\roblo\\Downloads\\kohya-demo\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=C:/Users/roblo/Downloads/v1-5-pruned.safetensors', '--train_data_dir=C:/Users/roblo/Downloads/ca/images/', '--resolution=512,512', '--output_dir=C:/Users/roblo/Downloads/ca/model', '--logging_dir=C:/Users/roblo/Downloads/ca/logs', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=32', '--output_name=ca_sm', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=86', '--train_batch_size=1', '--max_train_steps=860', '--save_every_n_epochs=10', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.
```

**Comment by the0ckid82** [comment]
was having the same issues and then found this [RuntimeError: "slow_conv2d_cpu" not implemented for 'Half' #481](https://github.com/kohya-ss/sd-scripts/issues/481#issuecomment-1567427033) make sure that you are in the virtual environment when you run the commands, this is what worked for me
