### ISSUE TITLE
error for training dreambooth

### ISSUE THREAD

**Issue by Aresisok** [bmaltais/kohya_ss#899]
when i try to train i get this error
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "G:\Delta\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\Delta\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "G:\Delta\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\Delta\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\Delta\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "G:\Delta\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "G:\Delta\kohya_ss\dreambooth_gui.py", line 415, in train_model
    log.info(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1624, in _log
    self.handle(record)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 968, in handle
    self.emit(record)
  File "G:\Delta\kohya_ss\venv\lib\site-packages\rich\logging.py", line 128, in emit
    message = self.format(record)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 678, in format
    record.message = record.getMessage()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting

these are the settings 
{
  "pretrained_model_name_or_path": "G:/Delta/stable-diffusion-webui/models/Stable-diffusion/artiusV21_v21.safetensors",
  "v2": true,
  "v_parameterization": false,
  "logging_dir": "",
  "train_data_dir": "C:/Users/Admin/Downloads/New folder (42)",
  "reg_data_dir": "",
  "output_dir": "G:/Delta/stable-diffusion-webui/models/Stable-diffusion",
  "max_resolution": "768,768",
  "learning_rate": 1e-05,
  "lr_scheduler": "cosine",
  "lr_warmup": "10",
  "train_batch_size": 1,
  "epoch": 100,
  "save_every_n_epochs": 1,
  "mixed_precision": "fp16",
  "save_precision": "fp16",
  "seed": "",
  "num_cpu_threads_per_process": 2,
  "cache_latents": true,
  "cache_latents_to_disk": false,
  "caption_extension": "",
  "enable_bucket": true,
  "gradient_checkpointing": false,
  "full_fp16": false,
  "no_token_padding": false,
  "stop_text_encoder_training": 0,
  "xformers": true,
  "save_model_as": "safetensors",
  "shuffle_caption": false,
  "save_state": false,
  "resume": "",
  "prior_loss_weight": 1.0,
  "color_aug": false,
  "flip_aug": false,
  "clip_skip": "1",
  "vae": "",
  "output_name": "last",
  "max_token_length": "75",
  "max_train_epochs": "",
  "max_data_loader_n_workers": "0",
  "mem_eff_attn": false,
  "gradient_accumulation_steps": 1.0,
  "model_list": "custom",
  "keep_tokens": "0",
  "persistent_data_loader_workers": false,
  "bucket_no_upscale": true,
  "random_crop": false,
  "bucket_reso_steps": 64.0,
  "caption_dropout_every_n_epochs": 0.0,
  "caption_dropout_rate": 0,
  "optimizer": "AdamW8bit",
  "optimizer_args": "",
  "noise_offset_type": "Original",
  "noise_offset": 0.1,
  "adaptive_noise_scale": 0,
  "multires_noise_iterations": 0,
  "multires_noise_discount": 0,
  "sample_every_n_steps": 0,
  "sample_every_n_epochs": 0,
  "sample_sampler": "euler_a",
  "sample_prompts": "",
  "additional_parameters": "",
  "vae_batch_size": 0,
  "min_snr_gamma": 0,
  "weighted_captions": false,
  "save_every_n_steps": 0,
  "save_last_n_steps": 0,
  "save_last_n_steps_state": 0,
  "use_wandb": false,
  "wandb_api_key": ""
}

**Comment by bmaltais** [comment]
The latest v21.6.5 release should fix this issue. Sorry for the oversight.
