### ISSUE TITLE
Error while start training

### ISSUE THREAD

**Issue by Meowbotz-ll** [bmaltais/kohya_ss#930]
Error When Training

Traceback (most recent call last):
  File "C:\Users\Kienhong\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Kienhong\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya_ss\kohya_ss_gui\venv\Scripts\accelerate.exe\__main__.py", line 4, in <module>
  File "D:\kohya_ss\kohya_ss_gui\venv\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "D:\kohya_ss\kohya_ss_gui\venv\lib\site-packages\accelerate\accelerator.py", line 39, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "D:\kohya_ss\kohya_ss_gui\venv\lib\site-packages\accelerate\tracking.py", line 42, in <module>
    from torch.utils import tensorboard
  File "D:\kohya_ss\kohya_ss_gui\venv\lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "D:\kohya_ss\kohya_ss_gui\venv\lib\site-packages\torch\utils\tensorboard\writer.py", line 16, in <module>
    from ._embedding import (
  File "D:\kohya_ss\kohya_ss_gui\venv\lib\site-packages\torch\utils\tensorboard\_embedding.py", line 9, in <module>
    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, "join")
  File "D:\kohya_ss\kohya_ss_gui\venv\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
AttributeError: module 'tensorflow' has no attribute 'io'

setting is as below

  accelerate launch --num_cpu_threads_per_process=16 "train_network.py" --enable_bucket
                         --pretrained_model_name_or_path="D:/kohya_ss/sd-models/animefull-latest.ckpt"
                         --train_data_dir="D:/kohya_ss/train/Arcaea_Hikari_Fracture" --resolution=512,768
                         --output_dir="D:/kohya_ss/output" --logging_dir="D:/kohya_ss/logs" --network_alpha="16"
                         --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=7e-06
                         --unet_lr=6e-05 --network_dim=32 --output_name="Hikari_Fracture_2816_v2"
                         --lr_scheduler_num_cycles="1" --learning_rate="6e-05" --lr_scheduler="cosine_with_restarts"
                         --train_batch_size="1" --max_train_steps="2816" --save_every_n_epochs="1"
                         --mixed_precision="bf16" --save_precision="bf16" --caption_extension=".txt" --cache_latents
                         --optimizer_type="Lion" --max_data_loader_n_workers="5" --clip_skip=2 --bucket_reso_steps=64
                         --save_last_n_steps_state="8" --mem_eff_attn --shuffle_caption --xformers
                         --persistent_data_loader_workers --bucket_no_upscale --noise_offset=0.1 --wandb_api_key="False"

**Comment by bmaltais** [comment]
Try deleting the venv and re-install from scratch. Not sure why this is an issue with the new requirements.txt file... but re-installing the venv from scratch should fix it.

**Comment by Meowbotz-ll** [comment]
Fix it when reinstalling venv , thank you!
