### ISSUE TITLE
Error when enable [Persistent data loader] in Dreambooth

### ISSUE THREAD

**Issue by vindia9** [bmaltais/kohya_ss#955]
Hi, Bmaltais

Thank you for your script that allowed me to successfully train my own model !!!

When I was trying to adjust the training parameters, I found that if I checked [Persistent data loader] in Dreambooth, an error would pop up on the command line when I started training.

Below is the error log. If you require further information, please let me know.

```
================================================================================
CUDA SETUP: Loading binary D:\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit AdamW optimizer | {}
Traceback (most recent call last):
  File "D:\kohya_ss\train_db.py", line 482, in <module>
    train(args)
  File "D:\kohya_ss\train_db.py", line 166, in train
    train_dataloader = torch.utils.data.DataLoader(
  File "D:\kohya_ss\venv\lib\site-packages\torch\utils\data\dataloader.py", line 253, in __init__
    raise ValueError('persistent_workers option needs num_workers > 0')
ValueError: persistent_workers option needs num_workers > 0
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\kohya_ss\train_db.py:482 in <module>                                                          │
│                                                                                                  │
│   479 │   args = parser.parse_args()                                                             │
│   480 │   args = train_util.read_config_from_file(args, parser)                                  │
│   481 │                                                                                          │
│ ❱ 482 │   train(args)                                                                            │
│   483                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\train_db.py:166 in train                                                             │
│                                                                                                  │
│   163 │   # dataloaderを準備する                                                                   │
│   164 │   # DataLoaderのプロセス数：0はメインプロセスになる                                            │
│   165 │   n_workers = min(args.max_data_loader_n_workers, os.cpu_count() - 1)  # cpu_count-1     │
│ ❱ 166 │   train_dataloader = torch.utils.data.DataLoader(                                        │
│   167 │   │   train_dataset_group,                                                               │
│   168 │   │   batch_size=1,                                                                      │
│   169 │   │   shuffle=True,                                                                      │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\utils\data\dataloader.py:253 in __init__                │
│                                                                                                  │
│    250 │   │   │   raise ValueError('prefetch_factor option should be non-negative')             │
│    251 │   │                                                                                     │
│    252 │   │   if persistent_workers and num_workers == 0:                                       │
│ ❱  253 │   │   │   raise ValueError('persistent_workers option needs num_workers > 0')           │
│    254 │   │                                                                                     │
│    255 │   │   self.dataset = dataset                                                            │
│    256 │   │   self.num_workers = num_workers                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: persistent_workers option needs num_workers > 0
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\Vindia\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main  │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\Vindia\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code             │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main              │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in launch_command           │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in simple_launcher          │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by bmaltais** [comment]
Did you try setting the number of workers to something like 2? I think your configuration is set for 0 workers as stated in the error.

**Comment by vindia9** [comment]
> Did you try setting the number of workers to something like 2? I think your configuration is set for 0 workers as stated in the error.

Indeed, I had not set the worker parameter. Adjusting it to 1 or 2 allows for successful training initiation. Thank you!
