### ISSUE TITLE
An error occurred while using Lion8bit in Dreambooth.

### ISSUE THREAD

**Issue by vindia9** [bmaltais/kohya_ss#969]
Hi, bmaltais

With the same training parameters, everything works fine when using Lion; however, an error appears in the console when using Lion8bit, preventing the training process.

commit fa8fbe1 (HEAD -> master, tag: v21.7.6, origin/master, origin/HEAD)

This is the error log.

```
D:\kohya_ss\venv\lib\site-packages\bitsandbytes\cuda_setup\paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/127.0.0.1'), WindowsPath('http'), WindowsPath('7890')}
  warn(
D:\kohya_ss\venv\lib\site-packages\bitsandbytes\cuda_setup\paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('D')}
  warn(
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
D:\kohya_ss\venv\lib\site-packages\bitsandbytes\cuda_setup\paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary D:\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
Traceback (most recent call last):
  File "D:\kohya_ss\train_db.py", line 482, in <module>
    train(args)
  File "D:\kohya_ss\train_db.py", line 161, in train
    _, _, optimizer = train_util.get_optimizer(args, trainable_params)
  File "D:\kohya_ss\library\train_util.py", line 2656, in get_optimizer
    import bitsandbytes as bnb
  File "D:\kohya_ss\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "D:\kohya_ss\venv\lib\site-packages\bitsandbytes\autograd\_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "D:\kohya_ss\venv\lib\site-packages\bitsandbytes\functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "D:\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 41, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "D:\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 37, in get_instance
    cls._instance.initialize()
  File "D:\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 31, in initialize
    self.lib = ct.cdll.LoadLibrary(binary_path)
  File "C:\Users\Vindia\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Vindia\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'WindowsPath' is not iterable
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\kohya_ss\train_db.py:482 in <module>                                                          │
│                                                                                                  │
│   479 │   args = parser.parse_args()                                                             │
│   480 │   args = train_util.read_config_from_file(args, parser)                                  │
│   481 │                                                                                          │
│ ❱ 482 │   train(args)                                                                            │
│   483                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\train_db.py:161 in train                                                             │
│                                                                                                  │
│   158 │   else:                                                                                  │
│   159 │   │   trainable_params = unet.parameters()                                               │
│   160 │                                                                                          │
│ ❱ 161 │   _, _, optimizer = train_util.get_optimizer(args, trainable_params)                     │
│   162 │                                                                                          │
│   163 │   # dataloaderを準備する                                                                 │
│   164 │   # DataLoaderのプロセス数：0はメインプロセスになる                                      │
│                                                                                                  │
│ D:\kohya_ss\library\train_util.py:2656 in get_optimizer                                          │
│                                                                                                  │
│   2653 │                                                                                         │
│   2654 │   elif optimizer_type == "Lion8bit".lower():                                            │
│   2655 │   │   try:                                                                              │
│ ❱ 2656 │   │   │   import bitsandbytes as bnb                                                    │
│   2657 │   │   except ImportError:                                                               │
│   2658 │   │   │   raise ImportError("No bitsandbytes / bitsandbytesがインストールされていない   │
│   2659                                                                                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\bitsandbytes\__init__.py:6 in <module>                        │
│                                                                                                  │
│    3 # This source code is licensed under the MIT license found in the                           │
│    4 # LICENSE file in the root directory of this source tree.                                   │
│    5                                                                                             │
│ ❱  6 from .autograd._functions import (                                                          │
│    7 │   MatmulLtState,                                                                          │
│    8 │   bmm_cublas,                                                                             │
│    9 │   matmul,                                                                                 │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\bitsandbytes\autograd\_functions.py:5 in <module>             │
│                                                                                                  │
│     2 import warnings                                                                            │
│     3                                                                                            │
│     4 import torch                                                                               │
│ ❱   5 import bitsandbytes.functional as F                                                        │
│     6                                                                                            │
│     7 from dataclasses import dataclass                                                          │
│     8 from functools import reduce  # Required in Python 3                                       │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\bitsandbytes\functional.py:13 in <module>                     │
│                                                                                                  │
│     10 from typing import Tuple                                                                  │
│     11 from torch import Tensor                                                                  │
│     12                                                                                           │
│ ❱   13 from .cextension import COMPILED_WITH_CUDA, lib                                           │
│     14 from functools import reduce  # Required in Python 3                                      │
│     15                                                                                           │
│     16 # math.prod not compatible with python < 3.8                                              │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py:41 in <module>                     │
│                                                                                                  │
│   38 │   │   return cls._instance                                                                │
│   39                                                                                             │
│   40                                                                                             │
│ ❱ 41 lib = CUDALibrary_Singleton.get_instance().lib                                              │
│   42 try:                                                                                        │
│   43 │   lib.cadam32bit_g32                                                                      │
│   44 │   lib.get_context.restype = ct.c_void_p                                                   │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py:37 in get_instance                 │
│                                                                                                  │
│   34 │   def get_instance(cls):                                                                  │
│   35 │   │   if cls._instance is None:                                                           │
│   36 │   │   │   cls._instance = cls.__new__(cls)                                                │
│ ❱ 37 │   │   │   cls._instance.initialize()                                                      │
│   38 │   │   return cls._instance                                                                │
│   39                                                                                             │
│   40                                                                                             │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py:31 in initialize                   │
│                                                                                                  │
│   28 │   │   │   self.lib = ct.cdll.LoadLibrary(binary_path)                                     │
│   29 │   │   else:                                                                               │
│   30 │   │   │   print(f"CUDA SETUP: Loading binary {binary_path}...")                           │
│ ❱ 31 │   │   │   self.lib = ct.cdll.LoadLibrary(binary_path)                                     │
│   32 │                                                                                           │
│   33 │   @classmethod                                                                            │
│   34 │   def get_instance(cls):                                                                  │
│                                                                                                  │
│ C:\Users\Vindia\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py:452 in            │
│ LoadLibrary                                                                                      │
│                                                                                                  │
│   449 │   │   return getattr(self, name)                                                         │
│   450 │                                                                                          │
│   451 │   def LoadLibrary(self, name):                                                           │
│ ❱ 452 │   │   return self._dlltype(name)                                                         │
│   453 │                                                                                          │
│   454 │   __class_getitem__ = classmethod(_types.GenericAlias)                                   │
│   455                                                                                            │
│                                                                                                  │
│ C:\Users\Vindia\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py:364 in __init__   │
│                                                                                                  │
│   361 │   │   │   else:                                                                          │
│   362 │   │   │   │   import nt                                                                  │
│   363 │   │   │   │   mode = nt._LOAD_LIBRARY_SEARCH_DEFAULT_DIRS                                │
│ ❱ 364 │   │   │   │   if '/' in name or '\\' in name:                                            │
│   365 │   │   │   │   │   self._name = nt._getfullpathname(self._name)                           │
│   366 │   │   │   │   │   mode |= nt._LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR                           │
│   367                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: argument of type 'WindowsPath' is not iterable
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\Vindia\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main  │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\Vindia\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code             │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main              │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in launch_command           │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in simple_launcher          │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by bmaltais** [comment]
I don't think this is related to the GUI... one thing to test would be to switch to torch 1 if you use torch 2 or vice versa... Maybe it will work better with a different set of requirements and torch version?

**Comment by vindia9** [comment]
> I don't think this is related to the GUI... one thing to test would be to switch to torch 1 if you use torch 2 or vice versa... Maybe it will work better with a different set of requirements and torch version?


Thank you for your suggestion. I resolved the issue by deleting the entire kohya_ss code package, then cloning and reinstalling it, while still using Torch 2.0.1.
The tool you've developed is truly impressive.

May I inquire if parameters such as Text Encoder learning rate (lr), Unet learning rate, learning rate number of cycles, and learning rate power are planned to be incorporated into the Dreambooth checkpoint?
