### ISSUE TITLE
Error(s) in loading state_dict for UNet2DConditionMode

### ISSUE THREAD

**Issue by RicGdlc** [bmaltais/kohya_ss#98]
Traceback (most recent call last):
  File "C:\AI\kohya\kohya_ss\train_db.py", line 337, in <module>
    train(args)
  File "C:\AI\kohya\kohya_ss\train_db.py", line 62, in train
    text_encoder, vae, unet, load_stable_diffusion_format = train_util.load_target_model(args, weight_dtype)
  File "C:\AI\kohya\kohya_ss\library\train_util.py", line 1327, in load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, args.pretrained_model_name_or_path)
  File "C:\AI\kohya\kohya_ss\library\model_util.py", line 880, in load_models_from_stable_diffusion_checkpoint
    info = unet.load_state_dict(converted_unet_checkpoint)
  File "C:\AI\kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
        size mismatch for conv_in.weight: copying a param with shape torch.Size([320, 9, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\AI\kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\AI\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\AI\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\AI\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\AI\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_db.py', '--pretrained_model_name_or_path=C:\\AI\\stable-diffusion-webui\\models\\Stable-diffusion\\sd-v1-5-inpainting.ckpt', '--train_data_dir=C:\\Users\\ricgd\\Desktop\\StableDiffusion\\Newfolder\\training\\scar\\birme-512x512\\processed\\scar\\image', '--resolution=512,512', '--output_dir=C:\\Users\\ricgd\\Desktop\\StableDiffusion\\Newfolder\\training\\scar\\birme-512x512\\processed\\scar\\model', '--logging_dir=C:\\Users\\ricgd\\Desktop\\StableDiffusion\\Newfolder\\training\\scar\\birme-512x512\\processed\\scar\\log', '--save_model_as=ckpt', '--output_name=scarlett johansson', '--max_data_loader_n_workers=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--max_data_loader_n_workers=1', '--clip_skip=2', '--xformers', '--use_8bit_adam']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
Try with one of the quicksettings models... I think the issue is that the model you are trying to use is not compatible...
